### ISSUE TITLE
Geographic region selection in field report forms

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#1]
When filing a field report, DMIS allows you to select one or multiple countries. However, if there's an option to select a more specific location than country, without adding extra burden to the user, that would be a great improvement.

One option would be to connect to a geocoding API, which would allow the user to type in any location you would type into Google Maps (cities, specific addresses, etc), and for that service to translate that location into geographic data based on a set of matching dropdown options.

Two possibilities off the top of my head are Google and Mapbox. Both have API usage limits that would almost certainly put us in the free tiers, with the option to pay-as-you-go for unexpected usage bumps. For private usage though, Mapbox would categorize us as enterprise, which becomes prohibitively expensive.

@renecnielsen I don't know if you've looked into this type of service before, but I think it could really help our geographic data gathering abilities. Could you or someone on your team look into whether we could use Google's or another geocoding service (I don't know if Carto has one..) without incurring some massive fees?

**Comment by renecnielsen** [comment]
We have, I think, 12,000 geocodes per month through our current Carto subscription. See more [here](https://carto.com/location-data-services/geocoding/).

I've previously thought about simply using http://www.geonames.org (either hosting the gazetteer ourselves or paying their very fair fees). [Mapzen](https://mapzen.com/) could also be an option. I haven't compared prices and language support between vendors.

Seeing that we generally have <500 field reports per month, we should be good regardless of our choice. Same holds if we include text searches in appeals and DREFs.

For information, we often look at "affected areas" (generally admin areas), and there can be multiple per report/appeal/DREF. So no street level geocodes should be needed.

@dalekunce, @SimonbJohnson, @guipizzini, any thoughts?

**Comment by dereklieu** [comment]
Since you've already got the carto subscription, I think it makes sense to go ahead with that. This is an easy thing to switch out should we need to.

**Comment by SimonbJohnson** [comment]
One aspect to be aware of is that unless there are large place names mentioned (though quite likely I think) it may be difficult to geocode locations.  For program with the BRC is usually takes quite a lot of effort for smaller locations, due to different spellings, incorrect spellings, locations not in geocoder etc.  Most IM products are also usually aggregated by to the cluster approved admin boundaries.

**Comment by dereklieu** [comment]
Not in scope for now and has been moving in a different direction with the implementation of sub-country admin levels.
