### ISSUE TITLE
Country 3W Data export

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1001]
Country page 3w data csv export.

**Comment by frozenhelium** [comment]
@lauripynnonen Can you provide the list of columns in order for the CSV?

**Comment by lauripynnonen** [comment]
I believe the list of columns should match the form that was used to fill it, and the order could also be the same. So 

Country | Region/Province | Operation Type | Programme Type | Project Name | Primary Sector | Tags | Start Date | End Date | Budget | Status | Targeted Males | Targeted Females | Targeted Others | Targeted Total | Reached Males | Reached Females | Reached Others | Reached Total |

 @LukeCaley do you have an opinion on this one?

**Comment by lauripynnonen** [comment]
Testing with Argentina: [projects-export-1585310569098.xlsx](https://github.com/IFRCGo/go-frontend/files/4393397/projects-export-1585310569098.xlsx)
- The exported csv has numeric headers before the real headers, is this intentional? 
- Country-wide region comes out empty 
- Reached others field comes out twice, (reached total is named reached others)
- reached others comes out empty
- targeted others comes out empty
- could we add 
   - Supporting NS after Region/Province

**Comment by frozenhelium** [comment]
@lauripynnonen All fixed! Could you verify?

**Comment by lauripynnonen** [comment]
Looks good!
