### ISSUE TITLE
COVID-1 // Adapt Field Report for epidemic response

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1004]
**Problem**
Field reports do not currently have data fields which are appropriate for an epidemic emergency.  for example "no. of injured" not "no. of confirmed cases".  This is resulting in confusion for National Societies and unreliable data capture.

**Proposed solution**
The field report structure to be replicated in terms of the four steps for data entry.  Option to submit epi field report alongside the option of early warning and normal field reports.  The data fields to be collected would then change (these to be proposed by Health colleagues). 

**Alternatives considered**
The Field Report is current

**Additional context**
*Add any other context or screenshots about the feature request here.*
The field report is currently being used by NS to report COVID-19 preparedness and response actions.  Likely to increase in the coming days and weeks.

**Where does the data come from and how is it maintained?**
This is National Society reported data.  The field report varies in detail and frequency depending on NS. 

**Should there be any restrictions around viewing or updating information related to this feature**
*any considerations around permissions e.g. public vs only logged-in RCRC users should be able to see this*

**Links to documentation**
*wireframes, detailed requirements, user stories/UATs, external API documentation etc.*

**Comment by batpad** [comment]
Ideally, we can do this as described, as another "Type" of Field Report, in addition to Event and Early Warning.

It would be great to get an outline of the differences for the `Epidemic` type of field report as soon as possible, to help figure out what backend / data structure changes might be required. Also, as we discuss, to just verify whether the data still fits within the existing structure of a `Field Report` with a different type, or if we need an entirely different data model for `Epidemic Report` or so.

Assuming that we are able to do this with another "type" on the field report, we would need to:

 - Add `EPI` as another type in the form fields definition: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/field-report-constants.js#L526
 - Take care of places in the code that assumes there to be only two types of field report (check all conditionals).
 - Make any changes to the backend as required for new fields, etc.
 - For new fields, make sure all the steps are followed to ensure correct validation and loading of the fields on the frontend.
 - Ensure to check all frontend views of Field Report data, especially the field-report.js view to ensure they handle the additional `EPI` type correctly.

**Comment by LukeCaley** [comment]
Indeed, the desired behaviour is for there to be another 'type' of field report which refers to epidemic.  The "Field Reports” fields need to change when the user selects “Epidemic”, e.g. 
Injured, Missing, Displaced become “Confirmed cases”, “Probable cases”, and “Suspected cases” followed by “Affected” and “Dead”.

**Below feedback from IFRC Health Informatics (Roxanne Moore) on desired changes to fields:**

![Field Reports - 1  Context](https://user-images.githubusercontent.com/7791954/76791531-6a6b7e00-67c1-11ea-9f76-f45d533ab172.png)

![Field Reports - 2  Situation](https://user-images.githubusercontent.com/7791954/76791539-6e979b80-67c1-11ea-857b-c98775b95f68.png)

![Field Reports - 3  Actions](https://user-images.githubusercontent.com/7791954/76791558-75bea980-67c1-11ea-8d6f-1c7bd6e1b79a.png)

![Field Reports - 4  Response](https://user-images.githubusercontent.com/7791954/76791566-7a835d80-67c1-11ea-81d4-560a66f5f897.png)

**Comment by LukeCaley** [comment]
Suggest @yellowumbrella-design to create wireframe mock-ups on the basis of the above for rapid feedback from other colleagues.

**Comment by LukeCaley** [comment]
As discussed with @mmusori and @yellowumbrella-design we would only seek to wireframe the field changes highlighted in pink at this stage.  All prior changes to the field report structure involved wider consultation with users and would follow the same process here.  

Following production of wireframes, we will share the epi field report structure with COVID-19 cell colleagues to check if:
- this works for the unique requirements of a pandemic, i.e. an emergency which is both global and domestic in nature
- information requirements for COVID-19 to support potential funding decision-making processes which might be tied to the submission of this information and activity monitoring processes

**Comment by yellowumbrella-design** [comment]
Hi everyone, the latest Epi wires: https://invis.io/FXWI5D4TAD2#/409814227_8-2-1_GO_Epi_FieldReports_1 (PW: IFRC)

**Comment by LukeCaley** [comment]
Agreed process on daily GO call (20/03):

- [ ] @mmusori to review and add comments and send with email to @nanometrenat for wider consultation across COVID-19 team with noon CET 23/03 deadline
- [ ] @mmusori @nanometrenat & @LukeCaley to process comments on CET 23/03 and clarify instructions for redesign
- [ ] @yellowumbrella-design to incorporate suggestions and handoff to 
- [ ] @batpad for implementation
- [ ] @batpad to provide time estimate to staging on 24/01 daily call

**Comment by nanometrenat** [comment]
Hi @batpad I have just been looking at the Field Reports via the API (need to programmatically extract some).  I can't see a field to tell me what type of Field Report it is - can you please add a field to the API response?  At the moment the only way I can tell if it's Early Warning vs Normal is by looking at whether the fields "imminent_dref" and "forecast_based_action" exist.

Note - *IF* there are Actions Taken by the National Society or Govt (i.e. tickboxes ticked) then I can see what field report types those actions can potentially relate to ("actions taken" / "actions" / "field_report_types") but if no Actions Taken ticked then no mention of type anywhere.

Would greatly appreciate being able to access this field.  We may wish to show type onscreen also?

**Comment by necoline** [comment]
@nanometrenat I moved your comment to a separate [ticket](#1062) since that should be easily addressed in isolation

**Comment by necoline** [comment]
I wanted to log a point that came up in a previous conversation regarding the first few steps in the field report. 

> An epidemic is a type of disaster that will only ever be an event - never an early warning. So if an epidemic is selected under `disaster type` it should automatically select event.

Considering this relationship between this disaster type and event category, I would recommend moving the selection of disaster type to be before early warning/event selection. The reason being is that the relationship between the event and disaster type is a cascading decision tree and right now the parent is buried a few steps below the child. This creates an unintuitive UX flow but also limits the extensibility of this logic. I imagine down the road, we might add other disaster types that can only be events so planning for this now could eliminate extra work down the road.


_Noting that I removed @batpad as an assignee since I'll be jumping on the implementation of this issue._

**Comment by mmusori** [comment]
Just a documentation of the key decisions on the Epi Field Report. 	
1.The work for the Epi field report is accurately portrayed in this wireframe.
2.	The drop down mean should have “Field Report” and “Informal Update”. 
3.	Auto generate a title that is editable. The tile is based on Country, Region, Disaster type and date. 
4.	In Disaster type if Epidemic is selected then the form changes to the Epidemic field report form as outlined in the wireframe. 
5.	New tab called Report Version. This will allow users to distinguish between a first report and updates of the evolving situation. Clicking first report will result in the continuation with the usual first report format. 
 
6.	If “Update Report” is selected, then  the search for existing emergency moves up and is made prominent (as in wireframe). The title is populated based on the selected emergency. The title is editable.
7.	National Society Requests International Assistance shall become a mandatory field. 
8.	On Actions taken the wireframe has incorporated the changes requested by the health team.

**Comment by mmusori** [comment]
> I wanted to log a point that came up in a previous conversation regarding the first few steps in the field report.
> 
> > An epidemic is a type of disaster that will only ever be an event - never an early warning. So if an epidemic is selected under `disaster type` it should automatically select event.
> 
> Considering this relationship between this disaster type and event category, I would recommend moving the selection of disaster type to be before early warning/event selection. Seeing as the relationship between the event and disaster type is a cascading decision tree, we don't want to bury the parent (disaster type ) under the child (event/early warning). I hope this explanation makes sense. Essentially, we don't want to give the user a false option as an initial step in the form.
> 
> Making this change also aid extensibility. I imagine down the road, we might add other disaster types that can only be events so optimizing this now could eliminate extra work later.
> 
> _Noting that I removed @batpad as an assignee since I'll be jumping on the implementation of this issue._

The Report type is actually the Parent. The need for the flow described above does break the logic.

**Comment by necoline** [comment]
Notes from a voice call on this decision:
- It is preferred to have the event type remain above the disaster type as reflected in the wireframes. 
- if the user selects 'epidemic` as a disaster type, the event type should change (if not already selected) to be `event` and disabled

**Comment by necoline** [comment]
Sorry, I clicked the wrong button. I didn't mean to close the ticket

**Comment by yellowumbrella-design** [comment]
Suggested UI recommendations for field reports in general. Let us know your thoughts and we can updated + add to Zeplin.

V1 - old red
![8 1 1_GO_FieldReports_1 1-9](https://user-images.githubusercontent.com/60006476/78398390-4bf3e800-75f3-11ea-981a-52cdd6ae7776.png)

V2 - new red
![8 1 1_GO_FieldReports_1 1-9 - RED032](https://user-images.githubusercontent.com/60006476/78398431-5e6e2180-75f3-11ea-8dd0-cc653c62205a.png)

**Comment by karitotp** [comment]
From https://github.com/IFRCGo/go-frontend/pull/1074#issuecomment-608590977 the frontend QA:

- **In context page:** 

The order of the forms, titles and some texts does not match with the design. For example  "Affected Country and Province / Region*" should go just above of "Disaster Type *" and "Report Emergency Title" should go after "Disaster type"

![context](https://user-images.githubusercontent.com/11504548/78608839-2bac6f00-7827-11ea-8037-bb05708a836f.png)

- **In Situation page:** 

Need to fix some titles and texts, also is need to add some letters (the blue ones in the screenshot).
In the Source Details section are missing a "Upload" button and a text field.

![situation](https://user-images.githubusercontent.com/11504548/78609258-f7857e00-7827-11ea-9427-df4e0362e0a6.png)

- **In Actions page:** 

Need to fix some texts and add the section of HEALTH and GENERAL where the screenshot show.

![Actions](https://user-images.githubusercontent.com/11504548/78609832-349e4000-7829-11ea-82b3-2c5f838c9f50.png)

![Selection_004](https://user-images.githubusercontent.com/11504548/78610196-f6555080-7829-11ea-8e35-9c1d1418635f.png)
_Missing section on the page_

**Comment by batpad** [comment]
Surge Testing URL: https://github.com/IFRCGo/go-frontend/issues/1004

**Comment by mmusori** [comment]
Additional information for UX design and Dev team @necoline .
Some changes below for the the epi field report to consider. 

Context
 ![image](https://user-images.githubusercontent.com/7780809/78914680-0c158080-7a8b-11ea-9676-66f9d44a5804.png)

Can we change the guidance in the event of an Epi field report.  If possible, it should read, “ Please edit this title by replacing “Epidemic” with the name of the specific disease” The dev team needs to take note of this feature . 

Situation
 
![image](https://user-images.githubusercontent.com/7780809/78914766-2e0f0300-7a8b-11ea-89f2-e1a131a8f67d.png)

In discussion with health this field will no longer be mandatory . Since uploading documents is a new feature the dev team need to know that the expected functionality is that documents will be uploaded if available and they need to go to the emergency page as attachments under “Response documents”.

**Comment by nanometrenat** [comment]
Hi all, just looking at Field Reports in https://ifrc-go-feature-1004-epi-field-report.surge.sh/reports/new - I can see that some changes have been split out into separate ticket #1095 but just want to check that the other bugs mentioned above are being fixed?
In particular:
* Actions page - currently says "Early Action Taken by other RCRC Movement" but it's not an Early Action so this label is incorrect - should be "Actions taken by any other RCRC Movement actors" as per "normal" event field report.  Similarly need to remove "Red Cross" from the top label (National Society)

Logging a separate ticket re the display of the submitted Field Report

**Comment by nanometrenat** [comment]
Hi all, NOTE that the list of "Actions Taken" that will be implemented in Production will be different to the actions taken listed in the Wireframes.  This is after additional consultation with Health, CEA and Emergency Operations colleagues.  I am happy to do the new configuration directly via the back end once released to Production, but wanted to make sure you are aware that the differences to the wireframe (and list of Actions in testing) will be deliberate.

**Comment by nanometrenat** [comment]
Hi all, just looking at Field Reports in https://ifrc-go-feature-1004-epi-field-report.surge.sh/reports/new - I can see that some changes have been split out into separate ticket #1095 but just want to check that the other bugs mentioned above are being fixed?
In particular:

- Actions page - currently says "Early Action Taken by other RCRC Movement" but it's not an Early Action so this label is incorrect - should be "Actions taken by any other RCRC Movement actors" as per "normal" event field report.

FYI I have logged separate tickets re the display of the submitted Field Report and figures (#1096 and #1097)  Thanks a lot

**Comment by batpad** [comment]
> Actions page - currently says "Early Action Taken by other RCRC Movement" but it's not an Early Action so this label is incorrect - should be "Actions taken by any other RCRC Movement actors" as per "normal" event field report.

Thank you @nanometrenat . Noted. Will make sure this is fixed. Also thank you for #1096 and #1097, replying separately there.

**Comment by nanometrenat** [comment]
Above text still awaiting fix (says Early Action in staging right now) - @LukeCaley presumably to be carried forward.

**Comment by nanometrenat** [comment]
Closing as this is now working well in Prod - additional minor changes are logged as separate tickets.

Thanks a lot all for your work on this, hugely appreciated!
