### ISSUE TITLE
COVID-2 // Epi field report to appear on emergency (UX/UI page design of Field Report and Emergency pages)

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1005]
**Problem**
Visualisation of the field report data is currently sub-optimal.  With the addition of the epi field report (xref: https://github.com/IFRCGo/go-frontend/issues/1004) this would help to provide a quick reference overview for National Society domestic response to COVID-19

**Proposed solution**
Icons associated with the key data (cases, RC/RC actions) to provide a rapid situational overview.  All field report data would appear on the emergency object once associated.

**Where does the data come from and how is it maintained?**
Field report data.  This data is likely to age quickly so there is a need for a date created field and the option to remove the data once / if the National Society is instead wishing to create a live dashboard or other dynamically linked data viz. 

**Restrictions around viewing or updating information related to this feature**
There should be consideration of potential sensitivity of this data - therefore options to make some data visible depending on user e.g. public vs only logged-in RCRC users should be able to see this

**Comment by batpad** [comment]
> This data is likely to age quickly so there is a need for a date created field and the option to remove the data once / if the National Society is instead wishing to create a live dashboard or other dynamically linked data viz.

Can we expand on this a little bit, and perhaps create a separate ticket, as the ability to "turn off" field reports or so seems perhaps a bit separate from the overall issue of visualing field reports on the Emergency page?

Will wait for UX guidance before speccing this out further.

**Comment by LukeCaley** [comment]
There is already the option to 'turn off' or hide field report data on the emergency page in the back-end interface for GO.   
![COV-field-report-off](https://user-images.githubusercontent.com/7791954/76792139-a18e5f00-67c2-11ea-958f-ae51e09480e8.PNG)

The intention here is to provide a slightly more engaging result from the submission of field report data.  This will help NS to use GO as a means to provide a rapid overview of the situation, providing standardised design and icon sets.  The option to export the overview to be used outside of GO could also be considered.  For instance for NS which did not have graphic design capacities to share summary statistics and updates of their work with external audiences.

*Further design work required @yellowumbrella-design*

**Comment by yellowumbrella-design** [comment]
Latest Epi wireframes: https://invis.io/FXWI5D4TAD2#/409814227_8-2-1_GO_Epi_FieldReports_1 (PW: IFRC) Comments from Roxanne are yet to be reviewed and implemented

**Comment by LukeCaley** [comment]
Clarified that this relates to the emergency page @yellowumbrella-design to mock up designs for this.

**Comment by yellowumbrella-design** [comment]
https://invis.io/WAWP5JIDXZE#/412009430_4-4-3_GO_FieldReport-Epi_Page Wireframe for the Epi field report page. We are currently working on the UI to propose a visual solution.

**Comment by yellowumbrella-design** [comment]
https://invis.io/59WZFUYEFTM#/412675366_4-2-1_GO_Specific-Emergency_Epi Wireframe for the Emergency page

**Comment by nanometrenat** [comment]
My understanding of the conversation in the call just now is that this ticket is to have further design refinement and considered to be rolled up in UX/UI redesign work (rather than being tied to current Field Report).  Hence moving back to Needs Spec for now - thanks

**Comment by mariam-yu** [comment]
@nanometrenat We could probably move to Design column; that way we can tackle that first. This is regarding the updated fields, right?

**Comment by nanometrenat** [comment]
> @nanometrenat We could probably move to Design column; that way we can tackle that first. This is regarding the updated fields, right?

Yep, re the updated fields about figures, and the other comments on the wireframes re how to handle situations where not all the info is present (e.g. no regions selected).  Thanks!

**Comment by mariam-yu** [comment]
@mmusori and @nanometrenat The wireframes are updated:
Emergency page: https://invis.io/59WZFUYEFTM#/412675366_4-3-1_GO_Specific-Emergency_Epi
Field report page: https://invis.io/49WZCQ0QVTY#/412009430_4-5-3_GO_FieldReport-Epi_Page
COVID Em page: https://invis.io/D3X6LBXQ47A#/416656597_4-4-1_GO_Specific-Emergency_COVID

Can you please let me know if I'm missing anything?

**Comment by mmusori** [comment]
This will be part of the GO Phase 4.3 Emergency page update. A ticket has been opened https://github.com/IFRCGo/go-frontend/issues/1243
