### ISSUE TITLE
COVID-3 // Non-emergency related uploads 

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1006]
**Problem**
If a user wishes to upload a document to GO (IFRC blob storage) then it must be related to a emergency.  This is a problem for managing content which is not linked to the emergency.

This is an acute problem for content management of technical guidance for COVID, whereby the hyperlinks implemented through the workaround CMS are often pointing to various external cloud storage sites.

To note, as of 16 March, we have:

- 98 "Response documents" shared on GO (SitReps, surge - TORs, Staff Health, Health/RCCE guidance notes)
- 206 technical guidelines shared under GO "Additional Information" (NS institutional preparedness, business continuity, clinical guidelines, Quarantine, RCCE, etc.)

with the key challenges of

- Six languages (English, French, Spanish, Arabic, Russian, Portugese, Mandarin)
- Frequency of updates (e.g. Health & RCCE weekly updates, now every other week.  New evidence released daily impacting clinical guidelines.  Aim to replace with latest guidelines, but translation delays imply need to maintain historic versions)
- Implementation of naming conventions and organization structure

**Proposed solution**
Ability for independent upload of documents to IFRC blob storage through the GO back-end.

*To note, there may be considerations around permissions e.g. public vs only logged-in RCRC users*

**Comment by nanometrenat** [comment]
> whereby the hyperlinks implemented through the workaround CMS are often pointing to various external cloud storage sites.

FYI actually in many cases we have no-where to host them externally in the cloud - so we use the workaround of uploading to GO as a SitRep against an Emergency but then immediately deleting the sitrep (while keeping a note of the URL).  Then copy that URL as a link in the technical guidance.

**Comment by LukeCaley** [comment]
Assuming we have enough information in the above to move this to the To-Do pile.  @batpad to assign.

**Comment by nanometrenat** [comment]
Closing - the current workaround is to use IFRCSharing and to link from GO to there.  Not ideal, but don't need to build any functionality in GO for this now.
