### ISSUE TITLE
COVID-4 // Link to reference materials

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1007]
**Problem?**
As COVID-19 is a global domestic emergency, we need a way to reflect global reference on domestic emergency pages.  This will help to ensure alignment and easy reference for National Societies.

**Proposed solution**
Global IFRC reference materials, predominantly hyperlinks but also potentially other types of documentation, reflected on COVID-19 emergency pages through some form of visual clue, e.g. accordion banner, which appears across all national emergency pages.

**Alternatives considered**
There may be better ways to achieve visibility of IFRC global reference materials.  For instance, a global banner could be placed on every page on the site.  Alternatives include 

**Screenshot of current IFRC global reference**
![COV-snip](https://user-images.githubusercontent.com/7791954/76706500-34a69680-66e8-11ea-828c-66fa2a7ad6bc.PNG)

**To note:** *The reference material is maintained manually and is an issue in and of itself to be logged!*

**Comment by batpad** [comment]
It would be great to decide whether this is something that will be "site-wide", or whether this is something we specifically need to add data models for -- i.e. maybe have a `GlobalResponse` model where one can add content to it -- and then be able to associate individual emergencies with being part of a `Global Response` and then linking those emergencies, etc.

Probably good to let UX guide the implementation here.

**Comment by LukeCaley** [comment]
This is the first, and I very much hope the last, time we have had a global domestic response during the lifespan of GO.  Indeed in living memory.  However there are other instances of multi-country response which did not come under one appeal, for instance in a migration scenario, e.g. https://go.ifrc.org/emergencies/3122#details and https://go.ifrc.org/emergencies/3495#additional-info.

Agreed that overarching UX should inform this approach.

**Comment by LukeCaley** [comment]
Ref discussion on the daily call 20/03:

- Need is for easy site-wide navigation to COVID-19 global operational page from anywhere across the site
- Requirement is due to the likely development of multiple operational pages at national level which is great and to be encouraged, but also linking this back to the global page for reference materials and global overview dashboards etc
- Unlikely to need to do this systematically - more of a one-off unless pandemics become the norm!  but potential to use same approach to link other multi-country emergencies, e.g. cross-border migration
- There might be a simple quick fix (global site-wide banner) and longer term (banner only applied to specific pages, e.g. national COVID pages link to global COVID page using some kind of back-end config)

@yellowumbrella-design for design suggestions and @batpad for estimates and feasibility

**Comment by yellowumbrella-design** [comment]
![1 0 0 - Home_Banner5](https://user-images.githubusercontent.com/60006476/78019702-6a868480-7350-11ea-89b0-a10602037431.png)

**Comment by yellowumbrella-design** [comment]
https://invis.io/Q7WNPZ9PD9Y#/411605624_1-0-0_-_Home_Banner (remember new password)

**Comment by mzslezak** [comment]
> https://invis.io/Q7WNPZ9PD9Y#/411605624_1-0-0_-_Home_Banner (remember new password)
> 
> We can make it sticky for extra reinforcement, but I feel it may make it too dominant (unless that's what you want).

can you pls resend the new password you mention to mark@rivannastrategy.com?

**Comment by LukeCaley** [comment]
Non-sticky is fine and most simple to implement I would expect.  For the text, please use 

> COVID-19 global situational information and technical guidance available `here`

Thanks @yellowumbrella-design

**Comment by yellowumbrella-design** [comment]
Updated red header: https://projects.invisionapp.com/share/Q7WNPZ9PD9Y#/screens/411605624_1-0-0_-_Home_Banner
+ hover style: https://projects.invisionapp.com/share/EBWNVRSK2NX#/screens/411668057_1-0-0_-_Home_Banner2_Hover (50% transparency on white over the red for the hover color).

**Comment by LukeCaley** [comment]
Thanks - looks good.  Assuming this is a relatively simple implementation - @batpad to share estimate and assign.

**Comment by batpad** [comment]
For now, this would be a static link to the Emergency page? i.e. we can just hard-code this, or would we want this text / and or link to be editable in the backend?

If this is a static link and we just keep it up for the duration of the crisis, or until this text / link is relevant, this should be a pretty light lift.

Tagging both @GregoryHorvath and @necoline here as I think they're probably best placed to implement. 

@yellowumbrella-design could you please share the new wireframes password in teams?

**Comment by LukeCaley** [comment]
We were initially thinking of something more clever such that if there are regional and country pages then there could be a link back to the global page to avoid duplication and pointing towards source material.  

However, given other priorities, we landed on just a timebound static link to be hard-coded on the banner.

Sent you the password in bilateral @batpad

**Comment by batpad** [comment]
Site-wide banner that links to COVID emergency page can be tested here: https://ifrc-go-feature-1007-covid-banner.surge.sh/

cc @karitotp

**Comment by LukeCaley** [comment]
@teklal to confirm UAT pass or not.

**Comment by karitotp** [comment]
The link works good!

When I do click in "here" on the banner, it opens in a different url https://go.ifrc.org/emergencies/3972#details, if I navigate in the different tabs in this same url, the banner is not longer displayed in the site, instead, the link to COVID emergency page appears in the highlighted operations as the first one https://go.ifrc.org/.

Is this the way how this will work when the user wants to revisit the Covid emergency page?

**Comment by teklal** [comment]
Could someone (@yellowumbrella-design @LukeCaley ?) clarify what the latest spec for the text on the banner should be?

As per @yellowumbrella-design comment https://github.com/IFRCGo/go-frontend/issues/1007#issuecomment-606695240 I understand that it should be as in these wireframes: https://projects.invisionapp.com/share/Q7WNPZ9PD9Y#/screens/411605624_1-0-0_-_Home_Banner i.e. "COVID-19 global situational information and technical guidance available here."

Currently on staging the banner is as in screenshot of an older comment https://github.com/IFRCGo/go-frontend/issues/1007#issuecomment-606558412

Should this be updated to be as here https://projects.invisionapp.com/share/Q7WNPZ9PD9Y#/screens/411605624_1-0-0_-_Home_Banner ?

**Comment by yellowumbrella-design** [comment]
@teklal https://invis.io/E3WPYZ2NBMS#/412204959_1-0-0_-_Home_-_RED_COVID should be the latest. The text came from Luke (you can see above in the thread).

**Comment by teklal** [comment]
Thanks @yellowumbrella-design for the quick response.
Based on this it seems the text currently on staging is based on the old wireframes and should be updated, @batpad fyi.

**Comment by teklal** [comment]
Text has been changed and is now as in the latest wireframes - hooray!

**Comment by nanometrenat** [comment]
@LukeCaley does the banner in Production now mean that this work is complete and the ticket can be closed?  Cheers
