### ISSUE TITLE
COVID-6 // Add tab and rename

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1009]
**Problem**
Users would like to add and rename tabs on Regional, Country and Emergency pages.  Currently there are differing numbers of pre-named and, to an extent, pre-populated tabs on each of these levels.  While this is true of the expanding range of data to be displayed for COVID-19, it is also true of regional and national pages.

**Proposed solution**
Users should be given the option to add a number of tabs (3 additional?) in order to provide them with flexibility to organise emergency, national and regional pages. 

**Alternatives considered**
The alternative might be to have an accordion style expansion based on different component areas.

Xref: https://github.com/IFRCGo/go-frontend/issues/855

*To note, there could be considerations around permissions for various tabs e.g. public vs only logged-in RCRC users able to see certain tabs*

![COV-snip-tabs](https://user-images.githubusercontent.com/7791954/76710804-b3143000-670a-11ea-827d-5d0c0387af93.PNG)

**Comment by batpad** [comment]
@LukeCaley I'm fairly confused with the intention here. Users would add a tab, give it a title .. and then be able to insert arbitrary content? Or choose where current data from the tabs goes? Or just rename existing tabs to something else, but continue showing the data they currently show?

We could possibly think of having a feature where a user can add an arbitrary "Tab", give it a "Title" and some "Content", and display these additional tabs on the page if they exist. Does that sound like what we're after?

@LukeCaley it would be really great to get better context of the use cases here to be able to better suggest a path forward.

**Comment by LukeCaley** [comment]
Thanks @batpad.  Indeed, this is "a feature where a user can add an arbitrary "Tab", give it a "Title" and some "Content", and display these additional tabs on the page if they exist".

One use case for an emergency might be https://go.ifrc.org/emergencies/3495#additional-info where this info might be found and organised more easily with tabs for `ops update` and `maps and graphics`.  

Another use case is for regional offices to be able to manage their information and specific requirements, for instance in the Americas where they have had to organise dashboards on KPIs, contact and office maps and a range of links into the same `additional-info` tab.

A further use case is for NS to add tabs dedicated to long-term emergency programmes, such as the Emergency Social Safety Net programme in Turkey, where the Turkish Red Crescent could dedicate a full tab to dashboards and other graphics.

**Comment by nanometrenat** [comment]
The other key thing would be to be able to hyperlink directly to that tab e.g. currently we are often sending this hyperlink out to ensure people see the Guidance docs: https://go.ifrc.org/emergencies/3972#additional-info (it would be even more ideal if we could hyperlink directly to the Guidance snippet, but know that would be tricky given configurability - though maybe each snippet could have a slug?)

**Comment by nanometrenat** [comment]
When testing, we will also need to bear https://github.com/IFRCGo/go-frontend/issues/1013 in mind

**Comment by necoline** [comment]
I am generally quite hesitant to make broad changes to the UI available to users. I my experience, this tends to get out of hand quite quickly - both from a data management perspective and a UI perspective.

Perhaps if I can get a bit more background on this request, I'll be able to put forward some more helpful suggestions. 


### From the backend perspective
I am assuming by users, we are referring to admin users adding tab categories on the backend, is this correct?

Are the additions made by these users something that is available for all other users to access or does each user get to create 3 additional tabs that they see when they login with their account?

What would the process look like to add read/write access to users on the backend? 
I imagine we will need a new set of tab data that relates to the unique country or region id that is then appended to the original tab list. 
I imagine this will additionally require continuous editing permission for the user and hopefully some sort of testing and content review process. 

@batpad Do you see any side effects for adding this type of specificity and edit-ability to the tabs? 

### From the UI perspective
Does this request arise from users needing better organizational tools for navigating to related activities on the platform or are we trying to find a simple way to offer additional tools to users that is not currently available on GO?
- _If its the former, would it suffice to add a 'Quick Links' tab where users add links to existing content, maybe with additional UI that provides clear division of content sections?_

What type of content will be available to add to a new tab? Will there be various types of data provided in the content section? If so, there will be varying complexity and potential side effects. 

If users are essentially taking on the role of determining what additional content is available on regional, country, and emergency pages, what checks do we put in place to make sure the content is unique (not repetitious) and relevant?

- Related to this, if users determine the content displayed in a tab, what checks should we have in place to ensure they are promoting the use of tools/or information as their purpose is intended (not publishing content in a way that might promote user anti-patterns)?

**Comment by nanometrenat** [comment]
Hi @necoline the problem is that major emergency pages (e.g. the COVID one) have a LOT of information on them - e.g. check out https://go.ifrc.org/emergencies/3972 Additional Info

At the moment I can't direct people directly to the Technical Guidance or to the Appeal Documents or to the epi Dashboard - I just have to _describe_ to them where stuff is on the page/tab.  And actually for COVID a lot of the MAIN resources are under "Additional Info" (whereas if going by the current tab title one would assume that the Additional Info is supplementary stuff rather than the key documents)

The same types of data (snippets, rich text, response docs) would be going into these tabs as go into the Additional Info + main page.

@batpad @LukeCaley had discussions around this and I think Sanjay thought it was feasible.

**Comment by necoline** [comment]
Thank you for the example, this feature is definitely feasible. The key motivations to my questions are to iron out underlying assumptions and highlight edge cases so we don't unintentionally create obstacles down the road for ourselves or the users. 

I think the simplest route to making tabs available would be to start with snippets.

On the frontend, I can append a list of optional tab names and map through the content with an id that corresponds with the tab. The more types of data, the more complex the feature. I will defer to weigh in on how it would change on the frontend till we have the backend scoped out a bit more.

@geohacker do you have thoughts on how to do this from the backend?

**Comment by LukeCaley** [comment]
@geohacker to add note on what to test and assign DevSeed QA team

**Comment by geohacker** [comment]
This can be tested here https://ifrc-go-feature-multiple-tabs.surge.sh/ 
These are the changes to expect and test:

* Custom tabs - when you edit an Event you'll see these custom tabs
![](https://user-images.githubusercontent.com/371666/78025045-fc08ed00-7376-11ea-8c74-f4ca63096168.png)
These titles can be edited. If you leave a title empty, that tab won't be displayed on the front-end.

* Assigning snippets to tabs
![](https://user-images.githubusercontent.com/371666/78025040-f90dfc80-7376-11ea-8a36-4071d52cdbcf.png)
In the snippets section, there's a `TAB` options list that now allows to select which tab this snippet should appear at. 

* Testing the front-end
Once the tabs named and snippets are associated, the front-end should have those tabs with correct snippets. 

@necoline @batpad I realised that the `Additional Graphics` text is hardcoded in snippets component and won't make sense for all the tabs. https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/emergencies/snippets.js#L21 thoughts?

**Comment by batpad** [comment]
@karitop would be great to have you test this.

**Comment by LukeCaley** [comment]
To note, this is only currently implemented for Emergency pages.  Once UAT complete and moved to PROD, @batpad to create a ticket for implementing this for Regional and Country pages.

**Comment by batpad** [comment]
@karitop I'm having some trouble assigning the issue to you for some reason - it would be great to test this. Please ask me or @geohacker for any clarifications on what needs to be tested here.

**Comment by karitotp** [comment]
> These are the changes to expect and test:

- [x] Custom tabs - when you edit an Event you'll see these custom tabs. These titles can be edited. If you leave a title empty, that tab won't be displayed on the front-end.

- [x] Assigning snippets to tabs. In the snippets section, there's a TAB options list that now allows to select which tab this snippet should appear at.

- [x] Testing the front-end. Once the tabs named and snippets are associated, the front-end should have those tabs with correct snippets.

@batpad @geohacker, all these are working correctly in emergency page.

**Comment by nanometrenat** [comment]
Hi team, I have been clicking round to have a quick look and sorry to report that I think there are still some gremlins here.

1. Grey Screens (intermittent)
2. Unexpected extra tabs sometimes (can't replicate reliably but have twice seen it)

I keep getting grey screens (not every single time, but a subset of times).  e.g. in this emergency I have named an extra tab but not put any snippets in it - mostly the page loads fine but not always.
https://dsgoproxyapp.azurewebsites.net/emergencies/3945#additional-information

Copied error code below, not sure whether there's anything relevant here.
`vendor-eb777ee34e.js:1 Warning: Failed prop type: Invalid prop `emergency` of type `string` supplied to `t`, expected `number`.
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in div (created by c)
    in c (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown
r @ vendor-eb777ee34e.js:1
s @ vendor-eb777ee34e.js:1
Te @ vendor-eb777ee34e.js:1
Ce @ vendor-eb777ee34e.js:1
l.render @ vendor-eb777ee34e.js:1
kA @ vendor-eb777ee34e.js:1
CA @ vendor-eb777ee34e.js:1
KA @ vendor-eb777ee34e.js:1
wb @ vendor-eb777ee34e.js:1
ib @ vendor-eb777ee34e.js:1
nb @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
Q_ @ vendor-eb777ee34e.js:1
Ht @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1  action GET_SURGE_ALERTS_INFLIGHT @ 23:51:24.485
vendor-eb777ee34e.js:1  action GET_PERSONNEL_INFLIGHT @ 23:51:24.496
vendor-eb777ee34e.js:1  action GET_SURGE_ALERTS_SUCCESS @ 23:51:25.248
vendor-eb777ee34e.js:1  action GET_EVENT_SNIPPETS_INFLIGHT @ 23:51:25.511
vendor-eb777ee34e.js:1 The above error occurred in the <Connect(t)> component:
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ vendor-eb777ee34e.js:1
yv @ vendor-eb777ee34e.js:1
Fv.r.callback @ vendor-eb777ee34e.js:1
sm @ vendor-eb777ee34e.js:1
fm @ vendor-eb777ee34e.js:1
cm @ vendor-eb777ee34e.js:1
Ev @ vendor-eb777ee34e.js:1
fb @ vendor-eb777ee34e.js:1
e @ vendor-eb777ee34e.js:1
g @ vendor-eb777ee34e.js:1
S @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
ub @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
L_ @ vendor-eb777ee34e.js:1
enqueueSetState @ vendor-eb777ee34e.js:1
P.setState @ vendor-eb777ee34e.js:1
l.onStateChange @ vendor-eb777ee34e.js:1
y @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
dispatch @ vendor-eb777ee34e.js:1
(anonymous) @ bundle-550c72cf47.js:1
Promise.then (async)
(anonymous) @ bundle-550c72cf47.js:1
(anonymous) @ vendor-eb777ee34e.js:1
_getPersonnel @ bundle-550c72cf47.js:1
value @ bundle-550c72cf47.js:1
value @ bundle-550c72cf47.js:1
Ev @ vendor-eb777ee34e.js:1
fb @ vendor-eb777ee34e.js:1
e @ vendor-eb777ee34e.js:1
g @ vendor-eb777ee34e.js:1
S @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
ub @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
Q_ @ vendor-eb777ee34e.js:1
Ht @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
Show 2 more frames
vendor-eb777ee34e.js:1  action GET_PERSONNEL_SUCCESS @ 23:51:25.552
vendor-eb777ee34e.js:1  action GET_PERSONNEL_FAILED @ 23:51:25.592
vendor-eb777ee34e.js:1  prev state {user: {…}, profile: {…}, countries: {…}, districts: {…}, systemAlertsReducer: {…}, …}
vendor-eb777ee34e.js:1  action     {type: "GET_PERSONNEL_FAILED", error: TypeError: Cannot read property 'results' of undefined
    at Function.mapToProps (https://dsgoprox…}`

@batpad @geohacker @LukeCaley @teklal

**Comment by geohacker** [comment]
@nanometrenat I tried this for a bit and couldn't replicate the grey screen or extra tabs other than the one added to the emergency. I also added a snippet to the additional tab and that worked as expected.

From the error you posted above, it looks like to be that a network request failed, causing a parse error (GET_PERSONNEL_FAILED). This could have been a network blip or a deployment in progress.

Could you try again and see if you are able to reproduce it?

**Comment by batpad** [comment]
@nanometrenat I, as well, just tried really hard to reproduce this but have been unable to.

**Comment by teklal** [comment]
Hi all, just tried opening the emergency in @nanometrenat's comment (https://dsgoproxyapp.azurewebsites.net/emergencies/3945#additional-information) and I also keep getting a blank page every now and then (not all the time and reloading the page makes it work again). This mostly happens when I click (quickly) on consecutively on the different tabs). I however get a different error:

```
Uncaught TypeError: Cannot read property 'results' of undefined
    at Function.mapToProps (bundle-550c72cf47.js:1)
    at s (vendor-eb777ee34e.js:1)
    at Function.s.mapToProps (vendor-eb777ee34e.js:1)
    at s (vendor-eb777ee34e.js:1)
    at vendor-eb777ee34e.js:1
    at Object.run (vendor-eb777ee34e.js:1)
    at u.l.initSelector (vendor-eb777ee34e.js:1)
    at new Connect(t) (vendor-eb777ee34e.js:1)
    at Fm (vendor-eb777ee34e.js:1)
    at CA (vendor-eb777ee34e.js:1)
vendor-eb777ee34e.js:1 The above error occurred in the <Connect(t)> component:
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1 Uncaught TypeError: Cannot read property 'results' of undefined
    at Function.mapToProps (bundle-550c72cf47.js:1)
    at s (vendor-eb777ee34e.js:1)
    at Function.s.mapToProps (vendor-eb777ee34e.js:1)
    at s (vendor-eb777ee34e.js:1)
    at vendor-eb777ee34e.js:1
    at Object.run (vendor-eb777ee34e.js:1)
    at u.l.initSelector (vendor-eb777ee34e.js:1)
    at new Connect(t) (vendor-eb777ee34e.js:1)
    at Fm (vendor-eb777ee34e.js:1)
    at CA (vendor-eb777ee34e.js:1)
```

and another time got this one:

```
vendor-eb777ee34e.js:1 Warning: Failed prop type: Invalid prop `emergency` of type `string` supplied to `t`, expected `number`.
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in div (created by c)
    in c (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown
r @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1  action GET_SURGE_ALERTS_INFLIGHT @ 10:23:14.598
vendor-eb777ee34e.js:1  action GET_PERSONNEL_INFLIGHT @ 10:23:14.602
vendor-eb777ee34e.js:1  action GET_EVENT_SNIPPETS_SUCCESS @ 10:23:14.646
vendor-eb777ee34e.js:1  action GET_SURGE_ALERTS_SUCCESS @ 10:23:15.421
vendor-eb777ee34e.js:1  action GET_EVENT_SNIPPETS_INFLIGHT @ 10:23:15.522
vendor-eb777ee34e.js:1 The above error occurred in the <Connect(t)> component:
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by nanometrenat** [comment]
Thanks @teklal - yes I am getting blank screens very often this morning as well.  And we are in two different countries/connections so think the problem is further up the way :)

Again, I don't know which errors are the relevant ones but here are my most recent console errors:
```
vendor-eb777ee34e.js:1  action GET_EVENT_SNIPPETS_INFLIGHT @ 10:28:35.559
vendor-eb777ee34e.js:1 Uncaught TypeError: Cannot read property 'results' of undefined
    at Function.mapToProps (bundle-550c72cf47.js:1)
    at s (vendor-eb777ee34e.js:1)
    at Function.s.mapToProps (vendor-eb777ee34e.js:1)
    at s (vendor-eb777ee34e.js:1)
    at vendor-eb777ee34e.js:1
    at Object.run (vendor-eb777ee34e.js:1)
    at u.l.initSelector (vendor-eb777ee34e.js:1)
    at new Connect(t) (vendor-eb777ee34e.js:1)
    at Fm (vendor-eb777ee34e.js:1)
    at CA (vendor-eb777ee34e.js:1)
(anonymous) @ bundle-550c72cf47.js:1
s @ vendor-eb777ee34e.js:1
s.mapToProps @ vendor-eb777ee34e.js:1
s @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
run @ vendor-eb777ee34e.js:1
l.initSelector @ vendor-eb777ee34e.js:1
Connect(t) @ vendor-eb777ee34e.js:1
Fm @ vendor-eb777ee34e.js:1
CA @ vendor-eb777ee34e.js:1
KA @ vendor-eb777ee34e.js:1
e @ vendor-eb777ee34e.js:1
g @ vendor-eb777ee34e.js:1
S @ vendor-eb777ee34e.js:1
wb @ vendor-eb777ee34e.js:1
ib @ vendor-eb777ee34e.js:1
nb @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
Q_ @ vendor-eb777ee34e.js:1
Ht @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1 The above error occurred in the <Connect(t)> component:
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in div (created by r)
    in r (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by i)
    in i (created by o)
    in o (created by t)
    in section (created by t)
    in main (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by withRouter(Connect(t)))
    in withRouter(Connect(t)) (created by t)
    in t
    in t
    in t (created by t)
    in t
    in i
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ vendor-eb777ee34e.js:1
yv @ vendor-eb777ee34e.js:1
Fv.r.callback @ vendor-eb777ee34e.js:1
sm @ vendor-eb777ee34e.js:1
fm @ vendor-eb777ee34e.js:1
cm @ vendor-eb777ee34e.js:1
Ev @ vendor-eb777ee34e.js:1
fb @ vendor-eb777ee34e.js:1
e @ vendor-eb777ee34e.js:1
g @ vendor-eb777ee34e.js:1
S @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
ub @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
Q_ @ vendor-eb777ee34e.js:1
Ht @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1 Uncaught TypeError: Cannot read property 'results' of undefined
    at Function.mapToProps (bundle-550c72cf47.js:1)
    at s (vendor-eb777ee34e.js:1)
    at Function.s.mapToProps (vendor-eb777ee34e.js:1)
    at s (vendor-eb777ee34e.js:1)
    at vendor-eb777ee34e.js:1
    at Object.run (vendor-eb777ee34e.js:1)
    at u.l.initSelector (vendor-eb777ee34e.js:1)
    at new Connect(t) (vendor-eb777ee34e.js:1)
    at Fm (vendor-eb777ee34e.js:1)
    at CA (vendor-eb777ee34e.js:1)
(anonymous) @ bundle-550c72cf47.js:1
s @ vendor-eb777ee34e.js:1
s.mapToProps @ vendor-eb777ee34e.js:1
s @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
run @ vendor-eb777ee34e.js:1
l.initSelector @ vendor-eb777ee34e.js:1
Connect(t) @ vendor-eb777ee34e.js:1
Fm @ vendor-eb777ee34e.js:1
CA @ vendor-eb777ee34e.js:1
KA @ vendor-eb777ee34e.js:1
e @ vendor-eb777ee34e.js:1
g @ vendor-eb777ee34e.js:1
S @ vendor-eb777ee34e.js:1
wb @ vendor-eb777ee34e.js:1
ib @ vendor-eb777ee34e.js:1
nb @ vendor-eb777ee34e.js:1
z_ @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
n.unstable_runWithPriority @ vendor-eb777ee34e.js:1
Bd @ vendor-eb777ee34e.js:1
Rd @ vendor-eb777ee34e.js:1
Id @ vendor-eb777ee34e.js:1
Q_ @ vendor-eb777ee34e.js:1
Ht @ vendor-eb777ee34e.js:1
(anonymous) @ vendor-eb777ee34e.js:1
vendor-eb777ee34e.js:1  action GET_EVENT_SNIPPETS_SUCCESS @ 10:28:38.381
```

**Comment by geohacker** [comment]
This is a strange one, I've been constantly hitting that page and clicking around to see if I get any error but nothing -- things work as expected. 

Some questions @nanometrenat @teklal:
* What countries are you both? So I can try a VPN and try loading the site in those countries
* Possible to record a gif/video of the screen while you are loading? You could use something like https://www.cockos.com/licecap/ to create gif.
* Can you share with us what you see in the Network tab of the console?

**Comment by teklal** [comment]
@geohacker: I'm in Luxemburg and Nat's in Switzerland.

I tried capturing the problem in the gif below. I started from a blank screen that I got and then reloaded the page and then clicked a few times and it happened again. Let me know if you need any further info.

![GOtabs](https://user-images.githubusercontent.com/52411237/79318391-380b8880-7f07-11ea-822f-e3259f43470b.gif)

**Comment by geohacker** [comment]
This should now be fixed in #1107.

**Comment by teklal** [comment]
Tested on the same link as in the morning and I'm not getting a blank page anymore, thanks!

**Comment by nanometrenat** [comment]
Moved to done as this was released a while back and is now being used in Production - @LukeCaley can you please close when happy?

I am just not sure whether you wanted any action re your comment in initial thread about setting visibility settings per tab?  But I'm guessing it was decided not to pursue that requirement in which case all is well.

(hilariously, I note that in the process of releasing this a while back all the URLs would've changed from /additional-info as they used to be to become /additional-information like the default is now ;) )

**Comment by LukeCaley** [comment]
Closing as working fine in PROD.  We can live with lack of visibility settings for now.
