### ISSUE TITLE
Field report form not working

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#101]
@guipizzini @renecnielsen I'm having trouble recreating the issue of the field report not working at:

https://dsgoproxyapp.azurewebsites.net/reports/new

Can you confirm that this issue still exists, and the steps needed to reproduce? Particularly useful would be whether or not entering specific fields causes this issue. Also, please include the browser and operating system you're testing on (note that IE11 support is still not done, cc #87

**Comment by guipizzini** [comment]
@dereklieu ran a test yesterday, it seems to be working now. And yes, IE11 still not done. I will leave it to you to close this one. Thanks

**Comment by guipizzini** [comment]
@dereklieu IE11 is now working. Great.

For the field reports there is a bug at the end, when submitting the final report we get the attached screenshot as an error.

![image001](https://user-images.githubusercontent.com/23258092/35152089-356c5be6-fd21-11e7-8d06-1b6e02891c4b.png)

**Comment by dereklieu** [comment]
Closing this as fixed.
