### ISSUE TITLE
COVID-8 // Rich-text editor

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1011]
**Problem**
Rich-text editor is not working well.  Some features, such as indented bullets, do not exist as an option in the Django inrterface back-end.  Others appear to work in the back-end but do not translate into front-end as desired.  Xref: https://github.com/IFRCGo/go-frontend/issues/931

**Solution**
In order to structure information using lists, bullets, etc, the rich-text editor to be enhanced across the application.

**Comment by batpad** [comment]
@LukeCaley could you help with highlighting all instances of the rich text editor in the backend that we are facing issues with?

This seems like mostly a matter of:

 - Verifying that the HTML being saved in the backend is being output correctly onto the frontend
 - Add CSS rules for all the HTML tags being allowed / added by the backend editor, and ensure it looks consistent on the frontend.

We should also generally do a bit of inspecting of the code generated by the rich text editor. Consider alternatives if needed - not sure if issues like this are related to code being generated by the rich text editor: https://github.com/IFRCGo/go-frontend/issues/999 - for now, let's focus on making sure the frontend CSS respects the styling rules and HTML generated by the rich text editor.

**Comment by LukeCaley** [comment]
Some examples contained in Xref: #931.  @teklal @nanometrenat will I'm sure have others. 

Issue is that there should not be any functionality (bullets, indents, etc) which appear as potential functions in the back-end only for them to fail to pull through to the front-end.

**Comment by batpad** [comment]
> Issue is that there should not be any functionality (bullets, indents, etc) which appear as potential functions in the back-end only for them to fail to pull through to the front-end.

:+1: this is something we can start working on right away.

**Comment by batpad** [comment]
+ Add Rich Text Editor for Snippets (I can create a separate issue for this if needed).

**Comment by nanometrenat** [comment]
And ideally audit trail so we can see what changes have been made to the Rich Text edits (at the moment we have that on Google Docs)

**Comment by LukeCaley** [comment]
In discussion with @nanometrenat we would also like the ability to select `notify` as an option when updating content.  So, for example, we might make small edits and not wish to spam everyone or be in the process of drafting the text and expect to publish and review before finally sending a notification email.  This option to `notify` should probably appear when users are saving their edits. 

This feature is basically a fix for the known limitations of GO for use as a CMS.

*@batpad thoughts on complexity?*

**Comment by batpad** [comment]
>  This option to notify should probably appear when users are saving their edits.

This would be more @GregoryHorvath's department to estimate how complex this might be in terms of tweaking the notification code to check if some variable like `should_notify` or so exists when the user is submitting forms. It seems reasonable to me. @LukeCaley can we have a separate ticket for this though?

**Comment by GregoryHorvath** [comment]
Altering Django's default RTE would be a bit complicated. The only help I could find by a quick search was a possible integration of [TinyMCE](https://www.tiny.cloud/docs/demo/full-featured/), which seems to be a subscription based product.

@LukeCaley If you meant by indented bullets that you should be able to indent lists into sub-lists, I just tried and I was able to do that (there seems to be sequence how you do it: first make a list, only then start to indent the necessary lines).

@batpad I'm wondering what would be the best solution here. A field like that would mean that until that checkbox is ticked on again, no-one will receive any notification about the changes on that record.

The main issue here would be that we're not sending notifications on the go (haha pun), but checking every 5 minutes if there were any changes/new records and notifying the subscribers in a bunch. So even if one would uncheck the `notify` box if they're not waiting to the next 5th or 10th minute to check it back for the future or something, it wouldn't do much. **This needs some brainstorming.**

**Comment by batpad** [comment]
> Altering Django's default RTE would be a bit complicated. The only help I could find by a quick search was a possible integration of TinyMCE, which seems to be a subscription based product.

Altering the existing RTE shouldn't be that bad, but I also do not think that we will need to.

> @LukeCaley If you meant by indented bullets that you should be able to indent lists into sub-lists, I just tried and I was able to do that (there seems to be sequence how you do it: first make a list, only then start to indent the necessary lines).

@GregoryHorvath I think the main problem here is just that the frontend CSS styling doesn't show the things that were edited in the RTE correctly on the frontend. Fixing that will mostly be a matter of making sure the CSS on the frontend correctly displays things like lists and other HTML elements output on the RTE.

@necoline I'm co-assigning this to you, let me know if this is something you'd be able to look into or if we should re-assign.

> The main issue here would be that we're not sending notifications on the go (haha pun), but checking every 5 minutes if there were any changes/new records and notifying the subscribers in a bunch. So even if one would uncheck the notify box if they're not waiting to the next 5th or 10th minute to check it back for the future or something, it wouldn't do much. This needs some brainstorming.

That is a very good point @GregoryHorvath . I have created a separate ticket for the notification issue: https://github.com/IFRCGo/go-api/issues/637 - I have assigned that to you, but let's use that ticket to discuss and figure out how we might implement this.

**Comment by GregoryHorvath** [comment]
@LukeCaley A PR (https://github.com/IFRCGo/go-frontend/pull/1068) is up for the indented lists, but other than that I couldn't find any discrepancies between the backend edited texts and the frontend ones. Did I miss something?

**Comment by LukeCaley** [comment]
@nanometrenat and @RFMoore to fill in other blocking issues currently encountered around the Rich Text Editor please

**Comment by nanometrenat** [comment]
Hi @GregoryHorvath thanks for looking into this - it's great if the indented lists are the only thing that needed to be added to make the RTE match the CSS.  To be honest I thought the links also don't show up well (only when hovered over, as no difference in font etc.) but that is up to UI peeps.  In any case if the CSS now supports indented lists then we can simplify the technical guidance publishing a little, hooray!  Thanks!

The Real Issue here is also that the Rich Text editor hasn't been rolled out to many places (for Emergencies a rich text editor is only available in the "Summary" box but we also need to be able to use the Rich Text Editor for Snippets e.g. Technical Guidance for COVID).  I think there was another ticket raised to roll out this capability to more places - will look for it and link.  Thanks

**Comment by nanometrenat** [comment]
@LukeCaley I can't find a ticket specifically around allowing us to use a GO Rich Text Editor to create the tech guidance section.  Did you log one (that I need to look harder for) or does one still need to be logged?  #999 alludes to it but is not its main point - cheers

**Comment by nanometrenat** [comment]
Note to self (not necessarily for right now), but this is a good example of why a RTE would be good for Field Reports:  https://go.ifrc.org/reports/12247 (this has a link that's not a link, and also a series of bullet points.

**Comment by batpad** [comment]
Just trying to re-focus this issue a bit to focus on fields where the Rich Text Editor exists on the backend, but the display on the frontend does not conform / look like what is input in the Rich Text Editor. The PR for this is here: https://github.com/IFRCGo/go-frontend/pull/1068 and we should ideally test this in isolation (i.e. does all the styling I apply to existing fields with the Rich Text Editor in the backend show up as expected when viewing a page on the frontend? )

There are, apart from this, several fields which do not have any rich text editing capabilities as of now, that we'd like to add rich text editing to.

For those, let's use this ticket: https://github.com/IFRCGo/go-frontend/issues/931 . If needed, we can split up that ticket further into fields in the Admin and fields in the Field Report forms.

**Comment by GregoryHorvath** [comment]
Deployed the changes to a surge URL and sent the link to @teklal via Teams (didn't want to put it out here since this is still public) so I move this ticket into the 'Ready for QA' section. It contains fixes to the list elements and links in those rich text areas on the frontend.

cc @LukeCaley @nanometrenat

**Comment by teklal** [comment]
Really cool to see this working!

So on the backend the only pages that I found having a field with rich text editing currently as an option were the 
- emergency pages / summary
- field reports / description (though usually there would be no need to go edit a field report on the backend)

Tested for both of these pages and this seems to work. The RTE in question may not be the best but at least all the editing it enables to do, does work.

There are some minor differences (mostly fonts) between the preview on the backend and the way it shows up on the frontend but nothing major.
![image](https://user-images.githubusercontent.com/52411237/78828093-76271a80-79e4-11ea-89fa-7c4b9903f822.png)

**Comment by teklal** [comment]
Ok, so the only problem here and not technically part of this ticket, if this ticket was meant to look at the backend only, is that if a user adds a link on the frontend when creating the field report to the field that has the RTE on the backend, the link does not show up as a link on the page generated from the field report.

**Comment by batpad** [comment]
>  is that if a user adds a link on the frontend when creating the field report to the field that has the RTE on the backend, the link does not show up as a link on the page generated from the field report.

This seems like a legitimate issue, and one that we should ideally fix as part of the field report submission. @teklal can we make a separate issue for this, since it is ideally a separate issue? :)

**Comment by nanometrenat** [comment]
@LukeCaley @GregoryHorvath am wondering if this ticket is staying open for a specific outstanding action/reason?
I think that https://github.com/IFRCGo/go-api/issues/670 covers the RTE snippets work Greg has has been doing.
https://github.com/IFRCGo/go-frontend/issues/931 was the one that was pulled from the Excel sheet into Github back in January, that may be able to be closed too and new clean tickets logged for any remaining work after 670 is released.

@mariam-yu noting that there are still some front-end places (in particular the Field Report) where Rich Text Editor will need to be put on the front end - but that would need to be a new ticket with appropriate consideration.  Same consideration for if any more back end functionality is pulled into front end in future.

cc @tovari  cheers

**Comment by GregoryHorvath** [comment]
@nanometrenat I think you're right and the original issue in the ticket was dealt with some time ago. I'd say this can be closed.

**Comment by nanometrenat** [comment]
Closing on the assumption that there has been a full rewrite of GO - if further work is required on rich text editing - or display of rich text on the front end - then new tickets will be logged with specifics.
