### ISSUE TITLE
COVID-9 // Section titles

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1012]
**Problem**
Sections on each emergency page are titled generically to allow for minimised manual input.  However it is frustrating when these generic titles are not appropriate or not providing sufficient explanation, e.g. "Additional information"

**Proposed solution**
An ability to either revise the title of an individual section for that specific emergency or to be able to create a sub-heading in the back-end to explain what the section is (or should) be providing in the way of information.

**Comment by batpad** [comment]
> or to be able to create a sub-heading in the back-end to explain what the section is (or should) be providing in the way of information.

@LukeCaley sorry I'm not sure I quite followed this bit. 

Is the first part a request to be able to change the titles of existing tabs on Emergency pages? Like, the user wants to call it `Global Overview` instead of `Additional Information` or something, just for that Emergency? But that tab would continue to show the same data that it currently does?

If that's the intention, we could think of making the default tab names overridable on a per-Emergency level in the backend. But I'm not sure I understood the request correctly.

**Comment by LukeCaley** [comment]
Thanks @batpad - this is not about naming of tabs but rather sections.

The COVID-19 https://go.ifrc.org/emergencies/3972#details page has `situational overview`, `alerts` & `field reports` etc.  Users have suggested that it would be valuable to provide an emergency specific sub-title to explain the content of the section.  

Therefore `situational overview` could have a date updated with indications of sources and frequency of updates; `alerts` could specify that the alerts are for the global COVID cell in Geneva as well as for IFRC regional offices; `field reports` could specify that these also refer to national emergency pages.

**Comment by batpad** [comment]
@LukeCaley thank you for the clarifications.

Is it possible to get a comprehensive list of all the subheadings that would be required? We can then go ahead with adding these fields to the backend, allowing the user to add custom subheadings for each of these.

And, once we have some UX guidance from @yellowumbrella-design, can work on adding these "subtitles" under the current headings on the Emergency page.

**Comment by yellowumbrella-design** [comment]
@LukeCaley I propose we go through the emergency page in our today's audit meeting and write down the improvements. We can then provide the updated wireframes to Sanjay.

**Comment by nanometrenat** [comment]
My current use case for these would be for the Global COVID-19 page, Field Reports section.  There are (correctly/should be) no Global field reports, but there are 90-odd field reports at a country level.  it would be useful if I could put a few words as a sub-heading to suggest people look at the field reports from each National Society.  This would of course depend on the Field Report section show/hide logic checking not just whether there are field reports against the emergency but also whether there is a subheading.  Many cheers!

**Comment by yellowumbrella-design** [comment]
![IFRC_UI_Situational](https://user-image@LukeCaley ithubusercontent.com/60006476/77415011-2597a680-6dc2-11ea-8b9a-01a1bd571af7.png)

@LukeCaley Does this solve the section headings challenge? We are proposing a dedicated text under the title line. Styles are on Zeplin.

**Comment by LukeCaley** [comment]
@yellowumbrella-design this looks good - essentially we would need a sub-heading text that would only appear and move section content down if text entered in the back-end.  This appears to do the trick from a design point of view.  Over to @batpad to assign this task.

**Comment by LukeCaley** [comment]
@batpad to split into front and back end tickets

**Comment by nanometrenat** [comment]
Additional potential requirement request for consideration
- is it possible to have direct hyperlinks to each section?  e.g. https://go.ifrc.org/emergencies/3972#appeal-documents (or something like that)?
In particular direct links to the Appeal Documents and Response Documents sections would be super-handy

I'm really often directing people to specific sections of the Emergency page, but currently have to say "go to https://go.ifrc.org/emergencies/3972#details then scroll down to Appeal Documents"
Be good if I could give them a link where the scrolling has already been done.

May not be viable but worth asking :)  thanks

**Comment by nanometrenat** [comment]
Closing this ticket as there have been many design updates since (custom tabs, GO rewrite etc) so think it's obsolete (Luke please re-open if I'm wrong about that)
