### ISSUE TITLE
COVID-11 // Emergency page contact organisation

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1014]
**Problem.**
It can be difficult to identify key contacts in an emergency when there are more than five.  

**Proposed solution**
New feature to organise the contact details more effectively through:

- ordering 
- sub-headings (e.g. Health or Africa Region)

![COV-snip-contacts](https://user-images.githubusercontent.com/7791954/76711224-44d16c80-670e-11ea-8cff-98baaf3bf72a.PNG)

**Comment by batpad** [comment]
This sounds good :+1: - will wait for UX guidance to spec further.

**Comment by yellowumbrella-design** [comment]
![IFRC_UI_Contacts-2](https://user-images.githubusercontent.com/60006476/77414902-fed97000-6dc1-11ea-88f4-862bc6274424.png)

UI suggestion for the contacts styling. The update is on Zeplin on the specs sheet.

**Comment by LukeCaley** [comment]
@yellowumbrella-design works for me. Over to @batpad to assign.

**Comment by LukeCaley** [comment]
Xref: https://github.com/IFRCGo/go-frontend/issues/1243#issuecomment-726262872

**Comment by maisa-yu** [comment]
Hey guys, here are the versions for Contact module, with subheadings and single/multiple contacts. 
This is the link to Zeplin:
https://zpl.io/VDEyWgJ

![GO Library 2](https://user-images.githubusercontent.com/64901386/99091578-60a84d80-25d0-11eb-9c9a-11f15f53fca8.png)

**Comment by mariam-yu** [comment]
@batpad Are you guys implementing these styles? Should we move this ticket to dev column? Thanks!

**Comment by karitotp** [comment]
The contacts organization on the page is according the design.

![Screenshot from 2021-01-06 14-50-46](https://user-images.githubusercontent.com/11504548/103813886-c93f0400-502e-11eb-9d97-04a7d87b35c4.png)

**Comment by GregoryHorvath** [comment]
@batpad Can you please refer this at the Pull Request or somewhere? Or was it ever merged into `develop`? I can't find this among the `master` <- `develop` Release PR commits but I may be blind: https://github.com/IFRCGo/go-frontend/pull/1827

cc @tovari
