### ISSUE TITLE
3W Aggregated visualization of regional data 

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1019]
Ability to see a regional view of activities (map and table)

**Comment by lauripynnonen** [comment]
@yellowumbrella-design  could you design this?

**Comment by lauripynnonen** [comment]
Based on our discussion this should be implemented as a tab on the region. 

The tab would have a similar map than the country 3W. 

Dropdowns on the top would allow a user to filter the content of both the map and the table beneath the map. The dropdowns would allow user to filter the viewed data based on the fields that have predefined list values (Operation Type, Programme Type, Sector, Status). 

Hovering over a country should show a summary of activities in that country based on the filters selected (number of planned, ongoing, completed activities, total budget, number of domestic, bilateral, multilateral projects, total targeted, total reached etc.). 

The table beneath the map should show country specific numbers based on the selected filters. (number of planned, ongoing, completed activities, total budget, number of domestic, bilateral, multilateral projects, total targeted, total reached etc.).

Clicking a country on that map would lead to the country 3W view.

**Comment by lauripynnonen** [comment]
@teklal is this how a Go user might like the regional view of 3W to work?

**Comment by lauripynnonen** [comment]
@guipizzini is the above regional view anything like a regional view you'd implement if you had the following data:
	- Reporting NS
	- Country & Region
	- Operation Type (Emergency Operation, Programme)
	- Programme Type (Domestic, Bilateral, Multilateral)
		○ IF Domestic Emergency Operation, identity linked Ongoing Emergency
		○ IF Domestic, Bilateral OR Multilateral Programme, select Disaster Type
		○ IF Bilateral Emergency Operation, (no additional info asked)
		○ IF Multilateral Emergency Operation, identify linked IFRC Emergency Operation
	- Project Name
	- Sector
	- Additional Tags (sub-sectors)
	- Start and End date
	- Budget
	- Status (Planned, Ongoing, Completed)
	- People targeted (TOTAL, male, female, other)
	- People reached (TOTAL, male, female, other)
- Visibility (public *default, identified users, IFRC Only
In addition, we could plan to pull information from the linked emergency operation (either IFRC operation or Emergency Operation from field report)

**Comment by yellowumbrella-design** [comment]
@lauripynnonen Took a stab at the 3W regional tab, but I have some questions: https://invis.io/YEWU44N45TW#/413302373_2-3_GO_3W

- You mentioned number of domestic projects, is this a type like multilateral and bilateral?
- All the information on this page is aggregated per country, right? Meaning we don't have any more details here per project.
- Can you share and example dataset that I can use that could be more realistic (for example, how many projects could Philippines have?)
- Are these projects or activities (for consistent lingo)
- How can we show the details of each project (e.g. start date, etc.) Do we want to find a way to show here or that's on the country level?
- What other content shall we display here besides the map and the table? Shall we add some summary graphs (e.g. top 5 countries with most projects, or top 5 contributing NS, or like the ones we have on the country page).
- Lastly, do we also need to display the supporting NS for each country, as that may be too much info for the table/map, given there may be many? What is the max number?

Thanks!

**Comment by lauripynnonen** [comment]
- Yes Domestic is a type like bilateral and multilateral
- That would make the most sense to me - having the activities grouped and aggregated to country level
- Mark is planning to use Bangladesh as a sample for the promotional video they are drafting for the launch of 3W. He can help by providing info on what kind of activities, how many actors are there operating at the same time and what kind of scale are the total budgets like. I'll notify him that you could work on the same country (if Bangladesh is OK)
- Activities
- I don't have a creative idea for this. We could categorize them into ongoing/planned/completed?
- Summary graphs sound excellent
- The supporting NS could potentially also be a top 5 thing?

**Comment by mzslezak** [comment]
Hi @yellowumbrella-design 

The wireframes look great, have everything we need. 

For scale are you looking for number of orders of magnitude? Total operations are commonly in the billions (for all humanitarian response in a disaster) so if we make the design include that, we are fine. Most will be in the 100 millions max. 

Johnny had created a design that we all liked here: https://www.figma.com/file/MXppouzuKGLTDtPTeTKH0N/IFRC-Data-vis-challenge?node-id=0%3A1

You have covered all elements except the Sankey. 

Can we include a Sankey? It would be a visual representation of the basic Who does What, Where data elements. 

Otherwise all looks good

**Comment by mzslezak** [comment]
The UN is also moving in the Sankey direction for Covid response 3w visualiation: https://reliefweb.int/report/philippines/philippines-covid-19-response-who-what-where-3w-23-march-2020

**Comment by yellowumbrella-design** [comment]
Thanks guys for your feedback and ideas.

@lauripynnonen just to build on the question, do we need more details for each country in the table, like which are the projects? Also, added some graphs on top as a summary information and top NS on the map to make it more actionable. The filters would affect that as well.

@mzslezak Added the Sankey graph on the bottom. Thinking it may become quite "fat" with data; so, may be a good idea to put it below to give it more space. Can you provide me with some example data once you have it? We can see how real numbers work with this structure.

Lastly, as mentioned in my email, let me know by when you may need the UI for the video, as we will need a bit more time to make the wires into GO shiny. Thanks!

https://invis.io/YEWU44N45TW#/413302373_2-3_GO_3W

**Comment by yellowumbrella-design** [comment]
@lauripynnonen and all, updated the wires: https://invis.io/YEWU44N45TW#/413302373_2-3_GO_3W Left some comments on the prototype for clarification.

Can you please clarify for me if there is a difference between project and an activity?

Also, still would love to get an idea of datasets to understand the scale, e.g. what are the min and max possible values for all the fields to understand whether this design can work. Thanks!

**Comment by lauripynnonen** [comment]
@yellowumbrella-design Thank you for the excellent wireframe and the replies to the comments! I added about 80 activities to the Asia-Pacific through bulk upload, so there should be  some test data. Let me know if there is something more I can do (like multiply the number of activities by 10?)

To my understanding in the context of 3w activity and project are in a sense synonyms. 

How do we proceed with this @frozenhelium? Would you be able to start the implementation based on the wireframes?

@yellowumbrella-design could you also take a stab at the global view of 3w on the emergency page as a module?

**Comment by frozenhelium** [comment]
@lauripynnonen We'll get the development started from this, cheers!

**Comment by yellowumbrella-design** [comment]
@lauripynnonen I suppose the data you added we can use on the country level for example, but you don't have on regional level, right? In any case, may be we can test that our directly in the staging. My question/concern though is about the scalability of the table underneath the map: https://invis.io/YEWU44N45TW#/413302373_2-3_GO_3W

Do you have any idea: 1 - how many projects can there be per country (max) and how many countries can have operations per region (max).

Questions to dev @frozenhelium could we have pagination within an accordion table?

Thanks!

**Comment by frozenhelium** [comment]
@yellowumbrella-design Yes, we can implement it with the accordion table and the pagination.

**Comment by frozenhelium** [comment]
@lauripynnonen So when aggregating the stats, should we only include the stat from the projects that use have permission to? i.e. if the user don't have access to the projects (ifrc-only, logged in user) that won't be reflected in their respective view (in charts and numbers) right?

**Comment by lauripynnonen** [comment]
@frozenhelium that is a good question. I guess to protect the user data that's what we have to do. It might be nice to have a disclaimer visible when data has been filtered out, for example with an asterisk after the sum and a hover text for the asterisk saying "some data not included due to user role" 
@teklal I need your wisdom here again - how does Go treat users with lower access to data, are they informed that they can't see everything?

**Comment by lauripynnonen** [comment]
> @lauripynnonen I suppose the data you added we can use on the country level for example, but you don't have on regional level, right? In any case, may be we can test that our directly in the staging. My question/concern though is about the scalability of the table underneath the map: https://invis.io/YEWU44N45TW#/413302373_2-3_GO_3W
> 
> Do you have any idea: 1 - how many projects can there be per country (max) and how many countries can have operations per region (max).
> 
> Questions to dev @frozenhelium could we have pagination within an accordion table?
> 
> Thanks!

I added regional data to Asia Pacific by adding about 80 activities to the region. I'm not a specialist in the number of activities, but I assume simultaneous active operations per country would be maximum in the tens, not hundreds. But with Africa having 54 countries we could still be talking about hundreds of active activities per region...

**Comment by frozenhelium** [comment]
Test link: https://tc-ifrc-go.surge.sh/regions/2#3w

**Comment by yellowumbrella-design** [comment]
@frozenhelium thanks! We put together a guiding UI. You don't have to worry about top part or general CSS (e.g. for buttons, etc.) for now, but this may guide with the new sections. Will be on Zeplin soon. https://invis.io/X9X1K2XEPTH#/415304299_2-3_GO_3W-4

**Comment by yellowumbrella-design** [comment]
@frozenhelium we probably would want to match some of the styles with what we currently have on GO (e.g. filter bar, tables with countries clickable, etc.). Also, as for the right side of the map, could we have the maps clickable too? plz let us know if you have questions, and good job!

**Comment by lauripynnonen** [comment]
@frozenhelium awesome job! Comments vs  the [InVisio design ](https://projects.invisionapp.com/share/K8R901UBXN4#/screens/414530877)

The NS With Ongoing Activities and Total Budget are reversed. Maybe for a reason, not sure
![image](https://user-images.githubusercontent.com/8285694/80376331-f3ce9f80-8899-11ea-81cb-d4b85210496a.png)

The Total Activities by Status is a bar chart titled Projects by Sector of Activity, however it shows statuses, not sectors. This could be a stack or pie chart
![image](https://user-images.githubusercontent.com/8285694/80376424-13fe5e80-889a-11ea-9ccb-ae4e32241536.png)

The order of items on the dropdowns on the map is odd. These could be alphabetical? 
![image](https://user-images.githubusercontent.com/8285694/80376500-30020000-889a-11ea-81b8-c3e75c1a12dc.png)

Where does the bar chart scale come from?
![image](https://user-images.githubusercontent.com/8285694/80376552-46a85700-889a-11ea-9999-162039c1d0d2.png)

Could the country name be a hyperlink to that country's 3W page? kinda like country name is a link on the emergency page if you click a country on the map? The country names on the list on the right could also be links
![image](https://user-images.githubusercontent.com/8285694/80377093-13b29300-889b-11ea-89c8-077251202ce6.png)

The sankey diagram is mad cool, no idea how you pulled that off. More comments in a bit!

**Comment by lauripynnonen** [comment]
Comments on Sankey (from Johnny):
- Sort each column most to least activities? Or even alphabetical to avoid bias to big orgs?
- only who’s doing what and what’s happening where.. Not possible to see who's doing here. Would this be possible? Maybe if the hover could go al the way through (from what to where)

Bug: Filtering by Supporting NS only shows one NS even if many are selected

**Comment by karitotp** [comment]
When I click over an activity in a country on the map, is shown two popups. This happen the first time that I click in the country and not happen in all of them but happen in most.

I get this only in the Asia Pacific Region https://tc-ifrc-go.surge.sh/regions/2#3w where there are many countries whit projects.

![Screenshot from 2020-04-27 16-39-07](https://user-images.githubusercontent.com/11504548/80428217-f38ccf00-88ae-11ea-80ea-fd8ee6de7d46.png)
