### ISSUE TITLE
3W Aggregated visualisation of Global data

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1020]
As per regional view, but global

**Comment by lauripynnonen** [comment]
@yellowumbrella-design  could you design this?

**Comment by lauripynnonen** [comment]
We agreed with Luke to not to make another map but to represent COVID related 3W activities on the COVID emergency dashboard. @yellowumbrella-design would you have time to visualize how this would look on the emergency dashboard?

**Comment by yellowumbrella-design** [comment]
@lauripynnonen are you speaking about the Home page or Emergencies page?

**Comment by lauripynnonen** [comment]
@LukeCaley I assume this is to be in the Emergencies page right?

**Comment by LukeCaley** [comment]
The idea would be to have this as an embedded snippet on the Global COVID-19 emergency page.  No need for @yellowumbrella-design to be designing this at this stage as @nanometrenat @lauripynnonen and @guipizzini taking this forward.

**Comment by lauripynnonen** [comment]
Ok so probably not closed yet, I'll reopen it

**Comment by lauripynnonen** [comment]
The idea would be to have this as an embedded snippet on an emergency page. 

The main required functionality for this would be to give users the ability to see activities related to certain emergency (e.g. all 3w activities related to the COVID-19 emergency, then the ability to filter them based on region, and activity type). Ability to navigate to a regional 3w page

**Comment by yellowumbrella-design** [comment]
Wireframe of the 3W on the emergency page: https://invis.io/59WZFUYEFTM#/412675366_4-2-1_GO_Specific-Emergency_Epi

When there are more than one country for the table, we can use the same accordion table as for the Regional page.

**Comment by LukeCaley** [comment]
@mariam-yu - Could you update the wireframe to include the sankey chart pre-filtered for data associated with the specific emergency, bearing in the mind the below specification.  

@frozenhelium this is an **urgent** requirement to show COVID-tagged, global flow of National Society support.  IF possible, it would be ideal to be able to filter the sankey by reporting NS (who), sector (what), and region (where) AND country (where).  This should be pre-filtered by COVID-19 tag.  **Note:** This is a 'one-off' for COVID-19 as normally we would pre-filter by associated emergency operation and NOT include region.

cc @lauripynnonen @batpad

**Comment by mariam-yu** [comment]
@LukeCaley Is this what you had in mind? https://invis.io/D3X6LBXQ47A#/416656597_4-4-1_GO_Specific-Emergency_COVID Also, would this diagram be present on all the emergency pages? There seems to be a bit of a duplication (and potentially confusion) between the sankey and the following table (or at least the titles).

**Comment by nanometrenat** [comment]
@lauripynnonen @LukeCaley I think the urgent requirements for the one-off for COVID in [Luke's comment above](https://github.com/IFRCGo/go-frontend/issues/1020#issuecomment-632600966) were met under #1284 - be good to confirm what is still to be covered under this ticket.

**Comment by LukeCaley** [comment]
Implemented https://github.com/IFRCGo/go-frontend/blob/develop/CHANGELOG.md#release-520 ref front-end: https://go.ifrc.org/three-w/
