### ISSUE TITLE
[PROD] Emergency detail key figures' boxes flow out of the parent container

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-frontend#1028]
## Steps to reproduce
Check: https://go.ifrc.org/emergencies/3124#details
![image](https://user-images.githubusercontent.com/30079559/77050811-960d8480-69ca-11ea-8518-e5735059b0c4.png)

## Severity
People could miss information if they're using smaller screens and can't resize/zoom the window.

## Is there a workaround?
Zoom out, resize the browser window.

**Comment by batpad** [comment]
This looks like it is still a problem. @imohkay tentatively assigning you here and moving to the 4.4 board for triage.

**Comment by nanometrenat** [comment]
Closing as no longer relevant due to web re-write
