### ISSUE TITLE
3W: Project from:  Automatically detect ongoing and planned field based on start and end date. Add `completed` checkbox to mark the project as complete

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1036]

**Comment by lauripynnonen** [comment]
Couldn't break this, seems to work!

**Comment by karitotp** [comment]
This is working for planed and ongoing status.
Initially, I was expecting that the completed status also could be completed according the end date. Is the completed status independent of the start and end date?

**Comment by frozenhelium** [comment]
@karitotp Yep that's the intended behaviour. "Completed" is separately marked through the checkbox instead from the dates
