### ISSUE TITLE
Hovering over empty chart breaks the site

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1041]
## Issue

When you hover over an empty chart, the site goes blank

## Steps to reproduce

1. Go to http://tc-ifrc-go.surge.sh/
2. Scroll down to the charts section (i.e DREFS and Appeals Over the Last Year)
3. Hover the mouse over the area where the charts are supposed to be

**Comment by batpad** [comment]
@frozenhelium could you give steps to reproduce? (or a PR to fix works ;-) )

**Comment by frozenhelium** [comment]
@batpad I suppose, it's not an urgent issue since it only occurs if there isn't any data for chart which is very unlikely for the current production environment. Nevertheless we should fix this one by not rendering the chart if data is not available.
![2020-03-24-183306](https://user-images.githubusercontent.com/4931541/77427126-f1da7200-6dfd-11ea-9ac1-a309973127b6.png)
