### ISSUE TITLE
3W: Disclaimer on the status of the map boundaries

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1045]
The map boundaries need a disclaimer. It could, for example, be the following (borrows heavily from the map disclaimer used by UN):

The designations employed and the presentation of the material on this map do not imply the expression of any opinion whatsoever on the part of the IFRC concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries.

Every effort is made to ensure this map is free of errors but there is no warrant the map or its features are either spatially or temporally accurate or fit for a particular use. This map is provided without any warranty of any kind whatsoever, either express or implied.

**Comment by frozenhelium** [comment]
@lauripynnonen I found a disclaimer in the emergency map which goes like

**Comment by lauripynnonen** [comment]
> @lauripynnonen I found a disclaimer in the emergency map which goes like
> 
> > The maps used do not imply the expresion of any opinion on the part of the International Federation of the Red Cross and Red Crescent Societies or National Societies concerning the legal status of a territory or of its authorities, Data sources: IFRC, OSM contributors, Mapbox.
> 
> Let me know if it works or we need to change it to the wordings you have provided.

This is way better - let's use this!

**Comment by lauripynnonen** [comment]
Comes out right - could the font be smaller though? So that the text would fit on one line?

**Comment by frozenhelium** [comment]
@lauripynnonen Done!

**Comment by lauripynnonen** [comment]
Great! One last wish @frozenhelium - could the text be beneath the graphs? So that if someone wants to cut it out it they can

**Comment by frozenhelium** [comment]
@lauripynnonen It's a bit difficult to do so with current method of implementation, the disclaimer currently needs to be contained within map for now. We can certainly do this later when we improve the method of downloading map in general to make it more consistent along all the downloads
