### ISSUE TITLE
Full Screen Option

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#105]
Make full screen modality available for all the maps/dashboards, not just operations (ongoing operations + emergencies + deployments are each to be shown on always-on screens outside the operations room).

**Comment by ascalamogna** [comment]
@guipizzini we won't be able to complete this for all of the dashboards during this phase. But we should have enough time and resources to add this for one more view. Is there a view you would like to prioritize?

**Comment by guipizzini** [comment]
thanks @ascalamogna for the feedback. Will leave it to @renecnielsen to give guidance on this one. Thanks

**Comment by renecnielsen** [comment]
Let's do Deployments, then. And if a good plan for reusability magically comes up, then Emergencies.
