### ISSUE TITLE
3W: Clone an Activity

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1050]
This requires design - but the idea is that the user should be able to clone an activity. Potentially change the buttons (show details, edit, delete, clone) into a dropdown? Cloning would lead to a prefilled input form with details from the original activity

**Comment by lauripynnonen** [comment]
I made the dropdown into a separate ticket. So this can continue, as a button next to DELETE, EDIT, SHOW - or as an element in the dropdown. The desired functionality is to create a copy of an activity and open it in the form - so basically pre-fill a form with the data from where it was cloned, except rename it as (original name *COPY*).

**Comment by lauripynnonen** [comment]
Works great! The name of the cloned activity is the same as the original, but maybe it's better this way!

**Comment by karitotp** [comment]
It works good!
