### ISSUE TITLE
3W: Activity Form: Alphabetical drowdowns

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1051]
All the dropdowns should have their contents in alphabetical order.

**Comment by lauripynnonen** [comment]
Countrywide is the first item on the regions dropdown (not alphabetical) but this might be for the best. So OK according to my testing.

**Comment by frozenhelium** [comment]
@lauripynnonen Yep, that was intentional

**Comment by karitotp** [comment]
Works good! Dropdowns is in alphabetical order, to exception of `Countrywide`.

**Comment by teklal** [comment]
I'm getting Finnish Red Cross first on the list for reporting national society - the rest is in alphabetical order. 

![image](https://user-images.githubusercontent.com/52411237/80108951-37b16400-857d-11ea-8527-0daeacb8ab93.png)

**Comment by frozenhelium** [comment]
@teklal That happened because there was a leading space in Finnish Red Cross, that won't be an issue in the staging or the production

**Comment by teklal** [comment]
Thanks @frozenhelium, checked already on staging this morning and saw that this was fixed :)
