### ISSUE TITLE
3W:  History of edits 

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1052]
Design needed. 

The user should be able to see the edits done to an activity, in the style of version history. 

This could be implemented as one of the things on the dropdown - History. This would then lead to a window where all edits could be seen based on who edited and what changed. In other words

Click history from the dropdown
- a new window (or frame) opens that lists all edits to the activity in chronological order (timestamp, username) (each line is a hyperlink)
Click a hyperlink
- window updates to show a table that has old values and new values with the new values that changed highlighted in bold. a back button on the top allows user to go back to the list of edits and a close button returns the user to the 3W view

**Comment by frozenhelium** [comment]
@lauripynnonen Doing this in the frontend will be a lot more complicated and time consuming. What we can do instead is that, we can use a plugin in the backend called `django-reversion` (It might be already in use, in that case we'll have to set it up for 3W projects). The only lacking feature from what's mentioned in the description will be the ability to highlight diffs. The plugin currently shows the all the version of edits and their preview as well but doesn't show the diff. We can still add a link for "Show edit history" in the frontend which will take user to the admin panel. 
Let us know if this method works. We highly recommend to use the plugin rather that doing it in the frontend.
@batpad any thoughts on this one?

**Comment by lauripynnonen** [comment]
@frozenhelium an awesome idea!
