### ISSUE TITLE
3W: Country-Wide activity - visualization

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1053]
Currently a country-wide operation does not show on the map nor in the bar charts. The country wide operations should increase the shading of all the provinces by one step and show on the bar charts as Country-wide

**Comment by lauripynnonen** [comment]
On bar charts the countrywide operations show as country name, maybe confusing? Also there is no way to click or hover countrywide operations, is there a way around this?

**Comment by frozenhelium** [comment]
@lauripynnonen The operation has been renamed to `Countrywide` now. There isn't any way to show the detail for countrywide operations in the current method of implementation (i.e. individual regions will always get priority over the countrywide when hovered over). We might need to change the design for this to work properly. So, I think we should track this issue in separate ticket.

**Comment by karitotp** [comment]
- Countrywide is shading on the map, but the color is less dark than the other regions with projects.
- It is shown in the bar charts as "Contrywide".

 ![Screenshot from 2020-04-22 13-00-31](https://user-images.githubusercontent.com/11504548/80044092-1858ff00-84c9-11ea-9abc-5a441122c02d.png)
