### ISSUE TITLE
[PROD] Accents and umlauts do not show on notification emails

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1055]
## Issue
Letters that have an accent ( ´ ` ^ ¨ ) do not show on field report notification emails.

## Steps to reproduce
You can test this by subscribing to field report notification emails on testing and submitting a field report on staging with letters with those accents.

Example from production:
![image](https://user-images.githubusercontent.com/52411237/77627462-3d4c6780-6f47-11ea-8937-1ef924aacb63.png)

Example from test field report in staging:
![image](https://user-images.githubusercontent.com/52411237/77627659-83a1c680-6f47-11ea-921a-dc5bc8803f96.png)

## Expected behaviour
The letters should show as on the website as letters with the accents

## Impact
This is mostly an issue affecting field reports submitted in other languages e.g. Spanish and French.
Only people that have subscribed to notification emails would see this.

## Is there a workaround?
There is no workaround.

**Comment by nanometrenat** [comment]
Also logged as SRV-19696 as presumably due to the integration changes done via SRV-18335 & SRV-16958, and https://github.com/IFRCGo/go-api/pull/643

Guessing a UTF/ISO type thing?  Thanks a lot for looking into this.

**Comment by GregoryHorvath** [comment]
@nanometrenat I've replied via the MSM ticket, please keep this conversation there so the guys responsible for the API can respond to that. Thank you for making the ticket, if others want to elaborate from the team they can do it here though.

**Comment by nanometrenat** [comment]
Fixed via SRV-19696 this afternoon, and accents in notifications have been coming through fine since then.

Thanks @GregoryHorvath and IT team for prompt turnaround
