### ISSUE TITLE
[PROD] Field report: fields left blank show up with "No" on generated page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1060]
## Issue

When filling in a field report (tested and this is the case for both the event type and early warning type) on the first page it asks whether the government or NS request international assistance. These are not mandatory fields. After submitting the field report these fields do however show up on the page generated from the report with answer "No" for both of the fields. And when clicking to edit the report, those fields show with "No" selected even though they were left blank on submission. They also appear with "No" on the email notifications although no selection was made.

Another minor cosmetic tweak related to these fields. On the page generated from the field report, add a space after the colon :
![image](https://user-images.githubusercontent.com/52411237/77748997-8ffa5200-7021-11ea-82cb-97cc5a672c82.png)

## Steps to reproduce
Go to staging and fill an field report and leave the fields below blank.
![image](https://user-images.githubusercontent.com/52411237/77748192-40ffed00-7020-11ea-98ce-a9f5aac8b1dc.png)

After submitting the field report, on the page it redirects to, you will find the fields as below:

![image](https://user-images.githubusercontent.com/52411237/77747774-82dc6380-701f-11ea-8bfb-1408d9871cbd.png)

When clicking on the "Edit report" button you will find the fields as below
![image](https://user-images.githubusercontent.com/52411237/77748366-891f0f80-7020-11ea-8920-0fe4024a8516.png)

Another field with the same behaviour, the information bulletin question:
![image](https://user-images.githubusercontent.com/52411237/80978801-d57f1b80-8e26-11ea-833b-0d98df5ac3fd.png)
![image](https://user-images.githubusercontent.com/52411237/80978813-d9ab3900-8e26-11ea-8238-1205f44ff977.png)

## Expected behaviour
The fields about assistance should not appear on the generated page unless user answered those fields. The fields should also not be filled when editing the report if not previously filled by originator.
Alternative option is to make those fields mandatory but this may not be what we want (@mmusori, thoughts?)

## Impact
As there are a lot of field reports being submitted at the moment this potentially affects a lot of reports.

## Severity
This information only shows on the page generated from the field report, not the emergency page it creates, which is likely to be more visited by users.

## Is there a workaround?
No workaround.

**Comment by mmusori** [comment]
@teklal @batpad for integration of GO with the ERP the NS request for international assistance is very important. Thus as a solution to the issue you have raise this should be made mandatory. While they might not know at the point of the first report (thus leaving blank) automatically putting NO for them also does not work. I am thinking of an extra reponse, "Yet to be determined"

**Comment by teklal** [comment]
Ok, just noticed another field with the same behaviour, the information bulletin question:
![image](https://user-images.githubusercontent.com/52411237/77753203-588fa380-7029-11ea-9dae-cbf1a9cdaf6f.png)
![image](https://user-images.githubusercontent.com/52411237/77753224-62b1a200-7029-11ea-87a5-2f1ec99bd81a.png)

**Comment by teklal** [comment]
Another similar issue:
The "Start date" field is marked as mandatory with an asterix * but in practice this is not enforced and a user can submit the report without choosing a start date.
If this field is left blank, the date is automatically chosen as the current date and this also shows on the generated page and when editing the report again.

I suppose for this one the easy fix would be to not allow the user to proceed without choosing the date (enforcing the fact that the field is mandatory).

**Comment by teklal** [comment]
Somewhat related to #984

**Comment by necoline** [comment]
This field is added as a boolean in the form and on the backend. So if users do not make a selection, it will default to false and autopopulate `No`. In essence, it is behaving like a checkbox.

Should fields with an option of `Yes` or `No` be converted to checkboxes, or should we leave the UI as is and change the form type?

> The "Start date" field is marked as mandatory with an asterix * but in practice this is not enforced and a user can submit the report without choosing a start date.

 -- This is fixed in #1074

**Comment by teklal** [comment]
Just adding: The fields about international assistance show up on notification emails as well with the default "No" even though no selection was made.

**Comment by LukeCaley** [comment]
@imohkay @batpad please confirm if this is in progress / ready for QA as the recent commit would suggest

**Comment by kamicut** [comment]
@batpad not sure what the right fix is here since we would need changes to the schema. Do you have any experience working with https://www.django-rest-framework.org/api-guide/fields/#nullbooleanfield ? For those fields which require a null value, we can modify the schema to allow for a "null" value. I'm not sure what would need to change on the frontend / API for this to work.

**Comment by batpad** [comment]
cc @mmusori
