### ISSUE TITLE
Add Field Report Type to API Response

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#1062]
**Is your feature request related to a problem? Please describe.**
> Hi @batpad I have just been looking at the Field Reports via the API (need to programmatically extract some). I can't see a field to tell me what type of Field Report it is - can you please add a field to the API response? At the moment the only way I can tell if it's Early Warning vs Normal is by looking at whether the fields "imminent_dref" and "forecast_based_action" exist.

Note - IF there are Actions Taken by the National Society or Govt (i.e. tickboxes ticked) then I can see what field report types those actions can potentially relate to ("actions taken" / "actions" / "field_report_types") but if no Actions Taken ticked then no mention of type anywhere.

Would greatly appreciate being able to access this field. We may wish to show type onscreen also?

Original Comment: #1004

**Comment by batpad** [comment]
The API returns a field called `status` which indicates the FR type (or disaster_type) to know whether it was an epidemic report. Closing here, feel free to re-open if this is still an issue.
