### ISSUE TITLE
3W: Domestic Programme Type (related to COVID)

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1065]
Add Domestic to the selectable Programme types (Dometic, Bilateral, Multilateral)

Domestic is similar to Multilateral, except that instead of asking for Current IFRC Operation, the user must select Current Emergency Operation. The list of current emergency operations pulls a list of Emergency Operations that have been added through field reports of that country

Add tooltip to the Current Emergency Operation that says "The list is populated from current emergency operations related to the selected country. If necessary, create the related emergency through a field report".

**Comment by lauripynnonen** [comment]
Looks good to me. @frozenhelium Could it be possible to pull the disaster type from the selected Emergency Operation and show it also on the form (but disabled)?

**Comment by karitotp** [comment]
Looks good! also the disaster type is automatically completed according the selected emergency operation and it is showed disabled on the form.
