### ISSUE TITLE
3W: Allow users to create a 3W activity through an emergency page

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1066]
Add "Create 3W Activity" button to the Emergency page.

**Comment by lauripynnonen** [comment]
I tried testing this but could not find any 3w things from the Emergency Page, maybe I'm too fast?

**Comment by lauripynnonen** [comment]
Found it - I believe the desire was to add the Create 3 W Activity to an emergency 
![image](https://user-images.githubusercontent.com/8285694/78778757-1278ff00-799c-11ea-81ad-84ffba43e452.png)

**Comment by frozenhelium** [comment]
Done!

**Comment by lauripynnonen** [comment]
Works!

**Comment by lauripynnonen** [comment]
@frozenhelium Just out of curiosity - I created a 3w activity to Aland Island (which is an autonomous region in Finland)
![image](https://user-images.githubusercontent.com/8285694/79873225-220a3600-83e7-11ea-9dd0-30ad45cd0c19.png)
However Åland is not listed in the Europe Regional pages, nor will the activity show under 3w Finland. Where did it go!?

**Comment by frozenhelium** [comment]
@lauripynnonen If there aren't dedicated country page for it then we might not be able to see it from the frontend but the entry will be accessible from the backend.

**Comment by lauripynnonen** [comment]
@frozenhelium could it be possible to pull the details of the emergency to the 3w form? Like Operation type (emergency operation), Disaster type, potentially country and region

**Comment by frozenhelium** [comment]
Will have to check.
