### ISSUE TITLE
3W: IFRC Only Checbox 

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1067]
Add IFRC Only Checkbox as the last thing the user can fill when adding an activity to 3W. If this the checkbox is checked only logged in users can see the activity.

**Comment by lauripynnonen** [comment]
Change this to a visibility dropdown with *public* as default, the alternatives are *logged in users* and *IFRC Only* @teklal - is this how Go generally treats visibility?

**Comment by frozenhelium** [comment]
@batpad Do you know if there is any way to identify if a particular user is an IFRC user?

**Comment by teklal** [comment]
@frozenhelium my hunch would be that based on the email address the user used for registering on GO, if the domain is @ifrc.org they'd be considered an IFRC user

**Comment by lauripynnonen** [comment]
I only have the ifrc-user in the test environment, but when filling the forms the dropdown seems to work! And logged in users-activities are hidden from a public user. 

Activities set to "IFRC-Only" are hidden for the test user - @frozenhelium I assume the test-user is not an IFRC-user?

**Comment by thenav56** [comment]
@lauripynnonen Yes, the test-user is not an IFRC-user. We treat a user as IFRC-user if their email ends with [@ifrc.org](https://github.com/IFRCGo/go-api/blob/feature/databank-fts-google-sheet/deployments/drf_views.py#L197).

If you want to add and view as an IFRC-user, you can create a new user from [here](https://go-api.togglecorp.com/auth/user/add/). The user's list is available [here](https://go-api.togglecorp.com/auth/user/).
