### ISSUE TITLE
[PROD] Help file links on About page are broken

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1069]
## Issue
The Go User Guide and Admin Guide currently lead to a Google Drive 404 page

## Steps to reproduce
Go - [About ](https://go.ifrc.org/about)- click either of the guides

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
Links fixed to existing files. Would it make sense to host the guides here on Github and link them from here instead of using Google Drive?

Guides attached
[GoUserGuide_MediumRes.pdf](https://github.com/IFRCGo/go-frontend/files/4415370/GoUserGuide_MediumRes.pdf)
[GoAdminGuide_MediumRes.pdf](https://github.com/IFRCGo/go-frontend/files/4415371/GoAdminGuide_MediumRes.pdf)

**Comment by guipizzini** [comment]
As an add on:

The footer has the "old" url when click the API: https://prddsgocdnapi.azureedge.net/docs

This should be replaced with the more user friendly url that has been created.

Thank you

**Comment by nanometrenat** [comment]
The user friendly URL is https://goadmin.ifrc.org/docs

**Comment by teklal** [comment]
Checked and these changes are now live. Closing the ticket.
