### ISSUE TITLE
[COVID] Field Reports - extract via API

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1072]
## Issue
At the moment, it is not possible to extract a data download of all the Field Report data (including actions taken).

1. If I go to https://go.ifrc.org/reports/all and click Export then the download fails (too much data)
2. If I just try to export one region then I get an export csv file OK, but it only has these columns:

> countries 0 id | countries 0 iso | countries 0 name | countries 0 record-type | countries 0 society-name | created-at | disaster-type id | disaster-type name | disaster-type summary | event | event disaster-type | event id | event name | event slug | id | report-date | summary | updated-at | visibility
i.e. the export does not list the actions taken or any of the other key details from the Field Report

NB I think the Export file is based on the API https://goadmin.ifrc.org/api/v2/field_report/ (need to use params to filter and limit number of results of course, as per above - I have been using these parameters for the moment:  https://goadmin.ifrc.org/api/v2/field_report/?limit=300&ordering=-created_at&created_at__gte=2020-01-01T00%3A00%3A00.000Z&offset=0&format=csv ) 

As far as I can tell, the only way to see the Actions Taken is to look up each Field Report individually via either the UI (https://dsgoproxyapp.azurewebsites.net/reports/9453) or via the API https://dsgocdnapi.azureedge.net/api/v2/field_report/9453

I need a way to export the Field Report data in bulk for analysis.

At a minimum, we need to add in the following columns/response fields to the field_report API response (and csv export):
* Actions taken by National Society (list of actions, plus summary)
* Actions taken by IFRC (list of actions, plus description/summary)
* Actions taken by other RCRC Movement Actors (list of actions, plus description/summary)
* Actions taken by others (UN etc.)

Ideally we would also have the figures assisted by govt, number of volys etc. - but that is second priority - it's the Actions that are most important for right now.

NB also critical to retain the visibility restrictions (e.g. the public should not see the FRs that are IFRC only etc.)

## Related feature
#1004 

## Impact
Without this we cannot do analysis on the Field Report data.

(please forgive me if this is already logged, know it has been discussed but I can't find a ticket so logging now!  thanks a lot)

**Comment by batpad** [comment]
@geohacker is this something we can take a look at next? It should be relatively straightforward changes / additions to the API.

**Comment by geohacker** [comment]
@nanometrenat I posted sample CSVs for before and after the API fix is here https://gist.github.com/geohacker/898a64a5cd7ea90698d921e83372d649 -- this now takes all columns but let us know if there are ones that you don't think are useful as part of the csv.

**Comment by geohacker** [comment]
@nanometrenat @teklal - this is now in staging. Based on the request above, if you go to this URL https://dsgocdnapi.azureedge.net/api/v2/field_report/?limit=300&ordering=-created_at&created_at__gte=2020-01-01T00%3A00%3A00.000Z&offset=0&format=csv you can test the field report export.

cc @batpad @necoline

**Comment by nanometrenat** [comment]
Thanks a lot @geohacker and sorry for my delayed response - have gone to the URL above but a few issues with the data coming through and would really appreciate your thoughts as to what is possible to resolve and with what degree of effort.

1. There's a fair bit of info that I can't figure out where it is coming from, and that is coming through in the API response as garbage (and meaning the csv export also doesn't work).  e.g. (among others):    

> "summary": "The function requires the library jsonlite.\n\nFunction input: the location address as string.\nFunction output: a data.frame with lon (longitude) and lat (latitude) of the input location, or empty data.frame if no/invalid address provided as the function input.\nLet’s test the function.",
> 
>                     "id": 5879
Even separate to those with code-like content coming through (such as the above) there are others that also don't work when I take the csv output and convert to columns in Excel.  Need to figure out if the best approach is to just stop these fields from being returned altogether (but it's hard to figure out which fields they are)

2. is it possible to explicitly select ordering of fields in csv or must they come through alphabetical?
3. xref #1062 as "type" does not show
4. the "actions" nodes (in both the full list of field reports and also for an individual field report) don't make sense - e.g. for the below the organization at top level is good but the list of possible organizations within the actions node doesn't help at all and is confusing - especially in the csv export as that's 3 extra columns per action that I need to delete after the fact.  Similarly having field_report_types within the action isn't relevant.  Would be greatly appreciated if these fields could be removed for the field_report endpoint (though will need to stay there for the actions endpoint) as that would hugely reduce the size of the file and number of columns.
```
            "actions_taken": [
                {
                    "organization": "FDRN",
                    "actions": [
                        {
                            "name": "CTP/Basic needs",
                            "id": 41,
                            "organizations": [
                                "NTLS",
                                "PNS",
                                "FDRN"
                            ],
                            "field_report_types": [
                                "EVT"
                            ],
                            "category": "General"
```
I hope this all makes sense - happy to jump on a call if that helps.

Many thanks, N

**Comment by nanometrenat** [comment]
Re number 1, FYI, here's a screenshot of how it comes out when the csv is opened in Excel:
![image](https://user-images.githubusercontent.com/33625192/78886639-db1f5680-7a5e-11ea-9b85-1445ae73afa4.png)

**Comment by nanometrenat** [comment]
Can see that some of the data that is coming through scrambled in csv is from this specific FR:  https://dsgoproxyapp.azurewebsites.net/reports/9441

**Comment by geohacker** [comment]
@nanometrenat thank you for testing this. Those actions are getting spread into columns from a JSON structure and creating all those weird columns. So we just grouped it by organizations. Omitted the summary because it's bound to have strings that might break the CSV, but if it's absolutely necessary we can add. 

Here's a test csv. [test.csv.zip](https://github.com/IFRCGo/go-frontend/files/4469600/test.csv.zip). Let me know if this looks ok.

**Comment by nanometrenat** [comment]
Thank you @geohacker that is hugely better.  I think we should go with that format for this release.

Noting two things for further consideration/future enhancement:

- Actions Taken - it will still require manipulation to be able to extract the data, as within e.g. actions_taken.NTLS it still has a JSON string e.g. "{"actions_name":   ["Relief/Supply distribution", "Shelter",   "Evacuation", "Search & Rescue", "Food   aid", "First Aid", "Damage/Needs assessment"],   "actions_id": [38, 32, 36, 28, 30, 37, 27]}"
For the immediate moment I will be able to extract the necessary info using PBI manipulation so that is great - we might want to think about whether there's a more useful download format for the next phase though (as none of our other csv exports have JSON in them)

- "Summary" strings - I note that whilst the "summary" strings have been omitted the "actions_others" string is still present (so presumably that might break the CSV also)?  Yes it would be very useful to be able to include the summary strings (as we want to run some qualitative analysis on them) however like the previous I am happy to carry that forward as a separate ticket for prioritisation, rather than holding up the release now.

THANK YOU!

**Comment by geohacker** [comment]
@nanometrenat great! Yeah actions taken would be challenging to have it in a single CSV as a flat row. The best thing to do would be to extract actions taken as a separate CSV and join them during analysis. Otherwise combining them into one would be pretty complicated.

I just added the summary as well. Tested the CSV on Numbers and text editors and it seemed to work well. [test.csv.zip](https://github.com/IFRCGo/go-frontend/files/4474621/test.csv.zip)

cc @batpad

**Comment by nanometrenat** [comment]
Thank you, looks great!  Let's implement it as is.

There are still some gremlins around special characters (e.g. French accents) but not a showstopper

**Comment by batpad** [comment]
Latest changes are now on staging.

**Comment by nanometrenat** [comment]
Looks great in staging, thanks hugely

**Comment by nanometrenat** [comment]
Field Reports export via UI has stopped working in Prod (504s) - MSM ticket raised.

**Comment by nanometrenat** [comment]
Thanks, API working well - and since Greg's latest changes were released we can now download via UI again.
