### ISSUE TITLE
3W: Reduce the amount of button on the table

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1075]
Currently, the table has three buttons (Show Details, Edit, Delete). Soon we'll have a clone and History button as well. 

Would there be a better way to do this? i.e. 
- Show Details could be just clicking the name of the project. 
- Edit, Clone, History and Delete could be a dropdown with buttons

@yellowumbrella-design  is this a terrible idea? How does the rest of Go work?

**Comment by yellowumbrella-design** [comment]
hey Lauri, can you plz add a screenshot? That will help. we can propose a suggestion. What does Clone do?

**Comment by lauripynnonen** [comment]
Current:
![image](https://user-images.githubusercontent.com/8285694/78262351-b841ef00-7500-11ea-97f3-9624492374ac.png)
Potential future version:
![image](https://user-images.githubusercontent.com/8285694/78263418-3783f280-7502-11ea-8794-37695f325d13.png)
Clone could open a prefilled activity form with the data from the activity where the cloning was initiated

**Comment by yellowumbrella-design** [comment]
Thanks will look into this. To have a better context, is this the editable form for 3w where only admins can see and manage?

**Comment by lauripynnonen** [comment]
Thanks! This form is on the front end. So I assume it is for normal logged
in NS staff

**Comment by yellowumbrella-design** [comment]
![GO_Table_Dropdown](https://user-images.githubusercontent.com/60006476/78350910-415f3180-75a6-11ea-8450-b4f3177b52d3.png)
@lauripynnonen here is a functional recommendation. We will take a stab at the entire table UI too (to make sure we have consistency across). Let's discuss over the call.

**Comment by lauripynnonen** [comment]
@yellowumbrella-design super thank you!
@frozenhelium could you look at this and when possible, implement according to the yellow umbrella table/functional design (if you find the description to be sufficient). Please note #1052 which adds History item to the dropdown

**Comment by frozenhelium** [comment]
@yellowumbrella-design Looks fantastic!
@lauripynnonen Sure, will implement it very soon

**Comment by lauripynnonen** [comment]
This is awesome and works great!

**Comment by karitotp** [comment]
This is working perfect!

Just one thing; in view details, it is needed to change the title for the total targeted and the total reached number. Currently it is saying Other instead Total.

![Selection_015](https://user-images.githubusercontent.com/11504548/80112957-4f6df580-8547-11ea-8eb3-50d316b4d4ef.png)
