### ISSUE TITLE
3W: Automate the Planned - Ongoing logic

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1076]
Automate activity status so that planned activities are automatically changed to ongoing when the period of that activity starts.

**Comment by karitotp** [comment]
What is the difference between this and https://github.com/IFRCGo/go-frontend/issues/1036?

What I guess is that, if I create and activity that is detected as "planned" according the start and end date with which it was created, the status should change automatically to a "ongoing" status when the start date arrives. I took a look to an activity which was created as "planned" but it did not change to a "ongoing", despite being currently within the start and end dates.

Te below screenshot is the EDIT mode of the activity that I am talking about https://tc-ifrc-go.surge.sh/countries/35#3w
![Screenshot from 2020-04-26 21-46-21](https://user-images.githubusercontent.com/11504548/80330623-4d3bbd80-880b-11ea-9da0-f5946f88fa12.png)

If my assumption is not correct, please let me know how should I test this :pray:

Other question is about to get the url of a specif activity, do they have an ID? When I go to edit or view details of of them it does not show any on the route :thinking:
