### ISSUE TITLE
[PROD] Change default scaling of points on maps

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1079]
## Issue
At the moment the default scaling of the points on the map on the home and region pages is by the "number of people affected". As some emergencies do not have this information we should change the default scaling to go by IFRC financial requirements.

## Steps to reproduce
Go to the GO home page or a regional page and you'll find a map similar to the one below:
![image](https://user-images.githubusercontent.com/52411237/78352736-23df9700-75a9-11ea-86cc-d0280a9c0720.png)

## Expected behaviour
Change the default scaling of the points on the map to go by IFRC financial requirements

**Comment by batpad** [comment]
@teklal @LukeCaley is this something that's still important to do? We could likely fold this into the geospatial data handling? If so, feel free to move to 4.3 and remove the backlog label.

**Comment by tovari** [comment]
We aim to review the dot scaling options on the map, so I close this ticket.
