### ISSUE TITLE
COVID-12 // Reordering of emergency page information

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1082]
**Problem**
The presentation of tables and information on the emergency pages do not seem to follow an intuitive order.  Users currently need to scroll past two tables of deployment/surge information to find appeal docs, response docs and contacts.

**Proposed solution**
Reordering of the information based on user interviews and study conducted by @yellowumbrella-design.  Likely to include 'demotion' of deployments information, in part due to the introduction of the surge database which will serve as the notification and 'action' channel for deployment information.

**Additional context**
Reordering should take into consideration additional tabs (x-ref: https://github.com/IFRCGo/go-frontend/issues/1009) and other ongoing UI work (x-ref: https://github.com/IFRCGo/go-frontend/issues/1014 & https://github.com/IFRCGo/go-frontend/issues/1012)

**Comment by batpad** [comment]
@LukeCaley do you think this ticket is covered under the Emergency Page UI / UX Redesign ticket? Should we mark this as closed once the design is ready, and move implementation to https://github.com/IFRCGo/go-frontend/issues/1243 ?

**Comment by mariam-yu** [comment]
The design is done actually: 
Wireframes: https://projects.invisionapp.com/share/9AXF55DFB5G#/screens/361592718
UI: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417134563

**Comment by mariam-yu** [comment]
@LukeCaley Updated emergency wireframes: https://invis.io/59WZFUYEFTM#/412675366_4-3-1_GO_Specific-Emergency_Epi

Some comments:

1 - Moved the Response Actions to a separate tab (3W). Does this work? @lauripynnonen Any thoughts on this?

2 - To your question, whether we should keep Surge Documents under Documents tab, we are proposing to keep all the docs in one section to manage easier. Thoughts?

3 - For Rapid Response, you had some comments about additional visualisations. Are we keeping them for after we tackle deployment or even now?

4 - Named the last tab - Additional Data - as we did on the country pages. One suggestion from the interviews was to split the graphs from other data added. Let me know your thoughts.

**Comment by batpad** [comment]
We have done a bit of design re-work on the emergency page as part of the new design implementation, but are moving the larger re-organization bits of the emergency page to 4.4., as per discussion.

**Comment by tovari** [comment]
Linking to https://github.com/IFRCGo/go-frontend/issues/1243

**Comment by LukeCaley** [comment]
Closing as work completed in phase 4.4
