### ISSUE TITLE
3W: Covid specific health adjustment

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1083]
When domestic / heath specific / emergency specific, when the emergency is a "Health Emergency" the "Sector of Activities" change to match the "Actions" from the Field Report.

Needs more info, but in its current form 3w does not serve COVID needs

/Roxanne: Minimum valuable information is split between "Public Health" and "Clinical" health activities. Preferred is to match the "Health Emergency" actions list outlined in the Health Emergency Field Report https://projects.invisionapp.com/share/BTVGAE434CJ#/screens/409814229

**Comment by lauripynnonen** [comment]
Suggestion: Divide Health Sector to "Health (clinical)" and "Health (public)".

@teklal as a Go Pro does this sector classification clash with other sector classifications in Go?

**Comment by lauripynnonen** [comment]
Ok this is it: Divide Health Sector to "Health (clinical)" and "Health (public)".
![image](https://user-images.githubusercontent.com/8285694/79568874-f0c3fa00-80b6-11ea-8a37-56747b7d7b36.png)

**Comment by frozenhelium** [comment]
Great!

**Comment by lauripynnonen** [comment]
They are there! but if you choose one you cant submit the form (either in primary or tags). The form below for example refuses to submit, but if I change the primary and tags to something else it works!
![image](https://user-images.githubusercontent.com/8285694/79993540-269d2000-84b5-11ea-998e-2530cf66001a.png)

**Comment by frozenhelium** [comment]
@lauripynnonen There was an small issues, it's fixed and deployed now

**Comment by karitotp** [comment]
The form is submit correctly now! :+1:
