### ISSUE TITLE
[Staging] Additional Information tab shows as blank if no snippets added

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1086]
## Issue
If there have been no snippets added to an emergency, the additional information tab now shows up completely blank instead of saying "No data to display."

## URL
E.g. Aland Bio Test3
https://dsgoproxyapp.azurewebsites.net/emergencies/3840#additional-info

## Steps to reproduce
Navigate e.g. to the above emergency page and to the "Additional Information" tab

![image](https://user-images.githubusercontent.com/52411237/78665657-720cd700-78d6-11ea-96a9-15d7fa363f38.png)

## Expected behaviour
If there are no snippets added, the page should say "No data to display." as in the screenshot below
![image](https://user-images.githubusercontent.com/52411237/78665810-b0a29180-78d6-11ea-9946-cac49adae0e6.png)

**Comment by teklal** [comment]
@batpad issue mentioned during the call now logged.

**Comment by geohacker** [comment]
@teklal thanks for catching this! I just fixed and this is now ready for QA on staging.

**Comment by teklal** [comment]
Thanks for the prompt fix. Tested and works.
