### ISSUE TITLE
[PROD] PER: add third option to benchmarks (NB: no action at the moment)

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1089]
## Issue
Currently assessing each benchmark in a PER form is mandatory. However it is possible that not all benchmarks are assessed during the PER assessment phase.

As a proposal as a workaround to enable uploading PER assessment data, add a third option, e.g. "Not reviewed" to the existing "Yes"/ "No" for the Benchmark status question in PER forms.

Current state:
![image](https://user-images.githubusercontent.com/52411237/78770657-28cc8e00-798f-11ea-9daf-8db7dbfc80e4.png)

## Related feature
A potential workaround for mandatory benchmarks i.e. #974 

## Impact
This affects all users filling PER forms on GO. Relevant especially for historical PER data (when benchmarks were different) and NSs doing the assessment in any other way than self-assessment (e.g. through a simulation).

## Severity
May be a blocking issue for uploading PER data.

## Is there a workaround?
Proposed but not ideal workaround: choosing "yes" or "no" for the benchmarks for which there is no data and explaining this in the comment box.

**Comment by nanometrenat** [comment]
Closing ticket as advised by Stephanie - this old PER is either not relevant any more, or solved because of the new forms/NS preparedness section.  There are other Github tickets related to the new development.
