### ISSUE TITLE
COVID-13 // Enhance 'About' page

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1094]
**Problem**
`about` page requires enhancement to provide support for users based on issues identified and new functionality to be released.

**Solution**
Design of a user friendly, uncluttered, links page. Preferably using the cards approach with a greyed out background image for the link.  Nice to have would be that the card changes to provide some textual info on the resource which appears when hovered over.

**GO user guidance**
- [GO video](https://www.youtube.com/watch?v=dwPsQzla9A4) 
- Links to download the user and administrator guides
- Future GO youtube videos to be produced including Field Reports, 3w, PER & Notifications - more to inevitably come but these expected in the next month

In addition, it would be useful to use this space as a way to redirect to other useful IFRC resources, including 

**IFRC surge services**
- [Catalogue of surge services](https://ifrcgo.org/global-services/) 
- [SIMS Network](http://rcrcsims.org/resources/)
- [Nyss - RC/RC Community based surveillance tool](https://www.cbsrc.org/)

**IFRC guidance material**
- [Cash Hub ](https://www.cash-hub.org/)
- [CEA hub](https://www.communityengagementhub.org/guides-and-tools/cea-guide/)
- [PrepareCentre](https://www.preparecenter.org/#)

**Other IFRC resources**
- [Missing Maps](https://www.missingmaps.org/) 
- [FDRS](https://data.ifrc.org/fdrs/)  
- [Learning Platform](https://ifrc.csod.com/client/ifrc/default.aspx)
- [Forecasts in Context](https://iridl.ldeo.columbia.edu/maproom/IFRC/index.html)

**Additional context**

- Xref: https://github.com/IFRCGo/go-frontend/issues/1069
- There may be other resources to be added but we should not overload the page
- We might need to rename the page and link in the banner from `about` to `resources`
- All links should be publicly available
- acknowledgements of support should be retained but it would be good to change them all to the same colour
- We should probably make the email more prominent 
- This removes the need to add `RCRCSIMS` and `data.ifrc.org` to the footer **note** @yellowumbrella-design

**Comment by nanometrenat** [comment]
xref #1069 re About page help docs
Also noted in call today that any _documents_ (e.g. pdfs) should be stored in Github source control, but videos and website links are via link only of course.

**Comment by yellowumbrella-design** [comment]
@LukeCaley Can you please clarify what do you mean about the card styling? is this referring to one of our existing styles? Thanks.

**Comment by LukeCaley** [comment]
As noted on the GO call today this refers to a notional style in keeping with the 'card' style for highlighted emergencies etc.  However, as also pointed out on the call, the implementation of this should not be to the detriment of users in low bandwidth areas so happy with a simple, elegant design of your creation @yellowumbrella-design

**Comment by yellowumbrella-design** [comment]
@LukeCaley Here is a first stab at the about (now resources) page: https://projects.invisionapp.com/share/37WWPCKXA6C#/screens/413996134
Please share your thoughts. Added a card flip anyway for review and consideration (last card with i  icons).

**Comment by nanometrenat** [comment]
May also wish to include Spanish translation of User Guides (currently linked from Additional Links section of https://go.ifrc.org/regions/1#additional-info)

**Comment by LukeCaley** [comment]
Thanks @yellowumbrella-design for the initial design - mostly looking good. Added comments to the wireframes.  They should be straight-forward - please let @batpad know here when this is ready to handoff for development.

**Comment by yellowumbrella-design** [comment]
@LukeCaley please check out the UI of the new Resources page: https://invis.io/7EX0OGCX4WA#/415044452_0-2-1_About_V5 If all good, we will drop it into Zeplin. Let us know. Thanks!

**Comment by LukeCaley** [comment]
Looks great!  Please handoff to dev with styles in Zeplin.  My only slight concern is with the implementation of the carousel for the reference videos - hopefully this is simple to implement? 

I guess you will also need some more text for info boxes etc - could you comment and tag me/IM focal point on those and we will add the appropriate text.

**Comment by yellowumbrella-design** [comment]
Thanks Luke. Updating on Zeplin. If the videos are issue in a carousel, we can just display them directly on the page.

Regarding the text for the boxes, if it's for videos, I assume they will be pulled from Youtube directly. But we can see how that works.

**Comment by LukeCaley** [comment]
@batpad to provide estimate for implementation.

**Comment by batpad** [comment]
> Thanks Luke. Updating on Zeplin. If the videos are issue in a carousel, we can just display them directly on the page.

Avoiding a carousel implementation will likely save a bunch of effort here.

Question around the video playback: should the video play right there, or open up in a modal dialog? I **think** my recommendation here would be to use a modal as to give the videos more space on the screen when playing, but happy to discuss.

> Regarding the text for the boxes, if it's for videos, I assume they will be pulled from Youtube directly. But we can see how that works.

Either is likely fine :)

@LukeCaley - can provide a firmer estimate once we are certain of some of the bits like modal, carousel, etc. but most of the rest of the layout is already done :-)

**Comment by batpad** [comment]
Work in progress can be viewed here: https://ifrc-go-feature-1094-about-page.surge.sh/about

Things remaining to do:

 - Implement mouse-over tooltips on Info icons
 - Figure out carousel / modal logic for videos

**Comment by yellowumbrella-design** [comment]
@batpad Great job putting it together so quickly. Showing videos directly works, given we don't have many. @LukeCaley Any idea of how many videos there may be?

**Comment by batpad** [comment]
> Showing videos directly works, given we don't have many.

My slight concern is then we may need to implement some logic to ensure a user cannot play more than video at a time (i.e. pause currently playing video if user plays a different video) - uncertain how much work that will be, but shouldn't be too bad. Let's figure the little details there, and hopefully we are pretty close here.

**Comment by yellowumbrella-design** [comment]
@batpad The layout is looking great, we just have a few comments on visual design: 
- Under the top video the white rectangle in the background is correct, but it shouldn’t have a drop shadow on it.
- The left/right margins of the white cards and videos should be in the same alignment as the top navigation (starting at GO icon and Home). 
- At the end of the page, there’s a grey banner, but it should be all white (from the logos until the footer).
Thanks!

**Comment by batpad** [comment]
@yellowumbrella-design thank you. Can you please check an updated version at https://ifrc-go-feature-1094-about-page.surge.sh/about and let know if this addresses all the points you mention? Thanks!

**Comment by yellowumbrella-design** [comment]
> @yellowumbrella-design thank you. Can you please check an updated version at https://ifrc-go-feature-1094-about-page.surge.sh/about and let know if this addresses all the points you mention? Thanks!

Yes, that's it, thanks @batpad !

**Comment by batpad** [comment]
@yellowumbrella-design carousel has been added for videos to https://ifrc-go-feature-1094-about-page.surge.sh/about

Also introducing @imohkay (Karen Menezes) who has been working on the design implementation - I know she is unhappy with some things about the carousel, but of course, using a plugin, there's some things that are hard to get perfect - but tagging @imohkay here so you can hopefully figure out solutions to anything that may seem off.

With this, I'm hoping this page is close to completion, except for:

 - Get all the final links, text and videos from IM team.
 - Implement logic to ensure two videos cannot be played at the same time

**Comment by yellowumbrella-design** [comment]
@batpad @imohkay Thanks for the link! 
The carousel works well like this, but is it possible to when clicking in the arrow it shows the next 3 videos complete? (So when the user clicks to watch they are not showing in half).
Also, can the clickable arrow be red? The other can stay light grey as it is now.
Thanks!

**Comment by imohkay** [comment]
@yellowumbrella-design Regarding the clickable arrow for the carousel, do you mean that it should be red always, or only on hover?
The carousel is causing some issues, as are a couple of other plugins I tried out (for showing 3 complete items at a time). I'll see if I can find a fix soon :)

**Comment by LukeCaley** [comment]
Emails:
Africa Region
Ted Bolton
RRIM.Africa@ifrc.org

Americas Region
Luis FANOVICH 
Luis.FANOVICH@ifrc.org

Asia Pacific Region
Dedi JUNADI 
Dedi.JUNADI@ifrc.org

Europe Region
Anssi ANONEN 
Anssi.ANONEN@ifrc.org

Middle East & North Africa Region
Ahmad AL JAMAL 
Ahmad.ALJAMAL@ifrc.org>

**Comment by imohkay** [comment]
@LukeCaley Hey, am just adding the email addresses as mentioned in your comment. 
Are the surnames intentionally in uppercase for the email address and the last name?

**Comment by LukeCaley** [comment]
@imohkay Cheers. Suggest the SURNAMES remain all-caps and the email addresses go all lower case.  Apologies, I just cut and pasted from outlook :)  About to detail desired links for the rest of the page.

**Comment by LukeCaley** [comment]
**GO User and Administrator Guides**
_Guidance on how to use and administrate GO_
EN same links as currently
ES @nanometrenat to share these links when uploaded to GitHub
AR - In progress
FR - In progress

**GO Reference Materials**
_How and why GO works_
Visual Guidelines - URL not yet available
Visual Identity - URL not yet available
User Studies - URL not yet available
Information Architecture - URL not yet available
3w guidance - URL not yet available
3w lessons learned - URL not yet available
GO presentation materials - URL not yet available
IFRC IM strategy - URL not yet available

**IFRC surge services**
Catalogue of surge services - https://ifrcgo.org/global-services/
Surge IM network - SIMS - http://rcrcsims.org/
Nyss - RC/RC Community Based Surveillance tool - https://www.cbsrc.org/

**IFRC Guidance Material**
Cash Hub & Remote Helpdesk - https://www.cash-hub.org/
Community Engagement Hub - https://www.communityengagementhub.org/
Global Disaster Preparedness Centre - https://www.preparecenter.org/
Data Playbook - https://www.preparecenter.org/toolkit/data-playbook-toolkit

**Other IFRC Resources**
Missing Maps - https://www.missingmaps.org/
Federation-wide Databank and Reporting System - https://data.ifrc.org/fdrs/
Learning platform - https://ifrc.csod.com/client/ifrc/default.aspx

**Comment by nanometrenat** [comment]
> **GO User and Administrator Guides**
> _Guidance on how to use and administrate GO_
> EN same links as currently
> ES URL not yet available - requires dev support @GregoryHorvath [Xref](https://github.com/IFRCGo/go-frontend/issues/1069)

Spanish link listed [in comment above](https://github.com/IFRCGo/go-frontend/issues/1094#issuecomment-615976275) - direct link here for clarity:
* GO User Guide (ES) https://drive.google.com/file/d/1FnmBm_8K52eTKWa8xWK52eebhgOz60SO/view?usp=sharing
(can't spot a Spanish admin guide)

**Comment by imohkay** [comment]
@LukeCaley sounds good... 
Staging has just been updated with the updated About page, including new links for User + Admin guides, Resources and Contacts.

**Comment by yellowumbrella-design** [comment]
> @yellowumbrella-design Regarding the clickable arrow for the carousel, do you mean that it should be red always, or only on hover?
> The carousel is causing some issues, as are a couple of other plugins I tried out (for showing 3 complete items at a time). I'll see if I can find a fix soon :)
@imohkay the clickable arrow would be red only on hover, the other colours are on Zeplin. Thanks!

**Comment by LukeCaley** [comment]
@imohkay if possible, please update the GO reference materials to reflect the links (and slight change in text) [here](https://github.com/IFRCGo/go-frontend/issues/1094#issuecomment-623447962)

@batpad @imohkay is it possible to change `About` to `Resources` sitewide?
![about](https://user-images.githubusercontent.com/7791954/80980561-0d875e00-8e29-11ea-93ad-f292127e9d4e.PNG)

**Comment by imohkay** [comment]
@LukeCaley For Reference Materials, the URLS for 'Information Architecture' and '3w lessons learned' go to a URL that says the link has been removed. And the 'User Studies' link leads to a page that is blank.

**Comment by nanometrenat** [comment]
> @LukeCaley For Reference Materials, the URLS for 'Information Architecture' and '3w lessons learned' go to a URL that says the link has been removed. And the 'User Studies' link leads to a page that is blank.

These two links should be fixed now

**Comment by LukeCaley** [comment]
Thanks @imohkay - @lauripynnonen will share the URLs for those imminently.

Re the videos - can we, for now, link to the GO 3w promotional and instructional videos in the [youtube playlist here.](https://www.youtube.com/playlist?list=PLf2g_NkFyyv5O5KmCXzuROjzWO_gxZ-ZN)
[IFRC GO 3w promotional video](https://www.youtube.com/watch?v=E1TuUEEMBRM&list=PLf2g_NkFyyv5O5KmCXzuROjzWO_gxZ-ZN)
[IFRC GO 3w guidance video ](https://www.youtube.com/watch?v=QiDwKVr5pxg&list=PLf2g_NkFyyv5O5KmCXzuROjzWO_gxZ-ZN&index=6&t=0s)

**Comment by imohkay** [comment]
@LukeCaley added links for reference and carousel on staging
@yellowumbrella-design carousel links updated on staging
@nanometrenat thanks for updated links for reference links :)

**Comment by imohkay** [comment]
@LukeCaley Hey, the following's been updated on staging:
- About text in nav changed to 'Resources'
- Links on about page have shortened text and appropriate style where links not available
- Added top padding for checkbox headings in field reports

Incase I've missed anything, let me know, and I'll quickly fix in the morning :)

**Comment by LukeCaley** [comment]
Thanks @imohkay - looking great and pushed to PROD today.

Some small hotfix changes anticipated in the next couple of days:

**GO User and Administrator Guides**
_Guidance on how to use and administrate GO_

**GO Reference Materials**
_How and why GO works_
 
And some updated links to IFRC youtube channel videos for Notifications, Field Reports and PER.

**Comment by imohkay** [comment]
@LukeCaley thanks for the heads up. I'm guessing new tickets will be opened for those...
