### ISSUE TITLE
[Staging] Epi Field Report - looking at completed FR

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1096]
## Issue
I successfully submitted an Epi Field Report in surge test site.  However when I look at my submitted report there are a few things that need further love.

In particular:

1. Actions Taken aren't split into Health vs Other (all jumbled up together)
2. The Injured/Missing/Dead/Displaced/Affected fields all show (even though these are not relevant for Epi Field Reports)
3. Date of Data is not with the other data fields (should be up with Source)

## URL
https://ifrc-go-feature-1004-epi-field-report.surge.sh/reports/9518

## Steps to reproduce
* submit an Epi-type Field Report

## Related feature
#1004 

## Criticality/Urgency
Should be resolved swiftly as there will be a lot of attention paid to these field reports.  Not critical blocker to the first Epi FR release however, as the information is correct just jumbled.

**Comment by batpad** [comment]
Thanks for flagging this @nanometrenat. These should ideally be fairly quick fixes.

**Comment by necoline** [comment]
I can work on the following:
- [ ] add action-categories to the actions
- [ ] remove Injured/Missing/Dead/Displaced/Affected fields
- [ ] move Date of Data to be by source.

**Comment by nanometrenat** [comment]
Hi @necoline @batpad thanks much better tho 2 still needs a touch more love!  Thank you.
1. actions correctly split by category (but only in cases where actions from both categories have been selected - otherwise no label) - I think this is OK
2. correctly showing Epi data fields BUT missing "Dead" field - this definitely needs to be added
3. date of data sitting with source - thanks

**Comment by karitotp** [comment]
Another thing that maybe need to re-order is `Planned international response`, which is in source.

![Screenshot from 2020-04-13 13-37-21](https://user-images.githubusercontent.com/11504548/79155916-813cca80-7d97-11ea-81b2-f3034850b3a4.png)

**Comment by nanometrenat** [comment]
@LukeCaley just letting you know that Dead field is missing when viewing completed Epi FR - I am guessing at this stage that this will be a bug that is carried forward but should be fixed asap.
https://dsgoproxyapp.azurewebsites.net/reports/9525

**Comment by nanometrenat** [comment]
Number 2 is fixed (Dead figures are now showing when viewing submitted FRs in Prod), and 1 and 3 were already fixed previously - thanks a lot.

Only bit outstanding on this one is @karitotp comment re Planned International Response (DREF etc.) showing at top near figures, rather than in the Response section where it should be (after Actions taken by others and before Contacts).  This is cosmetic (ordering) only, cheers

**Comment by mmusori** [comment]
Updated wireframe for the output Epi field report are found here:
https://projects.invisionapp.com/share/49WZCQ0QVTY#/screens/412009430_4-4-3_GO_FieldReport-Epi_Page

**Comment by mmusori** [comment]
Call with Gerg and decision taken to pull in Numerical details from the Field Report into the email notification regardless of the source. Also that the "Dead" field is the same between the epi field report and the other field report that is why there is only one place in the database.

**Comment by mmusori** [comment]
Feedback from Health on the new notification Email. 
1.	Recommend giving the source for the EPI data (otherwise there is often a lack of trust in the figures)
2.	If possible to include date as well, that goes a long way in eliminating the distrust.  Such as within the KEY FIGURES header, like KEY FIGURES (23 April 2020) 
3.	Also, there should probably be EPI key figure rules. “cases” is the SUM(“suspected”, “probable”, “confirmed”)

**Comment by nanometrenat** [comment]
@mmusori part 3 is not to do with notifications, suggest splitting into a separate ticket if desired (noting that it's possible NSs will fill in only cases and not the subdivision) cheers

**Comment by mmusori** [comment]
@nanometrenat thanks. The Health team is discussing how they would like that to work. Agreed this falls into the Field Report input template. We have been discussing this with Greg at length. Thanks again

**Comment by LukeCaley** [comment]
Seems there are two small issues to be resolved Xref: https://github.com/IFRCGo/go-frontend/issues/1096#issuecomment-618970225 @necoline 
@mmusori to please confirm if this is is all and then plan for UAT.

**Comment by mmusori** [comment]
The suggested changes based on discussion with Gerg and Roxxanne have been done. 
![image](https://user-images.githubusercontent.com/7780809/80351360-80656780-8872-11ea-92d7-b2535b009dae.png)

**Comment by mmusori** [comment]
Will close this ticket once the fix is in production.

**Comment by karitotp** [comment]
I could not see the changes, I am seeing it as it was previously :thinking: 
https://dsgoproxyapp.azurewebsites.net/reports/9548

**Comment by nanometrenat** [comment]
Moving back to dev/in progress as this is part of conversation @mmusori is to schedule

**Comment by mmusori** [comment]
The data is in Actions is split but the Socioeconomic needs to be a proper heading: 
![image](https://user-images.githubusercontent.com/7780809/82035615-0883a380-96a0-11ea-94b9-09b72231c308.png)
The output also includes Dead: https://dsgoproxyapp.azurewebsites.net/reports/9583
Indentation request by health is included. 
The logic for cases still needs specs in 4.3.

**Comment by nanometrenat** [comment]
@mmusori I believe the above is because of data config in Staging - and the action that was ticked in real life was actually called "Socioeconomic Impacts:  Livelihoods and cash support".  The above is an "Epi" Field Report not a "COVID" Field Report (and remember on the call with Sune we had manually edited the config data to see what was possible with Epi pre separate COVID build)
You can verify that for a COVID Field Report the headings are displayed correctly by looking at https://dsgoproxyapp.azurewebsites.net/reports/9582

Can you please update this ticket to advise if further work is required based on what you see in https://dsgoproxyapp.azurewebsites.net/reports/9582?

Thanks!

**Comment by mmusori** [comment]
@nanometrenat . For the Covid field report these is no issue. The issue is with the EPi field report. The title of the original ticket is on EPI field reports. So yes this is not an issue for Covid, this is an issue for EPI. So the issue needs to be resolved for EPI then we can close the ticket.

**Comment by nanometrenat** [comment]
The Epi Field Report doesn't have a socioeconomic section though?

**Comment by nanometrenat** [comment]
On call with Munu, agreed that there is no further work required on this ticket so closing.  Thanks all!
