### ISSUE TITLE
Content of automated emails / notifications

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#110]
Will send you guys via email, the content for the automated email and notifications soon.

**Comment by guipizzini** [comment]
You will get the content, tomorrow at the latest. thank you

**Comment by guipizzini** [comment]
Email has been sent to both of you with the content to be used. Thanks for the patience.

**Comment by guipizzini** [comment]
Hi @dereklieu could you confirm you received the email with the notification content? As well, if you could tell me if I have missed other notifications that the system will generate it would be great so I can work on the content for you to upload in the system. Thanks

**Comment by dereklieu** [comment]
Confirming that I've received this content, but have not had a chance to integrate it yet. I should have time to do that today and will let you know if I find any missing templates.

**Comment by guipizzini** [comment]
Do we have any notification that is missing content and that requires my action, @dereklieu ?

**Comment by dereklieu** [comment]
No, this can be closed.
