### ISSUE TITLE
Field Report - Actions Taken - ability to deprecate while still keeping historic data

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1101]
## Issue
At the moment, the Actions Taken for the various Field Report types are a "live" list.  So if an item is deleted from the Actions Taken list in back end then it does not show up when viewing historic field reports even if it had been selected at the time.

We need a way to be able to specify that a given action is active vs inactive.

- If Active then it should show as a tickbox on the New Field Report screen.
- If Inactive it should not show as a tickbox on the New Field Report screen, but should still be shown when viewing a previously-submitted FR where that action was selected.  Similarly it should also be returned in the API where relevant.

## URL
https://dsgocdnapi.azureedge.net/api/action/79/change/ - admin screen
https://dsgoproxyapp.azurewebsites.net/reports/new - new Field Report (Actions section)
https://dsgoproxyapp.azurewebsites.net/reports/9432 - viewing an existing FR

## Related feature
This is generic to all Field Reports rather than specific to Epi Field Reports, but relates to #1004 and #1098 

## Criticality/Urgency
It is expected that the list of actions for FRs will be updated several times in the coming months, so this should be addressed relatively swiftly.

**Comment by nanometrenat** [comment]
ALSO I am not sure what order the Actions display on screen but we should make sure we have the ability to explicitly specify order.  For the initial Epi FR implementation I input all the items in the order I wanted them to show - and they showed onscreen in that order.  However when I edited the wording of an item it then dropped to the end of the list.  However that wasn't always replicable (I couldn't get Other to drop to the end again despite editing it several times).  Actions ordering onscreen doesn't seem to correlate to order returned via the API either.  Weird!

**Comment by batpad** [comment]
On the ability to deprecate actions:

 - We should add an `is_active` flag for actions, set as True by default, and then only show actions that are marked as active to the user. This way we will preserve data about actions that are no longer "active", while still being able to hide them in the form. This should be straightforward.

 - With regards to ordering, I would highly highly recommend standardizing on alphabetical order or so. We can add an `order` numerical field in the admin and allow admins to set the order explicitly, but would really be in favour of sticking to predictable ordering like alphabetical. @nanometrenat can we make a separate ticket for the ordering of actions and keep this one to the topic in the title?

**Comment by nanometrenat** [comment]
> can we make a separate ticket for the ordering of actions and keep this one to the topic in the title?
Sure - the biggest problem with Alphabetical is that "Other" does not appear at the end - and also related items are distributed throughout the alphabet whereas it would be better to have them next to each other.  Will log a separate ticket.

**Comment by batpad** [comment]
There is now a flag in the backend (on staging) to mark an action as `is_disabled`. If an action is marked as disabled, it will no longer show up in the field report form, but data for past field reports that contained that action will be retained.

cc @nanometrenat

**Comment by nanometrenat** [comment]
Hi @batpad flag is showing in back end and correctly hides an action from the "new field report" form if it is unticked.

However, I can't see that flag in the Actions API response - should it be there?

**Comment by batpad** [comment]
> However, I can't see that flag in the Actions API response - should it be there?

It currently removes the action from the list of Actions served by that end-point entirely, since that end-point is used only to generate the actions list on the form. The "deprecated" actions should still show up in a Field Report where that action was associated.

If you think it's useful to have the disabled actions in that end-point, could add them back, but it helps to keep the data over the network to a minimum since we don't need disabled actions on the frontend for the field report any more.

**Comment by batpad** [comment]
Closing here as the actions API is not expected to contain deprecated actions. @nanometrenat if this is something you would still like, can we please ticket this separately, since the issue referred to in this ticket is done and deployed to prod?
