### ISSUE TITLE
[Staging] Source in numerical details is not updating correctly after edit a EFR

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1102]
## Issue
Editing an Epi Field Report, in the page of Situation, If you change the source of numeric details and save the editions, it does not update; what is show up is the same number in both sources. When you want to edit it again, show both too.

## URL
https://ifrc-go-fix-1096-report-summary.surge.sh/reports/9526
https://ifrc-go-fix-1096-report-summary.surge.sh/reports/9526/edit

## Steps to reproduce
Edit the source of the numeric details in the situation page.

![Screenshot from 2020-04-13 13-32-40](https://user-images.githubusercontent.com/11504548/79158482-09bd6a00-7d9c-11ea-80fc-ee8b34c41821.png)
_Epi field report summary_

![Screenshot from 2020-04-13 15-35-53](https://user-images.githubusercontent.com/11504548/79158750-80f2fe00-7d9c-11ea-869d-250d6ab4b109.png)
_Editing the Epi field report_

## Expected behaviour
What I expect is only the sources is updated and the data is not duplicated.

## Criticality/Urgency
Not a blocker.

**Comment by batpad** [comment]
Thank you for the catch, @karitotp .

This seems pretty must-fix. @necoline let me know if you have any ideas here. Am going to look.

**Comment by batpad** [comment]
I tested this with a non-epidemic field report, and the behaviour is the same. It's a bit hard to tell if this issue always existed, going to dig a bit more.

**Comment by nanometrenat** [comment]
As it's an existing bug (rather than regression) I suggest fixing it in next release alongside #987 (which is also an existing bug about Source)

**Comment by nanometrenat** [comment]
Suggest checking again after figures rework under https://github.com/IFRCGo/go-frontend/issues/1161

**Comment by mmusori** [comment]
This has been resloved as part of 1161
![image](https://user-images.githubusercontent.com/7780809/82040855-87300f00-96a7-11ea-8839-33d2b24356ee.png)

**Comment by karitotp** [comment]
I tested again updating these numerical details and now it is updating correctly; the numbers and the source. 

In case you delete the number, instead of changing it, it is not being updated and the old number is still kept.

cc. @batpad

**Comment by nanometrenat** [comment]
@mmusori can this be closed?

**Comment by mmusori** [comment]
This worked in staging . Was resolved under 1161.
