### ISSUE TITLE
Field Report: URLs shared in field report do not show as links on pages generated from field report

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1108]
## Issue
If a user adds a URL in the "Situational Overview"/"Description" field when filling and submitting a field report through the frontend, the URL does not appear as a link on the page generated from the field report even though the "Situational Overview"/"Description" field has a rich-text editor in the backend. Adding a URL (as a link) through the backend to this field does come through correctly, but it is practically never or very seldom that users modify field reports through the backend.

Field with URL in field report
![image](https://user-images.githubusercontent.com/52411237/79330241-7d38b600-7f19-11ea-9a94-f05e67dc8faa.png)

URL on page generated from field report
![image](https://user-images.githubusercontent.com/52411237/79330291-9477a380-7f19-11ea-8338-41c825ae5f51.png)

URL on the emergency page created from the field report
![image](https://user-images.githubusercontent.com/52411237/79330415-c852c900-7f19-11ea-9702-b130d888f7e2.png)

backend of field report
![image](https://user-images.githubusercontent.com/52411237/79330601-1a93ea00-7f1a-11ea-9423-26fdf41f2663.png)

## Expected behaviour
URLs shared through the frontend fields should show up as links in the field report and emergency pages generated from the field report - especially because these respective fields have RTEs enabling the sharing of links in the backend

## Related feature
#1011 
#931

**Comment by teklal** [comment]
This would be great to have addressed as in the new COVID FR we are even asking users to use URLs in field report fields but these do not show as links on the frontend
![image](https://user-images.githubusercontent.com/52411237/80979203-56d6ae00-8e27-11ea-9f13-fbfec3b83e7d.png)

**Comment by batpad** [comment]
This can be tested at https://ifrc-go-fix-1108-description-url-field-report.surge.sh/reports/9432

The only problem is that if a URL is added via the Rich Text Editor in the backend, it will show up with HTML tags in the frontend, but this would be an existing issue with or without this change, some discussion over at https://github.com/IFRCGo/go-frontend/pull/1476

If adding a URL to the field report form on the frontend causes URLs to be correctly linked, I would be in favour of moving ahead here.

@karitotp could you please test that adding a URL in these fields correctly makes them links on the field report detail page?

**Comment by karitotp** [comment]
@batpad, the Urls added in Source details and Situational Overview fields, both are displayed as links in the page.
![Screenshot from 2020-07-31 09-27-17](https://user-images.githubusercontent.com/11504548/89045321-f2859680-d310-11ea-839e-d9f77fc6f0f6.png)

The generation of the links should apply also to the url added in the action take fields? If so, these urls are not displayed as link in the page

![Screenshot from 2020-07-31 09-19-54](https://user-images.githubusercontent.com/11504548/89045612-6b84ee00-d311-11ea-9c60-cc0e5da525ac.png)

**Comment by batpad** [comment]
@karitotp thanks!

@LukeCaley @teklal @nanometrenat - URLs entered in the Situational Overview and Source Details should now show up as clickable URLs on the field report frontend. Can be tested at https://ifrc-go-fix-1108-description-url-field-report.surge.sh/reports/9432 . If this looks okay, would be great to merge to staging - do we want to implement it across all text fields on the field report?

cc @necoline

**Comment by batpad** [comment]
This is now in staging.

**Comment by LukeCaley** [comment]
@teklal - would you mind testing with a number of known scenarios please?

**Comment by LukeCaley** [comment]
As @teklal has now left the team, reassigning this to @mmusori 
cc @nanometrenat @tovari

**Comment by tovari** [comment]
@batpad, @LukeCaley urls starting with http are clickable now. Urls starting with www are not clickable. I suggest to move this case to Done and open a new one for the www links on the new board.
