### ISSUE TITLE
[Staging] Epi field report: date of data field marked as mandatory but can proceed without filling it

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1112]
## Issue
The "Date of Data" field on the page with the figures on cases etc is marked as mandatory with an asterix but I am able to proceed without having filled this field.

As the fields with figures are not mandatory I'm not sure what the ideal solution is here - whether to remove the asterix or make filling at least one field with figures mandatory?

Thoughts @nanometrenat @LukeCaley ?

![image](https://user-images.githubusercontent.com/52411237/79341443-1670c800-7f2c-11ea-8b72-06a1b8859fe9.png)

## Steps to reproduce
Start filling an Epi FR and click "continue" on the page with the figures without giving a date.

## Related feature
epi field report and general field report issues

I don't see this as a major major problem but worth noting.

**Comment by teklal** [comment]
Sorry @necoline, noticed this just after finishing the call!

**Comment by nanometrenat** [comment]
There was a conversation about this on the wireframes - suggest taking a look at that, thanks @teklal

**Comment by mmusori** [comment]
Proposed logic not yet implemented. If data is entered for cases or Dead then the date become mandatory. @GregoryHorvath We had a discussion about this.

**Comment by batpad** [comment]
Just confirming this logic @kamicut - if any data is entered in the fields for Cases, Dead, etc. - then Date of Data must be filled in.

**Comment by kamicut** [comment]
This is ready for QA in https://github.com/IFRCGo/go-frontend/pull/1281

**Comment by LukeCaley** [comment]
@teklal and @karitotp to test

**Comment by teklal** [comment]
Tested and seems to work now, thanks!

**Comment by batpad** [comment]
This is now on staging.

**Comment by karitotp** [comment]
This is working good!

**Comment by LukeCaley** [comment]
@teklal can you check that this is working on PROD and close if so - thanks!

**Comment by karitotp** [comment]
It is working as expected, it is mandatory when the numeric fields is fill.

**Comment by teklal** [comment]
This works now, thanks!
