### ISSUE TITLE
[PROD] Adding a response document through Situation Report section in backend gives an error

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1117]
## Issue
When trying to add a response document (situation report on the backend) via the Situation reports section in the backend (https://prddsgocdnapi.azureedge.net/api/situationreport/add/) it says adding the doc was successful but also gives an error. The document shows up on the panel of recent actions but when clicking on that link it doesn't go anywhere and again gives the same error "Situation report with ID "None" doesn't exist. Perhaps it was deleted?"

![image](https://user-images.githubusercontent.com/52411237/79437120-0d3a3680-7fd2-11ea-98e9-557b2d72a311.png)

The report doesn't either show up on the list of added response documents or the frontend, except for sometimes when it saves the document on the frontend despite the error - but not every time.

## Steps to reproduce
Safer to test on staging where the same issue has been observed.
Go to https://dsgocdnapi.azureedge.net/api/situationreport/add/ to add a response doc.

## Expected behaviour
A user should be able to add a report through this way without errors the same way they are able to add these documents via the respective section on an emergency page backend. The pinning of documents should also work when adding a document through https://prddsgocdnapi.azureedge.net/api/situationreport/add/

## Related feature
https://github.com/IFRCGo/go-frontend/issues/1008#issuecomment-614075168  the "pinning" of documents doesn't work when adding a document this way

## Is there a workaround?
Adding the response document through the situation report section on the emergency page backend.

**Comment by nanometrenat** [comment]
Hi Greg, I spoke too soon putting this to backlog.  I just uploaded 3 sitreps via the https://goadmin.ifrc.org/api/situationreport/add/ screen (i.e. not the emergency page).  All 3 were same format and same filename apart from version numbers/dates.  2 uploaded fine but then the third got the error message below.

Also, when I go back to https://goadmin.ifrc.org/ I can see all 3 down the right hand side in Recent actions, but clicking on any of them gives the error "Situation report with ID "None" doesn't exist. Perhaps it was deleted?".  In all 3 cases though the document is showing correctly (and downloads correctly) on the emergency page.  Can you please investigate why this is occurring?  It's intermittent, so hard to troubleshoot.

Thanks a lot as always.

![image](https://user-images.githubusercontent.com/33625192/82259500-fe8dc900-995b-11ea-96a7-eeb931d0c981.png)

**Comment by batpad** [comment]
@GregoryHorvath have added this to the 4.3 project board as In Progress. Feel free to move it if it is not so - but this does seem like an open issue we need to work? Let me know if I can help.

**Comment by GregoryHorvath** [comment]
@nanometrenat @batpad Found a hiccup in the code here (this is half-related to the original issue which will be fixed alongside).

If a **new** Sit.Rep. has multiple attachments, they are created like:
- newsitrep
- newsitrep 1
- newsitrep 2
- ...

making them if they were separate Sit.Rep.s for all attachments to be reachable there (max 30).

If a Sit.Rep. is getting **changed** then it's just overwritten. Here comes the problem when someone would attach multiple files to an existing Sit.Rep.

**What should happen in a situation like this? Should it also re-create new Sit.Rep.s with numbers based on the attachments' count?**

Code part: https://github.com/IFRCGo/go-api/blob/567056272009687f38faef5999ff9693aeb6ceaa/api/admin.py#L491

**Comment by nanometrenat** [comment]
To confirm our discussion, the multiple-attachments scenario is very much a corner case, the base case to make sure is working reliably is adding/editing one sitrep at a time (whether it's a URL or a document attached).  THANKS

**Comment by GregoryHorvath** [comment]
@teklal @nanometrenat Deployed the fix to staging.

**Comment by LukeCaley** [comment]
As discussed on the call 28/05, we believe this is a low-risk enhancement, difficult to test, but likely to fix the bug reported here.  Correct and good to GO cc @batpad @GregoryHorvath @teklal  @nanometrenat

**Comment by nanometrenat** [comment]
Closing as this fix has been in place for a month now and I haven't had any reported issues.  I have myself only uploaded a few docs this way, but they did work!  Cheers
