### ISSUE TITLE
Field Reports page - auth required (public FRs should not require auth)

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1118]
## Issue
As an unauthenticated user, when going to the Emergencies page and clicking through to view Field Reports (all regions or specific regions), it then prompts me to log in
https://go.ifrc.org/reports/all

I would expect that if I'm not logged in I would be able to see the list of field reports with visibility=public, and if I am logged in then I would see the list of field reports that I am authorised to view (Membership / IFRC)

Similarly, if I am looking at an Emergency page that has a linked Field Report then I am prompted to log in before I can view it.

Speaking on the GO call with @LukeCaley right now it sounds like this isn't a deliberate requirement to get users to log in in order to see PUBLIC field reports - so assuming Luke is happy then presumably we should be making the Public field reports Public.  Luke to confirm.

## Impact
Impact is that the general public can't see Field Reports even if visibility is set to Public.

**Comment by batpad** [comment]
Fix for this can be tested at https://ifrc-go-fix-1118-public-frs.surge.sh/reports/all 

cc @karitotp @nanometrenat

**Comment by karitotp** [comment]
The visibility of the list of public and not public reports to a non logged user is working well in the all report page https://ifrc-go-fix-1118-public-frs.surge.sh/reports/all, but seem this is not working well in the list per regions that is showing even the reports visible to RCRC and IFRC in the list when the user is unauthenticated.

I created a report with visible to IFRC: "Auth2 field report" and this is not list in the all report page https://ifrc-go-fix-1118-public-frs.surge.sh/reports/all, but it is listed in https://ifrc-go-fix-1118-public-frs.surge.sh/emergencies/all?region=1

cc. @batpad

**Comment by nanometrenat** [comment]
Hi @karitotp can you please take another look?  The https://ifrc-go-fix-1118-public-frs.surge.sh/emergencies/all?region=1 link shows _emergency_ list rather than Field Reports list (an emergency page is created automatically for each Field Report that is submitted that is not linked to an existing emergency).
FYI the list of Field Reports for Americas is https://ifrc-go-fix-1118-public-frs.surge.sh/emergencies/all?region=1

In terms of the visibility levels, we need to test that:
* field reports only appear in LISTS (such as the above links) for users that those FRs should be visible to.  Lists include those on
** /emergencies (several levels of filter params e.g. all and by region)
** /reports (several levels of filter params e.g. all and by region)
** individual emergency pages (e.g. this one has 5 associated Field Reports and if not logged in the user sees "You must be logged in to view this. Login" even though all the 5 Field Reports are visibility=public https://ifrc-go-fix-1118-public-frs.surge.sh/emergencies/3539)
* links to specific Field Reports (whether navigation via the platform or whether via direct URL entry) only show for the people who are entitled to see them e.g. https://ifrc-go-fix-1118-public-frs.surge.sh/reports/9256 is public so should be visible for everyone whether or not logged in - whereas if a FR is visible to a more restricted set of users then they should see the login screen or whatever the standard message is when people don't have permission to view something.

Thanks a lot

**Comment by karitotp** [comment]
Thanks @nanometrenat for the clarification and for the detailed lines for testing!

> field reports only appear in LISTS (such as the above links) for users that those FRs should be visible to. Lists include those on

All this is working as you mention above.

> links to specific Field Reports (whether navigation via the platform or whether via direct URL entry) only show for the people who are entitled to see them e.g. https://ifrc-go-fix-1118-public-frs.surge.sh/reports/9256 is public so should be visible for everyone whether or not logged in - whereas if a FR is visible to a more restricted set of users then they should see the login screen or whatever the standard message is when people don't have permission to view something.

I can not see this report https://ifrc-go-fix-1118-public-frs.surge.sh/reports/9256 when I am not logged, the page redirect me to login page, and as you mention, this is a public report.

@nanometrenat, related to this, if the user is not logged and is seeing the list of the public reports (all or per region), can the user go to any specific reports in the list? When I am not logged and I want to see one public report in https://ifrc-go-fix-1118-public-frs.surge.sh/reports/all?region=1, in all cases the page shows me the login screen.

**Comment by nanometrenat** [comment]
Thanks @karitotp so sounds like more work is required to make the Public FRs actually public!  Need to ensure you can open and view them, and that they appear in the list on the emergency page etc.

Important to be sure that even for logged-in users the IFRC vs Membership thing is working also.  @batpad can you please ask a dev to take another look?  Thanks heaps

**Comment by batpad** [comment]
@kamicut - it seems like we are close here, just need to handle login appropriately on the Field Report page: `/views/field-report.js` . Thanks for the catch @karitotp and all the clarifications @nanometrenat - @kamicut let me know if it helps to look at this together - ideally this should be relatively straightforward.

**Comment by karitotp** [comment]
This is working well now!

**Comment by nanometrenat** [comment]
Moving to Done as this was released to Prod this morning - to close when happy - initial signs are good!

**Comment by nanometrenat** [comment]
Hi, this needs further work -re the "individual emergency pages" test in comment https://github.com/IFRCGo/go-frontend/issues/1118#issuecomment-625752849 above

At the moment if (while not logged in) I go to an Emergency page that has Public field reports - e.g. Myanmar, https://go.ifrc.org/emergencies/4278#details - it still says "You must be logged in to view this. Login" in the Field Reports section of the emergency page.  I _should_ be able to see the list of public FRs there.  Can you please fix?

On a good note, if I go to the list of all FRs (i..e not by country) on the Emergencies page https://go.ifrc.org/emergencies then the Myanmar one does appear there, and I can click through to it fine (or access via the direct link).

**Comment by batpad** [comment]
@kamicut could you look at this, re: the issue on emergency pages? Hopefully is a simple fix?

**Comment by batpad** [comment]
This is ready to test. cc @teklal @karitotp .

**Comment by GregoryHorvath** [comment]
> This is ready to test. cc @teklal @karitotp .

@teklal @karitotp Testable with the frontend changes here: https://ifrc-go-fix-1118-emergency-pages-gregsurge.surge.sh/

**Comment by karitotp** [comment]
> @teklal @karitotp Testable with the frontend changes here: https://ifrc-go-fix-1118-emergency-pages-gregsurge.surge.sh/

I try to test in this url but it seems does not working correctly, the pages are not loading correctly and it does not allow me to log in.

I tested in the staging url https://dsgoproxyapp.azurewebsites.net/emergencies/3913#details and the list for the FRs in a individual emergency page is working as the expected. The public FRs is listed correctly, and if the FR is not public, it does not in the list if I am not log in.

**Comment by teklal** [comment]
Tested the different visibility levels of field reports showing on an emergency page and that works now (e.g. public field reports being listed on the emergency page even when not logged in), thanks!

One thing that I noticed is now different on staging and prod and I assume is related to this: there have been some pieces of information (emergency overview i.e. figures, situation overview and contacts) that have been pulled from the field reports and shown on the (public) emergency page no matter what the visibility setting of the field report. These pieces of info now follow the same visibility restrictions as the field report and hence would not always show on the emergency page.

I think we need to discuss if this change is desired or if we want the figures, situation overview and contacts to continue to be pulled/shown no matter what the field report settings. Flagging especially for @mmusori, what is your take on this?

**Comment by batpad** [comment]
@teklal that looks like a really good catch, and likely something that merits discussion.

**Comment by batpad** [comment]
Based on discussion, let's do the following:

 - Revert the API changes to implement permissions in the API
 - Handle the field report list display on the frontend, checking user permissions and omitting field reports from the frontend view if the user does not have permissions to see the detailed field report.

cc @GregoryHorvath

**Comment by GregoryHorvath** [comment]
@teklal @karitotp Reverted the changes back and @batpad made the frontend handle the visibility for now. All deployed to staging and should be testable.

**Comment by LukeCaley** [comment]
@karitotp it would be great if you could test this today so that we can release 4.3.5 tomorrow

**Comment by karitotp** [comment]
- Visibility of the list of FRs is showing for user that can see them, according if they are public or not.

- Visibility of the list of public and private FRs in a emergency page are working according the permissions. The public FRs are listed even when I am not logged and the private FRs is listed only when the user is logged.

- About the details of a Field report (emergency overview and contacts) that is showing in a Emergency page, they are displayed even if the FR is not pubic and the user is not logged. 
I created a no public FR https://dsgoproxyapp.azurewebsites.net/reports/9615 and the numbers in emergency overview and the contacts are showing in the emergency page even when I am not logged https://dsgoproxyapp.azurewebsites.net/emergencies/3913#details

@LukeCaley @teklal

**Comment by LukeCaley** [comment]
@nanometrenat could you check that this is working in PROD and close the ticket if so - thanks!

**Comment by karitotp** [comment]
It is working in production as is described here https://github.com/IFRCGo/go-frontend/issues/1118#issuecomment-637027970.
