### ISSUE TITLE
[PROD] Epi Field Report - notifications - Key Figures

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1119]
## Issue (Missed Requirement)
The Epi Field Report introduced a new set of Key Figures (Cases | Suspected Cases | Probable Cases | Confirmed Cases | Dead).  These are input correctly on Field Report, however they don't pull through to the associated automatic "New Field Report" notification emails.

The notification emails still have the old Key Figures fields (Affected | Injured | Dead | Missing | Displaced | Assisted).  Need to be amended so that Epi notifications contain the Epi fields.

## Related feature
#1004

**Comment by mmusori** [comment]
Wire frames for the Emergency page were developed in February but the latest wireframes with updated UI/UX are found here: https://projects.invisionapp.com/share/59WZFUYEFTM#/screens/412675366_4-2-1_GO_Specific-Emergency_Epi

**Comment by GregoryHorvath** [comment]
Deployed to staging and can be tested.

**Comment by mmusori** [comment]
Thanks Greg. 
Will test tonight. 


Sent from Yahoo Mail for iPhone


On Thursday, April 23, 2020, 19:22, Horvath Gergely <notifications@github.com> wrote:




Deployed to staging and can be tested.

**Comment by LukeCaley** [comment]
@mmusori to confirm UAT pass or not.

**Comment by nanometrenat** [comment]
@mmusori re requirements

**Comment by mmusori** [comment]
UAT pass

![image](https://user-images.githubusercontent.com/7780809/82038601-0d4a5680-96a4-11ea-9b7f-c76ecaef902c.png)
This is in production as part of a different ticket.
