### ISSUE TITLE
3W: Make UI consistent with other pages and forms

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1121]

**Comment by lauripynnonen** [comment]
How do we test this?

Maybe related: have there always been gaps between the items on the form 
![image](https://user-images.githubusercontent.com/8285694/79993181-c4441f80-84b4-11ea-933b-ed7d178fe833.png)
or have I just recently started to notice them?

**Comment by frozenhelium** [comment]
@lauripynnonen That's one of the things. I made the this form style more similar to the field report form. Also the 3W tab itself looks more like other tabs (i.e. background, shadow, spacing, etc)

**Comment by karitotp** [comment]
It Iooks similar to the other forms to me. I think some minor differences with the Field Report form is the font size, such us the header of fields that also are in lower case,  the alert on the empty required fields and the submit button has a different style.

![3wform](https://user-images.githubusercontent.com/11504548/80102420-50e3f180-8538-11ea-8354-9ff3090191d6.png)
