### ISSUE TITLE
[PROD] Field report map problems, autocentering off and illegible labels

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1126]
## Issue
Field report maps for some countries do not behave the way they should. 

For a number of countries the autocentering is off by quite a bit - in some cases this means that the affected area does not even show on the default view of the map. 
Here is a non-exhaustive list of countries (with example URL) for which I've observed this:
- Tanzania https://go.ifrc.org/emergencies/3979#details
- Niger https://go.ifrc.org/emergencies/3974#details
- Peru https://go.ifrc.org/emergencies/3997#details
- Netherlands https://go.ifrc.org/emergencies/4180#details
- DRC https://go.ifrc.org/emergencies/4188#details
- Burundi https://go.ifrc.org/emergencies/4189#details
- Papua New Guinea https://go.ifrc.org/emergencies/4190#details

For some countries it's more subtle, just extremities of borders get cut off, such as for
- Lebanon https://go.ifrc.org/emergencies/4020#details

For some countries only the affected area gets colored, while the rest of the country has the same color as neighbouring non-affected countries:
- Iran https://go.ifrc.org/emergencies/3999#details (in addition the label text is quite small)
- Egypt https://go.ifrc.org/emergencies/4046#details
- The Gambia https://go.ifrc.org/emergencies/4076#details
- DRC https://go.ifrc.org/emergencies/4188#details

There are countries where the label text is barely legible because it's either too small or white because the area is close to a water body (which are colored white on the map):
- Lebanon https://go.ifrc.org/emergencies/4020#details (Beirut, white on white)
- Palau https://go.ifrc.org/emergencies/4114#details (barely anything legible because of white on white)
- Chile https://go.ifrc.org/emergencies/4029#details (because of islands, zoom is far out and label text very small)
- France/New Caledonia https://go.ifrc.org/emergencies/3990#details (for countries with overseas territories the map view is not ideal also in other ways) 
- Guinea https://go.ifrc.org/emergencies/4048#details (close to waterbody, white on white)
- Mauritania https://go.ifrc.org/emergencies/4051#details

## Expected behaviour
Map should show whole country and styling should be such that especially the important labels are legible.

## Related feature
#938

**Comment by teklal** [comment]
Adding Netherlands to the list of countries where the whole country doesn't even show on the map and because of overseas territories the default view is mostly looking at sea.
https://go.ifrc.org/emergencies/4180#details

**Comment by batpad** [comment]
@geohacker tagging you here to look at some point.

**Comment by nanometrenat** [comment]
Is this still an issue, given UI rewrite and all the other work since 2020?

**Comment by nanometrenat** [comment]
In "Ticket time" document @davidmuchatiza advises _we can close this one since much of the issues were addressed-I will create another focusing on the few yet to be addressed_
Hence closing now as stale issue.
