### ISSUE TITLE
[PROD] Parent Emergency creating additional records in emergency

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1128]
## Issue
In the Global COVID-19 emergency page back end there are now 10 rows for Parent Emergency.  This may perhaps correlate (?) with the fact that the page has been edited 12 times since the release?

![image](https://user-images.githubusercontent.com/33625192/79694108-b1d8a480-826e-11ea-963f-0dc807d4e908.png)

Not sure what implications this will have, but think it should be investigated before the Merge Emergencies feature is used for real.

## Related feature
https://github.com/IFRCGo/go-frontend/issues/1010

## Impact/Severity
Unknown

@teklal @GregoryHorvath FYI

**Comment by nanometrenat** [comment]
Sure enough, the global page has been saved a few more times since then (with the manual workaround for uploading-then-deleting documents just to get a link - pending #1006 build), and there are now even more Parent Emergency rows @LukeCaley

**Comment by batpad** [comment]
Thanks for the catch @nanometrenat - fix here: https://github.com/IFRCGo/go-api/pull/673 - can confirm this was not a data issue, purely a bug in how that data was rendered for non super-users.

**Comment by nanometrenat** [comment]
hi @GregoryHorvath @batpad to confirm, the screenshot above was from me logged in as me (i.e. as a superuser)...

**Comment by teklal** [comment]
Checked now on staging and all seems good.

To note on the original issue (as is still atm in prod) - not only do the lines with the parent emergency text show up multiple times, but the box for assigning the parent emergency does not appear at all. I suppose that is fixed in https://github.com/IFRCGo/go-api/pull/673 as this seems ok atm on staging right now?

**Comment by GregoryHorvath** [comment]
@teklal Somehow I still couldn't reproduce that behaviour neither locally or on staging. Is that still happening after this fix? I can see it may be correlated but not 100%.

**Comment by nanometrenat** [comment]
Closing as I don't now have multiple parent emergency rows showing when I log in.  Remaining issue to make this work tracked under Tekla's ticket above
