### ISSUE TITLE
[PROD] Server Errors when editing emergencies/Field Reports

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1129]
## Issue
Hi, I mentioned in Teams that I have been having Server Errors (500 errors) editing Emergency pages in Staging, but am now getting 500 errors in Production.  Just got one when editing a *Field Report* - happened twice, on two different FRs.

## Steps to reproduce
I was in Admin site - https://goadmin.ifrc.org/api/fieldreport/12337/change/ - only change I made was to delete the "Event" it was associated with, and select a new event to associate it with, and clicked save.

Got 500 error.  When I went in to look at the screen again it had actually saved the change correctly though (although the audit trail had extra extraneous info).

Same thing happened when I edited FR 12364 - I made the changes as per above and got a 500 error.  Unfortunately didn't have dev tools turned on so can't tell you exactly what the issue was.

**Comment by nanometrenat** [comment]
Again just got a 500 error in Prod with https://goadmin.ifrc.org/api/event/3972/change/ - only change was to add in some snippets (all on the existing tabs)

@LukeCaley

**Comment by nanometrenat** [comment]
To confirm re the above, when getting 500 errors as above this is causing the whole page to show only 500 Server error onscreen (can't see usual site, and also not a white screen)

**Comment by batpad** [comment]
@nanometrenat will be great to see if we can figure out some test case to make this reproducible on staging. I have tried making a few edits and been unable to reproduce so far.

In the meanwhile, we are working urgently on https://github.com/IFRCGo/go-api/issues/672 to make sure we get detailed stack traces whenever there is a 500 error to be able to more clearly spot the reason for the error(s).

**Comment by nanometrenat** [comment]
Again got a 500 server error onscreen in Production just now (23:00ish GVA time on 29 April) when editing the Global COVID emergency.  The only thing I changed was 10 characters within the content a snippet (no other changes anywhere on the Emergency) so not sure why I got the 500.  Was it logged?

**Comment by nanometrenat** [comment]
Closing as I haven't had 500 errors when editing emergencies in recent days.  Will reopen or log new ticket if the gremlins happen to reappear.  Thanks!
