### ISSUE TITLE
[PROD] Subscription preferences show up multiple times on Notifications tab

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1130]
## Issue
On the notifications tab on a user's account page, there is the possibility to subscribe to notifications based on different choices e.g. new emergencies based on disaster types, regions etc.

There is something that has happened (potentially with the last push to prod) so that all of these choices show up multiple times. E.g. disaster types show up not only as a tickbox for each type but these tickboxes as many times as there are different disaster types.

![image](https://user-images.githubusercontent.com/52411237/79730608-5e5b6a80-82f1-11ea-930b-52049df854e9.png)

for disaster tyes now:
![image](https://user-images.githubusercontent.com/52411237/79730639-687d6900-82f1-11ea-8b3f-d26bfcc1c993.png)

how it was before:
![image](https://user-images.githubusercontent.com/52411237/79731087-10933200-82f2-11ea-995c-4b2336a5f267.png)

**Comment by teklal** [comment]
Just discovered another location on GO with this same problem (sorry @GregoryHorvath) - the ready ERUs on the Deployments page https://go.ifrc.org/deployments

![image](https://user-images.githubusercontent.com/52411237/79881131-23406080-83f1-11ea-8a6e-01dd3e39da3e.png)

**Comment by GregoryHorvath** [comment]
Accidentally clicked on closing the issue, sorry for that.

**Comment by LukeCaley** [comment]
@teklal to confirm UAT pass or not.

**Comment by teklal** [comment]
Checked on staging and checkboxes appear only once on Notifications tab and Deployment page, so that aspect of this fix works now.

Tested quickly the functionalities of the checkboxes and they seem to working as well - the filtering based on the checkboxes on the Deployments page and subscribing to specific types of notifications.

So all good.

**Comment by karitotp** [comment]
- The tickboxes in Disaster types on the user's account page are not duplicated and they look correct now.
- The ready ERUs on the Deployments page looks good now.
![Screenshot from 2020-04-27 10-01-37](https://user-images.githubusercontent.com/11504548/80387495-5316ba80-886e-11ea-9859-5bd26a5eaf39.png)

**Comment by LukeCaley** [comment]
@teklal could you smell test this and, if all good, please close and move to done.  Thanks

**Comment by nanometrenat** [comment]
@teklal I think this can be moved to Done and closed now, right?  I think it's good in Prod

**Comment by teklal** [comment]
Thanks @nanometrenat for checking in. So indeed, the checkboxes appear and filter correctly on the pages in prod. I haven't forgotten about this ticket but hadn't closed it yet because I've been "testing" the functionality behind the subscriptions checkboxes now slowly over the past days (it takes a bit more time in prod as one can't just create a bunch of new test field reports of different types to see if notifications come through :D). But so far it seems also the functionalities work as they should so from my side it's good to close and move to Done now.
