### ISSUE TITLE
Rich text summary information for submitted field reports shows up in a messy way on Notifications tab

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1131]
## Issue
Under the notifications tab in the accounts page of a user, it shows the field reports that this user has submitted. At the moment it shows the name of the field report and the date it was last updated. If a summary was given, this information will also show. 

![image](https://user-images.githubusercontent.com/52411237/79738952-c57f1c00-82fd-11ea-88ea-a37edb6ae27a.png)

The problem is that if rich text editing was used for this field (currently possible only via backend edits but to be possible through the frontend as well), the info will show the info in a funky way

![image](https://user-images.githubusercontent.com/52411237/79738888-aed8c500-82fd-11ea-807f-35d68676e043.png)

I observed this in Staging but expect this to be the same in prod but can't test there as I haven't submitted any field reports in the live environment.

## Expected behaviour
Either fix the way the rich text shows on the page or then just leave out the summary info completely. To be discussed.

## Related feature
#1011

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/931
