### ISSUE TITLE
Show emergencies from past 6 months in "Recent emergencies" on a country page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1132]
The "Recent Emergencies" box on a _country page_ currently shows emergencies that started in the past month. Due to the current ongoing pandemic, emergency pages on GO are now relevant and need to be accessed easily from a country page for a longer time period than just 30 days. Hence we would like to change the time filter of emergencies showing up in this box to cover the past 6 months.

An example of the box in question below

![image](https://user-images.githubusercontent.com/52411237/79855012-a7332200-83ca-11ea-9802-cffd0300d8d8.png)

(*No change* required for the time frame of emergencies shown on the global Emergencies page)

**Comment by nanometrenat** [comment]
Actually @LukeCaley given we are now in May I think this needs to be expanded to perhaps show emergencies in the last 12 months rather than 6 months... thoughts?

**Comment by LukeCaley** [comment]
Agreed and this should be in the priority easy win list for devs @batpad

**Comment by karitotp** [comment]
:heavy_check_mark: In the list of Recent emergencies (on a country and a region), are shown the emergencies of the past 12 months.

In the general Emergencies page are shown the emergencies of the last 12 month too, but the header title is saying "last 30 days" https://dsgoproxyapp.azurewebsites.net/emergencies
![Selection_001](https://user-images.githubusercontent.com/11504548/82243808-d2dff400-9905-11ea-849a-4716b1d7d81d.png)

**Comment by kamicut** [comment]
Before the PR i introduced, when an emergency table was marked with "show recent only", selecting "all" for the start date would show only the past 30 days. 

I changed "recency" in the app to be last 12 months, which affected other tables.

I can solve this in 2 ways:
1. Move "recency" back to meaning last 30 days, but make an exception for the country pages so that they have a different notion of recency which is equal to 12 months. This means when selecting "all" in the start date you'll get the last 12 months.

2. Move "recency" back to meaning last 30 days, but remove the recency requirement for country pages, which would mean that selecting "all" will give all emergencies.

Which would you prefer?

**Comment by nanometrenat** [comment]
When the original ticket was logged, the intention was to leave all other places on the platform the same (i.e. recent emergencies should show only past 30 days).

The only intended change was to the *country* pages, where when you first load the page you see the last year.  So sounds like option 2 is the one to go with - though I'm not sure what you mean by the dropdown?

**Comment by kamicut** [comment]
I've reverted the previous PR and made it such that recent emergencies on the country page are for the past year https://github.com/IFRCGo/go-frontend/pull/1261

> I'm not sure what you mean by the dropdown? In any case for country pages (like for everything), when "all" is selected we still need to show "all"!!

There is a drop down when you click on "Start Date", that allows you to pick "anytime", "last week", "last month", "last year". "Anytime" is selected by default, and prior to this ticket, when "Anytime" is selected for emergencies, on the country pages, it would only show the past 30 days. In the new PR I made the "Anytime" selection show the last year. You can still click on "Show all emergencies" to go to all emergencies.

**Comment by nanometrenat** [comment]
Moving to Done as this was released to Prod this morning - @teklal to close when happy!

**Comment by batpad** [comment]
@teklal please close when happy :-)

**Comment by nanometrenat** [comment]
@anamariaescobar @LukeCaley the COVID emergencies have started dropping off NS country pages again (as now we're out of the 12 month timeframe they're no longer considered 'recent' emergencies).  Means that users [such as FDRS team, as a handy example] have extra clicks to hunt down the relevant emergency.  Especially as searching for e.g. "Iran COVID" doesn't return the Iran COVID emergency page but rather returns all sorts of other countries' field reports not the COVID emergency page for the country I've searched for.
![image](https://user-images.githubusercontent.com/33625192/108708713-afbe3100-7576-11eb-916b-23e1398971b9.png)

Is it worth considering either a) extending the 'recent emergencies' timeframe again or b) figuring out another plan to keep the COVID pages visible?  Thanks loads and kia ora from Welli
