### ISSUE TITLE
Guidance notes for Epi Field Report

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1135]
The following changes which will need to be reversed in 2 months should be made on the Field reports. It is only changing the guidance text not the functionality. 
1.	Put in a line (If Covid-19 select “Epidemic” as the disaster type) 
![image](https://user-images.githubusercontent.com/7780809/79872685-63e6ac80-83e6-11ea-95bd-b948aebe94b9.png)
2.	Change the Guidance for the search to (For Covid-19 Field Reports,  please link to the country specific emergency page if one already exists. Please do not link to the Global emergency page. )
![image](https://user-images.githubusercontent.com/7780809/79872332-f63a8080-83e5-11ea-9f67-6c9482a45687.png)

**Comment by LukeCaley** [comment]
@mmusori @teklal to confirm UAT pass or not.

**Comment by teklal** [comment]
Checked on staging and guidance as requested by @mmusori above is now there - so this works.
