### ISSUE TITLE
[PROD] PER: Wrong components show under component results on global and country-specific PER pages

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1137]
## Issue
After PER forms have been submitted for a NS, the results of the component and sub-component ratings will show on that country's Go page under the PER tab. 

In the "PER components and subcomponent results" box, when clicking on the different ratings, the names of the components that have been given that rating show up. However some components that show up here have not been rated at all for that NS.

![image](https://user-images.githubusercontent.com/52411237/79955280-ddca7480-847e-11ea-99fe-8456f275138a.png)

I now observed this after having submitted forms for Area 2 (components 6 to 13) and the first form of Area 3 (component 14 with all its subcomponents A to N). The Area 2 components come through correctly but none of the Area 3-1 components show correctly. For sub-components 14A,B,C,D,E and 14N there is no component name showing at all (as seen in the bar chart in the screenshot above) and for components 14F to 14M the component names showing are from the form Area 3-2 (this form has not been submitted for the NS in question).

This makes me wonder if this could be linked to the fix when these Area 3 forms had to be switched around in order? xref #952 #953 

This applies to the global Preparedness page as well. Now under high performing components globally it shows a component which has not been assessed (a component in form Area 3-2) but due to incorrect mapping shows instead of the actual component that was rated as high performing (14D first aid, in Area 3-1).
![image](https://user-images.githubusercontent.com/52411237/79957066-58948f00-8481-11ea-9c0a-1e8efe80ae52.png)

## Severity
Important to fix as currently showing incorrect and misleading information.

**Comment by teklal** [comment]
Looking on the backend it seems that the data saves incorrectly.

I took a look at forms that had previously been added in staging and there the data saved and showed correctly. These were submitted before the changes referenced above in the ticket. 

I submitted a new form for Area 3-2 on the backend now and the data was saved under wrong components just like is in prod for Area 3-1. Hence I really think that with the switching of the languages in the two Area 3 forms some part of the backend switching was forgotten/broken.

**Comment by LukeCaley** [comment]
@batpad to confirm if this is to be included for testing ahead of mini-release 27/04 as per discussion Fri 24/04

**Comment by batpad** [comment]
@teklal this should now be fixed on staging. Please let me know when you have a chance to test.

**Comment by teklal** [comment]
First the good news: now for the form area 3-2 the components seem to be mapped correctly on the backend. 

There are however still frontend mapping issues. 

I think it may be easier to show and run through the outstanding issues on a call (@batpad will ping you on Teams for this). Will elaborate after that more on the ticket if needed.

**Comment by teklal** [comment]
Form area 3-2 seems to now be working as desired both on frontend and backend. 

Area 3-1 still needs work in the way components show on frontend.  The ratings of the components and benchmarks seem to save under the correct titles in the backend but they show in a wrong order in the backend and map incorrectly to the frontend. So some further work still required.

**Comment by teklal** [comment]
@batpad if you need something to help keep you busy, this would be great to have fully fixed :D (sorry)

**Comment by teklal** [comment]
Just noticed that this same problem of the components saving correctly but ordering in a wrong way on the backend applies for form Area 5 as well.

**Comment by batpad** [comment]
@teklal I added a script to regenerate the entire ordering for all the components, so ideally now everything should be in sync. Could you please test this on staging whenever possible? Thanks!

**Comment by batpad** [comment]
@karitotp would be great to have some testing here, to make sure that the data being saved on the forms in the frontend is showing up correctly in the Admin.

There are known issues around the ordering of the questions and components in the Admin, but for now, let's check that there are no mismatches between the questions on the frontend and backend.

**Comment by teklal** [comment]
Steps for testing this:

- Choose a National Society from the dropdown (I would suggest choosing one that doesn't yet have PER forms submitted as it's then quicker and easier to find the right form in the backend and also check the viz on the frontend) https://dsgoproxyapp.azurewebsites.net/account#per-forms

- Click on one of the Area X forms and fill it. Once all fields have a selection made, click "Submit form" at the bottom of the page. (The forms do not always directly appear on the page after submitting and you may have to refresh the page. This is a bug that has to be addressed at some point but not a blocker now)

- Open the form you just submitted by clicking "View"

- Go to the backend and find the form you just submitted https://dsgocdnapi.azureedge.net/per/form/

- Compare what are the selections for each component and benchmark to check if they match and are the same

Would be good to test with both scenarios: assessing and not assessing epi components (i.e. based on the selection made on the first Q):
![image](https://user-images.githubusercontent.com/52411237/82225942-22ceb300-9926-11ea-96d6-1382764cf5c4.png)

I've so far mostly tested without assessing epi components so would be great to have also testing done when that question is "yes".

Thanks @karitotp for testing this! Forms that we know have had problems are highlighted in the screen shot below but would be good to check for the other ones as well:
![image](https://user-images.githubusercontent.com/52411237/82225912-177b8780-9926-11ea-8024-8443eb4ba4b3.png)


Let me know @karitotp if you have question relating to this - we can have a run though of this on a call if needed.

**Comment by karitotp** [comment]
Thanks @teklal, for the above steps for testing!

From what I got, I tested creating PER forms in the different areas, including both areas number 3 and what I could see are;

- Seems that the selections in the components of a per form are matching with the backend.
- The known issue of the wrong order in the backend is still there.
- In case of:
  > Would be good to test with both scenarios: assessing and not assessing epi components (i.e. based on the selection made on the first Q):

I tested mostly selecting this as "YES", where appear "Epidemic Preparedness" for selection on the form.
![Screenshot from 2020-05-18 16-35-55](https://user-images.githubusercontent.com/11504548/82262160-06cb1180-9926-11ea-9629-6d905bf57932.png)

Is in this case, in which this item seems not to be in the correct order in the backend, and this happens in the Forms of the different areas.

Example:

In the form view, the "Component 14B Epidemic Preparedness" is in the 14.8 https://dsgoproxyapp.azurewebsites.net/view-per-forms/a3/82

![Screenshot from 2020-05-18 16-48-49](https://user-images.githubusercontent.com/11504548/82263307-35e28280-9928-11ea-82b6-5a75614ca6ca.png)

But in the backend, it is shown in the 14.6 section https://dsgocdnapi.azureedge.net/per/form/82/change/?app_changelist_filters=q%3Dperu

![Selection_002](https://user-images.githubusercontent.com/11504548/82263321-3d099080-9928-11ea-852f-fca37d216512.png)

In case to test without assessing, all the order seems to be good because the item of Epidemic Preparedness does not appear in the form.

@batpad @kamicut

**Comment by nanometrenat** [comment]
Closing ticket as advised by Stephanie - this old PER is either not relevant any more, or solved because of the new forms/NS preparedness section.  There are other Github tickets related to the new development.
