### ISSUE TITLE
[PROD] Country pages not loading correctly when reached via Elastic Search

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1142]
## Issue
When I am in GO Production and I type a country name in the search box then click on that country, when I land on the country page it often doesn't load properly.  I noticed this behaviour for the first time tonight however can't see any errors being returned in the console etc.

When I click on the Elasticsearch link it sends me to the country page WITHOUT #operations at the end of the URL.  e.g. https://go.ifrc.org/countries/51

Then when the page loads it loads correctly from the top all the way down to the Operations / Preparedness / Additional Information tabs.  But it then goes straight to the links at the bottom (ifrc.org, reliefweb, NS homepage) so does not show any actual body page content.

If I click on any of the tabs the content of those tabs loads fine.

No errors in console etc. at any point.

If I click "refresh" without changing the URL then the full country page loads fine without any issues (probably because it then defaults to adding #details to the URL via the automatic redirect thingie)

## Steps to reproduce
Per above
![image](https://user-images.githubusercontent.com/33625192/80139493-d56d5900-85a6-11ea-9319-8649f653eb67.png)

## Expected behaviour
Country page should load fine as soon as I search for it.

## Impact
This far me, Tekla and Sanjay have experienced it this evening - I have not seen this issue happening previously though.

## Severity
Really a perception thing - means people think there is no content on the page.

## Is there a workaround?
Hit refresh, or click a tab

**Comment by batpad** [comment]
Thank you for the catch @nanometrenat . Fix can be tested at https://ifrc-go-fix-1142-country-tab.surge.sh/

PR is here: https://github.com/IFRCGo/go-frontend/pull/1143

**Comment by batpad** [comment]
To reproduce this issue on staging: 
 - Go to any country page, for eg. https://dsgoproxyapp.azurewebsites.net/countries/14#operations
 - While on the country page, search for another country in the search box and click on it.
 - The default tab does not get highlighted

To test fix, check behaviour on https://ifrc-go-fix-1142-country-tab.surge.sh/ and the default tab should now always load on the country page.

cc @karitotp

**Comment by karitotp** [comment]
Now it is loading Operations as default tab!

**Comment by LukeCaley** [comment]
@teklal please confirm UAT pass or not.

**Comment by teklal** [comment]
Tested and I confirm this now works.
