### ISSUE TITLE
3W: Finetuning - hide empty fields from Show Activity -form

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1146]
Hide empty fields from view details (see pic)
![image](https://user-images.githubusercontent.com/8285694/80197369-d346e100-861e-11ea-9f8a-931643cc1aeb.png)

**Comment by karitotp** [comment]
Empty fields are not shown now :+1:

When Edit an activity and Change the program type from Domestic or Multilateral to Bilateral, the Current Operation and Disaster Type are still displayed in the details of the view. Is it correct or should they be empty fields and not showing in details view when the program is Bilateral?

![Selection_017](https://user-images.githubusercontent.com/11504548/80617048-38c41480-8a07-11ea-902c-3ac72655c8c3.png)
