### ISSUE TITLE
3W - Bilateral Emergency Operation is missing the disaster type

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1148]
For some reason, Bilateral Emergency Operation does not have a disaster type field
![image](https://user-images.githubusercontent.com/8285694/80199581-cecff780-8621-11ea-8d80-ff5e5e154283.png)

**Comment by frozenhelium** [comment]
That's the desired behaviour according to the specs

**Comment by teklal** [comment]
Can you @guipizzini confirm/clarify whether this is the desired behaviour, i.e. that when "Emergency Operation" and "Bilateral" is chosen, there is no field to specify the Disaster type? (sorry, I feel like I'm having trouble keeping up with the logic behind all these different combinations)

**Comment by guipizzini** [comment]
Correct, as the disaster type is already defined in the "emergency" when creating the field report so we could/should do the link to the disaster type that way. Makes sense?

**Comment by teklal** [comment]
Yes, thanks for the input @guipizzini, I get the logic and makes perfect sense - hence the questions. As with the current implementation for the bilateral ones there is no option to link to a GO emergency page - meaning there is no possibility to pull that disaster type info from there and have it predefined. 
![image](https://user-images.githubusercontent.com/52411237/80703835-ce34d680-8ae3-11ea-98e4-394f68a2eb87.png)

So I guess the question now is - should there be a box for linking to an emergency for "Emergency Operation - Bilateral" (as there is for Domestic and Multilateral) or should we just add the box "Disaster type" (if that, should it be a required field or not)? Do we expect that for bilateral emergencies a NS will have submitted or will submit a field report? Based on a quick chat with @mmusori yesterday, it seems that not necessarily - so maybe for these bilateral operations then just have the "Disaster type" box as a (required?) field?

Input/thoughts/corrections to my thinking above - @guipizzini @mmusori ?

**Comment by lauripynnonen** [comment]
I'm in for having the "Disaster type" box as a (required?) field. @LukeCaley can you give the last say?

**Comment by frozenhelium** [comment]
@luisfanovich What's the conclusion for this issue? Let's finalize this issue.
CC: @LukeCaley @danielfdsilva

**Comment by LukeCaley** [comment]
As agreed on GO call (16/04) I confirm that disaster type _should_ be a required field.
cc @frozenhelium @luisfanovich

**Comment by frozenhelium** [comment]
Disaster type is now a required field, available for test in the [staging server](https://ifrc-go-feature-three-w-dtype.surge.sh/countries/123#3w)
