### ISSUE TITLE
3W: COVID-19 tagging

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1155]
Due to everything being about COVID-19 it's safe to assume that many of the Go 3W users are there to either submit COVID related activities or to view COVID related activities. 

Hence we should make sure we start early on tagging activities that are related to the COVID-19. 

This could be 
- a separate checkbox for COVID related activity, 
- a COVID tag in the project tags, 
- something completely different? 

Needs discussion

**Comment by frozenhelium** [comment]
@lauripynnonen The easiest way would be a "COVID" tagging option in the project form

**Comment by lauripynnonen** [comment]
@frozenhelium you mean adding COVID on the top of the Tag list here?
![image](https://user-images.githubusercontent.com/8285694/80378762-70af4880-889d-11ea-92e1-4fe839cb72da.png)

**Comment by lauripynnonen** [comment]
@frozenhelium let's add it as COVID-19 tag on the top of the Tagging list.

**Comment by frozenhelium** [comment]
@lauripynnonen Yes, exactly! Let us know if that sounds good.

**Comment by lauripynnonen** [comment]
@frozenhelium could you
- Move COVID on the top of the tag list
- change COVID to COVID-19

**Comment by frozenhelium** [comment]
It's sorted alphabetically. And since we do not have any mechanism to change the order dynamically (eg: from admin panel) it won't be feasible to put it on top
