### ISSUE TITLE
COVID-specific Field Report

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1160]
## Issue
Under https://github.com/IFRCGo/go-frontend/issues/1004 an Epidemic Field Report was developed, with a different list of Actions Taken vs the actions from "normal" Field Reports, and with a different list of figures and also some different labels.

Epi Field Reports were deliberately written to be generic across epidemic types.

The new requirement is to explicitly separate out a COVID-type Field Report vs an Epidemic FR or another type of FR.

### Separating out COVID-19 Field Reports from normal Epidemic Field Reports

- They will need their own list of actions to be configured (separately), _and "Planned International Response" is not to be displayed_ - otherwise COVID-19 Field Reports will be the same in every other way as Epi Field Reports (in terms of types of figures shown, other prompts onscreen, how the figures etc. feed through to Emergencies and notifications etc)
- Possible ways we have thought of include the below, we will need to balance up complexity/risk/usability:
i.	At top level where there is Early Warning or Event field report, there is alternatively a COVID-19 radio button [know this option was ruled out for Epi FRs though…]
ii.	User selects disaster type = Epidemic but then has a tickbox to choose COVID-19 (or not)
iii.	In the disaster type dropbox, there is a COVID-19 option (i.e. different to Epidemic), this would need to be at the top of the list
iv.	Any other ideas?
- The ability to filter to COVID-19 would need to come through in the API (whether as a different disaster type, or another field coming through somehow)
- Noting that this will be in place for ~1 year (estimate) then would be removed once no longer relevant – although the historic FRs would of course need to remain visible even after no new COVID-19 field reports are created.

Re "Planned International Response" section (on 4th screen of New Field Report, the Response page), the whole section (DREF Requested, Emergency Appeal, Rapid Response Personnel, Emergency Response Units) should not display when creating/editing/viewing a Field Report of type COVID.

## Related feature
https://github.com/IFRCGo/go-frontend/issues/1004

## Next steps
Yellow Umbrella to please urgently advise which of the options above would be best from a user point of view (bearing in mind that the vast majority of Field Reports being submitted at the moment are for COVID; but not all are/will be!)  @batpad advises that his preference is for ii but any are possible from a dev point of view.

**Comment by yellowumbrella-design** [comment]
@nanometrenat why was option one ruled out? I think the best would be to make it visible and clear, i.e. one of the top options, even if conceptually it's a bit different from early warning/event. All the others, may be overlooked. @batpad Would it be possible, once Covid is selected, to have the disaster type locked to epidemic? Happy to help with the fields if they are anyway different from epi field report.

**Comment by batpad** [comment]
> @nanometrenat why was option one ruled out? I think the best would be to make it visible and clear, i.e. one of the top options, even if conceptually it's a bit different from early warning/event.

I don't think it was ruled out, per se. From a data structure point of view, it makes me slightly uncomfortable to have the COVID-19 category in the same level as `Event` / `Early Warning`. So then something could be either an `Event`, an `Early Warning` or a `COVID-19`.

In terms of implementation, having a third option to Event and Early Warning is definitely the simplest implementation. But it just seems to me a bit strange to have things in the backend categorized as either Event, Early Warning or COVID-19 - having it as a separate Boolean value for like `Is This a COVID-19 related field report?" in addition to Event / Early Warning seems cleaner in terms of the data organization. If we want to have it up front and center, it can be the first option on the form, and if the user selects that it is a COVID-19 report, we could auto-select Event and Epidemic as options, but this would still keep it as a separate classification in the database.

Let me know if that makes sense / in the end, any of the implementations here seem reasonable, so happy to go with whatever seems best.

**Comment by nanometrenat** [comment]
Thanks both
 
> In terms of implementation, having a third option to Event and Early Warning is definitely the simplest implementation. But it just seems to me a bit strange to have things in the backend categorized as either Event, Early Warning or COVID-19 - having it as a separate Boolean value for like `Is This a COVID-19 related field report?" in addition to Event / Early Warning seems cleaner in terms of the data organization. If we want to have it up front and center, it can be the first option on the form, and if the user selects that it is a COVID-19 report, we could auto-select Event and Epidemic as options, but this would still keep it as a separate classification in the database.

This sounds like a good option to me - keep a logical data structure "under the hood" but then also make the button front and centre for the user.  @mmusori can you confirm you are happy and if so we can move on getting this built :)  Thanks

**Comment by mmusori** [comment]
I believe one of the option we discussed was to have it as part of the Status bar with Event , and EW. We were meant to discuss this with @sanjay to see if it was a feasible option. It would be great it have it clearly and easily visible to users from the onset. So yes I would second the suggestion from @yellowumbrella-design .

**Comment by yellowumbrella-design** [comment]
I agree. It is a bit strange to have it next to event/early warning, but as it's a (hopefully) temporary event, it may be ok to bring it up. Let us to a very quick UI option to see how we can make it right up front but also not super confusing. Send you back something shortly.

**Comment by mmusori** [comment]
@yellowumbrella-design : 
Below is a suggestion from Health colleagues who do not like the idea of having the Covid-19 in the status bar since Covid-19 is not a timeframe. 😊
The Disaster Type taxonomy is listed alphabetically, can we override and push COVID-19 to the top?  For example:
COVID-19
Biological Emergency
Chemical Emergency

**Comment by yellowumbrella-design** [comment]
Hi everyone, please let me know what you think about this solution?
COVID toggle once event is selected (which is the default). In this case the Epidemic is pre-selected and uneditable.
![8 1 1_GO_FieldReports_1 1-8 - COVID_Toggle_Selected](https://user-images.githubusercontent.com/60006476/80493986-6c029700-8966-11ea-9bcd-d0eaa9fff42b.png)

The unselected view:
![8 1 1_GO_FieldReports_1 1-8 - COVID_Toggle_Unselected](https://user-images.githubusercontent.com/60006476/80494018-758bff00-8966-11ea-9c8a-f6dac87186a7.png)

**Comment by mmusori** [comment]
@yellowumbrella-design this works for me. My health colleague would prefer having that Covid-19 button above Disaster type. What do think?
![image](https://user-images.githubusercontent.com/7780809/80502196-9d806000-8970-11ea-8312-989096fdcff2.png)

**Comment by yellowumbrella-design** [comment]
I find it a bit strange to have it above the dropdown directly. Also, the Covid toggle in theory changes the entire field report flow, right (i.e. some fields will be different), so not only the disaster type. Thoughts?

**Comment by mmusori** [comment]
I would go with your design. @nanometrenat any red flags on this?

**Comment by nanometrenat** [comment]
Works for me - thanks all

**Comment by batpad** [comment]
@yellowumbrella-design @nanometrenat @mmusori - if a user selects the COVID-19 toggle, we force the field report type to be `Event`, right? I.e. we disallow users from submitting COVID-19 reports that are also Early Warning?

**Comment by batpad** [comment]
Also I'm seeing the additional `Report Version` field. Is this something that's expected for the COVID field report feature? I would need some more clarity on this, if yes.

**Comment by nanometrenat** [comment]
> @yellowumbrella-design @nanometrenat @mmusori - if a user selects the COVID-19 toggle, we force the field report type to be `Event`, right? I.e. we disallow users from submitting COVID-19 reports that are also Early Warning?
Exactly the same logic as if the user selects "Epidemic" - i.e. if this logic is in place for Epidemics (which I believe it is) then it should be for COVID, as all COVID FRs are by their nature disaster type = Epidemic.

> Also I'm seeing the additional `Report Version` field. Is this something that's expected for the COVID field report feature? I would need some more clarity on this, if yes.
This was specified in https://github.com/IFRCGo/go-frontend/issues/1004#issuecomment-605881493 I believe (in order to help reduce number of times that multiple emergencies are created when they should instead be linked).  However I know that several aspects of that ticket were split out for subsequent work in order to not delay the release (e.g. https://github.com/IFRCGo/go-frontend/issues/1095).  @mmusori would need to confirm where those items are at - HOWEVER it is not in scope to change that logic/new field under THIS ticket.  This ticket is solely for the COVID-ification.  I would expect that when the changes mentioned in the other ticket are made they would apply to COVID FRs as well.

**Comment by nanometrenat** [comment]
> * They will need their own list of actions to be configured (separately), _and "Planned International Response" is not to be displayed_ 

@batpad please note that I edited the original ticket description to add the above additional req re hiding a section - trust all's clear and apols this wasn't requested up front.  Thanks

**Comment by mmusori** [comment]
HLo WAt au Dooyn

**Comment by mmusori** [comment]
@nanometrenat the report version will be a feature on all Field Reports so that new title s are not generated and NS link to existing FRs.  Hope that makes sense.

**Comment by batpad** [comment]
The COVID field report can be tested at https://ifrc-go-feature-1160-covid-fr.surge.sh/reports/new

This implements:

 - Setting Status to Event when COVID field report is selected
 - Setting disaster type to Epidemic when COVID report is selected
 - Fetching actions as per the COVID type of action
 - Hiding Planned International Response from field report form (and field report page in case of COVID report)
 - Displays "Is COVID-19 Related Report" on field report page if field report is COVID-19 related
 - Adds additional Actions categories in the backend

All of the above should be good to test. The known issues are mostly to do with styling:

 - Styling of toggle widget does not match spec
 - Spacing of form components in Step 1 (Status and `Is Covid Report` need to be part of the same "section")
 - Spacing in Step 4 - weird spacing where Planned International Response used to be.

@imohkay - let's go through the styling fixes, hopefully they are pretty quick.

@nanometrenat @teklal - will be great if you are able to test the functionality. @nanometrenat - if you are also able to add some test actions to staging for the COVID report, that would be fantastic.

@karitotp - will be great if you can give this a test, let me know what all might need to be clarified.

**Comment by karitotp** [comment]
@batpad, this is what I found by testing the above implements:

> Setting Status to Event when COVID field report is selected

This works well, but when the COVID field report is changed to OFF, the status is in Event but the option Early Warning / Early Action is still deactivated for selection.
![Screenshot from 2020-05-03 17-58-27](https://user-images.githubusercontent.com/11504548/80928084-cdac7200-8d67-11ea-87db-f49adbd77213.png)

> Fetching actions as per the COVID type of action

Can not select actions taken in the field report form. Or, how this are being completed? none action appear as selected and could not selecting any action neither.
![Screenshot from 2020-05-03 18-36-49](https://user-images.githubusercontent.com/11504548/80929118-2b908800-8d6f-11ea-963a-63eca349d634.png)

> Displays "Is COVID-19 Related Report" on field report page if field report is COVID-19 related

It is displaying as "This is a COVID-19 Related Report."

**Field validators:**

- Maybe could be good to add validators in the date entries, I completed the "start date" and "date of data" with upcoming dates, and the report was created normally. 
https://ifrc-go-feature-1160-covid-fr.surge.sh/reports/9555

- Also, numeric fields have to be validated to allow entering only positive integer values.

**Comment by nanometrenat** [comment]
Thanks @karitotp - @batpad I originally thought that perhaps the reason why we couldn't tick these boxes might be because of some weirdness around the new is_disabled flag - but that doesn't seem to be the case, as when I tick that box for an action it disappears from the form rather than being disabled - so I don't _think_ it's misconfiguration of the actions by me.  Sanjay please let me know if I need to set them up differently though.  Thanks

**Comment by batpad** [comment]
>  Sanjay please let me know if I need to set them up differently though. 

Nope, this was a code issue. Thank you for the catch @karitotp @nanometrenat - you should now be able to select COVID actions correctly.

> It is displaying as "This is a COVID-19 Related Report."

We didn't really have a design spec for how the field report page should be indicated as being a COVID field report. This text was a bit of a place-holder. @nanometrenat do you have suggestions for how best to indicate on the field report page that this is a COVID-19 related field report?

> Field validators:

@karitotp since this is a pre-existing issue and not specific to the COVID field report, could you create a separate issue like `Fix validation for Field Report form` and we can add these in there as a consolidated ticket to fix validations on the form?

> This works well, but when the COVID field report is changed to OFF, the status is in Event but the option Early Warning / Early Action is still deactivated for selection.

This is actually a super interesting issue. So what happens is that when you select the COVID toggle, it sets the Disaster Type to Epidemic. When you unset the COVID toggle, the disaster type stays at Epidemic, and since for Epidemic disasters, only `Event` type field reports are allowed, the Event / Early Warning radio remains disabled.

This seems a bit tricky to figure out what the "correct" thing to do here is. If the user unselects the COVID toggle, changing the disaster type back from Epidemic also seems a bit strange, but perhaps that's the preferrrable solution? cc @nanometrenat 

> Styling of toggle widget does not match spec

^ This should now be fixed.

Thank you so much for the testing and discovering of issues @nanometrenat @karitotp .

**Comment by nanometrenat** [comment]
> This seems a bit tricky to figure out what the "correct" thing to do here is. If the user unselects the COVID toggle, changing the disaster type back from Epidemic also seems a bit strange, but perhaps that's the preferrrable solution? cc @nanometrenat

I'm comfortable with leaving it as-is.  If the user selects then unselects the COVID toggle and wants to do a different disaster type then they can always start the Field Report again - it's at the very start so they won't have lost anything.  Better that than complicated logic for an unlikely scenario!

**Comment by nanometrenat** [comment]
> > It is displaying as "This is a COVID-19 Related Report."
> 
> We didn't really have a design spec for how the field report page should be indicated as being a COVID field report. This text was a bit of a place-holder. @nanometrenat do you have suggestions for how best to indicate on the field report page that this is a COVID-19 related field report?

This is probably one for @mmusori but my thoughts are that perhaps it could show in the same way as the other yes/no fields e.g. put it underneath data of data and before start date, and simply say
"COVID-19 Field Report:  Yes"
In any case the font shouldn't be bigger and bolder than the other things on the page - I'd be fine with it just being normal text.  And only showing this text section if it's True (because of course we have a lot of historic FRs that relate to COVID-19 but were submitted before the select box was implemented - so don't want them to show as "false"!!)

Does that sound OK?

Current:
![image](https://user-images.githubusercontent.com/33625192/80947499-8f0eca00-8df0-11ea-801c-e424b54ab760.png)

![image](https://user-images.githubusercontent.com/33625192/80947512-946c1480-8df0-11ea-9257-836824633464.png)

**Comment by teklal** [comment]
This is a minor thing, but would it be better to have the COVID toggle say "COVID-19 Related Report" instead of "COVID-19 Related Event"? @mmusori @nanometrenat 
I'm thinking if this is used for the purpose of NSs reporting on Activities - a new FR does not necessarily signify a new event having happened but it's more like an update (or am I completely off - totes possible as I may not be in the loop of the most recent decisions).

**Comment by batpad** [comment]
> Does that sound OK?

Sounds good to me. Will update shortly with this change.

**Comment by nanometrenat** [comment]
@batpad thanks for this, looks great to me in surge testing URL - the two remaining things under this ticket please:

- [ ] adjusting how it looks when viewing Completed Field Reports (as per comments above)
- [ ] bringing through the narrative info from the "Actions taken by the IFRC" and "Actions taken by other RCRC Movements" narrative fields even when no actions are available to be ticked here.

**Comment by teklal** [comment]
Adding here re the Actions IFRC/Movement not saving/coming through:

The fields do not show at all on the page generated from the field report
![image](https://user-images.githubusercontent.com/52411237/80959672-91305300-8e07-11ea-9b75-e64ada941ab8.png)

They do however show as empty in the notification emails
![image](https://user-images.githubusercontent.com/52411237/80959759-bf159780-8e07-11ea-86d9-2e2faf09506a.png)

**Comment by teklal** [comment]
The Actions taken by IFRC/Movement narratives now save and show on the generated page (as well as the notification emails)

**Comment by karitotp** [comment]
It works good to me too!

**Comment by nanometrenat** [comment]
Confirmed that COVID Field Report looks good in staging now - thanks a lot.  I didn't check notifications but Tekla did so that's great.

A couple of issues that are unrelated to the above build that will need to be addressed separately (e.g. when viewing a submitted Field Report the figs around assisted by govt vs assisted by RCRC vs number of NS staff/volys and RCRC pax do not show - but all are saved correctly so just a display issue related to the figures display conversations that @mmusori has been having, e.g. under #1096 and others )
