### ISSUE TITLE
Map auto-centering not working properly for some countries

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1162]
## Issue
When navigating to the 3W tab for a country the map should change the view to zoom into the country in question.

There are some problems with this zoom/focus/centering being way or mildly off for some countries.

Countries that I've noticed this happening for (there may be more):
- Maldives https://dsgoproxyapp.azurewebsites.net/countries/227#3w
- Tuvalu https://dsgoproxyapp.azurewebsites.net/countries/213#3w
- Tonga https://dsgoproxyapp.azurewebsites.net/countries/171#3w
- New Zealand https://dsgoproxyapp.azurewebsites.net/countries/125#3w
- Fiji https://dsgoproxyapp.azurewebsites.net/countries/66#3w
- Micronesia https://dsgoproxyapp.azurewebsites.net/countries/195#3w

So far all the above are from Asia Pacific - will update ticket if/when I find more countries with the same problem.

I have identified a similar problem for field report maps in the live environment xref #1126 but with a quick check the countries for which the problem exists are not exactly the same so maybe a different problem.

**Comment by teklal** [comment]
This is probably something that the team here has to make a decision on how to show countries that have overseas territories but flagging nonetheless as the current way the country is shown on the map is not ideal:

- Netherlands https://dsgoproxyapp.azurewebsites.net/countries/124#3w
- France https://dsgoproxyapp.azurewebsites.net/countries/68#3w

**Comment by frozenhelium** [comment]
This is because those countries are missing the bbox values in `country-bounding-box.js`(probably because the boundaries are complicated).

**Comment by teklal** [comment]
@frozenhelium thanks for identifying and pinpointing the underlying issue. Is there a way to solve this or a workaround?

**Comment by frozenhelium** [comment]
Hi @teklal, I did a brief research while debugging this issue and couldn't find any easy fix or workaround. So, for now, we'll have to set it as an open issue and should prioritize solving this according to the urgency..

**Note:** Solving this'll require some research on how to represent those complex boundaries to the existing infrastructure of the GO platform and also weather or not the mapbox supports that kind of boundaries. For this reason, the boundary for those countries might have been skipped intentionally during the initial development. They cannot be stored in the current format for the boundaries.

**Comment by batpad** [comment]
tagging @geohacker here. Would be great to have a chat as this affects several parts of the website, and it seems like developing a consolidated plan to update spatial data, as well as resolving these kinds of issues of dealing with edge cases (where a country cannot fit neatly into a single "bounding box"). @frozenhelium would definitely be good to talk before, if you are planning on working on this.

**Comment by batpad** [comment]
@jhenshall @geohacker now that the bounding box and centroid are customizable in the Admin, could this be marked as Done? Perhaps we should verify that all default views for countries update correctly when editing in the Admin?

**Comment by jhenshall** [comment]
Hey @batpad - can confirm that countries do update properly after changing in the backend, so this could maybe be closed but want to flag a couple of issues first:

- Netherlands BB still includes Overseas Territories: this is a business decision to decide what's best so leave with me.
- New Zealand and Fiji have weird BB because they span the 180degrees date-line. I can change this to just be on one side but wanted to note for @geohacker and in reference to #897.

**Comment by jhenshall** [comment]
I've split the NZ and Fiji examples into a new issue about 'map flatness' so think this one is good to close now @batpad
