### ISSUE TITLE
3W: Regional View: Sankey topics to who what where

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1164]
Change Sankey Topics to 
**Who**
(subtopic) _Reporting National Society_ 
**What** 
(subtopic) _Activity_
**Where** 
(subtopic) _Receiving National Society_

**Comment by frozenhelium** [comment]
![2020-04-29-131650](https://user-images.githubusercontent.com/4931541/80571122-c3167380-8a1b-11ea-9af1-bcdaaefbd9fd.png)
@lauripynnonen  The view has been slightly modified to match other pages in the IFRC, let me know how to incorporate this in this new view

**Comment by frozenhelium** [comment]
finalized to `Select Who (Reporting NS)` `Select What (Sectors)` `Select Where (Country)`

**Comment by teklal** [comment]
@frozenhelium Minor thing: could you change sector to be in singular i.e. `Select What (Sector)` just so it's in line with the other two that are also in singular.

**Comment by frozenhelium** [comment]
Sure!

**Comment by lauripynnonen** [comment]
Perfect!
