### ISSUE TITLE
3W: Form Tooltips

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1165]
Tooltips for 3W form:
 
Reporting National Society 
_Descriptive Gray Text:_ Select National Society that is carrying out the activity. 
**Hover tooltip:** It can be either the National Society where the disaster has taken place or a different National Society that is carrying out an activity in support of the response. 
 
Country & Region 
_Descriptive Gray Text:_ Select the country and region where the disaster is taking place. 
**Hover tooltip:** The region can be referred to as states, provinces, or Admin Level 1. Choose countrywide for activities that are not limited to specific places. If the project takes place on multiple regions please submit each region separately using the clone-function on the country view table 
 
Operation Type 
_Descriptive Gray Text:_ Select the operation type. 
**Hover tooltip:** The operation type can be either an Emergency Operation or a Programme. Emergency Operations are new efforts linked to a specific emergency. Programs are ongoing work linked to a disaster. 
 
Programme Type 
_Descriptive Gray Text:_ Select the Programme Type. Choose from the options of Domestic, Bilateral, Multilateral. If you choose Domestic Emergency Operation, then identify linked Ongoing Emergency. 
**Hover tooltip:** If you choose Domestic, Bilateral, or Multilateral Programme, select Disaster Type that best fits the situation. Disasters are often multifactorial. Please choose the type that makes the most sense, recognizing that disasters are often the result of many complex factors. 
If you choose Bilateral Emergency Operation,  then no additional info is required. 
If you choose Multilateral Emergency Operation, then please identify linked IFRC Emergency Operation.
 
Activity Name 
_Descriptive Gray Text:_ Enter a name that differentiates your activity or project from other initiatives taking place in the response. 
**Hover tooltip:** The 3w system does allow for duplicate activities projects with the same name, but please choose a descriptive and original title. 
 
Sector 
_Descriptive Gray Text:_ Choose the sector that best represents the activity or project. 
**Hover tooltip:** CEA - Community engagement and accountability is a set of communication and participation activities that help put communities at the centre of the response. 
DRR - Disaster risk reduction is the concept and practice of reducing disaster risks through systemic efforts. It encompasses a broad range of activities – from ensuring that legislative and policy approaches reflect known hazards, to community-based initiatives and technical solutions such as early warning systems.
Education - Educational programming for people affected by disasters. 
Health - Immediate assistance for disaster-affected people and longer-term activities that save lives and improve health outcomes. Separated into clinical and public health.
Livelihood and basic needs - Livelihoods are the capabilities, assets and activities required for generating income and securing a basic means of living.
Migration - Aid and protection for migrants and displaced people, in countries of origin, transit and destination, whatever their legal status.
NS Strengthening - Support to the auxiliary role, strategy, governance and accountability; strengthening areas such as financial management, communications, fundraising; increase volunteer engagement; improve external relations; or ramp up their preparedness for responding to emergencies or improve the planning and execution of programmes and services they provide.
PGI - Protection, gender and inclusion (PGI) in emergencies including sexual and gender-based violence and disability inclusion. 
Shelter - Immediate and long term shelter assistance
Wash - Water, sanitation and hygiene support. 
 
Additional Tags 
_Descriptive Gray Text:_ Projects are often multi-sector. After choosing the primary sector, feel free to add additional sector ‘tags’. 
**Hover tooltip:** It is possible to add none, one or many tags using the definitions listed above. For COVID-19 related projects please add the COVID-19 tag
 
Start and End date - 
_Descriptive Gray Text:_ Choose the date when the work on the activity or project begins. 
**Hover tooltip:** Choose the date when the project is likely to end. Remember, you can easily return and edit this data if plans evolve. 
 
Budget 
_Descriptive Gray Text:_ Enter the budget for the activity or project. 
**Hover tooltip:** The budget includes the total costs for the listed activity or project. 
 
Project status
_Descriptive Gray Text:_  The project status (planned and ongoing) is automatically defined by the current date and the submitted project timeline. 
**Hover tooltip:** The project can be marked completed, which makes the people reached a required value.
 
People targeted 
_Descriptive Gray Text:_  Enter the number of people that the project plans to reach through the work. 
**Hover tooltip:** The options are: Male, Female, other, and Total
Male - People who identify as having the male gender
Female - People who identify as having the female gender
Other - Other can include data such as “other sex/gender”, “undisclosed”, “unknown”, etc.
Total - The total number of people included in the subcategories above
 
People reached -
_Descriptive Gray Text:_ Enter the total number of people reached already with (TOTAL, male, female, other) according to the definitions above. 
**Hover tooltip:** Please follow the Counting People Reached guidelines as establishing the Federation-wide Databank and Reporting System.   
 
Visibility -
_Descriptive Gray Text:_ Enter the desired visibility of the project
**Hover tooltip:** The IFRC Only option limits viewing to only those vetted IFRC members who are logged into the GO platform and have the required permissions to view the data. Most programs should be in public mode, and we should only use the IFRC Only option in limited sensitive contexts where issues such as protection concerns are present. As with the wider GO Platform, there is no place for Personal or Community Identifiable data on this type of coordination platform. Sensitive data or information that could jeopardize the safety of staff or project participants should not be shared.

**Comment by frozenhelium** [comment]
Tooltips for some fields have to be merged because the belonged to the same input group
