### ISSUE TITLE
[PROD] Merge emergencies not working

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1167]
## Issue
It seems the merging emergencies functionality is not working in prod. I get the same view (as below) for my user account (superuser) and a test account (not a superuser). The functionality should be enabled for superusers and I think the whole "Parent Emergency" section should not appear for non-superusers.

![image](https://user-images.githubusercontent.com/52411237/80473808-efac8b80-8946-11ea-9618-9f71959fe61a.png)

## Related feature
#1010 
#1128

**Comment by teklal** [comment]
If making this a superuser functionality is causing problems, alternative solution would be to make the ability to merge emergencies a user permission that can be assigned to user accounts.

**Comment by GregoryHorvath** [comment]
> If making this a superuser functionality is causing problems, alternative solution would be to make the ability to merge emergencies a user permission that can be assigned to user accounts.

@teklal Good idea! I still couldn't reproduce this locally at all sorry. We'll try that and see how it goes.

**Comment by teklal** [comment]
Closing as this particular thing is fixed and working on prod, thanks! Remaining "gremlin" related to this ticketed here: #1299
