### ISSUE TITLE
[Staging] Add, Edit and Duplicate forms does not load correctly for some countries

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1169]
## Issue
When I click in Edit or Duplicate in existing activities of the countries or when I click in Add button to add a new activity, the form loads correctly but after few seconds it disappear, and the site doesn't display anything, all the page turns to light grey.
This does not happen in all the countries and it is independent of the region which they are because some countries load correctly ant other not, I could not find the pattern to know in which countries happen this.

## URL
- Country where the forms do not load correctly: https://dsgoproxyapp.azurewebsites.net/countries/15#3w
- Country where the form load correctly: https://dsgoproxyapp.azurewebsites.net/countries/53#3w

## Steps to reproduce
Go to a country, click in 3W tab and click in Add button, or Edit or Duplicate button in the table of existing activities.
https://dsgoproxyapp.azurewebsites.net/countries/20#3w

## Expected behaviour
All the forms should load correctly in all the countries.

## Criticality/Urgency
These are basic functionalities and should be fixed soon.

**Comment by frozenhelium** [comment]
@karitotp This should be fixed now

**Comment by karitotp** [comment]
It is fixed!
