### ISSUE TITLE
3W: Sector labels get hidden when many sectors in "Activities by sector"

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1171]
## Issue
On a 3W country view, if there activities of several different sectors in that country, not all sector labels will show in the bar chart.

![image](https://user-images.githubusercontent.com/52411237/80580749-5b0c6100-8a0c-11ea-98bb-85525cc00371.png)

The label will still show when hovering over the bar but not in the static visualisation or the map/png export.

**Comment by frozenhelium** [comment]
@teklal This is the desired behaviour as there won't be enough space to display all the labels. Hovering over will show more details

**Comment by teklal** [comment]
Ok, I see. This is not a blocking issue now for push to prod but I think it would be good to find a way to display all labels at some point. If not on the page itself then at least just for the map export as there is no hover possibility.

Would it be possible to have the long labels in two lines?

**Comment by frozenhelium** [comment]
Cool, will have to check on the possible options to show all the labels!

**Comment by teklal** [comment]
Checked and this now works in staging, great! 

The only comment I have is that the font appears quite blurry in the png export - is there anything that can be done about it now (not a blocker if not)?
![image](https://user-images.githubusercontent.com/52411237/81167025-ca49fe00-8f94-11ea-8df9-24d05f3f51f0.png)

**Comment by frozenhelium** [comment]
@teklal On mine it looks like this.
![map-1588851154741](https://user-images.githubusercontent.com/4931541/81289873-d3b39300-9086-11ea-9dae-fb5b2f1bc007.png)
Which browser did you use for the download above? Also, can you make sure you have the zoom set to 100%. Technically the download should match the resolution that user sees in the website.

**Comment by teklal** [comment]
Oh the zoom thing probably caused the blurriness on my end, didn't think of that - thanks! All good now. Will move to done and close once this is in prod.
