### ISSUE TITLE
3W: Cosmetic things to be addressed

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1173]
- [x] On the form: capitalize the N and S in National Society (to be in line with rest of GO)
![image](https://user-images.githubusercontent.com/52411237/80582012-4e890800-8a0e-11ea-9065-6788d03b24ba.png)

- [x] On the form: National Societies in dropdown list should follow the alphabetical order of the country name of that NS 

- [x] On map export: the font of the labels in the charts is different from how they appear on the website
![image](https://user-images.githubusercontent.com/52411237/80582296-bc353400-8a0e-11ea-861b-b897cbf1cf55.png)

- [ ] The resolution of the map export is quite bad, could that be improved?

- [x] When hovering over a sector bar, the box tells the number of activities in that sector under the label "value". Would be good to change to e.g. "activities: 1"
![image](https://user-images.githubusercontent.com/52411237/80583151-24384a00-8a10-11ea-925d-b05842890098.png)

- [x] Activity status changes to planned as soon as any choice is made on the form

- [x]  Change the wording of the filter box on regional 3W
![image](https://user-images.githubusercontent.com/52411237/80590470-33bd9000-8a1c-11ea-8f8f-10a191f03a05.png)
wireframes: 
![image](https://user-images.githubusercontent.com/52411237/80590962-1b01aa00-8a1d-11ea-9796-5093d6311134.png)

- [x] Capitalize all letters in CEA, DRR and PGI both in graph and dropdown on on regional view
![image](https://user-images.githubusercontent.com/52411237/80591437-fd811000-8a1d-11ea-8781-3fa54275b54a.png)

- [x] Remove asterisk from Disaster type, when "Programme" is chosen as "Operation type" as it is possible to submit form without determining the disaster type and it does not need to be a required field in those cases
![image](https://user-images.githubusercontent.com/52411237/80600626-f9102380-8a2c-11ea-8053-ffcb2e272519.png)

- [x] pie chart on regional page to start from "12 o'clock" (as in wireframes). If possible, start at 12 o'clock and go clockwise, starting with the largest segment
now: 
![image](https://user-images.githubusercontent.com/52411237/80615111-9411f900-8a3f-11ea-994f-42b3f343bec4.png)
wireframes:
![image](https://user-images.githubusercontent.com/52411237/80615164-9f652480-8a3f-11ea-85f1-0989228e094b.png)

- [x] Another place to capitalize the N and S: a country page 3W under the map
![image](https://user-images.githubusercontent.com/52411237/80695069-a9d1fd80-8ad5-11ea-9893-526af43ef326.png)

- [x] Add space after All:
![image](https://user-images.githubusercontent.com/52411237/80695216-df76e680-8ad5-11ea-95e8-9a4a31287766.png)

- [x] Sectors in bar chart to follow alphabetical order (unless there is some logic behind the current way they show up and I missed it - let me know if that is the case):
![image](https://user-images.githubusercontent.com/52411237/80695602-6f1c9500-8ad6-11ea-8607-26fe8f2b9c6d.png)

Sorry, I know some of these seem very petty of me to bring up :D

**Comment by frozenhelium** [comment]
@teklal The method how we capture map is quite similar to doing a screenshot of the visible area. So, the resolution and size will be the same to how it looks. There isn't any immediate or an easy solution for this. This requires some research on how to implement and will effect all the maps site wide.

**Comment by teklal** [comment]
Copy that @frozenhelium. Thanks for being on the fixes so fast!

**Comment by teklal** [comment]
Thanks @frozenhelium, I checked this morning and saw that you had fixed a bunch!

Added a few more small things to the ticket (none of them major, can wait until after this first push to prod). 

Just to clarify what I meant with 

> On the form: National Societies in dropdown list should follow the alphabetical order of the country name of that NS

The list to be like e.g. here: https://data.ifrc.org/fdrs/societies or in the PER NS dropdown https://go.ifrc.org/account#per-forms i.e. that instead of using the first letter in the NS name to sort alphabetically, use the name of the country. Again, this is not something super urgent to address, more of a nice cosmetic thing.

**Comment by lauripynnonen** [comment]
@teklal I think this is the one Luke referred to, wanna give it a glance? This is a great ticket!

**Comment by teklal** [comment]
Thanks, most of these are now working.

A few more comments:
- [ ] The NSs still do not appear alphabetically based on the country - @frozenhelium let me know if you need further clarifications on this. Also if this is going to take a lot of time, may not be worth it.

- [ ] Would it be possible to have a dash between All and Status in the dropdown on the country 3w page like there is on the regional view (7th point in the ticket above)
![image](https://user-images.githubusercontent.com/52411237/82441085-ae1e8480-9a9d-11ea-8c10-549b73997353.png)

- [ ] I don't know how easy this would be to do (so if too complex let's forget it), but would be great to have the pie chart on the regional view to go clockwise from largest to smallest segment? (Thanks for having it already start at 12 o'clock!) Let me know @frozenhelium if clarification needed.

**Comment by tovari** [comment]
Closing as almost all items are resolved. The remaining will be appended to another ticket.
