### ISSUE TITLE
3W: Redirect to country 3W from regional page map does not work

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1178]
## Issue
On the regional view of 3W there is the map with the Movement activities. By clicking on a country with activities, a card with info pops up. When clicking on a country name on a card, it should redirect the user to that country's 3W tab.

![image](https://user-images.githubusercontent.com/52411237/80613928-21544e00-8a3e-11ea-88ee-cba4d1b1d94e.png)

The URL on the browser changes but redirecting to the page does not happen.

**Comment by teklal** [comment]
Tested and this works. Great, thanks!

**Comment by lauripynnonen** [comment]
Works for me too!
