### ISSUE TITLE
3W: Project status does not auto-update from "planned" to "ongoing" once start date is reached

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1181]
I set yesterday some projects to start today (2020-04-30) to see if the status would automatically change from planned to ongoing. Unfortunately they didn't, they're still marked as "planned".

Just to check if it is potentially following some other timezone (please tell me if it does) I made a new one now with today's date and that one has "ongoing".

![image](https://user-images.githubusercontent.com/52411237/80685300-43de7980-8ac7-11ea-8721-89d30cc9c641.png)

xref #1036 #1076

**Comment by teklal** [comment]
This also affects these figures on the regional view
![image](https://user-images.githubusercontent.com/52411237/80697938-03d4c200-8ada-11ea-8029-8e796d91143c.png)

**Comment by teklal** [comment]
Hi @frozenhelium, I see you've moved this to Needs Spec - anything you need specified/clarified from our side in order to work on this?

**Comment by frozenhelium** [comment]
@teklal, during the initial discussion of this feature (automatically detecting the project status), it was decided that it'll only assist user while filling up the form (i.e. the system won't automatically change the status afterwards). I'm guessing that the reason behind this might be that a planned project may not start on time and it could be misleading if its automatically changed without the user knowing it. 

So, we wanted to make sure that it's the desired behaviour now. Once you can confirm about this behaviour, we can start implementing this feature.

**Comment by teklal** [comment]
Thanks @frozenhelium. 
There's a ticket (https://github.com/IFRCGo/go-frontend/issues/1076) about this so at least at some point this was desired behaviour but I understand that things may have changed since then. 
Maybe @lauripynnonen can input as to what we want to do about this is?

**Comment by frozenhelium** [comment]
@luisfanovich Do we have a finalized behaviour for this?

**Comment by LukeCaley** [comment]
As agreed on the GO call (16/04) The desired behaviour should be that the project status _should_ auto-update as per original requirements.  cc @frozenhelium @luisfanovich

**Comment by thenav56** [comment]
This is now ready for testing at the staging server.

Changes: Added a cronjob (every 6 hours) that changes the project's status automatically using start/end date.

**Comment by tovari** [comment]
hi @thenav56,
thanks for the implementation. I have checked it and looks like the start date doesn't change to Ongoing, while the end date triggers correctly the completion:
![image](https://user-images.githubusercontent.com/68283148/115884289-064ccc00-a44f-11eb-899c-ce80731015c4.png)

**Comment by tovari** [comment]
As agreed on the GO call on 23.04., the end date will also automatically trigger the status update from Ongoing to Completed status.

We plan to have email notification service to the project creator, when end date is approaching, let them know that the status will be updated automatically, This will be implemented through a separate request. cc: @LukeCaley

**Comment by thenav56** [comment]
@tovari Thanks for the feedback.

Could you let me know if this behavior is okay?
```
For given date for a project
    start_date = 2012, 11, 12
    end_date = 2012, 12, 13

the status should change as below for the current date as.
-> 2011, 11, 11 => PLANNED
-> 2012, 11, 12 => ONGOING
-> 2012, 11, 13 => ONGOING
-> 2012, 12, 13 => ONGOING
-> 2012, 12, 14 => COMPLETED
```

**Comment by tovari** [comment]
@thenav56, yes, this how it should work. Thanks!

**Comment by thenav56** [comment]
@tovari This is now ready for testing at the staging server.
