### ISSUE TITLE
Updates required to admin1 layers and pcodes of some countries

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1188]
A ticket to keep track and list countries for which this issue is known and/or has been flagged to us by users.

The admin 1 level boundaries and/or names have changed for some countries and are not anymore in line with what we have on GO.

Issue identified for:
- Nepal
- Kazakhstan

## Related feature
#938 

## Impact
Affects especially the field report and 3W functionalities

**Comment by batpad** [comment]
cc @geohacker for visibility

**Comment by nanometrenat** [comment]
Re pcodes, from @simonbjohnson

the pcodes for Kenya on the 3W export are different from those on HDX
Example
GO 3W: Garissa KE107
HDX: Garissa KE007
https://data.humdata.org/dataset/ken-administrative-boundaries/resource/d3a5be7a-a15a-4cff-8cf1-908b3df3bbef

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/1485 which was just logged by a user re Nepal

**Comment by geohacker** [comment]
Also ticketed separately on why we can't import Nepal data https://github.com/IFRCGo/go-frontend/issues/1422

**Comment by jhenshall** [comment]
Nepal has now been fixed. Kazakhstan to be reviewed.

**Comment by jhenshall** [comment]
Note that Nepal has been added but the Admin1 codes remain blank as they weren't in the shapefile. These should be added before closing this ticket, but I have closed #1422 - which is a similar issue, specific to Nepal.

**Comment by jhenshall** [comment]
ICRC admin1 update still uses old Nepal divisions, so Nepal codes added according to [OCHA Common Operational Dataset (COD)](https://data.humdata.org/dataset/administrative-bounadries-of-nepal):
| admin1Name_en | admin1Pcode |
| --- | --- | 
| Province 1 | NP01 |
|Province 2|NP02|
|Bagmati|NP03|
|Gandaki|NP04|
|Lumbini|NP05|
|Karnali|NP06|
|Sudurpaschim|NP07|

**Comment by jhenshall** [comment]
Closing this ticket as the original issue is now sorted: Nepal has been updated and can't see any issues for Kazakhstan (but happy to reopen if I've missed it).

Noting the comment:
> the pcodes for Kenya on the 3W export are different from those on HDX
> Example
> GO 3W: Garissa KE107
> HDX: Garissa KE007
> https://data.humdata.org/dataset/ken-administrative-boundaries/resource/d3a5be7a-a15a-4cff-8cf1-908b3df3bbef

This issue is the same for a lot of countries and because the pcodes are drawn from ICRC shapefile, rather than the OCHA's Common Operational Datasets (CODs). It is a shame that they don't align but will need discussing with ICRC about updating their source - or need considerable scoping and mapping out if we're to change GO.
