### ISSUE TITLE
[Staging] Fix validation for Field Report form

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1189]
## Issue

Need to add validators in the date entries and fix the validation for numeric fields to allow entering only positive integer values.

## Steps to reproduce

- Entry the "start date" and "date of data" with upcoming dates.
- Entry decimal numbers on numeric fields.

## Expected behaviour
- The field of dates must not allow the entry of later dates.
- The field of numbers must allow only the entry of integer positive.

## Criticality/Urgency
It is not a blocker, but it should be fixed to have consistent data.

**Comment by necoline** [comment]
@karitotp I am unclear on the ideal validation for the start date. If it's an event, users should select a date in the past, if it's early warning it should be a date in the future right?

**Comment by karitotp** [comment]
Hi @necoline, I assumed that the dates should be only dates in the past, because the date of the data is talking about when was reported the registered and dead cases, and the start date have as help text "The date when the first case is confirmed.". 
I do not sure about a FR as an early warning. I think @nanometrenat can clarify which is the best validation for these dates.

**Comment by batpad** [comment]
Have commented on the PR: but my suggestion for the dates would be that validating that something "is a date" is good enough and let's not get into enforcing specific date ranges or past / future restrictions. I think this can likely get messy with various edge cases, and has the potential to frustrate users a bit. My suggestion would be to just validate that something "is a valid date" and not enforce before / after restrictions.

However, of course, @nanometrenat or @mmusori is likely the best to take a call on this, whether we do want to enforce certain date fields to always be either in the past or the future.

**Comment by nanometrenat** [comment]
Thanks for tagging me in @karitotp @batpad I'm sorry I didn't see this ticket earlier else would've commented.

Agree that we only want to just check that the input "is a date" and not also check past/future.  Partly because the business rules aren't well defined - would not only need clear business rules for early warning vs event when creating the FR, but would ALSO would need to cater for the fact that people often _edit_ existing Field Reports after several days/weeks have passed.

And, being "from the future" myself (NZ being 12-13 hours ahead of UTC) we would also need to ensure that "today" is the right "today" (server time vs user local time) as I know for some systems NZers can only use them in our afternoons (as by that time the Europe date is the same date as NZ).

SO... I suggest keeping with @batpad suggestion and if validation rules are needed then the business (i.e. @mmusori ) can define them once back from leave.  CHEERS ALL

**Comment by karitotp** [comment]
@necoline @batpad, validations are working good.

Only one thing, in Numeric Details, the help text below the fields are not displayed like in Contacts.

![Screenshot from 2020-07-31 09-53-17](https://user-images.githubusercontent.com/11504548/89047223-be5fa500-d313-11ea-9e56-54bf01a2d4ed.png)
_Numeric details_

![Screenshot from 2020-07-31 09-53-28](https://user-images.githubusercontent.com/11504548/89047204-b7d12d80-d313-11ea-8873-10d922f77d82.png)
_Contacts_

**Comment by necoline** [comment]
Great catch @karitotp there was an issue specifically with the display of the error message on `epi-source` numeric entry. I pushed up a fix for this. It is available on the same test url as before

**Comment by LukeCaley** [comment]
Is this now ready for QA? @necoline

**Comment by karitotp** [comment]
@necoline, this looks good now :+1:, the error message is displayed in numeric details too.

**Comment by LukeCaley** [comment]
assuming this is now in staging, @nanometrenat would you mind dong the QA honours?

**Comment by nanometrenat** [comment]
Hi @LukeCaley think there is still ongoing work around FR validation - see https://github.com/IFRCGo/go-frontend/pull/1513 where @necoline checked in more changes yesterday based on previous comments from @karitotp 

@karitotp once you're happy with the validation being in steady state can you please let me know and I will have a quick look again after that.  THANKS ALL!

**Comment by karitotp** [comment]
@necoline I tested the FR validations and most things are working good, some things that I found I commented here https://github.com/IFRCGo/go-frontend/pull/1513#issuecomment-676442923

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/1535 logged re other validation issues (thanks @karitotp !)

**Comment by LukeCaley** [comment]
@nanometrenat would you mind testing for UAT please?
