### ISSUE TITLE
3W: Sample lists for bulk upload

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1197]
would it be possible to get an export of the tables from 3w that have predefined values? This includes
 
- Country Names, 
- Regions, 
- National Society names (these seem to be just country names in the bulk upload?!)
- Operation types
- Programme types
- Sectors
- Tags

This would make bulk uploading a lot easier

**Comment by frozenhelium** [comment]
@GregoryHorvath We'll need to access production DB to fetch the list for that

**Comment by thenav56** [comment]
> @GregoryHorvath We'll need to access production DB to fetch the list for that

@GregoryHorvath No worries we used the API to fetch the data.

@lauripynnonen Here is the export [GO-Project-Upload-options.xlsx](https://github.com/IFRCGo/go-frontend/files/4579984/GO-Project-Upload-options.xlsx) with options for
- Country Names
- Regions
- National Society names (Yes they are country names)
- Operation types
- Programme types
- Sectors
- Tags
- Statuses

**Comment by lauripynnonen** [comment]
Thank you @thenav56 - Almost perfect. However, in 3w the regions are the regions within the country (like provinces or Admin 1), not the regions as in MENA or Europe

**Comment by thenav56** [comment]
@lauripynnonen Sorry about that. Here is the new export 
[GO-Project-Upload-options.xlsx](https://github.com/IFRCGo/go-frontend/files/4580116/GO-Project-Upload-options.xlsx)

**Comment by lauripynnonen** [comment]
@thenav56  thank you! The next iteration for this is going to be more difficult - could we have the regions grouped per country? For example like this
![image](https://user-images.githubusercontent.com/8285694/81147962-a6c68980-8f7b-11ea-9794-22b57b55ca41.png)

**Comment by thenav56** [comment]
@lauripynnonen Sure, here is the export with district group by countries. 
[GO-Project-Upload-options.xlsx](https://github.com/IFRCGo/go-frontend/files/4586196/GO-Project-Upload-options.xlsx)

FYI: There as some districts names which have a newline character in the production.
```csv
ID, Name
1159, Grad Zagreb (CITY OF ZAGREB)\n
1160, starska\n
1161, Karlovacka\n
```

**Comment by lauripynnonen** [comment]
@thenav56 This is so cool! Thank you! I tested with my file and it went in perfectly. 

I assume the export syntax no longer matches the import right? Might have to create a feature request for that...
