### ISSUE TITLE
3W: National Society view

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1198]
We are asking (Partner) National Societies to upload and manage their 3W data autonomously, but we do not provide an easy way for a National Society to access and administer all their 3W projects from a single page. Hence we should figure out a way to have a National Society view that would
- Show them a table of all their activities 
- Enable them to edit the activities directly in that table, where the list values would have (searchable) dropdowns like the original form does (this would be so awesome)
- Allow them to filter their projects based on region, country, type, sector, tags
- Allow them to export and bulk upload activities from a single page
@yellowumbrella-design is this something you could design?

**Comment by yellowumbrella-design** [comment]
@lauripynnonen probably yes, let's sync on this?

**Comment by mariam-yu** [comment]
@lauripynnonen Finally got to creating some mockups for this: https://invis.io/3QY3M2D9NJW#/372627192_3-2-1_GO_Country_3W Let me know your thoughts. Some comments and questions:

1 - Combined the Local and External projects if available. For example, Netherlands may do projects within their country but also quite a lot outside. Does this work?
2 - Proposing to put them both in the 3W tab.
3 - We should validate these with someone from NS (?) to make sure the info we are putting up is the most important (e.g. the people reached on top, etc.)

Want to make sure we are in line with terminology. 
- Are we call them _projects_ or _activities_? (@mmusori tagging you as I think you already weighed on this).
- Is it _reporting NS_ or _supporting NS_ vs _supported NS_ or something in that line? Reporting is specific who reported but may be a bit misleading just in case they report for others? (e.g. Philippines reports that Netherlands does some projects)
- Are we calling ongoing projects/activities or active projects/activities (@mmusori for consistency across the platform).

**Comment by lauripynnonen** [comment]
Comments from end-user (Henk, NLRC):

- [ ] rename the tab to "Activities (3W)". And not "Movement Activities".
- [ ] In this tab there are two sub-tabs. This is where it now gets confusing. I would make the two tabs as follows: Activities in country and NS activities in other countries. The "in-country" could show the map of the country with all the activities done by Movement partners as well as the HNS. Possibly with a filter of Movement Partners and National Society. Just like it is currently done of the NS activities tab.
- [ ] The Activities in other countries could then show a world map and show in which countries the NS is doing what kind of projects. Similar to 3W on the regional page.
- [ ]  It would be nice (in the country overview) to also have the number of regions mentioned in the table. For instance: have a column "Regions" in which the number of regions is mentioned and with a mouse-over effect (or click) a pop-up with the names of the regions.

My comment: The table that lists all the National Society Activities in other countries should have a table where the user could directly edit the contents of the table

**Comment by mariam-yu** [comment]
@lauripynnonen @mmusori So, 3Ws are updated: https://invis.io/3QY3M2D9NJW#/372627192_3-2-1_GO_Country_3W Please take a look when you get a chance.
- Updated terminology, so now it's all Projects and not Activities, Receiving/Sending NS (unless can be completely avoided ;) ), not Regions but Districts, and such.
- Clearer distinction what each section represents with organized tables


Questions:
- In the second section (NS with external projects), are we only showing ongoing projects or all?
- Lauri to clarify what timeframe we are using for Total Projects numbers.

Thanks!

**Comment by lauripynnonen** [comment]
In the second section (NS with external projects), are we only showing ongoing projects or all?
- I would say all (they can be filtered to cover only ongoing right?)
Lauri to clarify what timeframe we are using for Total Projects numbers.
- Should we use the past 12 months for the total project numbers (with some kind of a disclaimer?)

**Comment by mariam-yu** [comment]
@lauripynnonen Thanks. I replaced the Tags filter with Status. Not sure if they would want a Tag filter? (Above the map). let me get back to you about the date ranges. Will check across the site and see what's consistent.

**Comment by mariam-yu** [comment]
@LukeCaley This needs an approval/review from you: https://invis.io/3QY3M2D9NJW#/372627192_3-2-1_GO_Country_3W We split the NS view into 2: a) showing local projects in the country (from self or other NS), and b) showing external projects by the NS in other countries. Let us know your thoughts. Also, we cleaned up the terminology and such.

**Comment by LukeCaley** [comment]
Thanks.  Looking good.  Next step will be to ask member NS their opinion.  Can you open these 3w designs up to comments in Invision please @mariam-yu ?

**Comment by mariam-yu** [comment]
@LukeCaley Sounds good! I opened up the comment section and removed the links from the two 3W pages so that the users don't hop around. Is that what you had in mind or we allow them to explore the rest of the country pages?

This is the link with comments on: https://invis.io/3XX6LHEPNYC#/372627192_3-2-1_GO_Country_3W (PW: GOprototype)

**Comment by LukeCaley** [comment]
Implemented https://github.com/IFRCGo/go-frontend/blob/develop/CHANGELOG.md#release-430 ref front-end: https://go.ifrc.org/countries/68/#3w
