### ISSUE TITLE
Spacing - reduce for headers across (including home page)

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1201]
Currently, there is a lot of white space across the platform. Important information is pushed down. The goal of this task is to reduce the space as much as it visually looks good.

**Comment by imohkay** [comment]
@mariam-yu @maisa-yu Could you clarify what you mean by headers? Do you mean the top page titles, or the secondary titles in uppercase (Like Active Operations and Highlighted Operations on the home page, for example)?

**Comment by maisa-yu** [comment]
@imohkay That would be the top page titles. On zeplin you can find it as Country Page Headers (some have the key numbers integrated and others don't).

**Comment by imohkay** [comment]
@maisa-yu Okay. Thanks :)

**Comment by nanometrenat** [comment]
As per @LukeCaley this looks fine - release tracked under https://github.com/IFRCGo/go-frontend/issues/1325 so closing this ticket as not on any board.
