### ISSUE TITLE
Map - styling updated

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1202]
Visual clean up of the map to pass on to devs, including review of the colored dots, legends, popup and such.

**Comment by mariam-yu** [comment]
Design should tackle the following:

- Map - table correlation: Make the map and table correlation clearer that the filters apply to both and that visually they are connected.
- Maps are taking too much space: Reduce the size of the maps across the platform, may be besides home.
- Map table pagination vs View all: How much is shown in pagination and how much goes into view all?
- Map legends, filters and toggle
- Map colors and what they represent
- Map functionality - to be validated with dev.

**Comment by mariam-yu** [comment]
Please take a look at some suggestions of the UI for the map. We are trying not to deviate much from the new branding guidelines, but it doesn't give much wiggle-room. 

// Option 1: proposing to remove the dots and use highlights on the map directly for Appeals, DREF, and mixed. We lose the scale element, but that was kind of missed anyway. The advantage is we can have comfortable hovers over every country to allow clicking through, even if there are no appeals/DREFs. 

Alternatively, we can use the same coloring to show the number of emergencies per country, while having Appeals and Drefs only in a dropdown.

![1 0_GO_Home  Map 1](https://user-images.githubusercontent.com/60006476/86244160-d4a90280-bba7-11ea-8857-899f7967996c.png)

// Option 2: improved color scheme based on new guidelines and cleaned up legends/dots
![1 0_GO_Home  Map 3](https://user-images.githubusercontent.com/60006476/86244173-da064d00-bba7-11ea-9dc9-9034fc100fe7.png)

// Option 3: lighter option to have the dots pop
![1 0_GO_Home  Map 4](https://user-images.githubusercontent.com/60006476/86244179-da9ee380-bba7-11ea-9c57-46b3861fba51.png)

// Option 4: playing with background vs back, making the background darker
![1 0_GO_Home  Map 2](https://user-images.githubusercontent.com/60006476/86244170-d8d52000-bba7-11ea-8b74-c1741d0035f7.png)

**Comment by LukeCaley** [comment]
Thanks @mariam-yu.  Handing over to @jhenshall to move the MapBox styling along with @geohacker.  

- Personal preference is for concentric circles for lighter red for DREF, darker tone for Appeals and concentric circles of the two for Multiple Types.  This would give the sense of flow from small to large.  

- It would also be good to size these bearing in mind that eventually we might want to fill the circles with the Emergency Response Framework crisis categorisation @mmusori.

- Final point I would make is to consider potential implications and recommended way forward around revision of map projection and placement such that we are representing land area and not obscuring our antipodean friends.  

Welcome to the team @jhenshall

**Comment by mariam-yu** [comment]
@LukeCaley Thanks Luke, let us make some updates and provide for finalization (@maisa-yu )

**Comment by mariam-yu** [comment]
@jhenshall and @LukeCaley, here is an updated version of the map. 

1 - **Scale**: So, what we are proposing (if that's possible) to have the space around the dots change in scale depending on the number of emergencies. Currently we the scale either by people targeted or financial requirements, but the interviews showed that people wanted to know more how many emergencies were in each of those dots to see where the hubs are. The middle dot would stay consistent in scale, while the transparent layer around would scale. This way, the dots can even overlap without conflict.
2 - **Colors**: Regarding colors, we kept blue for multiple as it's a bit hard to do an overlap of dref and appeals reds, but also to add a bit of a color contrast to lots of red. We are also proposing a bit more neutral map background so that the dots stand out more (we need to test this out on printing and projections). A note about the map: the full map (including the antipodean friends :) ) I think will be directly on the mapbox properly visible.
3 - **Text**: We have a few examples of country names, but to be tested with scale with the Mapbox implementation.
4 - **Country Hovers**: Lastly, each country should be hoverable and clickable regardless of the dots (would that be possible?); example here -  Argentina. Clicking on the country would take them to that country page.

Please share your thoughts, and looking forward to seeing how this comes out on mapbox. Once the direction is approved, we will provide the rest of variations. Thanks!

https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/429808499_Map_4

**Comment by jhenshall** [comment]
Thanks @mariam-yu, looks great! Really like the design for the dot size and definitely need to consider what the scale actually shows as mentioned in #1079. To be honest, I'm not certain what is possible in MapBox yet but will explore properly once we have the data in order.

**Comment by LukeCaley** [comment]
1 - Scale: I like the concentric circles concept.  Agree that this would allow for greater variance in symbology size too.  I am sceptical that number of emergencies is more valuable as a reference point for current importance than people targeted.  
2 - Colors: Not sure we want blue as it has a different semiotic connotation.  Suggest yellow / orange to denote similar but different.  
3 - Text:  Like the concept but not sure how feasible in MapBox @jhenshall @geohacker 
4 - Country Hovers: Like the concept but not sure how feasible in MapBox @jhenshall @geohacker

**Comment by mariam-yu** [comment]
@LukeCaley Thanks for your comments! Let us then take another stab at the color instead of blue (@maisa-yu). 

Regarding the scale, it's something we can test but it seemed from the interviews that the immediate reaction was to see how many emergencies are in those popups. Also people completely ignored the toggle between people targeted and financial. So, our suggestion is to remove that completely, but your call.

As for the rest, will wait for Johnny to play around with Mapbox.

**Comment by LukeCaley** [comment]
Thanks @mariam-yu. I'm sure you're already aware but https://colorbrewer2.org/ is a good resource for this.

**Comment by geohacker** [comment]
This looks neat @mariam-yu. The labels, hovers, and popups should all be possible. It will be a bunch of work, but definitely possible!

**Comment by mariam-yu** [comment]
Thanks @LukeCaley and @geohacker ! @LukeCaley how is this yellow for multiple types? https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/429808499_Map_4

**Comment by batpad** [comment]
Oops, auto-closed accidentally, re-opening.

**Comment by batpad** [comment]
Map styling updates have been merged to develop which should update the map styles on the home page as well as the region pages:

 - Base map styling updated as per designs
 - Colours of points and on legend updated as per designs
 - Popups styling updated as per designs
 - Mousing over a country highlights it
 - Clicking on a country, even with no emergencies, shows a popup to be able to navigate to the country
 - Clicking anywhere on the country for a country with emergencies shows the popup with operation details

@karitotp would be great if you're able to test all of the above, especially navigating to countries via clicking on the map, also that the popup styling, etc. looks consistent and good across languages (especially to check Arabic).

cc @geohacker @jhenshall @mariam-yu @LukeCaley @tovari

**Comment by mariam-yu** [comment]
@batpad Woa! Excited to see this! A few comments:

1 - The dots seem a bit small to me. Do you think we could make the starting point for the size a bit bigger (similar to Zeplin) or will that be unscalable?
2 - The hover works for me in a funky way; there seems to be a big delay on when the hover color appears and it doesn't always work. You need to hover a few times over a country to the hover to appear (this could be due to the delay). Also, can we make it an arrow instead of a hand for the mouse pointer?

A comment and a question for @LukeCaley : 

a) We decided to keep the legends as they are for now to have a gradual update, but ultimately, from YU side, we are proposing to have the dots represent the numbers of operations, as this will give a good overview of where the most emergencies are happening.

b) There is currently a popup on the countries without a dot that says "no current operations" - this was a solution to have the popups be consistent for all the countries for navigation. But should we say "no IFRC-led operations" to be more specific?

Thanks!

**Comment by karitotp** [comment]
@batpad, here what I found testing the map

> Base map styling updated as per designs

The size of dots on the map are smaller than the style in zeplin

> Colours of points and on legend updated as per designs

The color of points in the legend don't looks same as the design in zeplin

![Screenshot from 2020-12-08 15-55-35](https://user-images.githubusercontent.com/11504548/101540378-e8823d00-396d-11eb-9c43-cf42e20bf352.png)
_Legend in staging_
![Screenshot from 2020-12-08 15-55-59](https://user-images.githubusercontent.com/11504548/101540383-eb7d2d80-396d-11eb-8a74-cad4bc94b768.png)
_Legend in zeplin_

> Popups styling updated as per designs

This looks good.

> Mousing over a country highlights it

As Mariam's comment above, there is a delay in highlighting the countries.

> Clicking on a country, even with no emergencies, shows a popup to be able to navigate to the country

This works correctly, but some observation are:

- There is a country in Europe ("Kosovo") next to Montenegro that is not displaying the name of the country.
![Screenshot from 2020-12-08 16-43-21](https://user-images.githubusercontent.com/11504548/101544926-82e57f00-3974-11eb-84d1-521e66336a0b.png)

- In Arabic language there are some countries that is not being translated. For example: Kingdom of Cambodia, Malasia, Kingdom of Thailand.

![Screenshot from 2020-12-08 16-56-35](https://user-images.githubusercontent.com/11504548/101546369-ad383c00-3976-11eb-92bf-0d47211044c8.png)

> Clicking anywhere on the country for a country with emergencies shows the popup with operation details

This works correctly

**Comment by jhenshall** [comment]
Firstly, they look super nice - so much cleaner and I much prefer the lighter grey! 🙂  Nicely done all.

But a few things key issues:

1. As mentioned by @karitotp - Kosovo, along with Western Sahara, are displayed as separate countries to Serbia and Morocco respectively. This is critical but hopefully solved by the solution we discussed @geohacker with overlapping the boundaries?
2. Disputed boundaries - these are currently a slightly thicker white line when zoomed but should be a clear dashed line at all zoom levels.
3. Some country names in the pop-up do not match the country name in the database but use the longer 'official names' e.g. Mali > Republic of Mali. Saudi Arabia > Kingdom of Saudi Arabia. Can we keep these as names in GO database?

A couple more minor:

- It's hard to click on countries with small landmass, such as island nations, even when there is an emergency - e.g. Bahamas. It would be great if clicking on the label brings up the popup, so that e.g. Maldives can be selected but might be difficult! Can we at least have that emergency dots are clickable (it seems the cursor changes to a point, but doesn't click).
-  Weird district labels in Bulgaria (I actually think this carried over from last map!): 
![image](https://user-images.githubusercontent.com/6359748/101550228-d8d31a80-39a6-11eb-825b-85ca7dc1632b.png)

Thanks all! cc @batpad

**Comment by geohacker** [comment]
### @mariam-yu 

> 1 - The dots seem a bit small to me. Do you think we could make the starting point for the size a bit bigger (similar to Zeplin) or will that be unscalable?

Just made them a bit bigger, hope that's alright. Let me know if it needs to be bigger. I've scaled the inner circle and the outer circle scale factor.

> 2 - The hover works for me in a funky way; there seems to be a big delay on when the hover color appears and it doesn't always work. You need to hover a few times over a country to the hover to appear (this could be due to the delay). Also, can we make it an arrow instead of a hand for the mouse pointer?

The hover is a bit slow but we're looking to find different ways to address this. Unfortunately one way is to remove all the mouse pointer transition. So now the mouse point will remain consistent instead of changing as and when the user is panning or moving on the map. This was causing quite a lot of render delays which we can avoid for now. If you think it's absolutely essential, I can turn it back on.

> We also had a "Last Update" date. Was this something we can/are planning to add? 

We don't know if we can do it at the moment. This may have to come from the API but at the moment on the side burner.

> Link hovers

We'll check!

### @jhenshall 

> Kosovo, along with Western Sahara, are displayed as separate countries to Serbia and Morocco respectively. 

So this comes from the data that's already in GO and may not be fixed until the data refresh. In the meantime @batpad is trying to address this by not highlighting in case the country is independent=false. If that's not enough, then we might take out this hover-highlight feature entirely for now.

> Disputed boundaries - these are currently a slightly thicker white line when zoomed but should be a clear dashed line at all zoom levels.

Could you share screenshots? We have not made any changes to disputed boundaries both fill and lines. So I'm a bit unsure what you mean here.

> Some country names in the pop-up do not match the country name in the database but use the longer 'official names' e.g. Mali > Republic of Mali. Saudi Arabia > Kingdom of Saudi Arabia. Can we keep these as names in GO database?

The country names should be fixed now. 

> It's hard to click on countries with small landmass, such as island nations, even when there is an emergency - e.g. Bahamas. It would be great if clicking on the label brings up the popup, so that e.g. Maldives can be selected but might be difficult! Can we at least have that emergency dots are clickable (it seems the cursor changes to a point, but doesn't click).

We'll make it possible to click on the landmass as well as the circle

> Weird district labels in Bulgaria (I actually think this carried over from last map!):

Yeah I've no idea why these exists as a separate layer on Mapbox. I was hoping you'd know :)

**Comment by batpad** [comment]
> 3 - For the popup styling, could you please check Zeplin? The arrow should be a bit different and the font type for the content seems bolder. Lastly, could you and/or @imohkay check the hover styles for links? @maisa-yu can help with this across the site.

@imohkay - can you please look at these?

**Comment by mariam-yu** [comment]
Thanks @geohacker . @maisa-yu Can you please review the dots on the map and popup styling - we have standard link hovers across the site, we should have those in the popups as well. Thanks!

**Comment by maisa-yu** [comment]
@geohacker Thanks for the changes!
Some comments from my side:
**Dots:** 
Still seems a bit small, could you make it bigger? In the prototype we did 8px for inner circle and 16px for outer circle, not sure if that is the same on your side, but it would be great to make it bigger and easier to click on.
**Country names:**
Size seems fine, but could you make it black instead of blue?
**Pop up**
The font on the pop up seems a bit bolder, can we make it with 300 (Poppins light)?
Also, a detail on the hover X, can we make it round instead of oval? you can check an example here: zpl.io/adgX49p

**Comment by jhenshall** [comment]
@geohacker - I've gone ahead and made the disputed boundaries visible. @mariam-yu - I wonder if we should make the grey _slightly_ darker, just to bring up the contrast a little bit? Or is this grey set with the colour pallete?

**Comment by mariam-yu** [comment]
@jhenshall Are you referring to the disputed one or in general? Tagging @maisa-yu from our side for colors and such.

**Comment by maisa-yu** [comment]
@jhenshall we have a little flexibility on the grey palette, we could increase a tiny bit to a #DDDDDD or similar. 
But just being careful to still keep the contrast with the hover (let's keep that one as it is for now).

**Comment by jhenshall** [comment]
Just reviewing the map on homepage after this ticket: #1810. The reds of emergency appeals and DREFs look very similar on the map - could we change the colours of the points and legend to match those used in the graphs further down the page:

 - Emergency response = lighter red (no change needed)
 - DREF = orange

I know we also have Early Action Protocol Activation being added as blue. This then leaves question of colour for multiple types - any thoughts @mariam-yu? I will also experiment with colours.

Finally, it's not clear to me what the grey 'Movement Response' point in legend represents - propose just removing this:

<img width="690" alt="Screenshot 2021-02-16 at 12 31 59" src="https://user-images.githubusercontent.com/6359748/108064021-ff22cf80-7053-11eb-9671-d2cd7cf7a791.png">

cc. @geohacker @mariam-yu @batpad @tovari

**Comment by mariam-yu** [comment]
hey @jhenshall So, we have the colors here in Zeplin (http://zpl.io/2yK3JAo), but sending you the hex codes here in any case:

Appeals - #f5333f
DREF - #b61d26
EAP - #4c5d9b
Movement Response - #8d8d8d
Multiple Types - #ff9e00

Could you double check if you have the same? We can always provide variations for the red, tagging @maisa-yu who can help with the colors. As for Movement Response, to be honest we weren't sure as well. So, tagging @tovari who said it's something we need.


<img width="1440" alt="1 0_GO_Home - Map" src="https://user-images.githubusercontent.com/60006476/108240487-cdd4fd00-7142-11eb-8f58-f5b57a00f418.png">

**Comment by jhenshall** [comment]
Thanks @mariam-yu. Could I propose to change DREF to orange which matches the graphs lower down the page (on the site itself, not the design above):

![image](https://user-images.githubusercontent.com/6359748/108704926-911f5200-7504-11eb-8886-5b4e8733adc0.png)


So, on the map it would be:

Appeals - #f5333f
DREF - ~~#b61d26~~ #ff9e00
EAP - #4c5d9b
Multiple Types - ~~#ff9e00~~ **TBC** - any thoughts for this? @maisa-yu

I can confirm that we should also remove the 'movement response' category, which I'm ticketing separately here for better reference: #1835

**Comment by maisa-yu** [comment]
Hey @jhenshall yes, we can put DREF as this orange (#ff9e00) like you suggested. 
But we'll still have the challenge for Multiple types: to find different colours within the red-orange-yellow spectrum that have enough contrast between them. As Multiple Types are not too many, maybe we can try something similar to the dark red (#A4053E) or a more vibrant orange (#FF6B00).

**Comment by jhenshall** [comment]
Thanks @mariam-yu. Yeah the multiple types is tough, especially as the new blue EAP colour is also part of the categorisation (i.e if a country has EAP and DREF - the dot will be 'multiple types').

I'm tempted to go with the orange you suggested (#FF6B00) for now as a quick fix and then we can maybe think about a different way to indicate multiple types that would allow you to see all the different types of operations that a country might have.

**Comment by jhenshall** [comment]
So, to confirm the final colours for the homepage map are:
Appeals - #f5333f
DREF - **#ff9e00** ~~#b61d26~~ 
EAP - #4c5d9b
Multiple Types - **#ff6b00** ~~#ff9e00~~ 

~~Movement Response - #8d8d8d~~ - **Removed entirely**

**Comment by maisa-yu** [comment]
@jhenshall 
Sounds good, we can always adapt the Multiple Types later if it's too similar

**Comment by jhenshall** [comment]
Epic ticket but think time to finally close it. 🙂 Thanks for all the work @mariam-yu @maisa-yu @geohacker! Last thing will be to switch on the hover state when the data and new Mapbox done, but I will ticket this separately.
