### ISSUE TITLE
Table - styling across the platform

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1203]
- Explore View All vs. Expand All options and showing max number of items per tables (across the platform)
- Consistent UI styling for tables (table styling, wrapping headers, removing header filters, adding a filter bar, etc.)

**Comment by imohkay** [comment]
@maisa-yu I'm planning to mimic the styling of the tables on the homepage of Zeplin (including the round numbers for pagination, etc.) Do confirm.
Have the table designs been approved?

**Comment by maisa-yu** [comment]
@imohkay Yes, you can go ahead with the tables. Thanks!

**Comment by imohkay** [comment]
Cool. Thanks @maisa-yu  :)

**Comment by imohkay** [comment]
@batpad I have pushed to branch feature/1203-table-global-styling
For the Funding (CHF) table column on the homepage, could you please add the functionality for a progress bar that indicates percentage for funding? Right now, it just shows the same figure as Requested Amount (CHF).
This is as per the designs on Zeplin. I can style the progress bar as needed.

**Comment by imohkay** [comment]
@batpad I have added the styling for the progress bars for funding, but the values are hardcoded for the Progress bar and the number above. Please could you do the needful?

**Comment by imohkay** [comment]
@maisa-yu @karitotp the updated tables are up on staging. you can take a look and refer to the designs in Zeplin (you can refer to the homepage @karitotp) .
@maisa-yu this doesn't include the search and filters for the table

@karitotp changes include bottom borders only, font sizes, adding a progress bar with percentage for the Funding header, link styles inside tables, etc... If you could just quickly check that the tables across the site are looking like the tables in Zeplin, that would be great :)

**Comment by karitotp** [comment]
@imohkay 
Overall the styles look as the style in zeplin. But I am finding some differences in the table columns between Zepln and the Staging site. Eg, In home page in Zeplin (https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b) there is the operation name as "Operation" column which also can be linked, while in the staging site (https://dsgoproxyapp.azurewebsites.net/) this is as "Name" column and it can not be linked.

![Selection_010](https://user-images.githubusercontent.com/11504548/87174111-5a116e80-c29c-11ea-9805-bfa76c268134.png)
_Table in Zeplin_

![Screenshot from 2020-07-10 10-37-50](https://user-images.githubusercontent.com/11504548/87174123-5c73c880-c29c-11ea-8397-63a9cc0cf57f.png)
_Table in Staging_

Please let me know if this is the home page style https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b that I have to do the comparison with. Also to see the stile for the other pages  I am comparing with the designs GO-UI_V2 in https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb. Am I correct?

**Comment by imohkay** [comment]
@batpad Please see Karito's comment above for the links in TDs for the Name column.

@karitotp you are using the correct home page on Zeplin. And yes, GO-UI_V2 is correct :)

**Comment by batpad** [comment]
Thanks @karitotp .

@mariam-yu @mmusori - with regards to the Operation Links:

This table is a list of Appeals. Only the Appeals that are connected to an Emergency will have a link. Otherwise they just have an Appeal code as we don't have a page for Appeal on the GO site. I might need some clarification on how this all works exactly, but as it stands, only some appeals have links to associated Emergency pages.

I see the design proposes removing the `Code` field, and merging the `Name` and `Emergency` field by linking to the Emergency from the name.

My questions:

 - Do we still want to remove the Code field if everything does not have a link?
 - If an appeal does not have a link, do we just show it without a link, and only hyperlink ones that have associated emergencies?

cc @nanometrenat

**Comment by mariam-yu** [comment]
@batpad Which page is this, the table under the map on the Home?

**Comment by batpad** [comment]
> @batpad Which page is this, the table under the map on the Home?

@mariam-yu yes :)

**Comment by imohkay** [comment]
@maisa-yu Do we have indicative styling for the links in the table footer? The ones with the red underline? Or do those stay as they are? I've attached a screenshot for reference.
![table-links-footer](https://user-images.githubusercontent.com/1667470/87421017-ecdf3f80-c5f3-11ea-9894-e84efced0b6f.png)

**Comment by nanometrenat** [comment]
> Thanks @karitotp .
> 
> @mariam-yu @mmusori - with regards to the Operation Links:
> 
> This table is a list of Appeals. Only the Appeals that are connected to an Emergency will have a link. Otherwise they just have an Appeal code as we don't have a page for Appeal on the GO site. I might need some clarification on how this all works exactly, but as it stands, only some appeals have links to associated Emergency pages.
> 
> I see the design proposes removing the `Code` field, and merging the `Name` and `Emergency` field by linking to the Emergency from the name.
> 
> My questions:
> 
> * Do we still want to remove the Code field if everything does not have a link?
> * If an appeal does not have a link, do we just show it without a link, and only hyperlink ones that have associated emergencies?

Re the Appeal Codes, I would strongly recommend _against_ removing the Appeal codes.  We have been asked by users to ADD appeal codes in more places (e.g. Emergency pages) so it would be disappointing if we removed them here!  Thanks @batpad for flagging!

**Comment by mariam-yu** [comment]
@nanometrenat good point. agree that we need to keep the codes. https://invis.io/6BWNPV8QEUA#/359175152_1-0_GO_Home updated the wireframes here, the designs will be updated soon as well to match. 

Also, as discussed with @batpad we will have the name and link connected. regarding the table design, can we make sure as much as possible to not wrap the title lines (we removed CHF and % from there, which should help - see the wires). Lastly, updating the margins should give a bit more space too.

Thanks!

**Comment by mariam-yu** [comment]
> @maisa-yu Do we have indicative styling for the links in the table footer? The ones with the red underline? Or do those stay as they are? I've attached a screenshot for reference.
> ![table-links-footer](https://user-images.githubusercontent.com/1667470/87421017-ecdf3f80-c5f3-11ea-9894-e84efced0b6f.png)

@imohkay The **View all field reports** should be the same as across the platform - next to the title on the right, the view by region should be a filter dropdown.

**Comment by imohkay** [comment]
@mariam-yu Thanks. I've put the View all field reports into a separate ticket..

**Comment by mariam-yu** [comment]
@imohkay @batpad So we have updated the designs as well with our discussions for the table and highlighted operations. By the way, we pumped up the text a bit in Highlighted Ops, as it seemed a bit small. Hope it doesn't create much extra effort to update. Let us know. It's all updated on Zeplin too. https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417294996

**Comment by nanometrenat** [comment]
> @imohkay The **View all field reports** should be the same as across the platform - next to the title on the right, the view by region should be a filter dropdown.
Just a reminder here that the key thing is to also be able to EXPORT the Field Reports by region - so please don't do any visual/styling changes that would prevent that from happening.  e.g. if it's just an on-page filter then will users still be able to export by region without things falling over?  Exporting ALL often falls over, so region-by-region is essential functionality for users right now.  Know there are future tickets to make the export process more robust, but timing-wise I think the styling changes are going out first so it's critical to ensure that styling changes don't inadvertently stop users from doing the exports.  Thanks a lot.

**Comment by LukeCaley** [comment]
@mariam-yu please confirm that tables are implemented as per designs on Zeplin across all expected components.

**Comment by LukeCaley** [comment]
Things I'm not that pleased with:

- Jumpy loading when clicking on the next page of a table leaving the view not necessarily in the same place as prior to clicking to change page
- Occasional slow rendering of tables - is this a GO / bandwidth / consistent connection / browser issue? cc @batpad 
- Length of NS name and Rapid Response spilling over to next line in Deployments page - surely we could find an elegant way to avoid this as Rapid Response will be the type for most 
![rap-response](https://user-images.githubusercontent.com/7791954/89342787-9372a980-d6a3-11ea-9c38-f4f4039d309d.JPG)
- Re Deployments, the type should read HeOps not HEOP
- Why are the selected types not in **bold** when all others are - surely this the wrong way around?

![highlighted-why](https://user-images.githubusercontent.com/7791954/89342772-8e155f00-d6a3-11ea-973a-c64c235c2799.JPG)

**Comment by nanometrenat** [comment]
@LukeCaley FYI a couple of points above are as-per-current (i.e. not regression), which may or may not affect the request to fix in this release:
> * Length of NS name and Rapid Response spilling over to next line in Deployments page - surely we could find an elegant way to avoid this as Rapid Response will be the type for most

_Earlier in this release the NS names were 4 lines so we are winning by having it as 2 ;) FYI current live site has RR and NS on 2 lines_

> * Re Deployments, the type should read HeOps not HEOP

_This is as per current live site.  There are quite a few things on this page that will need to change as part of surge integration, suggest we not worry too much right this instant.  If we were to worry about one thing on this page nownow personally I'd prioritise RR not appearing on the map at all..._
> * Why are the selected types not in **bold** when all others are - surely this the wrong way around?

_This is as per current live site._

Agree on the point re loading often being slower than usual though - however the other week it was superfast - doesn't seem to be constant loading times.  See [Teams thread](https://teams.microsoft.com/l/message/19:8f526fd5b918469799d2462ff2c5e1f0@thread.skype/1595407246625?tenantId=a2b53be5-734e-4e6c-ab0d-d184f60fd917&groupId=be22b1e3-23ec-4ddd-80cd-dc7ab032d2eb&parentMessageId=1595407246625&teamName=GO%20-%20Public%20channel&channelName=General&createdTime=1595407246625)

**Comment by batpad** [comment]
> Jumpy loading when clicking on the next page of a table leaving the view not necessarily in the same place as prior to clicking to change page

@LukeCaley do you see this as a regression / worse than the current state? Right now, we have logged a separate issue for this: https://github.com/IFRCGo/go-frontend/issues/1458 but as it did not seem like a regression, was aiming to tackle it in a next release. This does seem a bit tricky to get right - I believe this redesign does come with some improvements to the pagination: improved styling, hiding pagination when not required. I absolutely agree that the jumpiness when paginating is pretty terrible. Happy to prioritize this as you see best, though it's a bit hard for me to get a concrete sense of how much of a rabbit hole / how much work this would be. I'll spend some time this afternoon to explore quick-fix improvements or be able to have a better sense on the approach / time estimate for this.

> Occasional slow rendering of tables - is this a GO / bandwidth / consistent connection / browser issue? cc @batpad

Is there a specific table where you see this more often? I'm having a hard time reproducing this.

For the other issues that were not regressions, happy to make separate tickets, though hoping they can be non-blockers for the current release.

Thanks again for the detailed testing and feedback here.

**Comment by batpad** [comment]
> Length of NS name and Rapid Response spilling over to next line in Deployments page - surely we could find an elegant way to avoid this as Rapid Response will be the type for most

This should be better now, and Rapid Response should appear on a single line: https://ifrc-go-release-v4-3-11.surge.sh/

**Comment by mariam-yu** [comment]
> @mariam-yu please confirm that tables are implemented as per designs on Zeplin across all expected components.

@LukeCaley the designs are good, but we had also noted some of the issues you mentioned, specifically column widths and the table jumping when clicked on second page. @imohkay thoughts on this? Thanks!

**Comment by nanometrenat** [comment]
Accepting risk, going to Production now
