### ISSUE TITLE
Highlighted Operations - module cleanup

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1206]
- The title should not be cut but should wrap
- The CHF shouldn't wrap
- YU to provide styling for 4-5 operations (e.g. Asia Pacific region page)

**Comment by maisa-yu** [comment]
Highlighted Operations Modules on pages:
1.0_GO_Home
4.1_GO_Emergencies

**Comment by imohkay** [comment]
@maisa-yu I'm going to work on this over the next couple of days. Just to clarify, will follow the design in Zeplin.
Is the Follow button in red on each operation a new functionality?

**Comment by imohkay** [comment]
@batpad I have pushed to branch feature/1206-highlighted-ops-UI
Could you please checkout and fix the following?

1. The Follow button functionality needs to be implemented. On being clicked, the button should toggle the text "Following" and the style to bounded button (You will need to replace the class 'button--primary-filled' with 'button--primary-bounded'.
2. The translation strings will need to be implemented for the above button's toggle text (i.e. 'Follow' and 'Following')

**Comment by mariam-yu** [comment]
> @maisa-yu I'm going to work on this over the next couple of days. Just to clarify, will follow the design in Zeplin.
> Is the Follow button in red on each operation a new functionality?

@imohkay I'll jump in here. So, it's not a new proposed functionality, but I am not sure at which stage of development it is. This is the option to follow or subscribe to emergencies. @batpad May be you know what's happening with that?

**Comment by batpad** [comment]
> @batpad May be you know what's happening with that?

Yup, so the option to Follow / Subscribe exists on individual emergency pages. We'd need to bring this to all pages that show the Highlighted Operations. This should likely be okay to do, I just need to check-in with @GregoryHorvath and sketch out how it would work, will update here.

**Comment by imohkay** [comment]
@batpad the Highlighted Operations sections needs to come after the Key Numbers on the home page (as per the new designs on Zeplin). But some of the components are one big unit, so I would need your help on this.

**Comment by batpad** [comment]
@mariam-yu - quick question: On the button on the Highlighted Operation cards it says `Follow` / `Unfollow`, whereas on the Emergency page we are currently using `Subscribe` / `Unsubscribe` . Should we change to `Follow / Unfollow` on the Emergency page?

**Comment by batpad** [comment]
@imohkay -

> The Follow button functionality needs to be implemented. On being clicked, the button should toggle the text "Following" and the style to bounded button (You will need to replace the class 'button--primary-filled' with 'button--primary-bounded'.

The functionality is implemented now. May need to look at the class name change together, but should be straightforward. This feature will need a bit of testing.

> The translation strings will need to be implemented for the above button's toggle text (i.e. 'Follow' and 'Following')

Done :)

> Once you're done, you can assign the ticket back to me and I'll create a branch for testing.

Could you check it out? Will be great to create a Surge testing URL for this soon. I imagine there are a few things around the Follow toggle that we will just need to test thoroughly.

**Comment by mariam-yu** [comment]
> @mariam-yu - quick question: On the button on the Highlighted Operation cards it says `Follow` / `Unfollow`, whereas on the Emergency page we are currently using `Subscribe` / `Unsubscribe` . Should we change to `Follow / Unfollow` on the Emergency page?

It's more of a @mmusori question. Thoughts? We propose Follow an emergency rather than Subscribe to an emergency, but it's your call @mmusori .

**Comment by mmusori** [comment]
@mariam-yu , For consistence, I agree with you on follow/unfollow

**Comment by imohkay** [comment]
@karitotp Hey... The Highlighted Operations styling has changed to match the designs in Zeplin (see homepage). This is mostly minor changes like font sizes, borders, etc. Also, logged in users can now follow an operation, and the Follow button will change its style and text to say following. If you check that the changes are fine, that would be great :)

**Comment by batpad** [comment]
Would be great to have the `Follow` functionality properly tested:

 - When not logged in, should not see Follow button
 - When logged in, should see Follow or Following based on whether one is already following an Emergency.
 - Should be able to click Follow / Unfollow to Follow and Unfollow
 - When clicked, the state should change correctly.
 - When you reload the page, check that Follow / Unfollow was correctly saved

cc @karitotp

**Comment by karitotp** [comment]
@imohkay @batpad,
The style and the Follow button are correctly and they are working as it is mentioned in the above description :+1:.
The first time I changed the status of the Follow button and reloaded the page, this did not load correctly, the style seemed to be broken. I tried to reproduce this, but I didn't cross with this again and everything looks good after that.

**Comment by mariam-yu** [comment]
@imohkay @batpad question about functionality. Can we have the whole card clickable/hoverable that takes the users to the emergency page, while the follow/unfollow functions separately and can also be clickable/hoverable? Just checking. Thanks!

**Comment by nanometrenat** [comment]
@mariam-yu @imohkay @batpad 
Just going through staging with Daniel, we noticed the below - there is only one emergency highlighted for this region, and there is plenty of space for the full emergency name - yet for some reason it's being shortened with an ellipsis rather than having the full emergency name.  Can you please take a look?
![image](https://user-images.githubusercontent.com/33625192/87944315-877dc980-ca9f-11ea-9cbc-260ec450f03f.png)

**Comment by mariam-yu** [comment]
> @mariam-yu @imohkay @batpad
> Just going through staging with Daniel, we noticed the below - there is only one emergency highlighted for this region, and there is plenty of space for the full emergency name - yet for some reason it's being shortened with an ellipsis rather than having the full emergency name. Can you please take a look?
> ![image](https://user-images.githubusercontent.com/33625192/87944315-877dc980-ca9f-11ea-9cbc-260ec450f03f.png)

@nanometrenat Great catch. We actually just reviewed it today in our audit call. So the devs are on it :)

**Comment by imohkay** [comment]
@batpad @nanometrenat @mariam-yu 
Initially, the character count was 30. On staging, it is currently changed to one line only via CSS (which may spill over to 2 lines).
I will now be doubling the original character count to 60, as discussed in yesterday's call. Let me know if that works. Either ways, will be a simple fix to change things...

**Comment by mariam-yu** [comment]
@imohkay Thank! Could you please share an example of the long title to see how it looks like?

**Comment by LukeCaley** [comment]
Tested in https://ifrc-go-release-v4-3-11.surge.sh/ and looks good, including with 4, 5 and 6 highlighted operations.

**Comment by nanometrenat** [comment]
Moving to "done" (while still open) based on Luke's comment above :)

**Comment by guipizzini** [comment]
This looks great! And functions, after testing! Well done team.
