### ISSUE TITLE
COVID field report // update of wireframes

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1207]
Updating the flow of COVID toggle on field reports on wireframes.

**Comment by mariam-yu** [comment]
@mmusori Updated the COVID flow on the wireframes as per prod. https://invis.io/73X6LF8FZXQ#/416646280_8-5-1_GO_Epi_FieldReports_COVID_1

Also, updated Epi field report flow with the sources (Cases, etc.)

**Comment by mmusori** [comment]
@mariam-yu a few changes have been made to the Covid Field Report. 
1. removing the Info bulletin box.
2.  Switching title with linking to existing emergency.

![image](https://user-images.githubusercontent.com/7780809/82027620-d1f45b80-9694-11ea-8960-6aefcd4f4736.png)
3. The numeric details have been re order to have the source next to the date. 
![image](https://user-images.githubusercontent.com/7780809/82027844-2566a980-9695-11ea-8f4c-b59bfbcf6ea5.png)

4. On Actions for Covid the number of RCRC Movement Personnel has been removed.
![image](https://user-images.githubusercontent.com/7780809/82028118-80000580-9695-11ea-88d8-d7ae89d6fe66.png)
