### ISSUE TITLE
Covid WHO API for cases

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1225]
For Covid Epidata we would prefer that the data is directly piped into the Emergency page via an API from WHO. The input page for the Covid Field Report should  have the Situation page removed. The situation overview is then moved to the the Context page. Thus all the other fields on the Situation page will no longer be be used/exist. 
The API would link to the Emergency pages for each country being reported on.
The data would come from WHO and should only be updated via the API.
The data will be publically viewable.

For this feature to work and be developed we need a stable and accessible WHO API.

**Comment by nanometrenat** [comment]
Closing as Covid is no longer a priority
