### ISSUE TITLE
COVID FR: Change wording of help text for IFRC/Movement Activities fields

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1226]
The help text for the boxes below still implies that there would be checkboxes to choose activities from. 

![image](https://user-images.githubusercontent.com/52411237/81798208-0ee31580-9510-11ea-9cdc-350bbca938af.png)

As in the COVID field reports, these fields are just for text, could the wording be changed to e.g. 

"Describe the activities taken by the IFRC (could be the Regional office, cluster office or country office)"

and 

"Describe the activities undertaken by any other RCRC Movement actor(s)." 

i.e. replacing "Select" with "Describe" and removing "and briefly describe" from the end.

**Comment by teklal** [comment]
This seems like e a quick win/low-hanging fruit.

**Comment by mmusori** [comment]
On the Covid title please update instruction text.  
![image](https://user-images.githubusercontent.com/7780809/82032845-1f27fb80-969c-11ea-9c05-17e56e0ca016.png)
The text should be, "For Covid-19 Field Reports, please link to the existing country specific emergency page. Please do not link to the Global emergency page."

**Comment by batpad** [comment]
@mmusori can you please clarify:

What should the Title help text be for a COVID-19 report (i.e. when Is Covid Report is set to `Yes`)?

What should the Title help text be for a non-COVID-19 report (i.e. When Is Covid Report is set to `No` or is not set yet)?

@mmusori if you could clarify the above, should be easy to fix the title help text correctly. cc @kamicut

**Comment by mmusori** [comment]
"For Covid-19 Field Reports, please link to the existing country specific emergency page. Please do not link to the Global emergency page."

**Comment by mmusori** [comment]
We are just removing, 'if one already exists' because country emergency pages for Covid-19 were created for all countries. And we want NS to link to these pages and not create new emergency pages.

**Comment by batpad** [comment]
@mmusori so, to clarify, the help text for Title will continue being the same for both COVID and non-COVID reports? In which case, this should be ready to go and be tested.

**Comment by batpad** [comment]
@mmusori can you look at https://ifrc-go-fix-1226-fix-covid-language.surge.sh/ and let me know if the behaviour here is what is desired?

**Comment by mmusori** [comment]
@batpad, It looks like the help is the same for all Field Reports and only speaking to Covid. I can make a separate ticket for differentiating the help text.

**Comment by batpad** [comment]
> @batpad, It looks like the help is the same for all Field Reports and only speaking to Covid.

@mmusori that's what I was trying to ask with my previous question :) - if you can let know what the text should be for COVID, and non-COVID, that would be great. Either in this ticket or as a separate ticket is fine. Thank you.

**Comment by mmusori** [comment]
The text I provide above, which is now in the surge is the desired help text for Covid-19. https://ifrc-go-fix-1226-fix-covid-language.surge.sh/reports/new

**Comment by mmusori** [comment]
@batpad for non Covid related we will leave it until we implement the new UI based on the updated wireframes. So for now the solution in the surge url works for me.

**Comment by karitotp** [comment]
Now the texts are shown in the FR Form as it was suggested. In case of the Title the instruction "For Covid-19 Field Reports, please link to the existing country specific emergency page. Please do not link to the Global emergency page." is the same for Covid related and non Covid unrelated.

**Comment by mmusori** [comment]
I have reviewed the text and it matches with requirements. QA pass.

**Comment by teklal** [comment]
Looks good to me too. 

The only "problematic" thing I see is that if a user first chooses "Yes" on the "COVID-19 related" radio button but then changes the choice to "No" the help text stays the same along with some of the choices remaining locked, such as Disaster type. I remember this was the case previously already and based on the discussion then https://github.com/IFRCGo/go-frontend/issues/1160#issuecomment-623324856 the decision was to leave it as it is so I assume it's ok now as well. Just mentioning for records.

So all in all, this looks good from my end.
