### ISSUE TITLE
3W: Add a tag RCCE

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1227]
We need a new tag called RCCE (Tooltip should describe it as RCCE: Risk communication, community engagement, and health and hygiene promotion)

**Comment by frozenhelium** [comment]
@lauripynnonen It's done and deployed to the production

**Comment by lauripynnonen** [comment]
I tested in staging and get this
![image](https://user-images.githubusercontent.com/8285694/81831680-f38eff00-953d-11ea-9187-50463760532b.png)

**Comment by frozenhelium** [comment]
@lauripynnonen It'll only work on production, the backed for the staging hasn't been deployed yet

**Comment by lauripynnonen** [comment]
Works in production!

**Comment by nanometrenat** [comment]
Closing ticket and moving to Done on the basis of Lauri's comment above
