### ISSUE TITLE
Remove "Additional graphics" text from additional tabs

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1232]
As there is now the possibility to add more tabs (#1009) to emergency pages and these additional tabs can be used for sharing not only graphics but also guidance etc. I think we should remove the text "Additional graphics" from the top of these extra tabs as it does not anymore add any extra value or information as to the content of the tabs. The text currently appears for all the additional tabs.

![image](https://user-images.githubusercontent.com/52411237/81908888-1f57c680-95ca-11ea-9e3e-58b5d02e3ba5.png)

This is a more of a cosmetic issue and should not be prioritised for now if it's not a quick fix.

**Comment by batpad** [comment]
@teklal this can be tested at https://ifrc-go-fix-1232-remove-additional-graphics.surge.sh/ - please let know if this works as intended from a business logic perspective, and we can ask @karitotp to go ahead and do a round of testing to see if there's any edge cases or bugs. Thank you! cc @kamicut

**Comment by teklal** [comment]
Thanks, looks good to me. Would be good to have tested by Karito :)

**Comment by karitotp** [comment]
ADDITIONAL GRAPHICS does not appear any more in the new tabs added when I add something in the snippet box, but when I left it creating only the tabs an not adding anything as content for that, the text "Additional graphics" is still shown. Is that the expected behavior?

**Comment by teklal** [comment]
Thanks for that catch @karitotp. I don't think the text "Additional graphics" should be there when the tab is empty (as indeed there are no additional graphics shown in there in those cases :D).

**Comment by GregoryHorvath** [comment]
@teklal @karitotp Is this also for the default "Additional Information" tab or just the other ones?
@batpad the PR: https://github.com/IFRCGo/go-frontend/pull/1279 removes the header for all of them. Wondering if we should keep that logic at all and remove the header code alltogether at this point?

**Comment by karitotp** [comment]
@GregoryHorvath @teklal, "Additional graphics" text is appearing in the default "Additional Information" tab too.

**Comment by GregoryHorvath** [comment]
> @GregoryHorvath @teklal, "Additional graphics" text is appearing in the default "Additional Information" tab too.

Sorry, my question was misleading. Do we want to remove from all of them or keep it for the "Additional Information" tab? This wasn't really clear for me.

**Comment by LukeCaley** [comment]
@GregoryHorvath please remove from all.  We may introduce more functionality to name and provide descriptions for individual snippets in future work on Emergency pages (Xref: https://github.com/IFRCGo/go-frontend/issues/1243)

**Comment by teklal** [comment]
This is now in prod and seems to be working so closing the ticket.
