### ISSUE TITLE
Signup workflow - Register page improvements

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1233]
Spin-off from #889 - this ticket describes changes to the Register page on GO, to make things simpler for users.  I don't think these changes have follow-on effects to further down the line but devs please shout if they do.   Any more "structural" changes will be tracked under #889 or logged separately.

Register page is https://go.ifrc.org/register

1. Organization section:

- [ ] IF National Society is selected THEN show a dropdown of National Societies
- [ ] IF ICRC is selected THEN change the heading from Organisation Name to Office Name

2. Text changes to wording on page

- [ ] Put new wording at the top of the page (under the "Register" heading) to make it clear that only RCRC movement can register (not a public platform for all responders).  At Sune's request. - text in location shown wireframe but **this** text please:  **Staff, members and volunteers of the Red Cross Red Crescent Movement (National Societies, the IFRC and the ICRC) are welcome to register for a user account on GO, to access information for the Membership.
Other responders and members of the public may browse the public areas of the site without registering for an account.**

- [ ] Hint text by the Username field so users are reminded that they must use username for all future logins (so please remember this!) - hint text below the field, as per wireframe: **This will be your username to log into the platform.**

~~Exact wording for both the above to be defined - perhaps suggested draft to be made by @mariam-yu (while also confirming that the above changes would be a good approach from the User point of view) then @LukeCaley and Sune can confirm wording then it can go straight to dev.~~

Noted that ideally the New User setup process in the back end would also be adapted to reflect the NS dropdown in 1 above - however given the amount of existing free-text data in the existing user table that may be complicated - so can look to log a separate ticket at later date to change Django Admin page if deemed necessary.

@mmusori @LukeCaley hope this reflects the conversation just now and the above should be a pretty quick win once wording is defined.

**Comment by mariam-yu** [comment]
@nanometrenat Updated the Register page slightly with some text suggestions: https://invis.io/JUXJC30G2W9#/414002964_0-1-1_Register

Not sure whether the RCRC needs to be explained (i.e. the second line). After this phase, we will do a second approach to include other improvements.

**Comment by nanometrenat** [comment]
Thanks @mariam-yu!  FYI actually volunteers and members without a RCRC email are also welcome to register (it's just they need additional verification steps).  So I've taken the liberty of updating the wording in the ticket description above.  @LukeCaley please edit further if further edits needed, as I'm moving to "to do" now :) cheers all

**Comment by GregoryHorvath** [comment]
@nanometrenat @mariam-yu https://github.com/IFRCGo/go-frontend/pull/1377 covers all 4 points with the wordings described above.

If you let me have a comment on the 4th point, the text _"This will be your username to log into the platform."_ feels a bit redundant to me under the textbox labelled _"Username"_. Would you consider having something like _"You will need to use this when logging into the platform."_ or something similar instead?

**Comment by mariam-yu** [comment]
@GregoryHorvath I think it's a good suggestion. We basically just need to make sure the user knows that they need to login with that and not with the email, correct?

**Comment by GregoryHorvath** [comment]
@mariam-yu I believe that’s the main idea yes.

I’d say we could improve the login as well with giving an error message or something if a user inputs an ‘@‘ char, but some users already have their email address saved as their username. So I have no idea there what we should do to improve clarity.

**Comment by mariam-yu** [comment]
@GregoryHorvath Sounds good. We should take a stab at reviewing those error messages together at some point. Ideally, we should combine the email and username fields, but not sure where that stands.

**Comment by GregoryHorvath** [comment]
@mmusori Sorry I've not checked you were assigned instead of @nanometrenat . Updates in the above comments.

**Comment by GregoryHorvath** [comment]
Merged this into `develop` so it's deployed to staging.
- If you select 'National Society' as the 'Organization Type' you get a dropdown of the societies as the 'Organization Name' field
- If you select 'ICRC', 'Organization Name' changes to 'Office Name' and the field is plain text (again)
- Added text at the top under 'Register' (from the ticket)
- Added text under the 'Username' field (from the ticket)

cc @karitotp

**Comment by karitotp** [comment]
Hi @GregoryHorvath,

> If you select 'National Society' as the 'Organization Type' you get a dropdown of the societies as the 'Organization Name' field

This is working good, but the list of societies in the dropdown has line breaks between some societies and the list is not in alphabetical order.

![Selection_013](https://user-images.githubusercontent.com/11504548/87441691-0020e980-c5b9-11ea-9493-881d56376eed.png)

Also there are fields like name and phone number that need validation, name is allowing numbers and phone number allow letters.

The other things look good.

**Comment by nanometrenat** [comment]
Thanks @karitotp - great to catch the issues with the dropdown!

I think that validation is separate though, and a potential new requirement.  E.g. I don't think phone number should be numeric only as e.g. one often needs + for the international doalling code.  So happy to leave as-is (without validation) for now.  Many cheers!

**Comment by GregoryHorvath** [comment]
@karitotp @nanometrenat Fix merged into `develop` so it should be on staging in ~5 mins max. Now those empty parts won't show up and it should be in alphabetical order.

**Comment by karitotp** [comment]
:+1: It looks good now @GregoryHorvath

**Comment by nanometrenat** [comment]
Thanks @GregoryHorvath just noticed that ICRC is showing in the National Society dropdown - is there a way to filter this out?  Thanks a lot

**Comment by GregoryHorvath** [comment]
@nanometrenat Sure, it's basically only gathering the `society_name` fields from the Countries, but 'ICRC' appears to be both on staging and production there. I'll filter that out.

**Comment by LukeCaley** [comment]
@nanometrenat would you mind checking to confirm this is working as per requirements? Ta muchly

**Comment by nanometrenat** [comment]
Looks good right now on surge test URL https://ifrc-go-release-v4-3-11.surge.sh/register:

> * If you select 'National Society' as the 'Organization Type' you get a dropdown of the societies as the 'Organization Name' field

This works correctly, thanks

> * If you select 'ICRC', 'Organization Name' changes to 'Office Name' and the field is plain text (again)

This works correctly, thanks

> * Added text at the top under 'Register' (from the ticket)

Correct, thanks - though @mariam-yu the wireframes text needs to be updated to match what is requested in this ticket.

> * Added text under the 'Username' field (from the ticket)

Correct as per the ticket text above, thank you - though alternatively I would be equally happy with Greg's suggested text of "You will need to use this when logging into the platform."  Will leave this to future phase though, not critical right now.

THANKS!

**Comment by mariam-yu** [comment]
@nanometrenat Thanks. Matched for now till we take another stab at this section: https://invis.io/SBYBJQPK643#/414002964_0-1-1_Register
