### ISSUE TITLE
Page body collapsing

### ISSUE THREAD

**Issue by danielfdsilva** [IFRCGo/go-frontend#124]
@ascalamogna Removing the flex property from the body (that change because of IE compatibility) causes it to collapse when it has no content. Not sure if is problematic, just wanted to flag it.

![image](https://user-images.githubusercontent.com/1090606/35434408-f249d25e-027e-11e8-915c-9b008da8c352.png)

**Comment by dereklieu** [comment]
Maybe a min-height on `body` would fix this? It does look a bit weird.

**Comment by guipizzini** [comment]
Has this been fixed?
