### ISSUE TITLE
Translation: Create a UI to list / change all the translatable strings

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1240]
# Translation Dashboard

can be accessed from `<GO base URL>/translation-dashboard`
eg: for staging: https://dsgoproxyapp.azurewebsites.net/translation-dashboard

## Introduction
Translation dashboard lists out all the static strings with their *id* and *dev value* in currently selected language. We can modify the strings showed in the platform in each language from here.

### Conflict resolution mode
This mode will show up when there is a conflict occurs. A conflict occurs when developers add, remove or update any string.![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_a26bd87f228dbb9a378e52781b37eeb0.png)
#### New by dev
This type of conflict occurs when developers add new string in the codebase. We can check the new value and **Save** it to resolve this.

#### Removed by dev
This type of conflict occurs when developers remove some string from the codebase. We can just click **Remove outdated keys** to resolve this conflict.

#### Updated by dev
This type of conflict occurs when developers update existing string in the codebase. We can see the value set by developer and current value side by side and correct the current value and click **Resolve** button to resolve it.

### Normal mode
This is the default mode when there isn't any conflict. There'll be only one tab in this mode. User can change **Value** field from here. Once saved, the changes will be reflected in the original site. The **Dev value** column shows the value set by the developers and can be used as reference. Following figure shows the dashboard in normal mode.
![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_b347c28d23f71c436f4fe5e83fba8518.png)

## Test cases
1. Check if only logged-in users can access the dashboard.
2. Check if all the strings are listed in the no-conflict mode. Users should be able to import and export xlsx documents.
3. Check if the conflict resolution tabs (Added, removed, updated) tabs appear in the conflict mode.
4. Check if the conflict resolution tabs (Added, removed, updated) tabs should appear in the conflict mode.
5. Check if the GET requests send by the web browser has Accept-Language header which is automatically injected to currently set language

@batpad @karitotp 
CC: @guipizzini

**Comment by LukeCaley** [comment]
@frozenhelium could you elaborate on what needs to be tested here cc @karitotp @guipizzini

**Comment by frozenhelium** [comment]
Testing notes for the [**Translation Dashboard**](https://dsgoproxyapp.azurewebsites.net/translation-dashboard)
1. Only logged-in users can access the dashboard
1. All strings should be listed in the no-conflict mode. Users should be able to import and export xlsx document.
1. String once modified from the dashboard should change the respective string in the platform in the selected language.
1. Conflict resolution tabs (Added, removed, updated)  should appear in the conflict mode. A conflict occurs when developers adds / removes / updates any string.
    1. For newly added strings users should be able to **Add new keys** to the server.
    1. For removed strings, users should be able to **Remove outdated keys** from the server.
    1. For updated strings users can see the updated dev string and the current value in the server and **Resolve** them.

**Comment by guipizzini** [comment]
@frozenhelium here my feedback after testing:

1. Correct, logged in users can access the dashboard. This is the correct logic. We should ensure that only certain user roles (super admin for example) have access to the dashboard.
2. Import I did not test it. If I import strings, what is the overwrite logic? I want to ask a few questions first - before proceed with this testing.
3. Export works fine. Question, is it normal that it exports only the "dev strings" without the translated languages with its related content?
4. Conflict resolution tabs appear once logged in, but then when entering the language tabs with the strings - there is no way to go back to the conflict resolution tab. Is that normal behaviour?
5. All elements on the conflict resolution tab, work fine - as per instructions above.

Overall this looks good and works fine. Is it possible to ensure that the styling of the dashboard is consistent with the layout of GO?

As well, when opening staging as you know we get this "loading" icon and page saying "Initialising GO" I am not sure what was the result of that discussion @batpad ?

Thanks!

**Comment by nanometrenat** [comment]
> As well, when opening staging as you know we get this "loading" icon and page saying "Initialising GO" I am not sure what was the result of that discussion @batpad ?

Hi @guipizzini FYI the initialising screen conversation is under https://github.com/IFRCGo/go-frontend/issues/1386 and its spinoff https://github.com/IFRCGo/go-frontend/issues/1517

**Comment by nanometrenat** [comment]
Re translation changes - fully agree with @guipizzini above, the ability to edit translations definitely needs to be available only to superusers (unless a separate user group is created that is explicitly assigned to individual users).  View not a problem for everyone to see though.

One other thing that needs to be checked is where the audit trail sits for each of the different possible ways to add/edit translations.  Critical to be able to see who has changed what and when.  Presumably should feed into the existing back end audit trail processes but an alternative way could also be used as long as it's possible somehow :)

**Comment by batpad** [comment]
@karitotp could you look at the updated issue with the testing notes and let us figure out a plan to test this thoroughly? Thanks!

**Comment by karitotp** [comment]
Hi @batpad @frozenhelium, Here what I got from my testing, for the test for other functionalities;

- Login is working fine.
- Export works fine, and as Guido mentioned, it only contains the ID nad the Dev string without the translations.
- When I logged in, the showed dashboard is the normal mode without the conflict tabs.
- When I modified or deleted the strings in "value" column, it update correctly for the selected language, but if I change to the other language, the updated is not reflected. Does it correct?
- I could not get the conflict mode, when I do any changes for some a moment, while it is saving, it appear the tabs of conflict with 0 conflicts but then it disappears.

![Screenshot from 2020-09-04 09-27-58](https://user-images.githubusercontent.com/11504548/92250429-16e50d80-ee91-11ea-90d5-4e461f82bbb2.png)

- In some cases, the changes save take too much time. This occur when I change more than one string, but also repeat when I change just one. 

For the other functionalities, could you please provide more details, I do not sure how should I do it.

**Comment by frozenhelium** [comment]
@karitotp 
#4 - Yes, any changes to a specific language will not affect any other language
#5 - Conflict mode occurs only when developer adds/changes/removes string in the code base. I can setup the conflict in the staging server if required.
#6 - I'll have to check if there's anything causing that issue

I think the only thing remaining to test is the conflict resolution mode and the export. Let me know if you want me to create some conflict in the staging server

**Comment by karitotp** [comment]
> I think the only thing remaining to test is the conflict resolution mode and the export. Let me know if you want me to create some conflict in the staging server

@frozenhelium,that would be great. Thank you!

**Comment by guipizzini** [comment]
Testing completed

**Comment by szabozoltan69** [comment]
We should investigate the "Resolve" functionality. By my understanding it should move the developers changes to English translations – but it does not do this.
(If I am wrong about it, we need another button for that, to avoid the time-consuming XLSX export/change/import steps.)
