### ISSUE TITLE
Translation: Add support for bulk import / export for all translatable strings

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1241]
This feature is available through the **Translation dashboard**. More details on the dashboard at https://github.com/IFRCGo/go-frontend/issues/1240

The import and export is supported for file type `xlsx`. The import format should be similar to the export. The import will set all the keys available in the sheed to the value from the column with header of currently selected language key.

For example: If french language is selected the import will select value from the `fr` column in the sheet

**Comment by guipizzini** [comment]
Tested completed with success.
