### ISSUE TITLE
Emergency page UX/UI

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1243]
This is a ticket to implement the new UI and functionalities for the the Emergency pages. This covers Emergency pages for all disasters and the specific Emergency page for Epidemics. 
The wire frames can be found below.
Epidemics: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417134563
Emergency page will be incorporated into the above wireframe. 
The update UI design for the Field Report : Field report page: https://invis.io/49WZCQ0QVTY#/412009430_4-5-3_GO_FieldReport-Epi_Page

Full design specs will follow  below:

**Comment by mariam-yu** [comment]
@mmusori Emergency page wires updated (the first 2 tabs): https://projects.invisionapp.com/share/3VXBUL0F6DR#/screens/361592718_4-2-1_GO_Specific-Emergency Same exact information, except key figures are different from Epi.

**Comment by mariam-yu** [comment]
Wireframes updated with the latest feedback:
Big emergency (example: Ebola in DRC that also covers the Epi example): https://invis.io/59WZFUYEFTM
Small emergency (example: Libya Population Movement): https://invis.io/3VXBUL0F6DR#/361592718_4-2-1_GO_Specific-Emergency

**Comment by batpad** [comment]
These are looking great! Re-organizing the information into separate tabs looks good to me. And re-structuring the placement of the map, etc. should all be fine. cc @imohkay to take a look at wireframes and point out anything that needs clarification from the design implementation.

Couple of questions:

 - Can we clarify exactly how the data for the Key Figures as well as the overview are pulled in from field reports. We currently follow the logic of taking values from the last submitted field report. Is this intentional / what we should continue with, or do we need to follow a different logic? I would really like to take some time to think through this logic and how values are aggregated here and have that clearly specced out - this maybe a question more for @mmusori .

 - We now allow users to add a total of 3 additional tabs (including the "additional data" tab), allowing users to give tabs their own titles and arbitrary content. Just confirming that these would be fine to add to the right of the "Additional Data" tab? I can see that in this case, the tabs structure for large emergencies with many tabs could get crowded - cc @imohkay if you have thoughts here.

Otherwise looks good. There's some things on the Rapid Response section that may not be implemented until we re-do the Rapid Response piece with the new Molnix integration (please clarify that this understanding is correct @LukeCaley ).

**Comment by imohkay** [comment]
Regarding the tabs, we can add them and see how they look stacked..
Another option may be to experiment with vertical tabs in a left column if there are too many of them... 
Or a tab carousel, which may not be the best idea.

**Comment by imohkay** [comment]
@mariam-yu Hey Mariam, just wanted to check if the Specific Emergency page on Zeplin is good to implement? Or does anything need to be clarified?

**Comment by mariam-yu** [comment]
@imohkay So, we have the shorter emergency example there and are currently adding soon the longer one (the difference is basically the number of tabs and some extra modules). Shorter emergency will be in case there is not enough data while longer for big emergencies when there is a lot of data. Hope this makes sense.

Also, about your earlier questions: The grey extended background is more of a visual element to make the page look more balanced rather attached to specific elements. So, I think we should do them page by page (and we are still updating all of the pages ourselves). The chart styling is standardized, and Invision/Zeplin should match now. Please let me know if there is anything else. I will do another audit today unless you'd like me to wait.

**Comment by imohkay** [comment]
@mariam-yu sounds good, I'll wait for the longer example with more tabs :)
Regarding the extended background, that sounds good and you can go ahead and do an audit :)
I took a look at the chart styling and it's all standardised now, and I think matches what's on the site currently.

**Comment by mariam-yu** [comment]
@imohkay Really good job. It's coming together nicely! A few things I noticed:

1 - Thanks for making Search bigger. Just a note though, this wasn't approved yet from the team. @mmusori Did you have any thoughts on this or we wait for Luke?
2 - In the table under the map (across), can you make Requested Amount left aligned.
3 - Also, there is a bit of a funky thing happening with the map table on the regions (e.g. on Africa). When you click on page numbers, it jumps below the table and on page 2 Funding title wraps (the sorting icon). Can we have it not wrap?
4 - Regions - recent emergencies table - Left aligned requested amount and #affected
5 - Emergency map - can you make legend styling consistent with home? I know we are not touching the map now, just to make consistent whatever styling we implement now.
6 - Create a Report dropdown - the text is a bit lighter in the design (Poppins-Regular).
7 - You are probably still working on Specific Emergency pages. Just a comment on the header: the grey should end after key numbers and the country links should be closer to the title. Also, in Natalie's Covid emergency the key number is missing text. Is that manual? When clicked on Aland-Bio-Test3, the site breaks.
8 - Not many comments for country pages besides what's above, as I think you are still working on it. We are also working now hard to finish up all the tabs for you to implement. Lastly, I still owe you the field report dropdown solution from Emergency pages. 

Thank you!

**Comment by mariam-yu** [comment]
@imohkay One more thing, we updated the top nav dropdown style (for languages) in Zeplin. It's on the same section as the dropdown for Create a Field Report. Let us know if any questions.

**Comment by imohkay** [comment]
Thanks @mariam-yu 
I've dropped the feedback into a new ticket (#1448) and will work on the changes soon.

**Comment by mariam-yu** [comment]
@batpad @imohkay We finished the UI for Specific emergencies:
Small emergency with minimal available data: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/426664202
Larger emergency with all the available data and tabs: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417134563

All updated on Zeplin. Please let us know if any questions. Thanks!

**Comment by imohkay** [comment]
@karitotp Hey, so you can take a look at the designs in the Zeplin link here for Specific Emergency: https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5f194858aed4e06c77925cc4

There are a few pages with designs for each tab.

Issue: I am unable to see most of the tabs on the current site with data.

Request: I wanted to know if you could point me to a specific emergency that has all these tabs with data (just like how it is in Zeplin) or whether you could create an emergency on staging with all the relevant information in the tabs? That way, it would be easy for me to implement the new styles. Thanks @karitotp  :)

**Comment by nanometrenat** [comment]
Hi I am not sure where feedback for the Emergency page should go right now - but just to note that the "specific emergency" page wireframes now have 5 tabs and that's even without the additional tabs that users can add and customise for the emergency (e.g. https://go.ifrc.org/emergencies/3972#details and https://go.ifrc.org/emergencies/4379#details both have customised tabs.  Need to make sure that the custom tabs are still available and that there is room for them!  @mariam-yu

**Comment by mariam-yu** [comment]
Thanks @nanometrenat I'll tag @LukeCaley and @mmusori for this. I think there was a chat to reduce the number of custom tabs, but I'm not really sure.

**Comment by nanometrenat** [comment]
@mmusori conversation just now agreed to move this work to 4.4 (so on hold for now)

**Comment by tovari** [comment]
Also related to https://github.com/IFRCGo/go-frontend/issues/1082

**Comment by batpad** [comment]
@imohkay - re-tagging you here - we are awaiting on the final updated designs for the Emergency Pages, and then we would need to go through and discuss implementation: how much is CSS, what needs new backend implementations, etc.

@mariam-yu @mmusori - could you please update here with the latest designs / wireframes, even if they are not fully finalized? It will be great for @imohkay and I to start going through and speccing out the work here.

@kamicut tagging you here as well as it will probably be good to get your support on any functionality changes to support the new designs once the designs are finalized sometime next week.

**Comment by mariam-yu** [comment]
@mmusori Please let me know if there were other learnings/changes. Happy to update the wires accordingly. Thanks!

**Comment by mariam-yu** [comment]
@LukeCaley We updated the emergency pages based on your comments:
https://projects.invisionapp.com/share/WNZDV0QDZA2#/screens/417134563 There were a few points that needed clarification. Here they are:
- Contacts module UI - we had updated this sometime ago but it hasn't gotten the full UI upgrade yet on the live version. Thoughts?
_Movement Footprint (3W, formerly Response Activities)_
- Should we rename other 3Ws to this as well, such as on regional pages and country pages?
- Here, in the bottom graph (bilateral support), the last suggestion by Lauri was to use tags (for the right side), we just hadn't updated it on the UI before. Now it's updated. Let us know if ok.
- You mentioned "Movement Picture graphic" on this section, not sure what that is.
- For "Programmatic Figures by Area of Focus", should we remove this table from our "approved" UI prototype before it's ready? Also, not sure what "5 category Strategic Priorities structure" is.

Thanks! (CC @mmusori)

**Comment by imohkay** [comment]
@karitotp Hey, would it be possible for you to create a new emergency on staging with all data filled? That way, it will be easy for me to incorporate the new design changes. Let me know if that's possible.

**Comment by karitotp** [comment]
Hi @imohkay, sure, will create one.

**Comment by karitotp** [comment]
@imohkay, I created this emergency https://dsgoproxyapp.azurewebsites.net/emergencies/4120#details
Let me know if that works for what you are looking for.

**Comment by LukeCaley** [comment]
- Contacts module UI - we had updated this sometime ago but it hasn't gotten the full UI upgrade yet on the live version. Thoughts? looks good.  We should only have 3 categories
- Movement Footprint (3W, formerly Response Activities) - revert to 3w 
- Should we rename other 3Ws to this as well, such as on regional pages and country pages? - Revert to 3w (to avoid political implications of Movement Footprint) - we can look at rebranding the 3w if makes sense when picking up 3w enhancements in 2021
- Here, in the bottom graph (bilateral support), the last suggestion by Lauri was to use tags (for the right side), we just hadn't updated it on the UI before. Now it's updated. Let us know if ok. - We would like both Adm1 (where) and the option to toggle between Adm1 and Tags.  Would it be possible to do both?  If not, then the preference is for where / Admin1
- You mentioned "Movement Picture graphic" on this section, not sure what that is.  This should be the option to embed a snippet - probably a static infographic.  See https://go.ifrc.org/emergencies/4889#details Hurricane Eta situational overview for the kind of product.  @JonathanGarro can you share an example from the Americas Pop Movement with @mariam-yu ?
- For "Programmatic Figures by Area of Focus", should we remove this table from our "approved" UI prototype before it's ready? Also, not sure what "5 category Strategic Priorities structure" is.  @mmusori and I agreed to remove from current UI until clarity on how this data will be captured and presented

**Comment by LukeCaley** [comment]
@mariam-yu more specific comments in Invision.

**Comment by JonathanGarro** [comment]
@mariam-yu per Luke's reference above, I'm sharing my latest draft of the Movement Picture from the Americas Population Movement. Let me know if you have any questions! If there is an idea around embedding movement picture in a more dynamic way (e.g. an interactive or otherwise native functionality), I'd be happy to explore. We're currently working on converting the Operational Timeline (another SMCC product) to SVG for better embedding and we could explore a similar solution with this.

I think the development of the 3W feature within GO could possible serve as a linkage with the Movement Picture, as you'll see that is a main feature of this version of it.

[Venezuela Population Movement - v0.22.pdf](https://github.com/IFRCGo/go-frontend/files/5548999/Venezuela.Population.Movement.-.v0.22.pdf)

**Comment by imohkay** [comment]
@karitotp This works:) Thank you

**Comment by mariam-yu** [comment]
@JonathanGarro Thanks for the file. So, as of now, as I understand this could be just an embedded iFrame. For now, we just placed a screenshot of it within the emergency page (doesn't really fit with Ebola, but for now should be ok).

@LukeCaley We updated the prototype with your comments: https://projects.invisionapp.com/share/WNZDV0QDZA2#/screens/417134563

- Contacts module updated with IFRC/NS, as well as updated in Zeplin and the other GitHub thread.
- 3W naming - sounds good
- Bilateral support: the toggle actually would be a technical question to know how we could do this on the diagram. For now, we replaced with Admin 1 (Provinces) and we can determine with devs whether a toggle between Adm1 and Tags is possible.
- Place the "Movement Picture" graphic here. Doesn't fit with Ebola, but should be ok for now. I know that if we place the iFrame snippets in random order on the page (meaning it can be at any place after any module) @batpad may have some comments about that. So, it's best to discuss the implications.
- "Programmatic Figures" removed from the UI prototype but stays in the wireframes for us not to forget.

**Comment by imohkay** [comment]
@batpad Please checkout feature/1243-emergency-ui
The following needs to be done:
- Make Emergency Overview section fetch real content
- Making the tooltips on the deployed personnel graphic get real content, along with the correct dates
- Appeal Documents need to become a table with appropriate headings etc.

Thank you:)

**Comment by batpad** [comment]
Emergency page re-organization and redesign has been pushed to staging, with the major exception of the Deployed Personnel table not fully working.

What is expected to work:

 - Layout as per new designs: Overview box, figures to the right of the map, redesigned contacts, re-organized tabs
 - Reports / Documents tab to contain appeal documents and field reports
 - Appeal documents now appears as a table
 - Rapid Response tab contains Surge Alerts and Deployments
 - Now, tabs will not show if there is no data for them - eg. if there are no alerts or deployments, the Rapid Response tab will not show. If there are no documents, the Reports / Documents tab will not show, and if there are no snippets, the Additional Information tab will not show at all.
 - Situation Overview no longer shows "Show More" unless content is very large (over 4096 chars).

There is some of the restructuring of filters that we would tackle separately with work on filters across the site.

@karitotp - could you do a test of all of the above - you will need to test a few different types of emergencies - with data, without data, etc. Please let me know if there are any questions on expected functionality.

@mariam-yu would be great if you could give any design feedback - we may want to tweak things a little bit when there is no map, for eg.

@tovari this is ready for testing - the Personnel Deployments table is not finished, but based on discussion with @anamariaescobar, we may need to hold off on some of the surge related changes, so will finalize that in a bit - the rest of the emergency page should be fine to test - though maybe better after @karitotp has done an initial round of testing.

**Comment by tovari** [comment]
Thanks @batpad for the update.
I get a grey screen when I try to open an emergency. I cleared cache and tried in FF and Chrome.

**Comment by batpad** [comment]
@tovari could you tell me which emergency you are seeing this for? I am unable to reproduce so far, but it is very possible that some types of emergencies currently fail as there are a lot of different cases.

**Comment by tovari** [comment]
@batpad, it seems, it happens (with any of them)  only, when I'm not logged in.

**Comment by karitotp** [comment]
@batpad, all things are working as expected. Some things that I found are:

- In Arabic language, in the REPORTS/DOCUMENTS tab, the number of Field reports is not shown as in the other languages.
![Selection_003](https://user-images.githubusercontent.com/11504548/101657136-8b3fc780-3a11-11eb-904c-79b692ee1331.png)

- > Now, tabs will not show if there is no data for them - eg. if there are no alerts or deployments, the Rapid Response tab will not show. If there are no documents, the Reports / Documents tab will not show, and if there are no snippets, the Additional Information tab will not show at all.

This works correctly for these tabs. But it should apply also for the new tabs that are added even if there are no snippets? I added a new one with no snippets and it is displaying with the message "No data to display." 
![Screenshot from 2020-12-09 11-41-17](https://user-images.githubusercontent.com/11504548/101658896-782df700-3a13-11eb-9d58-112a7c3e63a5.png)

**Comment by batpad** [comment]
> @batpad, it seems, it happens (with any of them) only, when I'm not logged in.

@tovari thank you so much for that catch - this should now be fixed on staging.

> This works correctly for these tabs. But it should apply also for the new tabs that are added even if there are no snippets? I added a new one with no snippets and it is displaying with the message "No data to display."

Yes, if you add a custom tab title in the backend, the tab will show regardless if there are snippets inside. If the user doesn't want the tab to show, they should remove the custom tab title and it will go away. We can perhaps look at this closer in the future, but I believe right now this is fine as the admin user can control it - but perhaps we should make users aware. @tovari - let me know if you wish to discuss the details here - I'm putting this down to "expected behaviour". That is a good catch, though, @karitotp - thank you :+1: 

> In Arabic language, in the REPORTS/DOCUMENTS tab, the number of Field reports is not shown as in the other languages.
Selection_003

@kamicut could I get your hand here to look into this one? I think we had this bug with arabic earlier as well on the field reports table. Am hoping with your understanding of the language, it maybe easier to distinguish what's going on here.

**Comment by batpad** [comment]
> Apart of the emergency page in which there is not a map neither the emergency overview numbers https://dsgoproxyapp.azurewebsites.net/emergencies/4100#details 

Yea, for these kinds of emergencies, we just don't have a lot of data. @mariam-yu could you look at this case and advise if we should display things differently?

> and the emergency page where is only show the emergency overview numbers without the map https://dsgoproxyapp.azurewebsites.net/emergencies/4124#details.

@imohkay - I thought we had fixed this case to center the box when there is no map, but I see now it is displaying on the right with a big empty space where the map would be. Can we look at this case and fix? Also, @mariam-yu - this is a case where it's hard to get things looking very elegant, if you have any suggestions, let us know - currently our idea is to just make sure the box with the figures is centered on the page if there is no map.

Thanks for these catches @karitotp !

**Comment by batpad** [comment]
> and the emergency page where is only show the emergency overview numbers without the map https://dsgoproxyapp.azurewebsites.net/emergencies/4124#details.

@karitotp this should now be styled better with the box appearing centered. Could you check? Thank you!

**Comment by karitotp** [comment]
> @karitotp this should now be styled better with the box appearing centered. Could you check? Thank you!

@batpad, this now is centered :+1: 
But at the beginning while the page is loading, for some seconds the map apparently load and the box is located on the right side

**Comment by batpad** [comment]
> But at the beginning while the page is loading, for some seconds the map apparently load and the box is located on the right side

Thanks for the catch @karitotp - I will take a look at this.

**Comment by tovari** [comment]
I'm writing the UAT test cases. I have noticed already a few issues:
https://ifrcorg.sharepoint.com/:x:/s/GOIVfordeveloperteam/ERfcR2RDUMJOiGg4cRBrGtUB2LRyXW0IrBuUS8MsYwg5Nw?e=IkOgoa

On https://dsgoproxyapp.azurewebsites.net/emergencies, the new map look is not applied yet, the headers of lists are missing, and the list export button as well from the last 30 days FRs.

**Comment by batpad** [comment]
@tovari we have only made changes on individual emergency pages and not on the Emergencies page.

I think it makes sense to make the map styling consistent, but we didn't really have any other changes on the emergencies page in scope, only on the individual emergency page. Let me know if that makes sense.

@geohacker - could we look at the `emergencies-map` on this page: https://dsgoproxyapp.azurewebsites.net/emergencies and bring it in line with the new styles?

**Comment by batpad** [comment]
@tovari I do see that the table headers seem to have disappeared on the Emergencies page - @imohkay can you take a look at this? Compare tables below the map on Emergencies page between https://dsgoproxyapp.azurewebsites.net/emergencies and https://go.ifrc.org/emergencies/ ? Is this a regression due to changes to tables made elsewhere?

**Comment by batpad** [comment]
@tovari thanks for the catch around the table headings - that does seem like a regression and we are looking into it.

**Comment by batpad** [comment]
@imohkay table headings missing on the field report table as well: https://dsgoproxyapp.azurewebsites.net/emergencies

**Comment by batpad** [comment]
@tovari - table headings on the Emergencies page and across the site should now be fixed.

**Comment by mariam-yu** [comment]
@batpad Here is the guideline for Key Figures without a map: https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5fd39a8487eefa875c35c576

(CC @imohkay )
And some audit items, thought was difficult to pinpoint all the various modules:

- Tabs: the line under selected tabs should be the length of the word.
- Export button should have the export icons as well.
- Text should say Key Figures not Emergency Overview.
- Would the Key Figures have sources?
- Can we have the Key figures box be the size of the text not the map (as a lot of white space). Ideally, would be best to make the map height smaller and have the Key Figures fit map height (see Zeplin) - whatever is the easiest.
- Contacts: the separator lines have all the same length.
- Contacts: could we improve on column spacing (see Zeplin)?
- Contacts: for the organizations (e.g. IFRC, NS), could we add _letter spacing_ into the words (see Zeplin).
- Reports/Documents > Response Documents: Search doesn’t seem to work.

**Comment by karitotp** [comment]
> But at the beginning while the page is loading, for some seconds the map apparently load and the box is located on the right side

The delay to center the box persists.

**Comment by batpad** [comment]
@imohkay - can you look at the list of things from @mariam-yu above? I'll take a look at the Search inside Response Documents.

**Comment by mmusori** [comment]
GO page | Subpage/Tab | Test criteria | Result
-- | -- | -- | --
Emergencies(Specific   Emergency) | Emergency   Details- Emergency overview | All fields   appearing. Data consistent with Field report data. | Passed
Emergencies(Specific   Emergency) | Emergency   Details- Contacts | Contacts   split between NS and IFRC | Passed
Emergencies(Specific   Emergency) | Emergency   Details- Situation | Display text   from field report | Passed
Emergencies(Specific   Emergency) | Emergency   Details- Affected Regions | Map with   Affected Region | Passed
Emergencies(Specific   Emergency) | Emergency   Details- Key figures | Key figures   next to the Map as in wireframe | Passed
Emergencies(Specific   Emergency) | Emergency   Details- Key figures | Key figures   when map is not available | Passed
Emergencies(Specific   Emergency) | Reports/Documents | Field Report   attached | Passed
Emergencies(Specific   Emergency) | Tabs | Add new tabs   in the backend | Passed
Emergencies(Specific   Emergency) | 3W | Link to   specific Emergency when Bilateral | Failed
Emergencies(Specific   Emergency) | 3W | Link to   specific Emergency when Multilateral or Domestic | Passed
Emergencies(Specific   Emergency) | 3W | Displaying   information on Specific Emergency page | Failed
