### ISSUE TITLE
Covid related radio button 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1247]
Change Covid-19 related slider to radio buttons (YES, NO) and make it mandatory to select. 
 

![image](https://user-images.githubusercontent.com/7780809/82046084-8780d800-96b0-11ea-83cd-5b151e571183.png)

**Comment by mariam-yu** [comment]
@batpad Suggestion for the UI https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/418111554 (same password)

And the wireframes https://invis.io/Q7XBW10GTM2#/418048033_8-1_GO_FieldReports_1-1

**Comment by nanometrenat** [comment]
Moving to Done as this was released to Prod this morning - @mmusori to close when happy!

**Comment by batpad** [comment]
@mmusori please close when happy :-)
