### ISSUE TITLE
Translation: Adjust styling to support rtl languages

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1253]
Adjust styling to support RTL languages eg: Arabic

**Comment by nanometrenat** [comment]
@frozenhelium @batpad was this already done under #1364 and other recent work?  Or is this separate?

**Comment by batpad** [comment]
Leaving this ticket as `In Progress` until we have an RTL language available to test.

xref - a lot of work for this was done under #1382 and #1364
