### ISSUE TITLE
Structure of key pages to be updated.

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#126]
@ascalamogna as agreed, let's structure all the views in the following way:

1. Key Figures
2. Map
3. Bar / Line Charts
4. Table Structure.

This is the structure we have at present, on the home page.

We would need to have the "Emergencies" and the "Deployments" overview be the same.

Thanks a million!

**Comment by LukeCaley** [comment]
Key figures source requires a more specific date.  This can be encouraged through the django back-end by having an example date structure (as of___) or there could be an additional field required which specifies date of source.
