### ISSUE TITLE
Automate surge deployment

### ISSUE THREAD

**Issue by kamicut** [IFRCGo/go-frontend#1273]
Currently when deploying a preview for a new PR, we have to manually build the site locally using `yarn build-staging` and then deploy the local build using `yarn deploy-surge`. Ideally, we would want to deploy previews automatically when a PR is created, and have the reference to that preview website linked to the PR.

We should be able to do this on the Github interface using the [Github Actions API](https://help.github.com/en/actions). The benefit here is that it would also allow for other automatic actions such as teardown when the PR is merged.

**Comment by frozenhelium** [comment]
This might be a bit tricky in the situation where we want to use different API server. Currently manual build allows us to do so using the environment variables. Auto teardown would be great after the merge in the develop.

**Comment by batpad** [comment]
@frozenhelium thanks for pointing that out :-) . I think that's a valid issue that seems non-trivial to solve. Since this does not seem super urgent to do, going to move to backlog.
