### ISSUE TITLE
[PROD] Field report: blank screen/400 error when choosing certain "countries" on dropdown

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1276]
## Issue
This is a known issue (https://github.com/IFRCGo/go-frontend/issues/936#issuecomment-585106738) but creating a ticket so that this particular one is also captured separately as I just ran into it again.

I get a blank screen and a 400 error on the first page of a field report when choosing e.g. Aland Island or New Caledonia as the country from the dropdown. These countries shouldn't even show up in the dropdowns and this will hopefully be addressed once we get to working on geospatial data handling (#938). 

![image](https://user-images.githubusercontent.com/52411237/82458673-45440600-9ab7-11ea-95f2-57cf2273d5c7.png)

Flagging this on a ticket as well because with more and more users now submitting field reports there may be accidental clicks on these countries when looking for the right one in the dropdown resulting in these errors.

xref #936 #938

**Comment by batpad** [comment]
Thanks @teklal this is useful to capture separately, and I think should be fixed first, potentially separate from the larger issue of spatial data handling since it's an obvious bug.

**Comment by batpad** [comment]
Below is a list of countries that exists in the drop-down on the field report page, but do not exists as Countries in the GO API:

### Countries Not Found in Prod:

 - British Indian Overseas Territories
 - Montserrat
 - Virgin Islands, British
 - Turks and Caicos Islands
 - Cayman Islands
 - Netherlands Antilles
 - French Guiana
 - Guadeloupe
 - Martinique
 - American Samoa
 - Baker Island
 - Christmas Island, Territory of
 - Cocos Islands, Territory of
 - Falkland Islands (Malvinas)
 - Faroe Islands
 - French Polynesia
 - French Southern and Antarctic Lands
 - Greenland
 - Guam
 - Heard I. & McDonald Is.
 - Howland Island
 - Jarvis Island
 - Johnston Atoll
 - Mayotte
 - New Caledonia
 - Norkolk Island
 - Northern Mariana Island
 - Reunion
 - South Georgia and the South Sandwich Is.
 - St. Pierre et Miquelon
 - Svalbard and Jan Mayen
 - Tokelau
 - Virgin Islands, US
 - Wake Island
 - Wallis and Futuna
 - Guernesey
 - Jersey
 - Isle of Man
 - Aland Island
 - Bouvet Island
 - St. Martin (French part)
 - Zone Central and West Africa
 - Zone Southern Africa

### Countries with Differing Labels on Frontend and Backend:

Clientside: **Lao PDR**, Prod: **Lao People's Democratic Republic**
Clientside: **eSwatini**, Prod: **Eswatini**
Clientside: **Congo**, Prod: **Congo, Rep.**
Clientside: **Democratic Republic of the Congo**, Prod: **Congo, Dem. Rep.**
Clientside: **Micronesia, Federates States of**, Prod: **Micronesia, Federated States of**
Clientside: **Holy See**, Prod: **Holy See (Vatican City State)**
Clientside: **Zone Americas**, Prod: **Americas Region**
Clientside: **Zone Asia-Pacific**, Prod: **Asia-Pacific Region**
Clientside: **Zone Eastern Africa**, Prod: **Africa Region**
Clientside: **Zone Europe**, Prod: **Europe Region**
Clientside: **Zone MENA**, Prod: **MENA Region**
Clientside: **Zone GLOBAL**, Prod: **IFRC**
Clientside: **South Sudan**, Prod: **South Sudan, Rep. Of**

cc @geohacker @teklal  - I'm guessing we will resolve these with geospatial data management in the backend, but wondering if it makes sense to remove the countries that don't exist in the backend from the frontend right now?

**Comment by nanometrenat** [comment]
Noting that the same list of countries also appears on new user Register page (as well as FRs) so it will be great when aligned to the correct list.  CHEERS.

**Comment by nanometrenat** [comment]
Thanks @batpad for the reconciliation.  At risk of pre-empting Johnny's arrival to the team, my thoughts are that the list of "missing" countries above is correct - even if these locations are added to the countries table via the geospatial work they should not appear on the Field Report dropdown as do not have National Societies (and also are not IFRC regions/global).  Re the countries with differing labels, the Prod (back end) versions are correct.  Although not sure whether Holy See should appear in the list!

**Comment by geohacker** [comment]
This should be resolved when API and front-end geo PRs are merged. This should already be fixed in staging https://github.com/IFRCGo/go-frontend/pull/1514

**Comment by LukeCaley** [comment]
@karitotp would you be so kind as to test this in staging?

**Comment by batpad** [comment]
To clarify, this is testable on the Surge URL for the countries API work, and not yet on staging.

**Comment by geohacker** [comment]
The surge URL is https://ifrc-go-feature-geo-apis.surge.sh/

**Comment by karitotp** [comment]
I tested selecting different countries of the list in this ticket and I did not get any blank screen, I created a FR with South Georgia and the South Sandwich country  and all looks good to me https://ifrc-go-feature-geo-apis.surge.sh/reports/9643

**Comment by nanometrenat** [comment]
Thanks @karitotp it is great that there are no errors.

To be honest the country list is still incorrect though - these countries (South Georgia, South Sandwich Islands, New Caledonia etc.) shouldn't even be appearing as options in the Field Report dropdown.  Yes they are appearing in Production currently, but that shouldn't be the case ideally, as per comment above.

Note also that as well as the countries that are incorrectly in both staging and Production as per the original ticket here, since the changes we also have some _additional_ entries in Staging that are not in Production and _definitely_ shouldn't be appearing, e.g.

- ICRC
- Macao
- Macedonia, FYR (this should be North Macedonia - country name has changed in last few years)
(possibly others, I only glanced quickly)

Will leave to @jhenshall to confirm the business rules that should be applied as to which countries should appear in FR dropdown.  It's important that we don't end up with "orphan" Field Reports that aren't associated with a "real" IFRC country - at the moment in Prod it's handled by not being able to submit if not a valid IFRC country...

**Comment by jhenshall** [comment]
To minimise risk, we're not making any changes to the existing country data during the migration of geo data to the backend. However, all countries will be given an `independent` attribute of `true` or `false`. Proposing that the country drop-down lists filter out all countries where `independent` = `false`, which looks like it would cover all of the countries listed above.
