### ISSUE TITLE
3W: COVID-19 Sankey Diagram 

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1284]
A separate (hidden) page that has a Sankey Diagram that shows all Go 3w activities that have the COVID-19 tag. 

The page is to be shown as an iframe on the [COVID-19 Global Emergency page's Actions-tab.](https://go.ifrc.org/emergencies/3972#actions)

The Sankey works the same way as the one on the Regional page, displaying Who does What, Where

**Comment by lauripynnonen** [comment]
@frozenhelium: Title and subtitle:
   **Movement COVID-19 Response - National Society Who does What Where (3w)** 
> The Sankey chart below depicts the flow of National Society support.  On the left are the National Societies providing the support, in the middle are the sectors and on the right are the countries where the projects are taking place.  The thickness of the lines represents the number of projects.

**Comment by lauripynnonen** [comment]
@frozenhelium I tested the iFrame [here](https://dsgoproxyapp.azurewebsites.net/emergencies/4013#sankey), and the last filter (where) does not seem to work. It does not seem to work in the regional view, either (however it does work in production)

**Comment by frozenhelium** [comment]
@lauripynnonen it's working now, cheers!

**Comment by LukeCaley** [comment]
@lauripynnonen @teklal  can you confirm this is tested and ready to GO?

**Comment by teklal** [comment]
Good to go from my side. I did some testing after the filtering issue had been fixed and all seemed to be working but I believe @lauripynnonen tested more thoroughly?

**Comment by lauripynnonen** [comment]
Looks fine! To production and beyond!

**Comment by nanometrenat** [comment]
Prod URL is https://go.ifrc.org/covid19-3w-sankey
