### ISSUE TITLE
Stats are running over the line on region page

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#129]
This is happening on the Africa page:

![screen shot 2018-01-29 at 11 53 40 am](https://user-images.githubusercontent.com/1590802/35522800-4b223a4c-04eb-11e8-8677-78ec9c727a9c.png)

cc @ascalamogna

**Comment by guipizzini** [comment]
has this been fixed @ascalamogna ?

**Comment by guipizzini** [comment]
can we close this one @dereklieu ?
