### ISSUE TITLE
3w: "Add" 3w activity -button to 3w regional page

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1296]
On the country 3w page there is an add -button next to the export button. We should add the same button next to the export button on the regional 3w view.

**Comment by lauripynnonen** [comment]
Seems to work. @frozenhelium could the text of the button be just "Add" like on the country page?

**Comment by frozenhelium** [comment]
@lauripynnonen Done!

**Comment by lauripynnonen** [comment]
and it works!

**Comment by LukeCaley** [comment]
@lauripynnonen could you check that this is working in PROD and close the ticket if so - thanks!

**Comment by lauripynnonen** [comment]
- [ ] In production
- [ ] Says "Add"
