### ISSUE TITLE
3w: Change Supporting NS to Reporting NS on the Country 3w page

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1297]
I think this is the last place where we have the Supporting NS term visible - please change it to Reporting NS
![image](https://user-images.githubusercontent.com/8285694/83147203-a5f6c280-a0f7-11ea-8339-060b287b6636.png)

**Comment by lauripynnonen** [comment]
Perfect!

**Comment by nanometrenat** [comment]
Reopening as this is not yet in Production - but moving to "Done" to reflect that @lauripynnonen 's testing has passed.

**Comment by LukeCaley** [comment]
@lauripynnonen could you check that this is working in PROD and close the ticket if so - thanks!

**Comment by lauripynnonen** [comment]
Very much in PROD!
