### ISSUE TITLE
Covid Indicator Tracking on GO

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1298]
Indicator Tracking on GO. 

Intro
Discussion on Indicator tracking with Robert (PMER), Anssi (Regional IM ) Natalie (Covid IM) Mununuri (GVA-IM Planning & Reporting)

Issues to consider

•	Will indicator data be entered by National societies or by Country/cluster or Region as this has a bearing on quality control. 
•	If by National societies will there be a verification or quality control by the cluster/country or Region? If done by IFRC are we not dis impowering the National Societies, we are trying to empower.  
•	Within National Societies field reports are completed by DM managers, CEA focal points and PMER officers/managers. And within the IFRC most by Operations management staff. should indicators be completed by NS or by IFRC PMER/Ops team? So, we should essentially allow this diversity of actors based on the staffing capacity of the NS but ensuring that staff are well versed in the use of GO.  
•	How do we address the issue of frequency of reporting? NS and IFRC are used to a different reporting frequency but this is normally determined by the Regional office (PMER and Operations).  We will need to allow flexibility in the reporting requirements. Encourage NS to report on a fortnightly basis if required. Different pillars might have information at different times this is fine. Considering that some NS have only reported again once or twice since the first report compliance will be an issue. 
•	Since we are looking at a truly Federation-wide report targeting all National Societies to get the global footprint of the RCRC as a whole there should be no difference in the indicator tracking for strictly domestically funded response and multilaterally funded  NSs.
•	How are we reporting? Numeric figures only and are they cumulative?  Essentially if we are using the Field Report for both reporting and indicator tracking the narrative will be found in the description box and information on the indicator can be numerical. If we use a separate form, then we would need both quantitative indicator and a narrative description per priority area. Description per indicator might be tedious but still an option. 
•	Considering that the data will most likely be from National Societies with limited quality control, the visibility can be restricted and what will be viewable on the emergency are products created with this data. The data goes into the Go database from which ca be pulled for visualizations. Regional PMER/IM will review indicator data submitted in GO and flag and follow up outlier data. Data submitted will be saved in the GO database and figures need to be cumulative? Currently Field reports do not have save and continue so all data will need to be inputted in one GO every time there is an update. Might want to priorities the save and continue for the next build as FR will have more information coming through. 
•	If and when indicators change original information needs to be stored in the database and decisions need to be made prior to any change on how to aggregate or not any new data points. 
•	Indicators are based on the Pillars. The pillars are the plan and the indicator drop down should allow for a non-mandatory target figure (for planning) and a reached. So planned activities will not have a reached.  Figure. 

GO vs other platforms. 
GO should be a one stop shop for all things Covid especially in terms of reporting. Learning from the current challenges with the Financial Tracking form being a separate link. Having many separate related or unrelated platforms for one thing will result in a lot of non-compliance. 
Practical Functionalities and features.

1.	Options to consider for the development of the feature for GO include:
a)	Tying the Indicators to the existing Covid Field report within one of two ways:
•	Integrated as part of the Field report and Indicators appearing for each pillar ticked. This option has the advantage of being able to do everything all at once. But has the disadvantage of being more intimidating and resulting in possible none submission of the field report. Intimidating in the sense that if you click all 11 health pillars, they come with 25 indicators. 
•	A save and input indicator functionality that takes you to a fifth page of the FR where indicator data can be inputted. This option has the advantage of allowing NS to complete the Covid-19 field report in its current state and then if they have no indicator information to report they can submit only. The submit/save and input indicator button will allow NS with indicator information to then proceed to input the indicator data. The disadvantage is that there will instance where information is in the narrative section and an NS will click submit only and not go to the indicator page. 

b)	Having a link at the end of the field report that takes you to a different platform to complete the indicator tracking. This platform can be anywhere i.e. on data.ifrc.org or on a kobo form etc. The disadvantage with the link is that it might just be ignored. It would need to be well positioned and also consideration needs to be taken that it does not interfere with the submission of the field report. 

2.	What are the considerations for follow-on processes?  Is there a referral queue required to triangulate?  Don't want to make a complicated process, just checking whether checking/exception handling is required at all.
3.	Reaching out to the NSs that don't report anything or with outlier data will not be an automated process but done through the regional and sub regional networks thus forming solid PMER/IM networks with national societies. 
4.	Do we need an Internal dashboard to track whether everyone's pulling their weight and doing what they said they'd do- finding outliers and doing data quality?

**Comment by batpad** [comment]
@mmusori have added @mariam-yu as assignee. Would it be possible to get some UI / UX input for clarity on what needs to be built here?

Happy to jump on a call to discuss.

**Comment by mariam-yu** [comment]
@batpad I don't know much about this, I think. @mmusori can you help clarify?

**Comment by teklal** [comment]
This was solved in https://github.com/IFRCGo/go-frontend/issues/1363, right? @mmusori if so, do you mind moving this to the right column and closing if no further work needed?

**Comment by nanometrenat** [comment]
Yes solved in 1363 so closing as no further action required
