### ISSUE TITLE
[PROD] Extra "Additional information" tab appears on emergency page when using "child" URL

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1299]
## Issue
When being redirected to a "parent" emergency page by using the "child" emergency URL, there is an extra "Additional information tab" showing up. This tab is not a functional tab and doesn't work/show anything when clicking on it.

![image](https://user-images.githubusercontent.com/52411237/83154298-418c3100-a100-11ea-8b9d-83d0d636a09a.png)

## Steps to reproduce
Examples of URLs to use for observing this behaviour:
Staging: https://dsgoproxyapp.azurewebsites.net/emergencies/3907
Prod: https://go.ifrc.org/emergencies/4431

## Related feature
#1010 #1167 

## Impact
I suspect that it is only a very marginal group of users that would be able to see this as the parent emergency functionality has not been used on many pages and there is little trace of the old URLs. Flagging this nonetheless as it is a clear existing bug related to an implemented feature and would be good to fix at some point. Not the highest priority for now though.

## Is there a workaround?
The behaviour only occurs when using the URL of the "hidden"/"child" emergency. Refreshing the page also makes the extra tab disappear.

Note: we had a demo of this odd behaviour on a call with @GregoryHorvath. Happy to elaborate more on another call if needed.

**Comment by nanometrenat** [comment]
NOTE:  As of right now, when I go to emergency 4431 I don't get an extra tab (as logged above), rather I get the header but then the rest of the screen is grey.  However in staging there's still the same symptom as Tekla describes
https://go.ifrc.org/emergencies/4431#details
![image](https://user-images.githubusercontent.com/33625192/90015011-3fba1e80-dca8-11ea-9a27-9e114ac7bb5f.png)
