### ISSUE TITLE
[PROD] User email address is case-sensitive when requesting password reset / reminder of username

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1300]
## Issue
When a user tries to reset their password (https://go.ifrc.org/recover-account) or requests to get reminded of their username (https://go.ifrc.org/recover-username) they have to provide the email address they used to register.

At the moment this email field is case-sensitive and the email has to be given in the exact same case-format as upon registration. 

- When requesting to get reminded about their username: as long as the user gives any email where the letter before the @ sign is in lower-case, the user will see the message "If the given email address exists here, you will find an email in your mailbox...". They will not receive the email if the letters were not in the same case as when registering and they will see the same message even for emails that are not linked to a GO account.

- When requesting to reset password: In this case the system will let the user know if they give an email that does not exist (great!) with an error message "Error: That email is not associated with a user". However the same problem of having to have the last letter before the @ sign as lower case exists here as well. The email also has to be given in the exact same case format as when registering

For both user requests the system will give an error if the last letter of the email address before the @ sign is capitalized. In those cases the user will get the error "Please enter a valid email". This is problematic as there are a number of users who have registered writing their last name part of he email address in capital letters (IFRC default style). These users are hence unable to get their passwords reset or get reminded of their username through the system even if they used the correct case style.

I suspect this is the root cause of many of the problems users experience when they flag that they were unable to reset their password.

The username is not treated as case-sensitive so I do not see why we would treat the emails as such.

## Steps to reproduce
I am happy to have a call and demo this behaviour and the different cases as well as elaborate more.

## Expected behaviour
The email address should not be case-sensitive and the system should give an error if trying to use a non-existent email address.

## Related feature
#889 

## Impact
This would help and ease the workload of user support and having to reset passwords for them.

## Is there a workaround?
Users can contact IM for a manual update.

**Comment by nanometrenat** [comment]
xref previous tickets #434  and #471 
https://github.com/IFRCGo/go-frontend/issues/434#issuecomment-583769699

**Comment by GregoryHorvath** [comment]
@teklal Deployed to staging.

**Comment by karitotp** [comment]
- Password recovery and username recovery can now be done by entering an email that have lowercase and uppercase, even special characters, before the @ sign.

- In terms of the message for emails that are not linked with an account of IFRC Go, this is working well for password recovery, the page give me the message "Error: That email is not associated with a user". But in case of username recovery the message always is: "If the given email address exists here, you will find an email in your mailbox...".

**Comment by nanometrenat** [comment]
Think this has been released so moving ticket to done - @teklal to close when happy woop woop!

**Comment by teklal** [comment]
The changes that have been done are great! 

One thing that would be great to still address and is in the ticket and also mentioned by Karito in her comment (https://github.com/IFRCGo/go-frontend/issues/1300#issuecomment-638914582) is adding a check for the username recovery on whether the given email is linked to an account:

So for username recovery instead of always saying ""If the given email address exists here, you will find an email in your mailbox...", there should be an error when there is no account with that email, e.g. the same one as for the password reset: "Error: That email is not associated with a user". And in the case that the email indeed is linked to a GO account: "An email with your username has been sent to your mailbox". (@mariam-yu comments on the wording of these?)

**Comment by mariam-yu** [comment]
@teklal The suggestion is great, i.e. to specify whether the email exists or not. The wording seems good; I would just avoid putting the word Error.

**Comment by nanometrenat** [comment]
@teklal it would be worth doublechecking whether or not the distinction is deliberate.
I know on several systems it is deliberate to not tell the user whether there is an existing email address.

**Comment by teklal** [comment]
Ok, thanks for the good observations and input. I'll close this and will then open a new one if needed once we have feedback from infosec :)
