### ISSUE TITLE
Changing some of the queries from using Elasticsearch to using the database for more consistency

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#1306]
ElasticSearch can usually become inconsistent with what is actually in the database and what it knows.

Some of the dropdowns use it, for ex.: Emergency selection on 'Create Field Report' page's 'Context' step.

Convert these into actual database queries instead because they would still be low impact, and only keep the global search use ElasticSearch

**Comment by nanometrenat** [comment]
xref #989 also re Elasticsearch

**Comment by GregoryHorvath** [comment]
After discussions with the Dev team this has been scratched-off as an option for now since it really affects performance (in a bad way). Could be reopened in case there is no other / better solution to the issue, but recent Elasticsearch changes should help with it.
