### ISSUE TITLE
[PROD] 3W - country page - grey screen in Edge (i.e. can't load page)

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1314]
## Issue
Raised by Marcelo (FDRS) - if you go to the 3W tab for any country page then you get a grey screen in Edge browser - but the same page loads fine in Chrome.

Doesn't make a difference if you're logged in or not.
example:  https://go.ifrc.org/countries/43#3w

## Expected behaviour
3W page should load (not grey screen)

NB I have checked in dev tools and this doesn't look to be due to API calls as the one getting an error is the call to FDRS which I don't think relates to 3W??  anyway a dev can confirm

## Related feature
not sure what the "master" feature ticket is for 3W
@lauripynnonen can you please prioritise and assign as appropriate?  cheers

## Impact
just on Edge

## Is there a workaround?
Switch browser

**Comment by lauripynnonen** [comment]
I just received an email from a user that they are having this issue, too. Any updates on a possible fix!? @frozenhelium?

**Comment by frozenhelium** [comment]
Will take a look at it this week.

**Comment by frozenhelium** [comment]
@lauripynnonen @nanometrenat I was unable to replicate this issue, tested on Microsoft Edge Version 81.0.416.72 (Official build)(64-bit). Needs more information on the version of browser to debug this issue.

**Comment by nanometrenat** [comment]
The version on my machine is Microsoft Edge 44.18362.449.0

FYI the console says [object Error]: {description: "Object doesn't support property or method 'flat'", message: "Object doesn't support property or method 'flat'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'flat' at value (https://go.ifrc.org/assets/scripts/main.b7d1addd.chunk.js:1:702892) at La (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1872750) at Ua (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1872599) at ms (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1908484) at lu (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1899726) at su (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1899654) at Zs (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1896666) at Anonymous function (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1848049) at t.unstable_runWithPriority (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1923625) at Ho (https://go.ifrc.org/assets/scripts/2.162c99c7.chunk.js:2:1847745)"}

0: Object doesn't support property or method 'flat'
index.js (4,3)

**Comment by frozenhelium** [comment]
@lauripynnonen @nanometrenat http://dsgoproxyapp.azurewebsites.net/countries/43#3w loads in the legacy Edge now, cheers!

**Comment by lauripynnonen** [comment]
For me this works, great job!

**Comment by nanometrenat** [comment]
No grey screen now when I go to https://go.ifrc.org/countries/43#3w in Edge - thanks a lot!
