### ISSUE TITLE
3w: Project completed changes budget field to Actual Expenditure

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1319]
If the user checks the Project Completed -checkbox the PROJECT BUDGET (CHF) text is replaced with "ACTUAL EXPENDITURE (CHF)". 
Here
![image](https://user-images.githubusercontent.com/8285694/83875106-d3b2bb80-a736-11ea-8816-8dfcc913f61d.png)

**Comment by frozenhelium** [comment]
@lauripynnonen should this be new field (in the database) or update the existing `budget` field?

**Comment by lauripynnonen** [comment]
I don't think we'll need the original value, so just update the content of the budget field.

**Comment by lauripynnonen** [comment]
And we changed this around. It would be nice to keep the original value. @frozenhelium - could we still update the value to the original budget field (for the sake of simplicity in counting) and store the original value to a new field called original_budget

**Comment by frozenhelium** [comment]
@lauripynnonen in the UI should we show both the fields? Or, just switch the "Project budget" to "Actual expenditure" when completed is checked? Also, if we're switching the fields should the "Actual expenditure" copy the value of "Project budget"?

**Comment by lauripynnonen** [comment]
Hummm... Let's hide the Project Budget and show Actual Expenditure. Actual Expenditure should copy the value of the Project Budget.

**Comment by frozenhelium** [comment]
@lauripynnonen last one, how would this affect export / import and Tabular view in the 3W page?

**Comment by lauripynnonen** [comment]
@frozenhelium that's a good question. We're trying to keep it simple, but at the same time DRR needs this value. @LukeCaley do you know if the DRR colleagues would mind if the export table only showed "budget"? Alternatively we could rename that field on the export table "Budget/Expenditure" (for the tabular view that might be too long)

**Comment by LukeCaley** [comment]
@lauripynnonen  That would be fine - we can explain to them the logic.
Their main desire is the ability to track a final value of DRR projects across the world per year; as long as this change provides them the ability to do so, even if requiring one or two additional processing steps, I believe we have met the requirement.

**Comment by lauripynnonen** [comment]
The attached combination of fields breaks the form?
[IFRC Go ICRC test - Burundi.pdf](https://github.com/IFRCGo/go-frontend/files/4836613/IFRC.Go.ICRC.test.-.Burundi.pdf)

**Comment by lauripynnonen** [comment]
@frozenhelium seems to work!

**Comment by LukeCaley** [comment]
@lauripynnonen can you confirm that this has passed UAT for release?

**Comment by lauripynnonen** [comment]
Yes this passed my UAT.
