### ISSUE TITLE
Historic Databank and Country Profiles

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1321]
xref previous databank issues including
https://github.com/IFRCGo/go-api/issues/434
https://github.com/IFRCGo/go-api/issues/435
https://github.com/IFRCGo/go-api/issues/436

**Comment by mariam-yu** [comment]
Wireframes updated for country pages (6 tabs), reorganized and regrouped:

https://invis.io/FUXGHSABK4H#/356658484_3-1-1_GO_Country_Op

@LukeCaley Adding here for ease of access

**Comment by mariam-yu** [comment]
Updated wireframes as per latest feedback: https://invis.io/FUXGHSABK4H#/356658484_3-1-1_GO_Country_Op

@frozenhelium Updated the page without Past events: https://invis.io/YEXWOM1MAZT#/356658486_3-3-1_GO_Country_Overview

@guipizzini Do we have data (such as number of affected population) to populate a graph similar to operations for past events and epidemics? Also, is it confusing? Do we need to clarify IFRC-led operations? https://invis.io/VCXWON12GRU#/356658487_3-4-1_GO_Country_RiskAnalysis

**Comment by guipizzini** [comment]
@mariam-yu yes - it is in the API / JSON file available here: https://github.com/IFRCGo/data-analysis but @frozenhelium can you confirm?

It seems we are good to go soon :)

**Comment by frozenhelium** [comment]
@guipizzini @mariam-yu sure will do and let you know
CC: @thenav56

**Comment by mariam-yu** [comment]
Great so @guipizzini and @frozenhelium No comments on the wires? Good to go?

**Comment by guipizzini** [comment]
correct - can you share a final email please confirming we are good?

**Comment by frozenhelium** [comment]
@mariam-yu Looking at the data we currently have, the affected population is not available for past events and epidemics. @guipizzini We're currently pulling the data from reliefweb only and it doesn't provide the count of affected population.

CC: @thenav56

**Comment by mariam-yu** [comment]
@frozenhelium @guipizzini Does this work (see updated graph): https://invis.io/VCXWON12GRU#/356658487_3-4-1_GO_Country_RiskAnalysis @frozenhelium Could we have the years on the graph skip (e.g. say, jump from 2008-2012 if nothing happened there) if we want to crunch a lot of data into the graph and there is empty space?

**Comment by frozenhelium** [comment]
@mariam-yu Yes we can skip labels. And the chart looks nice :+1:

**Comment by guipizzini** [comment]
All good here @mariam-yu thanks a lot! @frozenhelium what would be the estimated time for this feature to be implemented / finalised in staging?

**Comment by frozenhelium** [comment]
@guipizzini About 3 weeks (around 3rd week of July)

**Comment by guipizzini** [comment]
So can we aim at testing for 1st week of August?

**Comment by frozenhelium** [comment]
@guipizzini Sure, can do!

**Comment by guipizzini** [comment]
@frozenhelium if any questions, while I am on leave in July - please redirect to @mmusori thanks!

**Comment by mariam-yu** [comment]
@imohkay @batpad The country UI is done. Tagging in this ongoing ticket, as this is where we started the design, but feel free to change: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/426677697

The country pages are on Zeplin. Thanks!

**Comment by nanometrenat** [comment]
Dev work moved to 4.4 based on conversation just now.  Guido will continue listing feedback ready for when this is picked up again.

**Comment by mariam-yu** [comment]
@frozenhelium Thanks for the update and it looks good. Some cosmetic UI comments. Do you mind also connecting with Karen? She had some logic for assigning font-weight depending on font type we use. It would be good to have them standard. and same with page styling and all, but here are the major things. Let me know if any questions, and thanks!

- Headers (e.g. Key Indicators, Population Map) - 18px instead of 20px
- For box content in terms of weight, can you check with Karen? We have Poppins-Regular on the left and semi-bold on the right. I thin she has weights assigned to those already that you can reuse.
- We will provide the icon for export box (will be on Zeplin).
- Climate chart - subtext (average…) - check font weight and size (14px and lighter weight)
- Seasonal Calendar - Side left text - size text 10px, medium, also can you readapt the box colors, formats as per zeplin  (no border, no shadow, etc.)
- Can you add grey background on the page as per Zeplin (check with Karen?)

**Comment by frozenhelium** [comment]
@mariam-yu Thanks for the detailed comments. @imohkay lets chat sometime regarding the above comments.

**Comment by imohkay** [comment]
@frozenhelium Sounds good. If you wanna take a stab at it first also, let me know :)

**Comment by frozenhelium** [comment]
Yeah, definitely, I'll let you know if I ran into something

**Comment by frozenhelium** [comment]
Hey @imohkay, a little help! I couldn't find variables regarding the font size for headers and other texts (eg: ones that have value in pixel viz. 18px, 14px, 10px). We only have relative font sizes in the `_variables.scss` file. Is it specified somewhere else?

**Comment by imohkay** [comment]
@frozenhelium Hey, if it helps, I'll quickly list the font sizes in pixels and revert :)

**Comment by frozenhelium** [comment]
@imohkay Thanks, that'll help a lot.

**Comment by imohkay** [comment]
@frozenhelium Hey, I sent you a PR for the same...
