### ISSUE TITLE
Weekly Field Report summary not part of requirements. 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1328]
## Issue
At the beginning of every week there is a Field Report summary, new operations summary, new surge alert summary and a weekly digest summary. The these summaries are potentially a legacy issue, from the time when we had summaries for the different notifications. Now should only have the Weekly Digest which gives a summary of the deployments done, the new operations launch and new Field Reports created but does not have new Surge alerts.
The code that provides the summary of Field Reports, summary of new operations needed to be removed or archived. Below is a snippet of the email notifications received

![image](https://user-images.githubusercontent.com/7780809/84637709-4faac180-aef6-11ea-827d-d2bf3125f801.png)

**Comment by teklal** [comment]
Just to complement (and @mmusori correct me if I'm wrong): Not only should the field report summary email but also the surge alert and new operations ones that are sent (as in Munu's screen shot) in addition to the true weekly digest be discontinued/removed. So that the only summary/compilation email to be sent on Monday morning is the one called "weekly digest".

**Comment by GregoryHorvath** [comment]
This is now deployed to staging. @mmusori as I'm seeing you're already subscribed for the weekly digest there so we will see on monday the latest if it worked or not since there are a couple of new Field Reports for sure.

**Comment by teklal** [comment]
I only got the weekly digest email from staging today so this seems to work! A curious thing is though that usually I've gotten the weekly digest from staging at the same time as from prod (i.e. 5:15 on Monday), today the Staging one didn't come until 9:18 though (prod came on time at 5:15). Don't know if there was something on my side causing the delay or if this is related to the change?

**Comment by GregoryHorvath** [comment]
@teklal It was me, because it still had a little hole in it where I didn't think anything could go wrong, but it did. So I triggered the weekly notification by hand at that time after making that fix.

**Comment by GregoryHorvath** [comment]
Deployed to production yesterday.
