### ISSUE TITLE
3W: If Reporting NS is ICRC then Budget and People targeted/reached not required

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1334]
**Is your feature request related to a problem? Please describe.**
ICRC has agreed to report movement-wide activities through 3w, but they cannot provide all the required information. Hence we must make them a special case, where they can fill out forms leaving out  Budget, People targeted and People reached

**Describe the solution you'd like**
If the reporting party is ICRC, make Budget, People targeted and People reached optional

**Describe alternatives you've considered**
We could make those values optional for everybody, but then we would potentially miss out on a lot of data

**Comment by lauripynnonen** [comment]
@frozenhelium can you put this on the top of your implementation stack? Thanks!

**Comment by lauripynnonen** [comment]
No idea how this is done in the backend, but works!

**Comment by frozenhelium** [comment]
@lauripynnonen In the backend we had to remove some validations all together for this to work

**Comment by lauripynnonen** [comment]
(this passed my UAT, too)
