### ISSUE TITLE
Search bar and search suggestions bar - design update

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1338]
- Search can be cleaned up visually to sort the results better, also make it more dominant. The users usually didn't use the search even though it would help them to find things faster. Considering making it more dominant and visible.

- Search results / dropdown: Appeals show but DREFs dont. Hard to comb through them. Needs a visual hierarchy.

- Testing of the functionality

**Comment by mariam-yu** [comment]
@LukeCaley @batpad Please take a look at a new suggestion for the search field and search results. Is this doable? Please share your thoughts. We also added a back to top button on the page itself (once you scroll down), which should be visible and sticky after scrolling down. https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/422773491

**Comment by LukeCaley** [comment]
I think the correct screen on Invision is https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/422773493

It looks good and useful but not the priority here should be responsiveness/speed and accuracy of search rather than design.  For @batpad to comment on relative complexity.

**Comment by mariam-yu** [comment]
Assigning to @LukeCaley for review and finalization specific to the look and functionality of the auto-complete dropdown which includes grouping of elements and UI clean up: https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens
