### ISSUE TITLE
Make links to Admin in frontend point to new domain

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1360]
**Is your feature request related to a problem? Please describe.**

Currently, links to the Django Admin point to https://prddsgocdnapi.azureedge.net/ , which works, but it would be better to point to the more user-friendly https://goadmin.ifrc.org/

Currently, we use the same config variable called `api` to construct URLs for API calls as well as the Admin.

**Describe the solution you'd like**

Options would be:

 - Create a new config param like `adminUrl` and have it default to the API url.
 - Move over the API end-points also to https://goadmin.ifrc.org/ as the domain - while this would work, I'd rather not change that.

So, we'll likely just have to create a new config parameter and use that.

xref #1116

**Comment by batpad** [comment]
Will be good to do as part of general cleanup. Moving to 4.4.

**Comment by tovari** [comment]
Has this been completely resolved, @batpad?
