### ISSUE TITLE
COVID Indicators - KoBo form link from GO

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1363]
## Request (new feature, but under urgency)
FDRS are creating a KoBo form to track National Society indicator reporting for COVID-19.  This will be launched by the SG early next week.

There is a strong desire for National Societies to have only one entry point to Federation-wide reporting, so it is requested that GO have a link to the indicators data collection form (and possibly another link to the separate Financial Form also).

@mmusori is the lead on this so can answer any questions.

Proposal is to put a dropdown by the New Field Report button (dropdown already part of the wireframes but for Informal Update)

Timing:  to Production *this week* so that information can go into the SG letter (being translated).

Munu to confirm whether or not login is to be required before users can proceed.

@mariam-yu @teklal @GregoryHorvath tagging you for info
@batpad I guess this will be coming to you for action, Munu to confirm prioritisation.

**Comment by RaniaAlerksoussi** [comment]
Thanks @nanometrenat and @mmusori! that would be awesome. Also if the same could be done for the Fed-wide covid-19 financial form, that would be ideal. This way, all FW data collection can be done "through" GO. Thanks a million!

**Comment by batpad** [comment]
So, as I understand it, the task here would be:

 - Make `Create Field Report` button a Drop-down as per wireframes
 - Get confirmed text and links from @mmusori on what options need to be and where they should link to
 - Implement options in drop-down - get inputs from @mariam-yu on design if required.

@imohkay - sorry to disturb your flow of work, but would you be able to look into how feasible this would be to / how much work this is? We would need to implement this as a Hotfix to the `master` branch. Let me know if you need any clarification. Thanks!

**Comment by imohkay** [comment]
@batpad I'll get it done soon with static content in the dropdown and update you.

**Comment by imohkay** [comment]
@batpad Please checkout branch feature/1363-dropdown-field-report
I have commented out the static Dropdown markup just below the field report. You will have to add the requisite Translation strings and the links to the dropdown items as well.
Let me know if you need anything.

**Comment by batpad** [comment]
@imohkay I've updated the branch commenting out the code and adding some example text and links. Could you please pull and deploy to a surge URL?

Once that's done, @nanometrenat @mmusori it's probably useful to have a quick call to go over the implementation and check that this would work, and also so that you're able to then come up with the appropriate text and links for the dropdown options.

**Comment by batpad** [comment]
Testing URL for the dropdown: https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/

If this works, we can plug-in text and links as appropriate - @nanometrenat @mmusori and @mariam-yu to check design. Thanks! :)

**Comment by mariam-yu** [comment]
@batpad Checking for the UI with @maisa-yu on the conceptual side it works, except I suppose in this case we need to rename the button from Create a Field Report to maybe just Create a Report (@mmusori ?)

**Comment by mmusori** [comment]
Yes @mariam-yu  we can change that to "Create Report" and we will have two new options in addition. 
1. Covid-19 Indicator Report
2. Covid-19 Financial Form

**Comment by batpad** [comment]
All sounds good to me. @mmusori would you be able to provide the links that The Covi-19 Indicator Report and Covid-19 Financial Form should go to?

To confirm -

Rename button to `Create a Report`

Options will be (in order):

 - Covid-19 Indicator Report (@mmusori to provide link)
 - Covid-19 Financial Form (@mmusori to provide link)
 - Create a Field Report

If that's confirmed, and ideally if you could also send the links to the forms, @mmusori we can make the changes right away and have it available for testing. Thanks!

**Comment by mmusori** [comment]
@batpad 
Indicator tracking is being tested and I have attached the url for that. 
The financial form is in use , so not sure we can use t for testing at this stage so I suggest using something else in the meantime like this url: https://ee.kob4.ifrc.org/single/::8FQ9laVR

Options in order will be 

- Create a Field Report
- Covid-19 Indicator Tracking (https://ee.kob4.ifrc.org/single/::Ho8bHKDr)
- Covid-19 Financial Form (waiting for link)

**Comment by maisa-yu** [comment]
@mmusori @batpad 
Sharing a UI suggestion for the button, you can click on "Create Report" to see the dropdown. 
https://invis.io/HGX94BX3EJA#/417294996_1-0_GO_Home
(PW: GOprototype)

**Comment by batpad** [comment]
Have updated https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/ to match the text on the wireframes.

Have added the link for the Covid-19 Indicator Report. For the Covid-19 Financial Form, it still links to https://example.com . We will update the link before going to production as per previous comment.

@maisa-yu @mariam-yu - let us know if this looks okay. @mmusori let us know if the text seems fine, have followed the wireframe and not your exact text from above - if there's changes to be made, could you discuss with @mariam-yu and ideally we'd update the wireframes as well to be in sync.

Thanks all

**Comment by batpad** [comment]
Moved this to Ready for QA.

Things to test:

 - Create Report dropdown on top-right matches wireframes
 - Create Field Report correctly takes you to create field report page
 - Clicking on Covid-19 Indicator Form takes you to the form (do NOT test filling in that form)
 - Currently, the last item in the menu takes you to example.com. This will be updated when we have the prod link.

Since we will be deploying this as a hotfix to master, the testing URL is https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/ (and this won't go through staging).

**Comment by mariam-yu** [comment]
> Have updated https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/ to match the text on the wireframes.
> 
> Have added the link for the Covid-19 Indicator Report. For the Covid-19 Financial Form, it still links to https://example.com . We will update the link before going to production as per previous comment.
> 
> @maisa-yu @mariam-yu - let us know if this looks okay. @mmusori let us know if the text seems fine, have followed the wireframe and not your exact text from above - if there's changes to be made, could you discuss with @mariam-yu and ideally we'd update the wireframes as well to be in sync.
> 
> Thanks all

@batpad We are updating the text on the UI designs now. Will share soon (@maisa-yu ) . Can you please also match the UI style of the dropdown? Ideally, the text shouldn't wrap. Thanks!

**Comment by mmusori** [comment]
@mariam-yu  and @maisa-yu can you use these terms in the wireframe:

- New Field Report
- Covid-19 Indicator Tracking.
- Covid-19 NS Financial Overview

**Comment by batpad** [comment]
>  Can you please also match the UI style of the dropdown? Ideally, the text shouldn't wrap.

@imohkay are you able to look into this and ask for clarification if needed?

**Comment by imohkay** [comment]
@batpad I've pushed to the branch with the styling changes.

**Comment by batpad** [comment]
Have updated surge URL. Latest version is at https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/

**Comment by mmusori** [comment]
This is working very well. Just waiting for the updating of the terms  to 

- New Field Report
- Covid-19 Indicator Tracking.
- Covid-19 NS Financial Overview

https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/. Thanks @batpad  and thanks @mariam-yu

**Comment by mariam-yu** [comment]
@mmusori @batpad the prototype is updated: https://invis.io/8FXCLVKEY6C#/417294996_1-0_GO_Home The file is on Zeplin as well. Thanks!

**Comment by batpad** [comment]
Have updated text as per wireframes at https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/ - still awaiting final link for Financial Overview.

@mariam-yu would you be able to do a final check of the styling and let @imohkay know if there's anything that seems off? Thanks!

**Comment by mmusori** [comment]
Thanks @batpad . I am chasing after the url for the financial form.

**Comment by mmusori** [comment]
@batpad the url for the financial form is https://ee.kob4.ifrc.org/single/::w4KbO3Rc
There is a request not to have the links live until Monday afternoon. Can we still push to production and then add the links on Monday or do we wait until Monday to push to production.

**Comment by batpad** [comment]
> There is a request not to have the links live until Monday afternoon. Can we still push to production and then add the links on Monday or do we wait until Monday to push to production.

I would then recommend waiting until Monday for the push to production. It seems awkward to push something with broken / dummy links. :+1:

**Comment by mariam-yu** [comment]
> @mariam-yu would you be able to do a final check of the styling and let @imohkay know if there's anything that seems off? Thanks!

@batpad The design doesn't seem to fully match. It's on Zeplin for reference, but looks more like this:
<img width="921" alt="Screen Shot 2020-07-10 at 10 41 43 AM" src="https://user-images.githubusercontent.com/60006476/87140881-19b0f100-c29a-11ea-8145-ac37def5bb53.png">
Also red on click for the button. Thanks!

**Comment by batpad** [comment]
@imohkay could you please look?

**Comment by batpad** [comment]
Have updated the testing URL with the latest styles: https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/
cc @mariam-yu @maisa-yu  - thank you! :)

**Comment by mmusori** [comment]
We can go ahead with the merge to production and the urls are below:
    
Indicator tracking: https://ee.kob4.ifrc.org/single/::Ho8bHKDr

    
Financial Overview: https://ee.kob4.ifrc.org/single/::w4KbO3Rc

**Comment by batpad** [comment]
Have updated the links: https://ifrc-go-feature-1363-dropdown-field-report.surge.sh/

@mmusori could you please do a final test and confirm this is correct?

**Comment by nanometrenat** [comment]
Thanks loads for doing this dropdown @batpad 

Just one last further tweak required please to finish it off - at the moment when I access go.ifrc.org via mobile device I still see the "New Field Report" button rather than the lovely new-style "Create a Report" dropdown.  Can you please make sure that the mobile header is consistent (where consistency is required)?  Thanks a lot

**Comment by batpad** [comment]
Thank you for the catch @nanometrenat .

@imohkay would it be straightforward to switch the Create Field Report button to the Dropdown in the mobile-header.js component? I'm not sure how the dropdowns currently work on mobile. I agree that this would be really good to do, as even if we don't fully support mobile, we shouldn't have inconsistencies. @imohkay if this seems straightforward from a styling stand-point, let's do it right away, or if it seems like it's better to wait until the overall styles restructuring is complete to get this working on mobile cleanly, let's schedule this for the mid-August milestone. @imohkay please advise on what seems best. Thanks!

**Comment by imohkay** [comment]
@batpad I'll take a look... At some point, it may be nice to refactor the header so we don't have two different components and the CSS handles the styling... But that's for another day :D

**Comment by nanometrenat** [comment]
@imohkay can you please confirm status of this ticket?  Is it done or should I log a new ticket for the mobile header aspect?  I see a commit above but not sure of status.  Thanks a lot.

**Comment by nanometrenat** [comment]
Confirming that mobile header looks good on staging - when accessing from my mobile I can see the dropdown with Field Report and links to the two KoBo forms.  Many thanks

**Comment by nanometrenat** [comment]
Mobile header working in Production
