### ISSUE TITLE
Refactoring the grid across the site for RTL compatibility

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1364]
**Goal:** RTL support across the site by mid-August 2020.

**Background on the styling issue for RTL support:** The style files need to be refactored to support RTL. This has been done by DFS and includes replacing key CSS values for properties like float, margins, padding, borders, border-radius, positioning values, etc.

**Issue:** Unfortunately, the current version of Chrome (version 83x) does not support float: inline-start, which causes massive issues in the layout, seen on pagination on this link, for example (https://ifrc-go-feature-translation.surge.sh/).
So we have had to revert to float: left, which is problematic. @frozenhelium  has mentioned it has been fixed in v 85x (please correct here if wrong).
[Caniuse.com](https://caniuse.com/#search=float%20inline) indicates that only Firefox support is confirmed for these rtl values for float properties. (I have not tested this personally).

The site uses [Jeet Grids] (http://jeet.gs/) as the grid system.
Unfortunately, Jeet uses Sass mixins which output code using margins and float. This means that the compiled CSS will need to be fixed to swap these values for RTL compatibility. How this can be done needs to be determined.

**Possible solutions:**
1. Leave things as they are, with the caveat of no-support on Chrome. This implies the layout will be broken on Chrome and other browsers (for RTL languages) until the bug is fixed. I would not recommend this as a path if RTL support is expected of the site.
2. Create a new Sass grid that doesn't rely on floats for alignment and margins for gutters. Instead, the grid will use Flexbox instead of floats and padding for gutters.

**Advantages of creating a new grid**
1. The new grid will use logical properties like flexbox and equal padding on both sides, which will translate seamlessly when the direction of the document is RTL.
2. Prioritising HTML/JSX markup over writing Sass mixins for the grid will make it easier for developers to use the grid. Additionally, Sass mixins will be available on the rare occasions when more complex or custom solutions are needed for certain widgets.
3. Moving to presentational grid classes should shave off hundreds of lines of code from the current compiled CSS file.
4. We don't need to figure out how to keep doing a search and replace for the problematic properties in the compiled files using Jeet Grids.

**Disadvantages of moving to a new grid system**
1. Every page will need additional markup (new classes, mostly and perhaps a wrapper div at the most per widget) and therefore testing
2. Time and budget

**A possible path forward with a new Sass grid:**
1. Create a Sass grid with parent containers, rows and 12 columns. The grid can be extended with different sized gutters or more columns as needed.
2. Add the new grid to a single page and test it thoroughly
3. Migrate the rest of the pages to the new grid with incremental testing
4. Clean up the codebase and remove all the old styles using Jeet Grids

**Timeline**
1. Create a new Sass grid compatible with the current site's UI, including gutters, media queries, etc. Write thorough documentation for the grid: roughly 15-20 hours
2. Migrate a copy of the homepage using the new grid: roughly 3 hours

Subsequently, the time to make migrations per page should be much less, roughly between 0.75 to 2 hours per page at the very most.

Time for testing on mobile, desktop and rtl will be additional.

@frozenhelium @thenav56 @batpad Ticket based on our call yesterday.
@frozenhelium please add inputs and corrections as you see fit :)

**Comment by frozenhelium** [comment]
Thanks @imohkay for the very detailed ticket. I strongly recommend creating and using new Sass grid system since that'll be better in longer term as well. The current grid system library that we use is a bit complicated and  uses not-very-good styling technique to place the content (i.e. float: left / right). And, it also doesn't have proper support for the RTL layout. Since RTL layout is very important for the Arabic, we must find workaround for this. Having the custom lightweight grid system is the best approach for the current situation and will also have longer term benefits as it'll be easier and less complicated to change the layout of the page as required.

CC: @nanometrenat

**Comment by nanometrenat** [comment]
Based on comment from Sanjay via email:  would update the grid framework through the site to support RTL languages. This has the side effect of bringing the styles up-to-date and making them easier to work with, and taking us a long way toward much better support on mobile.

xref https://github.com/IFRCGo/go-frontend/issues/1253 - not sure if this ticket replaces that ticket or is a prerequisite?

**Comment by nanometrenat** [comment]
Sanjay advised on call yesterday that @karitotp has tested this and is happy.  Hence moving to Done.

**Comment by batpad** [comment]
@nanometrenat on second thoughts, am moving this back to `Ready for QA`.

To explain: this code has been incorporated and we have tested that everything looks fine _without translations implemented_. We have not yet fully tested "for RTL compatibility" - this has been mostly tested, but will likely benefit from another thorough test, especially when we have translation strings for RTL strings in.

Although, we could also use https://github.com/IFRCGo/go-frontend/issues/1253 to track / confirm that all the styling works correctly once an RTL language is implemented.

Just wanted to clarify that this has not yet been thoroughly tested for RTL. Am happy keeping this in Done as this was a bit specific to the grid implementation and marking #1253 as Ready for QA whenever we have Arabic language strings and that is fully ready to test?

**Comment by nanometrenat** [comment]
> Just wanted to clarify that this has not yet been thoroughly tested for RTL. Am happy keeping this in Done as this was a bit specific to the grid implementation and marking #1253 as Ready for QA whenever we have Arabic language strings and that is fully ready to test?
Sounds good to track via 1253 rather than keeping two open for RTL - thanks!

**Comment by nanometrenat** [comment]
OK now I'm confused - are we tracking RTL support via https://github.com/IFRCGo/go-frontend/issues/1253 or via https://github.com/IFRCGo/go-frontend/issues/1382 (currently at Ready for QA) or this ticket?

I think we should keep one open but close the others (unless they have separate outstanding work)

**Comment by batpad** [comment]
Thanks @nanometrenat .

The work to support the RTL grid is all done and merged to production. Let's track detailed testing of RTL when we have translations for an RTL language in #1253. Closing here.
