### ISSUE TITLE
Change Subscribe / Unsubscribe to Follow / Unfollow on Emergency pages

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1370]
Ref #1206 - for consistency, we should rename Subscribe / Unsubscribe to Follow and Unfollow on the Emergency pages.

@GregoryHorvath assigning to you since you had worked on this, but feel free to toss it back to me.

**Comment by nanometrenat** [comment]
Confirmed that wording is now "Follow" in the surge testing URL https://ifrc-go-release-v4-3-11.surge.sh/emergencies/4059#details
