### ISSUE TITLE
Consistency across charts across site

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1372]
Fix consistency across:
Graphs and charts across the site: They can follow the new Zepling V2 designs with white background, shadow and other changes

**Comment by imohkay** [comment]
@maisa-yu Hey, for the charts, the homepage charts are slightly different from the charts in the Go Library 2 page on Zeplin. (Just the background color for the chart header, which is white on the homepage).
Which one should I refer to, to make the charts consistent across the site?

**Comment by maisa-yu** [comment]
hey @imohkay the header background will be white everywhere.

**Comment by imohkay** [comment]
Ok. Thank you :) @maisa-yu

**Comment by imohkay** [comment]
@maisa-yu also, I'm wondering what to do for the chart on the emergency landing page, since it has a section to the left (Emergencies by type). Should I follow the same styling for both those sections? (i.e. white background, uppercase text for both headers, etc.)

**Comment by maisa-yu** [comment]
@imohkay We're updating the emergency page with the chart, I'll let you know when it's on zeplin :)

**Comment by imohkay** [comment]
Great @maisa-yu 
Thank you :)

**Comment by maisa-yu** [comment]
@imohkay the Emergency page is updated on zeplin with the charts, you can check there

**Comment by imohkay** [comment]
@maisa-yu thank you :)
Could we consider this the final design for Emergencies? So I could start implementing it?
cc @batpad

**Comment by imohkay** [comment]
Done.
Relates to #1364
