### ISSUE TITLE
Translation: PER form translation

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1375]
PER forms have their own translation mechanism and currently has translations for English, French and Spanish (not for Arabic). The translation mechanism used in the PER forms is quite complex and does not align with the site wide translation.

CC: @batpad

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/971

**Comment by nanometrenat** [comment]
Hi, is this ticket still relevant?  @tovari

**Comment by tovari** [comment]
Not relevant anymore.
