### ISSUE TITLE
[Staging] [3W] "Add" button in 3W fails

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/go-frontend#1378]
## Issue
Clicking the "Add" button in 3W shows a blank page on the frontend.
In the dev console, I see this error "Cannot read property 'projectFormReportingNational' of undefined"

## URL
Staging URL (fails here): https://dsgoproxyapp.azurewebsites.net/regions/3#3w
Prod URL (works here): https://go.ifrc.org/regions/3#3w

## Steps to reproduce
1. Go to the URL above
2. Click on the 3W tab
3. Click on the "Add" button

## Expected behaviour
Follow the same steps in the Prod URL. You get a form on clicking the "Add" button.

**Comment by frozenhelium** [comment]
Should be fixed now
