### ISSUE TITLE
Setup "init" pattern with loading to fetch initialization data from backend

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1386]
Relates to #940 

As we move a lot of hard-coded values on the frontend to being handled by the backend as part of #938, we should develop a clean pattern for the frontend fetching data that is needed across most pages. This ensures we have a single place to handle the data fetching and loading state, and will make adding new constants and parameters to fetch from the backend much easier in the future, and avoid the pattern we are using in places currently of hard-coding those values on the frontend.

Data that frontend needs to fetch as part of "init":

 - User data: User logged in state, and profile if the user is logged in
 - Country data
 - ... Ideally we would start moving many constants that are defined both on the back and frontend, but this can be done incrementally once we have this pattern in place.

### Frontend:

 - We would need some way to have the application make an `init` request on load, show a loading state to the user while the init data loads, and only then render the app, so we can be sure the init data is always available across pages once the app has loaded. @frozenhelium I was looking at https://github.com/IFRCGo/go-frontend/blob/develop/src/root/index.js#L101 and realized I don't quite know the best way to do this - might pick your brain here / if you have any thoughts or suggestions, would be very useful.

 - Wire up frontend to fetch data from user `profile` and `init` endpoints.

 - In all the places in the code that currently load hard-coded strings in the frontend code, replace it with getting data from the redux store that has been populated on init.

### Backend:

 - On the backend, we need to decide whether to create a single `init` endpoint, or have the frontend fetch data from different endpoints. My suggestion here would be to have the frontend fetch data from separate end-points for existing entities, eg. countries.
 - We only create a separate end-point for hard-coded constants, not database values (which continue to be served from existing APIs).

So, initially, ideally we would need no change on the backend until we start moving over constants in addition to hard-coded database values. I would rather not prematurely optimize the number of requests we need to make to "init" - if we feel strongly like we need to combine all init values into a single endpoint for performance reasons, we can do this down the line, but this is likely better handled through smart caching strategies, etc.

@frozenhelium - to setup the "init" / loading pattern on the frontend, it would be great to get your help. Let's chat quickly when you have a moment and see how best to lay that out. Then we're happy to jump on integrating the new geospatial APIs onto the frontend and replacing the hard-coded values. Thanks!

cc @geohacker @thenav56

**Comment by frozenhelium** [comment]
@batpad While setting up this I also noticed that we don't have any code splitting (i.e. loading only the requested views / components dynamically) in the GO! We should also implement that in the future.

**Comment by nanometrenat** [comment]
Adding to Phase 4.3 board as I believe it is currently being worked on.  Devs can you please confirm if this is ready for QA?

> * We would need some way to have the application make an `init` request on load, show a loading state to the user while the init data loads, and only then render the app, so we can be sure the init data is always available across pages once the app has loaded. @frozenhelium I was looking at https://github.com/IFRCGo/go-frontend/blob/develop/src/root/index.js#L101 and realized I don't quite know the best way to do this - might pick your brain here / if you have any thoughts or suggestions, would be very useful.

I can see the initialising/loading page in staging - but have any of the below conversions also been made?

> Data that frontend needs to fetch as part of "init":
> 
> * User data: User logged in state, and profile if the user is logged in
> * Country data
> * ... Ideally we would start moving many constants that are defined both on the back and frontend, but this can be done incrementally once we have this pattern in place.

Just checking what changes need to be tested - many thanks.

**Comment by mariam-yu** [comment]
Added us to the ticket to support with the design of the preloader.

**Comment by nanometrenat** [comment]
At the moment in staging it is taking 15+ seconds of viewing the initialising splash screen before I get to see any of the home page.  Then another quite a long time before the _content_ of the homepage loads.  As you can see from the screenshot it took 51.5s to load the whole homepage.  This needs investigation please!
https://dsgoproxyapp.azurewebsites.net/

![image](https://user-images.githubusercontent.com/33625192/89453744-fd508900-d75f-11ea-9e2f-b5443faa61ca.png)

**Comment by nanometrenat** [comment]
Noting that I kept the window open, simply hit "refresh" button on my browser.  This time the initialisation splash screen was there for only a couple of seconds (not 15) and it took 39.32s to load the whole homepage.  So the refresh was faster but still very slow.
cc @LukeCaley

**Comment by batpad** [comment]
Thanks @nanometrenat - following up from Teams, this seems caused by the new geo-changes and accidentally including the geo data in the nested data serializers - sorry about that, we are working on fixing that and hopefully the slowness can then be re-tested. Thanks!

**Comment by nanometrenat** [comment]
The team have removed the geometry data from staging, since then I have checked in staging and found the following:
it only took about 2s for the initialising screen and then it took >1s of blank, then 2s of the "initialising", then another <1s to load the homepage web elements, then another second to load highlighted operations.  Those measurements were by counting - the network tab of dev tools tells me it took 7.96s to load the page as a whole.  So LOTS better than the 51.5s loading time from last night (THANKS) but not as quick as would be ideal.  The main slowness issue is solved though.  I think the Init bit might need some more love though.

**Comment by LukeCaley** [comment]
@batpad @geohacker if poss, could you update on progress around improving loading speed related to this change.

**Comment by batpad** [comment]
Fixing loading speed is dependent on #1517

**Comment by mariam-yu** [comment]
@batpad @LukeCaley We played with a few ideas for the pre-loader. We used this library as inspiration for interaction: https://connoratherton.com/loaders

Our suggestion would be to use the one from column 2, row 5. We played with a few option (that you can see below), but this seems to be the most intuitive. We propose to use the same throughout the site whether loading the entire page or sections.

![_Preloader 3](https://user-images.githubusercontent.com/60006476/91164035-bacefc00-e6ce-11ea-9c93-5670e049c44f.png)
![Preloader_Sections 3](https://user-images.githubusercontent.com/60006476/91164769-e999a200-e6cf-11ea-8759-eedd7b4695bb.png)

------------- Others we considered

Column 4, row 3 // mimicking GO logo
![_Preloader 2](https://user-images.githubusercontent.com/60006476/91164092-d1755300-e6ce-11ea-833a-47541c7624f8.png)

Column 4, row 4 or column 2, row 6 // mimicking emergency beacon
![_Preloader](https://user-images.githubusercontent.com/60006476/91164238-0b465980-e6cf-11ea-8290-bd207d6965db.png)

**Comment by batpad** [comment]
Thanks @mariam-yu .

Let's work on the global loading screen now, and we can tackle changing loading for individual elements later.

@frozenhelium would you be able to update the styles for the init loader based on @mariam-yu's comment above, or would you rather we take that on? Thanks!

**Comment by frozenhelium** [comment]
@batpad depends on how urgently we require this. I can take a stab at it after a while.

**Comment by LukeCaley** [comment]
@batpad could you update on the status of this ticket and the elements which require testing in staging if/when complete?

**Comment by nanometrenat** [comment]
possible xref https://github.com/IFRCGo/go-frontend/issues/1529

**Comment by LukeCaley** [comment]
As discussed on the call today (09/09), @batpad to confirm progress, loading speed expectations once 'resolved' and likelihood of this being rolled into the current release.  Suggest that this needs to be completed by 11/09 in order to be considered for the 'safari' release

**Comment by batpad** [comment]
The updated design for the loading screen should now be on staging, also the caching of countries and regions.

**Comment by mariam-yu** [comment]
@batpad awesome! Then when we get a chance, we can update the new 3 dot pre-loader for the other sections.
