### ISSUE TITLE
Key figures data on the regional pages.

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#139]
Hi Anna,

On the Regional Pages we are displaying the incorrect "data" line as the header.

The regional pages, should basically reflect the "Home Page" but just focusing on the region of concern.

This means that the header of the data line, should be the same as the one on the home page, but just filtered for the region of concern. For now we are showing on the regional pages, the data line that relates to the emergencies, which should not be the case.

*This is what we have on the home page. We would like to have the same for the regional page, but filtered only for the region of concern*
<img width="1259" alt="screen shot 2018-01-30 at 08 50 09" src="https://user-images.githubusercontent.com/23258092/35554132-e0b47f2a-059a-11e8-85c4-6870379e088c.png">

*This is what we have at present on the regional pages. These are for now reflecting the "emergency" data, which should not be the case. We want to have the regional overview of the operations.*
<img width="1251" alt="screen shot 2018-01-30 at 08 49 57" src="https://user-images.githubusercontent.com/23258092/35554188-1d91f65c-059b-11e8-9895-1558328c81af.png">

**Comment by dereklieu** [comment]
@guipizzini the region page was laid out this way in the original wireframes, and it also closely matches what we started on for the country pages. We can switch this over at a later point, but don't have room in phase 1 for this.

**Comment by guipizzini** [comment]
Ok labeled it for phase 2
