### ISSUE TITLE
[PROD] Change wording of disclaimer on map exports

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1395]
## Issue
The disclaimer under the map in the map exports (3W map, field report map) currently reads: "... of the International Federation of **_the_** Red Cross and Red Crescent Societies or National Societies ..."

field report/emergency page map:
![image](https://user-images.githubusercontent.com/52411237/87539311-eefdd880-c69d-11ea-8389-8a32a55fcd31.png)

3W country page map:
![image](https://user-images.githubusercontent.com/52411237/87539333-ff15b800-c69d-11ea-9f92-a1b680fd7559.png)

The extra "the" should be removed from the text (highlighted in the screenshots above).

This should be applied to all map exports on GO.

**Comment by batpad** [comment]
Let's keep this in this phase. @geohacker should be a minor fix? Let me know if you want me to look. Thank you!

**Comment by LukeCaley** [comment]
Is this intended for the current release @batpad @geohacker ?

**Comment by batpad** [comment]
Whoops, almost missed this @LukeCaley - have a PR up now, this will be included in this release :+1:

**Comment by batpad** [comment]
This is on staging now.
