### ISSUE TITLE
[PROD] Add option of hiding map on emergency page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1397]
## Issue
It is currently possible to hide the figures that are pulled to the emergency page from linked field reports. It would be great to have this as an option also for the map that is generated from the first field report.

## Expected behaviour
A tickebox similar to what is already in place for hiding figures on the emergency page backend:
![image](https://user-images.githubusercontent.com/52411237/87545249-f1fdc680-c6a7-11ea-83a2-0f21e97e5d57.png)

## Related feature
This would be helpful especially if this is a longer hanging fruit and quicker to implement than the updating of the map #1396 

## Is there a workaround?
*e.g. Users can contact IM for a manual update*

**Comment by nanometrenat** [comment]
@batpad is this one ready for QA'  I see there's been a commit - cheers

**Comment by batpad** [comment]
Moving to 4.4. I do not imagine this to be a big lift, apologies for not managing to get to it under 4.3.

**Comment by batpad** [comment]
@kamicut could you please add a brief testing note here? i.e. what is expected to work now?

**Comment by karitotp** [comment]
This is working correctly! 
cc. @batpad
