### ISSUE TITLE
Add 3w link to Go dropdown

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1399]
![image](https://user-images.githubusercontent.com/8285694/87558598-94727580-c6b9-11ea-91a4-8cd817a607c5.png)
Related to [1363](https://github.com/IFRCGo/go-frontend/issues/1363)

The above dropdown could have a "Create 3w activity" link after the links to the Kobo forms. This should lead to a 3w form. However, after the user submits the 3w activity they should be redirected to the country 3w page where they created the activity to. This could reduce the number of duplicates with 3w as the user could see the table of all the 3w:s in the country they added the activity to.

**Comment by frozenhelium** [comment]
@tovari @LukeCaley Would it be a separate page in the GO? or would it be a popup?

Steps required:
- Create a global route to create a new 3W entry. For this we can use following routes 
  - `/three-w/new/` if we will have a global 3W page in the future which will have `/three-w/` as route
  - Else, `/new-three-w/` or `/create-three-w/`
- Use existing 3W form in the new page
- Redirect to the country page (3W tab) for which the entry was just created

**Comment by frozenhelium** [comment]
Now available for testing in the [staging server](https://dsgoproxyapp.azurewebsites.net/three-w/new)

**Comment by tovari** [comment]
Sorry @frozenhelium, the label should be rather "New 3W project". Thanks!
