### ISSUE TITLE
[PROD] Export functionality of all Emergencies

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1412]
Export functionality of all emergencies from the front end, while logged in or not logged in with your personal account is not working: https://go.ifrc.org/emergencies/all

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/1349 for details of various export-related issues

**Comment by GregoryHorvath** [comment]
Before the above PR it took ~1min to get the CSV for me on staging. After deploying the PR it took me ~15sec. This could be easily deployed to production as a separate hotfix, if needed.

cc @batpad checked the before-and-after CSVs with `diff`, there was no difference.

**Comment by batpad** [comment]
@GregoryHorvath the PR looks great to me. Let's not do this hotfix late on a Friday, but let's have it on staging and consider deploying a hotfix on Monday?

I do feel that this combined with the PR to simplify the fields in the export ( https://github.com/IFRCGo/go-api/pull/762 ) should get us to a much better place with the CSV exports, and at least get them functional again while we figure out further improvements to deal with more data down the line.

**Comment by GregoryHorvath** [comment]
@nanometrenat deployed the latest changes (https://github.com/IFRCGo/go-api/pull/823) to staging, now it takes ~17 sec for me to download all the Emergencies there (before it was ~1 min, then after the first change ~30 sec). Big thanks for @thenav56 for optimizing the query and the education/patience.

cc @batpad (query counts: from ~282 --> ~82 --> ~11) Checked the before/after exports with `diff`, all good.

**Comment by nanometrenat** [comment]
@batpad advises that @karitotp has tested this and that the "before" and "after" are all good.

**Comment by nanometrenat** [comment]
@batpad @GregoryHorvath is this part of https://github.com/IFRCGo/go-frontend/pull/1465 and https://github.com/IFRCGo/go-api/issues/763 or a separate thing?  Thanks

**Comment by batpad** [comment]
So, I would advise that completely fixing `Export All` for Emergencies and Field Reports in a sustainable and future-proof manner likely requires further changes to be able to consider this issue resolved.

The Optimization of queries, some of which are covered under this release in #1465 and in https://github.com/IFRCGo/go-api/issues/763 are one part of improving exports, but longer term, we need to disallow unbounded requests against the API (i.e. requests that can fetch an arbitrarily large number of rows) - but first, we need to ensure that users can still easily get the data that they need exported easily.

We would need to:

 - Optimize DB queries - Close to done, covered in above tickets
 - Reduce the amount of nested data, and return a fixed number of columns on the CSV exports: https://github.com/IFRCGo/go-api/issues/708 
 - Implement filters for exports: https://github.com/IFRCGo/go-frontend/issues/1326, to make it easier for users to grab only the data they are interested in.
 - Enforce pagination in the API - enforce a limit of 500-1000 rows per single request in the API (Ticket pending)
 - Modify frontend Export All button to make multiple paginated requests and download a single CSV for frontend end-users. (Ticket pending)
 - Inform API consumers with examples on how to consume paginated results (we will be following all regular best practices for pagination in the API)
 - If required, temporarily maintain multiple versions of API to support unbounded requests while people move over

It would be great to figure out how we can proritize these tasks - I would strongly recommend enforcing an upper limit on results per page - pagination systems are reasonably well standardized and allowing unbounded requests is untenable for any API system.

If the DB optimization queries seem to fix the CSV exports for now, we could close this ticket, but I would definitely create a master ticket to implement a long-term fix for an "Export All" function.

**Comment by nanometrenat** [comment]
Thanks @batpad, great to have all the elements listed above.  The specific question though was whether the changes in the commit above are included in the current release (as not mentioned in the release request so not sure whether excluded or included).

Agree we need to make a plan and prioritise the elements above (another list of elements mentioned in https://github.com/IFRCGo/go-frontend/issues/1349) so we should also do that!  Thanks

**Comment by GregoryHorvath** [comment]
A partial / temporary fix to this was deployed via https://github.com/IFRCGo/go-api/issues/763 as part of https://github.com/IFRCGo/go-frontend/pull/1465

**Comment by frozenhelium** [comment]
This was also modified similarly to the field-report export. Can be tested from the [staging server](https://ifrc-go-feature-improve-emergency-export.surge.sh/emergencies/all)
