### ISSUE TITLE
Update of About Page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#142]
Hi Anna,

We would require to add the logo of Canadian RC in the "About" page.

Here is the logo...

![canadian_red_cross_logo](https://user-images.githubusercontent.com/23258092/35554531-48e1b896-059c-11e8-89b8-b5bb07ac940b.png)

**Comment by guipizzini** [comment]
@ascalamogna could we do this as a priority, today? Canadian RC is looking at the App and would be good advocacy to have them there :)

**Comment by guipizzini** [comment]
@dereklieu any chance we could update this one please? Thanks

**Comment by LukeCaley** [comment]
@dereklieu Can we re-open this ticket?  I will provide the text by 23 July
