### ISSUE TITLE
[PROD] [STAGING] Duplicate entry for admin1 Sulawesi Tengah, Indonesia

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1424]
## Issue
I ran into this issue while importing admin1 boundaries into the test database I've locally and was able to confirm that it is also the case on staging and production. There are two entries in the district table for the same district in Indonesia.

This happened because the ISO2 and ISO3 is not enforced at the model level. And likely when someone entered they accidentally created duplicates.

```
test=# select id, name, code, country_iso  from api_district where code='ID025';
  id  |      name       | code  | country_iso
------+-----------------+-------+-------------
 3525 | Sulawesi Tengah | ID025 | IDN
 1234 | Sulawesi Tengah | ID025 | ID
```

We should definitely remove the duplicates but now there are a few field reports linked to this `3525` Sulawesi Tengah. So next steps is to figure out what's the best way remap the field reports linked to 3525 to 1234.

```
postgres=> select * from api_fieldreport_districts where district_id = 3525;
  id  | fieldreport_id | district_id 
------+----------------+-------------
 5707 |          12555 |        3525
 5673 |          12564 |        3525
 6158 |          12607 |        3525
```

## Expected behaviour
* There should only be one entry for Sulawesi Tengah

## Severity
* This should never be the case and we should fix it while updating all geo data

## Is there a workaround?
No

**Comment by geohacker** [comment]
cc @batpad @GregoryHorvath

**Comment by geohacker** [comment]
We'll get around this by writing a migration that:
* maps all field reports associated with 3525 to 1234
* And removes 3525 
* sets a max length of 2 on the country_iso field

This will be addressed as part of https://github.com/IFRCGo/go-api/pull/815

**Comment by geohacker** [comment]
cc @guipizzini

**Comment by batpad** [comment]
@geohacker was this done as part of other tickets? If yes, could you reference them and then we can close this?

**Comment by geohacker** [comment]
Yes, good to close!
