### ISSUE TITLE
Add links to country, region for Header in Country and Emergency Page

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1428]
**Please base off branch feature/1382-grid-ui for this:**

**Emergency page:**
The region and country should be mentioned below the heading like here: 
https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417134563

I have the styling and markup for this commented out in the view. Please see the commented block of code below the only h1 tag on the page.

**Country page**
The region should be mentioned below the heading like here:
https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/424788546

I have the styling and markup for this commented out in the view. Please see the commented block of code below the only h1 tag on the page.

**Comment by batpad** [comment]
This is done, referencing master ticket https://github.com/IFRCGo/go-frontend/issues/1382 and closing.
