### ISSUE TITLE
Fixing table title on homepage

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#143]
Hi Derek,

The title of the table, seems to be wrong.

We have now "Ongoing Operatoins (3,053)" but that value, should refer to "Overview of All Operations (3,053)".

Would you agree on this?

<img width="1210" alt="screen shot 2018-01-30 at 12 24 59" src="https://user-images.githubusercontent.com/23258092/35563993-edeb1564-05b8-11e8-9de2-720865f963dd.png">

**Comment by k-som** [comment]
Additionally, the number of operations is incorrect - should be 3058.
