### ISSUE TITLE
Improve performance and reduce data loads on home-page

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#1443]
## Issue
1. Currently there are duplicate requests going out to the API when visiting the home-page because multiple components call the same action.
2. Some of the maps above data-tables get re-rendered whenever the table-page is changed, which largely impacts the render time.

## Expected behaviour
1. Only one request / action should get fired.
2. Maps shouldn't be re-rendered because they show data for all the table records, not just the actual page ones.

## Impact
All users.

## Severity
This should act as a minor/moderate performance and user-experience upgrade.

## Is there a workaround?
No.

**Comment by GregoryHorvath** [comment]
@karitotp On the surge URL above this should be testable.

## Expected
1. The design should look the same as it is on staging for - Home page "ACTIVE OPERATIONS", any Region page "ACTIVE IFRC OPERATIONS" or when you click "View all ..." link at the right side of these titles
2. Same data-sets are present
3. Filters are still working for the map
4. When you switch table-pages below the map the map should stay there and only the table re-render should happen (unlike on staging where both gets redrawn)

Thanks!

**Comment by karitotp** [comment]
> The design should look the same as it is on staging for - Home page "ACTIVE OPERATIONS", any Region page "ACTIVE IFRC OPERATIONS" or when you click "View all ..." link at the right side of these titles

There are some differences in the name of the columns in "Active operations" in home page, same in the table of all operations and the table of "Active ifrc operations" in a region page. 
About the width of the columns in operation table maybe are different to the staging because in some cases the data is appearing in two lines and other just in one line.

![Selection_002](https://user-images.githubusercontent.com/11504548/88299134-a2328700-ccc7-11ea-9387-53ea5ada559c.png)

> Same data-sets are present

:heavy_check_mark: data are same.

> Filters are still working for the map

:heavy_check_mark: filters are working

> When you switch table-pages below the map the map should stay there and only the table re-render should happen (unlike on staging where both gets redrawn)

:heavy_check_mark: only the tables are re-rendered

cc. @GregoryHorvath

**Comment by GregoryHorvath** [comment]
@karitotp Oh sorry I thought I linked the surge URL here as well, glad you found it in the PRs. Surge (test) URL: https://ifrc-go-fix-map-rerender.surge.sh/

Those design changes seem pretty new from today, I merged the changes from `develop` and deployed to the surge URL again, so now they should be identical in design.

**Comment by karitotp** [comment]
@GregoryHorvath, now, the operations table is same to the table in Staging, only the column of "Requested Amount" needs to be aligned to the left as "Disaster type" is.
![Selection_009](https://user-images.githubusercontent.com/11504548/88595034-e2776980-d027-11ea-8a1d-88b68a99585b.png)

**Comment by GregoryHorvath** [comment]
@karitotp Thanks for the recheck, although this difference again should occur only because the surge site doesn't automatically follow the staging changes, and there are again some changes since the last time.

I'd say we're good with this, thanks :+1:, cc @batpad

**Comment by GregoryHorvath** [comment]
Forgot to put this into "Ready for Q&A" but since the above testing succeeded and there are other improvements and changes coming from https://github.com/IFRCGo/go-frontend/issues/1386 there is no further action needed here and closing this.
