### ISSUE TITLE
[PROD] Incorrect districts import

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1445]
## Issue
There are a few districts with no code and incorrect country foriegnkeys. 

```
postgres=> select id, name, country_id from api_district  where code = 'N.A';
  id  |        name         | country_id 
------+---------------------+------------
    3 | Bir Tawil           |        282
    5 | Aksai Chin          |        282
    6 | Clipperton Island   |        282
    7 | Europa Island       |        282
    9 | Hala'ib triangle    |        282
   10 | Ilemi triangle      |        282
   11 | Juan de Nova Island |        282
   12 | Kuril islands       |        282
   14 | Navassa Island      |        282
   17 | Senkaku Islands     |        282
 1019 | United Kingdom      |          3
```

Country ID 282 is Americas Region
Country ID 3 is United Kingdom country

For instance, mapping Aksai Chin as part of Americas Region seems outright incorrect

## Expected behaviour
The districts should be mapped to appropriate country or no country at all when it's territory is under conflict.

## Impact
This will produce incorrect map behaviour

cc @batpad @GregoryHorvath @teklal

**Comment by geohacker** [comment]
I should also point out that the above districts all have code `N.A`.

**Comment by geohacker** [comment]
cc @guipizzini

**Comment by jhenshall** [comment]
This will be fixed after the upcoming changes - the missing countries will be added, so I can go in and link districts to the countries for these disputed areas.

**Comment by jhenshall** [comment]
Disputed territories have now been added to the countries table and these districts updated in admin to link to the country of same name. e.g. the district Ilemi triangle is the sole 'district' in the 'country' Ilemi triangle.
