### ISSUE TITLE
[PROD] Duplicate code for two different districts in Poland

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1446]
## Issue
Came across two different districts in Poland with the same code, PL009. This is also the case in the shapefile.
![image](https://user-images.githubusercontent.com/371666/88288035-cfefee00-cd10-11ea-9ebe-30da01fa12f8.png)
_districts in yellow_

```
  id  |     name     | country_iso | code
------+--------------+-------------+-------
 2380 | Podkarpackie | PL          | PL009
 2381 | Podlaskie    | PL          | PL009
```

## Impact
Potentially inconsistent database entries

cc @batpad @teklal @GregoryHorvath

**Comment by geohacker** [comment]
cc @guipizzini

**Comment by jhenshall** [comment]
Podkarpackie changed to PL016 taken from updated ICRC shapefile.
