### ISSUE TITLE
[PROD] Saint Martin district in France has code 'f'

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1447]
## Issue
Saint Martin district has code `f` in the shapefile. This code should be something like country_iso2 combined with a number. 

![image](https://user-images.githubusercontent.com/371666/88290047-c87e1400-cd13-11ea-96f5-ce3d1f64a57e.png)

cc @batpad @teklal @GregoryHorvath

**Comment by geohacker** [comment]
cc @guipizzini

**Comment by jhenshall** [comment]
This has been updated to FR032 inline with latest ICRC shapefile.
