### ISSUE TITLE
YU Feedback for UI post Grid Update

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1448]
1 - Thanks for making Search bigger. Just a note though, this wasn't approved yet from the team. @mmusori Did you have any thoughts on this or we wait for Luke?
2 - In the table under the map (across), can you make Requested Amount left aligned.
3 - Also, there is a bit of a funky thing happening with the map table on the regions (e.g. on Africa). When you click on page numbers, it jumps below the table and on page 2 Funding title wraps (the sorting icon). Can we have it not wrap?
4 - Regions - recent emergencies table - Left aligned requested amount and #affected
5 - Emergency map - can you make legend styling consistent with home? I know we are not touching the map now, just to make consistent whatever styling we implement now.
6 - Create a Report dropdown - the text is a bit lighter in the design (Poppins-Regular).
7 - You are probably still working on Specific Emergency pages. Just a comment on the header: the grey should end after key numbers and the country links should be closer to the title. Also, in Natalie's Covid emergency the key number is missing text. Is that manual? When clicked on Aland-Bio-Test3, the site breaks.
8 - Not many comments for country pages besides what's above, as I think you are still working on it. We are also working now hard to finish up all the tabs for you to implement. Lastly, I still owe you the field report dropdown solution from Emergency pages.
9. One more thing, we updated the top nav dropdown style (for languages) in Zeplin. It's on the same section as the dropdown for Create a Field Report. Let us know if any questions.

**Comment by imohkay** [comment]
@maisa-yu Sorry, but where is Aland-Bio-Test3? (See point 7 in the above description: "When clicked on Aland-Bio-Test3, the site breaks.")
I'm trying to tag Mariam, but she's not showing up in the people search right now, for some reason.

**Comment by imohkay** [comment]
@batpad  See point 3 of the issue description. This jumping of content during pagination seems to be a standard issue. Is there a way out? I'm guessing it happens because the height of the content changes while the new content is being fetched?

**Comment by mariam-yu** [comment]
> @maisa-yu Sorry, but where is Aland-Bio-Test3? (See point 7 in the above description: "When clicked on Aland-Bio-Test3, the site breaks.")
> I'm trying to tag Mariam, but she's not showing up in the people search right now, for some reason.

@imohkay Not sure why you can't tag me :S This was more a comment about one of the Highlighted Ops on the Home screen (the 3rd one in the top row). When I click on it, the site crashed (for me anyway).

**Comment by imohkay** [comment]
@mariam-yu  Now I can tag you again. Yesterday was just an anomaly, I think. You're right about the specific Highlighted Ops. I'll make a ticket and assign to a developer...

**Comment by batpad** [comment]
> This was more a comment about one of the Highlighted Ops on the Home screen (the 3rd one in the top row). When I click on it, the site crashed (for me anyway).

Thank you so much for this catch, @mariam-yu . Fixed with #1452 . This should now work on staging.

Just a small note: This was crashing when the country associated with the emergency did not have a "Region" associated. This is likely a data anomaly that will hopefully be fixed with our larger push to fixing our spatial data, for now am just not showing the region identifier and link below the page title if the country associated with the emergency does not have a region in the data for some reason.

**Comment by mariam-yu** [comment]
@batpad Great! I thought there must be an anomaly. Thanks guys!

**Comment by batpad** [comment]
@imohkay I've merged the PR you had to address these changes. Could you provide a summary of the fixes so that @mariam-yu can re-look and confirm if things have been fixed? I pushed a fix for the problem causing the Emergency page to crash if there was no region for the associated country.

**Comment by imohkay** [comment]
@mariam-yu 

All tables should have Requested Amount and Funding titles left aligned. Hopefully, almost all the table titles won't wrap now, but it can be a bit delicate.

Emergency map styling now consistent with home, and I've added a bit of padding between the items under the "Key" section

All the dropdowns in the top nav (Lang, Account and Report) should have similar styling, but unfortunately, the Lang dropdown is hidden for now.

The specific emergency pages I will tackle fully once the final designs are in.

**Comment by imohkay** [comment]
> @batpad See point 3 of the issue description. This jumping of content during pagination seems to be a standard issue. Is there a way out? I'm guessing it happens because the height of the content changes while the new content is being fetched?

@batpad need me to move this into a separate ticket?

**Comment by mariam-yu** [comment]
@imohkay Great! Thanks for doing the changes so quickly. I glance through it, and some minor things:
1 - On Home the first View all operations is still smaller in size than the rest. So some disconnect with the total CSS.
2 - Tables look great! Just a small thing - on Regions when clicking through the table pagination, it jumps under the table but should jump to the top of the table if possible.
3 - No comments for specific emergency before designs are final. Let's tackle it by itself.
4 - Same for country. Just, since you are updating the headers, the grey header looks wider. If you could check in Zeplin and tighten it, but otherwise, let's tackle that separately too.
5 - Another small thing to change the title of the page from Go to GO. Not sure if this goes to someone else, but want to make sure we don't forget this.

Great job!

**Comment by mariam-yu** [comment]
@batpad As you mentioned, here are some comments for a general clean up of em. and country pages before the push:
1 - Hiding the tabs that have no content, but I assume it's probably a bigger thing. So, your call.
2 - https://dsgoproxyapp.azurewebsites.net/emergencies/3789#details On this page, the map section seems a bit off, doesn't have a title, and the export button is a fit floating.
3 - Show more/less on text box should show only when text is cropped not to show always. (Also, not sure if it's for this release, your call).
4 - On this page, the Alerts table looks funky: https://dsgoproxyapp.azurewebsites.net/emergencies/3786#details

I think that's it, everything else needs a more thorough work in the next phase.

**Comment by imohkay** [comment]
> @imohkay Great! Thanks for doing the changes so quickly. I glance through it, and some minor things:
> 1 - On Home the first View all operations is still smaller in size than the rest. So some disconnect with the total CSS.
> 2 - Tables look great! Just a small thing - on Regions when clicking through the table pagination, it jumps under the table but should jump to the top of the table if possible.
> 3 - No comments for specific emergency before designs are final. Let's tackle it by itself.
> 4 - Same for country. Just, since you are updating the headers, the grey header looks wider. If you could check in Zeplin and tighten it, but otherwise, let's tackle that separately too.
> 5 - Another small thing to change the title of the page from Go to GO. Not sure if this goes to someone else, but want to make sure we don't forget this.
> 
> Great job!

@mariam-yu 
1. Home 'View all operations' should be fixed now on staging
2. Table jumping pagination issue assigned to @batpad here #1458
3. Emergency page: TBD
4. Could you let me know how the Country header looks wider? I can't seem to spot exactly where...
5. Go in uppercase has been assigned to @batpad here: #1423

**Comment by mariam-yu** [comment]
@imohkay for #4 was my bubu - I meant the height and spacing between the elements. The width is perfect. Thank you!!!!
