### ISSUE TITLE
[PROD] User Guide and Admin Guide pdf documents not available in French

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1450]
## Issue
https://go.ifrc.org/about has the User Guide and Admin Guide available in 4 languages.  At least, it implies it does... but the french titles are just placeholders and don't link anywhere.

FR

- Guides d'Utilisation
- Guides Administratifs

We need to get them translated and then ask a dev to add them to the Resources page to support our French-speaking users.  This comment on another ticket implies the translations are "in progress" but I'm not sure by whom or where they are at.  https://github.com/IFRCGo/go-frontend/issues/1094#issuecomment-623447962

- [ ] translate User Guide
- [ ] translate Admin Guide
- [ ] make both available on site

## Related feature
Other tickets and PRs re User Guides and resources include
https://github.com/IFRCGo/go-frontend/issues/1094#issuecomment-623447962
https://github.com/IFRCGo/go-frontend/issues/1069
https://github.com/IFRCGo/go-frontend/issues/1094
https://github.com/IFRCGo/go-frontend/pull/1341

## Impact
French-speaking users

**Comment by tovari** [comment]
Closing this as opened a new one for all user guide updates:
https://github.com/IFRCGo/go-frontend/issues/1658
