### ISSUE TITLE
Conditionally show "Show More" and "Show Less" only if there is extra content

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1459]
Right now, the Show More toggle shows up all the time.
Example: See Situational Overview here: https://dsgoproxyapp.azurewebsites.net/emergencies/3789#details:

Mariam has noticed this here.

**Comment by nanometrenat** [comment]
Also in Surge Alerts at bottom of the home page.
I have added a couple of alerts there and the column width jumps around when I hit show more show less because of the ...s being added/removed to the item with no additional content
@mariam-yu

**Comment by mariam-yu** [comment]
> Also in Surge Alerts at bottom of the home page.
> I have added a couple of alerts there and the column width jumps around when I hit show more show less because of the ...s being added/removed to the item with no additional content
> @mariam-yu

**Comment by mariam-yu** [comment]
@imohkay @nanometrenat Closed the issue accidentally :PP

The jumping thing happens as the text goes to the next line. But yes, once the show more/less is fixed, it should fix it here as well. Thanks!

**Comment by nanometrenat** [comment]
@LukeCaley FYI this is a "jumping around" ticket that has been logged but is not currently in the queue for dev action.
https://ifrc-go-release-v4-3-11.surge.sh/emergencies/3786#details (Alerts)
