### ISSUE TITLE
Homepage table - incorrect 'disaster type' names

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#146]
I've looked through active emergency appeals and some older records:
* no 'Population Movement', 'Cyclone', 'Epidemic' name has been used - 'Other' used instead,
* 'Flood' is sometimes written as 'Flood', 'Floods', '**Food**' or 'Other',
* 'Food' needs to be changed to 'Food Insecurity' (sometimes it's classified as 'Other' - pic below).

![table](https://user-images.githubusercontent.com/25579864/35570898-d8778448-05d0-11e8-98ab-05885f6ab807.jpg)

**Comment by k-som** [comment]
Edit: same for the map (@guipizzini)

**Comment by guipizzini** [comment]
Can we prioritise this one, @dereklieu ?

**Comment by guipizzini** [comment]
This one is important to have on phase 1.0

**Comment by dereklieu** [comment]
This will be included in the next db re-up.

**Comment by dereklieu** [comment]
This is fixed and deployed to dev.

<img width="1170" alt="screen shot 2018-02-07 at 6 40 55 pm" src="https://user-images.githubusercontent.com/1590802/35947570-7a483e78-0c36-11e8-85cc-14d185af1945.png">

I detected a few one-off disaster types from the appeals API that don't have a translation key in GO, but I don't think these are significant enough to cause an issue (and would get assigned to Other).
