### ISSUE TITLE
Map needs a title on Specific Emergency Page

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1460]
Unsure what this title is supposed to be.

Mariam has noticed this while doing an audit. See this page, for example:
https://dsgoproxyapp.azurewebsites.net/emergencies/3789#details

**Comment by batpad** [comment]
I am also unsure what this title is supposed to be. It seems like this doesn't have a title as such, though the Export button to the top right I think has always looked a bit weird.

@mariam-yu do you know if there should be a title above the map there, and if yes, what that should be? Happy to also be pointed to wireframes or so that clarify this. Thanks!

**Comment by mariam-yu** [comment]
@batpad So the lingo needs a proper cleanup on which I'm working now, but here are the wires: https://invis.io/36XXV6AT2YE#/412675366_4-3-1_GO_Specific-Emergency_Epi

Basically, the map structure should be consistent throughout. We can call it for now Affected Regions (as it's on the legend of the map as well).

**Comment by batpad** [comment]
@imohkay so we'd need to add a title / heading saying `Affected Regions` above the map on the Emergency page (for emergencies that have a map).

The map is being rendered here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/emergency.js#L927, so I guess it should hopefully be possible to stick it inside https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/emergency.js#L773 to add some sort of heading element above the EmergencyMap component? 

Alternatively, perhaps best is to make the heading part of the Emergency Map component: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/map/emergency-map.js#L119

@imohkay Assigning back to you, let me know you're prefer I stick the heading in somewhere and hand back to you for styling.

**Comment by batpad** [comment]
Title was added to the map view on the emergency page. Master ticket #1325
