### ISSUE TITLE
[PROD] 'countries' that are missing compared to admin0 shapefile

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1464]
Here's a list of all 'countries' that are missing in production compared to the admin0 icrc shapefile.
```
as American Samoa
bv Bouvet Island
io British Indian Ocean Territory
vg British Virgin Islands
ky Cayman Islands
cx Christmas Island
cc Cocos (Keeling) Islands
fk Falkland Islands (Malvinas)
fo Faroe Islands
gl Greenland
gu Guam
gg Guernsey
hm Heard Island and McDonald Islands
im Isle of Man
je Jersey
xz Kosovo
ms Montserrat
nf Norfolk Island
mp Northern Mariana Islands
gs South Georgia and the South Sandwich Island
tk Tokelau
tc Turks and Caicos islands
vi United States Virgin Islands
```

@teklal @batpad @guipizzini -- I'm guessing these should be imported as countries (record_type = 1). But I'll hold off until we confirm.

**Comment by batpad** [comment]
As long as we have this list to serve as documentation of what countries have been added during this import process, I'm okay with this. My hunch is that ideally this is something that should be looked at in greater detail to ensure any weird edge cases are covered. I think the question would be if there's other reasons these are not in the current list of "countries" in the backend / if for some reason they are not meant to show up in country drop-downs, etc.

@geohacker do these countries in the shape-file all have a reference to the Region they belong to?

**Comment by geohacker** [comment]
@batpad 👍  agree this needs to thought a bit more before importing. The scripts won't auto-import anything.
They all have a region column in the shapefile and can be mapped correctly based on what regions are available in the database.

**Comment by nanometrenat** [comment]
None of these have RCRC  national societies so should not appear in any dropdowns relating to IFRC countries.  They also should not appear on any "region" pages on GO (i.e. should not appear on https://go.ifrc.org/regions/2#operations etc.)

xref https://github.com/IFRCGo/go-frontend/issues/1276#issuecomment-651592294 and various others.

**Comment by nanometrenat** [comment]
Please also always xref any Geospatial tickets back to the master ticket https://github.com/IFRCGo/go-frontend/issues/938 cheers

**Comment by geohacker** [comment]
> None of these have RCRC national societies so should not appear in any dropdowns relating to IFRC countries.

@nanometrenat this is helpful, thank you. Some followup questions:

* Can you tell me where this list of RCRC national societies are?  That will allow me to further refine these import suggestions. 
* Also, if they shouldn't appear in the dropdowns related to IFRC countries or region pages then should these not be in the database? 
* Is there a different version of IFRC Go shapefile than the ICRC one?

**Comment by nanometrenat** [comment]
> > None of these have RCRC national societies so should not appear in any dropdowns relating to IFRC countries.
> 
> @nanometrenat this is helpful, thank you. Some followup questions:
> 
> * Can you tell me where this list of RCRC national societies are?  That will allow me to further refine these import suggestions.
> * Also, if they shouldn't appear in the dropdowns related to IFRC countries or region pages then should these not be in the database?
> * Is there a different version of IFRC Go shapefile than the ICRC one?

Hi, basically if there is a "Society Name" against the country then there is a National Society.  There are a few "quirks" whereby there are some countries' NSs have a special status (e.g. Eritrea) so should in the ideal world appear in some places but not others (based on governance).  But on the whole the above holds true.

If you have a read of the other geospatial tickets then you can see that we've worked through a bunch of the exceptions (either recently or back when Elsa was in the team) - e.g. https://github.com/IFRCGo/go-frontend/issues/619 talks about how British Virgin Islands should "sit" as part of the UK.

This is exactly why we have acknowledged the need for a lot of geospatial analysis work to make sure everything aligns, and we have a GIS analyst coming onboard in early August - who will be able to be point-person from then, but in the meanwhile the current IM team remains available for questions!

Re shapefiles, I don't know I'm afraid.  But _lists_ I can help with! :)  Cheeers

**Comment by teklal** [comment]
> Is there a different version of IFRC Go shapefile than the ICRC one?

As far as I'm aware we don't have any other (version of) IFRC GO shapefiles than the ICRC one. Emphasis on "as far as I'm aware".

**Comment by guipizzini** [comment]
The shapefiles to be used are the ICRC ones. Nothing else should be used. Please note that ICRC boundaries are available only for ADMIN 0 and ADMIN 1, no ADMIN 2 boundaries available in ICRC datasets...

List of NS and associated countries shared on MS Teams.

**Comment by jhenshall** [comment]
Decided to leave these 'countries' out of the GO database for now to focus on migrating what we have from frontend to backend. This will be considered as part of wider geodata handling after the geo api integration #1534

**Comment by jhenshall** [comment]
Hey @geohacker @batpad @GregoryHorvath - reconsidering the decision above to not include the missing countries and would be great to get your input for what's best for the immediate release vs longer term.

I'm conscious of the different ways that overseas territories are handled (e.g. Saint Helena is in the existing GO database but Montserrat is not - both are Overseas Territories of UK and run as overseas branches of the British Red Cross). Wondering whether it's best to add these missing countries and at least ensure that all countries from the ICRC dataset are handled equally?

As mentioned in discussions above, there are loads more edge cases and this needs more thought and will definitely be part of the longer term changes - but should we start from a place where all countries from the ICRC shapefile are in the GO database? Or we except it's not perfect for now and come back to it for future changes and initially suggested.

Also note that all countries in this list have the `independent` field as `FALSE` so they will not appear on the dropdown list for field reports etc. Cheers!

**Comment by geohacker** [comment]
@jhenshall it's ok if we want to import the missing countries into the database right now, but I'm less clear on what problem it would solve for the users immediately. Especially that they won't appear in the field report dropdowns. Is the goal that the overseas territories show up as districts under UK?

While making the db consistent with the ICRC shapefile is a good idea I don't know if merely importing missing countries would be enough.

**Comment by jhenshall** [comment]
Thanks @geohacker. Makes sense. Ok, let's stick with the original plan and leave these for now with a view to revisiting this as part of the bigger geo-data review. Cheers!

**Comment by jhenshall** [comment]
@geohacker @batpad - can we prevent non-independent states from appearing in search or having a country page created? Particularly conscious of the numerous countries we are adding with the sole function of being in the Mapbox tileset e.g. disputed territories. They will have no other function on the site!

**Comment by jhenshall** [comment]
Reopening - they have been added to staging but not yet prod

**Comment by jhenshall** [comment]
All added in 4.4 March release! GO now matches ICRC shapefile - was essential for building the Mapbox layers with MTS.
