### ISSUE TITLE
[Staging] Export Map styling broken on staging

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1466]
## Issue

The styling in the image exported in the Export Map feature is broken on staging.

## URL

https://dsgoproxyapp.azurewebsites.net/emergencies/3786#details

## Steps to reproduce

Click Export Map button on top-right of the map. See generated image. The "Legend" is showing up unstyled on the exported map.

*If applicable, add screenshots to help explain your problem.*

![2020-07-27-Flood-Afghanistan](https://user-images.githubusercontent.com/72280/88557317-b23fc300-d047-11ea-9427-72c50240dc38.png)

## Expected behaviour

The Exported Map should look like on-screen, OR we hide the legend.

## Criticality/Urgency

This is a blocker for release.

@imohkay my hunch is this should be relatively straightforward, there is a bit of weirdness when the "snapshot" is created to make the downloadable png. We will just need to make sure the styling rules are consistent there. We can look at this together.

**Comment by batpad** [comment]
Comparison with map on production: https://go.ifrc.org/emergencies/4543#details

**Comment by batpad** [comment]
So, looking at this further, this seems very inconsistent to reproduce.

It seems to always work fine in Chrome, and in Firefox it seems to mostly always work, but sometimes be broken. Am going to remove the `Must Fix` label as it seems to only break in some edge cases and may not actually be a regression.

@karitotp can you please pay special attention to testing the Export Map functionality on staging and let us know what you find? Thanks!

**Comment by karitotp** [comment]
Hi @batpad,
I took a look exporting maps from different emergencies in chrome browser and the exported map looks good in all cases that I exported.

What I found about the map rendering in the emergency details are:
- Not in all emergency details there is a map (Do not know if this is normal) https://dsgoproxyapp.azurewebsites.net/emergencies/4012#details
- In the emergencies in Peru, the map does not show the entire map of the country and it always shows the same part of the map https://dsgoproxyapp.azurewebsites.net/emergencies/4052#details

![Screenshot from 2020-07-27 13-21-35](https://user-images.githubusercontent.com/11504548/88577156-28263900-d00c-11ea-95f1-3fbc68a79a8b.png)

**Comment by batpad** [comment]
The styling of the export map layout was fixed and is in production. Closing here.
