### ISSUE TITLE
[Staging] Icons missing

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1468]
https://paper.dropbox.com/doc/IFRC-GO-TEST-07-27-R5uoDCI3YpCdQNrdaeA21

All the icons referenced in this document appear locally while testing, so there may be some issues with paths?

**Comment by batpad** [comment]
This was a bit strange, seems like a hiccup with the deploy process. Redeploying has fixed the icons now.

**Comment by karitotp** [comment]
All icons appear on the page now!

**Comment by nanometrenat** [comment]
Not sure if this is related to the one I just logged https://github.com/IFRCGo/go-frontend/issues/1479 ?

**Comment by LukeCaley** [comment]
@imohkay @batpad - has the root cause been identified for this bug?

**Comment by nanometrenat** [comment]
Closing based on Sanjay's advising that it looks to be a deploy issue, but will reopen if this happens again.
