### ISSUE TITLE
Edit action button height taller than other buttons on Specific Emergency Page

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1469]

**Comment by imohkay** [comment]
@karitotp The Edit Action button height was a bit taller than the other buttons, and should now be fixed here to be the same height as the other buttons: [https://ifrc-go-release-v4-3-11.surge.sh/](https://ifrc-go-release-v4-3-11.surge.sh/)
Could you test that this works?

**Comment by karitotp** [comment]
All buttons are at the same height:

![Screenshot from 2020-08-04 12-29-03](https://user-images.githubusercontent.com/11504548/89325227-1e28b980-d64e-11ea-980c-2b701beb29eb.png)

**Comment by nanometrenat** [comment]
@LukeCaley @batpad this ticket isn't in 4.3 or release notes pull request but I'm guessing is going in this release?

**Comment by nanometrenat** [comment]
Problem in staging, rectified in staging, being released today so closing.
