### ISSUE TITLE
Unfollow Button span not clickable on Account Page

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1471]
Only the surrounding area (padding) of the button is clickable.

**Comment by imohkay** [comment]
I believe this issue is due to the span being automatically added to the button as a child (via the Translation)

**Comment by imohkay** [comment]
@karitotp The Unfollow button is now fully clickable on the account and should work properly.
Could you test here? https://ifrc-go-release-v4-3-11.surge.sh/

**Comment by karitotp** [comment]
:heavy_check_mark: The button is fully clickable!

**Comment by nanometrenat** [comment]
@LukeCaley @batpad this ticket isn't in 4.3 or release notes pull request but I'm guessing is going in this release?
Adding to 4.3 Ready for QA now

**Comment by nanometrenat** [comment]
Problem in staging, rectified in staging, being released today so closing.
