### ISSUE TITLE
[Staging] Format/styling of new UI, for the standard IFRC laptop resolution

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1478]
## Issue
Speaking with @mariam-yu there are some strange things visually with my resolution - I have an IFRC standard laptop currently set to 1920x1080.

https://dsgoproxyapp.azurewebsites.net/emergencies - Key figs look scrunched according to Mariam
https://dsgoproxyapp.azurewebsites.net/ - COVID highlighted operation 450,000,000 goes over the box

Apparently both of these are to do with break points.  Can you please take a look?

## Related feature
*Please cross-reference the build item to which this relates, if known*

![image](https://user-images.githubusercontent.com/33625192/88807482-11214b80-d1b2-11ea-81dc-3d644fdb1d3f.png)
![image](https://user-images.githubusercontent.com/33625192/88807796-75440f80-d1b2-11ea-81f6-fdcc537c834b.png)

**Comment by nanometrenat** [comment]
Adding another screenshot which Mariam tells me is again to do with breakpoints

- key figs on deployments page - going up and down in terms of text alignment baselines
![image](https://user-images.githubusercontent.com/33625192/88817761-32883480-d1be-11ea-9e21-63ecc5cc7c6c.png)

**Comment by imohkay** [comment]
@nanometrenat Hey Natalie, I'm unable to replicate this on a 1920x1080 screen. I suspect your laptop may have a high pixel density screen. Could you let me know what model it is or whether the screen is high pixel dense? Thank you.

**Comment by nanometrenat** [comment]
Lenovo X270 (Lucia) - 1366x768 100% - misaligned
Lenovo T460s (Natalie) - 1920 x1080 150% - misaligned (screenshot below)
Lenovo X250 (Benjamin) - 1366x768 100% - misaligned
Lenovo T490s (Daniel) - not sure of res - misaligned

Tekla - "normal IFRC machine" - aligned
Tekla - outboard screen - aligned
Lauri - Lenovo Yoga - aligned

Hope that helps, many cheers

![image](https://user-images.githubusercontent.com/33625192/89034668-bc104180-d339-11ea-84c7-fccb69fe5c33.png)

**Comment by imohkay** [comment]
@nanometrenat Are we okay with having 2 highlighted operations in a row on screen sizes below 1400 px? (Right now there are three). Most desktops would still see 3. The new designs have additional horizontal padding, which consumes some of the space that was there previously.

**Comment by nanometrenat** [comment]
That is a question for @mariam-yu and @LukeCaley rather than me.
However I personally think it would look weird having only two highlighted operations when on a laptop screen (know a mobile screen needs to go rows down but a laptop theoretically should show most stuff as standard).  Bearing in mind that users in the field (i.e. on emergency operations) will often be using laptops only rather than big screens - and at the moment with everyone working from home there is also lots of laptop use even at HQ.   And given this problem affects multiple different IFRC computers (and therefore users) my personal preference would be to make 3 in a row work.  Even if it involves removing some padding instead.
Over to the experts though.

**Comment by nanometrenat** [comment]
Or could of course just leave exactly as-is and accept the above overlap/misalignment things as being OK!  Again, over to Mariam and Luke.

**Comment by imohkay** [comment]
@maisa-yu Sorry, could you ping Mariam? On certain tickets, I can't seem to ping her.
Mariam, for the key numbers, I could just reduce the size of the number on certain screen sizes. Would that work?
The same issue is present on the current production site, but it is less pronounced since the numbers are less bold and the 100px padding isn't there on both sides...

**Comment by mariam-yu** [comment]
@imohkay Sure let's try that. Can you please send some screenshots when done? We can review together. By the way, I guess as I was tagged early on, I still get notifications when anything is posted :)

**Comment by imohkay** [comment]
![go-hi-ops](https://user-images.githubusercontent.com/1667470/89116718-0ec23880-d4b5-11ea-9a3d-380c248db00d.png)

Something like this? @mariam-yu and I can tag you again :D

**Comment by mariam-yu** [comment]
@imohkay This should work. Thank you!

**Comment by imohkay** [comment]
@mariam-yu cool. will implement so screen sizes above 1300px see the larger size. On anything smaller, I'll go with a smaller font size since there are cases where the number overflows the container.

**Comment by batpad** [comment]
These fixes are deployed to the testing Surge URL for the Release branch: https://ifrc-go-release-v4-3-11.surge.sh/

**Comment by imohkay** [comment]
@karitotp on [https://ifrc-go-release-v4-3-11.surge.sh/](https://ifrc-go-release-v4-3-11.surge.sh/), could you please check the following:
1. The key numbers on Deployments and Emergencies: Natalie found them looking scrunched up on certain screen sizes, and there was an alignment issue on key numbers for Deployments. (You can see her screenshots at the top of the ticket). Could you check these have been fixed?

2. For Highlighted Operations, on smaller screen sizes, the large number in bold should not overlap the column

Thank you :)

**Comment by karitotp** [comment]
Hi @imohkay, here my findings of the reviewing:

> The key numbers on Deployments and Emergencies: Natalie found them looking scrunched up on certain screen sizes, and there was an alignment issue on key numbers for Deployments. (You can see her screenshots at the top of the ticket). Could you check these have been fixed?

These were fixed and they looks good now!

> For Highlighted Operations, on smaller screen sizes, the large number in bold should not overlap the column

This looks good, but when I reduce the screen size, the number is still over the box.

![Screenshot from 2020-08-04 12-16-02](https://user-images.githubusercontent.com/11504548/89324238-95f5e480-d64c-11ea-9a20-0c007fa2320b.png)

**Comment by batpad** [comment]
@imohkay are you able to take a look or comment on this?

**Comment by LukeCaley** [comment]
Has this been addressed now @imohkay @batpad ?

**Comment by batpad** [comment]
I believe these have all been addressed, at least all the instances of things "breaking". @nanometrenat can you confirm and if there are further design tweaks that would be helpful at this particular resolution, have new tickets? Thank you!

**Comment by nanometrenat** [comment]
I haven't clicked through the whole site but the main issues with laptop resolution have been addressed so I will close, and log new tickets as required.  Cheers
