### ISSUE TITLE
[Staging] Lots of 304 errors retrieving images when loading homepage

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1479]
## Issue
Not sure how much of an issue this is but would need a dev to advise:
![image](https://user-images.githubusercontent.com/33625192/88844693-5447e280-d1e3-11ea-8321-2990f94c00fa.png)

## URL
https://dsgoproxyapp.azurewebsites.net/

**Comment by nanometrenat** [comment]
304 = the condition specified using http conditional header(s) is not met

**Comment by nanometrenat** [comment]
Think this is actually fine - 304 for the svgs being "not modified" - and doesn't seem to be causing any functional problems so closing.

**Comment by nanometrenat** [comment]
Reopening - whilst I was getting 304s not modified earlier, now I am getting 304s re condition specified......not met... again.

I don't know whether to worry - @batpad can you please advise?  Noting also that the below screenshot is on a page that is not loading fully (3 loading dots there forever, as per https://github.com/IFRCGo/go-frontend/issues/1491)

https://dsgoproxyapp.azurewebsites.net/emergencies/3276#details
![image](https://user-images.githubusercontent.com/33625192/89352209-e48a9980-d6b3-11ea-9ea1-0d9b76343046.png)

**Comment by LukeCaley** [comment]
@batpad @GregoryHorvath is this currently seen as in scope for 4.3?  If not, please elaborate the desired way forward and time estimate for future prioritisation

**Comment by batpad** [comment]
This seems to have been an intermittent issue and is not causing any problems. I believe we can close this.

**Comment by nanometrenat** [comment]
@batpad FYI this is still happening as at today so I don't think it's as intermittent as all that.  The google thinks it's something to do with Azure blob storage.  But if you think it is a test artefact in staging rather than something that needs attention then please do close, thanks

**Comment by batpad** [comment]
This *looks* to me like it's the assets being served with the wrong mime-types - i.e. `text/plain` instead of image/svg or image/png or whatever a more appropriate mime-type maybe.

I believe if this is not causing image loading issues in any of our supported browsers, this is fine to ignore.

As it would be good to eventually fix the mime-types on the server as good practice, I'm leaving the issue open, but adding a `backlog` label.

**Comment by batpad** [comment]
Removing this from the projects boards and leaving the `backlog` label on. Nothing actionable here for now, I believe.
