### ISSUE TITLE
Homepage map - 'People Affected' to 'People Targeted'

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#148]
Needs to be changed:
* 'People Affected' to 'People Targeted',
* 'Target People' to 'People Targeted'.

Thanks!

![map](https://user-images.githubusercontent.com/25579864/35572069-15889978-05d4-11e8-8c97-dcc28943dd4a.jpg)

**Comment by guipizzini** [comment]
<img width="1231" alt="screen shot 2018-01-30 at 15 46 57" src="https://user-images.githubusercontent.com/23258092/35572403-d599185a-05d4-11e8-8a14-da82ef03e805.png">

1. Please check that all country names are showing up correctly. The example of "La Reunion" is that it shows up as "null" in the infobox.

2. I think that the data related to "Epidemic" in the bar chart, ends up in the category called "Other". Let's check this in details, please.

**Comment by k-som** [comment]
@guipizzini ad.2 - I've submitted incorrect disaster type names as a separate issue (#146), guess it's all connected.
