### ISSUE TITLE
[Staging] Column widths of Deployed Personnel mean some NS names take 4 lines

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1480]
## Issue
Names unnecessarily wide so other columns squished @mariam-yu 
![image](https://user-images.githubusercontent.com/33625192/88845789-fa481c80-d1e4-11ea-899c-6f03778c1fe5.png)

## URL
https://dsgoproxyapp.azurewebsites.net/deployments

**Comment by mariam-yu** [comment]
> ## Issue
> Names unnecessarily wide so other columns squished @mariam-yu
> ![image](https://user-images.githubusercontent.com/33625192/88845789-fa481c80-d1e4-11ea-899c-6f03778c1fe5.png)
> 
> ## URL
> https://dsgoproxyapp.azurewebsites.net/deployments

Thanks @nanometrenat 

@imohkay there are some difficulties with the table column widths. Some that have longer text get smooshed and others have more space. Is there a way to organize it a bit more? Let me know if you want to chat about this.

**Comment by imohkay** [comment]
@nanometrenat @mariam-yu We may have to customise widths per table... I was wondering if that could be avoided, but I guess it can't. I'll look into it.

**Comment by nanometrenat** [comment]
@mariam-yu is there still work required on this?

**Comment by mariam-yu** [comment]
Thanks @nanometrenat for highlighting this. Let's leave this open for now. I connected with Karen who was still working on this. @imohkay any updates? Thank you!!

**Comment by nanometrenat** [comment]
@mariam-yu reason for asking if work required was because I can see there was a commit a couple of weeks ago and also I can see that it's no longer 4 lines on my screen!  But if still ongoing work despite that then great to leave open.

**Comment by LukeCaley** [comment]
@imohkay @batpad to update on status

**Comment by batpad** [comment]
I believe this is resolved. @mariam-yu to confirm.

**Comment by mariam-yu** [comment]
Thanks @batpad looks good on my screen. I especially like that you made it responsive so it doesn't cut of the table. The responsive needs more work (later on), but so far the tables look good for me. @nanometrenat Do you mind glancing through on your resolution? Thanks!

**Comment by nanometrenat** [comment]
@mariam-yu this is how it looks on my resolution now (i.e. the equivalent of the screenshot in the original ticket above):
![image](https://user-images.githubusercontent.com/33625192/90637608-8241a500-e22c-11ea-9030-98712bd883d5.png)

So NS names now 3 lines rather than 4.  Over to you @mariam-yu to sign off if you're happy!  Cheers all

**Comment by mariam-yu** [comment]
@nanometrenat Thanks for checking so quickly. I think looks much neater. @batpad Good to go from me.

**Comment by nanometrenat** [comment]
Therefore closing as this change is already in Production
