### ISSUE TITLE
[Staging] Strangeness with pages not loading data even when user seems to be logged in properly

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1481]
## Issue
As per thread in Teams I've been having some strangeness in staging.  Below is as at yesterday afternoon:

> it seems like it is not "holding" my login fully.  I was logged in as the ifrcgo-testuser (like usual) and was clicking round happily.  Then when I went to Deployments screen [which requires the user to be logged in] no content loaded at all - just the header.  Same thing when I went to Account/PER Forms https://dsgoproxyapp.azurewebsites.net/account#per-forms  But when I was in Account/Account all the usual things loaded.  And the whole time I had my username in top right (not the "log in" link).

> Closed and reopened browser and when I went to deployments link it asked me to log in.  I did, and the deployments data loaded fine.  But now my Account page is showing Test at the top (i.e. it thinks I'm logged in) but no data is loading.

## URL
https://dsgoproxyapp.azurewebsites.net/deployments

## Steps to reproduce
Intermittent

![image](https://user-images.githubusercontent.com/33625192/88922611-a2ef8e00-d270-11ea-9a8e-64b17bd5c752.png)

## Related feature
Sanjay wonders if potentially related to changes under https://github.com/IFRCGo/go-frontend/issues/1386

## Criticality/Urgency
Definitely needs investigation asap!!

**Comment by frozenhelium** [comment]
@batpad I wasn't able to replicate this one. But my hunch is that the APIs might have been temporarily down or the user's session might have been expired. @nanometrenat if it occurs frequently, can you also include the screenshot of the console? Can't find any solid reason for this issue.

**Comment by nanometrenat** [comment]
It has been happening often for a few days earlier this week - I don't have the console open when browsing normally but can try to open it when it next happens.  I hear what you're saying about session having expired HOWEVER historically when the session has expired the username no longer shows in top right hand corner and Log In button shows instead, also if session has expired and I'm trying to access a restricted page then I am asked to log in.

This is why it's weird - because it seems to be a half and half state where it thinks I'm logged in and not logged in at same time.

**Comment by batpad** [comment]
@nanometrenat are you still able to reproduce this?

**Comment by nanometrenat** [comment]
Thanks @batpad I haven't seen this issue for the last week or so - though I haven't been in GO as much as usual.

Maybe it was related to the slowness from geostuff or the init or something and has been fixed?  Or maybe not related at all!

In any case I agree that it's hard to work on it if not immediately reproducible, so I will close for now but reopen if it comes up again.  Thanks!
