### ISSUE TITLE
[PROD]  Incorrect map Nepal 3W on IFRC Go

### ISSUE THREAD

**Issue by heleenelenbaas** [IFRCGo/go-frontend#1485]
## Issue
*The admin regions in the IFRC Go platform for Nepal are outdated and thus not correct anymore.*

## Steps to reproduce
*Go to https://go.ifrc.org/countries/123#3w*
Find map with outdated admin boundaries here

![image](https://user-images.githubusercontent.com/69036191/89033734-c3cee680-d337-11ea-8434-9ff85fa8fefd.png)

## Expected behaviour
*Current provinces/regions show as Central, Eastern, Far Western, Mid Western and Western. 
It should be listed as Province 1, Province 2, Bagmati, Gandaki, Province 5, Karnali, Sudurpaschim*

![image](https://user-images.githubusercontent.com/69036191/89034263-e7def780-d338-11ea-8b05-4fb07a29f937.png)
https://en.wikipedia.org/wiki/Provinces_of_Nepal

## Impact
*This is preventing Nepal Red Cross Society from using the Go Platform.*

## Severity
*High: completely blocked due to incorrect information.*

## Is there a workaround?
*Nepal Red Cross Society is using Excel Sheets for their reporting, instead of the Go Platform.*

**Comment by geohacker** [comment]
Thanks for the ticket!

The districts are present in the new shapefile, but there are no attributes to reliably import them into the database and served as part of the API. I've ticketed the shapefile issue separately https://github.com/IFRCGo/go-frontend/issues/1422

cc @batpad

**Comment by jhenshall** [comment]
These were actually updated during last release but the admin codes have just been added to finalise this. As noted here: https://github.com/IFRCGo/go-frontend/issues/1188#issuecomment-780790476
