### ISSUE TITLE
[PROD] Åland issues

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1492]
## Issue
[The Åland Islands](https://en.wikipedia.org/wiki/%C3%85land_Islands) is an archipelago province at the entrance to the Gulf of Bothnia in the Baltic Sea belonging to Finland. 

While Åland has its own flag and the islands are considered a separate "nation" for amateur radio purposes, it does not belong as a National Society or autonomous country in the country gazetteer/list on GO.  While this might just be seen as an annoyance to the Finns in the team it also unfortunately creates issues when selected as the reporting entity while submitting a Field Report.

When selecting Åland Island through the Field Report submission form, the screen goes blank 
![Aland](https://user-images.githubusercontent.com/7791954/89337545-615d4980-d69b-11ea-99c9-ee34af18390d.JPG)

## Expected behaviour
Åland should not exist in lists of country/ NS names in GO

## Related feature
Xref: https://github.com/IFRCGo/go-frontend/issues/938

## Impact
Mostly @teklal and @lauripynnonen .

## Severity
Not a big concern and should be cleaned up in the ongoing geospatial work @geohacker 

## Is there a workaround?
Keep away from Åland

**Comment by nanometrenat** [comment]
Duplicate ticket FYI - this issue was already logged as https://github.com/IFRCGo/go-frontend/issues/1276 which is in "To Do" for 4.3
@LukeCaley are you happy to close in favour of that ticket or would you prefer to keep open for the Finnish contingent specially?  Cheers
