### ISSUE TITLE
[Staging] Grey Screen for Emergencies that do not have countries associated

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1496]
## Issue

https://dsgoproxyapp.azurewebsites.net/emergencies/3252#details produces a grey screen with errors in the console.

## URL

https://dsgoproxyapp.azurewebsites.net/emergencies/3252#details

## Steps to reproduce

Visit this URL: https://dsgoproxyapp.azurewebsites.net/emergencies/3252#details . Expect a webpage, instead get a grey screen.

## Expected behaviour

Should still render page, without breadcrumbs for country.

## Criticality/Urgency

Does not affect production, but MUST FIX before release.

**Comment by nanometrenat** [comment]
As at just now in staging unfortunately I still don't get any content.  I no longer get a totally grey screen - but I get the header only with no actual page content:
![image](https://user-images.githubusercontent.com/33625192/89451375-67672f00-d75c-11ea-9d55-4f1bf055df9b.png)

Then when I hit "refresh" with the console open I get the below (loading stayed for quite some time then went away):
![image](https://user-images.githubusercontent.com/33625192/89451458-8b2a7500-d75c-11ea-9fe6-dc6ba1e6b671.png)

**Comment by batpad** [comment]
@nanometrenat could you confirm that this is fixed in production? Thanks.

**Comment by nanometrenat** [comment]
_Theoretically_ emergencies in Prod should all have a country (or more than one country, or a region) associated - however I can see that some in fact don't, so thanks for the change.

Tested on https://go.ifrc.org/emergencies/3623#details and can confirm I'm not getting a grey screen.  Thanks!
