### ISSUE TITLE
[Staging] Grey screen due the selection of a blank option in affected country dropdown in FR

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1499]
## Issue

There are an option in blank in the affected country dropdown in the FR form, if this option is selected the page turns in a grey screen.

## URL
https://dsgoproxyapp.azurewebsites.net/reports/new

## Steps to reproduce

Go to the FR creation form, in the affected country and province, select the blank option from the dropdown menu (first option from the dropdown menu).

![Selection_011](https://user-images.githubusercontent.com/11504548/89428692-4c67d100-d702-11ea-85e7-9c65588da09c.png)

## Expected behaviour
No option in blank  in a dropdown.

**Comment by nanometrenat** [comment]
xref #938 the general geospatial ticket
and xref https://github.com/IFRCGo/go-frontend/issues/1276 (and also https://github.com/IFRCGo/go-frontend/issues/1492#issuecomment-668839683) which are about the Country dropdown in FRs - not the blank specifically, but worth bearing in mind when fixing.

**Comment by geohacker** [comment]
This should no longer be an issue. @karitotp tagging you test this again on staging.

**Comment by batpad** [comment]
@karitotp could you please confirm the fix here?

**Comment by karitotp** [comment]
This issue is still there @geohacker @batpad

**Comment by batpad** [comment]
@karitotp thank you! It should be fixed now, can you please test again?

**Comment by karitotp** [comment]
@batpad it was fixed, the empty space in the country dropdown is not there anymore.
But the countries in the dropdown is appearing with (fr) at the beginning, this happen in all languages.

![Screenshot from 2020-09-14 08-53-14](https://user-images.githubusercontent.com/11504548/93094950-25d57800-f668-11ea-90b4-cb3e7a25a3ba.png)

**Comment by batpad** [comment]
Thanks @karitotp !

@frozenhelium this seems to be a cache issue -- user has French selected when they make Countries request - then they change language, but it still uses French countries from cache.

@frozenhelium we should probably bust the cache whenever the user changes language? Let me know if you would like me to make a separate ticket for this. Thanks!

**Comment by karitotp** [comment]
This issue of French initials in the countries is also in the list of countries in the different regions.

![Screenshot from 2020-09-14 09-28-36](https://user-images.githubusercontent.com/11504548/93099142-4fdd6900-f66d-11ea-90b5-770f1ef91443.png)

**Comment by frozenhelium** [comment]
@batpad Yep, we should clear cache on language change
