### ISSUE TITLE
Importing full country and district geometry slows down the API

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1500]
## Issue
Yesterday @nanometrenat identified that staging API is being slow to return requests successfully ([comment](https://github.com/IFRCGo/go-frontend/issues/1386#issuecomment-669414422)). This happened after we deployed the geo changes and ran management commands to import geometry, bbox and centroid for regions, countries and districts.

Earlier today, @GregoryHorvath and @batpad was able to confirm the slow behaviour. @GregoryHorvath  also noticed the spike in network usage at the VM level and that things seem much snappier when we remove the `geom` column from the countries model. This is the column that stores multipolygons of the country geometries.

### Further debugging
@GregoryHorvath  and I spend a bit more time debugging this and realized that Django was selection the geometry for every query that uses the country and district viewset. The raw SQL query selects all columns and doesn't respect the field filters. The filters are applied after the query result is returned from the DB. This is also why the VM network usage was high.
 
## Short term fixes
* First we made separate serializers for fetching geo data. So the existing API requests like Appeals for instance doesn't need to worry about dealing with geo columns. https://github.com/IFRCGo/go-api/pull/844
* Second, we removed the geometries from the database. The management commands allow one to optionally import geometries. The bbox and centroid doesn't rely on this, and the front-end doesn't rely on this. 

This is fixes are now on staging.

## Long term ideas
Still figuring out best approaches:
* Use [query defer](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#defer) to ignore the geom column. Though this will have to be across all viewsets
* Potentially store the geometries in a different table and use them only when needed.

**Comment by batpad** [comment]
@geohacker I imagine this is still a problem if and when we do want to store detailed geometries in the database? Would this still be needed for #1474 ? Moving over to 4.4., we can discuss how we want to scope this and #1474 out.

**Comment by geohacker** [comment]
This is fixed in https://github.com/IFRCGo/go-api/pull/933

**Comment by jhenshall** [comment]
Can this be closed now then @geohacker ?

**Comment by batpad** [comment]
We've split up the raw geometries into a separate table, so that the large geometries are still stored in the db, but don't affect API performance. This can be closed.
