### ISSUE TITLE
[PROD] IFRC Users not seeing the Field Reports that they should be able to see on Emergency page FR list

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1501]
## Issue
An IFRC user in Production is reporting that they cannot see any Field Reports on an emergency page - these FRs should be visible to IFRC users.

The Field Reports are visible to my user (which is a superuser). I have verified that they are not visible to IFRC users that are not superusers but are in the "IFRC Admins" group - i.e. the group that is automatically assigned to users with an IFRC email address.

A while back when IFRC users couldn't see things with IFRC visibility it was because they weren't in that group - however that original issue was resolved under https://github.com/IFRCGo/go-api/issues/741 and was thought to be working.

However as at right now IFRC users (i.e. IFRC Admin permissions) looking at an Emergency page can NOT see Field Reports that are set to be visible to IFRC (though they can correctly see Field reports in the list that are Public or Membership).

Please investigate asap as our colleagues in the Regions need to be able to see all FRs in their region.

## Steps to reproduce
https://go.ifrc.org/emergencies/4297#details - has 2 FRs, one visible to Membership and one to IFRC.  IFRC users should be able to see both.

https://go.ifrc.org/emergencies/4294#details - has 3 FRs, all visible only to IFRC.  IFRC users should be able to see them in the list.

NOTE I can see that the full list of ALL Field Reports for an emergency is being returned in the API every time (whatever the auth) so it must be filtering out incorrectly on the page perhaps?  https://prddsgocdnapi.azureedge.net/api/v2/event/4294/

## Expected behaviour
The list of Field Reports should be according to the user permissions and the Field Report visibility settings.

## Related feature
https://github.com/IFRCGo/go-frontend/pull/1286#issuecomment-634754749 https://github.com/IFRCGo/go-frontend/issues/1118

## Impact
IFRC users that aren't superusers (it seems)

## Severity
Regional PMER/IM colleagues can't see FRs that they should be able to see.

## Is there a workaround?
Have to ask someone else for the info.

**Comment by GregoryHorvath** [comment]
@nanometrenat Both the backend and frontend parts are deployed to staging, so now it's testable. I also did 2 separate PRs against `master` so we could do a hotfix deploy early next week if needed.

Keep in mind this includes an `is_ifrc_admin` boolean field in the users' API endpoint, which is `true` if the user is in the "IFRC Admins" group.

**Comment by nanometrenat** [comment]
NOTE xref this prior ticket which is also about returning user group data https://github.com/IFRCGo/go-api/issues/702

**Comment by nanometrenat** [comment]
@tovari can you please test this ticket?  I have not had a chance to.  It will entail logging in as a superuser, and as a non-superuser person with IFRC email address (therefore should automatically get IFRC Admins user group - check in back end), and as a non-IFRC logged-in user ("the membership") and as Public (i.e. not logged in).  Need to check that the various groups can see the right things - and in particular that IFRC users that aren't superusers can see FRs that are set to visibility = IFRC Only.  Thanks!

cc @LukeCaley

**Comment by tovari** [comment]
Test on staging has been completed. It works as expected, all IFRC users can see the FRs.
Thanks!

**Comment by batpad** [comment]
@GregoryHorvath can you close this if this has been deployed to prod and there are no further actions?

**Comment by GregoryHorvath** [comment]
This went out as a hotfix. We can close and in case it happens again open a new one.
