### ISSUE TITLE
[Staging] Field Reports count is the same on Emergencies page regardless the user's permission level

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-frontend#1504]
## Issue
Field Reports' count on Emergencies page show the total number regardless of authentication. _The whole section is not showing up if there are no Field Reports for the user's permission level (public / logged in / IFRC Admin or Superuser)_

## URL
https://dsgoproxyapp.azurewebsites.net/emergencies/4054#details

## Steps to reproduce
(not logged in)
![image](https://user-images.githubusercontent.com/30079559/89654157-8256b200-d8c8-11ea-80b1-c2b53b1cc4a6.png)

1. Go to an Emergency page which has Field Reports that are non-public and also public ones
2. Log out and see the Field Reports count stays the same

## Expected behaviour
Show the correct count per user.

## Criticality/Urgency
Non-blocker

**Comment by GregoryHorvath** [comment]
@batpad @LukeCaley only assigning you for prioritization.

**Comment by nanometrenat** [comment]
Thanks for logging @GregoryHorvath !  I noticed this too when investigating https://github.com/IFRCGo/go-frontend/issues/1501#issuecomment-670535505

I think that we need to ensure that sufficient testing is done with non-superuser accounts as currently often testing is done with good old ifrcgo-testuser which has access to everything ;)

**Comment by batpad** [comment]
Sorry, missed this issue in the release notes - @karitotp could you test that this works?

**Comment by karitotp** [comment]
@batpad, the FR counts is working according their visibility permissions.

In case there is a FR but its visibility is not public, the emergency page is still displaying an empty tab of Reports/Documents

![Screenshot from 2021-02-17 08-50-20](https://user-images.githubusercontent.com/11504548/108213576-300b0f00-70fd-11eb-8366-0708d2ba8697.png)

**Comment by nanometrenat** [comment]
Closing based on above comment
