### ISSUE TITLE
[PROD] Cosmetic - how "loading" shows on /emergencies page

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1510]
## Issue
When GO pages load, normally the header and basic outline of the web page pre-loads, and then the "loading" 3 dots are shown in boxes where data is required.

However for /emergencies nothing on the webpage pre-loads, so the user _only_ sees the 3 dots until the data for the page has arrived.

Suggest making it consistent with other pages and having the header etc. display while data is loading.

Interestingly, with current setup of /emergencies page this also means that the screen shows as totally grey (no loading symbols or any kind of content) when the API is down.  As opposed to the other pages, which show the header and web page structure but then just say "Data not available"

## Steps to reproduce
https://dsgoproxyapp.azurewebsites.net/emergencies

![image](https://user-images.githubusercontent.com/33625192/89705147-11140f00-d95b-11ea-943b-ad7978cf6b3b.png)

## Expected behaviour
This is how other pages look when loading
![image](https://user-images.githubusercontent.com/33625192/89705153-26893900-d95b-11ea-9f8b-9f788ec1a655.png)

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
Everyone

## Severity
Minimal - cosmetic

## Is there a workaround?
Not required

**Comment by nanometrenat** [comment]
_not_ the same issue, just an xref that https://github.com/IFRCGo/go-frontend/issues/1491 also relates to the global loading dots

**Comment by batpad** [comment]
This should be fixed with the new global loading, ready to test in staging.

**Comment by nanometrenat** [comment]
thanks - confirmed that emergencies page loading dots now show within the section rather than instead of the page cheers.
