### ISSUE TITLE
[DEV] Separate Redux actions by category/component from the main 'index.js'

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-frontend#1512]
We should make the Actions more organized so it's not just thrown into an `index.js` with currently ~700 lines of code. This would help clarity in a way that we could clearly see what has been implemented for a specific category and what hasn't, and also help with maintaining the codebase more easily.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/863 (?)
Closing on the assumption it was dealt with via the re-write
