### ISSUE TITLE
[Staging] Translation:  Show Language switch on mobile header

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1516]
## Issue
Noticed when looking at staging while having Dev Tools open in browser - as reduced window width means mobile header is used.

The Mobile version of the page header needs to be updated so that it has translations changes - in particular the language select dropdown - as at the moment (until https://github.com/IFRCGo/go-frontend/issues/1402 is prioritised) the mobile header is coded separately.

Related to PR https://github.com/IFRCGo/go-frontend/pull/1366 etc.

## URL
https://dsgoproxyapp.azurewebsites.net/

## Steps to reproduce
Any page - just with reduced width

## Expected behaviour
Language dropdown should be available somewhere

## Related feature
Translations

## Criticality/Urgency
Not urgent - mobile is not officially supported - just happened to notice due to having dev tools open.

**Comment by batpad** [comment]
@frozenhelium - unfortunately we still have this weird separate header component for mobile: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/mobile-header.js

Ideally we would do #1402, but that's not likely to go out immediately. Do you think you could work to add the language selector to the mobile header, and then feel free to assign to @imohkay if it needs any styling improvements for mobile?

**Comment by batpad** [comment]
@tovari @LukeCaley moved this to the 4.4 board - while we still don't claim to have first-class support for mobile, it seems like this would still be nice to do - there should not be any other blockers to making translation working on mobile other than making sure we add the selector to the mobile header view and ensure it is styled appropriately.

**Comment by nanometrenat** [comment]
Closing - rewrite has brought much better mobile support, cheers
