### ISSUE TITLE
Implement a localStorage cache for initial data load

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1517]
xref #1386 

**Is your feature request related to a problem? Please describe.**

Right now, we fetch the initial data on every page load - i.e. user profile data and countries data. And since these requests need to happen before the rest of the page loads at all, this has caused a perceptible slowdown to page loads. 

**Describe the solution you'd like**

Especially for countries data that we do not expect to change very often, it would be good to cache the data locally. My proposal would be to use localStorage to cache the data, and have the client manage expiry, but open to suggestions for doing this via HTTP headers, etc. from the server (cc @thenav56 )

Am happy to look into modifying the actions and the multiplexer to save / get from a localStorage cache.

**Describe alternatives you've considered**

The other option would be to ensure to correctly set cache-control / `Not Modified` headers correctly on the server and hope for browsers to do the correct thing and use data from cache. I've generally had mixed luck trying to configure caching headers correctly and getting browsers to respect them reliably - @thenav56 if you feel this would be a better approach, happy to give this a shot.

One way or another, we should definitely not have users re-fetch the entire country list from the API on every page load - @thenav56 @frozenhelium, will be great to quickly discuss best approach here, and am happy to take on the work.

cc @geohacker @GregoryHorvath @nanometrenat @LukeCaley

**Comment by LukeCaley** [comment]
@batpad is this currently seen as in scope for 4.3?  If not, please elaborate the desired way forward and time estimate for future prioritisation

**Comment by batpad** [comment]
This was implemented in https://github.com/IFRCGo/go-frontend/pull/1564#event-3755172583 - thank you @frozenhelium !!

This is ready for testing. Now, the initial data load which loads countries, regions and the user profile data will be cached with an expiry time of 1 day. This can be configured, so we can change the expiry time if needed.

To Test:

 - Initial data loading screen no longer appears after loading the page the first time
 - All data involving countries, regions, etc. continues to work as normal
 - Clearing cache by visiting https://dsgoproxyapp.azurewebsites.net/clear-init-cache works to clear the cache
 - After clearing cache, reloading the page should cause the loading screen to appear again

@karitotp - will be great if you can test the above on staging - https://dsgoproxyapp.azurewebsites.net/ ty!

**Comment by karitotp** [comment]
@batpad, the chache is working as the above steps :+1:

**Comment by tovari** [comment]
@batpad, @karitotp, I still see the same behavior after clearing the cache as before that. I see the data loading screen each time I reload the page. I'm not completely sure though, what should I expect exactly. Clearing cache would also release the language of the site and would log out the user? 
Thanks!
