### ISSUE TITLE
[Staging] ** Cannot continue past page 2 of new Field Report

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1518]
## Issue
"continue" button does not work in New Field Report Situation screen.

## URL
https://dsgoproxyapp.azurewebsites.net/reports/new

## Steps to reproduce
Creating new Field Report in staging

1. I fill in details on page 1 (Context) - I had chosen COVID-19 slider.
2. I click "continue" to go to page 2 (Situation) and page loads fine.
3. HOWEVER when I click "continue" to go to page 3 (Actions) nothing happens - I cannot move forward.  No errors given on screen, just nothing happens.  This occurs regardless of whether I have input any figures or data.

Note that clicking on the direct link to Actions (the red dot below the "Create Field Report" heading) works fine.

Error in console shows the below, not sure if relevant

> index.js:175 Uncaught TypeError: Cannot read property 'split' of undefined
    at a.value (index.js:175)
    at a.value (index.js:226)
    at HTMLUnknownElement.m (react-dom.development.js:188)
    at Object.f (react-dom.development.js:237)
    at y (react-dom.development.js:292)
    at react-dom.development.js:306
    at S (react-dom.development.js:389)
    at react-dom.development.js:414
    at pn (react-dom.development.js:3278)
    at dn (react-dom.development.js:3287)

## Expected behaviour
I should be able to create a Field Report

## Related feature
Potentially related to validation or epi figures changes.

## Criticality/Urgency
Critical as user cannot proceed to create their Field Report.

**Comment by batpad** [comment]
Thanks for the report @nanometrenat 

@necoline assigning this to you if that's okay - the error seems to be coming from here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/field-report-form/index.js#L175 - seems like ensuring description is an empty string there or so should likely fix? But not sure where you best seeing that check happening :-)

Thanks again for the catch @nanometrenat, we have been merging a few things to staging slightly prematurely to not be stuck behind with everything moving, we'll make sure things are thoroughly tested after all the field report fixes / changes are in.

**Comment by necoline** [comment]
I noticed that this morning as well and included the fix in #1513

**Comment by LukeCaley** [comment]
@nanometrenat would you mind doing the UAT honours, please?
