### ISSUE TITLE
[PROD][STAGING] many countries don't have iso3 in the database

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1522]
## Issue
Many countries don't have iso3 in the database. These are currently pulled from the front-end https://github.com/IFRCGo/go-frontend/blob/master/src/root/utils/country-iso.js#L1. This should be moved to the database.

cc @batpad

**Comment by nanometrenat** [comment]
Hi, are we talking about Staging or Prod here?  Not sure based on title.
IFRC countries should all have iso3 codes in Production database/back end right now (although some are upper case and need to be lowered).

**Comment by geohacker** [comment]
@nanometrenat Both staging and prod have several countries without iso3 codes. These were not a problem until now because there was a hardcoded iso2 to iso3 mapping on the front-end.

**Comment by jhenshall** [comment]
Was done as part of 4.3 release but wasn't on the board. Closing ticket.
