### ISSUE TITLE
Store fdrs codes in the database

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1523]
Currently we rely on an ISO to FDRS code mapping on the front-end defined here https://github.com/IFRCGo/go-frontend/blob/master/src/root/utils/fdrs-codes.js#L1. We should add the FDRS codes for every country in the database. This can be done along with #1522  in the management command.

cc @batpad

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/940

**Comment by batpad** [comment]
@geohacker does this still need to be done? Should it go on the 4.4 board?

**Comment by geohacker** [comment]
Yeah this should go into 4.4
