### ISSUE TITLE
[DESIGN] Validate the 3W Create and Edit button flows from emergency pages

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1525]
Currently on emergency pages there is a 3W Create button, but the users get confused when they want to edit it. One issue is that the 3W tab has not been added yet to the emergency pages. But also, the flow of creating and editing 3Ws need to be clarified, since one user can create multiple 3Ws and want to edit them.

The second issue is to make sure the 3W table is visible properly even on smaller screens, given the 3 buttons to edit get cut off when the table is too small and becomes scrollable. Also a dev issue to make sure the scroll bar is always visible.

**Comment by mariam-yu** [comment]
@frozenhelium There was an issue with the table and View All 3 dots. In smaller screens the table gets cut off so the button is not visible anymore. We have 2 options here: 1 - move the buttons to the front to be on a safe side, 2 - Make sure the table is responsive like on the other pages so the right column will always be visible. Our choice would be the second one but if there are any difficulties, you have the designs for both. 

A few more things:
- If we keep non-responsive, can we make sure the horizontal scroll bar is active and visible in all operating systems?
- We are taking out the View Details from the menu directly into the table. This way, the users who are not logged in/don't have access don't need to click on 3 dots just for one option.
- Can we have the History option open up in a new window?
- We added styling for Add 3W Data button.

@nanometrenat to confirm if this seems a viable solution to the challenge you noticed. As for the buttons, there should be one Add 3W button on top, and then edit happens on each line of the table. Is that correct?

Thanks!!!
![_GO_Country_3W_TableOptions](https://user-images.githubusercontent.com/60006476/90760624-72849800-e2e2-11ea-8eb2-d476ab21e53f.png)
![_GO_Country_3W_TableOptions2](https://user-images.githubusercontent.com/60006476/90760629-76b0b580-e2e2-11ea-8d60-33040c902047.png)

**Comment by LukeCaley** [comment]
Believe this has been implemented but please confirm, xRef release notes and close if so @tovari cc @mariam-yu

**Comment by tovari** [comment]
This has been resolved https://github.com/IFRCGo/go-frontend/pull/1959
