### ISSUE TITLE
[Staging] Contacts in a emergency page is showing an extra row with other data

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1526]
## Issue
In the contact section of an emergency page is displaying an extra row with other type of data. This ticket could be related https://github.com/IFRCGo/go-frontend/issues/1486

## URL
Example:
https://dsgoproxyapp.azurewebsites.net/emergencies/4061#details

## Steps to reproduce
Go to an specific emergency page that have contacts.

![Selection_020](https://user-images.githubusercontent.com/11504548/90268536-c6900800-de1c-11ea-8ab9-d48be3a8ffa0.png)

## Expected behaviour
I think this row should not be there.

**Comment by nanometrenat** [comment]
That line is correctly there, as is correctly reflecting the data that was input by the user (me) at the time of setup - to try to be sure that all the fields were being mapped correctly.  Cheers for finding it.

What is perhaps MORE of a concern is htat the other contact input is _not_ showing - see https://dsgocdnapi.azureedge.net/en/api/fieldreport/9637/change/

**Comment by batpad** [comment]
Can we close this?

Do we need another issue for contacts not showing @nanometrenat ?
