### ISSUE TITLE
[Staging] Url in Situational Overview does not work in Arabic language

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1527]
## Issue
If there is an URL in Situational Overview, this works good in other languages but the url does not link when I change to Arabic language.

## URL
https://dsgoproxyapp.azurewebsites.net/emergencies/4066#details
https://dsgoproxyapp.azurewebsites.net/emergencies/4057#details

## Steps to reproduce
Go to the Situational Overview section of an emergency page and click in the url if there is one.

![Selection_021](https://user-images.githubusercontent.com/11504548/90270089-4323e600-de1f-11ea-8b43-d918271a3cfb.png)

**Comment by batpad** [comment]
@karitotp could you please check and confirm if this is fixed? I was unable to reproduce here.

**Comment by karitotp** [comment]
@batpad, Now the Url works :+1:
