### ISSUE TITLE
Translation: Block forms submission for the languages other that English

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1528]
Forms submission is currently only supported in English language. To reflect this in the frontend we have to block the form in the frontend as well. One of the method will be overlaying over the forms and giving users a message about it as shown below:
![2020-08-17-185231](https://user-images.githubusercontent.com/4931541/90399550-d75da980-e0ba-11ea-840d-067dc6f4c207.png)

**Comment by nanometrenat** [comment]
@guipizzini @LukeCaley I just added this ticket to 4.3 as it wasn't on a board

**Comment by batpad** [comment]
@frozenhelium can you confirm that this is no longer in scope for 4.3?

@LukeCaley maybe we can take this off the board and re-visit when we are enabling dynamic translations if we still need to do this.

**Comment by frozenhelium** [comment]
@batpad Yep, this is no longer in the scope of 4.3 since we're not adding the automatic translation for now

**Comment by batpad** [comment]
Am going to close this and move this off the board. I think we never want a situation where we block forms for users of certain languages. We still need to do work to cleanly handle translations of inputs in multiple languages, that can be captured separately.
