### ISSUE TITLE
Refactor Global Loading

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1530]
### Problem
Currently global loading works by injecting the state to a globally defined component. This process is asynchronous and not very deterministic. This approach has been causing the problem like the loading animation not disappearing even when all the requests has been completed.

### Solution
Create the global loading component based on the React context so that it is deterministic and reliable.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/1491 and https://github.com/IFRCGo/go-frontend/issues/1510
