### ISSUE TITLE
Testing Geo API integration

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1531]
This ticket broadly outlines things to test before we merge https://github.com/IFRCGo/go-frontend/pull/1514. The PR touches 45 files, removes a lot of code and streamlines the use geo data across go-frontend. The key change is that regions, countries and districts are all fetched from the API -- no more hardcoded ids and codes (except fdrs, fix coming soon). This is the first round of testing to make sure the app is stable, and doesn't have regressions. The actual logic of what countries should up in the dropdowns and maps is a separate phase, which we'll do after the data is imported (ticket coming soon).

This should address quite a few of the issues linked in https://github.com/IFRCGo/go-frontend/issues/938

### Here are the main things to focus on while testing
*  **All pages** - test every page and ensure they load alright
* **New field reports** - create new reports, emergencies. Select different countries, districts and ensure they behave as expected. Make sure selecting countries like the ones mentioned here https://github.com/IFRCGo/go-frontend/issues/1276#issuecomment-651592294 doesn't freeze/break the application
* **Existing field reports** - existing reports across the platform should continue to load and work as usual. 
* **Maps** - notice that all maps load, regions and countries are zoomed into properly, and centroids are displayed for countries
* **Tabs and breadcrumbs** - ensure tabs (for example region link) and all breadcrumbs across the site that shows geo data are functional and shows the expected hierarchy.
* **PER Forms** - create new PER, save as draft, edit the draft. Try this with various countries and districts and ensure they do the right thing.

### Don't worry about missing data 
There are countries and districts with missing data. For example, there are many countries without iso3 code, centroid and bbox. Same for districts. These are captured in https://github.com/IFRCGo/go-frontend/issues/1464, https://github.com/IFRCGo/go-frontend/issues/1473 and https://github.com/IFRCGo/go-frontend/issues/1522

cc @batpad

**Comment by geohacker** [comment]
The surge URL for testing is https://ifrc-go-feature-geo-apis.surge.sh/

**Comment by karitotp** [comment]
@geohacker @batpad, here the things that I found that is not working good or is looking different to the staging site:

### Region pages:

- The section of the list countries on the region page is missing.

![Screenshot from 2020-08-18 11-01-20](https://user-images.githubusercontent.com/11504548/90536976-606bf380-e142-11ea-874a-a812f24be3f5.png)
_Missing section_


### New field reports:

- The validation of affected country field is giving an error for all countries. 

![Screenshot from 2020-08-18 14-03-29](https://user-images.githubusercontent.com/11504548/90554694-df215a80-e15b-11ea-9534-6e6cc2381020.png)

### Maps:
- Some centroids are shown outside the country to which they correspond.

![Screenshot from 2020-08-18 10-25-50](https://user-images.githubusercontent.com/11504548/90533029-9064c800-e13d-11ea-8a7b-e426120a28df.png)
_Somalia_

![Screenshot from 2020-08-18 10-55-02](https://user-images.githubusercontent.com/11504548/90536377-98bf0200-e141-11ea-9211-a319f8385b14.png)
_Croatia_


- The zoom for the region maps works good but the data (colored points) is not displayed correctly when I navigate from region to a region:
   **Steps to reproduce:**
  - Go from Home page Africa region page -> map and data load correctly.
  - Go from Africa page to other region for example Americas -> zoom to map is correct but the data is still displaying the data of the Africa region, this means the shown data is from the previous visited region. This does not happen if the navigation is from Home page to any region page.

![Screenshot from 2020-08-18 13-10-55](https://user-images.githubusercontent.com/11504548/90549554-49360180-e154-11ea-9e22-d24cb3aa1cf1.png)

### Tabs and breadcrumbs:

- Breadcrumbs for the region of Middle East & North Africa is `Home > Mena` instead to be `Home > Middle East & North Africa`. The title for the Region page and the name in the dropdown is also as Mena.

![Screenshot from 2020-08-18 11-07-59](https://user-images.githubusercontent.com/11504548/90537574-1afbf600-e143-11ea-96ae-64f6736cb1b2.png)

- Breadcrumbs for a specific emergency is different to the breadcrumbs in staging site
  - In this surge url: `Home > Emergencies > Asia Pacific > Afghanistan > Test Frontend`
  - In staging: `Home > Emergencies > Afghanistan > Test Frontend`

**Comment by geohacker** [comment]
Thank you @karitotp! This is really helpful.

I've fixed the following and deployed to https://ifrc-go-feature-geo-apis.surge.sh/
* [x] Missing countries section on region page
* [x] Field report 'should be string' validation
* [x] Region operations map reloading issue

@karitotp could you test this again? Thanks!

The other issues:
1. Incorrect centroids — this is because the centroid is currently the geometric centroid of the multipolygon for the country. I recommend we use capital city coordinates. Will open a separate ticket. This can also be edited from the django admin.
2. Region breadcrumb name (Mena) — this is because we pull the name directly from the database now and it is Mena. Unfortunately we can't change that directly because it's an enum type. We will add a name column that editable and use that on the front-end. Will ticket separately.

**Comment by karitotp** [comment]
> - [x] Missing countries section on region page
> - [x] Field report 'should be string' validation
> - [x] Region operations map reloading issue

@geohacker, all the above things were fixed and they look good now :+1:

**Comment by geohacker** [comment]
Centroids on staging are now updated 
![image](https://user-images.githubusercontent.com/371666/91440892-ee578500-e88c-11ea-8358-3fa10bb1df31.png)

**Comment by nanometrenat** [comment]
Adding to 4.3 board as I believe this is going in in 4.3 release

**Comment by jhenshall** [comment]
I've compiled a [list of UAT scenarios to test](https://docs.google.com/spreadsheets/d/1mnOuRZlzexG4Pi-QcKaGVNOlVvpPCRakiKzuW4GJFiM/edit#gid=0). Some of these need expanding more - I intend to do a first run through on staging and will clarify some of the points as I do so. This is my initial brain dump of everything. Also doing some local testing to try and replicate what the prod database will look like and possible issues there after the changes outlined by @geohacker [here](https://github.com/IFRCGo/go-frontend/issues/1534#issuecomment-691927120).
cc. @karitotp
