### ISSUE TITLE
[PROD] 3W map on country page not rendering - both PROD and Staging

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1533]
Identified by @teklal 

## Issue
3W maps on Country pages are not rendering on either Prod or Staging.
e.g. https://go.ifrc.org/countries/187#3w
![image](https://user-images.githubusercontent.com/33625192/90659010-7f52ae80-e244-11ea-8fd9-78790b849831.png)

Similarly not working on staging https://dsgoproxyapp.azurewebsites.net/countries/290#3w

However the 3W maps at Regional level are rendering fine.

Looking in browser dev tools I can see that the GET request to api.mapbox.com is returning a status code of 404 Not Found with response {"message":"Style not found"}

This has been working fine previously (since the last release) so not sure what has changed.
Side note - several of the PBI dashboards on GO have also stopped rendering maps despite not having been changed.  Am guessing the problem is Mapbox styles config end?

## Steps to reproduce
Go to any country and click on 3W tab.

## Expected behaviour
Map should load

## Impact
All country 3W pages

## Severity
Missing info

## Is there a workaround?
No

cc @LukeCaley @jhenshall @guipizzini not sure who/how needs to resolve this

**Comment by geohacker** [comment]
The 3W tabs use the map id `mapbox://styles/go-ifrc/ck1izjgrs016k1cmxwekow9m0`, this is now missing from Mapbox Studio.

![image](https://user-images.githubusercontent.com/371666/90662947-a9b56380-e266-11ea-9f6b-adf5e5c409d9.png)
This may have been accidentally deleted, but I'm not certain.

@jhenshall is looking to restore and support options. I'm chatting with friends at Mapbox, will update shortly.

**Comment by geohacker** [comment]
Two map ids `ck1izjgrs016k1cmxwekow9m0` and `ck9tz6f150ub11ip8j97wrsww` were accidentally deleted today from the IFRC Go Mapbox account. We got in touch with Mikel Maron at Mapbox and he helped us to restore these. All maps are back now!

**Comment by nanometrenat** [comment]
Thanks to all!
