### ISSUE TITLE
[PROD] 3W - view/edit menu not clickable in Edge

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1537]
## Issue
Identified by ICRC team.

If you go to a country 3W page in EDGE browser and click the three dot menu there is no response.  i.e. the menu does not load. Works fine in Chrome though

## Steps to reproduce
https://go.ifrc.org/countries/160#3w
Use Edge browser
Click on menu (...) button to right of a 3W entry.
Nothing happens

![image](https://user-images.githubusercontent.com/33625192/90752189-60512c80-e2d7-11ea-97d7-8546a96f2f72.png)

## Expected behaviour
If the user is logged in they should see the menu below, if not logged in then "view" should be visible.
![image](https://user-images.githubusercontent.com/33625192/90757309-c640b280-e2dd-11ea-92b6-b5ec3c684e33.png)

## Related feature
3W
Past Browser compatibility tickets include https://github.com/IFRCGo/go-frontend/issues/772 https://github.com/IFRCGo/go-frontend/issues/921 https://github.com/IFRCGo/go-frontend/issues/767

## Impact
Users using Edge

## Severity
They cannot edit and do not know that they can't so contact support

## Is there a workaround?
Use a different browser e.g. Chrome

**Comment by tovari** [comment]
It has been tested on Edge and it works now as expected.
