### ISSUE TITLE
[PROD] Grey screen when opening GO in IE - suggest a "use other browser" warning

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1548]
## Issue
Users accessing GO with Internet Explorer just see a completely grey screen and think something is broken.

It has explicitly been decided that GO is not supported on IE; however we need some way of telling the user that so we don't get support calls.

It would be great if GO could detect the user's browser, and display wording such as "Internet Explorer cannot be used to access GO.  Please use an alternative browser"
@LukeCaley @tovari to come up with good words and prioritisation

## Steps to reproduce
Go to any GO page in Internet Explorer

## Expected behaviour
Users should know what to do

## Related feature
Past Browser compatibility tickets include https://github.com/IFRCGo/go-frontend/issues/1537 #772 #921 #767

## Impact
Anyone using IE

## Severity
Completely stops them from using GO

## Is there a workaround?
Install/use a different browser

**Comment by batpad** [comment]
cc @frozenhelium for advice / recommendations on the best approach here.

My hunch / suggestion would be to do browser detection early, and show a simple message to IE users saying we are very sorry, but they are using an unsupported browser and they can use any of these other browsers - @frozenhelium how feasible do you think this is?

Would be good to know how important this is from a business perspective.

Based on conversations with @frozenhelium and all our reading into this, supporting Internet Explorer (which is by now not supported by Microsoft) would hold back development too much and not allow us to use modern browser features. But, we should definitely be better with our messaging and not show users a grey screen. @frozenhelium can you please advise on how much work you see this being, to help prioritize? Thanks!

**Comment by frozenhelium** [comment]
@batpad We can block the further processing / rendering of the GO app for IE.
We need to detect the browser first. [browser-detect](https://www.npmjs.com/package/browser-detect) an excellent library for that. We can then conditionally initialize the React app in the `src/index.js` according to the browsers we support.
We can also show the recommended browser if we detect that user is currently running unsupported browser (i.e. IE)

**Comment by batpad** [comment]
@LukeCaley @mariam-yu could we get copy for text to show the user if they are using Internet Explorer?

@frozenhelium - thanks! So we'd just add some conditional like `if (browserIsNotIE) { ... render the React app .. } else { document.getElementById('app-container').innerHTML = 'Sorry we do not support your browser' }` <-- something like this?

@GregoryHorvath might this be something you can take on once we have some text and minimal design for this message to users?

**Comment by GregoryHorvath** [comment]
@batpad I'll look into it sure and try to make the base functionality working so then we'll have to just replace "lorem ipsum" with the design/text.

**Comment by GregoryHorvath** [comment]
@mariam-yu Sorry for pulling you into this. There's a screenshot of how the error message looks right now at https://github.com/IFRCGo/go-frontend/pull/1633 . This is probably low priority and I don't know who should be the one to decide on the looks from the IM team on this now.

**Comment by mariam-yu** [comment]
@GregoryHorvath This is perfect. We are actually planning to comb through the error messaging. Is there a timeline on this?

**Comment by GregoryHorvath** [comment]
@mariam-yu Nope, just went ahead and implemented the functionality at first. I don't know how wide is the range of CSS which may be compatible with IE, so I guess it would be best to go with some simpler design.

@tovari Could help with answering the prio/timeline question probably?
