### ISSUE TITLE
UX/UI Updates

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1555]
A few design tasks (both functional and then visual) are combined in this ticket. The outcome will be the updated wireframes and the UI prototype.

- Finalize consistencies/terminology
- Explore country page layout without emergencies
- Highlighted Operations without ERUs
- Pushing users to login - experience
- Footer update
- Match the UI prototype to the live version

**Comment by mariam-yu** [comment]
Push to Login UX/UI suggestions - https://docs.google.com/document/d/1rB1pgS-HtlH7NC60tnUlQjtrkLidOogd78yEPOBVqyA/edit?usp=sharing @LukeCaley to review (whenever you get a chance)

**Comment by mariam-yu** [comment]
UX suggestion for:
- Footer, Highlighted Operations without ERUs (if the fields end up being more empty than populated)
![_Footer_NoERU](https://user-images.githubusercontent.com/60006476/93925482-7dce4780-fd16-11ea-9c87-79e008ed6267.png)

- Country page when there is no data. Assuming the Country Profile information can still be populated, we propose to make that the main tab, show Additional Information if it has any data, and replace the top numbers with a sign that says there are no operations, since otherwise, there will be only zeros.
![_Country-noData](https://user-images.githubusercontent.com/60006476/93925488-8161ce80-fd16-11ea-8d46-09d3a94bcf1b.png)

**Comment by mariam-yu** [comment]
Updated UI of the footer: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/433294669__Footer_Other
Updated "country with no emergencies" UI: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/433294670__Country-NoData

**Comment by mariam-yu** [comment]
@LukeCaley There were a bunch of stuff shared above. Could be small modifications to add to the UI this year (possibly). Let us know your thoughts.

**Comment by LukeCaley** [comment]
The push to login pieces look good to me and clearly 'action-oriented' for the user.  Suggest that the next step would be to break these down into dev tickets for the backlog and eventually pulled in to the 'to-do' column.  In terms of timing these might be quick-wins for early 2021 rather than adding to the load in 2020.

cc @tovari

**Comment by LukeCaley** [comment]
Comments on invision for "Updated UI of the footer".
Updated "country with no emergencies" looks good as proposed.

**Comment by mariam-yu** [comment]
@LukeCaley Sounds good and agreed to push for 2021 not to overload the team for the end of the year. @batpad and @imohkay tagging you as well for your info. The points to consider are:
- Push to login cues across the site: https://docs.google.com/document/d/1rB1pgS-HtlH7NC60tnUlQjtrkLidOogd78yEPOBVqyA/edit
- What to show on countries when they have no data/no emergencies (once the detail pages are build): https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/433294670__Country-NoData
- Updates to footer (to be validated with Luke)

**Comment by mariam-yu** [comment]
> Comments on invision for "Updated UI of the footer".
> Updated "country with no emergencies" looks good as proposed.

@LukeCaley Updated footer with your comments: https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/433294669 Are we good to push this forward? If yes, we will update it across the prototype and @batpad could consider for the backlog. For your info Sanjay:
Medium link: https://medium.com/@ifrcgoproject
Twitter: https://twitter.com/ifrc
Facebook: https://www.facebook.com/IFRC/

And the copyright date should be updated automatically.

**Comment by LukeCaley** [comment]
Footer looks good.  Aside from to add the link to the IFRC YouTube plalist: https://www.youtube.com/playlist?list=PLf2g_NkFyyv5O5KmCXzuROjzWO_gxZ-ZN.  Suggest next step is to detail this task into a GitHub ticket for @batpad & @tovari backlog management - thanks!

**Comment by mariam-yu** [comment]
@LukeCaley Thanks for getting back to us quickly. Just a quick question before we add Youtube, which I think was a point of confusion. Is this public? i.e. ok to share on the main footer? @batpad and @tovari we will drop the footer UI into Zeplin; so ready for whenever you are :)

**Comment by LukeCaley** [comment]
The GO youtube playlist is public but not profiled on the IFRC playlist as not aimed at the same general audience.  So, yeah, please use the GO playlist link for this purpose.

NB The Medium logo has recently been updated, ref: https://medium.design/logos-and-brand-guidelines-f1a01a733592

**Comment by batpad** [comment]
@LukeCaley @mariam-yu - do we still want to do the new footer implementation? If it's approved and has useful links, etc., we can likely get this in. cc @imohkay

**Comment by mariam-yu** [comment]
@batpad somehow I confused and thought this message was from Luke. All good from our side and Luke provided his feedback. All on Zeplin and relevant links above in this thread.
