### ISSUE TITLE
Error messaging review and proposal

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1556]
The task will include reviewing how error messaging is currently presented throughout the platform and propose a "cleanup" and consistent approach both from UX (functional) and UI (visual) aspects.

**Comment by GregoryHorvath** [comment]
Connected PR: https://github.com/IFRCGo/go-frontend/pull/1633 ticket: https://github.com/IFRCGo/go-frontend/issues/1548
![image](https://user-images.githubusercontent.com/30079559/94929424-5d944a80-04c5-11eb-94de-85be18db5695.png)

**Comment by mariam-yu** [comment]
@GregoryHorvath @batpad We did the audit for the error states with some wireframe suggestions: https://docs.google.com/document/d/1WYjUFqExYOjsNTVT5oEGiuaxYFuehZCG7FgJWfYm7wU/edit?usp=sharing Can you please comb through it to see a) if they make sense and respond to the ones you have, b) if we missed any. Once confirmed, we will provide the complete UI design for you to implement them.

For the general alerts, we will provide 3 visual styles (failure, success, informational). it would be great if you guys could provide some examples, as I couldn't find all.

Thank you!

**Comment by tovari** [comment]
@mariam-yu, this is great and very welcomed.
I think, the user registration process could be improved as well. Currently, in case the user doesn't complete the registration and tries to login, he/she doesn't get any information why can't login the site. Some information about the status of the registration would explain the situation and maybe also help the user to complete the registration. E.g. 'The account registration has not been completed yet. Please check your email and confirm your email validity'. It could result less incomplete registration hopefully (currently 15% of registrations remain incomplete).

**Comment by GregoryHorvath** [comment]
@mariam-yu @batpad @tovari All looks wonderful to me. The only error message I can think of this "is missing" from that doc is the "Data not available" where we only show a plain black text currently. I think that can be also covered by your suggestion to the field errors, with a warning sign and red text. Also this shouldn't really happen to users at any time because usually this means an error in the API (or we missed something in the code), but in case it happens I think the red text will be a nice indicator to catch.

Other than that I've only seen the (types of) error messages you listed in the doc.
@tovari I think the registration (and login... when people still try to log in with their email address...) process and the relevant error messages should be another ticket, it would need "some" restructuring too. Since we have the translations some of the error messages are muted, converted into a generic error message because translations wouldn't be able to handle those pop-ups' text since they are hardcoded in the backend code.

**Comment by mariam-yu** [comment]
@GregoryHorvath thanks for the feedback. Why don't we go ahead with the UI, you implement and let's see if anything is missing. For Data Not Available, do you mind dropping a screenshot here?

@tovari Thanks for your feedback as well. We actually have a ticket to review and update the registration/login flow. So, that will be our next thing to tackle. will check that error as well, but error-style-wise that may be covered by the "failure" type of alerts.

Thanks!

**Comment by GregoryHorvath** [comment]
@mariam-yu 2 occurences on the Home page for example (if the API is unreachable)
![image](https://user-images.githubusercontent.com/30079559/95862951-e2078880-0d63-11eb-8f32-a009c8174514.png)

**Comment by mariam-yu** [comment]
@GregoryHorvath Question about the last one - no data available. Is this for the entire page or just specific sections? Meaning, if it's for the entire page, we should probably show the "failure" kind of alert. Thanks!

**Comment by GregoryHorvath** [comment]
@mariam-yu This is showing on most pages if there's no data available - not as a whole page error but inside the sections where the data from the API would go, as shown above.

**Comment by mariam-yu** [comment]
@GregoryHorvath @tovari Please see the updated error fields document; we also replaced the solutions with the UI styling images. You can find all the updated UI in Zeplin. There is a separate section for error handling. Let us know if there is anything else on this. Thanks!

https://docs.google.com/document/d/1WYjUFqExYOjsNTVT5oEGiuaxYFuehZCG7FgJWfYm7wU/edit

**Comment by frozenhelium** [comment]
Initial implementation is available on [testing server](https://ifrc-go-feature-improve-error-and-alerts.surge.sh/)

Available features:
- Improved display of alerts
- Improved display of form field errors (limited to Field Report Form and Global New 3W page for now)
- 404 page

**Comment by batpad** [comment]
@karitotp - would you be able to check the behaviour and display of error messages as part of the field report form testing?

As well as checking field errors on the global new 3w page: https://ifrc-go-feature-improve-error-and-alerts.surge.sh/three-w/new

**Comment by karitotp** [comment]
@batpad @frozenhelium, I tested the field errors and 404 page, and all is working good. But when I try to edit a 3w activity and submit it, I am getting this type of alert even when there are not any required field to fill.

![Screenshot from 2021-05-25 14-57-23](https://user-images.githubusercontent.com/11504548/119561107-65617180-bd6a-11eb-86dd-acc8a8b38977.png)

**Comment by frozenhelium** [comment]
@karitotp Thanks for this.
This one is in the country 3w form right?

I'll check it out!
