### ISSUE TITLE
UI library design (GitHub-based)

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1557]
As discussed with the team, the goal is to incorporate the UI library that is currently hosted in Zeplin into a newly created space on Github. The design team will provide designs and guidelines on the best way to present the elements and pages. @guipizzini tagging you here as well to tackle this together.

**Comment by mariam-yu** [comment]
@LukeCaley while figuring this out with Guido, we thought could be nice to share with you our thoughts as well. We have a quick basic prototype to show the way we are thinking to approach the UI library and the breakdown of elements: https://projects.invisionapp.com/share/6GYYP7LVWXB#/screens/433471457_1-0_UILib_Home (same password as for other prototypes). Please let us know your thoughts. Our next steps are:

- Support Guido and team in figuring out the implementation part using GitHub
- Finalizing the breakdown, structure, and functionality
- Create the UI layout (we are working on that right now)
- Populate the pages with content. For this one, we will need team's support, as we can provide content only for design related sections.

The most immediate step is for us to gather feedback from the team.

Thanks!

Best,

Mariam

**Comment by mariam-yu** [comment]
@imohkay tagging you here as well. You may have already know the context, but if not, happy to discuss with you in detail. We'd love your thoughts on this and how it would be used by devs afterwards.

**Comment by LukeCaley** [comment]
Thanks @guipizzini & @mariam-yu.  In general, looks good to me and in line with other UI library designs.  My only concern would be to ensure that it is obvious to users that they are not in GO and to provide them simple access back. 

In order to move ahead with the next step to 'figuring out the implementation part', it would be great to have a design brief or something similar which we can then use to approach potential support.

**Comment by mariam-yu** [comment]
@LukeCaley Thanks for your feedback (we are so real-time :P) We have been working on the UI aspect to make it look somehow different from GO. We'll share that with you, but also agreed on a simpler link back to GO. We will work on that.

Regarding the design brief, do you have a template or guidelines? Can put something together, but hopefully the wireframes can already be helpful. We will add some more detail into them to make the functionality more explicit. Ideally, it should be using GitHub pages; so, someone who'd be familiar with that process.

We'd also need someone from your side who can generate some of the content. There will be parts that would need to be a bit of "marketing" in a way, but we can tackle that one at a time. Thanks!

**Comment by mariam-yu** [comment]
@LukeCaley As I mentioned, we have been working on the visual aspect of the design library to a) use the same library elements as GO for consistency, but b) to make it standout from GO and look a bit different. Can you please tell what you think about this?

https://projects.invisionapp.com/share/YXZ6K7N6STW#/screens/433781433 The secondary sections (brand/components, etc) offer 3 different styling for secondary pages too.

There is a link to Go in the top right corner, but we can work on making that more explicit (may be "Go to GO" is not that clear :P so we can put "Go to go.ifrc.org"). Thanks!

**Comment by LukeCaley** [comment]
Thanks @mariam-yu - looking good.

Regarding the design brief - this is required so that we can make a clearly structured request for support.  This should include necessary technical competencies, some analysis of the volume of work and examples of successfully completed projects if known.  If you could work with @guipizzini to put at least the bones of this together this week that would be appreciated.

**Comment by mariam-yu** [comment]
@LukeCaley Sure, will sync with Guido on guidance on how to put that brief together. @guipizzini I know your week must be busy, but if let's sync for 15 mins on this? Thanks!

**Comment by mariam-yu** [comment]
@LukeCaley Not really sure how the design brief should be, but threw in here a few paragraphs explaining the library and the need: https://docs.google.com/document/d/1RAJAKmdLI_tOlP9wkL6M15LBatWHfGjhlj0qJ-Mbpnk/edit?usp=sharing Please let me know what you think and feel free to edit it as you wish.

**Comment by LukeCaley** [comment]
This is great.  We are just starting the conversation with a couple of National Societies around potential support, including NLRC @mjvanderveen

**Comment by mariam-yu** [comment]
@LukeCaley So, Maisa and I had a call with Shafqat from BRC to follow up, and here is where we stand:
- I had a feeling getting their code for the UI library may not be super helpful as they haven't completed it yet, and it's quite custom to their own elements. So, it may still be a lot of separate work for devs.
- He did propose to organize a call between devs if we'd like to have more visibility.
- In terms of support, I guess it should be a conversation more between you and Stuart to see what resources they have. The development was done with the internal BRC dev team, which, as I understand, is usually quite busy. Definitely their design systems is a bit bigger as it's across the entire organisation, including various other sections (like templates, mobile apps, websites, etc.), while our focus is on the UI library, specific to GO (for now).

He was, though, very open to collaborate, share, and learn from each other, which is great! So, next steps I guess is to figure out who would be willing to put up our UI library and build it :)
