### ISSUE TITLE
[Staging] Testing of Frontend Translations

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1559]
Creating a separate issue to track testing related to functionality testing of the translation of frontend static strings. We need to test that:

 - The Language Switcher dropdown works to change the language of the all the UI strings.
 - There are no strings in the UI that are not translated (strings in the content / things coming from the backend are not expected to be translated right now).
 - Non-UI strings coming from the database continue to be displayed correctly in English.
 - The language switch works across all pages - all functionality works the same as before.
 - The CSS and styling remains consistent when language changes and some strings become very long, etc. - the layout should not break.
 - Extra testing for Arabic language across all pages to ensure that the layout does not break for the Right-to-Left layout.

@frozenhelium please add any points that I may have missed.

@karitotp will be great if you are able to test this as thoroughly as possible, and not any issues related to changing language and the new translation strings here. @frozenhelium we can then break things out into more specific tickets as and where required.

cc @LukeCaley @nanometrenat @guipizzini

**Comment by nanometrenat** [comment]
@guipizzini are you able to confirm if the above matches your intention?  It is slightly different to my understanding.  I thought we were still translating the config items from the backend - e.g. regions, countries, actions, disaster types etc. - and it's just the user-generated content that would not be translated right now.  However Sanjay's instructions imply that nothing at all from the backend database will be translated at this stage.  Over to you to confirm current scope - cheers

**Comment by batpad** [comment]
@nanometrenat yep - I was enumerating what we had ready for testing as of now, to be able to proceed testing the current state.

Can we edit and add in the Translations of the config items when these items are ready to be tested?

**Comment by karitotp** [comment]
@batpad, Overall almost everything looks good to me.

Where I see a weird behavior when the language is switched, was in the follow chart: 

- In the emergency page in Arabic language, the number chart is far from the graphic

![Selection_047](https://user-images.githubusercontent.com/11504548/92608220-b253f500-f27a-11ea-8803-39fe08c545d7.png)

In a region page in Spanish language, the stat chart is covering the whole graph

![Selection_048](https://user-images.githubusercontent.com/11504548/92612922-fa294b00-f27f-11ea-9c13-f05e9c0706a0.png)

In general, the behavior of this chart is different when the language is changed to other language different to english.

- The Arabic language specification looks weird in the dropdown in PER FORM of account page, same in the list of countries in a region page.

![Screenshot from 2020-09-09 09-51-42](https://user-images.githubusercontent.com/11504548/92614807-14642880-f282-11ea-8568-aa63d5616257.png)

![Screenshot from 2020-09-09 09-20-02](https://user-images.githubusercontent.com/11504548/92613952-209bb600-f281-11ea-9836-eeaa9bb179ad.png)

- The dropdown of menu for user account only works if you clicked is over the letters, same in the Create a report dropdown. Different behavior of the other dropdowns in the site. This is working as this way in the all languages.

![Selection_050](https://user-images.githubusercontent.com/11504548/92615123-63aa5900-f282-11ea-9dff-2dfef20b096d.png)

**Comment by batpad** [comment]
@frozenhelium it seems like we have some interesting issues with the Dropdown, which may also be partially responsible for #1560 . I know @imohkay took a bit of a look at this and there's some `react-tether` library that tries to handle the tethering that may not be dealing so well with RTL.

@frozenhelium would you be able to triage these issues identified and tag @imohkay and me where we can help? It does seem like we may need to look at what we can do about the Dropdown / Tether code. It's likely a good idea for us to speak to @imohkay and get some of her insights into this.

**Comment by batpad** [comment]
@imohkay can we look at the issue of the chart labels on hover appearing very far from the mouse cursor when Arabic is selected as the language? Seems like an issue with the ReCharts plugin, would be good to dig a bit and see what the best fix here is.

@frozenhelium to look at the issues identified with the Dropdown, also related to #1560

**Comment by nanometrenat** [comment]
> @nanometrenat yep - I was enumerating what we had ready for testing as of now, to be able to proceed testing the current state.
> 
> Can we edit and add in the Translations of the config items when these items are ready to be tested?

The config item translation is being tracked under https://github.com/IFRCGo/go-api/issues/888 (not on a board yet)

**Comment by batpad** [comment]
For the ReCharts issue where the labels are appearing far away I found this issue: https://github.com/recharts/recharts/issues/263 - @imohkay would you be able to take a look and see if any of the CSS work-arounds there seem implementable in our case?
cc @frozenhelium

**Comment by batpad** [comment]
@karitotp the issue you identified with the chart labels coming very far from the mouse pointer when Arabic language is selected should now be fixed, could you confirm?

**Comment by karitotp** [comment]
> @karitotp the issue you identified with the chart labels coming very far from the mouse pointer when Arabic language is selected should now be fixed, could you confirm?

It is fixed, @batpad

**Comment by karitotp** [comment]
@batpad, In Arabic language, the header of the form for a new FR does not look good.

![Screenshot from 2020-09-14 09-36-49](https://user-images.githubusercontent.com/11504548/93100418-bf078d00-f66e-11ea-8669-35af59dfc351.png)

**Comment by guipizzini** [comment]
Testing so far moving ahead well.

**Comment by karitotp** [comment]
@batpad, the problem in the dropdown in Arabic language in PER FORM is still there

![Screenshot from 2020-09-09 09-51-42](https://user-images.githubusercontent.com/11504548/92614807-14642880-f282-11ea-8568-aa63d5616257.png)

**Comment by guipizzini** [comment]
This has been completed and widely tested
