### ISSUE TITLE
Deployments page is bugging

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#157]
<img width="1231" alt="screen shot 2018-02-04 at 17 32 40" src="https://user-images.githubusercontent.com/23258092/35779674-73ec765a-09d1-11e8-950f-3fd3a94781d2.png">

When going to the deployments page, nothing is showing up. Is this because there is no data?

If yes, we should have an infobox saying something like "no data to be displayed" or similar to that.

**Comment by dereklieu** [comment]
@guipizzini can you try logging out and logging back in? This looks like a symptom of the front-end thinking you have a valid session token that is now invalid since we wiped the database.

**Comment by dereklieu** [comment]
This is what the deployments page should look like when there's no data.

<img width="601" alt="screen shot 2018-02-03 at 6 44 31 pm" src="https://user-images.githubusercontent.com/1590802/35781438-2ae085aa-09b8-11e8-8344-41afeb29be2e.png">

**Comment by guipizzini** [comment]
correct, works out now. thanks
