### ISSUE TITLE
Bug on API data

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#158]
Hi Derek,

We've noticed that we have some data issues, in addition to those already submitted by @k-som 

Will double check with our IT but pointing this stuff out.

<img width="628" alt="screen shot 2018-02-05 at 08 37 19" src="https://user-images.githubusercontent.com/23258092/35793569-6fd0027c-0a52-11e8-97af-5c10ed29ea7a.png">

**Comment by dereklieu** [comment]
Need clarification on what figures are not correct.

**Comment by k-som** [comment]
@dereklieu figures for DREF operations are almost correct, but we haven't launched any Emergency Appeals this year; that's what we have for this year:
![2018](https://user-images.githubusercontent.com/25579864/35848647-20b5ade0-0b1f-11e8-90fd-1443775e65ba.jpg)
7 DREFs, 1,449,548 CHF total budget, 52,284 people targeted (8 DREFS on the homepage??).

**Comment by guipizzini** [comment]
Hi @dereklieu this one we need to have done in phase 1.0 as its important. Thanks for your understanding.

**Comment by guipizzini** [comment]
For example on the infobox on the graphic, we have 960.6M of funded Emergency Appeals. That is actually quite not the case...

**Comment by dereklieu** [comment]
Pretty sure this is a result of #163 but we should check that after this is deployed. cc @guipizzini @k-som

**Comment by dereklieu** [comment]
Here's the current result for appeals started this year:

https://dsgocdnapi.azureedge.net/api/v1/appeal/?start_date__gte=2018-01-01

Is this accurate?

**Comment by k-som** [comment]
Yes, that is correct - 7 DREF operations only

**Comment by guipizzini** [comment]
And now 8 as DPRK was just launched and it appears correctly.

However the line chart still displays wrong data for the Appeals, see below:

<img width="659" alt="screen shot 2018-02-08 at 11 45 05" src="https://user-images.githubusercontent.com/23258092/35969000-be52ad62-0cc5-11e8-839d-5b2edbb87f7e.png">
