### ISSUE TITLE
[Staging] Header above Field Report looks broken RTL

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1583]
## Issue

Breaking this into a separate issue, the header bar over the field report form looks broken when language is Arabic:

Screenshot:

https://user-images.githubusercontent.com/11504548/93100418-bf078d00-f66e-11ea-8669-35af59dfc351.png

Original report: https://github.com/IFRCGo/go-frontend/issues/1559#issuecomment-692104997

## URL

https://dsgoproxyapp.azurewebsites.net/reports/new

## Steps to reproduce

Go to URL, switch to Arabic from the language menu. The context bar above the field report form looks broken as per screenshot link above.

## Criticality/Urgency

This makes the Field Report form look pretty broken for Arabic users. While it is a cosmetic issue, this seems pretty must fix. But @tovari @LukeCaley, will leave to one of you to add the `Must Fix` label as you feel appropriate. Currently treating this as something we need to fix for this release.

cc @guipizzini

**Comment by batpad** [comment]
Fix for this has been merged.

@karitotp could you please test and confirm that the header above the field report now looks and behaves correctly when Arabic is selected as the language?

**Comment by karitotp** [comment]
@batpad, the test shoul be do in staging? If so, it is still broken.

**Comment by batpad** [comment]
@karitotp sorry seems like there was some problem with the deploy, this should be on staging now.

**Comment by karitotp** [comment]
:+1: it is fixed!
