### ISSUE TITLE
[Staging] 3W form - dropdown boxes not loading

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1589]
## Issue
On the form to create a new 3W entry, the dropdown boxes for 'Reporting national society' and 'Country' display 'No results found'.
![image](https://user-images.githubusercontent.com/6359748/93369868-e5cceb80-f847-11ea-9520-eca84e30583e.png)

## URL
e.g. https://dsgoproxyapp.azurewebsites.net/emergencies/4043#details

## Steps to reproduce
- Go to URL above
- Click 'Create 3W activity' button in top right
- Click 'Reporting national society' or 'country' drop down 

## Expected behaviour
Searchable list of national societies or countries

## Related feature
Geo stuff? #1534 ?

## Criticality/Urgency
Urgent if the behaviour will be the same on prod after release.

**Comment by jhenshall** [comment]
cc @geohacker incase related to geo stuff.

**Comment by batpad** [comment]
@frozenhelium @GregoryHorvath can this be moved to Ready For QA?

**Comment by frozenhelium** [comment]
Yepp
