### ISSUE TITLE
IFRC Team doing the Functional Testing of Go

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#159]
1. When submitting a field report, this one does not feed/appear on the "Emergency Map". The emergency map should show the inputs of GDACS as well as the ones from the field reports.

**Comment by guipizzini** [comment]
2. When we try to modify the password, the email is received by the user but then the link in the email where he is redirected gives the following error:

![image001](https://user-images.githubusercontent.com/23258092/35795163-956a7c96-0a58-11e8-8d0f-dcd5447ca1ba.png)

**Comment by guipizzini** [comment]
3. The names of the "Organization Type" when registering should change as follow:

---> Remove "Delegation"
---> Change "Secretariat" to "IFRC"

**Comment by guipizzini** [comment]
4. Making all "Error" messages more visible at the "center" of the page, rather at the bottom right corner. This is not a priority, but could be a good one in terms of user experience.

**Comment by guipizzini** [comment]
4. Can we make the "Country" not selectable? On the Emergency page, we have the country at the far right. When selecting that one, we get the following message saying the page is missing. This is because we do not have yet the "country page". We suggest we make the countries not selectable for now, we will be able to run this up in GO Phase 2.0.

<img width="1234" alt="screen shot 2018-02-05 at 09 56 22" src="https://user-images.githubusercontent.com/23258092/35795843-da3c4fbe-0a5a-11e8-926d-2fa67583a396.png">

**Comment by guipizzini** [comment]
5. In the API it seems that we are pulling into GO the value of "ModifyTime". For all DREFs and Emergency Appeals we should focus only on the "StartDate". This means that we do not filter the most recent update, but only the launch/start of the Operation.

For example, if we look into "Africa Region" we will see the most recent event is Cyclone Enawo.

This should not be the case, as Madagascar was launched sometime in March last year. It has been updated just recently, but we do not want to track that. Just the most recently launched Appeals and DREFs.

<img width="1184" alt="screen shot 2018-02-05 at 10 05 19" src="https://user-images.githubusercontent.com/23258092/35796261-443b91e4-0a5c-11e8-8aee-f4ee5e965065.png">

**Comment by guipizzini** [comment]
6. We need to rephrase the "heading" for the emergency page.

Requested Amount (CHF) to change to ---> Requested Amount (CHF) in the last 30 days
Funding (CHF) to change to ---> Funding (CHF) received in the last 30 days

<img width="1245" alt="screen shot 2018-02-05 at 10 23 33" src="https://user-images.githubusercontent.com/23258092/35797107-f29b3490-0a5e-11e8-8483-039466a5ba10.png">

**Comment by guipizzini** [comment]
7. When entering emails in the registration form, if emails get an error message because they are case sensitive. Can we change, this please?

**Comment by guipizzini** [comment]
8. When a non-IFRC user is registering, the notification to the two IFRC users goes for validation.

However even if only one IFRC user validates the new non-IFRC user request, it will get approved in the database as an active user without the second level of validation from the IFRC.

As well, the non IFRC user does not get any notification of his account being validated.

**Comment by dereklieu** [comment]
All of these points are either fixed or created as separate issues. @guipizzini please create individual tickets for each to-do, otherwise it becomes easier for them to get lost.

**Comment by guipizzini** [comment]
noted, thanks!
