### ISSUE TITLE
[Staging] Refactor account details to support translation

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1596]
## Issue
Account details is currently rendered from map of the database fields
```js
const profileAttributes = [
  ['username'],
  ['first_name', 'firstName'],
  ['last_name', 'lastName'],
  ['email'],
  ['profile.phone_number', 'phoneNumber'],
  ['profile.city', 'city'],
  ['profile.org', 'org'],
  ['profile.org_type', 'orgType'],
  ['profile.department', 'department'],
  ['profile.position', 'position']
];

```

We cannot translate for this type of fields. We need to separate it out to individual fields and appropriately add translations.

**Comment by tovari** [comment]
Hi @frozenhelium, this is already resolved, right?

**Comment by frozenhelium** [comment]
@tovari No, this is an active issue

**Comment by nanometrenat** [comment]
@frozenhelium is this still an active issue?

**Comment by frozenhelium** [comment]
@nanometrenat This issue is obsolete now and can be safely closed.
