### ISSUE TITLE
Create option to mute green event notifications

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#160]
@guipizzini this actually isn't as easy as I had thought. To save on dev time, I think this should be pushed to phase 2, as it's not immediately breaking anything or hampering how the system is used.

**Comment by guipizzini** [comment]
Ok, we plan it for phase 2.0

Thanks

**Comment by guipizzini** [comment]
Hi @dereklieu this seems to be working, hence I will close it. Thanks
