### ISSUE TITLE
[PROD] Non-RCRC registrations: verifier's email is case-sensitive

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1601]
## Issue
A user with a non-RCRC email was unable to register and kept getting errors saying 'Non-IFRC users must submit two valid admin emails.' The admin emails they were trying to use were confirmed as active users but with some capital letters in their email address, it was only when the case was matched that the user successfully registered.

## Steps to reproduce
- [Go to register page](https://go.ifrc.org/register)
- Enter all the details in the form using a non-RCRC email address
- Enter the details of two people to verify who are already active users but use the wrong case

## Expected behaviour
Casing of email is ignored and user able to register

## Impact
Volume of users at risk of encountering this is likely low but important to have fixed.

## Is there a workaround?
Users contact IM because of problem and we can find the exact entry for each email.

**Comment by tovari** [comment]
This has been resolved in https://github.com/IFRCGo/go-frontend/issues/1645
