### ISSUE TITLE
[Staging] Notifications - Country level notification settings are not saved

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1604]
## Issue
*On the Notifications page, Country level notification settings cannot be saved. There is no error, but selected country settings are not saved.*

## URL
*https://dsgoproxyapp.azurewebsites.net/account#notifications*

## Steps to reproduce
*Go To Account - Notifications. Add countries to the Country level notification list. Save page. Go Home, go back to Account - Notifications. The country is not visible, only an empty label is visible in the country list.*

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
*List of countries should be saved in the list.*

## Related feature
**

## Criticality/Urgency
*Important*

**Comment by tovari** [comment]
Hi @GregoryHorvath, @frozenhelium,
now the same country can be added multiple times, if we change the language:
Add country - Change language - Add the same country - ...
![image](https://user-images.githubusercontent.com/68283148/93765110-a4a45500-fc14-11ea-8c61-7d3da82b2576.png)

**Comment by GregoryHorvath** [comment]
@tovari This seems to be an older bug where if you reload the page with F5 sometimes it populates the list with duplicates. At least I can't recall if this has been fixed for production or not yet, I'll have to check.

cc @batpad

**Comment by tovari** [comment]
The country notifications can be saved now. The ticket will be moved to Done.
Another ticket will be created for the issue that a country can be added multiple times.
