### ISSUE TITLE
[Staging] Missing translations

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1605]
## Issue
*This is a collection of still not translated strings . 
*

## URL
**

## Steps to reproduce
* - Missing translation on password change page: 'Verify old password'
*

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
*.*

## Related feature
**

## Criticality/Urgency
*Important*

**Comment by guipizzini** [comment]
All strings have been translated and uploaded correctly into the site
