### ISSUE TITLE
Submitting a field report causes it not to show up in the emergencies map

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#161]
This is expected behavior. The emergency map shows emergencies. Emergencies are separate from field reports.

For it to show up on the map it must have a linked emergency.

![screen shot 2018-02-05 at 4 31 05 pm](https://user-images.githubusercontent.com/1590802/35829784-feec9fa8-0a91-11e8-8849-639dec3f5b1b.png)

**Comment by guipizzini** [comment]
We will do this manually, as agreed on phase 1.0.

This will be moved to phase 2.0.

Thank you

**Comment by dereklieu** [comment]
Field reports without an emergency create a separate emergency.
