### ISSUE TITLE
[Staging] Number of FRs in a specific emergency page is not displayed in Arabic language

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1616]
## Issue
The number of Field Reports of an emergency is not displayed in Arabic language.

## Steps to reproduce
In Arabic language, go to an specific emergency and go to the field reports section. Example: https://dsgoproxyapp.azurewebsites.net/emergencies/4054#details
![Selection_052](https://user-images.githubusercontent.com/11504548/93781230-c5f24a80-fbee-11ea-81e5-7bf3190f5124.png)

## Expected behaviour
In the other languages, it appears correctly.
![Selection_053](https://user-images.githubusercontent.com/11504548/93781436-ffc35100-fbee-11ea-8c44-cc137badfcd5.png)

**Comment by batpad** [comment]
@tovari it would be good to confirm this bug / behaviour, and prioritize fixing?

**Comment by tovari** [comment]
This has been fixed by #1772
