### ISSUE TITLE
[PROD] Translations - Missing, incorrect translations

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1620]
## Issue
*This is a collection of missing or not correctly translated components. Please report issues in comments! *

## Steps to reproduce
**

**

## Expected behaviour
**

## Related feature
**

## Impact
**

## Severity
*.*

## Is there a workaround?
**

**Comment by anamariaescobar** [comment]
The search box message is coming in english. Happening in all languages.
![image](https://user-images.githubusercontent.com/69478743/94013853-fd0d5b00-fdaa-11ea-9e26-adcee2d4afad.png)

**Comment by anamariaescobar** [comment]
In the region list, Asia Pacific is listed as Region Asia-Pacifico (Asia- Pacific Region) can we change it to only Asia-Pacifico (Asia-Pacific) to mantain consistency with the other regions names?

Likewise in the region page is listed as Region Asia-Pacifico.
![image](https://user-images.githubusercontent.com/69478743/94014558-fd5a2600-fdab-11ea-884e-3fe6756d33ef.png)

![image](https://user-images.githubusercontent.com/69478743/94014821-5629be80-fdac-11ea-8473-c3c45dcc53ac.png)

**Comment by anamariaescobar** [comment]
The tabs on the Operations pages remain in english.

https://go.ifrc.org/emergencies/3972#details

![image](https://user-images.githubusercontent.com/69478743/94015064-a9037600-fdac-11ea-8d9e-b2fa52d7363e.png)

**Comment by anamariaescobar** [comment]
The whole section (tittle and add a report button) of the emergencies page relating to response documents remains in english.

https://go.ifrc.org/emergencies/3972#details

![image](https://user-images.githubusercontent.com/69478743/94015310-fbdd2d80-fdac-11ea-9309-ef36ab1b7e65.png)

**Comment by tovari** [comment]
Emergency page tab titles (Emergency details, Additional information) is not translated.

![image](https://user-images.githubusercontent.com/68283148/94027418-1ae2bc00-fdbb-11ea-97c6-f7c761241a71.png)

**Comment by anamariaescobar** [comment]
This is a double one!

The key figures in Emergency pages not translates, also note how not all the figures are visible (First key figure just showing half)

![image](https://user-images.githubusercontent.com/69478743/94028237-03580300-fdbc-11ea-8fac-56374b7f6e75.png)

**Comment by tovari** [comment]
Som breadcrumbs are not completely translated:

![image](https://user-images.githubusercontent.com/68283148/94032486-4c11bb00-fdc0-11ea-873f-9ea4fe0e5dd5.png)

![image](https://user-images.githubusercontent.com/68283148/94032841-aa3e9e00-fdc0-11ea-837f-69e6df00ea91.png)

![image](https://user-images.githubusercontent.com/68283148/94033074-e4a83b00-fdc0-11ea-87e2-ade65f852e44.png)

**Comment by tovari** [comment]
Emergencies map items like Key, scale points by, and pop up window content are not translated.

![image](https://user-images.githubusercontent.com/68283148/94039168-a3fff000-fdc7-11ea-8519-457379f548cb.png)

**Comment by tovari** [comment]
https://go.ifrc.org/regions/3#operations

Map filter drop-downs are partially translated (Appeal types and Date are not):

![image](https://user-images.githubusercontent.com/68283148/94039768-69e31e00-fdc8-11ea-91fd-819dee5074a3.png)

**Comment by tovari** [comment]
https://go.ifrc.org/about
This is not translated:
![image](https://user-images.githubusercontent.com/68283148/94125075-2c2cd680-fe56-11ea-8f58-b0900a5f9917.png)

**Comment by GregoryHorvath** [comment]
> In the region list, Asia Pacific is listed as Region Asia-Pacifico (Asia- Pacific Region) can we change it to only Asia-Pacifico (Asia-Pacific) to mantain consistency with the other regions names?
> 
> Likewise in the region page is listed as Region Asia-Pacifico.

Seems like we're not pulling the Region name translations from the backend but having them in those static frontend translations (accessible at `/translation-dashboard`). I guess it would be better to use the backend's for these?

cc @batpad @frozenhelium

**Comment by tovari** [comment]
Created a new ticket for the missing translation option for the key figures:
https://github.com/IFRCGo/go-frontend/issues/1831

> This is a double one!
> 
> The key figures in Emergency pages not translates, also note how not all the figures are visible (First key figure just showing half)
> 
> https://prddsgoproxyapp.azurewebsites.net/emergencies/3751#details
