### ISSUE TITLE
[PROD] Editing Field Reports on frontend overwrites values in EN and deletes values in ES, FR, AR

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1625]
## Issue
*In case a FR has content in multiple languages (added on the Admin site), and the FR is being edited on the frontend, then the content will be saved in EN fields while ES, FR, AR content will be deleted.*

## Steps to reproduce
*1. Create a field report
2. Using the Admin site, add translation to the text.
3. Using the frontend site, edit the FR and save it.
4. The content will be saved to EN and content on other languages will be deleted.*

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
*Editing FR on the frontend should overwrite the fields only in the display language. E.g. in case the ES field is displayed, only the ES field should be updated.*

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
*This affects users, who would like to add text in multiple languages.*

## Severity
*This can lead to data loss.*

## Is there a workaround?
*Important and urgent*

**Comment by batpad** [comment]
I can see adding translations in the Admin and then editing the Field Report form in the frontend can be tricky.

There are two problems here:

In Edit mode, the fields will show as per the language the user currently has selected, even though it always saves as English. Hence, we must make sure when editing the Field Report, the user always sees only english values.

The second problem is when editing a field report, the backend is saving the english values and clearing the other language values. This was likely done to ensure the remaining fields get auto-translated again. Here, we should make sure that we save the edited english values and do not touch anything in the translation fields. They can continue to be managed in the Admin.

This way, the Field Report form on the frontend always deals with english, and the translations can be managed in the Admin.

**Comment by batpad** [comment]
cc @thenav56 in case you see an obvious fix to this - especially the second issue: is there a clean / easy way to avoid content of translation fields being emptied when saving english?

**Comment by thenav56** [comment]
@batpad  The fix is easy. I forgot to provide this before while disabling auto-translation changes.

This diff should be enough. cc: @GregoryHorvath 
```diff
diff --git a/lang/serializers.py b/lang/serializers.py
index 3c26a4a..502b430 100644
--- a/lang/serializers.py
+++ b/lang/serializers.py
@@ -130,6 +130,7 @@ class TranslatedModelSerializerMixin(serializers.ModelSerializer):
     @classmethod
     def reset_and_trigger_translation_fields(cls, instance, created=False):
         """
+        NOTE: Not used right now
         To be used directly for a Model instance to reset (if value is changed) and trigger translation.
         """
         if created:
@@ -174,8 +175,10 @@ class TranslatedModelSerializerMixin(serializers.ModelSerializer):
         return instance
 
     def update(self, instance, validated_data):
-        if self._get_language_clear_validated_data(instance, validated_data, self.included_fields_lang):
-            self.trigger_field_translation(instance)
+        # NOTE: Skip reset+triggering translation (Keeping for test cases)
+        if settings.TESTING:
+            if self._get_language_clear_validated_data(instance, validated_data, self.included_fields_lang):
+                self.trigger_field_translation(instance)
         return super().update(instance, validated_data)
```

**Comment by GregoryHorvath** [comment]
This was deployed as a hotfix via the above PR.
