### ISSUE TITLE
[PROD] Register page - National Society dropdown not working

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1627]
## Issue
On the register page for new user sign-ups - when you select `Organization Type` as `National Society`, the `Organization Name` drop-down doesn't pull through any of the National Societies.

As the field is mandatory, this means that no new users from National Societies are able to sign up.

## Steps to reproduce
- https://go.ifrc.org/register
- Under  `Organization Type` select `National Society`
- Click `Organization Name` drop-down

![image](https://user-images.githubusercontent.com/6359748/94258640-0b7f8200-ff25-11ea-8f3c-aa2ca5ca1205.png)

## Expected behaviour
List of National Societies in drop down

## Impact
All new users from National Societies

## Severity
Critical - new users unable to sign-up

**Comment by nanometrenat** [comment]
@jhenshall I'm going to take the liberty of closing this as I just registered as a National Society member and the process let me continue as NZRC :)
