### ISSUE TITLE
Use start date for appeals

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#163]
> In the API it seems that we are pulling into GO the value of "ModifyTime". For all DREFs and Emergency Appeals we should focus only on the "StartDate". This means that we do not filter the most recent update, but only the launch/start of the Operation.

> For example, if we look into "Africa Region" we will see the most recent event is Cyclone Enawo.

> This should not be the case, as Madagascar was launched sometime in March last year. It has been updated just recently, but we do not want to track that. Just the most recently launched Appeals and DREFs.

<img width="1184" alt="screen shot 2018-02-05 at 10 05 19" src="https://user-images.githubusercontent.com/23258092/35796261-443b91e4-0a5c-11e8-8aee-f4ee5e965065.png">

**Comment by dereklieu** [comment]
@guipizzini This appeal was ingested with a start date of 2018-01-19. Here's the record in the admin:

https://dsgocdnapi.azureedge.net/admin/api/appeal/3019/change/

Your internal appeals API outputs appeal "Details" as separate items. This appears to be revisions of an appeal. We are currently finding the most recent one and updating based on that. For each one, as you can see, both the start date and end date get updated.

I'm not sure the best way to ingest this data at this point. I think this data ingestion is causing the inaccuracies you've pointed out in other tickets. 

Here sample output from your API:

![screen shot 2018-02-05 at 5 02 45 pm](https://user-images.githubusercontent.com/1590802/35831088-8fe8f8d6-0a96-11e8-9647-a16196728f7d.png)

**Comment by guipizzini** [comment]
@dereklieu thanks for this, we track as start date only the first date of when the appeal was launched which in this case would be 2017-03-12. We do not filter by the most recently updated appeals. Does this make sense? Thanks a lot, could we keep track only of the first date and just update all the other values in the system (target / funding) ?

<img width="453" alt="screen shot 2018-02-06 at 18 29 58" src="https://user-images.githubusercontent.com/23258092/35874104-ebe64c76-0b6b-11e8-9e96-13d63f23530a.png">

**Comment by dereklieu** [comment]
This now shows the correct start date:

https://dsgocdnapi.azureedge.net/api/v1/appeal/?event=21

<img width="408" alt="screen shot 2018-02-07 at 6 38 58 pm" src="https://user-images.githubusercontent.com/1590802/35947508-2e755e0e-0c36-11e8-97ac-98693b5ed66a.png">
