### ISSUE TITLE
Add Finnish Red Cross logo to Resources page

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1634]
**Is your feature request related to a problem? Please describe.**
GO has received dedicated personnel and funding support from Finnish Red Cross so this should be acknowledged with their logo on the Resources `https://go.ifrc.org/about` page 

**Describe the solution you'd like**
5 logos on the top row - American, Australian, British, Canadian, Finnish
4 logos on the bottom row -  Japanese, Netherlands, Spanish, Ericsson
Alphabetical and centred on each row

**Links to documentation**
https://github.com/IFRCGo/logos/tree/master/national-societies/FIN_Finnish-Red-Cross

**Comment by frozenhelium** [comment]
![2021-05-21-164549](https://user-images.githubusercontent.com/4931541/119127438-0cd16200-ba54-11eb-9897-dd7e7c00dc66.png)

**Comment by LukeCaley** [comment]
Looks great.  Thanks!
