### ISSUE TITLE
[PROD] Appeal ingest - country mismatches to Singapore, Clusters & Regions

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1636]
## Issue
Some appeals are being mapped to the wrong countries during the ingest. The whole mapping process should be reviewed but this outlines two immediate issues that could be fixed to improve the data in the short term.

**1. Appeals are being matched to regions and clusters, rather than countries**
Clusters and regions in the countries table use the same ISO as the country that the offices are based in. Previously, appeals were correctly mapped to the country that the office is in, now with duplicate ISO codes, some are being matched to cluster / region instead. e.g. Appeals in Kenya appear as Africa region.

**2. Appeals for the Sahel Country Cluster are being mapped to Singapore**
There is a lookup table as part of the appeal ingest. The following line has a mistake: 
`'WAF': 'SG', # Sahel country cluster: Senegal`
'SG' should instead be 'SN' for Senegal. There is also the issue of duplicates in the lookup table, but needs more thought.

## Steps to reproduce
Singapore list of appeals: https://go.ifrc.org/appeals/all/?country=153

## Expected behaviour
Appeals are only mapped to countries and the correct country.

## Impact
High - the API is currently serving wrong data

cc: @GregoryHorvath @geohacker @batpad

**Comment by GregoryHorvath** [comment]
So the duplicates are:
```python
'WAF': 'NG', # Western Africa country cluster: Nigeria
'WAF': 'SG', # Sahel country cluster: Senegal
'SAM': 'AR', # South Cone and Brazil Country Cluster Office: Argentina
'SAM': 'PE', # Andean Country Cluster Office: Peru
```

I'm changing `SG` -> `SN` for now and removing the other `WAF`. Need input for which `SAM` to keep. We can't really map one thing to multiple different things, there's no way to tell which one should work in which case  (maybe they are also dependent on other fields coming from the Appeals API?).

Also in the next PR (will appear below in a few minutes), I'll also filter the queryset (which tries to get the Country by the ISO) by `record_type=1` (must be 'Country' type).

Soon to be on staging.

**Comment by GregoryHorvath** [comment]
@jhenshall @mmusori I've checked our pre-release dump of the database, there we only have Appeals mapped to Countries, and none mapped to Regions, Clusters, etc. So I guess we should be good to go with the above change of explicitly filtering for `record_type=1` aka `Type: Country` records when trying to match by `ISO`?

**Comment by jhenshall** [comment]
Sounds good to me @GregoryHorvath ! Going to checkout the duplicates now to see if we can sort that in the same fix.

**Comment by jhenshall** [comment]
For reference, we have decided to leave the duplicates for now. It needs some business decisions and don't want to block getting the bigger fix out. We should review the whole mapping of appeal to country, as well as how we handle clusters and regions as part of the wider geo-review. cc. @geohacker

**Comment by GregoryHorvath** [comment]
If we want to go with changing the database structure - my initial idea for separating the different types of records (just a quick mockup):
1. Create new tables for each `record_type` a `Country` object can have (Region, Cluster, etc)
2. Copy the separate types into their new respective tables
3. Change the relations so Countries would have their Region mapped to the new table's records
4. Create new endpoints, serializers, etc for the new tables
5. Change the frontend pages, actions, etc to use the new endpoints if needed
6. Remove all the hard-coded `enum`s and deprecated fields from the `api_country` table

cc @batpad @geohacker

**Comment by jhenshall** [comment]
Immediate issue fixed and wider question of how clusters and regions handled compiled into new ticket - #1639
