### ISSUE TITLE
ESSN - custom tabs on country pages

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1637]
**Is your feature request related to a problem? Please describe.**
ESSN operations would like to publish content on the Turkey country page. Therefore we need to add the option to create custom tabs on country pages.

**Describe the solution you'd like**
Just like in case of the Emergency pages on the Admin site, we need an option to add a custom tab on the country pages. The tab editing should work as it works now on the emergency pages. Users should be allowed to add custom content to the page. 

**Describe alternatives you've considered**
Alternatively, we need only the custom tab on the Turkey country page.

**Additional context**

**Where does the data come from and how is it maintained?**
NA

**Should there be any restrictions around viewing or updating information related to this feature**
Country page administrator should be able to **set visibility of the custom tab** (to be confirmed) and the should be able to restrict snippet visibility for public.

**Links to documentation**
tba

**Comment by tovari** [comment]
@mmusori, would you be able to confirm the minimum number of additional tabs required for Africa?

**Comment by mariam-yu** [comment]
@tovari You moved the task to the design stage. What do we need to do here? @mmusori Is this also where we'd make country page updates as per Africa Ops Room?

**Comment by tovari** [comment]
@mariam-yu, sorry, I was not sure if the custom tabs request handling was considered during the new region page tab redesign. We don't need design updates here, as we don't plan to add standardized content. 
I push this ticket forward.

**Comment by tovari** [comment]
Closing this as it is part of https://github.com/IFRCGo/go-frontend/issues/1621
