### ISSUE TITLE
Update mapbox styling and functionality

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1642]
## Issue
This is a master ticket to bring together existing issues for updating the map styles and functionality, including design review, Mapbox styling and some frontend changes. Some have come from the existing geo master ticket #938.

The main map design ticket already has lots of details: #1202

cc @geohacker @batpad @tovari

**Comment by batpad** [comment]
Made the change to not highlight countries on hover, but you can still click on them to see the popup.

**Comment by karitotp** [comment]
Functionalities on the map are working as expected.

**Comment by jhenshall** [comment]
Closing this ticket because it's a duplicate with all the details captured in #1202
