### ISSUE TITLE
Make map labels translatable as per user language

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1652]
Creating this issue to track the feature of making the map labels translatable.

This will be released in v4.4.3.

When you switch language, country names on the map will switch to the language you have selected. We don't yet have translations for "Districts", so at higher zoom levels, districts will still show up as English, but perhaps we can ticket this separately?

cc @geohacker @jhenshall @tovari

**Comment by tovari** [comment]
Checked on Prod.
