### ISSUE TITLE
Early Warning Field Report has a wrong label on the 3rd page.

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#1654]
## Issue
 In the Early Action page of the Early Action Field Report the is a duplication of the the label number of people assisted by government see below. 
![image](https://user-images.githubusercontent.com/7780809/96096364-0e401800-0ed0-11eb-9e8e-8d3bbdc8176e.png)

## Steps to reproduce
Navigate to the Early actions part of the Early Action Field report. 
https://dsgoproxyapp.azurewebsites.net/reports/new

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
The second field in the in the first tab should read " Number of people assisted by RCRC-Early Action as in the wire frame. See snippet below.
![image](https://user-images.githubusercontent.com/7780809/96096726-6f67eb80-0ed0-11eb-927d-65354a5cbd44.png)

As see the wireframe.
https://projects.invisionapp.com/share/59WZFUYEFTM#/screens/409814233

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
High. A user has already spotted this and wants to understand.

**Comment by GregoryHorvath** [comment]
The fix is on production already, the right textbox was using the wrong label.

**Comment by mmusori** [comment]
I have tested the fix is now live both in staging and in production. Thanks.
