### ISSUE TITLE
Molnix Integration: Map Molnix Open Positions to GO Surge Alerts

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1659]
We will query the Molnix API for Open Positions and populate / sync the GO database for Surge Alerts. This issue outlines the fields in both systems, and needs clarification / agreement on how we map these fields and what data from Molnix we need to store in GO.

I will create a separate issue to map Deployments in Molnix to GO.

@anamariaescobar will be great if you can go through this and then am happy to get on a call to go over these details, or if some of these clarifications are straightforward, we could just clarify on this ticket - thank you!

### Map Molnix Open Positions to GO Surge Alerts

Molnix API URL: https://api.ifrc-staging.rpm.molnix.com/api/positions
To filter for only open positions: https://api.ifrc-staging.rpm.molnix.com/api/positions/open

Data for each position on Molnix:

 - id: ID in Molnix system. We should save a reference as `molnix_id`
 - created_by: Maps to a user ID in Molnix. We should ignore this for the GO import.
 - created_from: Not sure what this field indicates, and if we need it in GO
 - process_id: Again, not sure what this is and if we need it in GO
 - name: Name of the position. (Maps to `message` in current SurgeAlert schema?)
 - status: active / inactive (we would only import active positions into GO?)
 - ispublic: Do we need to take this into consideration / not important things that are not public?
 - visibletoapplicants: Same as above
 - salary: Array field in Molnix. Safe to ignore for GO?
 - opens: Datetime timestamp of when the position opens. We don't have a field for this in GO currently. Do we need it?
 - closes: Same as above.
 - start: Same question as above
 - end: Same question as above.
 - notes: I don't see this filled in for positions on staging - do we need these in GO?
 - end_permanent: (true or false) - not sure what this field is for and if we need it in GO
 - process: Object with more details of "process" - i.e. name - Global Alert-1 Language. Do we need "process" details from Molnix in GO?
 - process_phases: similar to above.
 - entry_phase: similar to above.
 - tags: List of tags in Molnix system. We will use the tag `OP-<id>` to attach the position to an Emergency id. Do we need to store the other tags or display them on GO?
 - country: Details of country. We will map this to a country within GO by ISO code.

Current fields we have for Surge Alerts in GO:

 - `atype`: Surge Alert type: One of FACT, SIMS, ERU, DHEOPS, HEOPS, SURGE, RAPID_RESPONSE.
 - `category`: One of INFO, DEPLOYMENT, ALERT, SHELTER, STAND_DOWN
 - `operation`: Text field for name of operation (not associated with Emergency in GO)
 - `message`: Message of Surge Alert. Text field, used as title.
 - `deployment_needed`: Boolean field.
 - `is_private`: Do we derive this from the `ispublic` field from Molnix?
 - `event`: Link to Emergency, derived from `OP-` tag on Molnix
 - `created_at`: Creation timestamp, autogenerated in database.

### Questions

 - Can we derive the Surge Alert Type from the current Molnix data? Do we still need a type? Do we need a different classification scheme?
 - Same with `category`.
 - We will only import positions from Molnix that have an Emergency ID associated, hence the `operation` text field will always be blank. Is this a correct assumption?
 - The `message` field on GO will be populated from the `name` field on Molnix. Is this correct?
 - We have a deployment_needed field on GO, do we need this? Does some data from Molnix map to this field value?
 - We map the `ispublic` field in Molnix to the `is_private` field in GO. Is that correct? Do we need this public / private information, and related, if yes, what are the permission levels of who can see which alerts?

### Additional fields in GO

We will need additional fields in GO for:

 - `molnix_id` - where we store a reference to the id in Molnix
 - `opens`, `closes`, `start`, `end`: Do we want these fields in GO?
 - `tags`: Do we want to store the different Molnix tags in GO? Do we need to assign special meanings to some Tags in Molnix, to for eg. map positions to Alert Types and Categories?

**Comment by anamariaescobar** [comment]
Hi! I talked a little a bit with the Surge team about this, these are some of the answers and some points that we might need to discuss over the meeting on tuesday

Data for each position on Molnix:

id: ID in Molnix system. We should save a reference as molnix_id **Correct**
created_by: Maps to a user ID in Molnix. We should ignore this for the GO import. **Agree, we don't need this field.**
created_from: Not sure what this field indicates, and if we need it in GO. **We don't need it in GO.**
process_id: Again, not sure what this is and if we need it in GO. **We don't need it in GO.**
name: Name of the position. (Maps to message in current SurgeAlert schema?) **Yes. this would be transfer into message.**
status: active / inactive (we would only import active positions into GO?). **Yes, we need to discuss what is going to happen with the stand down positions, where they should go, etc.**
ispublic: Do we need to take this into consideration / not important things that are not public? **This field is not being used by the surge team, it was in the Molnix system before.** 
visibletoapplicants: Same as above. **Same as above.**
salary: Array field in Molnix. Safe to ignore for GO? **Yeah, shouldn't be in GO. Surge team won't be using this field either.**
opens: Datetime timestamp of when the position opens. We don't have a field for this in GO currently. Do we need it? **We do, for the launch of the "open alert" and also for the deployed personnel.**
closes: Same as above. **Same as above**
start: Same question as above. **Same as above**
end: Same question as above. **Same as above**
notes: I don't see this filled in for positions on staging - do we need these in GO? **We dont need them in GO**
end_permanent: (true or false) - not sure what this field is for and if we need it in GO. **Field previously in Molnix, Surge team doesnt uses it.**
process: Object with more details of "process" - i.e. name - Global Alert-1 Language. Do we need "process" details from Molnix in GO? **We dont need process details in GO**
process_phases: similar to above. **Same as above, not needed**
entry_phase: similar to above. **Same as above, not needed.**
tags: List of tags in Molnix system. We will use the tag OP-<id> to attach the position to an Emergency id. Do we need to store the other tags or display them on GO? **mmmmmm this is an interest one! I think in the final document there is no mention about this, but it would really good to have them in GO, as this way we could keep track of thing like how many profiles are being deployed to each type of emergency. We can discuss this on tuesday.**
country: Details of country. We will map this to a country within GO by ISO code. **Agree**

Current fields we have for Surge Alerts in GO:

atype: Surge Alert type: One of FACT, SIMS, ERU, DHEOPS, HEOPS, SURGE, RAPID_RESPONSE. **All the ones coming from Molnix will be Rapid Response, FACT, SURGE, HEOPS and DEHEOPS should dissappear, HEOPS will be managed by Molnix but they will be identified by a tag........we need to think about this one. SIMS and ERU wont be managed through Molnix, so as discussed before they will be need to be updated manually.**
category: One of INFO, DEPLOYMENT, ALERT, SHELTER, STAND_DOWN. **Surge team will confirm about this one.**
operation: Text field for name of operation (not associated with Emergency in GO)
message: Message of Surge Alert. Text field, used as title.
deployment_needed: Boolean field.
is_private: Do we derive this from the ispublic field from Molnix? **They wont be using this field.**
event: Link to Emergency, derived from OP- tag on Molnix
created_at: Creation timestamp, autogenerated in database.
Questions
Can we derive the Surge Alert Type from the current Molnix data? Do we still need a type? Do we need a different classification scheme? **As mention above, some types will dissappear, and some should stay. Need more discussion around this one.**
Same with category. **Surge team to comfirm.**
We will only import positions from Molnix that have an Emergency ID associated, hence the operation text field will always be blank. Is this a correct assumption? **The operation text field in GO? can it be populated using the ID?**
The message field on GO will be populated from the name field on Molnix. Is this correct? **Correct**
We have a deployment_needed field on GO, do we need this? Does some data from Molnix map to this field value? **I really dont see why we would need it.**
We map the ispublic field in Molnix to the is_private field in GO. Is that correct? Do we need this public / private information, and related, if yes, what are the permission levels of who can see which alerts? **The permisions should remain the same as they are now, only logged users will be able to see both the alerts and the deployed personnel. The no-logged in users will only see that there is an alert.**
Additional fields in GO
We will need additional fields in GO for:

molnix_id - where we store a reference to the id in Molnix. **Agreed.**
opens, closes, start, end: Do we want these fields in GO? **We do want them.**
tags: Do we want to store the different Molnix tags in GO? Do we need to assign special meanings to some Tags in Molnix, to for eg. map positions to Alert Types and Categories? **I do think it would be a plus to have them even though it wasnt discuss previously, but of course this depends on how much work is behind this.**

Please let me know if you want to hae a meeting on monday or tuesday before the meeting with Molnix to talk about this!

Thank you!!!

**Comment by anamariaescobar** [comment]
Update: 
The surge team has confirmed that ALL the alerts will be Rapid Response Personnel and that the HeOps will be a role profile (as a tag).
Stand down alerts: The surge team wants to have them together with the open alerts for a period of time and then disaper from the front end, they are having conversations with Molnix on how this will be managed there as they dont have it yet. 
@batpad let me know if you wanna have a quick call to clarify any of this :)

**Comment by batpad** [comment]
Note: Molnix will add "stand-down" as a status, in addition to Open and Archived, likely called "Unfilled".
