### ISSUE TITLE
Deployments map not displaying points

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1660]
## Issue
The world map on the deployments page has no points on it, despite there being people deployed.

## Steps to reproduce
- Go to the deployments page (you need to be logged in): https://go.ifrc.org/deployments
- Scroll down to the world map:
![image](https://user-images.githubusercontent.com/6359748/97420943-d4c1d080-1903-11eb-991d-a98c361b4fd7.png)

## Impact
Map broken for all users viewing this page

cc: @geohacker @batpad @tovari

**Comment by batpad** [comment]
We have pushed a fix for the deployments map to staging, which makes it work "as it worked before", fixing a few issues that were causing things to not render at all.

I'm not sure I've ever seen the deployments map working - I do see that the design and structure of it is a bit different to the rest of the maps. Right now, we left it "as it was", just getting it not throw errors and actually render.

We will likely be unable to do a full overhaul, but can likely make small colour / design changes to make this look more consistent. I'm also a bit unfamiliar with the history and why this map looks and behaves drastically different to the rest of the maps (cc @LukeCaley )

@jhenshall - could you test the deployments map on staging, it should work again. @mariam-yu - we should probably chat about what we can do with the map right now, and maybe with @anamariaescobar on what the ideal plan with the map on the deployments page is.

**Comment by mariam-yu** [comment]
@batpad Sure, let me know. I see the map looks a bit purple-y. Not sure whether we should do an audit, as you mentioned it works as before, but yah let us know!

**Comment by jhenshall** [comment]
Thanks @batpad @mariam-yu - I'm with you that I've never seen this blue style map before!

I can't see anything like it in Mapbox, so wonder if it's possible it's something on the frontend? 🤷 The blue seems to be the exact same colour of the label text and so can't see them over land. Might not be possible for this round, but think it would be great to use the same new basemap style as on the homepage - even if we review the overlay styling at a later date.

Also, might just be the data, but there are no blue dots on the map but it says there are 7 rapid response deployed above it.

**Comment by karitotp** [comment]
The map does not display blue points but the country where there are deployed ERUS is painted in purple color. Also the base map, has the same style of the rest of the maps.

![Screenshot from 2021-01-07 14-34-03](https://user-images.githubusercontent.com/11504548/103936445-6c5a5100-50f5-11eb-9864-dee06b66fe04.png)

**Comment by tovari** [comment]
https://github.com/IFRCGo/go-frontend/pull/2012
