### ISSUE TITLE
Staging and production data parity

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1661]
## Background
The Go staging and production databases have diverged quite a bit for several reasons. While the schematics are the same, most of the foundational datasets are very different, and most often incorrect. Some examples include tables like countries and districts. 

This means that many of PRs that are staged before deploying to production can't be truly tested for data integrity. We've previously run into numerous issues because the foundation data on staging and production are so different. 

## Why now

We're gearing up to address a lot of geodata inconsistencies in phase 4.4. This requires changes at the core — from schema, relations, and data entries themselves. It means we may have to drop certain districts or countries and remap them to new accurate geographies. With numerous field reports and emergencies linked already, it could get very difficult for us to test this migration if staging and production doesn't at least have the geo datasets.

I'm very confident that if we don't do this, our work to resolve #1643 will be painfully slow and increasingly complex to get to production.

## Next steps

Obviously, we can't just copy over data from production to staging, or just arbitrarily drop existing data on staging. We have to take into account private and sensitive data as well as existing testing workflows that rely on staging data. My suggestion would be to work towards getting the geo data on both staging and production same. I know @batpad has more ideas and potentially @GregoryHorvath as well.

cc @jhenshall

**Comment by batpad** [comment]
We have copied over countries and districts data from production onto staging.

These left a few "orphaned" countries that were on staging but not matched in the country CSV. These countries have been dropped from staging so that the data is exactly the same as prod.

Some field reports / emergencies on staging associated with these countries will have been deleted from staging in the process. This is likely fine - overall, the data is intact.

@jhenshall over to you to check that it all looks correct.

**Comment by jhenshall** [comment]
They're matching, amazing! 😄 Quick check and all looks good except there are 7 clusters on prod that aren't on staging. Not necessarily an issue but wanted to flag in case an underlying reason why this might have happened:

- Andean Country Cluster
- Bangkok Country Cluster
- Central Asia Country Cluster
- English Speaking Caribbean Country Cluster
- Guatemala City Country Cluster
- Russia, Belarus and Moldova Country Cluster
- South Caucasus Country Cluster

Is there a plan to also update tables that link to geo data - e.g. field reports, emergencies, 3W, as this is what a lot of the testing involves: seeing how these link? Might also be good to document this as a semi-regular process? cc @tovari

Awesome though, thank you!

**Comment by jhenshall** [comment]
Hey @geohacker @batpad - I was just about to update the clusters in staging for #1684 but we have the above ones missing. I can add these in manually but then the IDs will be different to prod. Probably no big deal but could cause issues when joining with ID? Let me know if you can add them or I will add.

**Comment by jhenshall** [comment]
Definitely done now for the geo stuff. @geohacker @batpad - closing this but do reopen if there's more to consider?
