### ISSUE TITLE
Regional tabs solution (considering the needs for ESSN on country level)

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1665]

**Comment by batpad** [comment]
@mariam-yu is it possible to please add the relevant links for the wireframes, etc. to this ticket so we have this info all in one place? Thanks!

**Comment by mariam-yu** [comment]
@batpad I thought I archived this one, as there was on already created by Munu https://github.com/IFRCGo/go-frontend/issues/1621 I'll delete this one, ok?

**Comment by nanometrenat** [comment]
Closing based on @mariam-yu comment above
