### ISSUE TITLE
PER Refactor: Master ticket

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1667]
Master ticket for the PER refactor work.

Some background / context:

We developed the PER module about a year ago, with an ambitious feature-set - while the implementation has given us a good sense of how PER should work, unfortunately, the module has had structural issues with the way it has been developed that has made proper integration with the rest of the GO platform increasingly painful. This has become a burning issue recently as, since this module is not properly integrated, we were unable to implement translations for it.

The various issues with PER have been covered in several past tickets - eg. https://github.com/IFRCGo/go-frontend/issues/971 .

The goal of the current work is to re-write the code for the PER module, almost from scratch, while keeping the functionality close to as is, fixing bugs along the way, allowing for translations, and being a more robust code-base.

What this means practically:

 - Remove hard-coded questions data from the frontend and model all the Question / Area / Form data on the backend, which has the added benefit that site Admins will be able to add and edit questions.
 - Re-write the components on the frontend to follow a normal React architecture, which will allow us to mark strings as translatable and work with our translation framework.
 - A few data wrangling scripts to import the existing questions to the database, attempt to import existing translations for questions, etc.

@GregoryHorvath please feel free to add anything I may have missed, and / or break-down pieces of work into separate tickets if that's helpful, referencing this as the master ticket.

cc @LukeCaley @tovari

**Comment by GregoryHorvath** [comment]
We had a call with Marco and clarified a couple of things and got some direction:
- Component benchmark / EPI questions should be stored along with the regular questions but have a flag like `is_epi`, `is_benchmark` and without a number
- Show the general `comment` field of the `Form` in the Area forms
- `Overview` should be the base of the whole Assessment process (maybe we want to rename the model to `PER Assessment`?) and the `Form`s and `WorkPlan`s, etc to it
- Every `Overview` can only have 1 of each sub-form
- We shouldn't have Drafts but sub-forms are editable as long as the main `Overview` one is not finalized - add `is_finalized` flag to it
- `started_at`, `submitted_at` and `ended_at` are redundant and unnecessary fields, we only need the timeframe between the `created_at` and `updated_at` of the `Overview` as a measurement to how long did the assessment take
- Add `is_epi` field to the `Overview` which indicates that we also want to show the EPI benchmark questions

Waitin for validation / undecided:
- PER data are sensitive, so it means that we want to remove them from the Country pages (?)
- Have everything at one place - do we want to make another page for it or simply move everything into the PER tab of the Account page?

If I missed anything feel free to jump in.

cc @batpad

**Comment by GregoryHorvath** [comment]
Second session's summary:
- At the top probably we should call the whole thing as "PER Tool"
- Remove everything from the Country pages' Preparedness tab except the very top status data:
![image](https://user-images.githubusercontent.com/30079559/98661746-26784b00-2347-11eb-8105-fa0bd6da9feb.png)
- Add a "Cycle" to the above which would indicate how many Assessments a National Society did (how many `Overview`s were created)
- Results of the Forms, Work Plan, Documents upload, Outcome, etc should be all part of the PER Tool / process
- Phase (assessment / prioritization / etc) should automatically change based on the process'es "status" -- first idea to have checkboxes around the headers of the components, and if someone is finished with a part they'd just tick that in and it would automatically save and change the Phase (needs ability to undo / go backwards too)
- Either have an "assessment end date" field for manual edit or automatize that when the process proceeds from the "Assessment" Phase it would measure and show the time between the Overview creation and this date

**Comment by batpad** [comment]
@karitotp will be great if you can test the basic functionality of the PER forms to create new assessments, save forms, etc.

This should all be in the PER tab of the Account page: https://dsgoproxyapp.azurewebsites.net/account#per-forms

You should be able to:

 - Start a new Assessment
 - See it show up in the list of Assessments
 - Be able to Edit and see all the data correctly.
 - After Saving, no longer being able to edit, but being able to View and Export data correctly.

@karitotp let know if there are any questions when you're online, we can go over in more detail if needed. Thank you!

**Comment by GregoryHorvath** [comment]
@batpad Quick correction: "Final Submit" makes an assessment Finalized which means no Edit or Delete (but will have an Export function in the list). The base "Save" functionality saves every change made on every tabs. For testing purposes right now everyone can see/edit every Assessment but Users can only delete their own ones.

**Comment by karitotp** [comment]
> Start a new Assessment

This woks correctly

> See it show up in the list of Assessments

The new created assessment is listed correctly.

> Be able to Edit and see all the data correctly.

The data load correctly and it can be edited.

> After Saving, no longer being able to edit, but being able to View and Export data correctly.

Works correctly!

cc. @batpad

**Comment by GregoryHorvath** [comment]
@karitotp Sometime later today I'll be pushing the permission updates which basically will introduce the previously used schema which is:

On the backend, Users can have permissions like:
  - `api | country | PER Admin for X`
  - `api | region | PER Admin for Y`
  - `api | country | IFRC Admin`
  - `api | country | PER Core Admin`

Only `superuser`s / `IFRC Admins`s / `PER Core Admin`s can see every Overview and Form. Otherwise the Users can only see those which are created for a country/region they're `PER Admin`s for. This applies to both the backend and frontend pages.

I'll drop a comment here whenever it's live on staging.

cc @batpad

**Comment by GregoryHorvath** [comment]
@karitotp The permission changes are deployed to staging.
cc @batpad

**Comment by GregoryHorvath** [comment]
@karitotp I missed to handle giving full permissions to superusers (and the 2 similar permission categories mentioned above) for some of the functions, so a fix has been just deployed for this to staging.

**Comment by karitotp** [comment]
Hi @GregoryHorvath, I tested again the creation of a new assessment and I saw that is appearing a button for clear the selection. 

![Screenshot from 2020-12-11 09-51-17](https://user-images.githubusercontent.com/11504548/101919962-375fea80-3b99-11eb-861b-8a5abfd4f016.png)

Do not know if that is correct but it also appear when I am just in view mode, where apparently it allows editing.

![Screenshot from 2020-12-11 10-20-18](https://user-images.githubusercontent.com/11504548/101921586-287a3780-3b9b-11eb-8bd6-f37b1499d0bf.png)

> Only superusers / IFRC Adminss / PER Core Admins can see every Overview and Form. Otherwise the Users can only see those which are created for a country/region they're PER Admins for. This applies to both the backend and frontend pages.

How should be test it? 
Currently I can see the list in different countries and I can create, edit and delete an assessment while I do not do a "Final submit", and if I do a final submit I only can view and export it.

**Comment by GregoryHorvath** [comment]
@karitotp thanks for catching that! It shouldn't appear in View mode for sure.

For the permissions, the way I tested it that I created a new user for myself and gave that user the PER Admin permissions for Hungary as the country and Americas as the region and tried to create/edit/view Assessments for other countries/regions than these. And of course tested if I could actually work with ones I had permissions for.

If you don't have access to the backend to give yourself permissions and create a user I can do that for you if needed, just drop me a note here.

**Comment by karitotp** [comment]
> For the permissions, the way I tested it that I created a new user for myself and gave that user the PER Admin permissions for Hungary as the country and Americas as the region and tried to create/edit/view Assessments for other countries/regions than these. And of course tested if I could actually work with ones I had permissions for.

@GregoryHorvath, I created a new user according your comment, and I tested this with different permissions, and it works as expected :+1:
