### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#167]
The tables for all pages, are not displaying correctly when testing on mobile phones.

The rest is working very well.

**Comment by guipizzini** [comment]
As agreed. We will remove from the mobile response visualisation all the tabular data, the pages that require login, the account register option, the login option and the creation of field reports.

Basically users on mobile phones will be able to see the key figures, the maps and the graphs.

**Comment by guipizzini** [comment]
As agreed. We will remove from the mobile response visualisation all the tabular data, the pages that require login, the account register option, the login option and the creation of field reports.

Basically users on mobile phones will be able to see the key figures, the maps and the graphs.

**Comment by guipizzini** [comment]
The rest will be done in phase 2.0

**Comment by dereklieu** [comment]
cc @ascalamogna
