### ISSUE TITLE
[PROD] Erroneous creation of 'Region' country pages

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1673]
## Issue
There are country pages for the 5 regions, i.e. Americas, MENA etc.  These should not exist.

Example: https://go.ifrc.org/countries/282#operations

## Steps to reproduce
When searching "Americas Region" on GO I discovered that there are country pages named after the Regions

![Americas_Region_Country_bug](https://user-images.githubusercontent.com/7791954/99084830-bcbaa400-25c7-11eb-8c01-81beecebef8d.JPG)

## Expected behaviour
These region `country` pages should not exist

## Related feature
Xref: https://github.com/IFRCGo/go-frontend/issues/1643, 

## Context
This is due to the countries table containing an entry for each region and cluster. 

Future geo-fixes aiming at introducing hierarchy within the table (country>cluster>region) which would potentially solve the issue.

## Severity
Not a major problem but good to close this if forthcoming geo-fixes resolve the issue.

**Comment by nanometrenat** [comment]
FYI this is not a new issues - the country pages for regions have existed for some time - it's just that when search wasn't working they couldn't be found easily ;)

**Comment by jhenshall** [comment]
This is also true for [clusters](https://go.ifrc.org/countries/302#operations), which maybe also shouldn't exist.

There's also non-independent states that should not have country pages ([such as Macao](https://go.ifrc.org/countries/279#operations)). And will be lots more once we add missing countries and disputed territories, that will be needed for building the Mapbox tilesets. #1464 

Can we use a field in the country table to determine whether a page is created for that country?

cc. @geohacker @batpad

**Comment by batpad** [comment]
> Can we use a field in the country table to determine whether a page is created for that country?

It would be easy to show the user a message saying "This does not exist" or so - the potentially slightly trickier part is making sure that country does not show up in search - so, ideally, this ticket has two parts:

 - Make sure countries that are not of record_type=1 display an error if you navigate to them.
 - More importantly, make sure these countries don't show up in search, so there's no real way to navigate to them in the first place.

This would involve poking around with the Elastic Search indexing process and making sure those records are ignored while indexing - this shouldn't be too hard, would just require a bit of careful testing of the different cases since it seems like the indexing code could be triggered from multiple places. @geohacker - we should take a look at this a bit to at least be able to frame out exactly what we need to do to keep these countries out of the search index.

**Comment by nanometrenat** [comment]
@jhenshall not the same thing, but may be related - I see that regions now show in the country dropdowns in some places - e.g. when creating a new Field Report - not sure if this was a deliberate decision to align with other lists/options elsewhere (e.g. admin site)?  I know that sometimes _emergencies_ are deliberately created against regions/multiple countries but normally the _field reports_ would relate to just one country not a region.  Cheers

old (a few months ago)
![image](https://user-images.githubusercontent.com/33625192/102959254-d85c8700-4543-11eb-9e89-8a2b4217bc5c.png)

now:
![image](https://user-images.githubusercontent.com/33625192/102959274-e5797600-4543-11eb-9e9b-65b55f3b040b.png)

**Comment by jhenshall** [comment]
Thanks @nanometrenat! This was not a conscious decision as far as I'm aware, so will capture in a new ticket alongside me documenting better. Thank you for flagging!

**Comment by jhenshall** [comment]
For the issue of the unwanted region, cluster and country pages - the plan is to remove these from site search, so that although they are still being created, they will not be accessible from anywhere on the site.

@batpad - do you know if this will also remove them from search engine indexing?

**Comment by GregoryHorvath** [comment]
@jhenshall I deployed the change to staging and ran a reindex, so now:
- Countries created/removed (or name changed) should update their respective Elasticsearch index
- If you remove the `society_name` from a Country its ES index is removed
- If you don't fill the `society_name` when creating a Country it doesn't create an ES index for it

**Comment by jhenshall** [comment]
The changes made by @GregoryHorvath mean that cluster and region records are no longer displayed in site search. They are also not linked to from anywhere, so cannot be navigated to except [via Google](https://www.google.com/search?q=ifrc+go+cluster&rlz=1C1CHBF_en-GBGB916GB916&oq=ifrc+go+cluster&aqs=chrome.0.69i59j69i60l3j69i64.3634j0j1&sourceid=chrome&ie=UTF-8).

There is a wider question of whether clusters and regions should even be in countries table but that is in a different ticket: #1639 

I have also captured the [dropdown comment](https://github.com/IFRCGo/go-frontend/issues/1673#issuecomment-749925775) in a new issue: #1845.

But immediate issue of this ticket solved, so closing this one.
