### ISSUE TITLE
Name of ERU types to be changed on deployment page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#168]
@k-som can you share the names of the types of ERUs that need to change, please?

**Comment by k-som** [comment]
@guipizzini @dereklieu IT&Telecom, WASH M15, WASH M40, WASH MSM20, RCRC Emergency Clinic, RCRC Emergency Hospital, Logistics, Relief, Base Camp

**Comment by guipizzini** [comment]
Thanks @k-som could you match them to what we currently have on GO please?

**Comment by k-som** [comment]
@guipizzini @dereklieu 

Basecamp >> Basecamp
Healthcare >> /remove/
**Telecom >> IT&Telecom**
Logistics >> Logistics
**Deploy Hospital >> RCRC Emergency Hospital
Refer Hospital >> RCRC Emergency Clinic**
Relief >> Relief
**Sanitation 10 >> WASH M15
Sanitation 20 >> WASH MSM20
Sanitation 40 >> WASH M40**
