### ISSUE TITLE
[PROD] Update clusters to match organisation structure

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1684]
## Issue
The counties table has entries for clusters which no longer match the APPLE organisational structure. With the next round of geo changes aiming to add hierarchy of Country > Cluster > Region into the countries table, we first need to make sure that GO replicates the organisation structure.

## Changes to be made
**Add missing clusters**
`North America and Mexico`

**Split out**
`Eastern Africa and Indian Ocean Islands Country Cluster`
To become:
`East Africa country cluster`
`Indian Ocean Islands country cluster`

**Merge**
`Guatemala City Country Cluster` & `Tegucigalpa Country Cluster`
To become:
`Central America country cluster`

**Name changes**
Just changing the names from what is currently on GO to what is now on APPLE.
Current GO name | New APPLE name
-- | --
Andean Country Cluster | South America country cluster
English Speaking Caribbean Country Cluster | Caribbean country cluster
Latin Caribbean Country Cluster | Cuba, Haiti and Dominican Republic country cluster
Russia, Belarus and Moldova Country Cluster | Moscow country cluster
Southern Asia Country Cluster | New Delhi country cluster
Western Africa Country Cluster | West Coast country cluster

## How to do it

@geohacker - think I can just do this in backend because not much. For the splitting out and merging, probably best to deprecate the existing and add new entries but what do you think? Could also repurpose what's existing to prevent having deprecated clusters but might be some relationships I'm unaware of.

cc @batpad

**Comment by geohacker** [comment]
@jhenshall thank you for this explanation! Yes this might would easier done on the django admin. I think deprecating and adding new ones make sense, but do you know if we want to remap existing events/emergencies/reports tied to these old ones?

**Comment by jhenshall** [comment]
Very good question @geohacker! Will look into what's already mapped and what we'd need to do with them.

**Comment by jhenshall** [comment]
@geohacker - I've checked and there are no field reports, events, appeals or 3W that are linked to cluster records. They are all done at a country level: so either mapped to multiple countries or to a single representative country for a region - e.g. Panama for Central America. So, thinking no mapping required unless I might have missed something?

**Comment by jhenshall** [comment]
Done in admin at same time as 4.4 release
