### ISSUE TITLE
Make sure the Deployment map pulls the correct data on ERUs from the back end

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#169]
As discussed on the phone, @dereklieu thanks a lot.

**Comment by guipizzini** [comment]
When stating deployments on the ERU back end, nothing is showing up on the map...

As well, we logged off, logged in again and if we click on the Deployments we get the page. However, if we reload the page it shows up blank.

Image below:

<img width="1272" alt="screen shot 2018-02-08 at 12 04 22" src="https://user-images.githubusercontent.com/23258092/35969774-3e381ca4-0cc8-11e8-9f19-c90bc3738a14.png">

When going to the region of concern, even if we have deployments in that region, the overview will not tell us the correct information.

Image below:

<img width="1237" alt="screen shot 2018-02-08 at 12 04 12" src="https://user-images.githubusercontent.com/23258092/35969813-64a1db00-0cc8-11e8-90a3-5c3c40693ea2.png">

**Comment by guipizzini** [comment]
Hi Derek, the last point mentioned is still the case.

When we go to the Regions overview, we do not get the data showing up for the active deployments for that region of concern - despite having data in the system and on the deployments page.

**Comment by guipizzini** [comment]
Ok perfect, thanks for that.

Its showing up now correctly on the bar charts but its still missing from the tabular data and the ERU readiness cards. Images below...

<img width="1216" alt="screen shot 2018-02-09 at 10 18 12" src="https://user-images.githubusercontent.com/23258092/36020354-af3313ae-0d82-11e8-8b3f-477c966f9c41.png">
<img width="1203" alt="screen shot 2018-02-09 at 10 18 01" src="https://user-images.githubusercontent.com/23258092/36020355-af5ab5b2-0d82-11e8-8826-8c28acd9ebae.png">

**Comment by dereklieu** [comment]
It seems like it's working now. Maybe a caching issue? 

Europe region page.

![screen shot 2018-02-11 at 10 49 14 pm](https://user-images.githubusercontent.com/1590802/36083158-dac32066-0f7d-11e8-9201-1bc1bf453c0f.png)

**Comment by guipizzini** [comment]
Hi @dereklieu refreshed cache, used other browser and still not showing the data.

**Comment by danbjoseph** [comment]
The map at `/deployments` isn't rendering correctly. Refresh browser a number of times and the following behavior seems to occur at random.
Sometimes the bubbles show and everything seems to work:
<img width="250" alt="screen shot 2018-02-16 at 2 03 04 pm" src="https://user-images.githubusercontent.com/4806884/36308890-bfbeb840-1322-11e8-9120-21bd46f1b0cb.png">
But sometimes they aren't visible:
<img width="250" alt="screen shot 2018-02-16 at 2 03 17 pm" src="https://user-images.githubusercontent.com/4806884/36308899-d02a4ea6-1322-11e8-8a65-d4c8e4eaa981.png">
Although even if they aren't visible you can still click on them:
<img width="250" alt="screen shot 2018-02-16 at 2 03 19 pm" src="https://user-images.githubusercontent.com/4806884/36308924-e62626d0-1322-11e8-98c9-ed3821f7537e.png">
Errors are showing in the console:
<img width="890" alt="screen shot 2018-02-16 at 2 05 04 pm" src="https://user-images.githubusercontent.com/4806884/36308977-0dd9d32a-1323-11e8-9026-a85b259598b3.png">
<img width="906" alt="screen shot 2018-02-16 at 2 05 16 pm" src="https://user-images.githubusercontent.com/4806884/36308979-0f26852a-1323-11e8-95f8-af95f0eeb923.png">
<img width="909" alt="screen shot 2018-02-16 at 2 05 28 pm" src="https://user-images.githubusercontent.com/4806884/36308983-10c97374-1323-11e8-9615-8bde63c9f62c.png">

**Comment by dereklieu** [comment]
@danbjoseph 👍 that should be fixed in in #194. Mapbox GL emits errors to console for lots of things, but the important thing is it should not interrupt map functionality - if you see that happen again please open another ticket.

@guipizzini just to clarify, do you mean that you should be able to see ERU deployments on the region page maps? They are showing up on the charts.

<img width="1116" alt="screen shot 2018-02-18 at 6 11 16 pm" src="https://user-images.githubusercontent.com/1590802/36358141-305c4602-14d7-11e8-932d-5b67a13c9869.png">

However, having ERU deployments on the map was not something we spec'd out.

**Comment by guipizzini** [comment]
@dereklieu yes correct, all is good and working - my mistake in explaining myself. Closing this one.
