### ISSUE TITLE
[PROD] Link overseas territories to 'sovereign state'

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1690]
## Issue
Overseas territories are currently included in the countries dataset with `independent`=`FALSE` but are not linked to the sovereign state record. This would be useful for when emergencies happen in overseas territories but need to be linked to the country with the National Society - e.g. Anguilla> United Kingdom or other examples outlined in #619.

Need to confirm whether `sovereign_state` is appropriate name for the field.

## Other considerations
It is worth noting that there needs to be a wider review of how overseas territories are handled, as it is not uniform. e.g. Anguilla is a separate record in the countries table, whereas Aruba is stored as a 'district' of the Netherlands.

This ticket  is to address the underlying data schema but will require subsequent work to better define how overseas territories are handled.

**Comment by geohacker** [comment]
@jhenshall `sovereign_state` sounds good to me. Do you know if this requires changes anywhere in the front-end especially for the logic on linking emergencies? If so, what exactly would that be? cc @batpad @GregoryHorvath

**Comment by batpad** [comment]
@geohacker @jhenshall - feel free to shoot down this idea but to put it out there: how about a single `parent_id` field.

So parent_id would be a ForeignKey to itself (i.e. the country table - i.e. any entity in the Country table can mark another entity in the Country table as `parent`).

When applied to a country (record_type=1) with `independent=False`, the `parent` is the "Sovereign State" the non-independent country entity is a part of.

When applied to a country (record_type=1) with 'independent=True`, the `parent` is the Country Cluster this country is a part of.

If there's a chance of weird edge cases, let's stick to having separate columns for these - just wanted to throw this out there as a possibility in case it helps to keep things tighter, having a single column to express this hierarchical relationship.

**Comment by jhenshall** [comment]
Just noting here... discussed @batpad suggestion above but agreed to keep as two separate fields `sovereign state` and `country cluster` - this makes it clearer what the data is showing and doesn't need additional explanation, especially for users of API.
