### ISSUE TITLE
[Staging] Filter icons on table look broken

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1691]
## Issue

Icons in the table headings seem to be broken. This possibly happened when we updated our icon font.

Ref #1621 

This is a bit silly, but we may need to change the way we are processing our icon font right now to cleaner integrate new icons.

@imohkay assigning this to you, and to outline whatever solution you come up with.

**Comment by imohkay** [comment]
@batpad Have made a PR for this, which I see you have already merged into develop. I have added basic documentation to the README for the same.

**Comment by batpad** [comment]
This is now on Develop. Thanks @imohkay

**Comment by karitotp** [comment]
@batpad, icons looks good now. But I saw that in the table for Surge, the filter for “CATEGORY” and “TYPE” is not rendering correctly.

![Selection_014](https://user-images.githubusercontent.com/11504548/100646290-d704b980-330b-11eb-9325-25a2462052d5.png)

**Comment by karitotp** [comment]
Filter icons on tables look and work good!
