### ISSUE TITLE
Change Colour scale of the ERU Deployment Map

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#170]
Will share colour palette to be used asap.

**Comment by guipizzini** [comment]
For the ERU colour scale could we use this colour code #00A0DC

For the deployed Surge (FACT/HEOps/RDRT/RITs) could we make the bubbles with this colour code #FF9966

**Comment by danbjoseph** [comment]
@guipizzini the color [#00A0DC](http://www.color-hex.com/color/00a0dc) might be a little close to the blues used in the basemap. did you want a scale that extended out both lighter and darker from that color code? or range from white to that color code?

also, with both the existing and proposed color scale, it might be worth noting:
> With sequential, colors simply go from light to dark across the color ramp; it is cartographic convention that “darker = more” so that the larger numbers attach to the darker colors, although if your map is going to be displayed against a dark background, that rule is inverted (it is the “high contrast” colors, against the background, that are the most easily seen and stand-out).

via http://www.axismaps.com/guide/multivariate/bivariate-choropleth/

**Comment by danbjoseph** [comment]
for example, Bangladesh has 6005 and Norway only has 2 (but the bright color draws the eye much more) 
<img width="957" alt="screen shot 2018-02-19 at 8 54 44 am" src="https://user-images.githubusercontent.com/4806884/36367361-a088eb58-1552-11e8-9a72-bbfdca29032b.png">
<img width="150" alt="screen shot 2018-02-19 at 8 57 46 am" src="https://user-images.githubusercontent.com/4806884/36367464-089031a2-1553-11e8-98af-0880899798ae.png">
<img width="150" alt="screen shot 2018-02-19 at 8 58 05 am" src="https://user-images.githubusercontent.com/4806884/36367465-096b075a-1553-11e8-9092-decbdf2c9e14.png">

**Comment by dereklieu** [comment]
I think we should table this in favor of broader discussions on map styles and how they align to organizational standards.
