### ISSUE TITLE
Update styles for new footer

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1706]
Update the footer to look like this:
https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ef20a7ec497bf4479990370

**Comment by batpad** [comment]
This is now on staging.

@karitotp could you test that links in the new footer, etc. all work fine?

cc @mariam-yu for design feedback.

**Comment by mariam-yu** [comment]
@batpad Great! This is coming together so nicely. A few comments:

- Could you check the font weights across? Seems a bit bolder to me, but to double check.
- The copyright is on the left.
- All the external links should open in a new window; so, I guess only "Other Resources" can open in the same window.
- We could make the overall box height a bit bigger (264px in Zeplin).

Thanks!

**Comment by batpad** [comment]
cc @imohkay ^

**Comment by karitotp** [comment]
@batpad, all links works good. Just some style issues in Arabic language :point_down: 
 
![Selection_002](https://user-images.githubusercontent.com/11504548/101548368-baa2f580-3979-11eb-8c31-fc2dd4705ea7.png)

**Comment by imohkay** [comment]
@karitotp Hey, the UI for the copyright with 2020 looks okay to me on the footer. Am I missing something?

**Comment by imohkay** [comment]
@mariam-yu Could you see if the footer looks okay now? I've also fixed the thicker font weight for the headings and reduced it to 600 (from 700)

**Comment by mariam-yu** [comment]
Thanks @imohkay . Regarding for weights, I think what would be best, is we find some standards of how we convert them in code and then we can just apply throughout. For example, if in Zeplin it says Poppins-Medium, then we can assign it the weight of 500 or whatever fits the closest and then every time in Zeplin it's Medium, we make it 500 consistently. Happy to help you with this matching exercise (unless that's how you do it already) (cc @maisa-yu ).

The footer looks good. The only comment I have is the alignment of columns in a way that the right and left margins are more equal in size, as well as the distance between the columns. Also, to double check the height of the footer and distance between elements vertically.

Thanks! Looking good!

**Comment by maisa-yu** [comment]
@imohkay  thanks! Looking great!
I'd emphasise Mariam's comments on the alignment, "Contact us" could go more to the right, leaving more space to the other columns. 

I have just another comment that is not related to the Footer, but it's a detail right next to it:
Surge Notifications table is white over a grey background, which means the white part doesn't go all the way on the sides. (the grey background goes from DREF charts to Surge table).

Thanks!

**Comment by karitotp** [comment]
> @karitotp Hey, the UI for the copyright with 2020 looks okay to me on the footer. Am I missing something?

@imohkay, I thought there is a issue because I believed that the copyright had to be only in one line as shown in the other languages. 
But it is ok :+1:
