### ISSUE TITLE
[PROD] Handling disputed territories

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1709]
## Issue
With the work to have GO as the canonical source of geo data and export to Mapbox tileset #1474, there are some disputed territories that are separate records in the ICRC shapefile but should not be displayed as separate countries, both on GO and on the map. There may be more instances but the two current considerations are:

- Kosovo - should be displayed as part of Serbia as it is covered by the The Red Cross of Serbia
- Western Sahara - should be displayed as part of Morocco as it is covered by the Moroccan Red Crescent

## Solution
Not sure how best to handle this so ticketing for discussion. We could have a separate field for `ICRC country` or perhaps utilise the `sovereign_state` field being added for non-independent states #1690. But not sure how this can be handled in Mapbox because e.g. when hovering the Serbia, Serbia and Kosovo should be highlighted.

## Related tickets
Although politically very different, the handling could have similarities to overseas territories #1690 
Also related to the missing countries #1464 and districts #1473 compared to ICRC shapefile.

cc @geohacker @batpad

**Comment by geohacker** [comment]
With https://github.com/IFRCGo/go-api/pull/969 we now have a way to add sovereign_state and disputed status. One idea for showing disputed territories appropriately is to have a GeoJSON that we store as part of the go-api code base on Github and then pull that everytime tilesets are updated. That way we make it part of the process but don't try to magically determine the parts of the boundary that needs to be styled differently.

**Comment by jhenshall** [comment]
Proposing that we replace the geometries of Serbia and Morocco to include Kosovo and Western Sahara respectively. We would then have overlapping polygons for the disputed areas but any hover state would be displayed as required by the National Society. cc @geohacker

**Comment by geohacker** [comment]
@GregoryHorvath to replace the geometries, all we have to do is run:

```
python manage.py import-admin0-data --update-geom 20201209_GO_Kosovo_WesternSahara_merge/20201209_GO_Kosovo_WesternSahara_merge.shp
```

The shapefile is in the Google Drive.
