### ISSUE TITLE
Surge calendar link on the Resource page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1723]
Please add a new item to the IFRC Surge Services list on the Resource page with the following text:
Global Surge events and trainings

If the string is too long to fit in one line, it can be 'Surge events and trainings'

the link:
https://docs.google.com/spreadsheets/d/1F-78qDc8vdh5hli5FLFeyTvlFQgw19OqZXMR50TQ1C0/edit?usp=sharing

![image](https://user-images.githubusercontent.com/68283148/101510095-c55d8a80-3979-11eb-8345-8b03cdf90b78.png)

**Comment by batpad** [comment]
@imohkay - could you look?

**Comment by batpad** [comment]
This is now on staging - thanks @imohkay

**Comment by tovari** [comment]
This looks good for the requester as well! Thanks!

**Comment by karitotp** [comment]
This is on production too.

![Screenshot from 2021-01-06 14-10-39](https://user-images.githubusercontent.com/11504548/103810292-030d0c00-5029-11eb-9ca8-31716e1f6e4f.png)
