### ISSUE TITLE
[Staging] Uncheck radio button styling

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#1742]
Related PR: https://github.com/IFRCGo/go-frontend/pull/1735/files

@imohkay I've introduced an "uncheck radio buttons - button" to the PER Forms: Account > PER > any Assessment > Area 1-5 > questions' radio buttons.

I was not able to fix the styling of this button for my life so please could you please look into this? There's no clear direction here, basically I just wanted to align it with the radio buttons, but if you have an idea how to make it more consistent so no matter how many radio buttons are there it would be at the same place, then please feel free to play around with that too.

PS: the above PR merged to `develop` too, so you should be able to check on staging

cc @batpad

**Comment by imohkay** [comment]
@GregoryHorvath This should now be fixed on staging...

**Comment by GregoryHorvath** [comment]
@imohkay They look so much nicer now, big thanks!

**Comment by imohkay** [comment]
Glad it worked :)
