### ISSUE TITLE
Bar charts on deployment page disappear on full screen

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#175]
@ascalamogna not sure if this is intentional or not.

**Comment by guipizzini** [comment]
As well, on the home page when we go full screen we have the following view which seems not correct:

<img width="1244" alt="screen shot 2018-02-08 at 12 09 32" src="https://user-images.githubusercontent.com/23258092/35970026-0ea10770-0cc9-11e8-9d3f-3bb0d8199f14.png">
