### ISSUE TITLE
[Staging] Deployments map not showing personnel deployed

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1761]
## Issue
The map on the deployments page is only showing ERU deployed, not personnel deployed, also the style doesn't matches GO, it would be nice to show the map as the one in the main page, with circles of different color showing ERU and Rapid Response Personnel instead of highlighting the country.

## URL
https://dsgoproxyapp.azurewebsites.net/deployments

## Steps to reproduce
Just go to the deployments tab.

![image](https://user-images.githubusercontent.com/69478743/102216063-e4f53580-3eda-11eb-8c81-0c9f54a2de04.png)

## Expected behavior
The map should follow the styling of GO and show where the Rapid Response Personnel and ERU are deployed to.

## Related feature
#1760 

@batpad

**Comment by batpad** [comment]
Thanks for the ticket @anamariaescobar !

@geohacker - this is what we would need to do:

### API

We currently have an end-point we use to populate the Deployments Overview By Emergencies table on the deployments page here: https://github.com/IFRCGo/go-api/blob/develop/api/serializers.py#L512 . The end-point serializer is here: https://github.com/IFRCGo/go-api/blob/develop/api/serializers.py#L512 . We will need to add the countries for events there and their ISO codes / centroids to show on the map.

### Frontend

Convert the results from the `/personnel-by-event` end-point into GeoJSON and render on the map as points. In the case where there are multiple emergencies in a country, we will need to aggregate the total deployments for the country on the frontend.

Question for @anamariaescobar : Should the scaling / size of the points represent the number of deployments to that country? Also confirming that the points represent the countries DEPLOYED TO - i.e. the countries where the emergencies deployed to are taking place.

@geohacker I can help with the API changes, will be good to get a sense from you for how much work this will be - I know you have mentioned the deployments map is a bit awkward in general and I also wonder if it might make sense to just re-do the map from the ground-up, and only show the Rapid Response Deployment points? @anamariaescobar would it be okay to remove the ERU units deployed from the map, or do we want to show both? Perhaps it will be useful to get on a quick call to clearly define what the map on the deployments page should display.
