### ISSUE TITLE
[PROD] Arabic map labels are wrong

### ISSUE THREAD

**Issue by kamicut** [IFRCGo/go-frontend#1765]
## Issue
Map labels for Arabic pages are incorrect. We need to include HarfBuzz through the Mapbox RTL plugin. (Here's an explanation on text shaping for Arabic if anyone's interested https://increment.com/programming-languages/unplain-text-primer-on-non-latin/)

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/719357/102230684-d9fbce80-3ef5-11eb-959f-140bdf208e12.png">

**Comment by batpad** [comment]
Re-opening as auto-closed.

**Comment by tovari** [comment]
Ramez confirmed that labels are okay. Thanks!
