### ISSUE TITLE
[PROD] Issue with arabic translation strings

### ISSUE THREAD

**Issue by kamicut** [IFRCGo/go-frontend#1772]
## Issue
Some translation strings for the Arabic pages have the "variable" inside the template string translated as well. This means that we do not have the correct variable name when we try to replace the variable with content. For example, in #1616, the variable for `emergencyFieldReportsWithCountTitle` is `count`, but in the associated string it's translated to `{عدد}`. (the word for "count" in arabic): (`"emergencyFieldReportsWithCountTitle","التقارير الميدانية ({عدد})"`).

You can see in the following list all the strings that contain variables (they are inside curly brackets `{...}`: some are translated and some are not. 

```
"accountUserGreeting","مرحبًا {المستخدم}"
"countriesAllOperationExportLink","عرض كافة العمليات لـ {الاسم}"
"countryPageTitle","IFRC Go - {اسم الدولة}"
"countryTableProjectCount","{projectCount} من المشاريع"
"deploymentsMapDeployed","نشر {activeFilter}"
"emergenciesMapPopoverPeopleAffected","{numAffected} الأشخاص المتأثرون"
"emergenciesMapPopoverTotalEmergencies","{totalEmergencies} حالات الطوارئ"
"emergenciesMapPopoverWithIFRC","{withResponse} مع استجابة الاتحاد الدولي لجمعيات الصليب الأحمر والهلال الأحمر"
"emergenciesMapPopoverWithoutIFRC","{withoutResponse} بدون استجابة IFRC"
"emergencyFieldReportsWithCountTitle","التقارير الميدانية ({عدد})"
"emergencyPageTitle","IFRC Go - {الاسم}"
"emergencySourceFigure","المصدر: {مصدر}"
"fieldReportActionTakenBy","الإجراءات التي اتخذها {orgDisplayName}"
"fieldReportIncomplete","الصفحة {الخطوة} من 4 غير مكتملة."
"fieldReportSummaryTitle","IFRC Go - {reportName}"
"globalHeaderBannerTitle","تتوفر معلومات عن حالة COVID-19 العالمية وإرشادات فنية {link}."
"headerBetaNote","هذه النسخة التجريبية من IFRC GO.فيما يتعلق بالمشاكل والتعليقات حول المنصّة، يرجى الاتصال بـ {email}"
"homePageLinkText","{countryName} الصفحة الرئيسية للهلال الأحمر"
"ifrcLinkText","{countryName} على IFRC.org"
"langSelectLabel","اللغة:{currentLanguage}"
"loginErrorMessage","خطأ:{message}"
"mapPopoverTitle","عمليات النشر في {name}"
"nationalSocietiesCountries","({value} دولة من إجمالي {total})"
"readinessDeployedErus","{numDeployed} نشر وحدات الاستجابة للطوارئ"
"readinessReadyErus","{numReady} وحدات الاستجابة للطوارئ جاهزة"
"regionAppealsTableViewAllText","عرض كافة عمليات الاتحاد الدولي لجمعيات الصليب الأحمر والهلال الأحمر لمنطقة {regionName}"
"regionEmergenciesTableViewAllText","عرض جميع الطوارئ لمنطقة {regionName}"
"regionTitleSelected","IFRC Go - {regionName}"
"reliefWebLinkText","{countryName} على reliefweb.int"
"reportsTableTitle","جميع التقارير الميدانية {title}"
"supportingNSListProjects","{noOfProjects} من المشاريع"
"tableAppealsTitle","كل {title} {اسم}"
"tableEmergenciesTitle","كل {عناوين} حالات الطوارئ"
"tableTitle","IFRC Go - {type}"
"accountReportListLastUpdated","آخر تحديث: {on}"
"dateFilterHeaderTooltip","تصفية حسب {title}"
"displayTableFilterHeaderLabelTooltipText","تصفية حسب {title}"
"displayTableFilterHeaderOptionTooltipText","تصفية حسب {title} - {label}"
"displayTableSortHeaderTooltip","الترتيب حسب {title}"
"emergencySourceMessage","المصدر: {link}"
"resendValidationErrorMessage","خطأ: {message}"
"fieldReportLastUpdatedBy","آخر تحديث بواسطة {user} في {date}"
"fieldReportLastUpdatedOn","آخر تحديث في {date}"
"globalHeaderBannerSurveyTitle","Take 5 mins to tell us what you think - {link}"
"regionalTabBox1","National Societies in {regionName}"
"newPasswordErrorMessage","خطأ: {message}"
"recoverAccountErrorMessage","خطأ: {message}"
"registerErrorMessage","خطأ: {message}"
"userMenuPopupHeading","مرحبًا {firstName} {lastName}"
```

## Steps to resolve
The variables should not be translated in the language strings.

**Comment by tovari** [comment]
hey @ypyelab, would you mind to check in the attached translations file, if there are strings in arabic, where the string inside {} is not the same as in the 'dev' string between {}?
If there are such, could you also replace that part in the arabic string (between {}) with the related string from the 'dev' string between {}? 
[go-all-strings-2021-8-4-10-47-33.xlsx](https://github.com/IFRCGo/go-frontend/files/6929941/go-all-strings-2021-8-4-10-47-33.xlsx)

**Comment by ypyelab** [comment]
hey @tovari! 
I added an 'ara' column with the requested change. I left 'ar', so you could get the comparison.
I think observations 450, 1133 might not have the best translation in arabic (Page {step} of 4 incomplete, All {title} Emergencies). Probably we could ask the MENA  IM team to 'write' us which would be the best translation.
[arabic_dynamic_names.xlsx](https://github.com/IFRCGo/go-frontend/files/6932323/arabic_dynamic_names.xlsx)

**Comment by tovari** [comment]
Thanks @ypyelab! Imported to Staging and Prod. Nice improvements on the localized UIs!
