### ISSUE TITLE
[PROD] Number of deployments on the Surge tab not adding up

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1778]
## Issue
The number of Rapid Response personnel deployed on the Surge (previous Deployments) tab is way to high.

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/69478743/102377691-3ed22a00-3fc5-11eb-846a-ed3d5cab57b9.png)

## Expected behaviour
For example, for Hurricanes Eta and Iota, the actual number of deployed Rapid Response personnel is 37 (checked form the csv extracted from all deployed personnel) and the front end is showing 925.

## Related feature
#1659 

## Impact
All users consulting the Surge tab

## Severity
Functional impact

## Is there a workaround?
No

@batpad

**Comment by batpad** [comment]
This has been hotfixed in production.

@anamariaescobar to confirm tomorrow that all edge cases work as expected. Thanks again for the catch here.
