### ISSUE TITLE
Wrong disaster taxonomy is showing up after the last db scrapping

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#178]
Hi Derek,

We have noticed that after last night's edits the wrong disaster names are showing up which were not there anymore.

@k-som can give you the details of the correct taxonomy to be used.

Image below:

<img width="1252" alt="screen shot 2018-02-08 at 12 06 47" src="https://user-images.githubusercontent.com/23258092/35969978-e428870c-0cc8-11e8-9af0-e34c737d810d.png">

**Comment by k-som** [comment]
Local Storm >> Other

**Comment by guipizzini** [comment]
and when we go full screen now, things are fixed for the disaster types but they are still different on the home page when not in full screen.

As well, when going full screen the infobox when hovering over the graphs is cutting off.

Finally, the appeal data for 2018 is still showing up - this time with a different value. But in 2018 we have 0 emergency appeals.

Image below for reference:

<img width="1277" alt="screen shot 2018-02-08 at 22 44 21" src="https://user-images.githubusercontent.com/23258092/36000202-7978af22-0d22-11e8-951f-d950070bbea1.png">

**Comment by dereklieu** [comment]
Full screen isn't going to look exactly the same, unfortunately. When we artificially constrain the screen size with dynamic data we're going to have to make concessions based on screen height and the amount of data we're showing. We also don't have a great way to fix the hover, short of adding padding to the bottom of the view (which would further cut into the data we show).

The 2018 item is a separate issue #158.

**Comment by guipizzini** [comment]
noted. No chance to put the infobox in a "higher" position? If not possible, Let's then fix for now the 2018 data showing up wrongly. Thanks
