### ISSUE TITLE
[PROD] Getting a blank page after go to Preparedness tab in a country page

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1780]
## Issue
In a country page, after go to the PREPAREDNESS tab, the next visited tab is giving a blank page.

## Steps to reproduce
- Logging on the site
- Go to a country page
- Go to the Preparedness tab
- Go to another tab like Additional data and it will not load and it will display a blank page

![ifrc](https://user-images.githubusercontent.com/11504548/102382248-3b747980-3f98-11eb-86bb-5e3ce9c6e760.gif)

**Comment by batpad** [comment]
This has been hotfixed in production. @karitotp can you confirm that it works now? Thanks!

**Comment by karitotp** [comment]
This work correctly, Sanjay.

**Comment by tovari** [comment]
This has been resolved
