### ISSUE TITLE
[PROD] Missing Keys on the Translation dashboard

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1782]
## Expected behaviour
*Please add the following items to the translation dashboard:*

- [x]  'All Counries' on the region pages on the country panel
- [x] 'National Societies' on the Surge site 
![image](https://user-images.githubusercontent.com/68283148/102385094-b6a45280-3fcd-11eb-9573-39b7659ee81f.png)

**Comment by vdeak** [comment]
The key for "All countries" was already exists: regionAllCountries
For "Nationel Societies" I created a new key: nationalSocieties
