### ISSUE TITLE
Prepare additional layers to be added to tileset

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1785]
With the Mapbox Tile Service work almost done #1474, we should now be able to add additional data layers so we can update them regularly. These are:

1. Country and district centroid layer with names in 4 languages for labels
2. Disputed boundaries data stored on github

cc @jhenshall @batpad

**Comment by jhenshall** [comment]
The boundary line file to be used is in the Google Drive folder: ICRC_Admin0_WD_Borders.zip

**Comment by jhenshall** [comment]
Decided that we will not store disputed boundaries on Github but instead upload shapefile directly to Mapbox. This is rarely updated so no need to automate.

**Comment by jhenshall** [comment]
Boundary data has been added to Mapbox and centroids are covered by #1474 so closing this ticket.
