### ISSUE TITLE
[PROD] Admin - Deployments & 3W - Personnel ÍDeployments search error

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1786]
## Issue
*The search field doesn't work, it gives a Server Error 500 page.*

## Steps to reproduce
*Try to search for any text.*
https://prddsgocdnapi.azureedge.net/en/deployments/personneldeployment/
https://dsgocdnapi.azureedge.net/en/deployments/personneldeployment/

## Impact
Production and Staging

## Severity
*Moderate.*

## Is there a workaround?
*No*

**Comment by tovari** [comment]
cc @anamariaescobar

**Comment by batpad** [comment]
Thanks for the report @tovari -

@GregoryHorvath - PR with fix is here: https://github.com/IFRCGo/go-api/pull/983 - this seems like a pre-existing bug, but good to fix. I don't see much risk in pushing this as a hotfix to production.

**Comment by GregoryHorvath** [comment]
@batpad thanks for the fix, it's deployed to staging @tovari

**Comment by tovari** [comment]
Thanks @batpad, @GregoryHorvath , works fine.
