### ISSUE TITLE
[PROD] Emergency map export - filename undefined

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1787]
## Issue
When you export a map from an emergency details page, the file name contains `undefined`.

Should this instead be the emergency name?

## Steps to reproduce
- Visit emergency e.g. https://go.ifrc.org/emergencies/4959#details
- Navigate to map and click 'Export' button
- Filename contains undefined e.g. `2020-12-22-undefined-Belize`

cc @batpad

**Comment by szabozoltan69** [comment]
Fixed via https://github.com/IFRCGo/go-frontend/pull/2181
