### ISSUE TITLE
[PROD] Country page shows previous country page data after navigating through the Search field

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1788]
## Issue
*Country page shows the previous country page content, while navigating from country to country using the Search field.*

## Steps to reproduce
*1. Search for Turkey country
2. Go to ESSN tab
3. Search for Brazil
4. Check the Additional tab - it shows the ESSN tab content
5. Refresh the browser - It updates the page and shows the correct content. *

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/68283148/103752454-0a70ed00-500a-11eb-81ba-77a6876de0a3.png)

![image](https://user-images.githubusercontent.com/68283148/103752573-283e5200-500a-11eb-9064-ee9cca681fa1.png)

## Expected behaviour
*Content should be updated.*

## Severity
*Severe. Data can be misleading..*

## Is there a workaround?
*Content gets updated after browser refresh..*

**Comment by GregoryHorvath** [comment]
@tovari I think this is closeable?
