### ISSUE TITLE
[PROD] Request assistance info is not pulled from the FR to the emergency

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1789]
## Issue
*The Government Requests International Assistance and NS Requests International Assistance info is always NO on the emergency page, regardless what is set in the related field report*

## Steps to reproduce
*Create a FR. Set Yes at these 2 questions. The related emergency page will still show NO.*

Example:
https://go.ifrc.org/emergencies/5027#details
FR:
https://go.ifrc.org/reports/13808

## Expected behaviour
*The attribute value should be taken from the first field report and should be kept updated.*

## Impact
*All emergencies where assistance have been requested.*

## Severity
*Severe, the displayed data is misleading. It needs a hotfix.*

**Comment by GregoryHorvath** [comment]
Hotfix has been deployed and confirmed it's working, closing this.

**Comment by nanometrenat** [comment]
NB already logged as https://github.com/IFRCGo/go-frontend/issues/1060 - @tovari if fixed you may wish to close that also
