### ISSUE TITLE
[PROD] Appeal documents don't get downloaded. 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1791]
## Issue
*Appeal documents should be downloadable by mouse click, but it doesn't work.*

## Steps to reproduce
*Go to e.g.: 
https://go.ifrc.org/emergencies/3469#reports
click on the Appeal document name. This should start the document download.*

## Expected behaviour
*Document download should start on mouse click.*

## Impact
*All users affected, who would like to download documentsr*

## Severity
*Severe. The workaround is unknown for the users *

## Is there a workaround?
*Yes. Right-click on the document name and select Open in New tab or in New window. That downloads the document *

**Comment by GregoryHorvath** [comment]
This was a fix on the adore.ifrc.org site to allow `https` too. Updated the URLs in GO production: `http` -> `https`.
