### ISSUE TITLE
Create a Report button - KoBo server URL changes in GO header, for 1 Feb please

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1796]
Back in July 2020 a new button was introduced into the GO header (web and mobile) to direct people off to KoBo for the COVID-19 Federation-wide Indicator and Financial reporting forms.
That ticket was https://github.com/IFRCGo/go-frontend/issues/1363

However now, as requested, we are aiming to migrate to the new KoBo server for the February round of COVID-19 global data collection.  **This means that the KoBo URL links will change - so URLS in the header will need to be changed on GO.**

It is intended that the SG communication to National Societies goes out on **1 Feb**, so this change would need to be released then.  New KoBo forms still being tested so don't have URLs yet - these will be supplied end of this month - just wanted to get a ticket in so you have a headsup that a tiny release would be needed please in order to roll out.

Thanks as ever!  cc @tovari @anamariaescobar @LukeCaley @mmusori (can't find Eero's handle to tag him)
(and hello/Happy New Year to all the GO devs+testers too!)

**Comment by nanometrenat** [comment]
Hi @tovari thanks for your patience - links to swap out in the Create a Report dropdown are below:

- COVID-19 Indicator Tracking:  https://eenew.ifrc.org/single/y300V3lY?returnURL=https://go.ifrc.org/emergencies/3972#actions
- COVID-19 NS Financial Overview:  https://eenew.ifrc.org/single/VmcTHDMh?returnURL=https://go.ifrc.org/emergencies/3972#actions

(hope you like the little GO redirects in there!!)

Please update the links as soon as you're ready (all good to do it this week if that works for you, or could wait till Monday 1st as long as the updates are in before SG msg goes out).  THANKS TEAM!

**Comment by tovari** [comment]
Thanks @nanometrenat for raising this and for sharing the details.
@GregoryHorvath what do you think about a release on Monday morning (01.02)?

**Comment by GregoryHorvath** [comment]
@nanometrenat Thanks for raising this.
@tovari I propose that we could do a small release either tomorrow afternoon or early Thursday - with this and that new endpoint for the FDRS / key-figures header. I'll retest the endpoints and recheck if no conflicts were caused by the new endpoint, and if so then I'm totally sure these changes are as safe to be deployed as we can have them.

**Comment by nanometrenat** [comment]
Thanks a million @tovari and @GregoryHorvath !  Most appreciated

**Comment by nanometrenat** [comment]
@GregoryHorvath I have a follow-up question!  Is there a way of (at server end) forcing a browser to refresh the "create report" button?
I have been advised by a user that they went to go.ifrc.org, clicked on the New Report > Indicator Tracking and it took them to the _old_ link.  I suggested they refresh the page and try again, they did, then when they clicked on the New Report button it correctly directed them to the _new_ link.  So it looks like their browser had cached the old link or something?  Not sure if anything we can do at this end but worth asking.  THANKS!

**Comment by GregoryHorvath** [comment]
@nanometrenat To the best of my knowledge we're caching the "main parts" of the site but a full refresh should (almost) always refresh this cache. As far as I know we don't have a way to bust clients' cache on the go. There's also a `/clear-init-cache` URL route which should definitely wipe most of the cache, but that's also not the most user-friendly option for sure.

@frozenhelium @batpad Do you have an idea what else could we do to ease usage in such cases?
