### ISSUE TITLE
(ReqID) FBA - Add new Appeal type: Forecast Based Action

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1798]
**Is your feature request related to a problem? Please describe.**
*At the moment the APPLE system handles and provides 3 types of Appeals (Emergency Appeal, DREF, International Appeal). However, there is a Forecast Based Action (FBA) type of Appeal, which is handled and provided by the Apple API under the DREF type. We need to have an option on the GO Admin page to manually update the Appeal type to FBA. Also the Operations maps and Operations lists  on the frontend should be able to publish this type of appeal.*

**Describe the solution you'd like**
*We need the following updates:
Backend:
- Add a new Appeal type: Forecast based action

Updating data from the APPLE API:
- In case, the Appeal Type gets updated manually to FBA on the Admin page, the Appeal type (only this field) of this appeal should not be updated anymore through the API.

Frontend:
Operational map (main page and regional pages):
- add a new type of appeal. Name in legend:....., Place in Legend: between 'DREF' and 'Movement response',  Color:..... 

List of operations (global and regional):
- add the new type of appeal. Short name in the table:....., Long name in the appeal type filter:.....
Not needed to add FBA to the monthly or yearly line diagrams. Also not needed to add new Key metric about it.
Note, as APPLE keeps this type as DREF, the number of DREF in Apple and GO will deviate by the number of FBAs *

**Additional context**
*Add any other context or screenshots about the feature request here.*
![image](https://user-images.githubusercontent.com/68283148/105191543-7fc6dc80-5b37-11eb-9bef-b029cce5798f.png)

**Should there be any restrictions around viewing or updating information related to this feature**
*existing permission rules don't need to be changed.*

**Comment by tovari** [comment]
Hi @mariam-yu, would you mind to check this?
I'm sure we need a color proposal for the new type. 
Not sure, if we need any design work though. On the map, the legend is affected, while in the list the Type filter.

**Comment by mariam-yu** [comment]
@tovari We will need to explore a new color. Let me tag @maisa-yu to see if we can come up with one quickly. We can always enhance on that later on. I would place it before Multiple Types though.

**Comment by tovari** [comment]
Thanks @mariam-yu, indeed I see the placement between DREF and Movement response (not like on the screenshot).
The requestor suggests a long name (_Early Action Protocol activation_), hopefully it will fit into the legend as well as the list filter.

**Comment by mariam-yu** [comment]
@tovari at least in the table we may have to abbreviate it. Would it be ok to do EAP activation? But also, is this point validated, i.e. would it be clear to the users?

**Comment by tovari** [comment]
@mariam-yu, yes the proposal is to have the short name in the table: _EAP_, Long name in the appeal type filter: _Early Action Protocol (EAP) activation_

**Comment by mariam-yu** [comment]
@tovari How about this? https://www.figma.com/proto/n2D5xvtXBZ9XCejRXeDeUq/IFRC-GO_UI_20201126---LIVE-VERSION?node-id=0%3A4963&viewport=488%2C-436%2C0.10703381150960922&scaling=scale-down-width&hide-ui=1

**Comment by tovari** [comment]
Thanks @mariam-yu, I like the color (is it a new one on the GO color palette?). What is missing from the legend is the existing 'Movement response' type. And however it is not on design, I assume we would not remove the 'Scale points by' selection option. Good, that the entire 'EAP activation' text is visible in the list.

**Comment by mariam-yu** [comment]
@tovari Actually, our recommendation was to remove the scales and have it by default set to number of emergencies, as it seemed the more valuable view was to see in scale where is the "hub" for more emergencies. Also, not sure what is Movement Response? We don't seem to have that in the table, do we?

**Comment by mariam-yu** [comment]
@tovari Regarding the color, we just quickly came up with one that works well with the others, but of course didn't do a thorough color evaluation with the palette. We'd probably have to do that afterwards (especially since the palette changed with the new IFRC stlying), but here is the Hex code for devs: #4C5D9B

**Comment by tovari** [comment]
@mariam-yu, thanks. The Movement response is a type of appeal that is not so frequently applied as DREF, Emergency appeals or even, EAP activation. We should keep the option for this type though.

**Comment by GregoryHorvath** [comment]
Confirmed with @tovari that wherever we differentiate DREF from the other Appeal types, this should act as a DREF.

**Comment by tovari** [comment]
> Confirmed with @tovari that wherever we differentiate DREF from the other Appeal types, this should act as a DREF.

@GregoryHorvath, FBA appeals should not be calculated in the Number of active DREF operations metric in the Key metrics.

**Comment by tovari** [comment]
Translations:
[Early Action Protocol translations.xlsx](https://github.com/IFRCGo/go-frontend/files/5888786/Early.Action.Protocol.translations.xlsx)

**Comment by GregoryHorvath** [comment]
This is now deployed to staging:
- New Appeal type can be set through the backend
- New Appeal type in the frontend Appeal lists' filter and in the map on the homepage
