### ISSUE TITLE
ERP intergration 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1799]
**This is a collection of requirements related to the ERP integration of the FRs.**
*Requirements:
- [ ] to be confirmed:  NS Contact and IFRC Focal point contact should be mandatory
- [ ] Push API availability for FRs *

**Describe the solution you'd like**
More information:
https://ifrcorg.sharepoint.com/:w:/r/sites/ERPProjectTeam/_layouts/15/Doc.aspx?sourcedoc=%7BDFA80BF1-8ECA-4A51-A283-69EFD417A53F%7D&file=TDD%20Re%40dY%20-%206885%20Interface%20Go-D365FO%20Request%20for%20international%20support.docx&action=default&mobileredirect=true

**Comment by tovari** [comment]
@GregoryHorvath, not sure all requirement has been added. I have a note from the meeting about the API should keep the FR IDs

**Comment by GregoryHorvath** [comment]
Our brief tasks here (up until we have the middleware(s)):
- Create a trigger (`@receiver`) for Field Report create/update
- If Request for International Support is `true` for any of the Field Reports (of their Emergency), then create a payload with all the data mentioned in the docs
- Add multiple tries to the request, for the case if some of them fails at first
- Add logging
- Optional, and probably a bit more work: add a cronjob like the `index_and_notify` which would periodically check for new/updated Fields Reports and would send data to the middleware API. This might need an additional check in some way to only send those which didn't succeed.

**Comment by tovari** [comment]
Offline version on 24.03.:

[TDD Re@dY - 6885 Interface Go-D365FO Request for international support (1).pdf](https://github.com/IFRCGo/go-frontend/files/6196111/TDD.Re%40dY.-.6885.Interface.Go-D365FO.Request.for.international.support.1.pdf)

**Comment by szabozoltan69** [comment]
Now we have a working version.
@thenav56 – please give me some hints or examples how to write some unit tests for https://github.com/IFRCGo/go-api/blob/develop/utils/erp.py

**Comment by thenav56** [comment]
@szabozoltan69 For the unit test I would suggest using snapshot testing for the payload send to the ERP_ENDPOINT and mock the response from the ERP_ENDPOINT. So basically we want to make sure the payload structure is valid from our side and we correctly handle the response as well. cc: @batpad

- For the snapshot test example: https://github.com/IFRCGo/go-api/blob/develop/deployments/tests.py
- For mock: https://realpython.com/python-mock-library/

**Comment by szabozoltan69** [comment]
We would need to silently fail and make a log somewhere if the ERP request fails for any reason (if their system is down, for example). Certainly not to give an "Error: U"
