### ISSUE TITLE
[PROD] Typo mistake on url in the footer

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#1809]
## Issue
The text of the url redirect at the footer, for data.ifrc.org has a typo.

![Screenshot 2021-02-04 at 00 05 53](https://user-images.githubusercontent.com/23258092/106815677-df1b0580-667c-11eb-85e2-c1dd77a64c79.png)

**Comment by GregoryHorvath** [comment]
The fix is deployed to staging.
