### ISSUE TITLE
[PROD] Map: Home page and Emergency page map bubbles have an error in displaying data

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#1810]
## Issue
 There is a potential bug on the GO Map, since the bubbles have 2 slightly different colours on the map (hence not reflected on the legend if that is intentional) and that the values of the bubbles seem to all be the same in terms of size.

For example, the Venezuela appeal has 650,000 people affected while Bahamas has 15,000 people affected and the bubbles seem the same size.

<img width="1312" alt="Screenshot 2021-01-06 at 14 08 01" src="https://user-images.githubusercontent.com/23258092/106815898-391bcb00-667d-11eb-93dc-ca9dde5e2dc7.png">

<img width="1295" alt="Screenshot 2021-01-06 at 14 24 14" src="https://user-images.githubusercontent.com/23258092/106815987-610b2e80-667d-11eb-9b82-1152c5dc4c42.png">

**Comment by tovari** [comment]
A better way of symbol scaling (with data outlier handling) will be part of the coming action to unify map designs across the platform.
