### ISSUE TITLE
Map attribution credits

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1815]
## Issue
As we use the Mapbox elevation layer for our map styles, we may need to add text attribution for Mapbox and possibly OpenStreetMap (I'm not certain the elevation layer uses OSM but plenty of other Mapbox layers do).

[Full details here](https://docs.mapbox.com/help/how-mapbox-works/attribution/) and the precise attribution needed for our tilesets is stored in the [TileJSON](https://docs.mapbox.com/help/glossary/tilejson.).

We should also check with ICRC about crediting their admin layers.

cc @geohacker @batpad

**Comment by jhenshall** [comment]
ICRC are finalising the data agreement but we do not have to worry about crediting them at this stage. Could be added once formalised.

**Comment by geohacker** [comment]
@jhenshall can you post on this ticket what the attribution on the map should say? At the moment there's no attribution 
![image](https://user-images.githubusercontent.com/371666/108991805-8d372f80-76be-11eb-99e1-e85d29600574.png)

Turning on the attribution control will automatically use the attributions available in all layers
![image](https://user-images.githubusercontent.com/371666/108991989-c374af00-76be-11eb-9f1c-60a320b2061d.png)

**Comment by jhenshall** [comment]
@geohacker - that's awesome, nice one! ICRC have not requested attribution yet - so using the built in Mapbox attribution control is perfect for now.
