### ISSUE TITLE
Prod and Staging: GO contact details (on Resource page) update option on the Admin page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1820]
## Issue
It looks like the GO contact names and emails on the Resource page are hard coded. The IM contacts may change frequently, it would be good to have an option on the Admin page to update this.
If this is not possible at the moment, at least the Africa contact should be updated now to Elly NANDASABA MULAHA  Elly.MULAHA@ifrc.org

## Expected behavior
*Expect a page on the Admin site where names and emails of regional contacts can be updated.*

**Comment by GregoryHorvath** [comment]
@tovari Deployed to staging.

- There is a `Main contacts` menu in the Django Admin now under the API section
- Added our current contacts with their translations (changed the one mentioned in this ticket) with a management script

**Comment by tovari** [comment]
Thanks @GregoryHorvath for the quick action.
It works well on Staging.
