### ISSUE TITLE
3W:. PNS view, Global view

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1823]
- [x] Partner NS view
- [x] Global 3W view

https://www.figma.com/proto/RZTZdDWf6Xjweh9GA8rMGW/IFRC_GO_Wires_20210502?page-id=0%3A72&node-id=104%3A8886&viewport=1350%2C3308%2C0.12138918787240982&scaling=scale-down-width&hide-ui=1

**Comment by LukeCaley** [comment]
Xref: https://github.com/IFRCGo/go-api/issues/368

**Comment by tovari** [comment]
@mariam-yu, additional notes on the design:
- we would add a new date field (last update) that will show, when the project was last updated. Would be good to see this info on the UI as well.
- we offer a bulk upload functionality on the admin page. This is available for users with specific permissions, but would make sense to provide access to the relevant admin page from the frontend UI somehow.
Thanks!
cc: @luisfanovich

**Comment by mariam-yu** [comment]
@luisfanovich @tovari Sending the link to the prototype here for documentation: https://www.figma.com/proto/RZTZdDWf6Xjweh9GA8rMGW/IFRC_GO_Wires_20210502?page-id=0%3A72&node-id=111%3A0&viewport=1350%2C3308%2C0.12138918787240982&scaling=scale-down-width&hide-ui=1

**Comment by tovari** [comment]
The QC comments will be collected on the 'Issue details' worksheet of this shared spreadsheet:
https://ifrcorg.sharepoint.com/:x:/s/GOIVfordeveloperteam/EVCmzXtZUr1OnesoW8JL1vABRuedOxmo62Q8Q4amhkbUcg?e=27Hyte

**Comment by tovari** [comment]
Please add the following description on the Global view page:

The 'Who does What, Where' or 3w aims to map the global footprint of the Red Cross Red Crescent Movement. It is a global database of projects conducted by National Societies, IFRC and the ICRC, broken down by sector, location, budget and people targeted and reached.  

_Find explanatory videos and guidance on the Resources page.  Please note data is incomplete and maintained by GO users.  If you know of an error or omission, please submit data or contact IM@ifrc.org for assistance._

**Comment by tovari** [comment]
Feedback listed in the UAT file:

- [ ] Country 3W, all projects view: https://dsgoproxyapp.azurewebsites.net/countries/82#3w - The size of the symbols on the map does not represent the number of projects
- [ ] Dates: start and end date format. - Start date and end dates of projects already in the database might be incorrectly handled. Previously MM/DD/YY was used, now we use DD/MM/YYYY, however the old dates are not converted to the new format.
![image](https://user-images.githubusercontent.com/68283148/123662267-959ea300-d835-11eb-826d-fdc7293fa922.png)

- [ ] Snakey diagrams - Filtering on ongoing/all projects doesn't work on the Sankey. It always shows all projects.
- [ ] Program type pie chart colors and chart values - Its a bit difficult to see the differences between the similar redish colors. The project status pie chart colors seem better and could be applied here as well. Also, values are not displayed at the chart sections.
![image](https://user-images.githubusercontent.com/68283148/123662920-31301380-d836-11eb-83d2-a08e113c2bc4.png)

- [ ] Global 3W charts - Looks like the charts shows all projects, while the key numbers above filtered to ongoing projects. Charts should be also filtered to ongoing projects
![image](https://user-images.githubusercontent.com/68283148/123663019-47d66a80-d836-11eb-82b2-7562bc090646.png)

- [ ] Regional and Country 3W Maps symbols - Global maps styling looks great. Would be good to have the same styling on regional and country maps as well.

- [ ] Global 3W map legend - Order of items should be: Emergency Operation, Programme, Multiple types
![image](https://user-images.githubusercontent.com/68283148/123663200-76ecdc00-d836-11eb-9833-48e7a32c0e11.png)

- [ ] Country 3W map filter - Filter of NSs contains duplicates and 'Disputed' list items.
![image](https://user-images.githubusercontent.com/68283148/123663301-8c620600-d836-11eb-9d7b-b5d63b709cfe.png)

- [ ] Translation dashboard - Only 4 new dev strings have been added to the TD. Missing many from the Country, PNS views
- [ ] PNS map - Clicking on a marker on the map leads to a grey screen.
![image](https://user-images.githubusercontent.com/68283148/123663471-b6b3c380-d836-11eb-917a-695a16a11105.png)

**Comment by tovari** [comment]
Test results thanks to @karitotp:
https://paper.dropbox.com/doc/My-Paper-doc-Psg8Cz9yBs0Gxbk1HT2Ps

**Comment by tovari** [comment]
Thanks to @ryales :
- [ ] Regional and Country 3W Maps - Filters should work just as on the 3W Global map. At the moment: Cannot unselect a filter choice; no reset or select none. I don't know what to do other than refresh the page when I want to start over. No ability to select multiple tags, thisis fine for most of the other fields, but it would be nice if the tag field allowed multiple select.
- [ ] 3W form - please remove the RCCE tag
- [ ] 3W form - The form states Disaster Type is not required, but forces you to choose before allowing submission. This does not make sense for "Programme" activities. A long-term WASH or Education programme, for example, has nothing to do with a disaster.

**Comment by tovari** [comment]
Thanks @frozenhelium for the latest updates. We did some testing with the IM team and identified the following things that should be fixed before we can release them:

- [ ] 3W form - Disaster type should not be mandatory in case of "Programme" activities
- [ ] 3W form - Links to create new 3w project end in error from Global, "add 3w project" and "Create a report" dropdown in top right of page. Seems to be when linking to /three-w/new, rather than the in-page popup.
- [ ] Sankey on country domestic projects - Remove sankey from country page for 'domestic projects' (but not international projects) for release on 05/07. 

Thanks!

**Comment by karitotp** [comment]
@batpad @frozenhelium, I found also these things to improve:

- On regional 3w maps, when you click on a marker on the map, the country names disappear from the map per seconds.

![3w](https://user-images.githubusercontent.com/11504548/124324135-17e5da80-db48-11eb-88c5-68370bb49dae.gif)

- In country 3w; the "National Societies" filtering is displaying many same values.

![Screenshot from 2021-07-02 15-41-30](https://user-images.githubusercontent.com/11504548/124326451-04d50980-db4c-11eb-9c25-6ac141f8092e.png)

- The charts in global 3w is not correctly displayed in other languages.

![Screenshot from 2021-07-02 15-47-41](https://user-images.githubusercontent.com/11504548/124327080-271b5700-db4d-11eb-849f-1e558645311d.png)
_Arabic language_

![Screenshot from 2021-07-02 15-50-53](https://user-images.githubusercontent.com/11504548/124327195-53cf6e80-db4d-11eb-8c0a-74333ee02b88.png)
_French language_

**Comment by tovari** [comment]
Closing this ticket and opening another one for further improvements.
