### ISSUE TITLE
Structure of HEOps/FACT/RDRT/RITs table

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#183]
<img width="1237" alt="screen shot 2018-02-09 at 10 32 51" src="https://user-images.githubusercontent.com/23258092/36021034-def2a364-0d84-11e8-869c-dc8e2d78b4fb.png">

On the tables for FACT/RITs/RDRTs, we would need to show:

Start Date
End Date
Name/Family Name of the person deployed
Function/Role
Country of the deployment
Emergency
Deploying National Society

On the table for HEOPs we would need to show:

Start Date
End Date
Name/Family Name of the person deployed
Country of the deployment
Emergency

**Comment by guipizzini** [comment]
cc @ascalamogna and @dereklieu can this be done?

**Comment by dereklieu** [comment]
@guipizzini The heops change has been made, but each FACT and RIT/RDRT record contains multiple people. Each of these people have different end dates, but they all have the same country and emergency. Should each of these people be a row of the table, or should the entire deployment be a row? If the former (each person is a row) this might be a bigger change than we have time for currently.

**Comment by dereklieu** [comment]
To add some more: this is because we changed up the FACT and RIT/RDRT schema towards the end. One thing we could do, instead of just having the number of people, is listing each individual person. We could also set the end date of the deployment to the the latest end date of any deployed person in that deployment. This would be within the phase 1 scope.

**Comment by guipizzini** [comment]
@dereklieu yes please, let's make one line per person as per HeOps structure. That would be amazing. I think there has been some confusion on this one during a call between our teams. No big deal, we can keep the total aggregate on top key figures bar on the header.
