### ISSUE TITLE
Translation dashboard improvements

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1830]
It would be great to add a few new functionalities to the translation dashboards:

- [x]  export all strings with existing translations to file, while missing translations could be displayed by an empty string - this would help us to update translations when necessary
- [x] export only new strings to a file - this will help to prepare the translation requests
- [x] add permission handling - a user permission should be created that allows editing on the translation dashboard (import as well) - only superusers should have this permission by default
- [x] add orange 'Staging' banner at the bottom of the Staging translation dashboard

**Comment by frozenhelium** [comment]
Available for testing [here](https://ifrc-go-feature-translation-dashboard-improvements.surge.sh/translation-dashboard/)

- [x] export only new strings to a file - this will help to prepare the translation requests
- [x] add permission handling - a user permission should be created that allows editing on the translation dashboard (import as well) - only superusers should have this permission by default
- [x] add orange 'Staging' banner at the bottom of the Staging translation dashboard

Any logged in user can access the dashboard in the view only mode (as shown in the screenshot below), but only those users, who have permission to modify the particular language string can modify the strings
![2021-04-27-131854](https://user-images.githubusercontent.com/4931541/116203265-3b149800-a75b-11eb-97cf-a3b1232ff44c.png)

**Comment by tovari** [comment]
Thanks @frozenhelium, looks good with superuser account. Unfortunately, I wasn't able to test with other accounts as it seems, I wasn't able to log out. After logging out from the staging admin page and clearing cache, it didn't ask my credential anymore.

**Comment by batpad** [comment]
@tovari not sure if this is the issue, but logging out of the Admin backend does not log you out of the front-end. You would need to logout of the frontend separately.

**Comment by tovari** [comment]
:) ah, sorry. I had an impression that the translation dashboard is using the backend login.
