### ISSUE TITLE
[PROD] Surge page displaying ops with 0 deployments under active deployments

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1836]
## Issue
Surge page displaying ops with 0 deployments under active deployments and showing ALL deploying organizations.

![image](https://user-images.githubusercontent.com/69478743/108715431-275e7280-751b-11eb-99bd-290f16c10e9f.png)

## Expected behaviour
Deployments overview by emergencies should only show emergencies that have active deployments. As well the deploying organization should only show the active ones not all of them.

## Impact
All users

## Severity
More of a visual issue

@batpad

**Comment by batpad** [comment]
This should be fixed on staging: https://dsgoproxyapp.azurewebsites.net/deployments

We should be able to get this in with the next production deploy.

**Comment by anamariaescobar** [comment]
Thanks @batpad, looks good on staging! Will be available to test once is on production
