### ISSUE TITLE
[PROD] Country dropdown lists

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1845]
## Issue
Ticket to outline how various dropdowns that reference the countries table should look across the site. Thanks to @nanometrenat for [raising and detailing an issue here](https://github.com/IFRCGo/go-frontend/issues/1673#issuecomment-749925775) that regions are wrongly being shown in the field report list (also quoted at bottom of this ticket).

This is focussing on frontend only. All records remain selectable in the backend. This actually works ok for now - as we're able to manually make changes not possible in the front end - e.g. for region-wide appeals, such as those used for Covid response.

## Expected behaviour
The following logic should be applied to all country and national society dropdowns:

- `record_type = 1` (countries only, not regions or clusters)
- `independent = TRUE`
 
There dropdowns across the site frontend (please shout if I've missed any). Below is the page and dropdowns within each page:

- **[Submitting a new field report](https://go.ifrc.org/reports/new)**
  - [x] Affected Country
- **[Creating a new 3W (click _add_ button to start form)](https://go.ifrc.org/regions/0#3w)**
  - [x] Reporting national society
  - [x] Country
- **[PER form (need to log in)](https://go.ifrc.org/per-assessment/create#overview)**
  - [x] National Society
- **[Completed PER assessments](https://go.ifrc.org/account#per-forms)**
  - Country - found in testing so not done this time. Ticketed here: #1869 
- **[Registering a new account](https://go.ifrc.org/register)**
  - [x] Country

## Related feature
Initially flagged in [this ticket ](https://github.com/IFRCGo/go-frontend/issues/1673)but separated out as main issue there closed.

> @jhenshall not the same thing, but may be related - I see that regions now show in the country dropdowns in some places - e.g. when creating a new Field Report - not sure if this was a deliberate decision to align with other lists/options elsewhere (e.g. admin site)? I know that sometimes _emergencies_ are deliberately created against regions/multiple countries but normally the _field reports_ would relate to just one country not a region. Cheers
> 
> old (a few months ago)
> ![image](https://user-images.githubusercontent.com/33625192/102959254-d85c8700-4543-11eb-9e89-8a2b4217bc5c.png)
> 
> now:
> ![image](https://user-images.githubusercontent.com/33625192/102959274-e5797600-4543-11eb-9e9b-65b55f3b040b.png)

## Impact
When last checked, no entries had been submitted to regions, but it is confusing to the user and we generally want to prevent users linking to regions / clusters.

cc @batpad @geohacker @tovari

**Comment by nanometrenat** [comment]
Thanks @jhenshall will be great to get this sorted.

I can see NSs are still creating Field Reports against regions - and this doesn't seem to be being picked up in the gardening process e.g. this one https://go.ifrc.org/reports/13993 and this one https://go.ifrc.org/reports/13636 - the emergencies are against the countries but the FRs are against the region

Cheers

**Comment by nanometrenat** [comment]
e.g. if you go to this page (when logged in) and look at the FRs list you'll see it clearly - https://go.ifrc.org/emergencies/4249#reports cheers ;)

**Comment by jhenshall** [comment]
That is super helpful, thank you @nanometrenat! Once the changes have been made, note to check other tables too and change all field reports wrongly created against regions before closing this ticket.

**Comment by jhenshall** [comment]
@geohacker @batpad @GregoryHorvath - I've just updated the 'Expected behaviour' of the ticket to better outline the requirements and all the dropdowns affected - I hope this is all of them?!

**Comment by batpad** [comment]
@jhenshall - dropdowns country list fixes have been deployed to staging. Could you check? This now essentially always only shows record type Country and independent=True for all the dropdowns mentioned above.

**Comment by jhenshall** [comment]
Thanks @batpad - looking good, with the exception of PER form: the independent filter doesn't seem to be working? It's not just the disputed entries that show, but still has all the duplicate entries.

**Comment by jhenshall** [comment]
Also just want to note the edge cases of ICRC, IFRC and Benelux. They are all 'countries' with `independent=null` but are appearing in all lists. Are we _including_ `independent=true` or _excluding_ `independent=false`?

Ideally these three 'countries' should only appear in dropdown: 3W > Reporting NS. This could be achieved by making that field exclude `independent=false` and all others include `independent=true`.

cc @batpad

**Comment by jhenshall** [comment]
We got it @batpad! All looking good on staging. 👍 🎉

**Comment by jhenshall** [comment]
Drop downs are now sorted on prod and recent field reports wrongly assigned to region have been changed to appropriate country.

**Comment by tovari** [comment]
Thanks @jhenshall. 
FRs assigned to a region appears now on the GO data quality dashboard shared with the regional IMs, so hopefully they will be able to detect such cases easily in the future.
