### ISSUE TITLE
URL of emergency page additional tab loads the operations tab

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1857]
## Issue

*https://go.ifrc.org/emergencies/5123#trends-and-analysis link loads the https://go.ifrc.org/emergencies/5123#details tab instead, if the page was not yet in cache.
This makes the shared urls confusing as not the relevant information appears for the user.*

## Steps to reproduce

*1. clear cache.
2. https://go.ifrc.org/emergencies/5123#trends-and-analysis*

## Expected behavior

*Should load https://go.ifrc.org/emergencies/5123#trends-and-analysis also at first load.*

**Comment by nanometrenat** [comment]
Hi @tovari this is a problem across a number of tabs - not just the 'custom' tabs but also the 'standard' tabs.
E.g. today I was reading the Emergency Appeal doc that has just been issued for the new wave of COVID in India/South Asia, the document links to https://go.ifrc.org/emergencies/3972#surge which should go to the surge tab.  However it was sending me to the front page of the emergency instead.

HOWEVER it's intermittent - I opened a new incognito browser window, copied and pasted that same URL (https://go.ifrc.org/emergencies/3972#surge) several times consecutively, and it was sometimes staying on the Surge tab (where it should be) and other times directing back to #details.  Same issue for another couple of emergencies I tried.

**Comment by szabozoltan69** [comment]
Works fine now.

**Comment by nanometrenat** [comment]
Hi @szabozoltan69 @tovari sorry to report this is still a problem (albeit intermittent).

I just copied and pasted https://go.ifrc.org/emergencies/3972#surge into my browser address bar, hit enter, and got redirected to #details.  This doesn't happen every single time but happens a lot - I tried 10 times, and only 3 of them correctly went to #surge.  This problem happened whether or not I was logged in to GO, and whether or not I was in an incognito browser window.  See [my screen recording from just now](https://ifrcorg-my.sharepoint.com/:v:/g/personal/natalie_gyles_ifrc_org/EXWBGG90ONdEkXwhwIC_uWgB_EdFvnHDYlpO72AZYSpTjA?e=E1d0uk).

Can you please take another look?  Not sure if it's an infrastructure/config thing or a code thing, given it's intermittent.

**Comment by szabozoltan69** [comment]
Ok, thanks @nanometrenat

**Comment by szabozoltan69** [comment]
Ok, thanks @nanometrenat. It's  true what you mentioned. In the original report there was this issue:  https://go.ifrc.org/emergencies/5123#trends-and-analysis – and it's OK now.  But due to the #surge-not-loading error let's keep this open.
