### ISSUE TITLE
GDACS alerts not pulling in to the Emergency page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#186]

**Comment by dereklieu** [comment]
This is a phase 2 item.

**Comment by guipizzini** [comment]
But they were there, before. They are not there anymore...

**Comment by guipizzini** [comment]
Can we have these back there, @dereklieu ?

**Comment by dereklieu** [comment]
My mistake, I thought this was referring to something else.

Looks like GDACs updated their website. The link we had been using looks to have been [deprecated](http://gdacs.org/rss.aspx). We can fix this.

**Comment by guipizzini** [comment]
Thank you, looking forward. Cheers

**Comment by guipizzini** [comment]
works fine. Thanks
