### ISSUE TITLE
[PROD] Completed PER assessments - country dropdown

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1869]
## Issue
[Completed PER assessments](https://go.ifrc.org/account#per-forms) - country dropdown displays all country records including non-independent, disputed and regions.

Should have like all other country dropdowns:
- `record_type = 1` (countries only, not regions or clusters)
- `independent = TRUE`

## Related feature
All other country dropdowns were covered in #1845 but reticketing this as only small part of original (more severe) issue remaining.

**Comment by jhenshall** [comment]
Logic should be:
Page | Dropdown name | DB field name | Record type = | Independent = | Disputed = | Notes
-- | -- | -- | -- | -- | -- | --
Completed PER forms | Select country (filter) | name | 1 (country) | TRUE | - |  

As outlined in #1997

**Comment by szabozoltan69** [comment]
Deployed to Staging.

**Comment by szabozoltan69** [comment]
![image](https://user-images.githubusercontent.com/6050643/216920540-20ae2bca-7d9a-4eb9-8049-0b050df79a1a.png)
