### ISSUE TITLE
Alert Hub 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1871]
Alert hub wil be an aggregator of official alerts from official alerting authorities...

**The Common Alerting Protocol (CAP)**
The Common Alerting Protocol (CAP) is an XML-based data standard for exchanging public warnings and emergencies between alerting technologies. CAP allows a warning message to be consistently disseminated simultaneously over many warning systems to many applications, such as Google Public Alerts and Cell Broadcast. CAP increases warning effectiveness and simplifies the task of activating a warning for responsible officials.
CAP is an international standard which communicates key facts of the emergency such as: What is it? Where is it? How soon is it? How bad is it? What should people do? It is a general format for exchanging all-hazard emergency alerts and public warnings over all kinds of networks. CAP allows a consistent warning message to be disseminated simultaneously over many different warning systems, thus increasing warning effectiveness while simplifying the warning task. CAP also facilitates the detection of emerging patterns in local warnings of various kinds, such as might indicate an undetected hazard or hostile act. And CAP provides a template for effective warning messages based on best practices identified in academic research and real-world experience. In short, with CAP, emergency alerting is more available, precise, reliable, secure, and faster than ever.

More info about CAP for GO: https://docs.google.com/presentation/d/1CxgvlxvS1GXQgV8gkaA9Z54MOYJB-gtXapJEfRStPfs/edit#slide=id.g709a45be86_0_67

**Comment by nanometrenat** [comment]
For whoever does the analysis on this build, a top tip from someone who uses the NZRC Hazard App (based on the Red Cross Global App):  remember that alerts can change (a lot) over time.  e.g. when an earthquake is first detected the notifying agency might create a CAP alert with a certain magnitude, then as more data comes in they send an update of that same alert.  For a while there the Red Cross app was sending a notification to users *every time* an updated alert message came through - meaning that people could be spammed 50 or so times as each tiny alert change came through - and to the user all looked the same (maybe a slight difference in magnitude, maybe a tiny difference in geo/location data).  Need to make sure that updates are handled with the appropriate business rules.

**Comment by tovari** [comment]
This is managed in Devops:
https://dev.azure.com/IFRC/IFRC_AlertHub
