### ISSUE TITLE
Risk Module feature 2: Risk Watch (includes INFORM Warning plus visualisation of hazard-impact models)

### ISSUE THREAD

**Issue by justinginnetti** [IFRCGo/go-frontend#1873]
**Is your feature request related to a problem? Please describe.**
*Within the new GO Risk Module, we will have several components. One of them will be a tab for Risk Watch (and other risk metrics). At present, this doesn't exist though it shares some similarities to the wireframes that were initiated for the crisis databank.*

**Describe the solution you'd like**
*This will visualise three kinds of information related to disaster risks: 1) risk metrics about seasonal risks (eg. by month); 2) simulated impacts and humanitarian needs caused by forecasted/detected natural hazards; and 3) information about potential early warning and anticipatory actions that National Societies might take.*

**Describe alternatives you've considered**
*Since this doesn't exist yet, and we need to build it, there aren't many alternatives.*

**Additional context**
*Add any other context or screenshots about the feature request here.*
![IM System v 2](https://user-images.githubusercontent.com/74773708/113107507-5051e180-9204-11eb-91f6-d571b8944e93.png)

**Where does the data come from and how is it maintained?**
*The information about seasonal risks will come from INFORM monthly risk rankings for the floods and cyclones; from IDMC about flood- and storm-related displacement risk; from IPC and/or FEWS NET about food insecurity (estimated population in IPC3 or above); so that data pipeline needs to be built. There may be additional historical data that we expose here too, either via partners APIs or once we've ingested it and stored it in our own database. The information about imminent events/detected hazards will come from the Pacific Disaster Center (via its API) and other partners as those other partners come on board. The information about potential early actions will come from IFRC's own data ecosystem, wherever this information is stored.*

**Should there be any restrictions around viewing or updating information related to this feature**
*The first two kinds of data should be visible to anyone; the third type of information may be visible only to the National Societies in some cases.*

**Links to documentation**
*A link to the draft concept note is [here.](https://docs.google.com/document/d/1l9AOocbKrYm6DjaVD0Uiwx3Hw3E7HUP7Yj_eHKlOosA/edit?usp=sharing) This feature is still being developed, and I will update it as I have a better sense of the user stories and requirements/specifications.*

**Comment by suraj-ram-shrestha** [comment]
NOTE: (TEST COMMENT) Task need to be broken down into granular level

**Comment by justinginnetti** [comment]
Hi, Ankit and DFS colleagues, thanks for the great work!
Some small fixes:
**Seasonal Risk y Month tab**

- [ ] Let's rename the tab "Seasonal Risk by Month" simply "Risk by Month"
- [ ] When you load the "Risk by Month" tab, the following text should appear just below the "Risk by Month" label: "This page displaces available information about specific disaster risks for for each month. When you move the slider from month to month, the information in the table and charts below will update automatically."
- [ ] The map: The map will need a legend that explains what the colors represent.
- [ ] The map: The data for disaster displacement risk for cyclones does not seem to be displaying correctly -- it doesn't match the data from the file provided by IDMC (labeled as "storms")
- [ ] The table below the map: Please reorder the table rows for Hazard Type as follows: Floods, Cyclones, Drought, Food Insecurity 
- [ ] Within the table the population exposure data does not seem to be displaying yet
- [ ] Within the table, we will need a pop-up box explaining the source of each metric and what it means; let's put the icon for the pop-up box at the column header (e.g., after "INFORM Risk Score")
- [ ] The pop-up box for the INFORM Risk Score should read: "These figures depict INFORM seasonal hazard exposure values for each country for each month on a five-point scale: 1: Very Low | 2: Low | 3: Medium | 4: High | 5: Very High. More information on these values can be found here[https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Covid-19/INFORM-Covid-19-Warning-beta-version]
- [ ] The pop-up box for the People Exposed should read: "These figures represent the number of people exposed to each hazard per month, on average. The population exposure figures are from the 2015 UNDRR Global Risk Model, based on average annual exposure to each hazard. The average annual exposure estimates were disaggregated by month based on recorded impacts of observed hazard events. [We need to then get a link to a description of Maria Teresa's methodology.] 
- [ ] The pop-up box for People at Risk of Displacement should read: "These figures represent the number of people expected to be displaced per month, on average, by each hazard. The estimates are based on the Internal Displacement Monitoring Centre's disaster displacement risk model using estimates for average annual displacement risk. These values were disaggregated by month based on historical displacement data associated with each hazard." [Again, we will want to link to the same methodology as above.] 
- [ ] The vertical bar chart: not sure that this is displaying the data correctly either. There should be two toggles here, one for the hazard (e.g., floods), the other for the risk metric (e.g., people exposed, people at risk of displacement)
- [ ] Historical data: I'm not seeing any historical data displaced in the plot at the bottom of the page. This should populate using data from the GO database.
- [ ] I'm also not sure I'm seeing the data from ThinkHazard here (should be to the right of the map) or potential early actions (also to the right of the map, below the ThinkHazard data). 


**Imminent Events tab**

- [ ] Under "Imminent Events" there should be text that says, "This page displaces information about the modeled impact of specific forecasted or detected natural hazards. By hovering over the icons, you can see the forecasted/observed footprint of the hazard; when you click on it, the table of modeled impact estimates will appear, as well as an information about who produced the impact estimate."
- [ ] The impact estimates for that first hazard that's being displayed should have the source of the estimate for each metric in parenthesis, and it should also have the look-up to the return period, which should then display to the right of each impact estimate metric.
- [ ] The name of the event should appear at the top of the pop-up box, so I'm not sure what the shaded gray box to the right of the page that says "EQ20210826HTI_1EQ" means -- this box on the right is useful though, and should be retained, as a way to navigate between multiple impact forecasts for the same event.

**Comment by justinginnetti** [comment]
- [ ] Today, for some reason, on the Haiti page, the people at risk of displacement/month is being populated for the Food insecurity row but not the cyclone row.
- [ ] For all figures in all of the tables on the risk module, let's round down/up to the nearest integer -- at least!

**Comment by mariam-yu** [comment]
@frozenhelium @justinginnetti Here is the updated UI for the merged page and the new graph: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=0%3A4957&node-id=1489%3A80559&viewport=274%2C48%2C0.24&scaling=scale-down-width&starting-point-node-id=0%3A4963&hide-ui=1 You can also fins there some placeholder designs, i.e. 
<img width="776" alt="Screen Shot 2022-02-16 at 12 42 44 PM" src="https://user-images.githubusercontent.com/60006476/154266895-e2b92454-29a6-4495-9e42-d7b046f00605.png">
<img width="621" alt="Screen Shot 2022-02-16 at 12 42 52 PM" src="https://user-images.githubusercontent.com/60006476/154266899-65ce4c42-194f-4b1a-8ee2-63e7eaa3f1fc.png">

And here the direct link to the canvas for the specs: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=1489%3A80559

Let us know if any questions (cc @maisadesign)
