### ISSUE TITLE
[PROD] Greece - Search list fails to find recent emergencies

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1881]
## Issue
*When creating a new Field Report, The search function doesn't find all recent emergencies.*

## Steps to reproduce
*Start to create a new field report at https://go.ifrc.org/reports/new
type Greece to the search field, which proposes only 3 recent emergencies:*

![image](https://user-images.githubusercontent.com/68283148/113863360-ddb7a780-97a9-11eb-9e33-d9765372e22d.png)

There are more emergencies so the search field should suggest the latest 10 emergencies:

![image](https://user-images.githubusercontent.com/68283148/113863885-7fd78f80-97aa-11eb-8bda-f850d442a8ab.png)

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
*Search should propose the 10 latest emergencies. E.g. in case of Bosnia*

## Impact
*Users cannot link new Covid Field Reports to the Greece Covid-19 emergency.*

## Severity
*Not sure, if this is a specific problem. It seems working in case of other countries, but might be a problem elsewhere as well. We haven't done a thorough check on all countries.*

## Is there a workaround?
*Admins can link FRs on the admin page.*

**Comment by tovari** [comment]
@szabozoltan69, @vdeak, would you mind to check this weird issue together? 

Gergely was already made some initial checks. I share here our conversation about it:
[3/17 11:54 AM] Daniel TOVARI
    ugy latom, h itt nem volt 10 emergency a covid ota
​[3/17 11:58 AM] Gergely HORVATH
    hmm de ezt az alap search se dobja fel ahoyg nézem
​[3/17 11:58 AM] Gergely HORVATH
    futtatok rá nemsokára egy reindex-et és meglátjuk mi a helyzet ezzel
(1 liked)​[3/17 12:08 PM] Gergely HORVATH
    Nagyon furcsa, lefutattam és nem vette fel...
​[3/17 12:08 PM] Gergely HORVATH
    És ahogy nézem csak azokat nem mutatjuk a Search-ben, amiknek a Parent Emergency-jében van valami
​[3/17 12:20 PM] Daniel TOVARI
    Ez azt jelentené, h parent emergencyt nem ad vissza a search?
​[3/17 12:20 PM] Gergely HORVATH
    Child-ot nem ad vissza, tehát aminél üres a parent azaz ő maga "a parent"
​[3/17 12:21 PM] Gergely HORVATH
    azokat vissza kéne adja
​[3/17 12:21 PM] Gergely HORVATH
    most próbálom az Elasticsearch-ből kihámozni, hogy egyáltalán létezik-e az index benne
​[3/17 12:28 PM] Gergely HORVATH
    
root@02a83bf366db:~/go-api# curl http://prddsgoes.northeurope.cloudapp.azure.com:9200/page_all/page/event-4320?pretty=true
{​​​​​​​​
  "_index" : "page_all",
  "_type" : "page",
  "_id" : "event-4320",
  "_version" : 1,
  "found" : true,
  "_source" : {​​​​​​​​
    "id" : 4320,
    "event_id" : 4320,
    "type" : "event",
    "name" : "Greece: COVID-19 outbreak",
    "keyword" : null,
    "body" : "Greece: COVID-19 outbreak Greece",
    "date" : "2020-05-01T09:00:00+00:00"
  }​​​​​​​​
}​​​​​​​​

Pedig van is rá indexünk

**Comment by szabozoltan69** [comment]
Gergely told me 2 weeks ago, that it's quite a weird issue (and it will be not easy to find the solution).
We can begin to work this out with Viktor, but I think we are in a previous state with the KT for really solving such an issue together.

**Comment by tovari** [comment]
Looks like we have a problem finding emergencies in the United Arab Emirates as well.

**Comment by batpad** [comment]
Right, so this seems like ElasticSearch issues again. There seem to be some conditions where records do not get indexed correctly in ElasticSearch.

Gergely's notes look good - we would need to check whether the records exist in ElasticSearch - if yes, why are they not showing up in search - if not, why are they not being indexed.

Iirc, there is also a command to re-index everything - we can check if this fixes the problem for now, while we investigate why it missed updating certain records.

@szabozoltan69 yes you are right, this is definitely one of the "hidden" parts of the system - it will be great if someone is able to take on the task of looking at the ElasticSearch setup more closely and perhaps making recommendations to increase stability of the search.

**Comment by szabozoltan69** [comment]
It's strange that if I give a direct search to portugal, in the answer there is nothing related to Portugal:
https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=portugal

**Comment by batpad** [comment]
@szabozoltan69 can you confirm if my understanding is correct --

The records seem to exist in ElasticSearch (i.e. Django is doing the correct thing and adding them to the index), but the results are not showing up on the search end-point?

If this is the case, we would need to delve into the exact search logic that ElasticSearch is using / weightage given to different fields, etc. Am happy to try and look at code together with someone to try and track down where we need to fix this.

**Comment by szabozoltan69** [comment]
@batpad yes, your understanding is correct.

**Comment by esario** [comment]
Received one user comment from Costa Rica: 

_When creating a new report in GO, it does not give you the option of "Costa Rica: COVID-19" so that it remains linked to that emergency already created. Currently, other emergencies can be seen but not COVID-19._

**Comment by tovari** [comment]
https://github.com/IFRCGo/go-frontend/issues/1132#issuecomment-783341112

**Comment by szabozoltan69** [comment]
[Local elasticsearch testing](https://osztalyta.li/es_bug.mp4) – bug could be reproduced.

**Comment by frozenhelium** [comment]
This was an issue due to a bug in the library used in the frontend, it should be fixed with the [PR #1886](https://github.com/IFRCGo/go-frontend/pull/1886) and available for testing in the [staging server](https://ifrc-go-fix-field-report-recent-emergency.surge.sh/reports/new)

CC: @tovari

**Comment by tovari** [comment]
Thanks @frozenhelium, @szabozoltan69 and @batpad! Great team work! 
Works well on staging.

**Comment by thenav56** [comment]
@batpad @szabozoltan69 
Looking at the logic used for elasticsearch. We are not including `name` attribute where the text we want is stored.

indexing logic:  https://github.com/IFRCGo/go-api/blob/develop/api/models.py#L600
Search logic: https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L110

If we include `name` there too, it should work right? Is there a way someone can check this? maybe @szabozoltan69

**Comment by szabozoltan69** [comment]
@thenav56 I can check it on the local environment.
What should I change in the code?
Maybe this?
  'fields': ['keyword^3', 'body', 'name']

**Comment by thenav56** [comment]
@szabozoltan69 Thanks.

Yes, make sure to use the production elasticsearch host. It has the required data. I would suggest to run this [code block](https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L102-L140) in a python shell locally using prod E host and print the response here.

**Comment by szabozoltan69** [comment]
Well, I could use only the local elasticsearch entity (due to the limitation of IP addresses that ES is listening to).
But I have results.
The main issue is: the ES engine searches with an "**OR**" applied to all the words written in.
So, if I write Hungary, it finds 82 entities,
but if I write "Hungary: covid-19" or "Hungary covid-19", it finds 191 entities. (If I use the above "name" extension, it finds 203.)
In this latest ^ query it finds "COVID-19 in Ecuador" also. So it found the "covid-19" string somewhere (without Hungary).

Is this behavior OK?

**Comment by szabozoltan69** [comment]
'fields': ['keyword^3', 'body', 'name'] - this is deployed to staging now, can be tested.

**Comment by tovari** [comment]
It seems to me the improvement is that it finds now not only Countries or Reports, but also Events.
Otherwise it fails to find exact search terms.
Examples:
Event to find: "Created in Spanish UI", country: "Hungary"
![image](https://user-images.githubusercontent.com/68283148/117178634-8c173280-add2-11eb-90f7-0537274732c1.png)
rank: 9

![image](https://user-images.githubusercontent.com/68283148/117178752-a9e49780-add2-11eb-8d53-d6aae95df558.png)
rank: 1 

![image](https://user-images.githubusercontent.com/68283148/117178918-d5678200-add2-11eb-8ffe-ff9ef0b81acd.png)
rank: >10

![image](https://user-images.githubusercontent.com/68283148/117179104-1495d300-add3-11eb-8c2d-d6370dfbee6f.png)
rank: 10

Event to find: "Flash flood in Hungary", country: HUN

![image](https://user-images.githubusercontent.com/68283148/117179463-6c343e80-add3-11eb-94a4-37ae63f945e0.png)
rank: >10

![image](https://user-images.githubusercontent.com/68283148/117179640-9be34680-add3-11eb-9e4c-8eb325ee194d.png)
rank: 5

![image](https://user-images.githubusercontent.com/68283148/117179887-e6fd5980-add3-11eb-8c5f-a7fbbbc64814.png)
rank: >10

![image](https://user-images.githubusercontent.com/68283148/117179995-03999180-add4-11eb-9e34-6bc2e8887413.png)

rank: >10

**Comment by tovari** [comment]
I think, multi word search ranking needs to be improved somehow, maybe by combining the lists of results to rank up the results that available on each result lists.

**Comment by thenav56** [comment]
@szabozoltan69 We can use the operator as `AND` https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#operator-min.
Let's try with that too.

We should also probably define custom queries for each `type` as the logic can be different while searching.

**Comment by szabozoltan69** [comment]
'operator': 'and' is added to the query. This version is deployed to staging and can be tested.

**Comment by tovari** [comment]
Wow, it is already very good!
Can we also order the results by the different types? Currently Reports are before Events:
![image](https://user-images.githubusercontent.com/68283148/117266746-de4d6780-ae55-11eb-90c9-96b25c220f13.png)

Would be great to have the following order:
1. country
2. event
3. report
4. appeal

**Comment by szabozoltan69** [comment]
Recently this is the only sort algorythm:
https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L115-L118
How could we change it to have the country-event-report-appeal order? @thenav56 @batpad ?

**Comment by thenav56** [comment]
@szabozoltan69 We may be able to do a custom sort like [this](https://medium.com/tensult/elasticsearch-sort-by-manual-input-order-5f366b6ea31e).

But we should definitely use different search logic for each type and `all`. In `all`, custom type sorting can be used.

**Comment by tovari** [comment]
As the fix has a high priority, we agreed with Zoltan to push to production the implemented improvements. 
I will create a new ticket for ordering the results.
Thanks for your contributions!

**Comment by szabozoltan69** [comment]
It went live.

**Comment by tovari** [comment]
Thnaks for the improvements!
