### ISSUE TITLE
Make 3W Records Distinct URLs

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-frontend#1882]
**Is your feature request related to a problem? Please describe.**
Right now 3W records do not have their own URL on the front end. If you want to access the data on the record, it appears as a popup from the country page. But as the tool gets adopted, there will be a need for users who build dashboards or other tools to provide the data to their users as well as the ability to click a link that brings them to the record itself.

**Describe the solution you'd like**
Add a unique identifier on the back end that can be queried with the rest of the data and used to build a URL that brings you to the relevant 3W record.

**Should there be any restrictions around viewing or updating information related to this feature**
I think whatever existing limitations have been put in place around viewing a given 3W record should extend to this feature.

**Comment by batpad** [comment]
@frozenhelium am going to assign this one to you, but leave it to @tovari to decide on prioritization. If you can provide a quick estimation of the work involved here (hours, days, weeks?) it would be great!

**Comment by tovari** [comment]
https://go.ifrc.org/three-w/1105/
