### ISSUE TITLE
Consolidate Mapbox styles

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1889]
## Issue
With the new Mapbox tilesets, we now have to replace all Mapbox styles across the site. This is also an opportunity to consolidate the styles used (there are currently different ones on homepage, 3W, emergency map and export).

Where the style is only used as a basemap, it should be relatively simple just swapping out the style url. Where layers are dynamically filtered (e.g. the emergency maps to show affected districts), this will require more work and thorough testing.

## New style
The new style can be [previewed here](https://api.mapbox.com/styles/v1/go-ifrc/ckrfe16ru4c8718phmckdfjh0.html?fresh=true&title=view&access_token=pk.eyJ1IjoiZ28taWZyYyIsImEiOiJjamlybHUzNmMwZDUxM3Fwa215YjJ1dzk5In0.OhqEybDX303sHjHzq3nFYQ) and has the Style URL:
`mapbox://styles/go-ifrc/ckrfe16ru4c8718phmckdfjh0`

There are some minor design changes, but the majority of the changes are the data that the styles use now being the GO-built tilesets.

To tidy things up, most style layers have been either deleted or renamed. [The full list of changes can be found in this spreadsheet.](https://docs.google.com/spreadsheets/d/1FF8kvGG__ifqMWlDDbpyH7yEDtd0fySAkO4dSjjMVlw/edit?usp=sharing)

## Pages with maps that need replacing

- [Homepage](https://go.ifrc.org/)
- [Regional operations](https://go.ifrc.org/regions/0#operations)
- [Global 3W](https://go.ifrc.org/three-w/)
- [Country 3W](https://go.ifrc.org/countries/290/#3w)
- [Country 3W (PNS view)](https://go.ifrc.org/countries/290/#3w)
- [Regional 3W](https://go.ifrc.org/regions/0#3w)
- [Emergencies overview](https://go.ifrc.org/emergencies)
- [Surge deployments](https://go.ifrc.org/deployments)
- [Emergency pages](https://go.ifrc.org/emergencies/5308#details)
  - Export button of the emergency maps

**Comment by jhenshall** [comment]
@batpad @geohacker I have edited the description of this ticket to include the new style and all the pages (I hope) that it needs adding to. This is obviously going to need a LOT of testing on staging but hopefully this is enough to get started.

cc @frozenhelium

**Comment by jhenshall** [comment]
Hey @szabozoltan69 - thanks for helping with this! As mentioned, the best way to make progress on this is to change the style on staging and see what breaks. We can then better understand the dependancies and what required to fix. Initial steps are:

## Add new style ID
For every map on site, replace the existing Mapbox ID in the style URL with the new style ID. 
**Every map should use** `ckrfe16ru4c8718phmckdfjh0`

 - Existing maps with `cki7aznup3hqz19rxliv3naf4`:
    - [ ] [Homepage](https://go.ifrc.org/)
    - [ ] [Regional operations](https://go.ifrc.org/regions/0#operations)
    - [ ] [Global 3W](https://go.ifrc.org/three-w/)
    - [ ] [Country 3W](https://go.ifrc.org/countries/290/#3w)
    - [ ] [Country 3W (PNS view)](https://go.ifrc.org/countries/290/#3w)
    - [ ] [Regional 3W](https://go.ifrc.org/regions/0#3w)
    - [ ] [Emergencies overview](https://go.ifrc.org/emergencies)
    - [ ] [Surge deployments](https://go.ifrc.org/deployments)
  - Existing maps with `cjxa3k4cx39a21cqt9qilk9hp`:
    - [ ] [Emergency pages](https://go.ifrc.org/emergencies/5308#details)
    - [ ] Export button of the emergency maps

## Dynamic maps

The emergency page maps will need additional work as layers are selected based on attributes (there may be others @geohacker ?). All the style name changes are outlined in [this spreadsheet](https://docs.google.com/spreadsheets/d/1FF8kvGG__ifqMWlDDbpyH7yEDtd0fySAkO4dSjjMVlw/edit) but relevant to emergencies page are:

- Layer name: `adm1` > `admin-1-highlight`
  - Attribute: `Admin01Nam` > `name`
  - Attribute: `Admin00Nam` > `country_name`

## Testing

This is intended as a starting point and there will likely be other issues.

The success criteria for this piece of work is that all maps function as they do now but with the new style. Once initial changes made, @jhenshall to test and outline issues. Will then need a thorough round of testing after initial catches.

cc @batpad @geohacker @tovari

**Comment by szabozoltan69** [comment]
Concerning the new style ID: after the replacement the git diff shows everywhere ckr...h0, where there is styles/go-ifrc:
```
-this.theMap = newMap(this.refs.map, 'mapbox://styles/go-ifrc/cjxa3k4cx39a21cqt9qilk9hp');
+this.theMap = newMap(this.refs.map, 'mapbox://styles/go-ifrc/ckrfe16ru4c8718phmckdfjh0');
-export default function newMap (container, mapStyle = 'mapbox://styles/go-ifrc/cki7aznup3hqz19rxliv3naf4', mapOptions = {}) {
+export default function newMap (container, mapStyle = 'mapbox://styles/go-ifrc/ckrfe16ru4c8718phmckdfjh0', mapOptions = {}) {
-export const defaultMapStyle = 'mapbox://styles/go-ifrc/cki7aznup3hqz19rxliv3naf4';
+export const defaultMapStyle = 'mapbox://styles/go-ifrc/ckrfe16ru4c8718phmckdfjh0';
-'mapbox://styles/go-ifrc/ck1izjgrs016k1cmxwekow9m0',
+'mapbox://styles/go-ifrc/ckrfe16ru4c8718phmckdfjh0',
```
The last one is src/root/views/CountryProfile/Map.js, not used.

**Comment by szabozoltan69** [comment]
The changes are in https://github.com/IFRCGo/go-frontend/pull/2024

**Comment by szabozoltan69** [comment]
It can be (quite) easily check all the used layout styles. They are:
```
grep map.*Property -ir1|grep "'"
views/RegionalThreeW/map.js:      map.setLayoutProperty('admin-0-label', 'visibility', 'none');
views/RegionalThreeW/map.js:      map.setLayoutProperty('additional-geography-labels', 'visibility', 'none');
views/CountryProfile/Map.js:      this.map.setLayoutProperty('admin-0-label', 'visibility', 'none');
views/CountryProfile/Map.js-      'admin-1-highlight',
components/map/emergency-map.js:    theMap.setLayoutProperty('admin1-selected', 'visibility', 'visible');
components/map/emergency-map.js:    theMap.setLayoutProperty('admin1-selected-labels', 'visibility', 'visible');
components/map/emergency-map.js:    theMap.setLayoutProperty('admin1-country-selected', 'visibility', 'visible');
components/map/emergency-map.js:    theMap.setLayoutProperty('admin1-country-selected-boundaries', 'visibility', 'visible');
components/map/emergency-map.js:      this.theMap.setLayoutProperty('admin-0-label', 'visibility', 'none');
components/map/emergency-map.js:      this.theMap.setLayoutProperty('additional-geography-labels', 'visibility', 'none');
components/map/main-map.js-    paint.push('rgba(0, 0, 0, 0)');
components/map/main-map.js:    const action = () => this.theMap.setPaintProperty('district', 'fill-color', paint);
components/map/main-map.js:    //       theMap.setLayoutProperty('admin-0-highlight', 'visibility', 'visible');
components/map/main-map.js-    //       theMap.setFilter('admin-0-highlight', ['==', 'OBJECTID', feature.properties.OBJECTID]);
components/map/main-map.js-        this.showOperationsPopover(theMap, feature, e, this.props.countries, 'appeals');
components/map/main-map.js:        // theMap.setLayoutProperty('admin-0-highlight', 'visibility', 'visible');
components/map/main-map.js-        // theMap.setFilter('admin-0-highlight', ['==', 'OBJECTID', feature.properties.OBJECTID]);
components/map/main-map.js-        this.showOperationsPopover(theMap, feature, e, this.props.countries, 'admin-0');
components/map/main-map.js:        // theMap.setLayoutProperty('admin-0-highlight', 'visibility', 'visible');
components/map/main-map.js-        // theMap.setFilter('admin-0-highlight', ['==', 'OBJECTID', feature.properties.OBJECTID]);
components/map/main-map.js-    // theMap.on('mouseleave', 'admin-0', e => {
components/map/main-map.js:    //   theMap.setLayoutProperty('admin-0-highlight', 'visibility', 'none');
components/map/country-map.js-    paint.push('rgba(0, 0, 0, 0)');
components/map/country-map.js:    const action = () => this.theMap.setPaintProperty('district', 'fill-color', paint);
components/map/common/map-component.js:      this.theMap.setLayoutProperty('admin-0-label', 'visibility', 'none');
components/map/common/map-component.js:      this.theMap.setLayoutProperty('additional-geography-labels', 'visibility', 'none');
```

**Comment by szabozoltan69** [comment]
Some quick local tests showed me that it is OK like this.
![kép](https://user-images.githubusercontent.com/6050643/131532453-39e2a202-7dc8-438a-94f4-d3850fdcee05.png)

**Comment by jhenshall** [comment]
Thanks @szabozoltan69 for [this comment](https://github.com/IFRCGo/go-frontend/issues/1889#issuecomment-909344712) - might be worth us going through this together at some point with @batpad @geohacker ? I don't understand it all but I suspect there will be a lot of dormant code e.g.  `additional-geography-labels` no longer exists and there is line:

> `components/map/common/map-component.js:      this.theMap.setLayoutProperty('additional-geography-labels', 'visibility', 'none');`



Could this be an opportunity to have just one global map component that is then only customised where needed - e.g. emergency page map?

**Comment by szabozoltan69** [comment]
The recent state is merged to develop via https://github.com/IFRCGo/go-frontend/pull/2024
@jhenshall proposed: now that every page uses the same map and it is just emergency that has the colouring - could this be consolidated into a global map component.

**Comment by tovari** [comment]
hi @szabozoltan69, would you mind to update the map symbology as well on the Emergencies page map?

**Comment by jhenshall** [comment]
Ok, we're slowly getting there and think we're ready for a good round of testing. @karitotp it would be amazing if you could help with this. I'll do my best to outline everything that needs testing but basically it's just a complete stress test of all the maps.

## Maps
All the maps that need checking on staging are:
- [Homepage](https://dsgoproxyapp.azurewebsites.net/)
- [Regional operations](https://dsgoproxyapp.azurewebsites.net/regions/0#operations)
- [Global 3W](https://dsgoproxyapp.azurewebsites.net/three-w/)
- [Country 3W](https://dsgoproxyapp.azurewebsites.net/countries/290/#3w)
- [Country 3W (PNS view)](https://dsgoproxyapp.azurewebsites.net/countries/290/#3w) - click the 
- [Regional 3W](https://dsgoproxyapp.azurewebsites.net/regions/0#3w)
- [Emergencies overview](https://dsgoproxyapp.azurewebsites.net/emergencies)
- [Surge deployments](https://dsgoproxyapp.azurewebsites.net/deployments)
- [Emergency pages](https://dsgoproxyapp.azurewebsites.net/emergencies/5308#details)
- Map export - Click export button of the emergency maps

## What to test
For most maps, all that has changed is the basemap so the functionality is not expected to change. However, would be good to test:
- Does it load and display what's expected?
- Is the new style displayed?
  - [View style here](https://api.mapbox.com/styles/v1/go-ifrc/ckrfe16ru4c8718phmckdfjh0.html?title=view&access_token=pk.eyJ1IjoiZ28taWZyYyIsImEiOiJjamlybHUzNmMwZDUxM3Fwa215YjJ1dzk5In0.OhqEybDX303sHjHzq3nFYQ&zoomwheel=true&fresh=true#1.86/14.69/14.13) - main visual difference is the country borders are grey instead of white
- Does the legend look right?
- Are the points clickable
- Are the countries clickable on homepage map only

For the emergency map, this has a lot more dynamic functionality, so good to test this more:
- Create a new emergency, does it display affected districts
- Change the districts affected in backend - does it update the map
- NOTE: we are aware of a bug that the map for smaller affected countries does not appear and this is already being worked on by @geohacker @batpad @szabozoltan69 

I'm sure I've missed a lot so please do test anything that you feel is missed. Thanks so much!

cc @tovari

**Comment by karitotp** [comment]
Hey @jhenshall,

I gave a look at all the maps on the site and they look good to me and the functionalities are working correctly :+1: 

> For the emergency map, this has a lot more dynamic functionality, so good to test this more:
Create a new emergency, does it display affected districts
Change the districts affected in backend - does it update the map

I tested this too and all is working as expected.

**Comment by jhenshall** [comment]
Amazing. Thanks a lot @karitotp! Will be great to get this finally released.

**Comment by tovari** [comment]
Closing this. We will set up a new to have a single map engine for all maps on the platform instead of many replicates.
