### ISSUE TITLE
Fix https bundle

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#189]
<img width="1273" alt="screen_shot_2018-02-05_at_16 38 46" src="https://user-images.githubusercontent.com/1590802/36100678-0d616e40-0fd5-11e8-8dcc-e159b3ae05b1.png">

<img width="348" alt="screen_shot_2018-02-05_at_16 40 49" src="https://user-images.githubusercontent.com/1590802/36100681-0f3bf0c8-0fd5-11e8-897a-c01395284f44.png">

**Comment by guipizzini** [comment]
All these seems to be working now, thanks @dereklieu

**Comment by dereklieu** [comment]
Great!
