### ISSUE TITLE
[Staging] React-select update breaks Field Report

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1891]
## Issue

@frozenhelium I can confirm that this is because of the select upgrade - I tried locally with the older version with rest of the code same, and then with the newer select version and it breaks. (STR below)

## URL

https://dsgoproxyapp.azurewebsites.net/reports/new

## Steps to reproduce

Fill in details on first page of Field Report form, including at least one District.

Try and press button to Continue.

## Expected behaviour

Expect to go to next step - instead get:

```
TypeError: val.map is not a function
districts
src/root/views/field-report-form/data-utils.js:139

  136 | nsAssistance: toBool,
  137 | isCovidReport: toBool,
  138 | country: (val) => val ? val.value : undefined,
> 139 | districts: (val) => val.map(o => o.value),
      | ^  140 | // countries: (val) => val.value,
  141 | event: (val) => val ? toNumIfNum(val.value) : undefined,
  142 | 
```

@frozenhelium - it seems like the way data is returned for Multiselects has changed? Let me know if you're able to take a look / if it seems familiar else I can dig.

## Criticality/Urgency

This would block release.

@szabozoltan69 thank you for finding this.

**Comment by frozenhelium** [comment]
@batpad I've figured out the issue and will very soon push the fix

**Comment by batpad** [comment]
@tovari sorry I think I forgot to add this to the board. This is fixed on production, closing.
