### ISSUE TITLE
April scope - Dropdowns don't work  

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1895]
## Issue
*Some of the drop-down selection don't work for some of the users.*

- In the FR creation in situation section, is not possible select the source.
![](https://paper-attachments.dropbox.com/s_C19F6355699F5F3FE3B655AA5749E90B4FE3D20D1A82F69A2520F182851F79D1_1619622482000_ifrcgo.gif)

- Some other options for selecting does not working in PER assessment creation
![](https://paper-attachments.dropbox.com/s_C19F6355699F5F3FE3B655AA5749E90B4FE3D20D1A82F69A2520F182851F79D1_1619623291604_ifrcgo1.gif)

- The country selection option does not display the selected option

![](https://paper-attachments.dropbox.com/s_C19F6355699F5F3FE3B655AA5749E90B4FE3D20D1A82F69A2520F182851F79D1_1619623521060_ifrcgo2.gif)

**Comment by tovari** [comment]
Hi @karitotp, could you please share more details about the environment you used? I'm unable to reproduce either in Chrome or FF. Thanks!

**Comment by szabozoltan69** [comment]
Recently there is a gap between the backend and frontend version. The develop frontend should be merged to frontend as soon as possible to avoid similar bugs. What do you think, @batpad ?

**Comment by frozenhelium** [comment]
@karitotp This should all be fixed in the [staging server](https://dsgoproxyapp.azurewebsites.net/)

**Comment by frozenhelium** [comment]
@szabozoltan69 yep we should once we verify that all these issue related to `react-select` are fixed :)

**Comment by frozenhelium** [comment]
For the reference:

**Comment by karitotp** [comment]
Hi @tovari, sorry for the late response.

My environment was:
- OS Ubuntu 20.04.2 LTS
- Browser: Google Chrome 90.0.4430.93
- Resolution: 1920x1080

> @karitotp This should all be fixed in the staging server

@frozenhelium yes, all this is working well now :)
