### ISSUE TITLE
Refactor Field Report Form

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1898]
**Is your feature request related to a problem? Please describe.**
Most of the Field Report Form code is obsolete. It uses method of coding that was used few years ago. Since then, React itself has updated a lot and has introduced better and easier way, which allows better, cleaner and less error-prone coding. If the Field Report Form is left as-is, It would be a bit difficult and  time consuming to add features or modify.

**Describe the solution you'd like**
Refactor the Field Report Form to use better code, form validation

**Comment by frozenhelium** [comment]
Available for testing on: https://ifrc-go-feature-new-field-report-form.surge.sh/reports/new

**Comment by batpad** [comment]
@frozenhelium this is some really amazing work here.

@karitotp - would you be able to spend some time testing https://ifrc-go-feature-new-field-report-form.surge.sh/reports/new to create field reports, and verify that all the information on the created field report is correct? Will be good to try a few combinations of things, there likely will be minor issues.

**Comment by batpad** [comment]
@karitotp to note: @frozenhelium is working on fixing the visual / CSS issues to make it look like the previous form, but it will be great if you can test the functionality, the validation, saving, etc. Thanks!

**Comment by karitotp** [comment]
@frozenhelium @batpad, here my findings testing the creation of different Field Reports

- The required title field validation is giving a error even when the title field is filled.

![Screenshot from 2021-05-20 09-40-13](https://user-images.githubusercontent.com/11504548/118999038-8c293d80-b94f-11eb-9646-199a714c4b9c.png)
 
- In a event related to Covid, in the Situation tab, when the "Number of new cases since last Field Report" is filled, the "Number of new deaths since last Field Report" field is also auto filled with the same above input number.

![Screenshot from 2021-05-20 09-02-36](https://user-images.githubusercontent.com/11504548/118992703-7b29fd80-b94a-11eb-8ccb-c6c402a080d5.png)

- In a event related to Covid, in situation tab, should the Source of figures and Date of data  be required fields when the numeric fields is filled? If so, the validation of required fields is not working here.

- When a FR is created, these fields are not displayed on the FR page. It seems that the imputs have not been saved, because when the FR is edited, those fields appear clean too.

![Selection_002](https://user-images.githubusercontent.com/11504548/119003051-08715000-b953-11eb-9c9f-cdf687e1b995.png)

In a FR no related to covid and a FR of Early Warning also there are numbers that are not been displayed.

![Screenshot from 2021-05-20 10-21-24](https://user-images.githubusercontent.com/11504548/119005615-36f02a80-b955-11eb-9737-feca04f29e5d.png)

- In an Early Warning FR, the sources for the numerical detail appear as not required unlike the sources in a event no related to covid where they are required.

![Screenshot from 2021-05-20 10-24-44](https://user-images.githubusercontent.com/11504548/119007215-a4e92180-b956-11eb-8fee-21481e6caa3f.png)

**Comment by frozenhelium** [comment]
@karitotp Thank you a top for testing these out. I've just pushed fixes for all of the issues mentioned above except the following one:
> - In a event related to Covid, in situation tab, should the Source of figures and Date of data be required fields when the numeric fields is filled? If so, the validation of required fields is not working here.

Could you please take a look at it again? Thanks again!

**Comment by karitotp** [comment]
@frozenhelium, all the above things is working good now :+1:

**Comment by frozenhelium** [comment]
# Summary of the refactor

### Identified Report types (EW, EVT, EPI, COV)
- Early Warning / Early Action
- Event
    - Epidemic
        - Covid
        - Other epidemic
    - Other event
    
### Form Steps
#### Step1: Context
- The type of report will be determined from this step with combination of various fields
- Conditions for different report types
    - EW: `Status` is `Early Warning / Early Action`
    - COV: `COVID-19 Related Event` is `Yes`
    - EPI: `Disaster type` is `Epidemic`
    - EVT: `Status` is `Event`
- `COV` is subtype of `EPI` and `EPI` is subtype of `EVT`

#### Step2: Risk Analysis / Situation
- `Risk Analysis` will appear for `EW` reports
    - Mostly contains numeric details / sources, source details and risk analysis
- `Situation` will appear for other report types (`EVT, EPI, COV`)
    - Mostly contains numeric details / source 
    - Fields will depend on type of report
    - For epidemic: Cumulative cases, suspected cases, confirmed cases, etc
    - For covid: Fields will be slightly different than epidemic
    - For event: injured, dead, missing, etc

#### Step3: Early Action / Action
- `Early Action` will appear for report type `EW`
- `Action` will appear for other types
- Will have similar type of fields for all report type with some added / removed fields

#### Step4: Response
- Will have similar type of fields for all report type with some added / removed fields

### Known issues in old system (Currently at staging server)
- `EPI` type report doesn't show intended fields for the Step2: Situation
- Any other `Disaster type` than the `Epidemic` can be selected for `COV` type of report along with the `Early Warning / Early Action` as `Status` which breaks the form when we proceed to Step2
- A report that is selected to be a `COV` type initially breaks the Step3: Action when we switch the report to `EPI` (i.e. set `COVID-19 Related Event` to `No`)
- When edition a field report from the field report detail page, sometimes previous data doesn't appear (It appears as new field report form)

### Notes for testing
- Check if the new system (Test server) matches closely with old system (Staging server). The known issues, mentioned above, should also be fixed
- Check if the above mentioned logic, steps for the form is functional
- Some of the labels, description of the fields change according to value of some other field (For example: In Step1: Context, date field has different label and description when disaster type is epidemic) 
    - Disaster type is not `Epidemic` ![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_7fafe2ed90cd3cc8b1473d64dc66dab7.png)
    - Disaster type is `Epidemic`
![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_6e1625a3a6c5670bdf28b11ffd566720.png)

- Some fields become conditionally required depending on the value of some other field (For example: As shown in the figure below, estimation becomes required when source is filled or vice-versa) ![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_dd85c981dc34920cb13f9b9cb2c8b321.png)
- Some fields become conditionally optional when other field is filled. For example: In Step1: Context, `Title` becomes optional when we link the report to an existing emergency. 
    - Title is required here ![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_f29147f4eaa69ca7bd319a901f08d9d1.png) 
    - Title is optional here ![](https://s3-ap-southeast-1.amazonaws.com/tc-codimd/uploads/upload_6bec59964cf3015efcc8aea6ee2f27cb.png)

**Comment by tovari** [comment]
When changing from Epidemic type of Event to EW/EA and back to Event, then a error message indicates the missing Disaster type. Disaster type should be cleared, but without error message. Error message should only appear when user tries to step to the next page.
![image](https://user-images.githubusercontent.com/68283148/119373046-499d9300-bcb8-11eb-8289-15b331a81cbf.png)

![image](https://user-images.githubusercontent.com/68283148/119373108-59b57280-bcb8-11eb-81b4-89b541016f4a.png)

**Comment by batpad** [comment]
@karitotp could you give this another test, based on @frozenhelium's comment above?

**Comment by karitotp** [comment]
@batpad , all is working as @frozenhelium's comments and the field required message when a epidemic report is changed to Early warning reported by @tovari is still there.

**Comment by tovari** [comment]
@frozenhelium, here is a text duplication on Action tab, only 'Information Bulletin' should appear in bold text in the first line:
![image](https://user-images.githubusercontent.com/68283148/119782240-36fba780-becc-11eb-87da-1f89c188777b.png)

**Comment by tovari** [comment]
@frozenhelium, noticed that some of the field values are not saved:
Situation tab:
- Source details
- Situation overview
Actions tab:
- Actions Taken by Others (Governments, UN)

**Comment by frozenhelium** [comment]
> When changing from Epidemic type of Event to EW/EA and back to Event, then a error message indicates the missing Disaster type. Disaster type should be cleared, but without error message. Error message should only appear when user tries to step to the next page.
> ![image](https://user-images.githubusercontent.com/68283148/119373046-499d9300-bcb8-11eb-8289-15b331a81cbf.png)
> 
> ![image](https://user-images.githubusercontent.com/68283148/119373108-59b57280-bcb8-11eb-81b4-89b541016f4a.png)

@tovari This is expected behaviour (i.e. we set the validation to immediately trigger). This behaviour is consistent with other places as well, where the validation is immediately triggered when related fields are changed. Let me know if we should change this behaviour.

**Comment by batpad** [comment]
@karitotp could you do one final test of the Field Report form functionality that everything looks good after all the latest changes?

**Comment by anamariaescobar** [comment]
Some feedback from the UAT regarding Field Reports:

- [ ] In the Epidemic FR the actions taken by the IFRC is showing only 3 actions, this list should match the list used for Actions taken by National Society and for any other RCRC actor
- [ ] When No on international assistance requested is checked, it doesn't shows up on the review page, the Yes is working correctly
- [ ] 
@batpad

**Comment by karitotp** [comment]
@batpad this is what I found

- In EW field report, the title Affected Pop Centres that have as source "Government" appears only as "Affected".

![Selection_001](https://user-images.githubusercontent.com/11504548/120338703-1a8bb080-c2ba-11eb-8a3b-bc1f47d422a7.png)

- In the edition mode of a FR, the data of "Region / Province" and "Date of Data" does not load.

**Comment by frozenhelium** [comment]
@anamariaescobar Thanks for the catch. I've fixed the "No" not being showed for the "International assistance requested". For the Epidemic FR actions taken by the IFRC, it appears different in the staging because it's loaded from the API. It'll be same as other 2 when it goes to production. I verified this in my local setup using the prod API.
