### ISSUE TITLE
DMIS users and GO

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#190]
Hi @dereklieu do you confirm, that if a user registers in DMIS it will be ported into GO?

As well, that all the DMIS database of users will be migrated to GO?

Any manual action required from our side?

Thanks.

**Comment by dereklieu** [comment]
New DMIS users will be ported to GO, and existing users who make changes to their profile in DMIS should see those changes propagated to GO as well.

Currently we're having GO only ingest users who have logged into DMIS at least once within the last year. If we want to have all users, even inactive ones, we can change this. There are about 11,000 user records in DMIS I believe, and with the one-year restriction, about 2,200 are being ingested.

**Comment by guipizzini** [comment]
Perfect, thank you.
