### ISSUE TITLE
PROD MDRMM016 appeal filter removal

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1909]
MDRMM016 was a hidden appeal when it was launched. To block publishing it on GO, it is filtered at the moment in the ingest_appeals.py file.
Now, it is public, so we should also publish it on GO. Please remove this appeal from the filtered ones.

**Comment by vdeak** [comment]
Sure, removing MDRMM016

**Comment by vdeak** [comment]
Deployed to Staging

**Comment by vdeak** [comment]
Deployed to PROD. also ran the Cronjob, the new appeal (MDRMM016) was created.
