### ISSUE TITLE
Replace square GO favicon with circular icon

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1913]
**Minor issue** - Replace current _square_ GO browser icon 

**Describe the solution you'd like**
Replace with filled _circular_ GO logo negative icon 

**Links to documentation**
GO design documentation currently lives here: https://go.ifrc.org/about

cc @mariam-yu to confirm any additional specs

**Comment by tovari** [comment]
@LukeCaley, would you mind to add a screenshot about the square GO browser icon? Thanks!

**Comment by LukeCaley** [comment]
![GO-square-icon](https://user-images.githubusercontent.com/7791954/119493390-6e4d4580-bd60-11eb-8c51-bbc719987e0d.JPG)

**Comment by mariam-yu** [comment]
@LukeCaley @tovari H
Here are the round favicons without the background: https://drive.google.com/drive/folders/1ehSy1mlrKAn-WoJSFljEUz9kwtt-fela?usp=sharing

**Comment by tovari** [comment]
Hey @frozenhelium, @vdeak, I'm not sure, who could do this update? Thanks!

**Comment by frozenhelium** [comment]
It's now available on staging
![2021-07-12-091516](https://user-images.githubusercontent.com/4931541/125226998-c7ae0b80-e2f1-11eb-9e7c-81010cda53d2.png)
Note: Might need to hard refresh the page (since favicon are cached by browser)

CC: @tovari
