### ISSUE TITLE
Maintain ERU types (and other such lists) one place

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#1914]
Recently ERU types are listed on backend: https://github.com/IFRCGo/go-api/blob/develop/deployments/models.py#L18-L53
And also on frontend: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/eru-types.js
It would be good to read data from backend and not keeping hard-coded values on frontend. (In case of change it is double work and can be forgotten, as it happened in https://github.com/IFRCGo/go-api/issues/1085 )

(If there is a fancy way of compiling js code based on go-api backend at build time, then no api call would be needed each website watching. But if it is not possible, then api call would be made. Maybe one api call to gather "all such lists".)

**Comment by batpad** [comment]
Thanks @szabozoltan69, it would definitely be good to get these as part of an API call, perhaps added to the initial data call from the frontend and cached on the frontend.

cc @frozenhelium

**Comment by szabozoltan69** [comment]
A possible solution is to generate frontend file based on backend. In case of backend change the developer should run this in a directory which is just above the go-api root directory:
https://github.com/IFRCGo/go-infrastructure/blob/develop/bin/create_frontend_ERU_types.py
The (renamed) result should be put into the appropriate frontend directory.

(We can make similar converters for other files also.)
This is not an automated way, but a bit better then nothing.

**Comment by batpad** [comment]
@szabozoltan69 no, we will just have the ERU types available on the API, and then the frontend can fetch it from the API rather than from values from a file, so changes are immediately reflected, etc. I can take a look a bit more in detail, but we should definitely not generate files here, but rather just fetch this data from the API and change the frontend code accordingly.

**Comment by szabozoltan69** [comment]
@batpad Ok, no problem, if we do not use this.
(My motivation was: to avoid a lots of unnecessary API calls. And to write a fine python script. :-)  )
But it would be cleaner via API calls, it's sure.

**Comment by frozenhelium** [comment]
> Thanks @szabozoltan69, it would definitely be good to get these as part of an API call, perhaps added to the initial data call from the frontend and cached on the frontend.
> 
> cc @frozenhelium

@batpad If we're using it on only one page / view, lets limit it there. Otherwise we should include this in the initial data
