### ISSUE TITLE
Key figures sequence on the UI should be determined by the sequence on the admin page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1921]
When adding key figures to an emergency and editing these later on the admin page, the order on the frontend is not maintained anymore. The sequence of key figures (left to right) on the frontend should be the same as the sequence on the admin page (top to down).

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/68283148/120985301-c8480500-c77b-11eb-8729-3c0e378223b2.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/68283148/120985320-cbdb8c00-c77b-11eb-80cc-31d684f1fb8f.png)

cc: @ryales

**Comment by szabozoltan69** [comment]
This is a backend task (only), because the backend gives the key figures in this order; the frontend only displays them so.

**Comment by szabozoltan69** [comment]
Via an "ordering" classMeta parameter It works fine in local environment; I deploy it to staging.
![kép](https://user-images.githubusercontent.com/6050643/148217253-960f4559-0b09-485d-8b47-94007f8523e5.png)
![kép](https://user-images.githubusercontent.com/6050643/148217357-b7223405-7109-41b7-83fe-8ba803e27f77.png)

**Comment by szabozoltan69** [comment]
Deployed to staging.

**Comment by tovari** [comment]
Thanks @szabozoltan69, works well!
