### ISSUE TITLE
Add error message for non-supported browsers

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#1925]
Add error message for non-supported browsers as mentioned in the https://docs.google.com/document/d/1WYjUFqExYOjsNTVT5oEGiuaxYFuehZCG7FgJWfYm7wU/edit

Xref: #1556

#### Page alerts > Browser not supported
This will be a style for all the on page alerts where the top navigation cannot be loaded. So, the message shows directly. The alerts should match in style, and it’s important to guide to the user to the next step, if possible pushing to open the other browsers or downloading the latest one for their own browser.
![2021-06-07-181047](https://user-images.githubusercontent.com/4931541/121016406-d0279980-c7bb-11eb-8ec0-5327722d122c.png)

**Comment by tovari** [comment]
It looks like this in Explorer. Links are not incorporated, but this is fine. Would be good though to mention Edge as an example of Chromium browser. E.g.: "Please open the same URL in Chrome, Safari or any Chromium (e.g. Edge) based browser."
![image](https://user-images.githubusercontent.com/68283148/127992386-5553200d-b621-4833-b54d-b9cc0546c8f8.png)

**Comment by frozenhelium** [comment]
New wording from @LukeCaley 

>GO doesn't work on Internet Explorer.
>Please visit GO on Chrome, Edge, Safari, Firefox or any other chromium based browser

**Comment by tovari** [comment]
![image](https://user-images.githubusercontent.com/68283148/128196653-0c000944-a444-4876-aba9-dfbec5e4a8e8.png)
