### ISSUE TITLE
Upgrade Mapbox GL

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#1927]
We should upgrade Mapbox GL to the latest version.

cc @frozenhelium @geohacker

**Comment by batpad** [comment]
@geohacker whenever able, would you be able to add some colour to this issue? Any outline of what we'd need to do / any known gotchas, etc?

**Comment by frozenhelium** [comment]
@batpad We are currently on the way to update the Mapbox version, since we need it to implement new 3W map features. We should list the pages where maps are displayed to verify that all the maps are being displayed properly after the update.

**Comment by batpad** [comment]
cc @geohacker @jhenshall 

List I can think of:

 - Home-page map (similar on Region pages)
 - Surge deployments page
 - Map on Emergencies page
 - Map on page for Single Emergency (for emergencies that have country / district attached)
 - 3w maps
 
@jhenshall have I missed anything above? @frozenhelium feel free to reach out for any clarifications on any of these pages.

**Comment by batpad** [comment]
@frozenhelium a thing to note: the Export Map functionality on most of these (most important on the Emergency Detail page map) - we'd need to test that the image download of the map still works - that code is a bit brittle in general, so we'd need to test that well. Another note to test multilingual labels across maps, as well as the Full Screen view on the home and region pages to make sure maps work fine in "full-screen" mode.

**Comment by batpad** [comment]
@frozenhelium this is all done? 

@tovari sorry we missed having this on the project board as it became a dependency for some of the 3w maps. I've moved it to `Done` on the project board. If @frozenhelium doesn't flag any work remaining to be done here, I think this can be closed.

**Comment by frozenhelium** [comment]
@batpad @tovari this is all done
