### ISSUE TITLE
Field report can be submitted without a Title

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1929]
## Issue
A new FR can be submitted without title, when it is linked to an existing emergency.
Validation works properly when the new FR is not linked to an existing emergency.

See example: https://dsgoproxyapp.azurewebsites.net/reports/9774

**Comment by batpad** [comment]
@tovari hmmm just the Title I thought we allowed users to either link to an existing Emergency or Add a Title, and if Linked to an Existing Emergency, it should just take the title from the Emergency? Am pretty sure that's how it always worked from the frontend? I don't think this behaviour is changed - we always required EITHER the association with Emergency or a title, so its a bit unclear whats happening here..

**Comment by tovari** [comment]
@batpad, okay, edited the comment. Lets apply the original logic then.

**Comment by batpad** [comment]
@frozenhelium do you know if there might be any change in how we send the title to the backend when not filled in? i.e. sending as empty string instead of `null` or so? Not fully sure how we best track this down.

**Comment by tovari** [comment]
Hey, the problem is more complex and not sure, if this is one issue or more. 
I inserted the same data myself on staging and prod with different results. On staging all was okay. On prod, I got an error message about unknown error. This was reported by another user as well (and I posted the screenshot on the dev channel). Despite of the error message, the FR has been created  on prod as well. So I guess, the user was just kept trying to submit the FR by hitting the submit button several times.
Also strange that the Health description doesn show up on the created FR:
https://go.ifrc.org/reports/14368
but available on the backend:
https://goadmin.ifrc.org/en/api/fieldreport/14368/change/

**Comment by frozenhelium** [comment]
@batpad We don't send anything at all if the title is not defined

**Comment by batpad** [comment]
@tovari the specific issue of the frontend skipping validation for the Title field if an Emergency was selected has been fixed and deployed as a hotfix to production. So a user will no longer be allowed to submit field reports with empty title / summary fields from the frontend.
