### ISSUE TITLE
[PROD] 3W reporting National Society drop down - ICRC & IFRC

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1934]
## Issue
The reporting National Society drop down on the 3W form needs to contain IFRC, ICRC and Benelux. This bug will be as a result from the recent consolidation of country drop downs: #1845 

[This comment](https://github.com/IFRCGo/go-frontend/issues/1845#issuecomment-792742873) does outline the desired behaviour but I must've missed this in testing:

> Also just want to note the edge cases of ICRC, IFRC and Benelux. They are all 'countries' with independent=null but are appearing in all lists. Are we including independent=true or excluding independent=false?
>
> Ideally these three 'countries' should only appear in dropdown: 3W > Reporting NS. This could be achieved by making that field exclude independent=false and all others include independent=true.

## Steps to reproduce

- [Go to page to add new 3W](https://go.ifrc.org/three-w/new)
- Click 'Reporting National Society' drop down
- Should have ICRC, IFRC and Benelux

## Related feature

- https://github.com/IFRCGo/go-frontend/issues/1845

## Impact
IFRC staff are trying to add 3W and ICRC have the most projects so this is a blocker for them adding new data.

**Comment by batpad** [comment]
cc @geohacker @frozenhelium @jhenshall - can we get on a quick call and just clarify the logic to use for various cases, and hopefully turn that into a document of some sort?

@frozenhelium - sorry, this is a bit confusing and its really easy to get the country filters wrong between the various lists. This should ideally be a quick fix.

**Comment by jhenshall** [comment]
I would love that @batpad - definitely need to get it documented! Like you say, it's so easy for this to happen when so many are just slightly different.

**Comment by jhenshall** [comment]
Logic should be:
Page | Dropdown name | DB field name | Record type = | Independent = | Disputed = | Notes
-- | -- | -- | -- | -- | -- | --
New 3W | Reporting National Society | society_name | 1 (country) | TRUE & NULL (NOT FALSE) | - | Includes unique NS + ICRC, IFRC & Benelux

As outlined in #1997

**Comment by LukeCaley** [comment]
Believe this has been released but please confirm, xRef to release notes and close if so @tovari

**Comment by batpad** [comment]
Merged a fix for this to staging.

**Comment by batpad** [comment]
This should now be fixed on prod. cc @tovari
