### ISSUE TITLE
[PROD] Repetitive entries in NS dropdown on signup page

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-frontend#1936]
## Issue
Multiple NS appear multiple times on the NS dropdown list when creating a new user account.

## Steps to reproduce

- Go to https://go.ifrc.org/register
- Select "National Society" from the "Organization Type" dropdown
- Open the "Organization Name" dropdown
- Following orgs appear multiple times on the dropdown: 
    - American Red Cross
    - Australian Red Cross
    - British Red Cross
    - Danish Red Cross
    - French Red Cross
    - Japanese Red Cross
    - Norwegian Red Cross
    - Red Cross Society of China
    - The Red Cross of Serbia
    - The Republic of Korea National Red Cross
    - The Russian Red Cross Society

![image](https://user-images.githubusercontent.com/15220593/121908771-9875a000-cd2d-11eb-8160-975edeb2b3ab.png)

## Expected behaviour
Each NS should appear only once on the list.

## Related feature
Could this be related to those NS having multiple admin regions, e.g. Australian RC has Australia and Tasmania, American RC and French RC have overseas territories, etc.

## Impact
People signing up.

## Severity
Cosmetic.

## Is there a workaround?
None identified.

**Comment by batpad** [comment]
cc @jhenshall @geohacker @frozenhelium 

Country filters strike again! I **think** this is because there are a bunch of non-independent countries that have the same National Society name and we are not filtering out non-independent countries here? @jhenshall so now we have at least these two lists where we need to (re)define exactly what logic to use to display in the dropdown:

 - 3w form (to make sure the logic includes IFRC / ICRC)
 - Signup form (to make sure logic excludes repeat national society names).

This seems like a bit of a critical issue, and if this is a very straightforward fix, I might be tempted to recommend a hotfix here.

cc @tovari

**Comment by jhenshall** [comment]
Logic should be:
Page | Dropdown name | DB field name | Record type = | Independent = | Disputed = | Notes
-- | -- | -- | -- | -- | -- | --
User registration | Organization Name (when Org Type = NS) | society_name | 1 (country) | TRUE | - |  

As outlined in #1997

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/2002 fixes this.

**Comment by szabozoltan69** [comment]
(The cleanup is still in progress: the lookup of the problematic registrations of the last few months.)

**Comment by batpad** [comment]
Fix for this is now on staging, cc @esario @jhenshall - thank you @szabozoltan69 !

@szabozoltan69 the update on the db to "fix" registrations that may have occured in the past months and point to the wrong country in the database, that looks good to me. Let's wait for @jhenshall to be back to confirm the logic before we run it though - I think it is okay if that waits a week or so.

**Comment by jhenshall** [comment]
Amazing, thanks @szabozoltan69 @batpad ! Logic sounds good to me.

As discussed on call, but to clarify here. We will only be changing the records where the 'Organisation Name' is linked to a non-independent country, not the field for users' country of residence.

e.g. a user could have `country` = `Anguilla` but will be `organisation` = `United Kingdom (for British Red Cross)`

Where organisation is taken from non-independent country, the `sovereign_state` field in country database to be used to link to correct NS country. Thanks!

**Comment by szabozoltan69** [comment]
This is the logic, ok!

**Comment by szabozoltan69** [comment]
Recently there is the 13 cases. In some of them the organization is set quite properly, showing the sophisticated situation. Shall I overwrite them?
```
postgres=> select org,org_type,department from api_profile where user_id in (select p.user_id 
from api_profile p 
join api_country c on (c.id = p.country_id) 
where not c.independent);
                          org                          | org_type |             department             
-------------------------------------------------------+----------+------------------------------------
 OSB                                                   | NTLS     | NR EMT
 Anguilla Red Cross (Branch of the British Red Cross)  | NTLS     | Anguilla Branch
 Overseas Branch of National Society                   | NTLS     | Disaster Management
 The Netherlands Red Cross OSB Aruba                   | NTLS     | NIT& VCA member
 OSB                                                   | NTLS     | RED CROSS ARUBA
 Red Cross                                             | NTLS     | Red Cross
 Programme Officer                                     | NTLS     | Disaster Preparedness and Response
 The Netherlands Red Cross OSB Aruba                   | NTLS     | NIT& VCA member
 Netherlands Red Cross Chapter Aruba                   | NTLS     | Volunteers 
 Red Cross Aruba                                       | NTLS     | Red Cross
 Red cross Aruba                                       | OTHR     | 
 OSB Netherlands Red Cross                             | NTLS     | Marketing & Operations
 Bermuda Red Cross/OSB                                 | NTLS     | Health, Safety & Disaster Services
(13 rows)
```

**Comment by szabozoltan69** [comment]
Then we should not update anything, organization can remain this string as it is now. (Discussed with Sanjay.)

**Comment by jhenshall** [comment]
This is interesting thanks @szabozoltan69 ! It shows the need to better represent overseas branches in the dataset. With the current setup, if they select National Society as org type, then the National Society should be British RC or Netherlands RC but it's then a shame to overwrite this more granular overseas branch information. Great if you've already discussed with @batpad .
