### ISSUE TITLE
[PROD] Grey screen when accessing go.ifrc.org via mobile browser and trying to search

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1943]
## Issue
This morning I was trying to look up a specific GO link to send to @JonathanGarro and used my (android) phone.  Got a grey screen when searching - however I don't get a grey screen when doing the same thing via a laptop/desktop browser *
I browsed to go.ifrc.org, waited for it to load, 

## Steps to reproduce
* go to go.ifrc.org on a mobile device
* type something in the search bar e.g. "switz" or "united"
* screen immediately goes grey

This is definitely to do with mobile version of site rather than due to my device, as I also tried emulating mobile when using Chrome on my laptop and I had the same problem - see below for screenshot with console errors.

I know go.ifrc.org isn't optimised for mobile, but it'd be great to get rid of the grey screen :)  Thanks!

![image](https://user-images.githubusercontent.com/33625192/122154227-97bd4500-ceb8-11eb-8955-7bf278655426.png)

## Expected behaviour
Should never get a grey screen using basic functions

## Impact
All users on mobile who are trying to search (I assume)

## Is there a workaround?
Use a desktop not a mobile

**Comment by batpad** [comment]
I can reproduce this. @tovari @frozenhelium - could we add this to the next sprint? This is likely something quite silly and is a pretty terrible bug for anyone who navigates from mobile.

**Comment by nanometrenat** [comment]
Closing due to rewrite having brought much better mobile support - thanks a million
