### ISSUE TITLE
Update links on GO Resources page

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1960]
**Several hyperlinks on the GO Resources page should be updated with the Release 5.2**

- Replace `Visual Guidelines` with link to `GO User Library` [URL](https://go-user-library.ifrc.org) 
- Replace `Visual Identity` with link to `GO Blog` [URL](https://ifrcgoproject.medium.com/)
- Replace `IFRC IM Strategy` with link to `IFRC IM Strategic Direction` [URL](https://ifrcgoproject.medium.com/information-saves-lives-scaling-data-analytics-in-the-ifrc-network-fd3686718f9c)
- Replace `GO presentation materials` with link to `GO Workplan 2021` [URL](https://ifrcorg.sharepoint.com/:f:/s/IFRCSharing/Es9Yv8LsLVBGn_jAkphR4YMBuZOD0eFgKPVCQMvREPw8ig?e=eLaaXF)

**Comment by batpad** [comment]
@LukeCaley pushed these changes to staging - if you could check that it looks fine, we can include them in this release.

I imagine translations should be fine - new strings would show up on the Translation Dashboard that would need translating and then it should all work.

cc @frozenhelium

**Comment by nanometrenat** [comment]
Hi @LukeCaley and team, most fabulous to see the GO presentation just now!  However I just clicked on the GO User Library link from https://go.ifrc.org/about and sadly it is broken (cannot be reached / DNS_PROBE_FINISHED_NXDOMAIN)
Not sure if the link (https://go-user-library.ifrc.org/) is wrong or if I'm just being impatient and there is still another step to get it released?  Thaaaaaaanks!

**Comment by tovari** [comment]
Hi @nanometrenat, indeed, the User Library is not live yet there. We still need a couple of updates done by BRC. I will notify you as soon as it goes live.

**Comment by nanometrenat** [comment]
@tovari the link from GO is now working (i.e. not a broken link) but the GO User Library at https://ifrcgo.org/go-user-library/ doesn't function... the links along the top menu work fine, but the links in the main body don't work at all - hence reopening.  Not sure whose remit this is?  But looks a bit dodgy...
![image](https://user-images.githubusercontent.com/33625192/131452031-28d6249b-d2ad-4914-9f5f-446b6f2883d0.png)
