### ISSUE TITLE
Frontend Changes to Surge pages for Molnix Integration

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1965]
Changes in the frontend, specifically Global surge page: [https://go.ifrc.org/deployments](url) and the Emergency surge page (example): [https://go.ifrc.org/emergencies/5308#surge](url) needed for the soon deployment of the Molnix system (Deployment date 1 of August 2021).

Wireframes prepared by Mariam here: [https://projects.invisionapp.com/share/B3XKVKZJWY9#/screens/361601984_5-1_GO_Deployment](url) and [https://projects.invisionapp.com/share/3QXKWXWTAHF#/screens/414729370_4-3-4_GO_Specific-Emergency_Epi](url)

Some point to take into account:

**Global Surge page**
- [x] #2011
- [x] Add a new key figure with Total Rapid Response personnel deployed (this will be a cumulative number of all deployments for the year)
- [ ] On the little information button on the key figures we should add a pop up that reads: Currently deployed, for both Rapid Response personnel and ERU.
- [x] Map: I think we should follow the style of the map on the front page of GO [https://go.ifrc.org/](url), the scale of the points will be the number deployed, categories will be Rapid Response Personnel and ERU.
- [x] Charts below the map: Top 5 NS deploying Rapid Response Personnel, the tittle should include the year and the chart must be cumulative for the present year
- [x] Charts below the map: Rapid Response personnel, add in the last 12 months in the tittle and the chart should always show the last 12 months of data.
- [x] Open Surge alerts: The field application deadline can be ignored, the surge team has decided not to input any data there.
- [x] Open Surge alerts: Can we move the column Start Date before Duration?
- [x] Keywords: Is there a way to filter specific tags from showing in GO (example the ops tags, there is a couple specific ones that they are not interested in showing here)
- [x] Deployments Overview by Emergencies: Can we change this tittle to: Active Deployments Overview by Emergencies?

**Emergency Surge Page**
- [x] Can we add a new Key figure "Deployed ERU"? This way all the key figures will match between global and emergency surge pages.
- [x] Can we make sure the style of the Key figures is the same for both  global and emergency surge pages?
- [x] Open Surge alerts: The field application deadline can be ignored, the surge team has decided not to input any data there.
- [x] Open Surge alerts: Can we move the column Start Date before Duration?
- [ ] Open Surge alerts: Can we change the "View all open alerts" to "View all open alerts for this operation" and make sure that the result are  all the alerts related to that specific operation.
- [ ] Rapid Response Personnel Deployed: Can we change this tittle to "Current Rapid Response Personnel Deployed"?
- [ ] Rapid Response Personnel Deployed: Can we change the "View all deployed personnel" to "View all deployed personnel for this operation" and make sure that the result are all the deployments related to that specific operation.
- [x] The pop up box on the gant chart showing the dates of each deployment is not working.
- [x] Pagination is still broken

@batpad Sorry for the long ticket!

**Comment by anamariaescobar** [comment]
One more thing I forgot to add:

- [ ]  Emergency surge page: Rapid Response Personnel section: Position, from Molnix it will be coming as: Position, Emergency, Country, so if we could separate them with the , and only take the first half that would be great!.

This ticket supersede the following tickets: #1638 #1659 #1666

**Comment by batpad** [comment]
@anamariaescobar the updated Surge Alerts table is available for testing at https://ifrc-go-feature-1965-surge-changes.surge.sh/deployments (it is pulling data from Staging).

I'll start working through the other issues in the list - let me know if there is anything in particular you would like me to prioritize.

**Comment by anamariaescobar** [comment]
Hey @batpad the changes look really good, I would say that for next steps Key figures are the top priority.
Also, remember about the tags we wanted not to bring? they are these 3:
- Nosuitable
- NotSurge
- OpsChange
It also seems we are still facing problems with matching IFRC in the deploying Organization.

I am doing tests with the Surge team on Wednesday :)

**Comment by anamariaescobar** [comment]
Following our call today, here a couple of things to fix:

- [ ] Bug with the duration of open alerts
- [ ] "Positiion" in both Open Alerts and Deployments, can we show only whatever is before the first comma?
- [ ] On "Deploying organization", can we remove the link to the organization if it is not a country on the countries table?

Thank you @batpad :)

**Comment by anamariaescobar** [comment]
Hey @batpad here the url for the production site for Molnix:  https://rrms.ifrc.org/ the im@ifrc.org shoud have all the permissions already!

**Comment by anamariaescobar** [comment]
@batpad as discussed, some issues we found after the deployment:

- Approximate the duration field on the Open Alerts
- For the older manual alerts, leave the duration blank
- Mark all older manual alerts as inactive
- Multi-country issue, see ticket #1988

**Comment by batpad** [comment]
> Approximate the duration field on the Open Alerts
> For the older manual alerts, leave the duration blank

This has been fixed in https://github.com/IFRCGo/go-frontend/pull/1987 and is on staging. Also have fixed the truncation of the "Position" field (not truncate for older Surge Alerts + add truncation for Position on Deployments table).

We should likely push out a hotfix to the frontend with these fixes.

> Mark all older manual alerts as inactive

So for all Surge Alerts in the database where `molnix_id` is NULL, we need to the `is_active` flag to False. I will work with @vdeak to do this tomorrow.

> Multi-country issue, see ticket Multi-country ops in Open Surge Alerts (Molnix) #1988

This is a bit more involved, and as discussed, will work on for the August-end release.

**Comment by anamariaescobar** [comment]
@batpad @tovari 

Just tested on staging and I am getting the same issues:

![image](https://user-images.githubusercontent.com/69478743/128393356-10003cff-5440-4512-a6d0-5456f4ff519a.png)

Maybe the fixes were pushed on the surge link?

**Comment by batpad** [comment]
> Just tested on staging and I am getting the same issues:

Sorry, seems like there was an issue with the deploy. The changes are on staging now.

**Comment by anamariaescobar** [comment]
@batpad It looks good, I created one alert with a duration of like 25 days or something like that and the duration I get is 0 months.......maybe we should take a look at this? For the rest it looks perfect!

**Comment by anamariaescobar** [comment]
Hey @batpad, the count seems to be working now!

Some general feedback:

- [ ] The yellow points of the map don't seem to have the outer circle as the rest of them.
- [ ] For the graph NUMBER OF DEPLOYMENTS BY NS, maybe we can limit it to 5 and not 6.
- [ ] It would be great if both graphics were the same size
- [ ] Can we move the Deployed ERU to the bottom just before the ERU readiness? I think it makes more sense to have those to next to each other (The order will be Open alerts, Personnel deployments, ERU deployments and then ERU readiness)
- [ ] Can we also move the ERU to the bottom on the Surge tab in an emergency?
- [ ] On the Surge tab of an emergency, can we get rid of the key figure "Deployments this year" but keep it on the global surge page?

Also, there are a couple of points that haven't been addressed:

- [ ]  When not logged in, the only field that shouldn't be visible is the Name of the person deployed.
- [ ]  The today line continues to be a bit of an issue, not working correctly.
- [ ]  We were wondering if for the open alerts could we only count the ones with a status of Open (not Stood down)
- [ ]  Can we organize the Open Surge alerts, showing the open ones on top and the stood down one on the bottom?
- [ ]  Can we only keep the stood downs in the Open Surge Alerts for 7 days?
- [ ] Open Surge alerts: Can we change the "View all open alerts" to "View all open alerts for this operation" and make sure that the result are all the alerts related to that specific operation. Same for Deployed personnel /This one is for the surge tab in an emergency page)

**Comment by karitotp** [comment]
Here some feedback more, @batpad 

- The style of the points on the map does not work well when we change the "Scale points" from ERU to Personel and viceverse.
![surge_map](https://user-images.githubusercontent.com/11504548/132078504-6ec189a4-7ec1-4a19-b74a-5d1817ad61d7.gif)

- When the popup over the map is displayed to the left or right side of the points, an additional white box appears below it.
![Selection_021](https://user-images.githubusercontent.com/11504548/132078540-65ca08f3-4040-4da0-a725-f1723ed66192.png)

- In the "Rapid response personnel" table of the Surge tab of an emergency https://dsgoproxyapp.azurewebsites.net/emergencies/3840#surge, the filters by RDRT/RIT, HEOP and FACT are giving a white page. It seems is because there is not any of those types.

![Selection_020](https://user-images.githubusercontent.com/11504548/132078614-2a531a60-632d-47df-95d6-29daadea689a.png)

**Comment by batpad** [comment]
@willemarcel - would you be able to look at the two map related issues flagged by @karitotp above, re: the popups and the scaling?

@szabozoltan69 could we look at the Type filter in the Rapid Response Personnel table on the Emergency page? The best option would be to remove that filter, since now we have only Rapid Response. So we just want to remove the dropdown triangle and the filter next to the Type column. We can look together.

**Comment by batpad** [comment]
@anamariaescobar can we identify which of the points above we need to fix for this release? All the points seem reasonable / doable, just wondering which we'd consider critical for this release. Some notes / responses below:

> The today line continues to be a bit of an issue, not working correctly.

Can we try and create a test case for this to show the issue on staging? 

> Open Surge alerts: Can we change the "View all open alerts" to "View all open alerts for this operation" and make sure that the result are all the alerts related to that specific operation. Same for Deployed personnel /This one is for the surge tab in an emergency page)

I'm afraid this needs a bit of design thinking - currently we don't really have a view for "view all alerts, including inactive, for an emergency" - we would need a good way to indicate on the All Surge Alerts page that this was showing alerts for a single emergency, figure out navigation etc. I wonder if it is better to have a way to just show this on the Emergency page itself (like "View All" which removes the filter for active and the current date range and shows all alerts / deployments for this emergency.

Sorry, I think I mis-read the complexity of this feature a bit and didn't fully think it through initially - it would be introducing a new way of navigating a bit here, and I think for this to make sense, we would need to implement it directly on the emergency page OR add filters to the All Alerts / Deployments pages, both of which is a little bit of work and thinking through.

**Comment by anamariaescobar** [comment]
Hi @batpad, I would say that addressing the general feedback and Karito's comments, the rest of the thing we can leave for later.
For the today line, it works perfect in staging, so I can't reproduce the issue there which is strange......

**Comment by batpad** [comment]
>  The yellow points of the map don't seem to have the outer circle as the rest of them.

So, I think this is because we are either scaling the Deployments points or the ERU points. @willemarcel will you be able to look at this and comment?

>  For the graph NUMBER OF DEPLOYMENTS BY NS, maybe we can limit it to 5 and not 6.

@szabozoltan69 could you look at this? We need to only show 5 National Societies in the Number of Deployments by NS chart on http://localhost:3000/deployments

> It would be great if both graphics were the same size

Hmm .. @willemarcel do you know if you might be able to look at this - ideally both the charts on the deployments page would have the same height - I'm a bit worried about the CSS here, would you be able to look and see if it seems feasible / easy?

> Can we move the Deployed ERU to the bottom just before the ERU readiness? I think it makes more sense to have those to next to each other (The order will be Open alerts, Personnel deployments, ERU deployments and then ERU readiness)

@szabozoltan69 does this make sense and would you be able to make this change?

> Can we also move the ERU to the bottom on the Surge tab in an emergency?

@szabozoltan69 same for this?

> On the Surge tab of an emergency, can we get rid of the key figure "Deployments this year" but keep it on the global surge page?

@szabozoltan69 and this? :)


These seem like they should all ideally be relatively straightforward fixes. @szabozoltan69 let me know if these are alright for you, happy to discuss details.

**Comment by szabozoltan69** [comment]
I am on these above... ^

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/132205628-7ea0e09b-c314-44a6-a4b8-6e0057adeb46.png)
![kép](https://user-images.githubusercontent.com/6050643/132205731-82556a47-8d9f-439e-ad6d-b930ad9e8363.png)

**Comment by tovari** [comment]
> Here some feedback more, @batpad
> 
> * The style of the points on the map does not work well when we change the "Scale points" from ERU to Personel and viceverse.
>   ![surge_map](https://user-images.githubusercontent.com/11504548/132078504-6ec189a4-7ec1-4a19-b74a-5d1817ad61d7.gif)

Regadring the symbol size: it looks like the when loading the Surge tab, all ERU locations have the same size (the max symbol size) regadless of the number of ERUs in the location. While changeing the scale to RR and back to ERU, then the symbol size is getting related to the number of ERUs (max number of ERUs displayed with the max symbol size)

**Comment by anamariaescobar** [comment]
HI @batpad, @tovari and @szabozoltan69,

I found 2 issues with the deployment:

- The map doesn't seem to be showing ERU
- The graphic "Number of deployments by NS" seems to be connected to the ERU and it should be connected to the personnel deployments, in staging seems to be the same way, so this one is completely my fault, I didn't noticed :( sorry!

**Comment by anamariaescobar** [comment]
Wording changes:

- In the Map, change "Mixed" for "ERUs & Rapid Response deployed"
- In the graph, change "Deployments over the last year" for "Ongoing deployment over the last year"

Thanks @batpad !!
