### ISSUE TITLE
Incorrect geospatial data

### ISSUE THREAD

**Issue by ryales** [IFRCGo/go-frontend#1967]
Fiji has the incorrect centroid points for its Eastern province and Northern Province. They appear thousands of miles away from where they should. See https://go.ifrc.org/countries/66/#3w

Tanzania has outdated shapefiles for its regions in the 3w. They are unable to be matched to the latest operation document. See the list in the docs here: https://go.ifrc.org/emergencies/5256#reports. Only 6 of 8 can be matched to in Go. Both OCHA COD (https://data.humdata.org/dataset/tanzania-administrative-boundaries-level-1-to-3-regions-districts-and-wards-with-2012-population) and Wikipedia confirm the Go dataset is incomplete/outdated.

Same for South Sudan. Admin boundaries changed in 2020. Cannot match IFRC appeal docs to the 3w admin areas.

**Comment by jhenshall** [comment]
Thank you for ticketing @ryales - really helpful! The Fiji ones are weird and will hopefully fixed with upcoming Mapbox changes. If not, we can manually change in admin. The others will need to get update from ICRC and then update.

**Comment by jhenshall** [comment]
The Fiji issue has been fixed as part of the Mapbox work. The other admin 1 issues should be considered as part of the pending admin boundary work.
