### ISSUE TITLE
3W - July improvements

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1970]
After the implementation of the 3W updates, the following improvement needs are identified:

- [x] 3W form - please remove the RCCE tag - RCCE can be replaced with a dual tag of CEA+Health (public)
- [x] Language unclear if referring to number of countries or projects.  Suggest to amend "Activities in Countries" to "Countries where NS has reported projects" 
![image](https://user-images.githubusercontent.com/68283148/125686718-1b397e2e-2b0f-4ed2-83a4-d7314f32bdff.png)
- [x] Change "value: #" to "Projects: #" 
![image](https://user-images.githubusercontent.com/68283148/125686847-1e30cbed-d96f-4310-b85f-a1be451ab90f.png)

- [x] When hovering longer tags (Livelihoods and basic needs), it goes of the screen and scroll bar appears. 
![image](https://user-images.githubusercontent.com/68283148/125686929-40dabe48-af7c-4678-9ec6-87165a1a902f.png)

- [x] No values appear when hovering under Programme Type Pie chart. We can see values when hovering under Projects per Sector and Top Tags bar chards. 
![image](https://user-images.githubusercontent.com/68283148/125687180-0eb3c91e-66e4-491e-9a4e-4f4e5d87d6b1.png)

- [x] 3W project view should show the user name, who last modified the project

- [x] Charts on the Arabic global 3W page looks weird. Labels are missing 
![image](https://user-images.githubusercontent.com/68283148/125754459-1c245443-f0ca-4345-8e11-0ba33ddc122b.png)

**Comment by frozenhelium** [comment]
@tovari, for the following action point, we also need to remove the `RCCE` tag from all the existing 3W entries and replace it with a combination of `CEA` and `Health (public)`. So it'll involve some migration in the backend and will also impact 3W projects in existing database. Do you confirm that this is the desired behaviour?
>3W form - please remove the RCCE tag - RCCE can be replaced with a dual tag of CEA+Health (public)

**Comment by tovari** [comment]
@frozenhelium, I confirm that it can be updated on the existing projects as well.
