### ISSUE TITLE
[PROD] Consolidate drop downs that use country dataset

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1997]
There are a few bugs for drop downs that use the country dataset for selecting country or National Society. This ticket outlines the logic for _all_ relevant drop downs across the site. There are only 3 known issues but this could be an opportunity to consolidate and perhaps introduce global behaviour?

The issues that definitely need fixing according to the logic below:

- #1869
- #1934
- #1936

Logic for all drop downs across the site (copy of table from the Teams wiki):

Page | Dropdown name | DB field name | Record type = | Independent = | Disputed = | Notes
-- | -- | -- | -- | -- | -- | --
User registration | Country | name | 1 (country) | TRUE & FALSE (NOT NULL) | FALSE | All countries but excludes ICRC, IFRC & Benelux
User registration | Organization Name (when Org Type = NS) | society_name | 1 (country) | TRUE | - |  
New field report | Country | name | 1 (country) | TRUE | - |  
New 3W | Reporting National Society | society_name | 1 (country) | TRUE & NULL (NOT FALSE) | - | Includes unique NS + ICRC, IFRC & Benelux
New 3W | Country | name | 1 (country) | TRUE | - |  
New PER form | National Society | society_name | 1 (country) | TRUE | - |  
Completed PER forms | Select country (filter) | name | 1 (country) | TRUE | - |  

cc @batpad @tovari

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/2002 fixes the [PROD] Repetitive entries in NS dropdown on signup page #1936 bug.
