### ISSUE TITLE
[PROD] grey screen for emergency operation surge tabs

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1998]
## Issue
Whenever going to the "surge" tab of an emergency operation, I get a grey screen if not logged in.  Works OK if logged in.

## Steps to reproduce
* log out of GO (or open an incognito window)
* go to an emergency where surge personnel are deployed
* click on "surge" tab
* get grey screen
e.g. https://go.ifrc.org/emergencies/3972#surge and https://go.ifrc.org/emergencies/5499#surge and https://go.ifrc.org/emergencies/5123#surge

## Expected behaviour
Page should load without a grey screen - I think it's supposed to have a "please log in" message similar to if you click on the surge tab in the main navigation (which sends you to https://go.ifrc.org/login)

## Under the hood
`https://prddsgocdnapi.azureedge.net/api/v2/personnel/?event_deployed_to=3972&limit=5&offset=0&end_date__gt=2021-08-16T03%3A54%3A06.069Z` is returning `{"detail":"Authentication credentials were not provided."}` - which is fine, given the user isn't logged in - but it seems the page then doesn't render.

Console shows
`network.js:256 GET https://prddsgocdnapi.azureedge.net/api/v2/personnel/?event_deployed_to=3972&limit=5&offset=0&end_date__gt=2021-08-16T03%3A54%3A06.069Z 401
network.js:16 No login token found
TypeError: Cannot read property 'filter' of undefined
    at Ta (utils.js:487)
    at alerts-table.js:216
    at Array.reduce (<anonymous>)
    at a.value (alerts-table.js:199)
    at ua (react-dom.production.min.js:173)`

## Impact
Most users (as lots of people use GO without logging in)

## Severity
Reputational impact

## Is there a workaround?
Log in (if you have a log in)

**Comment by batpad** [comment]
Thank you for the report @nanometrenat . This should now be fixed in production.

Thank you @thenav56 @frozenhelium @AdityaKhatri for the fix.

**Comment by nanometrenat** [comment]
Thanks - confirming no longer a grey screen in Prod, so closing issue.  Sounds like discussion continues on https://github.com/IFRCGo/go-frontend/issues/2003 re requirements for wording etc.

Cheers all!
