### ISSUE TITLE
[PROD] GO User Library URL is incorrect

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-frontend#1999]
## Issue
Link to GO User Library on the [Resources](https://go.ifrc.org/about) page points to https://go-user-library.ifrc.org/ although the correct URL is https://ifrcgo.org/go-user-library/

**Comment by batpad** [comment]
Ideally, https://go-user-library.ifrc.org/ would be the correct link, but is having some issues being setup, currently dependent on https://github.com/IFRCGo/go-user-library/issues/31

@anamariaescobar @esario - we could make a hotfix to change the link back to https://ifrcgo.org/go-user-library/ while https://go-user-library.ifrc.org/ still does not work. If a hotfix would be good, @szabozoltan69 would you be able to take this on? i.e. Change the link on the Resources page from https://go-user-library.ifrc.org/ to https://ifrcgo.org/go-user-library/ (to make it a hotfix you should create a branch from `master` and not `develop`, and then make a Pull Request straight to `master`).

**Comment by szabozoltan69** [comment]
The change is on branch https://github.com/IFRCGo/go-frontend/tree/hotfix/1999-temporary-fix-user-library-link – will be deployed soon.

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-frontend/pull/2006

**Comment by szabozoltan69** [comment]
It is on production ( = master). Should I merge it also to develop?
