### ISSUE TITLE
[PROD] Surge Alerts table should show Not Logged in message

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2003]
## Issue

With the new Surge Alerts table on the Emergency page, when the user is not logged in, it does not show all the details of the alert (which is correct behaviour), but also does not inform the user that they are not seeing more data because they are not logged in. The user just sees many fields missing in the table, and no indication that they will be able to see more if they are logged in. eg https://dsgoproxyapp.azurewebsites.net/emergencies/3840#surge

## Steps to reproduce

Visit https://dsgoproxyapp.azurewebsites.net/emergencies/3840#surge when not logged in. You see many fields like Duration, Position, etc. that are empty, and no indication that they are empty because you are not logged in.

## Expected behaviour

Previously, the Surge Alerts table had much fewer fields, and we could just replace the text for the `Position` / `Message` field with a message for non-logged in users that they need to log in. With the new, additional fields, this might be a bit more work to think about - we may need to render a completely different table for non-logged in users with less fields, and that's likely a bit of work.

I think we have 3 options here:

1. Hide the entire Surge tab for non-logged in users, and just display a message that the user needs to be logged in to see the contents of the tab. This should be reasonably easy to implement, and if i remember correctly, @anamariaescobar was the initial plan? I think the implementation of this got a bit missed.

2. Do as we were doing previously, and replace the text that should come in the `Position` column to say something like `Log in to see details`. This is also easy to do, will just look awkward since the other columns for Duration, Tags, etc. would still exist but contain no data. We could push this to a testing site to see how it would look.

3. Implement showing a table with less columns, and one column just giving the message that the user needs to log-in, that we show to non-logged in users. If we do want to show the Surge Alerts table to non-logged in users, this definitely seems like the best option. This will be a bit more work, though, and may not be implementable as a quicker hotfix.

My recommendation here would be to do either 1> or 2> as a hotfix, and see if we are able to discuss and if needed, do 3> ideally for the next release.

@szabozoltan69 would be great to get your help to implement whatever is decided here - happy to have a chat to clarify details.

cc @anamariaescobar 

## Related feature

Part of https://github.com/IFRCGo/go-frontend/issues/1965

**Comment by szabozoltan69** [comment]
I work on it...

**Comment by nanometrenat** [comment]
@anamariaescobar in terms of business requirements for this, as at last time I heard (and things may have changed since) it was intended that all Surge information except _name_ of deployed personnel would be available to non-logged-in-users - has that changed?

**Comment by anamariaescobar** [comment]
@nanometrenat hi!! yes, we were not sure on the behavior agreed, since the integration when not logged in it was showing a blank page (I really didnt thought about this ), and all the emergencies that went down this week, we pushed this hotfix (an easy one to implement)  an following the previous behavior, but indeed we need to make it better, would you be available for a quick chat on this? :)
