### ISSUE TITLE
Surge: Key figures on top of page

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2011]

**Comment by batpad** [comment]
Key Figures at the top of the Surge page should be:

 - Deployed Rapid Response Personnel
 - Deployed ERUs
 - NS Providing Rapid Response Personnel

The data for each of these can be found at https://dsgocdnapi.azureedge.net/api/v2/deployment/aggregated

cc @szabozoltan69 

And we also need to show the same key figures on the Emergency page (currently there are no key figures in the surge tab on the emergency page) - this will show the same data, but filtered for that emergency. The query will be like https://dsgocdnapi.azureedge.net/api/v2/deployment/aggregated?event=<event_id>

**Comment by batpad** [comment]
Related: seem to be getting a 500 for a request like https://dsgocdnapi.azureedge.net/api/v2/deployment/aggregated?event=4136 - @szabozoltan69

**Comment by szabozoltan69** [comment]
The cause of this mentioned Error 500:

.../api/v2/deployment/aggregated?event=4130

FieldError at /api/v2/deployment/aggregated
Cannot resolve keyword 'personneldeployment' into field. Choices are: country_from, country_from_id, deployedperson_ptr, deployedperson_ptr_id, deployment, deployment_id, end_date, id, is_active, molnix_id, molnix_tags, name, role, role_ar, role_en, role_es, role_fr, start_date, type
Details are here: https://pastebin.com/TYHm5AvS

**Comment by szabozoltan69** [comment]
Event-filtering is OK. Two testing examples: https://dsgocdnapi.azureedge.net/api/v2/deployment/aggregated?event=4119 (0,1,0)
https://dsgocdnapi.azureedge.net/api/v2/deployment/aggregated?event=3786 (6,0,6)

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/2019 solves this. :-)

**Comment by tovari** [comment]
Hey @batpad, @szabozoltan69. The ERU number in the key figures is currently calculated differently than the Deployed ERUs considered in the table. It should be the count of Equipment Units where the ERU is deployed to a country. As I see, this is the way ERU deployment is considered at the National Societies part of the page, and this should be the calculation method at the Deployed ERUs table title. 

In the example here, it should be 19:
![image](https://user-images.githubusercontent.com/68283148/131863639-36c1107a-f6ae-4105-9fcc-57bb084d721b.png)

You also see here 19 deployed ERUs:
![image](https://user-images.githubusercontent.com/68283148/131863793-32edb42d-f443-4968-8f67-42530717d2c9.png)

**Comment by batpad** [comment]
@tovari - yes, we are currently using just the count of ERU objects in the database for the ERU counts in the aggregations, and not summing the `units` deployed of the ERUs. This was my over-sight, not being familiar with the logic and structure of ERUs, so:

 - For the Deployed ERU aggregation that we perform here: https://github.com/IFRCGo/go-api/blob/develop/deployments/drf_views.py#L172 - instead of just returning the `count` of rows, we should rather return a `Sum` of all the `units` in the active ERU rows. cc @szabozoltan69 

There was another bug with the aggregate Deployment counts on Emergency pages - sorry @szabozoltan69 again my over-sight, there is a fix for that here: https://github.com/IFRCGo/go-api/pull/1171

Thanks for the catches @tovari.
