### ISSUE TITLE
Deployment table in Global surge page not adding up[Staging] 

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2023]
## Issue
The table "Deployments overview by emergencies" in the global Surge page is not adding up correctly the active deployments. At this moment there should only be 2 Emergencies with deployed personnel (Aland Bio Test3 and Guinea-Ebola Virus Disease) and even for those operations the count is not correct.
The map is showing the correct data.

## URL
[](https://dsgoproxyapp.azurewebsites.net/deployments)

## Steps to reproduce
Go to the global surge tab and scroll down to "Deployment overview by Emergencies"

![image](https://user-images.githubusercontent.com/69478743/131523369-f342ce15-f5ed-41ba-ad74-fc68c68c134b.png)

## Expected behaviour
The table should show the sum of the active deployments for each operation

@batpad @tovari

**Comment by tovari** [comment]
@anamariaescobar, I think the number of Deployed ERUS is also incorrect. Currently 15 is displayed, but if we sum up the ERUs in the Number of Deployments by NS chart or at the bottom at National Societies deployments, it should be 16. There is 1 case where 2 units are deployed, which causes the discrepancy probably.

**Comment by anamariaescobar** [comment]
@tovari, you are right, I just changed the one with 2 units deployed, and now the numbers match. As of now we only put 1 unit when an ERU is deployed, so I dont see this as much of an issue, we can tackle this when we work on the ERU module.

**Comment by batpad** [comment]
Thanks @anamariaescobar .

Yea, the count of deployments by emergency is a complex query and it would be really nice to have more robust tests for it.

@szabozoltan69 can we look at this closer when you're up? I'll need some help querying what's actually in the database and figuring out the reason for this mismatch.

The view / query for this is: https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L117 - I notice we are missing a check for `start_date__lt=timezone.now()` or so - I can add that but I don't think that is the reason for this mismatch. @szabozoltan69, this would be really nice to debug together to try and figure out why this count mismatch is happening.

Re: ERUs: Yes, with ERUs, sorry, I realize I am not familiar at all with how the logic is supposed to operate. Looking at the code, @anamariaescobar @tovari - you are right, it is currently not summing up the `units` - it is just a count of ERU entries in the database. If this should rather be a sum of the `units`, let me know and we can make that change.
