### ISSUE TITLE
Home page annual chart doesn't display tick for 2017

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#204]
![screen shot 2018-02-27 at 2 08 49 pm](https://user-images.githubusercontent.com/1590802/36749093-c05775a0-1bc7-11e8-8f93-3adba433aa58.png)

This is consistent behavior, and I couldn't figure out why. @danielfdsilva could you take a look at this?

**Comment by guipizzini** [comment]
Closing this one as a new ticket has been created for the same issue.
