### ISSUE TITLE
Surge email notifications improvements

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2041]
Currently, the Surge email notification is not well designed, need to improve.
Current notification screenshot:
![image](https://user-images.githubusercontent.com/68283148/132237662-817a1ae4-ac74-4f38-b0ad-8214f1392572.png)

Requested updates:
- set the Read more and teh Open in GO urls to the Surge tab
- Title: 1 new surge alert: Position title, Country
  e.g.: 1 new surge alert: CVA Coordinator, Haiti
- Notification body: remove (RAPID_RESPONSE, alert), add Duration and Start date
  e.g.: CVA Coordinator, Earthquake, Haiti, 2 months starting on 01.10.2021.

cc: @anamariaescobar

**Comment by szabozoltan69** [comment]
I try to figure out if sync_molnix or index_and_notify sends these emails, because both of them are related to surge alerts. An email example to my mailbox would be fine.

**Comment by szabozoltan69** [comment]
I would like to ask to leave the "X new surge alert" as it is, because there can be more than 1, and in that case it would be not feasible to show (all) the titles above with a colon. My suggestion is to leave "X new surge alert" as it is, and change the texts below.

**Comment by tovari** [comment]
@szabozoltan69, for 1 new surge alert, the details could be listed as above, for more than 1 new surge alerts, we don't need the details in the title. This is  how other notifications work as well (event, field report). Thanks!

**Comment by tovari** [comment]
Looks like, the coming info is inconsistent and therefore the notification info might be incomplete:
![image](https://user-images.githubusercontent.com/68283148/144623450-e75ed9ad-5f30-41ff-afc0-00b62c155215.png)

**Comment by szabozoltan69** [comment]
Yes, we should have an alternative source for Operation, because that field can be empty:
![kép](https://user-images.githubusercontent.com/6050643/144624011-6c38f0c3-0034-42b6-956e-4e692090dd62.png)

**Comment by szabozoltan69** [comment]
Changes done on staging and prod also.
