### ISSUE TITLE
[PROD] ifrc.org upgrade means Country weblinks no longer work and some other links on GO are broken too

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#2042]
## Issue
Weblinks to IFRC.org country pages were added via #776, and further enhanced via #922.  Every country page has a footer that shows links to that country's page on ifrc.org.

Or at least, it did until the ifrc.org website recently got upgraded - meaning that the old links no longer work.

e.g. DPRK page on GO https://go.ifrc.org/countries/193 - the `Democratic People's Republic of Korea on IFRC.org` button links to `https://www.ifrc.org/en/what-we-do/where-we-work/asia-pacific/red-cross-society-of-the-democratic-peoples-republic-of-korea/` which just gives `Page not Found`
![image](https://user-images.githubusercontent.com/33625192/132275804-cd941e83-31f0-4c50-aa76-659991a2c54b.png)

Similar for other countries e.g. https://go.ifrc.org/countries/165 for Switzerland sends you to broken https://www.ifrc.org/en/what-we-do/where-we-work/europe/swiss-red-cross/

## Steps to reproduce
Go to any country page and click on the relevant button in bottom left

## Expected behaviour
Links should work

## Related feature
#776

## Impact
All users/all countries

## Severity
It's annoying, and makes the button pointless - but the workaround is to search on the IFRC website.

## What's required
IM will need to manually update the website links in the back end for each country.  OR figure out what the new ifrc.org URL structure is and make the links follow that logic.

**Comment by nanometrenat** [comment]
I've also seen that there are other places on GO where links to the ifrc.org website don't work now - e.g. the 'for more information on the PER Approach select **here**.' link on https://go.ifrc.org/preparedness#global-summary, which directs to `https://media.ifrc.org/ifrc/what-we-do-disaster-and-crisis-national-society-preparedness-effective-response/` (now broken).

Also at least one link on the About page.  Not sure about others - someone will need to go through and check all the ifrc.org weblinks and make sure they work (some will be able to be amended in the back end by a business user, others will presumably need a code change).

All the best

**Comment by szabozoltan69** [comment]
The NS pages ( = country's page on ifrc.org) has this structure on ifrc.org:
https://www.ifrc.org/national-societies-directory/swiss-red-cross
https://www.ifrc.org/national-societies-directory/german-red-cross
and so on. I begin to fix them.

**Comment by tovari** [comment]
The Reference centres link on the Resource page should point to
https://www.ifrc.org/reference-centres

![image](https://user-images.githubusercontent.com/68283148/132326550-ed24f67c-3b7d-4237-b1cc-852357e60de5.png)

**Comment by szabozoltan69** [comment]
The country links has to be fixed via database update:
![kép](https://user-images.githubusercontent.com/6050643/132334256-29fd0c72-a08e-4b5d-aabb-500d609fa48c.png)

**Comment by szabozoltan69** [comment]
```
select regexp_replace(url_ifrc,'.*(\/.*\/)', 'https://www.ifrc.org/national-societies-directory\1') from api_country where url_ifrc<>'';


 https://www.ifrc.org/national-societies-directory/liberian-red-cross-society/
 https://www.ifrc.org/national-societies-directory/andorra-red-cross/
 https://www.ifrc.org/national-societies-directory/mali-red-cross/
 https://www.ifrc.org/national-societies-directory/mauritanian-red-crescent/
 https://www.ifrc.org/national-societies-directory/lithuanian-red-cross-society/
 ```

**Comment by szabozoltan69** [comment]
Db fix is done (staging and prod).

**Comment by nanometrenat** [comment]
Thanks for the prompt response @szabozoltan69 and @tovari 
Unfortunately it seems the IFRC website is giving an intermittent "The website encountered an unexpected error. Please try again later." when accessing those National Society pages.  Not sure if the problem is just with the redirect (as when they work they redirect to a URL with an ID rather than a society name) or if it's something else.  Either way it'd be great if you could please liaise with whomever on the ifrc.org side to doublecheck - thanks again!

**Comment by batpad** [comment]
Yes, it seems like it was not just a URL prefix change for all the national societies.

I see for example on GO we now link to https://www.ifrc.org/national-societies-directory/afghan-red-crescent-society/ but the correct URL would be https://www.ifrc.org/national-societies-directory/afghan-red-crescent

This seems like we should do a bit of a process of exporting out the `url_ifrc` links from the database into a spreadsheet or so, maybe write a script to automate checking which links work, and which don't, and maybe then highlight which ones need to be fixed? @szabozoltan69 would you be able to start doing this?

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/132352359-89135b97-3c2b-4495-9914-f79fc0c62065.png)

**Comment by tovari** [comment]
Looks like it is not consistent, as society might be included in the url:
https://www.ifrc.org/national-societies-directory/indonesian-red-cross-society

**Comment by szabozoltan69** [comment]
Oh, great, there is a dropdown list, so it will be faster to identify the changes:
![kép](https://user-images.githubusercontent.com/6050643/132353848-a838d915-326f-4ecc-8b61-13af6dce3ce8.png)

**Comment by szabozoltan69** [comment]
Do we know a Country entity for which we could use this?
https://www.ifrc.org/national-societies-directory/belgian-red-cross-flanders/
(Not Belgium, because for them we have https://www.ifrc.org/national-societies-directory/belgian-red-cross )

**Comment by szabozoltan69** [comment]
Andorran Red Cross:
An illegal choice has been detected. Please contact the site administrator. 
:-D

**Comment by szabozoltan69** [comment]
I think I return later. I have a list of "recent" (https://pastebin.com/Bk8e3QUk) and "to-be" (https://pastebin.com/pPU4AXJD), but before update let's wait a bit.

**Comment by nanometrenat** [comment]
> Do we know a Country entity for which we could use this?
> https://www.ifrc.org/national-societies-directory/belgian-red-cross-flanders/
> (Not Belgium, because for them we have https://www.ifrc.org/national-societies-directory/belgian-red-cross )

@jhenshall FYI for interest

**Comment by jhenshall** [comment]
Interesting, thanks @nanometrenat and @szabozoltan69 . This is horrible to accommodate in the current data model. Would need to create a 'false country' just to have it. Thinking this is more of a 'branch' than a separate National Society so proposing to ignore for now but noting for upcoming branch project.

**Comment by tovari** [comment]
> I've also seen that there are other places on GO where links to the ifrc.org website don't work now - e.g. the 'for more information on the PER Approach select **here**.' link on https://go.ifrc.org/preparedness#global-summary, which directs to `https://media.ifrc.org/ifrc/what-we-do-disaster-and-crisis-national-society-preparedness-effective-response/` (now broken).
> 
The new PER url:
https://www.ifrc.org/disaster-preparedness

**Comment by szabozoltan69** [comment]
I updated the NS links (both on staging and prod), so all of the country links works. E.g.:
https://go.ifrc.org/countries/afghanistan
-> https://www.ifrc.org/national-societies-directory/afghan-red-crescent
(At some NS-es there were no "nice url", just numeric, like https://www.ifrc.org/national-societies-directory/370/65 )

The "flanders" question is still open, and also that we have Eritrea on GO side but not on ifrc.org side.

**Comment by jhenshall** [comment]
Eritrea RC is not an official IFRC National Society but has an observer status so does have a presence on GO. It seems there was a page on the old ifrc.org but not now - can we remove the link on the Eritrea country page?

For Flanders, this can be left as is without an entity on GO (for now). So we only link to Belgian RC from the Belgium page.

**Comment by szabozoltan69** [comment]
Thanks Johnny. OK, I remove the link on the Eritrea country page to ifrc.org. (They have another link to reliefweb anyway, https://reliefweb.int/country/eri )
Then I think this issue is fixed and can be closed when all these will be deployed to production.

**Comment by nanometrenat** [comment]
> Please check it again – it could be a temporary blackout, now it works.

Hmm weird - you're right it works now... So we think it was a problem with ifrc.org rather than GO?  Wonder if I should let them know.

Anyway, cheers!

**Comment by szabozoltan69** [comment]
(For today all of the NS Country links works fine, even these: https://github.com/IFRCGo/go-frontend/issues/2042#issuecomment-948707537 )
