### ISSUE TITLE
Update Mapbox fields - admin 1 codes

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#2048]
Admin 1 codes need adding to the districts layers on Mapbox - both for polygons and centroids.

This could also be a good opportunity to consolidate all the fields and have them matching across tilesets and to GO database?

[Spreadsheet here](https://docs.google.com/spreadsheets/d/1wn7L-NMvQCuK5TR-J0Ftqv84jGGteu3B0GSwnBtAzUk/edit?usp=sharing) with all the fields from GO and Mapbox tilesets:

- Definite changes highlighted in red - either need adding or name changing to match others
- Some other changes in orange that could be added?

@geohacker might be easier to grab some time to quickly run through these and whether neccessary?

cc @szabozoltan69 @batpad

**Comment by geohacker** [comment]
@jhenshall I can add district codes and county info in the districts tilesets.

**Comment by jhenshall** [comment]
Done with the Mapbox stuff ages ago, just slipped through net.
