### ISSUE TITLE
[PROD] Consolidated Surge-Molnix page final changes

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2057]
Closing previous ticket #1965 and moving the remaining task in here.

**Global Surge page**

- [x]  Charts below the map: Top 5 NS deploying Rapid Response Personnel, the tittle should include the year and the chart must be cumulative for the present year (right now is showing ERU information)
- [x]  Charts below the map: Deployment over the last year change to: Ongoing deployments over the last year
- [x] Open Surge positions: Change to: Open Surge Alerts
- [x] Sort the alerts by putting the Open ones first and the stand downs at the end
- [ ] Count only the open positions and not include the stand downs (although the stand downs should still visible)
- [ ] Show stand downs only for 14 days
- [x]  Deployments Overview by Emergencies: Change to: Ongoing Rapid Response Deployments by Emergencies
- [x] In the Map legend, change "Mixed" for "ERUs & Rapid Response deployed"

**Emergency Surge Page**

- [ ]  Open Surge alerts: Can we change the "View all open alerts" to "View all alerts for this operation" and make sure that the result are all the alerts related to that specific operation (no matter if open or stood down) - implement filter by emergency on the view all alerts page and apply the filter - low priority
- [x]  Rapid Response Personnel Deployed: Change to "Ongoing Rapid Response Deployments"
- [ ]  Rapid Response Personnel Deployed: Can we change the "View all deployed personnel" to "View all deployed personnel for this operation" and make sure that the result are all the deployments related to that specific operation.
- [x]  The today line seems to still be off, which is weird because in staging works perfectly.
- [x] When not logged in, the only field that shouldn't be visible is the Name of the person deployed, all table for alerts should be visible.
- [x] Sort the alerts by putting the Open ones first and the stand downs at the end
- [x] Count only the open positions and not include the stand downs (although the stand downs should still visible)
- [x] Show stand downs only for 14 days
- [x] The count of personnel deployed seems to be off, for example for Haiti, in the key figures we have 19 
![image](https://user-images.githubusercontent.com/69478743/132484498-89bb31dd-4db0-4f53-8a9b-f065cfdc1a71.png)
but in the personnel deployments, we have 21
![image](https://user-images.githubusercontent.com/69478743/132484683-7b5e869b-ba38-4e3b-862d-e7f151fce452.png)
this is due to having 2 deployments that will start on the 14 and 15 of this month, so they are being counted on one part and not on the key figures, just talked to the surge team and they agree we should keep showing the persons deployed even if they haven't arrived in country yet but they do want to change the count from 21 to 19 (so including the dates), happy to have a quick chat to clarify if necessary (this is not happening any more because of dates of the deployments, but it is an issue)
- Remove number in brackets in the title of Rapid Response Personnel table

Happy to discuss any of the points if needed :)

@batpad @szabozoltan69 @tovari

**Comment by szabozoltan69** [comment]
Do I remember well that the /deployments page ("Surge" menu point) should be shown to everybody, even to not logged in visitors?
![kép](https://user-images.githubusercontent.com/6050643/134915823-66a1cae1-cd85-4c46-83f2-1a5d25c91a43.png)

**Comment by szabozoltan69** [comment]
"When not logged in, the only field that shouldn't be visible is the Name of the person deployed, all table for alerts should be visible."
Done, anonymous:
![kép](https://user-images.githubusercontent.com/6050643/134961886-36b859f8-28c4-48aa-9d11-b401f7f966b1.png)
Logged in:
![kép](https://user-images.githubusercontent.com/6050643/134961980-5f91dbab-a9ad-4431-8ee2-86b4281602f1.png)
There was an UnauthenticatedSurgeAlertSerializer in API which has the intent of "not showing so much" to unauthenticated user, now we do not use it, because (if I understand well) there is no difference in "Open Surge Alerts" table for any kind of user.

**Comment by batpad** [comment]
> There was an UnauthenticatedSurgeAlertSerializer in API which has the intent of "not showing so much" to unauthenticated user, now we do not use it, because (if I understand well) there is no difference in "Open Surge Alerts" table for any kind of user.

This looks really good to me @szabozoltan69 !

@anamariaescobar @tovari - would you be able to test on staging - if the behaviour for the deployments page as well as displaying surge alerts and rr personnel is correct / what is desired, when logged in and logged out.

Essentially, now all the pages and all the tables should be viewable by both logged in and non logged in users - the only thing that is hidden to non-logged in users is the Name field for Rapid Response Personnel.

**Comment by szabozoltan69** [comment]
Plan:
   - Add another column for is_stood_down
   - When ingesting Molnix data, if status=unfilled, set is_stood_down to True
   - Here, order by the is_stood_down field instead of the status string.

**Comment by batpad** [comment]
@szabozoltan69 we could probably add the check for `status=='unfilled'` and populate the `is_stood_down` column correctly around here: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L275

**Comment by szabozoltan69** [comment]
The ordering_fields will not be ok, the ordering would be needed instead ( https://www.django-rest-framework.org/api-guide/filtering/ ). But I think it is time to the more complex solution that is mentioned above, thank you @batpad .

**Comment by szabozoltan69** [comment]
The seems to be too long and the title row is breaking,
![kép](https://user-images.githubusercontent.com/6050643/136513359-5ac667db-dd2b-4d9f-a4e8-e84a02774a99.png)
 so maybe it would be better:
 **Top 5 NS Deploying RR Personnel (2021)**

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/2079 solves the above Diagram issue.

**Comment by anamariaescobar** [comment]
Hi @batpad and @szabozoltan69, just went through the whole ticket to consolidate the pending tasks:

**Global Surge page**
- [ ]  Charts below the map: Top 5 NS deploying Rapid Response Personnel, is there any way to make the space where the names of the NS are shown a little bit bigger so for Netherlands RC it doesn't go to a second line? - low priority
![image](https://user-images.githubusercontent.com/69478743/141960269-3986dfcd-aed5-4e1b-b735-4d66f5ef606a.png)
- [ ] Open Surge positions: Change to: Open Surge Alerts
- [ ] The Key number count of personnel deployed is not matching with the table of deployed personnel:
![image](https://user-images.githubusercontent.com/69478743/141961967-eb0373db-8a89-4fce-8dc2-d28f2a91f2f9.png)
![image](https://user-images.githubusercontent.com/69478743/141962030-ee1b6816-a943-45b3-ad56-3e75ef604ed1.png)
I think the issue is with Haiti, in the Surge tab of that operation there is 7 personnel deployed, while the table in the global Surge page is showing 18 and Central Mediterranean Sea: Population movement (HSP@Sea) that is countrin 1 person who is not yet deployed.
- [ ] Can we get rid of the number next to Open surge positions? - alternatively, can we only count open alerts and not stand downs?

**Emergency Surge Page**
- [ ] Open Surge alerts: Can we change the "View all open alerts" to "View all alerts for this operation" and make sure that the result are all the alerts related to that specific operation (no matter if open or stood down) - implement filter by emergency on the view all alerts page and apply the filter
- [ ] Can we get rid of the number next to Open surge alerts? - alternatively, can we only count open alerts and not stand downs?
- [ ] Rapid Response Personnel Deployed: Can we change the "View all deployed personnel" to "View all deployed personnel for this operation" and make sure that the result are all the deployments related to that specific operation.
- [ ] The today line seems to still be off, which is weird because in staging works perfectly.
- [ ] Sort the alerts by putting the Open ones first and the stand downs at the end

**Comment by szabozoltan69** [comment]
The ✓ signed rows implementation is deployed to staging.

**Comment by mariam-yu** [comment]
@batpad (@anamariaescobar FYI) empty table:
<img width="686" alt="Screen Shot 2021-12-06 at 3 46 33 PM" src="https://user-images.githubusercontent.com/60006476/145067151-69031f2c-46f9-4a9a-8612-c28eb9454c1a.png">

**Comment by anamariaescobar** [comment]
Aaand the mismatch is back!

We are having some operations popping up on the "ONGOING RAPID RESPONSE DEPLOYMENTS BY EMERGENCIES" in the Global Surge page that actually don't have any deployments (Benin : Floods/Inondations - 2021)

![image](https://user-images.githubusercontent.com/69478743/148946443-4ba04df1-2e51-4d59-a633-4cd2463019ea.png)
[https://go.ifrc.org/deployments#overview](url)

And in the Emergency page of this operation, the Surge tab is appearing even if there is nobody deployed or any open alerts:

![image](https://user-images.githubusercontent.com/69478743/148956935-d4e889bc-bc2e-4bd0-8652-8a0dba15eee9.png)
[https://go.ifrc.org/emergencies/5670#surge](url)

@batpad @tovari @szabozoltan69

**Comment by szabozoltan69** [comment]
Solved! :-) via https://github.com/IFRCGo/go-api/pull/1275
Please @anamariaescobar give it a check.
https://porgeto.hu/tmp/BeninBef.png < before | after > https://porgeto.hu/tmp/BeninAft.png

**Comment by szabozoltan69** [comment]
Web-rewrite made this solved.
