### ISSUE TITLE
Situation Reports - slider

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#207]
Can you add a slider to the "Situation Reports" box (Emergency>>)? For "Bangladesh - Population Movement" I uploaded 90 sitreps but only 20 are visible/available for download - as there is no option to filter them, the slider could do the job.

![sitrep](https://user-images.githubusercontent.com/25579864/37031680-fcfcaad4-213f-11e8-8c1b-f7169db2d122.jpg)

cc: @guipizzini

**Comment by dereklieu** [comment]
@k-som can you send a link to where this is happening?

**Comment by k-som** [comment]
@dereklieu https://dsgoproxyapp.azurewebsites.net/emergencies/2 only 20 sitreps visible/available and when you take a look at back-end there are 90 of them

**Comment by dereklieu** [comment]
This is https://go.ifrc.org/emergencies/2 at the deployed url.

**Comment by dereklieu** [comment]
This limit is now much higher, and the emergency in question is now showing all the reports.
