### ISSUE TITLE
Missing Fields in FR Report and Notification Email [PROD] 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#2098]
## Issue
Both the notification email and the report on GO are missing that is generated from a Field Report has some missing information that is inputted by a “National Society” when they create the Field Report. 
What is missing:  Taking the example of the input template found on:  https://dsgoproxyapp.azurewebsites.net/reports/9828/edit and the report generated based on that input: https://dsgoproxyapp.azurewebsites.net/reports/9828

1.	Regions Affected. The map on the Emergency page is great and it utilizes this information below but the report itself and the notification email  does not have the region/provice but they should have this information (not as a map since the emergency page already has this).
 
![image](https://user-images.githubusercontent.com/7780809/138277334-59f01e8a-2176-4770-9e57-cc0a4af0e695.png)

2.	Planned interventions data contained in the table below is missing from the report and notification email. Since this information is not surfaced on the Emergency Page that means it is lost to everyone who is not trying to edit the original report submitted. The Amount CHF can be written as “Initial CHF estimate”.  Data from the first two row is important (i.e DREF Requested and Emergency Appeal).  
 
![image](https://user-images.githubusercontent.com/7780809/138277381-773bbdbd-989b-4120-9e99-e38e2b63cfb7.png)

3.	Contacts are available on the Report generated but not in the notification email 
 
![image](https://user-images.githubusercontent.com/7780809/138277425-1ddd9a9e-0b0d-42d7-b134-826e28b27784.png)

This is the report generated after the submission of the Field Report. 
 
![image](https://user-images.githubusercontent.com/7780809/138277493-42ebe16b-e9ca-4c0f-80d0-11296b484e0a.png)

## Steps to reproduce
 In the staging environment create a Field Report with all data sections completed. 
Compare the report generated with the data entered. Specifically check for the planned response and the region field. 
Also check for the Contact information in the email notification. 

## Expected behaviour
The email notification and the the report should have all the information entered by the "National Society " in the FR template. 

## Related feature
 Field Reports

## Impact
 This impacts all the user but becomes important with the new emergency appeal process and templates. This gives the ball park figure the national society is looking at to inform the discussion on the FAD.

## Severity

It was not affecting business process flows but will start to affect our emergency appeal process based on the new guidelines. 

## Is there a workaround?
Go in to the report and edit it to find the missing information. But this is not a good idea.

**Comment by mariam-yu** [comment]
@szabozoltan69 @mmusori Just in case you need, here are the Figma mockups:
Prototype: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=0%3A4957&node-id=673%3A4518&viewport=274%2C48%2C0.24&scaling=scale-down-width&starting-point-node-id=0%3A4963&hide-ui=1
For devs: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=673%3A4518

The report page (for devs): https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=636%3A15651

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/170006929-ea9a6d21-a9a1-406c-9c74-835df509ebac.png)
