### ISSUE TITLE
Missing trusted Domains

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#210]
Make sure that the following domains are added as trusted.

We have Netherlands RC users registering and they are requested 2 levels of validation - which should not be the case as they are part of the RCRC Movement.

Domains to be added as trusted:

@redcross.nl and @rodekruis.nl

**Comment by dereklieu** [comment]
We had rodekruis.nl but not redcross.nl. I can add that to the list.

For future reference, the allowed list is here:
https://github.com/IFRCGo/go-api/blob/develop/registrations/views.py#L24

I'll make sure to add this to the API README. If you see the domain in this list, it should always treat these as single-level email verification only.
