### ISSUE TITLE
Field report naming 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2112]
*Field reports and Emergencies are named by the user at the moment without any guideline as a free text string. This causes that multiple events may have the same name. This makes the linking of additional FRs to emergencies very difficult (as well as the Appeal linking to Emergencies).*

**Describe the solution you'd like**
*We propose that certain attributes of the FR should be included in the name automatically that will make the Emergency and FR identification more easy.

	a. In case of the initial FR that will be the emergency title as well: 
		['ISO3': ][Didaster type] - ['Year and month of event'] - {Title} 
 e.g.: _HUN: Flood - 2021-09 - Flood in Budapest_

	b. In case of additional FR to an emergency:
		['ISO3': ][Didaster type] - ['Year and month of event'] - {Title}[ #FR][ ('Date of submission')] 
 e.g.: _HUN: Flood - 2021-09 - Flood in Budapest #2 (2021-09-28)_

	c. In case of Covid-19 FR:
                ['ISO3': ][Covid-19][ #FR][ ('Date of submission')]
 e.g.: _HUN: Covid-19 #32 (2021-09-28)_

where 
[Automatically added components]
{User defined components}
'attribute name' - e.g.: in case of 'Country' it can be Austria 

Date format: YYYY-MM-DD
Field report update (#FR) example: #12, which can be calculated from the count of the already linked FRs.

The FR form needs to be re-designed at the Title part. Maybe the block should be moved after the Start Date of emergency/outbreak block. The Add Title part should reflect somehow that the title have auto generated components from the country, disaster type and start date attributes.
![image](https://user-images.githubusercontent.com/68283148/139280839-fa743f9f-c86b-4c92-8468-ebcefc59196a.png)

On the admin page, the whole FR and emergency name should be editable, which allows name adjustments by the admins.
*

**Describe alternatives you've considered**
*In case the #FR attribute can not be generated automatically, it should be a free text option in (c) case (Covid-19 filed reports) and could be omitted in case of (b) (Additional FRs)*

**Comment by mariam-yu** [comment]
@tovari please see the updated wires. We actually already had a few of those concepts in place, but cleaned it and made some changes. Let me know if it's the correct direction, and we will update across all the screens and the UI.

Flow:
- There is a toggle for the First Report and the Report Update.
- In the First Report, we push the user to enter the info before the title becomes active. Only the extra part is active for them to add to the title.
- In the Report Update, the user should select an existing emergency (if one field report was already created). The fields below are populated from the selection. The user can still add to the title, but the #2 of the field report is amended to the title automatically. 
The question is if the user doesn't select the emergency from the dropdown list, what happens? Does this create a duplicate emergency? Shall we "force" the user to select from the dropdown if they have selected "Report Update"? This way, we make sure they are linked and the numbering is correct.

Thanks!
https://www.figma.com/proto/uRgMamNHRi5KhhroYDwuxN/IFRC-GO---Wireframes?page-id=0%3A72&node-id=104%3A25094&viewport=274%2C48%2C0.31&scaling=scale-down-width&starting-point-node-id=111%3A0&hide-ui=1

**Comment by tovari** [comment]
Thanks @mariam-yu, looks good. We will use the ISO3 codes instead of the country names.
I agree that we should force the user to select the emergency, if it is a Report Update. I also agree that the base information of the Report Update should be pre-populated. We might even disable editing of those fields. 
In case, of Covid, all name components are generated from other attributes, so we don't need a user specified component there. 
@JonathanGarro, @anamariaescobar

**Comment by mariam-yu** [comment]
@tovari We can do that. Our initial idea was to have that filter a searchable field, so you can type in and it will narrow down and once you select it pre-populates everything, like country, province, etc. But we can add the country above too. The only thing is I guess we would keep the provinces below, separately, which may break the flow a bit.

**Comment by tovari** [comment]
@mariam-yu, right, I don't know which would be better. maybe an A/B testing would make sense in such case. I will check, if we could do it within a reasonable budget.
