### ISSUE TITLE
Handle Stand-Downs on Surge page

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2115]
Stand-downs should always be ordered after Open Alerts.

Stand-downs should no longer be visible 14 days after the Alert Date.

Also, hide the number of Open Alerts in the Surge Alerts table header.

This should likely be handled in the API:

 - Add an `is_stood_down` column to SurgeAlert
 - In the API call, order to show SurgeAlerts with is_stood_down at the bottom
 - In the API, filter out items with is_stood_down = True and current_date > 14 days later than alert_date

cc @szabozoltan69 @anamariaescobar

**Comment by szabozoltan69** [comment]
Let me show some "sign" of the successful work.
The sort is 'OK'. If I set the code 
```
        sort: {
          field: 'is_stood_down',
          direction: 'desc'
        },
```
This is the result:
![image](https://user-images.githubusercontent.com/6050643/140310074-dc352a5f-b8ca-48d7-ae4d-39db1db96211.png)
But in the done version (asc):
![image](https://user-images.githubusercontent.com/6050643/140310153-f1b462d4-bd8f-4233-881d-221ec258c48b.png)
Also the 14 days limit can be checked. With a "bit interval limit (914 days)" we see this:
![image](https://user-images.githubusercontent.com/6050643/140310218-01dbccb2-5198-4897-a8e2-7282aea3e053.png)
But setting day limit to 14 no last row:
```
    def get_queryset(self):
        limit = 14  # days
```
![image](https://user-images.githubusercontent.com/6050643/140310413-e207287e-b3e8-49fc-84b1-de91162b865a.png)

**Comment by tovari** [comment]
"Stand-downs should no longer be visible 14 days after the Alert Date." - is this applied now?
