### ISSUE TITLE
Handle URL state for in-tab navigation

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2125]
**Is your feature request related to a problem? Please describe.**

Currently, we have a URL for a page, like https://go.ifrc.org/emergencies/5699 and for navigating between tabs on the page, we append a hash so like https://go.ifrc.org/emergencies/5699#details

Now, we have a few cases, where there is further navigation within a tab, and we would like the different navigation states within the tab to have their own URLs.

**Describe the solution you'd like**

It seems to me like the "cleanest" solution would be to do a fairly large refactor of the tabs and routing for tab state changes, and stop using # URLs but rather do like https://go.ifrc.org/emergencies/5699/details, and then if there is a navigation state within `details`, do something like https://go.ifrc.org/emergencies/5699/details/xyz . This would mean though that existing links to like https://go.ifrc.org/emergencies/5699#details will break or we need to include code to be backwards compatible. I worry a bit that changing the URL structure like this would be a large-ish refactor, but I'm a bit fuzzy on how best one would hook into React Router, etc. to implement this, would be good to hear thoughts @frozenhelium .

The other option would be to create URLs something like https://go.ifrc.org/emergencies/5699#details?view=xyz - So add a "fake" query parameter type structure, to be able to add some additional navigation info within a tab, and then handle that in the code to display the appropriate view inside a tab. This seems "easier" to add into the existing code, but also feels a little bit like a hack.

I'll spend some more time going through the code to try and arrive at an opinion here. @frozenhelium would love to hear if you have a strong opinion here, or thoughts. May ping you on Teams as I start to sketch this out a bit more.

**Comment by szabozoltan69** [comment]
Also https://go.ifrc.org/emergencies/5699/xyz#details could be an alternative, though semantically not very nice, because xyz is a part of the #details tab... But it can be easier to parse the "before-#" part of the URL.

**Comment by batpad** [comment]
Thanks @frozenhelium for the guidance on this one. I started sketching out the idea you proposed, using the React Router to handle tab navigation, and it seems to work quite well: https://github.com/IFRCGo/go-frontend/pull/2159/files

So, what we need to do:

 - Create a new "Tab" component to just hold the links to the different tab sections, styled exactly like our current tabs.
 - Move content from TabPanel sections into Routes for different tab URLs
 - Create sub-navigation URLs for pages that need them - we will start with the Catalogue of Services tab on the Deployments page
 - Make sure we know how to deal with more complex cases, for eg. when the number of tabs is not known until we fetch some data, etc.
 - Write some logic to handle redirecting the # URLs to the new URL structure, to keep existing URLs working - eg. /deployments#operations should redirect the user to /deployments/operations
 - Once we have the `/deployments` page migrated to the new tab URL structure, do this for all pages with tabs, starting with the Emergency page (which will be required to implement the Surge Alerts table on Emergencies).

The new structure seems really nice and I think overall simplifies the logic for our views and tab handling, making it seem cleaner to grow out logic of complex sub navigation inside tabs, etc. This is a fair chunk of work, though. It will be a fair bit of work getting the general structure in place and making it work for the first page, and it should be significantly less work applying that pattern to other pages.

I would shoot for getting the /deployments page working with the new tab URL structure alongwith adding URLs for pages within the Catalogue of Services for the December sprint. And then look to migrate the other pages first thing next year. Unfortunately, this means that the Surge -> Emergency -> View All alerts for emergency view may need to wait until next sprint as well.
