### ISSUE TITLE
[Staging] 3W page - key figures - Project type pie chart is displaced

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2127]
## Issue
Pie chart in the middle has been displaced:
![image](https://user-images.githubusercontent.com/68283148/143411904-2680aa63-0587-4b15-a0e4-b2edafd247c3.png)

This affects only Staging, Prod works well.

https://dsgoproxyapp.azurewebsites.net/countries/14#3w

**Comment by szabozoltan69** [comment]
Not easy to find the clue. Randomly sometimes it's OK and sometimes not, maybe depending on some creation event.
In case of "ok" this is the relevant node's source: https://pastebin.com/ybMbHWkL
In case of "not ok" this is the source: https://pastebin.com/xFCXVtJi
The diff looks like that, in width, cx, cy params are different:
![kép](https://user-images.githubusercontent.com/6050643/143462908-84ac8ff2-81ae-4a75-bcd6-a33e7f28f6bf.png)

**Comment by szabozoltan69** [comment]
@frozenhelium – do you have any hunch about the solution? Maybe some "is... fetched" test before the rendering?

**Comment by szabozoltan69** [comment]
This helped me a lot: https://stackoverflow.com/questions/45812458/recharts-pie-chart-centering-using-responsive-container

**Comment by szabozoltan69** [comment]
Deployed to staging.
Old and new view:
![pie](https://user-images.githubusercontent.com/6050643/143567073-7955e92a-edee-42ae-8a8e-b2f61a718bf0.png)

**Comment by tovari** [comment]
Thanks @szabozoltan69 !
