### ISSUE TITLE
Update frontend Node JS version to 16

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2167]
Currently, the frontend works in node 14, but seems like package installs are broken for node v16.

Node v16 is an LTS support version and it would be good to get our code working with node 16 - most likely this would mean:

 - Installing node 16 locally
 -  Seeing what breaks
 - Updating package versions for packages that fail to install, repeating until (hopefully) all errors are solved
 - Look into any TypeScript warnings with the updated code (should hopefully be mostly fixed by installing missing @types/ packages)
 - Test that the frontend seems to work fine with updated versions of packages. Cypress tests should help here to some extent, will also need a round of manual QA.

We should probably not release this change immediately, but might be good to start testing, hopefully it's not too many issues updating.

cc @frozenhelium @szabozoltan69 @tovari @vdeak

**Comment by frozenhelium** [comment]
Moving from webpack 4 to 5 will be great as well. Here's the migration guide https://webpack.js.org/migrate/5/

**Comment by szabozoltan69** [comment]
Let's update it to 18.14.1, which is the recent LTS

**Comment by szabozoltan69** [comment]
Deployed to Staging with node 18.14.1
