### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#217]
In the notifications section of the account, when logged in to be able to select all the notifications possible for all sections a "select all" per each section is missing. So this means you need to select all the boxes manually. This could be improved in phase 2.0

The bug is however, that when you select all the notifications possible and you save you get an error message. See below image as a reference:

![screen shot 2018-03-15 at 21 39 47](https://user-images.githubusercontent.com/23258092/37484496-b78ed10a-2899-11e8-8553-a312f1b10959.png)

**Comment by dereklieu** [comment]
Noting here that it's not necessary to check every single box in every section (I'm not sure if that is your error case or not) as many of the sections are duplicative. For example, checking the five regions means that you will get anything that has a region attached to it, whether it's a field report, appeal, or emergency. 

If you want to subscribe to everything in GO, a sure-fire way to do that would be checking both `New Records` and `Modified Records` for emergencies, appeals, and field reports. This is essentially the same as checking everything.

**Comment by dereklieu** [comment]
Looking at the form, it looks like `Local Storm` is still listed as a disaster type, even though it's no longer represented in the API. I'll remove it, and that should fix the error you're seeing.
