### ISSUE TITLE
Add donor icons to resources page

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#2193]
**Short description**
To add some additional .svg donor logos to the [GO 'about' page](https://go.ifrc.org/about)

Swiss Development Cooperation
![Logo_der_Schweizerischen_Eidgenossenschaft](https://user-images.githubusercontent.com/7791954/150769992-13edd4a0-da12-4ee8-8740-04ffe22eae33.svg)

Danish RC
`https://github.com/IFRCGo/logos/tree/master/national-societies/DNK_Danish-Red-Cross`

USAID

![USAID-Identity](https://user-images.githubusercontent.com/7791954/150770607-4f095d01-4cec-456e-a761-157163e18d76.svg)

**Additional context**
There might be a need to create a third row of donor logos
Suggest to keep RCRC logos in alphabetical order, with 'other' donors (e.g. Eriksson, USAID & SDC) on a separate line.

@mariam-yu could you take a look at the best way of organising these logos?

NB this is **not** an urgent task - @tovari please add to backlog

**Comment by mariam-yu** [comment]
@LukeCaley Logos organized: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=3453%3A95811&scaling=scale-down-width&page-id=0%3A4957&starting-point-node-id=0%3A4963&hide-ui=1 Let us know if works (CC @maisadesign)

**Comment by LukeCaley** [comment]
Thanks! Prefer the final line to be aligned to the centre if possible @mariam-yu

**Comment by maisadesign** [comment]
@LukeCaley @mariam-yu @szabozoltan69 
Updates on the logos are in the prototype:
https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=3453%3A95811&scaling=scale-down-width&page-id=0%3A4957&starting-point-node-id=0%3A4963&hide-ui=1

**Comment by szabozoltan69** [comment]
Done on prod and staging.
Please give a check to the links (mainly to the Swiss Confederation) if they are ok.
