### ISSUE TITLE
Surge Catalogue of Services updates:

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2196]
## Surge Catalogue of Services updates:

At this link, in the additional resources section (at the bottom of the page)

https://dsgoproxyapp.azurewebsites.net/deployments/catalogue/health/eru-red-cross-red-crescent-emergency-hospital

Please include these two links-

Norwegian Red Cross Emergency Hospital Handbook

Norwegian Red Cross Emergency Hospital film

---------------------------------------------------------------------------------------------------------

At this link, in the additional resources section (at the bottom of the page)

https://dsgoproxyapp.azurewebsites.net/deployments/catalogue/water/water-supply-rehabilitation-wsr

Please include this link (text is already there).

Water Supply Rehabilitation ERU Handbook

-------------------------------------------------------------------------------------------------------

At this link, in the additional resources section (at the bottom of the page)

https://dsgoproxyapp.azurewebsites.net/deployments/catalogue/health/community-based-surveillance-cbs

Please include this link

Public Health ERU Community Base Surveillance Handbook

**Comment by szabozoltan69** [comment]
Can be tested on staging.
![kép](https://user-images.githubusercontent.com/6050643/151173249-f3ef6e73-7fb2-4c87-b7f5-303b10b7058a.png)
![kép](https://user-images.githubusercontent.com/6050643/151173279-50985491-5cd1-44a6-a8b4-3137adda3ab9.png)
![kép](https://user-images.githubusercontent.com/6050643/151173303-cf3af0ef-c1eb-429d-b029-f072a430e39f.png)
If you need other segmentation (between normal text and URL), let me know.
