### ISSUE TITLE
Some users report not being able to log into admin

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#220]
@k-som @guipizzini I'm still not 100% clear on the issue here, so let's use this ticket to clarify this problem.

From what I understand, you've created a user group and added two users to this group. You've also given them staff status separately, which I believe is required in order to allow them to log into the admin. But they aren't able to login. Is this correct?

Questions:

1. What do they see when they attempt to login? A credential warning, unauthorized, or something else?
1. Is everyone else who was formerly able to login to the admin still able to do so?

**Comment by dereklieu** [comment]
Closing as this seems resolved. I created a test user account, gave that account staff status, and successfully logged in without issue. I also gave that account access to the existing user group, which also seemed to work. Not sure of the original issue, but please reopen if this comes up again.

**Comment by guipizzini** [comment]
Created a new ticket for this, following the template. As well, using our new IFRC internal ticketing system to track maintenance.
