### ISSUE TITLE
Emergencies: 'Funded' key value card doesn't show up, when funding is 0.

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2209]
## Issue

'Funding' card is not shown when funding is zero.:
![image](https://user-images.githubusercontent.com/68283148/152348733-4701c882-b684-47fe-a262-d8183b1f9c6f.png)

Would be good to see the 'Funding' card on the emergency page even when it is 0 CHF.

cc: @mmusori

**Comment by szabozoltan69** [comment]
A local environment example:
![kép](https://user-images.githubusercontent.com/6050643/155569255-ffc27a50-a624-4f80-8486-f8ea7cf8cf81.png)
