### ISSUE TITLE
User Rights on GO

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#221]
## Issue

The GO back end is "kicking out" users.

As soon as we are granting editing rights to users they're editing rights remain valid for 24 hours but are then not anymore a user with editing rights. This means that our colleagues are not being able to edit the operations pages.

This does not apply to "super users".

This applies to "regular" users as well.

Regular users, even though they're "active", they can't log in. After changing a password, they can log in once and the story repeats.

## Steps to reproduce

Logged into the Django Framework and either:

- Changed the role of the user;
- Changed the password of a regular user.

## Expected behavior

Each user should interact with the platform, based on their user rights defined in the Django Framework.

**Comment by dereklieu** [comment]
Thanks for opening this. I've created a test account in the development admin to re-create this, and will update here on my findings.

**Comment by dereklieu** [comment]
I haven't been able to re-create this issue from my end on the development API - my test account is still able to log in and perform actions consistent with it's user group. I move to test on the production API.

**Comment by guipizzini** [comment]
@dereklieu any updates on this one?

**Comment by dereklieu** [comment]
So far I haven't been able to recreate this issue from either development or production environments. My test account is still able to log in into the admin site without issue.

@guipizzini perhaps we can set up a call between myself and one of the users experiencing this issue? Talking in person will help me gather more info to figure out what could be happening here.

**Comment by guipizzini** [comment]
@dereklieu we need to prioritise this one, it is becoming very urgent. Could we have a call tomorrow?
