### ISSUE TITLE
3W in Emergencies Epic

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-frontend#2233]
This ticket is meant to consolidate several disparate issues into one cohesive feature request.

# Overview

The 3W reporting tool is intended to facilitate rapid data collection across response and non-response activities. In its current form, the GO platform collects this information in a single screen, with most data fields overlapping regardless of the type of activity being recorded. This feature request will split up these two workflows, with the focus for this round up upgrades being the response data side. 

# Proposed Changes

Users will still access the 3W reporting interface in the same way, but the first question they answer will be the fork in the road between response and non-response:

![Screen Shot 2022-02-18 at 11 04 51 AM](https://user-images.githubusercontent.com/8890661/154718393-c866e97b-e2d7-4af4-ac9b-2678bd0f61e2.png)

Next, users will use a lookup to active GO emergencies. Existence of an emergency record is a pre-requisite for saving emergency activity information.

![Screen Shot 2022-02-18 at 11 05 54 AM](https://user-images.githubusercontent.com/8890661/154718623-c477546a-0a08-4922-bb22-1e55ce890050.png)

Users will then be asked to select the admin boundaries of the country or countries associated with the emergency record. Given current system limitations, we will only be able to provide admin1 locations, but future development could explore adding admin2, if that data becomes available in the system. The lookup should use the same search function as currently exists. Each distinct 3W record should be created for activities that are occurring across all tagged locations. 

There is currently a start and end date associated with the 3W, but the response 3W would only ask for a start date, given the rough timelines of rapid response work. A radio button selection would be, by default, set to "Activity On-Going", but users will be able to toggle it to "Activity Complete".

![Screen Shot 2022-02-18 at 11 10 25 AM](https://user-images.githubusercontent.com/8890661/154719438-932b679a-756b-48de-947c-5eacfe7d34ce.png)

Next, users will be asked who is conducting the activity: Either a national society or a deployed ERU. For National Societies, a lookup field would show all NSs, and then add three plain text fields for Name, Role, and Email of the main contact for people to reach out to if they have questions about the activity.

![Screen Shot 2022-02-18 at 11 12 31 AM](https://user-images.githubusercontent.com/8890661/154719820-2e4e84f4-99d6-4380-ba14-13b004646f96.png)

When toggling to a deployed ERU, the system will reference surge data and list all activated ERUs. Users can then select the relevant one doing that work. If they expect to see an ERU that isn't listed, the help text should explain that they need to register the ERU's activation in the system.

![Screen Shot 2022-02-18 at 11 12 58 AM](https://user-images.githubusercontent.com/8890661/154719920-e83dcfac-03a4-4880-877b-fcec82a34050.png)

Next, users will select the relevant sectors that this 3W record is meant to capture. This list will be match IFRC's "Operational Strategy Template": 

- Shelter, Housing and Settlement
- Livelihoods
- Multipurpose Cash
- Health and Care
- Water, Sanitation and Hygiene
- Protection, Gender and Inclusion
- Education
- Migration
- Risk Reduction, climate adaptation and recovery
- Environmental Sustainability
- Community Engagement and Accountability

They will select one or more of these categories, and then be brought to the next page where the data will be collected:

![Screen Shot 2022-02-18 at 11 18 52 AM](https://user-images.githubusercontent.com/8890661/154721116-f3dce522-91b8-4e66-bb7a-a1572fc90875.png)

On the left pane, the selected categories will appear, along with activities that fall under those categories. This list is still being consolidated. At the bottom of the list of most common activities reported in the response phase for 3Ws, users will be able to select "Add Custom Activity". 

Activities that are selected then appear in the main pane of the page. 

## Data Entry Process and Options

In order to provide flexibility and speed of input for users while also allowing for more robust data when possible, users will, by default, be given aggregated data fields but have the option to toggle more granular/disaggregated data fields. There are several data types that will be available (sometimes multiple per type), depending on the activity selected. 

### Simplified Fields (Default view)

**Beneficiaries**: The activity is only reporting people reached. Boxes will allow user to either enter people or households (with a toggle to select which) OR men and women. An optional long-text box will be available if users want to provide additional information about the activity. 

![Screen Shot 2022-02-18 at 11 34 17 AM](https://user-images.githubusercontent.com/8890661/154723977-47556545-6ebe-4dd2-84bc-fee374337922.png)

**Supplies**: A dropdown of common NFIs will appear, dependent on the activity. This will be a multi-select. Next to each item selected, a box will appear and allow the user to quantify how many of that item has been distributed. The same beneficiary boxes will appear, allowing optional entry of people reached with each item type reported.

![Screen Shot 2022-02-18 at 11 38 48 AM](https://user-images.githubusercontent.com/8890661/154724683-c8bd8323-6e87-4b16-a6ee-ef17be58d999.png)

**Points**: For activities that have specific point data associated (e.g. a hospital assessment/rehabilitation), users can provide a simple count of the number of those points. 

**Custom**: Users that create custom activities will have that associated with the sector/category it fell under (e.g. a custom activity from the WASH category will be associated on the backend as a custom WASH activity. Users will then be able to create a new row for beneficiary, supply, and/or point data. Create/delete new activities will appear below.

### Detailed Fields (Optional)

Each data type listed above can have more expanded details associated. This captures issue [1983](https://github.com/IFRCGo/go-web-app/issues/849) requirements. A toggle allows activity-specific conversion from simple default data to more complex, FDRS compliant disaggregation. When selected on the following types: 

**Beneficiaries**: People/households and men/women change to FDRS age/gender disaggregation.

![Screen Shot 2022-02-18 at 11 44 09 AM](https://user-images.githubusercontent.com/8890661/154725572-a6b12649-fa2b-445e-8acf-08ba035c41f1.png)

**Supplies**: No detailed view available at this time. 

**Points**: Data type changes from integer to three fields: X, Y, and an optional description. Note that this is not intended to be a robust GIS data collection tool, only for teams that are managing relatively small point data sets. Each row will need a delete option, and an "Add Point" button will generate new rows.

# Impact on Other Interface Elements

## Profile

Users that are creating these records will need a way to quickly access them to update or close out the activity. I recommend a simple table view available as a separate tab on the profile page called "Reporting" where 3W (both response and non-response) records are available. 

## Emergency

Recommend having the response 3W available as a table that sums people reached and NFIs distributed from all 3W's associated with the disaster on the activities tab. If the logged in user ID matches that of the record created_by, then an edit button will appear next to that record.

![Screen Shot 2022-02-18 at 11 58 33 AM](https://user-images.githubusercontent.com/8890661/154728075-ce4b1d63-14ee-49c1-866c-21235800f92b.png)

# Impact of Proposal on Existing Issues

## Captured On This Ticket

- [1983](https://github.com/IFRCGo/go-web-app/issues/849): FDRS Data Disaggregation
- [1978](https://github.com/IFRCGo/go-frontend/issues/1978): 3W Record Access on User Page

## To Be Addressed in the Future

- [1822](https://github.com/IFRCGo/go-frontend/issues/1822): Integration with NS Databases - This will require implementation of these features and evaluation of what didn't make it in from the proposal before making headway on that data transfer process.

**Comment by batpad** [comment]
@frozenhelium @tovari @LukeCaley - we will need to figure out how we neatly integrate the ERU information with the existing backend for ERUs. There are a few places where we display ERU counts, etc. that pulls from the existing ERU backend. If we are now entering ERU data into this new form, we will have to think of how to consolidate this and make sure all the places where we surface ERU data and counts are accurate. For eg. the ERU count on the Surge tab of the emergency page.

Am happy to help with this, but this will need a bit of discussion and figuring out. @frozenhelium @thenav56 - should we maybe try and take a look at the existing models a bit, and see how best we can either reconcile, or for now make sure the data in different tables is kept in sync .. ? I'm not fully sure of the best approach here.

+cc @anamariaescobar

**Comment by LukeCaley** [comment]
Post release fixes to the GO 3w for emergencies, [added to the GSS here](https://docs.google.com/spreadsheets/d/13aXRVISdq_VRTmlaarqxz05hjnkhN5StrMN3Ut-t3Gw/edit#gid=0).  I have added a priority label and sorted for your convenience, cc @tovari @frozenhelium @szabozoltan69 , cc @JonathanGarro

**Comment by tovari** [comment]
Created a new ticket for the post release updates (#2329) and closing this.

**Comment by nanometrenat** [comment]
> Each data type listed above can have more expanded details associated. This captures issue https://github.com/IFRCGo/go-web-app/issues/849 requirements. A toggle allows activity-specific conversion from simple default data to more complex, FDRS compliant disaggregation.

Noting that Emergencies 3W was implemented differently to the above requirements - can't see documentation as to why - have therefore left https://github.com/IFRCGo/go-web-app/issues/849 open
