### ISSUE TITLE
PROD: Password recovery page doesn't load

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2270]
## Issue

https://go.ifrc.org/recover-account 
page doesn't load, only a grey screen is visible.
![image](https://user-images.githubusercontent.com/68283148/156246121-7381527c-da1a-45d2-aa1f-e83755855976.png)

**Comment by szabozoltan69** [comment]
In Inspector I see this twice: "Error: Keyword if is already defined".
The error can be reproduced locally also.
The detailed error report is below.
@frozenhelium @batpad could you please give me some clue for what can be changed? Maybe some kind of webpack issue?
![kép](https://user-images.githubusercontent.com/6050643/156307546-389c9403-867b-445c-8010-7d7f6a0a8cc3.png)
