### ISSUE TITLE
GO Logo Go on Browser Tab

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#228]
## Issue

*Kindly include the GO Logo on the Browser Tab*

## Steps to reproduce

*Simply navigate to go.ifrc.org and you will notice the browser tab has no GO Logo*

## Expected behavior

*GO Logo to appear when navigating the site*

**Comment by dereklieu** [comment]
Also put page title for different pages into `title` header element.

**Comment by dereklieu** [comment]
Page titles addressed in #292, waiting on favicon.

**Comment by dereklieu** [comment]
Closed #341
