### ISSUE TITLE
[PROD] Resend validation (for users) contains infinite recursion

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2281]
The https://go.ifrc.org/resend-validation page does not work well.
It does not process the API-s error message.
For a quick workaround I removed the 24 hours limit: https://github.com/IFRCGo/go-api/pull/1344/files
But the frontend is still ill, gives errors after sending the (proper) email.
Some experiments of Viktor, using a "hello" to show infinite recursion (maximum update depth exceeded):
![kép](https://user-images.githubusercontent.com/6050643/156771722-44984ee6-1d83-4b1a-8ca5-5cd4c539dea9.png)
![kép](https://user-images.githubusercontent.com/6050643/156771917-b9aeb691-35c1-4d17-aa62-0f88ffe5777d.png)
![kép](https://user-images.githubusercontent.com/6050643/156771977-74ff2a07-a2f5-4c5e-a996-56dfc6df062d.png)
^ maximum update depth exceeded
![kép](https://user-images.githubusercontent.com/6050643/156772094-c2f0540c-8b83-4720-bc1b-61abc341ea57.png)

**Comment by szabozoltan69** [comment]
@frozenhelium @batpad if you have any idea, much appreciated.

**Comment by szabozoltan69** [comment]
There is an other bad_request message also with which it is possible to test the frontend error handling:
https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L476-L478

**Comment by batpad** [comment]
Made a PR here: https://github.com/IFRCGo/go-frontend/pull/2282 - @szabozoltan69 could you test, that should fix this.

**Comment by batpad** [comment]
cc @vdeak ^^ if you are able to test that that works, I can cherry-pick this commit onto master and make a hotfix (we should not merge develop to master since all the unreleased features are now un-hidden).

**Comment by vdeak** [comment]
@batpad I tested it, it works fine. Cheers :)
