### ISSUE TITLE
Geolocation issue on Maps

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#231]
## Issue

*Geolocation for pacific islands needs to be double-checked*

## Steps to reproduce

*Fiji appearing off the western coast of Australia on deployments page: https://go.ifrc.org/deployments*

## Expected behavior

*Geolocation to be corrected.*

**Comment by dereklieu** [comment]
Adjust centroid for Fiji.

**Comment by dereklieu** [comment]
Adjusted, and for New Zealand as well.
