### ISSUE TITLE
3W in Emergencies - 2022 April updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2329]
This is related to #2233 

Post release fixes to the GO 3w for emergencies, [added to the GSS here](https://docs.google.com/spreadsheets/d/13aXRVISdq_VRTmlaarqxz05hjnkhN5StrMN3Ut-t3Gw/edit#gid=0). I have added a priority label and sorted for your convenience

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/commit/8e32470ccac672dffc18774fd45793050985a47a - solves row 43

**Comment by szabozoltan69** [comment]
Web-rewrite made this solved.
