### ISSUE TITLE
Missing operations/Homepage

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#233]
## Issue

Operations missing in the key figures and map on the Go **homepage**:
* Emergency Appeals:
> Ethiopia - Drought (MDRET016),
Kenya - Drought (MDRKE039),
Dominican Republic - Floods (MDRDO009),
Peru - Floods (MDRPE012),
Sri Lanka - Floods & Landslides (MDRLK006),
Costa Rica - Floods (MDRCR016);
* DREF operations:
> Papua New Guinea - Volcanic Activity (MDRPG007),
DR Congo - Floods and Cholera (MDRCD024),
Philippines - Mayon Volcano Eruption (MDRPH027)

It seems that these operations have been pulled as you can access them from a country page level but in the same time you can't find them on the homepage (both the map and key figures affected).

## Steps to reproduce

Look for the above-mentioned operations on both the homepage and country pages - can be found only on the latter.

## Expected behavior

All operations can be accessed from the homepage, map bubbles correspond to certain ongoing operations, correct key figures.

cc: @guipizzini

**Comment by dereklieu** [comment]
Two issues that were fixed: using a broader last_modified date to recognize modified appeals, and correctly updating existing appeals that are marked as modified. The appeals mentioned are now in the production database.
