### ISSUE TITLE
Graph Bars on Deployments Page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#234]
## Issue

*Deployments page, ERU deployment type and number of deployments by NS element represented as a diagonal bar chart seems redundant when so few data points.*

## Steps to reproduce

*Navigating the Deployments Page*

## Expected behavior

*Could be better to present this data with capacity in some way to understand how stretched is the system* To be discussed with @ascalamogna

**Comment by dereklieu** [comment]
No further actions in this phase.

**Comment by LukeCaley** [comment]
1. ERU boxes at bottom of page should replace ERU table (with export button) as contains all the same data.
2. Order the boxes based on number of ERUs deployed.
3. Order to be discussed with surge but suggestion: a, HEOps; b: ERU; c: personnel
