### ISSUE TITLE
Risk module v1.1 (Initial improvements for May 2022 update)

### ISSUE THREAD

**Issue by justinginnetti** [IFRCGo/go-frontend#2355]
*New features and fixes to be included in the first update of the GO Risk module*

**Describe the solution you'd like**
*We will add/visualise some additional data, add a couple of new visualisations for existing data and make some changes to the UI/UX.*

**Describe alternatives you've considered**
*The alternatives have arisen through the bug tracker and numerous conversations with users and the dev team.*

**Additional context**
*Most of these have been in the works for some time.*

**Where does the data come from and how is it maintained?**
*Several sources, including PDC, 510, INFORM, IDMC, as well as IFRC's own data.*

**Should there be any restrictions around viewing or updating information related to this feature**
*All outputs will be publicly available*

**Links to documentation**
*See checklist below:*
**New features**

- [x] Add average annual loss metrics per country from UNDRR, IDMC. This will be visible on country pages and maybe regional pages. *Solution: Add “total” value to left/right of slider.*
- [x] Pull in dynamic table of potential anticipatory actions from [this file](https://docs.google.com/spreadsheets/d/1hgvPQzLAL6RknxsLTUCXIVSdd78roBDW5FiKSwwSleY/edit?usp=sharing). *Mariam to have a first look.*
- [x] On country pages, next to link for EAPs, provide link to the public IFRC Resilience Dashboard report PDFs using [this API](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Frmd-api-test-appservice.azurewebsites.net%2Fpublishreport%3FprogramId%3D&data=04%7C01%7CJustin.GINNETTI%40ifrc.org%7C1e86c27ff51b4665454b08da13263a1a%7Ca2b53be5734e4e6cab0dd184f60fd917%7C0%7C0%7C637843352144230324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jzn3j6HoRjFcTXc1sCfE1XuSBAQYCbQ1SpQKgje%2Bm4k%3D&reserved=0)
- [x] Using the Resilience Dashboard API, display link to PDFs of public reports
- [ ] *Start now, but deliver for June:* In the table of impacts per return period, show impacts for annual events and 1-in-5-year events (to appear on country pages for countries for which we have the DesInventar data). Use the data form DesInventar to establish the thresholds.

**Bug fixes**

- [x] On imminent events map, make sure that forecasted hazards are assigned to one or more countries to avoid them appearing on the "wrong" regional pages
- [x] Add PDC logo and updated link to the PDC impact forecasts *Mariam to have a look*
- [x] Rescale the food insecurity map coloring and legend because the thresholds are too low at present
- [x] Make sure we are pulling in and correctly visualising the most recent data from IPC per country per month
- [x] Make sure population exposure values exceed the values for the number of people at risk of displacement (e.g., Canada for floods)
- [x] For the monthly INFORM scores, display them by category rather than by numerical value (using the INFORM categories)
- [x] The data sometimes displays a 0, while at other times shows a middle-score. I expect a 0 to really mean 0 people and a middle-score to mean 'unknown'. However, for instance for American Samoa, it only shows a 0 for one option, which may be confusing.

**Comment by frozenhelium** [comment]
Updates available on the test server: https://ifrc-go-feature-risk-improvements.surge.sh/
