### ISSUE TITLE
Multiple bubbles for operations in the same country

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#236]
## Issue

If there is more than one operation in the same country, it's not reflected on any of maps as there's only one bubble for a country. 
In most cases, you can find the operation when filtering by disaster type but eg. there are two population movement operations in Uganda and using a map you can access only one of them.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/25579864/40350026-bdf7d46c-5da8-11e8-8ecb-2e8ab859a914.png)

## Expected behavior

Multiple bubbles for a country??

**Comment by dereklieu** [comment]
Operations are combined; tooltip should show cards for separate operations.

**Comment by dereklieu** [comment]
Closing as we're not supporting multiple bubbles.
