### ISSUE TITLE
Capitalize GO in page titles

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2367]
## Issue
Please make capital GO in all page titles (prod and stage as well):

![image](https://user-images.githubusercontent.com/68283148/170062194-50239744-4f0e-45c4-a2a0-0fe39883e3f0.png)

Should be IFRC GO....

**Comment by szabozoltan69** [comment]
Changed all IFRC Go strings to capital: IFRC GO.
Maybe a translation reload is needed to take effect, because the translation keys did not change (just the value).
