### ISSUE TITLE
Response Documents search on the emergency page Reports tab

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2368]
## Issue

The search field of the Response Documents is case sensitive, which makes search difficult. It should be case insensitive.

E.g.:
https://go.ifrc.org/emergencies/5854#reports

![image](https://user-images.githubusercontent.com/68283148/170066668-1268089a-1d4a-4ebb-9d83-cb2a81d14ee5.png)

![image](https://user-images.githubusercontent.com/68283148/170066786-3013d667-9cff-4ede-8494-511c42573a6c.png)

**Comment by szabozoltan69** [comment]
Solution found:
![kép](https://user-images.githubusercontent.com/6050643/170103230-ebee0832-c223-4e3a-80e0-c2b4de25b243.png)
