### ISSUE TITLE
Field reports issues

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-frontend#237]
## Issue

1. Country names not pulled, have to add them manually - as already described (#235) .

2. Field reports are not being updated or there are some timing issues - run the dmis.py script at 8:15, only one field reports out of five got updated on Go, app. an hour later the second one appeared on Go, still waiting for the next three (10:30).

3. "Created at" should indicate the date when a field report has been submitted not when the script has been run.

## Steps to reproduce

DMIS:
![image](https://user-images.githubusercontent.com/25579864/40351069-ccb449f6-5dab-11e8-86d7-9e83afdd3d7e.png)
GO:
![image](https://user-images.githubusercontent.com/25579864/40351083-d9c8ae0c-5dab-11e8-8614-550db8b57124.png)

## Expected behavior

Field reports updated once the script has been run.
Country names automatically pulled.
"Created at" inditaces when a reports has been created.

Ideally - field reports updated automatically without running the script.

cc: @guipizzini

**Comment by dereklieu** [comment]
There's a column in `ew_reports` called `Inserted` that should correspond to the `created_at` date.
