### ISSUE TITLE
[PROD] Elasticsearch returns results that user isn't allowed to view

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-frontend#2389]
## Issue

Elasticsearch returns results that user isn't allowed to view.

## Steps to reproduce

1. Log in with an NS user account
2. Search for "Bangladesh Monsoon Floods"
3. Elasticsearch returns many results, one of them is Event: Bangladesh : Monsoon Flood 10/2019 [(front-end)](https://go.ifrc.org/reports/11966) [(backend)](https://goadmin.ifrc.org/en/api/fieldreport/11966/)
4. Select the event
5. "Resource Not Found! The resource doesn't exist or you are not authorized to access this resources" error message is shown

![image](https://user-images.githubusercontent.com/15220593/171804228-121c2eab-4e08-49dd-98f2-dc2388e04943.png)

## Expected behaviour

Search should return only results that user is allowed to view.

## Impact

Potentially every user who uses the search feature.

## Severity

9 out of 10 patients might develop slight symptoms of confusion and irritation. 1 out of 10 might show more severe symptoms of anxiety.

## Is there a workaround?

None identified.

**Comment by szabozoltan69** [comment]
Recently we do not store visibility data in the ElasticSearch indexing.
We should smarten our system with this feature, but this needs some effort.

A (dirty) workaround would be an extension to the warning, like "...if you are sure that the needed page exists, please write an email to im@ with the required entity and the team will email you the needed info".

**Comment by szabozoltan69** [comment]
Good news: succeeded to put a visibility value to the indexing.

Example:
![kép](https://user-images.githubusercontent.com/6050643/171907694-04c9bc4e-0a66-4917-a0f3-5d5e820c4bb4.png)
https://github.com/IFRCGo/go-api/pull/1444

So the task is to be aware in https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/utils.js#L368-L374
with the user's profile entities (on frontend).

**Comment by szabozoltan69** [comment]
Another good news: https://github.com/IFRCGo/go-frontend/pull/2394/files uses a "linear" permission level comparison and shows only those that are permitted.

**Comment by szabozoltan69** [comment]
Can be tested on Staging.

**Comment by tovari** [comment]
This is fine partially. Filtering of non-public content seems to work. 
On the other hand NS users may get search result of content visible to other NSs only.
E.g.:

![image](https://user-images.githubusercontent.com/68283148/178265721-3a235b12-6b6a-4741-ab52-4a64f067bb28.png)

When clicking on it, it shows the message correctly:
![image](https://user-images.githubusercontent.com/68283148/178265912-fe44c9bf-07a8-4eaa-9c5f-f65b9a63ad4e.png)

**Comment by szabozoltan69** [comment]
It's true. Then we should extend the check - in case of NS - that which one. Maybe also the indexing should contain it (or them, if multiple ones are related).

**Comment by tovari** [comment]
I think, we could still release the existing improvements and further work on it.
