### ISSUE TITLE
[PROD] Visibility / orgType

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2392]
We should fix this: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/ThreeWForm/useThreeWOptions.ts#L190-L193
... to use the other organization types also:
```
  <option value="NTLS">National Society</option>
  <option value="DLGN">Delegation</option>
  <option value="SCRT">Secretariat</option>
  <option value="ICRC">ICRC</option>
  <option value="OTHR">Other</option>
```
Maybe we can introduce the concept of "Movement", as it is on frontend:
Movement (NTLS, DLGN, SCRT, ICRC) differs from Membership (Movement + OTHR).

We should fix also https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/constants.js#L206-L209 and https://github.com/IFRCGo/go-api/blob/develop/api/models.py#L315-L318

@tovari – if you have sthg to add, please add it.

**Comment by tovari** [comment]
Is this obsolete @szabozoltan69 ?

**Comment by szabozoltan69** [comment]
Yes, due to org_type-s come from https://goadmin-stage.ifrc.org/api/v2/global-enums/ now:
```
    "api_profile_org_types": [
        {
            "key": "NTLS",
            "value": "National Society"
        },
        {
            "key": "DLGN",
            "value": "Delegation"
        },
        {
            "key": "SCRT",
            "value": "Secretariat"
        },
        {
            "key": "ICRC",
            "value": "ICRC"
        },
        {
            "key": "OTHR",
            "value": "Other"
        }
    ],
```
