### ISSUE TITLE
Frontend login tracking

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2393]
For backend login tracking there is the Auth log, and the (anonyme) frontend login data is logged via go-logs/access.log, but we would like to know, when and which username was used to log in.

So we would like log the time and username (and maybe browser params) at the "login" API endpoint hit by frontend when a user tries to log in. (Of course, password not.)

@tovari – if there is something to add, please add it.

**Comment by thenav56** [comment]
@szabozoltan69 We can track the logins here https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L337-L369.

Maybe just logger or create a separate table for tracking.

**Comment by szabozoltan69** [comment]
@thenav56 Is it possible to set the logger to use a specific log file for that "login-tracking" purpose?
(In api/management/commands the scripts use their own log files – it would be fine here also.)

**Comment by szabozoltan69** [comment]
A duplication of issue 2394, so I close this.
