### ISSUE TITLE
Follow best practices when loading google fonts / tag manager incl user agreeing to policy

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2401]
Make sure we are using best practices to preload, etc. when fetching google resources.

cc @frozenhelium

**Comment by tnagorra** [comment]
We should also think about adding a cookie banner / privacy policy if we are using google fonts.
https://www.iubenda.com/en/help/20625-google-fonts-gdpr-how-to-be-compliant

**Comment by nanometrenat** [comment]
@batpad @frozenhelium did this get addressed as part of the rewrite, or is work still required here?

**Comment by nanometrenat** [comment]
Changed title to reflect that the Google fonts link above advises that even if no cookies the usage of google fonts still involves a tracker that users need to agree to.  Not sure if this already got picked up in the rewrite but assigning to Mariam as know lots of Ts & Cs conversations just now

**Comment by mariam-yu** [comment]
Thanks @nanometrenat . Will definitely keep it in mind. So far, what we have learned is GO doesn't need to be GDPR compliant (as I understood), and Paola is working on the cookie part, but I will make sure to clarify and include the fonts.

**Comment by frozenhelium** [comment]
@nanometrenat Thanks for the follow-up, apologies I missed your previous comment. After the rewrite, we pull the google fonts during build.  So, we do not need to add preload tag or the cookie banner for this.

**Comment by nanometrenat** [comment]
Thanks @frozenhelium based on this I will close this ticket - cheers
