### ISSUE TITLE
DREF Request final changes

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2418]
**General changes to be implemented in all the forms (Sudden, Slow and Imminent)**

- [x] Essential Information: Tittle --> Change to "DREF Tittle"
- [x] Essential Information: Tittle --> Move it below Country and Region
- [x] Essential Information: Name of National Society --> move to the top of the section.
- [x] Essential Information: Copy data from an existing field report --> Change to "Import data from existing field report"
- [x] Essential Information: Copy data from an existing field report -->  Change guidance "These field reports have already been filtered by the country and disaster type that you have entered. Selecting field report will pre-fill matching fields in this report, which you can modify" to "These field reports have already been filtered by the National Society that you have selected. Selecting a field report will pre-fill matching fields in this request, which you can modify"
- [x] Essential Information: Copy data from an existing field report --> Can the list of Field reports be filtered so only the ones from the NS selected appear?
- [x] Essential Information: Tittle --> Can we automatize the tittle? Country + type of disaster + year - month + space to add name? Like we have on the Field Reports now
- [x] Essential Information: Affected Country and Region --> Remove the option for multiple Countries
- [x] Essential Information: Affected Country and Region --> The country should be pre-populated by the selection of NS
- [x] Essential Information: People Affected/ at risk --> Total affected population/Total population at risk
- [x] Essential Information: People Affected --> Add guidance below: Includes all those whose lives and livelihoods have been impacted as a direct result of the shock or stress.
- [x] Essential Information: People Affected --> Should be pre-populated from FR if linked
- [ ] Essential Information: Upload map --> Can we re-use the functionality from FR to autogenerate maps? Add a check-box labelled "Autogenerated map"
- [x] Essential Information: Upload map --> Add guidance: "Add a map highlighting the targeted areas for this operation, it will be used for the publishable document"
- [x] Essential Information: Cover image --> Add guidance: "Upload a image for the cover page of the publishable document"
- [x] Timeframes: Date of event --> Move to top of Description of the event section + rephrase to "Date of the event/trigger" **This  item is not needed anymore, will add the correct feedback in the update**
- [x] Timeframes: Date of event --> Should be pre-populated from FR field "start date" **This  item is not needed anymore, will add the correct feedback in the update**
- [x] Timeframes: Date of GO field report --> Delete
- [x] Timeframes: National Society response commenced --> Move to top of Current National Society Actions section + rephrase to " Start date of National Society actions"
- [x] Timeframes: Date of National Society request: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: Date of Submission to GVA: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: Date of approval: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: Date of Publishing: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: Operation timeframe: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: Operation timeframe: Add a constraint, no more than 30 months
- [x] Timeframes: End date of Operation: Move to the end, new section called "Operational Timeframes"
- [x] Timeframes: On the new section called "Operational Timeframes", can we make it in 2 rows?
- [x] Previous Operations: Has a similar event affected the same area in the past? --> Rephrase to "Has a similar event affected the same area(s) in the last 3 years?"
- [x] Previous Operations: Did it affect the same population? --> Rephrase to "Did it affect the same population groups?"
- [x] Previous Operations: Did the National Society request funding from DREF? --> Rephrase to "Did the National Society request funding from DREF for that event(s)?"
- [x] Previous Operations: If yes, please specify which operations --> Enter MDR code and year + MDRXXX YEAR, MDRXXX YEAR
- [x] Description of the event: What happened, where and when? --> It's being brought form FR, which is great, but it brings <p> before and </p> at the end
- [x] Description of the event: Upload photos --> Limit to maximum 2 pictures
- [x] Description of the event: Upload photos --> possibility to add a caption?
- [x] Movement Partners Actions --> Rephrase to " Movement Partners Actions related to the current event"
- [x] Other actors actions --> Rephrase to "Other actors actions related to the current event"
- [x] Other actors actions --> List major coordination mechanisms in place --> Can we make this a yes/no question labelled "Are there major coordination mechanisms in place?" and if yes is selected then a text box opens to list them?
- [x] Targeted population: Total population --> Rephrase to "Total targeted population"
- [x] Targeted population: Total population --> Can we pre-populate this field with the value entered on the Essential information? field name: Number of people targeted
- [x] Targeted population: Estimated number of displaced people (if any) --> Rephrase to " Estimated number of people on the move (if any)"
- [x] Objective and strategy rationale --> Move it to the top of the page, before Targeting strategy
- [x] Objective and strategy rationale: Overall objective of the operation -->Change "persons affected" to "people in need" in the guidance
- [x] About support services: Will surge personnel be deployed? --> Can we make it a yes/no question and if yes selected open a box with the following guidance inside "Please provide the role profile needed"
- [x] About support services: If there is procurement, will it be done by National Society or IFRC? Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? For Cash and Voucher Assistance, what is the status of the Financial Service Provider? --> Make this part guidance "Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? For Cash and Voucher Assistance, what is the status of the Financial Service Provider?"
- [x]  About support services: Any potential risk to the implementation of this operation? What will be the mitigation measures? Any safety and security concerns? How will the National Society ensure the safety of the staff, volunteers and community? --> Make this part guidance "What will be the mitigation measures? Any safety and security concerns? How will the National Society ensure the safety of the staff, volunteers and community?" **This change is not longer needed, update in comment below**
- [x] About support services: How will this operation be monitored? Will there be IFRC monitoring visits? How will it be deployed? --> Make this part guidance "Will there be IFRC monitoring visits? How will it be deployed?"
- [x] About support services: Please briefly explain the National Societies communication strategy for this operation. Will the IFRC be supporting with communication? What roles will be involved? -->Make this part guidance "Will the IFRC be supporting with communication? What roles will be involved?"
- [x] Planned interventions --> Move above About support services section

@frozenhelium @tovari  sorry for the long ticket!

**Comment by anamariaescobar** [comment]
Hey all,

One final change from the lead:

- [ ] About support services: Any potential risk to the implementation of this operation? What will be the mitigation measures? Any safety and security concerns? How will the National Society ensure the safety of the staff, volunteers and community? --> Remove
- [ ] Create new section called "Risk and security considerations", this section will have 2 questions and will be placed just before planned interventions:
> 1. [ ] Please indicate about potential operational risk for this operations and mitigation actions –->This questions will have the  bottom to “add new risk”, and when clicked, two text boxes will appear(hopefully next to each other):
>> 1. Risk
>> 2. Mitigation action
> 2. [ ] Please indicate any security and safety concerns for this operation --> Simple text box for this question

@frozenhelium  @tovari @marcovvu1

**Comment by anamariaescobar** [comment]
Helloooo!

I promise these are the last ones, they are only to add guidance to some of the fields:

- [ ] Current National Society Actions --> Add guidance "Please indicate a description of the ongoing response with **if possible**: Branches involved, number of volunteers/staff involved in actions, assets deployed/distributed, number of people reach. Impact/added value of the NS in the response already ongoing."
- [ ] Movement partners actions: IFRC --> Add guidance "Presence or not of IFRC in country (if not, indicate the cluster covering), support provided for this response, domestic coordination, technical, strategic, surge. Explain what support provided in terms of Secretariat services: PMER, Finance, Admin, HR, Security, logistics, NSD."
- [ ] Movement partners actions: ICRC --> Add guidance "Presence or not of ICRC in country, and support directly provided for this emergency response. Other programs and support provided outside of the scope of this emergency should not be indicated here."
- [ ] Other actors’ action: List major coordination mechanisms in place --> Add guidance "List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?"
- [ ] Targeting Strategy: Who will be targeted through this operation? --> Add guidance "Explain the logic behind our targets. Which groups are we targeting and why are we targeting these particular groups? Explain how you will target vulnerable groups (e.g., Migrants, refugees, etc.)"

@frozenhelium @tovari @marcovvu1

**Comment by anamariaescobar** [comment]
Hi Ankitttt, after reviewing the  changes, here all the feedback we have (looks supeeeer long, but I believe are fairly easy changes, I hope!)

- [ ] ESSENTIAL INFORMATION: Import data from existing field report--> Add an option to delete the selected Field Report in case the user select the wrong one (the little trash can that is used in other questions) **All forms**
- [ ] ESSENTIAL INFORMATION: People in need --> Move before Number of people targeted + add the word "(Optional)"at the end of the string + the little question mark should point to : [this link](https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EeXCXJDbQ3VKhl9sq9MzR8cBShIgYdb-QYzs515cRwKerA?e=eGksHF) **All forms**
- [ ] ESSENTIAL INFORMATION: Estimated people in need --> Add the word "(Optional)"at the end of the string + Add guidance: "Include all those whose physical security, basic rights, dignity, living conditions or livelihoods are threatened, and whose current level of access to basic services, goods and social protection will be inadequate to re-establish normal living conditions without additional assistance" **Imminent**
- [ ] ESSENTIAL INFORMATION: People at Risk --> Change to "Total population at risk" + Change guidance to "Includes all those whose lives and livelihoods are at risk as a direct result of the shock or stress." + add the little question mark pointing to : [this link](https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EeXCXJDbQ3VKhl9sq9MzR8cBShIgYdb-QYzs515cRwKerA?e=eGksHF)  **Imminent"
- [ ] ESSENTIAL INFORMATION: Total affected population/Total population at risk --> Change to Total affected population + add the little question mark pointing to : [this link](https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EeXCXJDbQ3VKhl9sq9MzR8cBShIgYdb-QYzs515cRwKerA?e=eGksHF) **Slow/Sudden**
- [ ] ESSENTIAL INFORMATION: Number of people targeted --> the little question mark should point to : [this link](https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EeXCXJDbQ3VKhl9sq9MzR8cBShIgYdb-QYzs515cRwKerA?e=eGksHF) **All forms**
- [ ] ESSENTIAL INFORMATION: Affected Country and Affected Region(s): Region/Province --> Should be pre.-populated from FR if listed in there. **All forms**
- [ ] ESSENTIAL INFORMATION: Upload map --> Add text box for caption **All forms**
- [ ] ESSENTIAL INFORMATION: Cover image --> Add text box for caption **All forms**
- [ ] OPERATIONAL TIMEFRAMES: This section needs to be moved to the last page, just before Tracking data and contacts + reorganize the dates in this order: first row: Date of Approval, Operation timeframe, End date of operation. Second row: Date of National Society request, Date of submission to Geneva, Date of publishing. **All forms** Date of National Society Request should ALWAYS appear, not dependent of any question **Imminent**
- [ ] OPERATIONAL TIMEFRAMES: Did the National Society started any anticipatory actions? --> This questions has to be moved to the top of the section Current National Society Actions, if yes, National Society anticipatory actions started appears. **Imminent**
- [ ] OPERATIONAL TIMEFRAMES: Date of Submission to GVA -->Add guidance "Added by Geneva" **All forms**
- [ ] OPERATIONAL TIMEFRAMES: Date of Approval -->Add guidance "Added by Geneva" **All forms**
- [ ] OPERATIONAL TIMEFRAMES: Date of Publishing -->Add guidance "Added by Regional PMER" **All forms**
- [ ] OPERATIONAL TIMEFRAMES: End date of Operation --> Add guidance "Automatically calculated using the Date of Approval + Operation timeframe" **All forms**
- [ ] OPERATIONAL TIMEFRAMES: End date of Operation --> Should be calculated using Date of Approval + Operation timeframe **All forms"
- [ ] PREVIOUS OPERATIONS: If yes, please specify which operations --> Change the "+" in the guidance for "Example:" **All forms**
- [ ] OBJECTIVE AND STRATEGY RATIONALE: Overall objective of the operation --> Remove the guidance below the question and change the guidance inside the box (only change the text in bold) "This DREF allocation aims at supporting...of **people in need** affected by.......  (leave the rest the same). **All forms**
- [ ] TOTAL TARGETED POPULATION: Estimated Number of Displaced People on the move (if any) --> Remove the word "Displaced" **All forms**
- [ ] DESCRIPTION OF THE EVENT: Date when the trigger was met --> Change to "Date of the Event" **Sudden**
- [ ] DESCRIPTION OF THE EVENT: What happened, where and when? --> is still bringing some format mistakes from the FR. **All Forms**
- [ ] DESCRIPTION OF THE EVENT: Upload photos (e.g. impact of the events, NS in the field, assessments) --> Add guidance: "Add maximum 2 photos" + make sure that we limit this. **All forms"
- [ ] CURRENT NATIONAL SOCIETY ACTIONS: Did the National Society started any anticipatory actions? --> For sudden/slow add this question renaming it to: " Has the National Society started any actions?", if yes, show "Start date of National Society actions" **Sudden/Slow"
- [ ] CURRENT NATIONAL SOCIETY ACTIONS: In the dropdown of actions, change "Shelter and basic household items" to "Shelter, housing and Settlements" + Add "Multipurpose Cash" as an option **All forms**
- [ ] NEEDS (GAPS) IDENTIFIED: In the dropdown remove "Multipurpose Cash" **All forms**
- [ ] NEEDS (GAPS) IDENTIFIED: Bring back the question "Any identified gaps/limitations in the assessment" only for Slow/Sudden **Slow/Sudden**
- [ ] NEEDS (GAPS) IDENTIFIED: Assessment Report --> Add the word "(Optional)" at the end of the string **Slow/Sudden**
- [ ] RISK AND SECURITY CONSIDERATIONS: All text boxes in this section need to be big text boxes. **All forms**
- [ ] MOVEMENT PARTNERS ACTIONS RELATED TO THE CURRENT EVENT: IFRC --> Should be pre-populated from FR **All forms**
- [ ] MOVEMENT PARTNERS ACTIONS RELATED TO THE CURRENT EVENT: ICRC --> Should be pre-populated from FR **All forms**
- [ ] TRACKING DATA AND CONTACTS: National Society contact --> Tittle and phone number are not coming through from FR. **All forms**
- [ ] TRACKING DATA AND CONTACTS: IFRC focal point for the emergency--> Tittle and phone number are not coming through from FR. **All forms**
- [ ] TRACKING DATA AND CONTACTS: Media Contact--> Tittle and phone number are not coming through from FR. **All forms**
- [ ] Remove the requirement of having a Region/Province to be able to save the form. **All forms**

Also, we are having issues saving the applications, is this because is hosted in a surge url? or there is something wrong with it?

@frozenhelium @marcovvu1 @tovari

**Comment by anamariaescobar** [comment]
Hi Ankit, as promised, here you will find the templates for the export:

- Sudden/Slow:  [DREF Request PDF Export_Sudden Slow Onset.docx](https://github.com/IFRCGo/go-frontend/files/9288279/DREF.Request.PDF.Export_Sudden.Slow.Onset.docx)

- Imminent:  [DREF Request PDF Export_Imminent Event.docx](https://github.com/IFRCGo/go-frontend/files/9288284/DREF.Request.PDF.Export_Imminent.Event.docx)

@frozenhelium @marcovvu1 @tovari

**Comment by frozenhelium** [comment]
@anamariaescobar could you please send the export templates in the PDF format, the docx format might look slightly different in our system.

**Comment by anamariaescobar** [comment]
@frozenhelium here the export templates in PDF format:

- Imminent: [DREF Request PDF Export_Imminent Event.pdf](https://github.com/IFRCGo/go-frontend/files/9298814/DREF.Request.PDF.Export_Imminent.Event.pdf)
 
- Suden/Slow: [DREF Request PDF Export_Sudden Slow Onset.pdf](https://github.com/IFRCGo/go-frontend/files/9298825/DREF.Request.PDF.Export_Sudden.Slow.Onset.pdf)

**Comment by anamariaescobar** [comment]
@frozenhelium two more changes and I promise to stop:

- [ ] DESCRIPTION OF THE EVENT: Upload any supporting documentation if relevant--> Add the word "(Optional)" at the end of the string + Move after "Explain why your National Society is acting now and what criteria is used to launch this operation." + add guidance "Here the National Society can upload documentation that substantiates their decision to launch this operation now. For example: seasonal outlooks, forecast information, reports from credible sources...etc."
- [ ] OPERATIONAL TIMEFRAMES: Date of National Society Request --> Change to "Date of National Society Application"
- [ ] ESSENTIAL INFORMATION: Upload map--> Change guidance from "Add a map highlighting the targeted areas for this operation, it will be used for the publishable document. "Add a map highlighting the targeted areas for this operation, it will be used for the publishable document." to "Add a map highlighting the targeted areas for this operation, it will be used for the publicly published DREF application."
- [ ] ESSENTIAL INFORMATION: Cover image --> Change guidance from "Upload a image for the cover page of the publishable document." to "Upload a image for the cover page of the publicly published DREF application."

**Comment by frozenhelium** [comment]
Hi @anamariaescobar @marcovvu1 We've implemented the changes and also updated the tasks above accordingly. The latest changes can be found on https://ifrc-go-project-dref.surge.sh/

**Comment by anamariaescobar** [comment]
Hi Ankitt!!

We went through the changes with Marco, and we have a couple of comments:

- [ ] ESSENTIAL INFORMATION: Region/Province: This field shouldn't be mandatory to move forward with the form. **All forms**
- [ ] ESSENTIAL INFORMATION: DREF Title: Can we go back to have this as one field (instead of 2), making it editable (without loosing the automatization of it) and remove the guidance "Add country, type of disaster and location to the title" *All forms**
- [ ] ESSENTIAL INFORMATION: Total affected population: is not pulling the data from the FR **All forms**
- [ ] ESSENTIAL INFORMATION: Total affected population: Add guidance "People Affected include all those whose lives and livelihoods have been impacted as a direct result of the shock or stress." **Slow/Sudden**
- [ ] ESSENTIAL INFORMATION: People in need (Optional): Add guidance: "People in Need (PIN) are those members whose physical security, basic rights, dignity, living conditions or livelihoods are threatened or have been disrupted, and whose current level of access to basic services, goods and social protection is inadequate to re-establish normal living conditions without additional assistance." *Slow/Sudden**
- [ ] ESSENTIAL INFORMATION: People in need (Optional): It seems this field is not being saved when we save de Application.
- [ ] DESCRIPTION OF THE EVENT: Date of the Event: Change to "Approximate date of impact", get rid of the string on top of the box. **Imminent**
- [ ] DESCRIPTION OF THE EVENT: Upload any supporting documentation if relevant (Optional): I can't seem to be able to attached any documents in this field. Realized we didn't discussed what documents should be able to be uploaded here, should be Word and PDF. **Imminent**
- [ ] OBJECTIVE AND STRATEGY RATIONALE: Response strategy rationale: Change this to "Operation strategy rationale" **All forms**
- [ ] TOTAL TARGETED POPULATION: Numbers of persons targeted with early actions --> Add (if any) to the end of the string. **Imminent**
- [ ] NEEDS (GAPS) IDENTIFIED: Assessment Report (Optional) --> Preview not available! can we have a general document icon instead of this message?
- [ ]  OPERATIONAL TIMEFRAMES: Reorganize the dates in this order: first row: Date of National Society request, Date of submission to Geneva, Date of Approval. Second row: Operation timeframe, End date of operation, Date of publishing. Sorry, this ordering was totally my fault!

@frozenhelium @marcovvu1 @tovari

**Comment by anamariaescobar** [comment]
Hi Ankit!

These are the requirements for the DREF for assessment:

- [ ] ESSENTIAL INFORMATION --> Add a yes /no question below "Name of National Society", if yes is selected the following changes will happen to the form.
- [ ] PREVIOUS OPERATIONS --> Hide the whole section
- [ ] DESCRIPTION OF THE EVENT --> Hide “Scope and Scale” field
- [ ] NEEDS (GAPS) IDENTIFIED --> Hide all this section
- [ ] TOTAL TARGETED POPULATION --> Hide “Women”, “Men”, “Girls (under 18)” and “Boys (under 18)” fields
- [ ] ABOUT SUPPORT SERVICES --> Hide “If there is procurement, will it be done by National Society or IFRC?” field, Hide “How will this operation be monitored?” field and  Hide “Please briefly explain the National Societies communication strategy for this operation.” field.
- [ ] OBJECTIVE AND STRATEGY RATIONALE-->  below the field “Response strategy rationale” add the following guidance: Please describe the strategy to conduct the assessment exercise, main objectives, who will be involved? 
- [ ] When for assessment is selected, and “Type of onset” us sudden, limited the number of months in the field “Operation timeframe” to “2”
- [ ] RISK AND SECURITY CONSIDERATIONS, below the field “Please indicate about potential operational risk for this operations and mitigation actions” add the following guidance: “Please consider any possible challenges to conduct the assessment, any possible limitations in getting the information required and overall risk to the implementation”.
- [ ] Operations Update should have the functionality to bring back all the field above that have been hidden so that they can complete them with information from assessment.

@frozenhelium @marcovvu1 @tovari

**Comment by anamariaescobar** [comment]
Hey Ankit, thanks for the update, it looks great, a couple of comments:

- [ ] ESSENTIAL INFORMATION: DREF Title --> make this field completely editable (while maintaining the automation), it shouldn't be required to add or change text (unless the user wants to) to submit
- [ ] ESSENTIAL INFORMATION: At Risk Country and Region(s): Region/Province --> Should not be required to save the application
- [ ] ESSENTIAL INFORMATION: Total affected population --> Is not transferring from Field Report.
- [ ] DESCRIPTION OF THE EVENT: Date when the trigger was met --> Change to "Date of the event" **Only for Sudden**
- [ ] TOTAL TARGETED POPULATION: Eliminate the logic that the of Women+Man+Girls (under 18)=Total Population **Only for DREF for Assessment** as we are hiding these fields and it is preventing us to save the Application
- [ ] On the Account page, under My DREF application, the export button doesn't seem to work.
- [ ] On the Account page, under My DREF application, under name, can we bring the complete DREF tittle? (including country and date?

@frozenhelium @marcovvu1 @tovari

**Comment by anamariaescobar** [comment]
As discussed, some changes for the Export **this changes are for all the forms exports**

- [ ] In Risk and Security Considerations “Mitigation Measures” is appearing as “Mitigation Meas”, the title should be equal to the title field in the application, "Mitigation action".
- [ ] In “About Support Services”, The only fields that are appearing is “How many staff and volunteers will be involved in this operation. Briefly describe their role" and "Will surge personnel be deployed? Please provide the role profile needed", even if the other 3 fields in this section have text ("If there is procurement, will it be done by National Society or IFRC?", "How will this operation be monitored?" and "Please briefly explain the National Societies communication strategy for this operation." All fields should only not appear if they haven't been filled.
- [ ] In “Budget Overview”, the imported PDF one pager is too small, this section should take a full page.
- [ ] In “Description of the Event”, the section “What happened, where and when” appears to down in page two, and not at the start of the page (see the export attached) [MDRIQ015 Iraq Cholera.pdf](https://github.com/IFRCGo/go-frontend/files/9402131/MDRIQ015.Iraq.Cholera.pdf)
- [ ] In “What happened, where and when?” The text should be justified, and not aligned to left
- [ ] In “Scope and Scale” The text should be justified, and not aligned to left
- [ ] In “Contact Information”, change to red the color of the title of the fields (e.g. National Society Contact)
- [ ] In “Budget Overview”, the imported PDF one pager is too small, this section should take a full page, with a break with “Contact information”
- [ ] In “Current National Society Actions”, “Movement Partners Actions Related To The Current Event”, “Other Actors Actions Related To The Current Event” and “Planned interventions”, the titles in the left column of the table change it to “aligned to left” instead of “aligned to right”
- [ ] Add a page break at the end of the the Needs (Gaps) Identified whole section
- [ ] For “Overall objective of the operation” and "Operation strategy rationale", change them to Montserrat font 12 bold in red + add a title “Operational Strategy”, with font 20 Montserrat, bold in blue.
- [ ] Can we change the naming convention of the resulting PDF (once is downloaded), right now is a random mixture of letters and numbers. Can we change it to: MDRXXX+DREF tittle (if not MDR is input yet, only the DREF tittle)

- [ ] **THIS ONE IS NOT RELATED WITH THE EXPORT, BUT WITH A BUG WE HAVE IDENTIFIED**: When submitting any kind of application, it seems the fields for "Please indicate about potential operational risk for this operations and mitigation actions" (both "Risk" and "Mitigation action") have a very small limit of characters and is not allowing us to save the Application if the text is longer than a sentence here. Also, the error message coming from this pops up on the "Actions/Needs" page and not on the "Operation" one where Risk fields are. After removing or shortening the text inside this fields, the error goes away and we are able to save the application.

@frozenhelium @marcovvu1 @tovari

**Comment by frozenhelium** [comment]
Hi @anamariaescobar, we've updated the [testing instance](https://ifrc-go-project-dref.surge.sh/). A couple of thing to note is:
- We've added a button to generate the title (on the right side of title input) so that the manually edited title doesn't conflict when user changes the related fields.
- For total affected population we've used the field `Affected` from the `Situation` tab when the `Status` is selected as `Event` in the `Context` tab

**Comment by anamariaescobar** [comment]
Hi @frozenhelium, the changes look great! I am attaching here the export template for the DREF for Assessment.

[DREF Request PDF Export_Assessment.docx](https://github.com/IFRCGo/go-frontend/files/9476961/DREF.Request.PDF.Export_Assessment.docx)

**Comment by anamariaescobar** [comment]
Hey Ankit!!

Here the changes for the Ops. Update:

- [ ] Bring the Sharing field
- [ ] ESSENTIAL INFORMATION: Copy the structure and guidance from the Application (Adding the map field and captions + keeping the extra fields "Additional Allocation Requested" "Operational Update Number")
- [ ] TIMEFRAMES: Copy the structure of the Application. No information in this section should be transferred from the Application
- [ ] CURRENT NATIONAL SOCIETY ACTIONS: Copy structure of the Application (removing "Has the National Society started any actions?" and "Start date of National Society actions")
- [ ] MOVEMENT PARTNERS: Copy guidance from the application
- [ ] OTHER ACTORS ACTIONS RELATED TO THE CURRENT EVENT: Copy structure of Application
- [ ] NEEDS (GAPS) IDENTIFIED: Copy structure of Application
- [ ] TARGETING STRATEGY: Copy structure of Application
- [ ] TARGETED POPULATION: Copy structure of Application
- [ ] Add the Risk section
- [ ] Add About support services section
- [ ] Re-organize all the sections to match the Application
- [ ] SUMMARY OF CHANGES: can we make this section a new point on the top?
- [ ] SUMMARY OF CHANGES: Are you changing the timeframe of the operation --> add some logic around this question so it is linked to the operation timeframe in this form and in the Application, if these two are different an error message should appear.
- [ ] SUMMARY OF CHANGES: Are you changing the target population of the operation --> add some logic around this question so it is linked to the people targeted in this form and in the Application, if these two are different an error message should appear.
- [ ] SUMMARY OF CHANGES: Are you changing the geographical location --> add some logic around this question so it is linked to the region/province in this form and in the Application, if these two are different an error message should appear.
- [ ] SUMMARY OF CHANGES: Is this a request for a second allocation --> add some logic around this question so it is linked to the Additional Allocation Requested in this form.

@marcovvu1 @tovari @frozenhelium

**Comment by anamariaescobar** [comment]
One additional change for the Ops Update:

- [ ] SUMMARY OF CHANGES: Add a question "Has the forecasted event materialize? Yes/No" If yes, add the field "Please explain how is the operation is transitioning from Anticipatory to Response" long text + guidance "Explain on whether the specified triggers have been met, and if the event has materialized either as forecasted or if there were any differences. Also please provide an update on the readiness, prepositioning and/or early actions implemented so far" **This is only for Imminent event**

@frozenhelium

**Comment by tovari** [comment]
Marco discovered a bug eith the export:

- [ ] When exporting directly from the application, and when exporting from the My DREF tabs, the order of the sectors in the document changes

- [ ] And an additional request to provide view/export permissions for each DREF to all superusers.

**Comment by anamariaescobar** [comment]
A couple of things we need to fix from the import:

- [ ] CURRENT NATIONAL SOCIETY ACTIONS --> Information is not transferring from the Assessment template **Assessment**
- [ ] MOVEMENT PARTNERS: Participating National Societies --> Information is not transferring, should link to PNS field. **All forms**
- [ ] ESSENTIAL INFORMATION: Number of people targeted --> Information not transferring from template. **All forms**
- [ ] PLANNED INTERVENTION: List of Activities --> Information not transferring from template. **All forms**
- [ ] ABOUT SUPPORT SERVICES: How many staff and volunteers will be involved in this operation. Briefly describe their role.--> Information not transferring from template **All forms**
- [ ] RISK AND SECURITY CONSIDERATIONS: Please indicate about potential operational risk for this operations and mitigation actions --> the information from "Please indicate any security and safety concerns for this operation" is being transferred as a new risk.
- [ ] OPERATIONAL TIMEFRAMES: Date of Approval--> this field shouldn't be transferred from template.
- [ ] DESCRIPTION OF THE EVENT: Date when the trigger was met --> this field should be transferred from template. **Slow**
- [ ] DESCRIPTION OF THE EVENT: Date of the Event --> this field should be transferred from template. **Sudden**

@frozenhelium @tovari @marcovvu1

**Comment by anamariaescobar** [comment]
Hi Ankit!!

All the changes look really good for the import! for the 2 you couldn't reproduce:

- CURRENT NATIONAL SOCIETY ACTIONS --> Information is not transferring from the Assessment template Assessment **I checked and this one is not importing only for the Assessment template**
- RISK AND SECURITY CONSIDERATIONS: Please indicate about potential operational risk for this operations and mitigation actions --> the information from "Please indicate any security and safety concerns for this operation" is being transferred as a new risk. **I tested all of the imports and I still get the issue, see the image below**
![image](https://user-images.githubusercontent.com/69478743/202161152-db2c333f-20c3-4857-8b9f-b4aa78c7a144.png)

We can have a call if you can't reproduce this issue (I used the templates I sent you on friday)

@frozenhelium @tovari  :)

**Comment by frozenhelium** [comment]
Thanks @anamariaescobar will take a look again! :)

**Comment by frozenhelium** [comment]
@anamariaescobar both should be fixed now and is deployed to the staging.

**Comment by anamariaescobar** [comment]
Just tested it, and looks great! all the import changes are working perfectly! 

Thanks @frozenhelium !! @tovari

**Comment by anamariaescobar** [comment]
Hey Ankit! Thanks for the changes! I have reviewed everything on the Ops. Update and I just have a few comments.:

- [ ] OPERATIONAL TIMEFRAMES: Operation timeframe --> it is being limited to 2 months when assessment is selected, let's remove this (this is on the Application, not on the ops update)
- [ ] Remove empty fields from the export (Ops Update)
- [ ] Remove priority actions (Planned interventions) only on the export of the ops update (still keep it on the form) (Ops Update)
- [ ] Include the "Actual" field from the planned interventions on the export (Ops Update)

The rest looks great! Thank you!!

@frozenhelium @tovari @marcovvu1
