### ISSUE TITLE
Country plans (formerly 'Annual plans') integration

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2435]
Annual plans, or ‘Country plans’ are planned to be published as pdf documents on GO with a very simple integration. Admins shall be able to upload the pdf-s on the admin page and add the key figures manually there. On the GO UI, they will appear on a new tab of the country pages as shown in the design below.
A sample document is attached.
wireframes:
https://www.figma.com/proto/uRgMamNHRi5KhhroYDwuxN/IFRC-GO---Wireframes?page-id=0%3A72&node-id=104%3A11879&viewport=274%2C48%2C0.11&scaling=scale-down-width&starting-point-node-id=111%3A0&hide-ui=1

Design (needs to be updates):
https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=8706%3A142928

- key values, strategic priorities, membership coordination

[Master_UP2023-import_template-draft.xlsx](https://github.com/IFRCGo/go-frontend/files/9927482/Master_UP2023-import_template-draft.xlsx)

 can be added and edited manually on the admin page
- no automatic data import from the pdf
- Targeted people and Funding data shall be imported from an Excel sheet (attached)
- data update on the admin site, where users will be able to edit the data and upload the pdf files

**Comment by tovari** [comment]
This is an updated version of the import file with Total funding requirement (Column BX):

[Master_UP2023.xlsx](https://github.com/IFRCGo/go-frontend/files/10000825/Master_UP2023.xlsx)

**Comment by udaynwa** [comment]
Hey @tovari , I am not able to open the xlsx file you attached in the above comment. 
![image](https://user-images.githubusercontent.com/72339626/201614660-4bbc7e78-f274-4879-a5c1-2383ddebaabd.png)

**Comment by tovari** [comment]
Sorry, the permissions are restrictive on this file. I made an extarct with the data of some countries.

[Master_UP2023-extract.xlsx](https://github.com/IFRCGo/go-frontend/files/10002112/Master_UP2023-extract.xlsx)

**Comment by tovari** [comment]
@frozenhelium, @udaynwa, I have shared the latest and final (for this year) version of the import file here:
https://ifrcorg.sharepoint.com/:x:/s/GOIVfordeveloperteam/Ebz131EJlxVKuA4EEtWo7M4BUuF64WKxg0QGAS7QEq34bQ?e=d8tIfW

Please use the
Funding REQ_2023 worksheet.
It has a Total Funding requirement column (AV).

**Comment by Rup-Narayan-Rajbanshi** [comment]
> 

@tovari , could not excess the file, its asking for microsoft login.

**Comment by tovari** [comment]
Nice work Team! Thanks!

One more thing needs to be implemented_
- 'Ongoing emergencies' line needs to be added to the Strategic priorities table.

**Comment by frozenhelium** [comment]
@tovari we can close this issue, right?
