### ISSUE TITLE
Improve access control for regional and country editors

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#244]

**Comment by LionelDenis001** [comment]
Think about RBAC - Role based Access Control
A Role should contain multiple "Security application access functions" (autorisation / access list).
A person is attached to one or multiple Roles.
A person should never be directly link to an access functions. 
Therefore, the integration with other systems such as ERP, Finance system and so on , is based on Role.
For instance, myself as Lionel (Person), I could have the role "Information Manager" Role on FDRS, the ERP and GO.
In the future (2018), when IFRC will have a "Federated Identity Management (IDaaS project), the Identity and related Roles will be managed by this new product. However, the access control will be managed by each application.

**Comment by dereklieu** [comment]
Waiting on IM team discussion for specific roles and permissions.

**Comment by dereklieu** [comment]
![photo jun 20 9 42 04 am](https://user-images.githubusercontent.com/1590802/41644437-51d91944-746e-11e8-85bd-38fb54650838.jpg)

**Comment by dereklieu** [comment]
Users can be restricted to one or multiple countries, and one or multiple regions. This can be combined with other user role definitions to create any of the combinations outlined in the picture above.
