### ISSUE TITLE
Search bar not functioning

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#248]
## Issue

The search bar function doesn't seem to work.  For instance, entering "Ebola" does not bring any results. 

## Steps to reproduce

Entering "Ebola" in search bar.  No results or site action to explain no results. 

## Expected behavior

Search bar should provide nearest match term, with preference given to most prominent and/or useful (in the sense of providing an overview or links) pages.  There could also be a way to filter the search based on wish to see emergency, deployment or country/region information.  The result of the search should be clean and intuitive so that not all the pages with Ebola are pulled, but rather the 'landing page' for the most recent Ebola emergency outbreak.  

More aspirationally, it may be useful to have some tracking/AI here to understand and adapt search results based on following behaviour, in order to continually improve the results.

**Comment by dereklieu** [comment]
Hey @LukeCaley the elasticsearch instance had become unresponsive. I just re-started it and it's functioning again. I've also re-run the index and confirmed that the Ebola outbreak in question has been indexed. However I agree we can do a much better job surfacing the results you'd expect. Right now the recent Ebola outbreak doesn't show up when you enter Ebola. 

A few approaches to address this:

1. Better monitoring and notifications when the elasticsearch instance becomes unresponsive.
2. Give more weight to more recent events and operations.
