### ISSUE TITLE
[PROD] Risk Watch: Imminent Events in Region showing events not in Region

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2489]
## Steps to reproduce

 - Go to Africa Risk Watch page: https://go.ifrc.org/regions/0#risk-watch
 - First event in the list is an Earthquake in Japan, which is not in Africa.

Expected:

 - I would expect to only see events within the region selected.

Am not sure whether this is on purpose for some reason, but it feels like a bug. Feel free to close if its a known issue or intentional.

cc @frozenhelium @justinginnetti @tovari

**Comment by tovari** [comment]
done
