### ISSUE TITLE
Add the frontend version number in the footer of the application

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#2490]
Could we add the version of the frontend app to the footer and encourage people who open tickets to use this in their reports?

![image](https://user-images.githubusercontent.com/371666/191166407-295ba312-175c-450e-8685-f6906af4ce0f.png)

cc @batpad @szabozoltan69 @frozenhelium @thenav56 @tnagorra @tovari

**Comment by tnagorra** [comment]
We should discuss if we want a semantic versioning on the client application or use the latest commit hash when building the client application.

**Comment by szabozoltan69** [comment]
I suggest the first 8 characters of the latest commit hash, like a95e30bd. It is short enough, not too attractive (does not catch visual focus at the bottom), and automatically generated. Nobody has to find out a nice, verbose name for the version.
(This is the same what we get via `git log --pretty=format:"%C(yellow)%h"`)

**Comment by szabozoltan69** [comment]
https://dev.to/nastassia/add-commit-hash-version-to-your-react-app-n3n can be useful

**Comment by szabozoltan69** [comment]
I wonder how to set this git commit hash in the Azure pipeline deployment.  @frozenhelium @tnagorra ?

**Comment by tnagorra** [comment]
We generally pass the git commit hash during build using a [webpack plugin](https://www.npmjs.com/package/git-revision-webpack-plugin) so that it is accessible in `process.env`

**Comment by szabozoltan69** [comment]
I could not install that plugin via "npm install --save-dev git-revision-webpack-plugin" with node v14.18.2, gave conflicts:
`Object for dependency "file-saver" is empty
`

**Comment by szabozoltan69** [comment]
Deployed to Staging.
Works ONLY with node 14.18.

**Comment by szabozoltan69** [comment]
![image](https://user-images.githubusercontent.com/6050643/220191216-3f1c194f-4e3e-484c-9fde-f3a55211aa36.png)

**Comment by tnagorra** [comment]
It shouldn't be much of a problem, as 18.14.1 is the latest LTS release for node
https://nodejs.org/en/

**Comment by szabozoltan69** [comment]
Solved with the hint of @batpad – thanks.
See https://github.com/IFRCGo/go-frontend/pull/2651 - now it can be used with node 18.14.1 also.
