### ISSUE TITLE
Clean-up and make Frontend Tables consistent

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2491]
Currently, quite a few of our tables use this pretty terrible (imo) structure to render tables, for example: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/alerts-table.js using this `SFPComponent` stuff: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/extendables.js#L22

This structure has been horribly hard to customize / move the filters out of the column headers, etc.

Tables developed more recently use a much nicer structure. We should move over all the older tables to the new Table structure to bring them into a uniform structure and allow us to much easier iterate on UX and features across tables on the site. These are the existing tables using the old structure: https://github.com/IFRCGo/go-frontend/tree/develop/src/root/components/connected

@frozenhelium it would be great to get your thoughts / clearer direction here on what we can do. I think this might be a good / required first step before we can move the older `views` to the newer architecture patterns.

cc @tnagorra @szabozoltan69 @frozenhelium @tovari

**Comment by frozenhelium** [comment]
@batpad Completely agreed that we should have a bit simpler approach to build / render tables. Lets list out all the requirements for the table and we can tweak the latest table component to fulfill all those needs and simplify the overall development & maintenance task for tables and also makes it consistent.

The features that comes to my mind right away are:
- Server Side Pagination
- Filtering
- Sorting
- Responsive?
