### ISSUE TITLE
Having country "result" at once in search bar

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2492]
There is a complaint for having too much time until the search results appear, even when searching for countries.

The country pages mean 192 pages. We could have these 192 links in frontend literal memory and if the searched string matches some/one of these, we display them at once, and then, when in 1-2 seconds the other results arrive, we put them after these.

So the user can have the experience of "typing 3 letters" of a country and at once there is a result of the country page, and if the user has a bit more patience, the others also appear below.

@mariam-yu @frozenhelium

**Comment by szabozoltan69** [comment]
Let's use useReduxState('countries')
And maybe we could showing that collecting results are in progress.

**Comment by szabozoltan69** [comment]
@frozenhelium @tnagorra @batpad 
I would like to ask some help in this topic.
Where to put the "fixed country list"?
I tried this way: replacing this row: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/utils.js#L429
with some fixed thing, now (for simplicity) let's use this only:
```
      const fixes = [{ value: "/countries/14", label: "Country: Afghanistan" }];
      callback(fixes.concat(options));
```
But this does not help, because the callback gives back the answer when the whole options list is arrived.
How could we have a "quick" result? Maybe somewhere https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/navbar.js#L50 here where getElasticSearchOptions is called?

**Comment by szabozoltan69** [comment]
@frozenhelium @tnagorra @batpad 
I would like to ask some help in this topic.
Where to put the "fixed country list"?
I tried this way: replacing this row: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/utils.js#L429
with some fixed thing, now (for simplicity) let's use this only:
```
      const fixes = [{ value: "/countries/14", label: "Country: Afghanistan" }];
      callback(fixes.concat(options));
```
But this does not help, because the callback gives back the answer when the whole options list is arrived.
How could we have a "quick" result? Maybe somewhere https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/navbar.js#L50 here where getElasticSearchOptions is called? Or can we use an other condition instead of request...then(), some kind of ...else (in the case where the "then" is not yet actual)?

**Comment by szabozoltan69** [comment]
We can find an other solution, in the next release :-) – but then we should implement some logic also with it, which is not straightforward. E.g. the 'United Arab Emirates' can be found now with 'un', 'ar', or with 'em'. But this rule (beginning of words) is not always works, because there are a lot of "Republic..."-s or "Kingdom..."-s).
And there are other tricks like "us" -> United States, "uk" -> United Kingdom. "co" and "cô" should be also usable for Côte d'Ivoire... So, for now, it seemed to be the more simple way to create this collection semi-programmaticaly to have a relevant search possibility. Let's consider it as an example.

My harder question is to have a better solution instead of this: 2 letters -> wired in list, 3 letters -> ElasticSearch.
Instead of this, we would like to know that "the answer still not arrived, in the meantime we show this fixed list".

**Comment by batpad** [comment]
@szabozoltan69 I believe you are over-thinking this. I would vote for just doing a simple substring match.

so something like:

```
/**
* @param {String} searchTerm - string being searched by user - eg. "us"
* @param {Array} countries - array of countries with something like `{"name": "United States"}`
* @returns {Array} returns countries whose name matches searchTerm
*/
function matchTerm(searchTerm, countries) {
  return countries.filter(country => {
    return country.name.toLowerCase().indexOf(searchTerm.toLowerCase()) !== -1;
  });
}
```

This should work for the majority of use-cases. Agreed, there are several edge cases that we should think about more deeply, but I don't think hard-coding these values on the frontend is the way to do it. I would strongly advocate for just doing the substring matching for now, and doing a better solution if needed by:

 - Adding a "Search terms" field to the Country model, so then users can add many alternate names for a country, that will not display, but be used in the search. That way it will be updateable in the admin and we will maintain a single source of truth -- we won't need to change frontend code if the name of a country changes, etc.

I am really uncomfortable having this hard-coded stuff on the front-end and would advocate for moving to a substring search very strongly, even if we don't hit some "fancy" use cases, and then ticket out what solving this by adding alternate names in the backend would look like.

Whilst saying all this: the countries appearing immediately as you type is REALLY COOL - really good work on this @szabozoltan69 !

**Comment by szabozoltan69** [comment]
Thanks so much @batpad for thinking it over deeply!
Recently the elasticSearch searches only in beginning of words (so not every substrings). So India can not be found via "ndi".

I am really open to solve this issue without (hardly maintainable) wired-in stuffs. Maybe we should read the countries to some storage (or use  useReduxState('countries')), then optionally make some exeptions based on backend data to work (us -> United State, co -> Côte d'Ivoire). Then enjoy. :-)

But I think the user experience will be better if we do it somehow else, not this 2Chars/moreChars way.

**Comment by batpad** [comment]
> But I think the user experience will be better if we do it somehow else, not this 2Chars/moreChars way.

I definitely think we can solve the 2chars / more chars issue separately by finding a good way to "merge" the results from user typing and ElasticSearch. But let's deal with that separately. Maybe we can get on a call or so to go through this one, also to make sure I've understood the issue properly?

> Recently the elasticSearch searches only in beginning of words (so not every substrings). So India can not be found via "ndi".

Hmm we could change the substring to a `startsWith` or so in the code above, if that seems better. Point being to just use a simple logic to start that mirrors what's there in the database, and then we can try and solve for exceptions later.

> Maybe we should read the countries to some storage (or use useReduxState('countries')), then optionally make some exeptions based on backend data to work (us -> United State, co -> Côte d'Ivoire). Then enjoy. :-)

Yes. I would rather even not hard-code these exceptions on the frontend but find a good way to add these as fields in the database, but, if we need to hard-code a few exceptions on the frontend, that is definitely MUCH better than having this entire list hard-coded.

**Comment by szabozoltan69** [comment]
Thanks to @batpad for the final, nice version!
