### ISSUE TITLE
[PROD] Emergency 3W: Change status text option to proper spelling

### ISSUE THREAD

**Issue by ryales** [IFRCGo/go-frontend#2502]
## Issue
The options for Status field on the Emergency 3W (On-Going, Complete, Planned) need to be updated as "On-Going" is not the correct spelling. It is "Ongoing".

## Steps to reproduce
![image](https://user-images.githubusercontent.com/4562153/191696411-33321e1e-247f-4074-b7fd-1b441aff1ac9.png)
[https://go.ifrc.org/emergency/6183#activities](https://go.ifrc.org/emergency/6183#activities)
[https://goadmin.ifrc.org/en/deployments/emergencyproject/121/](https://goadmin.ifrc.org/en/deployments/emergencyproject/121/)

## Expected behaviour
"On-Going" should change to "Ongoing"

## Impact
Cosmetic text string, impacts all users but not functionality.

## Severity
Minimal impact

## Is there a workaround?
No

**Comment by szabozoltan69** [comment]
Deployed to Staging.

**Comment by szabozoltan69** [comment]
Deployed to Staging. (Needed backend and frontend changes also.)

**Comment by szabozoltan69** [comment]
Can be tested on https://go-stage.ifrc.org/emergencies/4422#activities or on https://dsgocdnapi.azureedge.net/en/deployments/emergencyproject/43
