### ISSUE TITLE
DREF Ops Update improvements[PROD] 

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2516]
Some changes needed for the DREF Ops Update:

- [x] ESSENTIAL INFORMATION: Is this the DREF for assessment? -->Data should be transferred from the Application
- [x] ESSENTIAL INFORMATION: People in need (Optional) --> This field is missing in the Ops Update
- [x] SUMMARY OF CHANGES: Are you making changes to the budget--> This question should be connected to "Additional Allocation Requested" (if Additional allocation requested is 0, the answer has to be yes), add error message
- [x] DESCRIPTION OF THE EVENT: Date of the Event --> This field is missing from the Ops Update
- [x] DESCRIPTION OF THE EVENT: Has anything changed in the context since the request --> Remove this question
- [x] CURRENT NATIONAL SOCIETY ACTIONS: Guidance below the tittle is missing. "Please indicate a description of the ongoing response with if possible: Branches involved, number of volunteers/staff involved in actions, assets deployed/distributed, number of people reach. Impact/added value of the NS in the response already ongoing."
- [x] CURRENT NATIONAL SOCIETY ACTIONS: Has the National Society started any actions? --> Missing from Ops Update (data must transfer from Application)
- [x] CURRENT NATIONAL SOCIETY ACTIONS: Start date of National Society actions --> Missing from Ops Update (data must transfer from Application)
- [x] OTHER ACTORS ACTIONS RELATED TO THE CURRENT EVENT: Are there major coordination mechanisms in place? --> Data must transfer from application
- [x] TARGETED POPULATION: Total Population--> Field is missing from Ops Update
- [x] ABOUT SUPPORT SERVICES: The whole section is not transferring the information from the Application
- [x] TIMEFRAMES: Operation start Date --> Should be transferred from Application, from the field "Date of Approval" and the user shouldn't be able to edit it, but we still want to show it
- [x] TIMEFRAMES: Re-organize the dates in this order: First line: Operation start date, Total operating timeframe, New operational end date. Second line: Reporting timeframe
- [x] TIMEFRAMES: New operational end date --> Calculate this field with the Operation start date + total operating timeframe and select the last day of the resulting month (just as in the application)
- [x] TIMEFRAMES:  New operational end date --> Automatically calculated using the Operation start date + Total operating timeframe
- [x] TIMEFRAMES: Reporting timeframe --> it should be a range, so we need two date boxes (from date to date)
- [x] TRACKING DATA AND CONTACTS: MDR Code --> make this field not editable for the user, but still visible
- [x] NEEDS (Top section) --> Rename to "ACTIONS/NEEDS"
- [x] UPDATE ON INTERVENTION: Alert that in planned interventions the sums of the budgets don’t match total budget
- [x] DESCRIPTION OF THE EVENT: Add a question "Has the event occurred?" Yes/No question **Only for Imminent**
- [ ] In the export, the pictures uploaded under CURRENT NATIONAL SOCIETY ACTIONS don't appear.

Also, some functionality bugs we need to fix:

- [x] If there is no Field Report associated with the Application, we can't make any changes on the backend
- [x] We need a download button in the Application for the Attachments (Assessment report and budget template)

@tovari @frozenhelium @marcovvu1

**Comment by frozenhelium** [comment]
- [ ] Add download links for uploaded Assessment Report, Budget Template & Documentation in the DREF edit form
