### ISSUE TITLE
Prevent users from over-writing concurrent DREF form edits

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2517]
While this ticket is for the specific issue with DREF forms, any solution we implement should ideally be generalizable to other forms on the platform.

### The Problem

User A opens up a DREF form to edit. User B opens up the same form after some time. User B makes many extensive edits to the form and saves it. User A makes some small edits to the form and saves it after User B. User A's changes thus over-write all of User B's changes. Currently, there is no warning to the user or anything that the form has been saved after they fetched it.

### Approaches to solving

There are likely many approaches to this problem - let me list down some possible approaches, and then we can try and figure out the most practical way forward:

 - **Explicit Locking** - when User A starts editing the form, the system "Locks" the form to be editable only by User A for some period of time, say 30 minutes. We will need to explicitly communicate this to the user - i.e. that they have a lock on the form, allow them to clear the lock, extend the lock, etc. If another user tries to edit the form while there is an active lock on it, it just informs that user who has the form locked, and they can contact the person if needed, etc.
 - **Optimistic Locking(?)** - In the example above, User B would still be allowed to start editing the form and save it. User A, when saving, would get a message informing them that the form has changes since they started editing it. They would then need to be given a choice to retain their changes and over-write other changes, or discard their changes. This could get more complex with showing them "what changed" and allow users to apply changes selectively, but this would involve increased complexity.
 - **Offline coordination**: We largely ignore this problem on the website itself, but just add some UI to let people know that they need to coordinate with their peers to make sure forms are not edited at the same time. We could implement something really lightweight that just gives a notification to the user if there is another user who starts editing the form at the same time - this would take some engineering work, but can likely be implemented a lot easier than any sort of automatic merging mechanism.
 - **Collaborative Editing**: Implement collaborative editing and sync all changes that anyone is making on the form in real-time. This potentially kills two birds with one stone, as it allows people to work collaboratively on the form, hopefully reducing the need for external applications like MS Word. This would likely involve the most engineering work, but having a re-usable mechanism to do this would likely benefit other current and future forms on the platform. @frozenhelium @tnagorra @thenav56 - how do you feel about this? I'd imagine this as a separate websocket server that ONLY handles syncing data between connected clients - so all users editing the same form are connected to the same websocket channel, which receives and publishes changes made by any connected client to the other clients, which apply them to the relevant form fields. I feel okay about the websocket server bit - I'm just not sure how crazy it would be to implement this on the frontend form library, etc. Feel free to completely shut me down here -- but I'd be very interesting in at least scoping out what this would take to do.

### Way Forward

Let's discuss this at the next Dev meeting, but I feel the simplest solution to start is the **Offline Coordination** proposed above. I think what I'd recommend is:

 - When a user opens the form to edit, we store the username and timestamp in the database.
 - When another user opens the form, if there is another user who opened the form in say, the past 60 minutes, we let them know that User X may also be editing the form and they can contact them if they need to.
 - When a user saves the form, we also record username and timestamp.
 - All clients poll a backend end-point which informs them if another user has started editing the form, OR saved data while they are editing. If either is the case, they get a notification with the username who has started editing or saved, and they can coordinate with them directly.

In addition to this, we just add some text to the top of the form maybe asking users to be in touch with other people who might be editing the form, or something to the effect.

There could be other creative solutions here, so would definitely welcome any other ideas. In the medium-term, I like the idea of implementing collaborative editing, but I can definitely see there are likely rabbit holes there that I am likely underestimating.

cc @szabozoltan69 @tovari @anamariaescobar @frozenhelium

**Comment by frozenhelium** [comment]
Thank you very much @batpad for the very detailed description and solutions. Given the current situation, I think *Optimistic Locking* is way to go. Let's discuss this further during the dev call!

**Comment by szabozoltan69** [comment]
@frozenhelium @batpad Some notes of the discussion:
Let's define version number on server side for the form.
Once the user loads into the client, user sees that version number.
Save: increases it by 1.
Server checks: if the one is lower, then somebody has not already saved.
Let's display: it is already edited, if you save it, you overwrite someone else's work (maybe with the username of other other editing user?).
