### ISSUE TITLE
[PROD] Increase Ops Toolbox svgBody height

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-frontend#2521]
## Issue
[Operational Toolbox](https://go.ifrc.org/deployments/operational-toolbox) timeline does not fit into the page causing some users to miss over half of the content - there are two vertical scroll bars the user has to navigate:

![image](https://user-images.githubusercontent.com/15220593/195119983-ef503fea-ce4d-45f3-b05c-607e024653c1.png)

## Expected behaviour
The timeline should have enough height so that there's no vertical scroll bar for the timeline content within the page. 

Probable fix: change the height of the following style in `_operationalTimeline.scss` to 1834px:

```
.operationalTimelineContainer .svgBody {
    height: 800px; 

```
## Impact
Every user who looks at the Operational Toolbox, especially the ones who do not realise there are two scroll bars they have to control to access the bottom part of the Toolbox.

## Severity
Minor

## Is there a workaround?
N/A

**Comment by szabozoltan69** [comment]
I am so grateful for this kind of bug reports!
Small effort, big win.

I found that **height: 100%** will be fine, otherwise (with a fixed value) the screen size has effect of the wanted number. (For my bigger screen 2700px was the usable value, for the smaller screen a smaller value.)

**Comment by szabozoltan69** [comment]
Hotfix deployed to prod. Staging will also be deployed soon.
