### ISSUE TITLE
[PROD] Incorrect mailto links on Ops Toolbox

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-frontend#2525]
## Issue
Mailto-hyperlinks for Antoine Belair and Betisa Egea under the Operational Toolbox timeline graphic have a wrong domain (UI shows correct address, but the mailto-hyperlink is incorrect). 

## Expected behaviour
...@ifrc.go should be ...@ifrc.org

**Comment by szabozoltan69** [comment]
I fix it now.
