### ISSUE TITLE
Show "Be patient" at DREF export button

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2538]
Sometimes DREF export takes 6-8-10 seconds. We could put a "Be patient" sign (popup/label) somewhere, so that the user should not think it did not work. Just needs some time until it gets done.

@anamariaescobar @frozenhelium – any ideas?

**Comment by szabozoltan69** [comment]
Maybe there are some other issues concerning this topic also:
https://porgeto.hu/tmp/blobNotFound.txt
Maybe the PDF export needs some pictures (blobs) which are not on the place that they are expected to be?
(Or the user had no permission to them?)

**Comment by frozenhelium** [comment]
@szabozoltan69 thanks for putting it together, will take a look into it

**Comment by szabozoltan69** [comment]
(It turned out that the BlobNotFound issue is independent from the export issue, at least that is another (VietNam) DREF one, which does not like to be exported.)
