### ISSUE TITLE
Account page - Notifications - Subscription preferences - Country list

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2545]
Country list field currently allows to add the same country multiple times to the list. It can be saved as well:

![image](https://user-images.githubusercontent.com/68283148/201091377-4f949839-062d-48c6-a182-de3ada520fa6.png)

The field should show a country only once.

**Comment by szabozoltan69** [comment]
Also the temporary commenting out of the "Approaching End of Mission" task is done via this change; the original ticket went to Backlog.
