### ISSUE TITLE
[PROD] "Explore 3W Regional" button leads to a blank page

### ISSUE THREAD

**Issue by steph-gm** [IFRCGo/go-frontend#2555]
## Issue
On the 3W section, when scrolling to the map, we see the "Explore 3W Regional" button, and when clicking on it we see a list with the different regions. There, when selecting and clicking any of the regions, the page starts loading, but after a few seconds it will just show a blank page.
This issue was found late november 2022. I got the same blank page from 2 different browsers (chrome and firefox) and from different computers as well.
- Link to 3W main page: https://go.ifrc.org/three-w/
- One of the links not working (copy pasted from the url bar after selecting the Americas region): https://go.ifrc.org/regions/1#3w

## Steps to reproduce
1. Go to the 3W page/section (URL: https://go.ifrc.org/three-w/)
2. Scroll to the "NS WITH ONGOING PROJECTS" map and click on the "Explore 3W Regional" button
3. In the displayed list, select and click on any region name
The page will not load. And when going back, netiher the main 3W page.

## Expected behaviour
Page should show the 3W for the specific region that was selected

## Impact
Affects anyone looking at the 3W page and wanting to explore the regional 3W page. 

## Severity
Minimal impact. Prevents of using the option, but this has not been reported by any user, it was noted when reviewing the 3W functionality

Note: This is also hapenning with Staging.

**Comment by szabozoltan69** [comment]
The error message in development environment:
![image](https://user-images.githubusercontent.com/6050643/205023018-11d68b25-8bb6-4007-bdbd-adbb74ce0b25.png)

**Comment by szabozoltan69** [comment]
It seems to be the problem: the ownPorps.match.params.id contains not only the id but the #string also, so e.g. 0#3w.
It is possible to cut it down (via a split('#')[0] ), but this way I get an URL like  0#3w#operations, so an automatic appending of the default tab (#operations) appears.

**Comment by szabozoltan69** [comment]
The normal Region pages are also blank at first usage (only get shown after reloading).
