### ISSUE TITLE
DREF Final Report Changes

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2556]
Finally the ticket for the DREF final report changes is here!!

- [x] SHARING: Share the DREF Application with other Users --> Bring this field
- [x] ESSENTIAL INFORMATION: Name of National Society --> Bring to the top of the section
- [x] ESSENTIAL INFORMATION: Is this the DREF for assessment? --> Bring this field
- [x] ESSENTIAL INFORMATION: Affected Country and Affected Region(s) --> Can we organize it in 2 columns like the Application and Ops. Update?
- [x] ESSENTIAL INFORMATION: Title --> Change it to DREF Tittle, move it after Affected Country and Affected Region(s)
- [x] ESSENTIAL INFORMATION: People Affected, Number of people targeted --> Mimic the way it is presented on the Ops. Update + add People in need + add the guidance
- [x] ESSENTIAL INFORMATION: Add Upload map field + guidance + any map on the ops update should be transferred here, but also with a possibility to replace the map
- [x] ESSENTIAL INFORMATION: Add Cover image+ guidance + any pic on the ops update should be transferred here, but also with a possibility to replace it
- [x] TIMEFRAMES --> Move this section to the Submission page + add Operational end date (calculated as in Ops Update) + Reorganize in 2 rows as follows: 1st row: Start os Operation, Total operating timeframe, 2nd row: Operational end date, Publication date of final report
- [x] DESCRIPTION OF THE EVENT: Upload map --> Remove from this section
- [x] DESCRIPTION OF THE EVENT: Date of the Event/ Date when the trigger was met/Approximate date of impact --> Bring this field
- [x] DESCRIPTION OF THE EVENT: Upload Photos of the implementation --> add guidance "Add maximum 2 photos" and limit it to 2 photos only
- [x] MOVEMENT PARTNERS ACTIONS: IFRC --> Bring the same guidance as Ops Update
- [x] MOVEMENT PARTNERS ACTIONS: ICRC --> Bring the same guidance as Ops Update
- [x] MOVEMENT PARTNERS ACTIONS: Partner National Society --> Change to "Participating National Societies" + bring the same guidance as Ops Update
- [x] FEDERATION WIDE AND PARTNERS --> Remove this section
- [x] CURRENT NATIONAL SOCIETY ACTIONS --> Bring back this section but rename it to "National Society Actions", information must be transferred from las Ops Update
- [x] OTHER ACTORS --> Change to "OTHER ACTORS ACTIONS RELATED TO THE CURRENT EVENT"
- [x] OTHER ACTORS: List major coordination mechanisms in place--> Change to "Are there major coordination mechanisms in place?" + make it a yes/no question, if yes open text box with the same description as in Ops Update
- [x] OBJECTIVE AND STRATEGY RATIONALE --> bring this whole section to the top of the page
- [x] OPERATION REOPORT: How have, community engagement Protection, Gender and Inclusion been considered in planning this operation? --> Remove
- [x] TARGET POPULATION: Add the field "Total Population"
- [x] RISK AND SECURITY CONSIDERATIONS --> Add this whole section as per Ops Update

Let me know if any clarification is needed!! @frozenhelium @tovari @marcovvu1

**Comment by frozenhelium** [comment]
@anamariaescobar This has been deployed to the staging!
CC: @tovari

**Comment by anamariaescobar** [comment]
Some changes to the final report:

- [ ] Form title: Change the title to “DREF Final Report” 
- [ ] In Essential Information: Remove the question “Is this a DREF for Assessment”. In case the application is for assessment, the Final Report needs to keep the sections not available in the assessment form hidden 
- [ ] In Essential Information: Add a field “Number of people assisted”, after the field “Number of people targeted” 
- [ ] Rename the “NEEDS” title to “Actions/Needs” 
- [ ] In National Society Actions Section: Remove the “Has the National Society started any actions” questions and remove the “select actions that apply” field and dropdown list. The content on these fields from the DREF application should be hidden and it should not appear in the DREF Final report 
- [ ] In National Society Actions: Add a yes or no question titled: Have the National Society conducted any intervention additionally to those part of this DREF Operation? If yes is selected, a long text box should appear titled: Please provide a brief description of those additional activities 
- [ ] Change the title of the section NEEDS (GAPS) IDENTIFIED to NEEDS.
- [ ] Rename the section called “OPERATION REOPORT”  to “Targeting Strategy” and move it after "Objective and strategy rationale"
- [ ] Remove the option to upload the budget from the “Implementation” section 
- [ ] In the “Implementation” section: Add to all sectors the field “Persons assisted”, after the “Persons targeted”
- [ ] In the “Implementation” section: Change the layout of the sectors to the below: 
![dref](https://user-images.githubusercontent.com/69478743/209319956-e3f9d679-e021-4de7-911a-7b1f1435f446.png)
- [ ] Add a new section after "Implementation" called "Financial report" this section should have two new fields: "Please attach the final financial report" and a text box "Please explain variances (if any)"

@frozenhelium @marcovvu1 @tovari

**Comment by udaynwa** [comment]
> 

@anamariaescobar , we have pushed the Final Report changes to STAGING. 

A question on the `In the “Implementation” section: Change the layout of the sectors to the below:`. Do you need the order of 'Narrative description of achievements', 'Challenges' & 'Lessons Learnt' fields to be the same as in the screenshot you've attached in the comment above? 

cc @tovari @frozenhelium

**Comment by anamariaescobar** [comment]
hey @udaynwa! Thanks for the changes, I just have a couple of comments:

- [ ] In National Society Actions Section: The content on these fields from the DREF application should be hidden and it should not appear in the DREF Final report (Water, Sanitation and hygiene, Coordination, etc). Only the new 2 questions ("Have the National Society conducted any intervention additionally to those part of this DREF Operation?" and  "Please provide a brief description of those additional activities") should appear in both the Final report form and the Final report export
- [ ] Implementation section: We should bring the "List of activities" on the form (should NOT be on the export), next to it the "Narrative descriptions of achievements", below them we can keep "Lessons Learnt" and "Challenges" (as they are, one below the other and next to them we can have the indicators part).
- [ ] On the export, the new fields of Persons assisted, etc in the implementation section should appear.
- [ ] I like the functionality that doesn't let the Final Report to be saved without anything on the person assisted under the implementation sector, but can que have a banner to let the user known what the mistake is?

The rest of it looks great!! Thank you!!

@tovari @frozenhelium

**Comment by udaynwa** [comment]
> hey @udaynwa! Thanks for the changes, I just have a couple of comments:
> 
> * [x]  In National Society Actions Section: The content on these fields from the DREF application should be hidden and it should not appear in the DREF Final report (Water, Sanitation and hygiene, Coordination, etc). Only the new 2 questions ("Have the National Society conducted any intervention additionally to those part of this DREF Operation?" and  "Please provide a brief description of those additional activities") should appear in both the Final report form and the Final report export
> * [x]  Implementation section: We should bring the "List of activities" on the form (should NOT be on the export), next to it the "Narrative descriptions of achievements", below them we can keep "Lessons Learnt" and "Challenges" (as they are, one below the other and next to them we can have the indicators part).
> * [x]  On the export, the new fields of Persons assisted, etc in the implementation section should appear.
> * [x]  I like the functionality that doesn't let the Final Report to be saved without anything on the person assisted under the implementation sector, but can que have a banner to let the user known what the mistake is?
> 
> The rest of it looks great!! Thank you!!
> 
> @tovari @frozenhelium

@anamariaescobar , the changes requested in the above comment have been implemented and pushed to Staging. But we have found a couple of minor (non-blocker) issues in the export. We will fix them very soon.

**Comment by anamariaescobar** [comment]
Thanks!!

The changes work as expected, I just have 2 suggestions regarding layout:

- [ ] In the Final Report form: On the Implementation section, List of Activities should be to the left and Narrative description of Achievements to the right, also can Lessons learnt and Challenges boxes be as wider and the indicator boxes smaller? See picture:
![FR_form_Implementation](https://user-images.githubusercontent.com/69478743/212030536-7569a389-8eba-4821-b7ad-c763f872f0d4.JPG)

- [ ] In the Final Report Export: On the Implementation section, can we make the boxes for Budget, Targeted Persons, etc bigger and the boxes for the numbers smaller? See picture:
![FR_export_Implementation](https://user-images.githubusercontent.com/69478743/212031175-f378b879-3bb3-4471-bc80-893b3a76bc5c.jpg)

@udaynwa @frozenhelium @tovari @marcovvu1

**Comment by udaynwa** [comment]
> Thanks!!
> 
> The changes work as expected, I just have 2 suggestions regarding layout:
> 
> * [x]  In the Final Report form: On the Implementation section, List of Activities should be to the left and Narrative description of Achievements to the right, also can Lessons learnt and Challenges boxes be as wider and the indicator boxes smaller? See picture:
>   ![FR_form_Implementation](https://user-images.githubusercontent.com/69478743/212030536-7569a389-8eba-4821-b7ad-c763f872f0d4.JPG)
> * [x]  In the Final Report Export: On the Implementation section, can we make the boxes for Budget, Targeted Persons, etc bigger and the boxes for the numbers smaller? See picture:
>   ![FR_export_Implementation](https://user-images.githubusercontent.com/69478743/212031175-f378b879-3bb3-4471-bc80-893b3a76bc5c.jpg)
> 
> @udaynwa @frozenhelium @tovari @marcovvu1

Hi @anamariaescobar both of the suggestions have been **implemented and pushed to STAGING**. 

cc @frozenhelium @tovari

**Comment by anamariaescobar** [comment]
Hi @udaynwa !!

The changes look great! the only thing is that we are missing the Narrative description of achievements in the export on the Implementation part, can we add it?

@frozenhelium @tovari

**Comment by anamariaescobar** [comment]
Sorry! I just found a couple of more things:

- [ ] In the export (for both final report and Ops Update), the first section is named "Provide any updates in the situation since the xeld report and ewplain .hat is ewpected to happen" and it's pulling information from the field "What happened, where and when?" in the form, it should be re-named on the export to match the form
- [ ] In the export, Implementation section, the indicators should have target and actual
- [ ] In the export, Implementation section, add Narrative description of achievements, Lessons learnt and Challenges (in that order)

@udaynwa @tovari @frozenhelium

**Comment by udaynwa** [comment]
> Sorry! I just found a couple of more things:
> 
> * [x]  In the export (for both final report and Ops Update), the first section is named "Provide any updates in the situation since the xeld report and ewplain .hat is ewpected to happen" and it's pulling information from the field "What happened, where and when?" in the form, it should be re-named on the export to match the form
> * [x]  In the export, Implementation section, the indicators should have target and actual
> * [x]  In the export, Implementation section, add Narrative description of achievements, Lessons learnt and Challenges (in that order)
> 
> @udaynwa @tovari @frozenhelium

Hi @anamariaescobar , the above listed changes have been implemented and pushed to STAGING. Please feel free to go ahead and verify them. 

cc @frozenhelium @tovari

**Comment by anamariaescobar** [comment]
Thanks @udaynwa, the changes look really goood!!!!! Nothing else from my side, all ready to launch the hotfix if everyone is ok with that! 

@frozenhelium @tovari
