### ISSUE TITLE
[PROD] Surge - Catalogue of services - text update

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2557]
Please change the text in the Catalogue that in the Health section on the Rapid Response personnel, we have “Emergency Relief Unit Role profiles....” It should be Emergency Response Unit Role Profile instead...

![image](https://user-images.githubusercontent.com/68283148/205266661-aada606d-f547-4d58-bdf3-c228702e9559.png)

**Comment by szabozoltan69** [comment]
So in fact this change is required (with plural, the 2nd one), I suppose:

Emergency Relief Unit Role profiles
->
Emergency Response Unit Role Profiles

**Comment by tovari** [comment]
https://go-stage.ifrc.org/deployments/catalogue/health

**Comment by szabozoltan69** [comment]
Deployed to Staging.
