### ISSUE TITLE
Surge catalogue - remove text

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2560]
Please remove the Finnish RC as a holder of a Relief ERU from the bottom of the page here:

https://go-stage.ifrc.org/deployments/catalogue/relief/eru-relief

![image](https://user-images.githubusercontent.com/68283148/205602506-d7e2df11-6716-4a31-b710-b76424787e7b.png)

Thanks!

**Comment by szabozoltan69** [comment]
Deployed to Staging.
