### ISSUE TITLE
Surge CoS update

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2569]
Could you please add the below paragraph at the end of the text of the [Catalogue of Surge services](https://go.ifrc.org/deployments/catalogue)?

Paragraph:
You can find the list of the Minimum trainings required for IFRC Surge personnel in [this link](https://surgelearning.ifrc.org/resources/minimum-training-required-surge-personnel). It provides guidance on minimum required courses for current and future Rapid Response personnel.

Location:
![image](https://user-images.githubusercontent.com/68283148/206215145-c2893ccd-6129-4147-88ab-fcfd675511d6.png)
Please adjust text styling.
Thanks!

**Comment by szabozoltan69** [comment]
Deployed to Staging
