### ISSUE TITLE
Field report form - Arabic 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2581]
The arabic FR form contains a few selection items that cannot be used as the trashbin icon appears:

1st page, last 2 selections:
![image](https://user-images.githubusercontent.com/68283148/208412792-9609eb7a-93ce-4ff9-a28d-c567299adbfe.png)

4th page, on the top:
![image](https://user-images.githubusercontent.com/68283148/208413024-420581d2-a062-429f-bb5b-78c20bdf72b2.png)

**Comment by frozenhelium** [comment]
@tovari the fix is available in the staging
