### ISSUE TITLE
Map disclaimer

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2593]
We need to show a disclaimer on all GO maps (main page, region pages, country pages, emergencies page, surge page, 3W pages).
It would pop-up on clicking the small 'i' (in circle). 
_Map Sources : ICRC, UN._

The text in the pop-up:
_The maps used do not imply the expression of any opinion on the part of the International Federation of Red Cross and Red Crescent Societies or National Society concerning the legal status of a territory or of its authorities._

Design:
https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=0%3A4957&node-id=0%3A4963&viewport=-566%2C-2323%2C0.06&scaling=scale-down-width&starting-point-node-id=0%3A4963&hide-ui=1

**Comment by frozenhelium** [comment]
@tovari  we're not adding this to the risk maps?

**Comment by tovari** [comment]
> @tovari we're not adding this to the risk maps?

Yes, please add it, as the country borders are visible there as well.

**Comment by frozenhelium** [comment]
@tovari It's now available on the staging (except for the risk maps)
![2023-01-27-150145](https://user-images.githubusercontent.com/4931541/215050784-512e8317-46ed-4656-917c-54c626ffd52f.png)

We'll extend this to risk maps separately, since we're already working on the maps in another PR.

**Comment by tovari** [comment]
Thanks! As we discussed today, we aim to add a link to UN data:
https://cod.unocha.org/
Sources can be added to the pop-up window.
OSM source designation shall be removed, or moved to the pop-up as well. 
@geohacker, can you confirm, if we display any OSM data on the map?
