### ISSUE TITLE
[PROD] WikiJs links

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#2594]
## Issue
There are different approaches for WikiJs links on frontend.
We should use the component based approach everywhere, like this:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/RegionalRiskWatch/index.tsx#L38-L43
Not like this:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/region.js#L290

**Comment by tovari** [comment]
Has this been resolved by the rewrite @szabozoltan69 ? If yes, would you mind to close it? Thanks

**Comment by szabozoltan69** [comment]
Yes! :)
