### ISSUE TITLE
Region pages - Additional tab url is redirected to the Operations tab

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2613]
Each Region pages Additional tab url gets redirected to the Operations tab, when we directly call the url.
E.g.:
https://go-stage.ifrc.org/regions/0#additional-info
leads to
https://go-stage.ifrc.org/regions/0#operations

All other tabs on the region pages can be directly loaded.
Both on staging and prod.

**Comment by szabozoltan69** [comment]
The same error in case of https://go-stage.ifrc.org/regions/0#preparedness (when not visited this before).

**Comment by szabozoltan69** [comment]
Can be fixed via getting out the comments:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/region.js#L83-L89

**Comment by szabozoltan69** [comment]
At the moment of the running of this row:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/region.js#L167
this following adding of the 2 "checked tabs" has not yet run:
https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/region.js#L225
(Neither "data" exists, so the adding rows can not be duplicated simply)

**Comment by szabozoltan69** [comment]
Deployed to Staging
