### ISSUE TITLE
DREF simplified permissions [Staging] 

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2618]
Opening a new ticket to deal with the issues on the simplified permissions for DREF.

When I share an Operational Update with another user, the logic connecting the "Summary of Changes" with the "Number of people targeted" and the "Total operating timeframe" gives me errors only for the user that the Ops Update was shared.
When I try to share a Final Report and save, the pop up says that it was saved successfully but the changes on the sharing don't save.

@udaynwa @frozenhelium @tovari

**Comment by udaynwa** [comment]
@anamariaescobar , it seems that we have validation for the above-mentioned questions. For changing the above fields, we must set some boolean to 'Yes' in the 'Summary of Changes'. For example: if you try to change the 'Total operating timeframe', you should set the 'Are you changing the timeframe of the operation' in the 'Summary of Changes' section to 'Yes'. Same with the 'Number of people targeted'. 

For the second issue, we have replicated and are resolving it. 

@frozenhelium @tovari

**Comment by anamariaescobar** [comment]
@udaynwa yes, we do have those validations, but even if I dont change those fields I get the error message.

**Comment by udaynwa** [comment]
@anamariaescobar I think we replicated it. Can you confirm if it is happening only when the fields are left empty at first?

**Comment by anamariaescobar** [comment]
@udaynwa, yes it seems is only  when the fields are left empty

**Comment by anamariaescobar** [comment]
@udaynwa, I just checked the simplified permissions in Staging, when I share an operational update with an user, that user can't see the Operational Update in his account, but the user is able to see the Operational update if a link is shared, so it seems the permissions are working, but is not appearing on the account page.

Let me know if we should have a call to clarify.

@tovari

**Comment by anamariaescobar** [comment]
@udaynwa, I just checked in the testing branch, and the permissions are working as expected, but we are still experiencing the issue that the operational timeframe is not transferring from the application to the Operational update, as this question has some logic linked to the Sumary of changes, if the Operational timeframe is blank  this generates an error and the users are getting confused. Can we make sure this field gets transferred from the Application to the operational update? 

Thanks!

@tovari

**Comment by udaynwa** [comment]
> @udaynwa, I just checked in the testing branch, and the permissions are working as expected, but we are still experiencing the issue that the operational timeframe is not transferring from the application to the Operational update, as this question has some logic linked to the Sumary of changes, if the Operational timeframe is blank this generates an error and the users are getting confused. Can we make sure this field gets transferred from the Application to the operational update?
> 
> Thanks!
> 
> @tovari

@anamariaescobar , is it happening when you are trying to save the Operational Update with '0' as the 'Total Operating Timeframe', and setting 'No' in the Summary of changes? If yes, we have replicated it and will let the users save the Operational Update with '0' too. If not, could you please explain the issue over a quick call? 

@tovari

**Comment by anamariaescobar** [comment]
Yes, the issue is that when I start an operational update the operational timeframe does not transferred from the application, so when trying to save the Ops update with that field empty it generates the error. The right solution should be that the Operational timeframe is transferred from the Op Update.

@udaynwa

**Comment by udaynwa** [comment]
2 questions, @anamariaescobar ;

- Are we transferring Operational Timeframe from DREF Application to the Operational Update? 
- Are we also transferring Total operating timeframe from one Operational Update to another Operational Update?

**Comment by anamariaescobar** [comment]
Yes to both questions @udaynwa, but also convert those errors into warnings, so the user can save the progress in the operational update even with the errors, it will be the responsibility of the DREF focal point to ensure that those warnings are resolved before "publishing" the Ops update.

**Comment by udaynwa** [comment]
@anamariaescobar , 

- now the Operational Timeframe will transfer DREF Application to Operational Update, and to the Final Report as well
- the Total Operating Timeframe will transfer from one Operational Update to another Operational Update also
 You can go ahead and verify these in the test-server. 
 
Converting the errors into warnings, and letting the users save the Ops Update with the errors might take a bit of time. It is in-progress.

@tovari

**Comment by anamariaescobar** [comment]
@udaynwa I just check the operational timeframe issue and the fix works perfectly! Thank you so much!
I will wait for the "save with error" fix, but I think if this one takes longer, we could release without it.

@tovari what do you think?

**Comment by anamariaescobar** [comment]
I have checked the "save with errors" and it's working great!!

Thank you @udaynwa!!
@tovari

**Comment by anamariaescobar** [comment]
@udaynwa one issue persists in production.
when I share an operational update with an user, that user can't see the Operational Update in his account, but the user is able to see the Operational update if a link is shared, we experienced this issue when we were testing in staging and it was fixed, but it is still happening in Production.

@tovari

**Comment by udaynwa** [comment]
Looking into it, @anamariaescobar . Thanks for reporting

**Comment by udaynwa** [comment]
@anamariaescobar , can you share the name of the user in whose account this issue is persisting? Thanks.

**Comment by anamariaescobar** [comment]
Sure @udaynwa , the user who has the issue is rachel.day@ifrc.org
