### ISSUE TITLE
Surge CoS - document to be added

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2630]
Could you please add the Security technical competency framework (attached) to the Catalogue of Services?
It will need to go on the Security sector page- https://go.ifrc.org/deployments/catalogue/security
We also need to add the Technical Competency Framework box (example below) next to the Role profiles box.

![image](https://user-images.githubusercontent.com/68283148/216971813-4f833bbf-63f3-4153-bb08-b6eb6a002291.png)
[1. Surge Security Technical Competency Framework (FINAL).pdf](https://github.com/IFRCGo/go-frontend/files/10662989/1.Surge.Security.Technical.Competency.Framework.FINAL.pdf)

**Comment by szabozoltan69** [comment]
Deployed to Staging
