### ISSUE TITLE
GO Workplan update on the Resources page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2632]
Please change the GO Workplan 2022 link and label on the GO Resources page to 'GO Workplan 2023'
`https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/Ea0TfruyRiZGhyGT3XCEnPMBxZSYqlwLLgEHx1VqeBT9Tg?e=nrpLmz`

![image](https://user-images.githubusercontent.com/68283148/217001073-d6447da5-3288-4979-96a8-611a73ebd5e3.png)

**Comment by szabozoltan69** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/6050643/217013666-b9ee194d-b75f-419c-8f89-93e99a39d2d8.png)

**Comment by szabozoltan69** [comment]
Deployed to Staging
