### ISSUE TITLE
[PROD] Surge - Ongoing Deployments by emergencies table data 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2641]
Ongoing RR deployments by emergencies table shows incorrect details:
https://go.ifrc.org/deployments/overview

![image](https://user-images.githubusercontent.com/68283148/218044560-c23ec041-6a06-4548-931a-7fcda77d8270.png)

On the emergency pages, we can check the details.
Türkiye:
https://go.ifrc.org/emergencies/6345#surge
![image](https://user-images.githubusercontent.com/68283148/218046418-8abb08c8-4d04-4cf0-9e8d-0bb0eaa9faef.png)

Issues in the _Ongoing RR deployments_ table:
- The 2 deployments starting today are not counted as ongoing
- the organizations are not filtered to the ongoing deployments, but showing also future deployment organizations as well

@anamariaescobar

**Comment by szabozoltan69** [comment]
Some facts for investigation:
The /deployments/overview page uses https://goadmin.ifrc.org/api/v2/personnel_by_event/ endpoint (without any filtering) and has this kind of results from backend:
![kép](https://user-images.githubusercontent.com/6050643/218057691-18f4e13c-c9ff-4f03-8d95-c5d70867f86a.png)
The /emergencies/6345#surge page uses https://goadmin.ifrc.org/api/v2/personnel/?event_deployed_to=6345&limit=5&offset=0&end_date__gt=2023-02-10T09:43:04.957Z (So has "event_deployed_to | 6345" and "end_date > now" filters),
and that sort of result is received:
![kép](https://user-images.githubusercontent.com/6050643/218059136-4eb449c8-5863-49d8-b278-0644c67c0415.png)

So briefly we can say that personnel_by_event and personnel are different API endpoints.

**Comment by szabozoltan69** [comment]
Nevertheless the (frontend-wise) unfiltered personnel_by_event has some filters on backend:
https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L132-L146
Namely is_active=True is a requirement, and also the start_date and end_date should include "now".

**Comment by szabozoltan69** [comment]
Should this show 4?
![kép](https://user-images.githubusercontent.com/6050643/218069342-568fba3d-ac1b-4a3f-a385-119e9f3ab5dd.png)
Or should we remove the future one from the diagram?

**Comment by anamariaescobar** [comment]
3 is ok, the future deployments should not count there as we are showing "Ongoing deployments"

**Comment by szabozoltan69** [comment]
A Number of Deployments is count this way:
```
COUNT("deployments_personnel"."deployedperson_ptr_id") 
FILTER (WHERE (
"deployments_deployedperson"."end_date" >= '2023-02-10T17:01:24.921492+00:00'::timestamptz AND
"deployments_personnel"."is_active" AND 
"deployments_deployedperson"."start_date" <= '2023-02-10T17:01:24.921474+00:00'::timestamptz AND
 "deployments_personnel"."type" = 'rr'))
 AS "personnel_count" FROM "api_event"
```
So, if start_date is an exact date (with 0:00:00 in it), it will be not >= "now" on the mentioned "today".
 The query is [here](https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L132-L146).
The "Deploying Organizations" are collected here: https://github.com/IFRCGo/go-api/blob/develop/api/serializers.py#L651-L657
These two parts are to be fixed.

**Comment by szabozoltan69** [comment]
The "Deploying Organizations" will be (tested locally):
![kép](https://user-images.githubusercontent.com/6050643/218163822-d6e4b428-7035-4e7e-b468-9070ca7f94df.png)
If I put a "start_date__lte=timezone.now()" condition to https://github.com/IFRCGo/go-api/blob/develop/api/serializers.py#L655

**Comment by szabozoltan69** [comment]
If my quess is fine, this '1' will became '2' tomorrow (Febr 11):
![kép](https://user-images.githubusercontent.com/6050643/218189747-0ef41f78-4d68-4a79-b824-ff3fcf223c2a.png)

**Comment by szabozoltan69** [comment]
And it happened!
https://go.ifrc.org/deployments/overview
![kép](https://user-images.githubusercontent.com/6050643/218401849-8025d411-fb14-480a-ad54-f7befbdb0337.png)

**Comment by szabozoltan69** [comment]
Deployed to staging.
(In this fix only the "Deploying organization" list was corrected.)

**Comment by szabozoltan69** [comment]
Deployed to staging.

**Comment by szabozoltan69** [comment]
Deployed to prod.
