### ISSUE TITLE
DREF - New type of DREF

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2643]
Hello everyone! this is the first ticket on the NEW phase of the DREF in Go!

We are tackling the biggest change so far that is introducing "Type of DREF", we need a new field on that will reflect what type of DREF this is, we will have 3 options: Assessment, Response and Imminent, this means that the field "Onset" Imminent will disappear.
Type of DREF will be de deciding field that will "change the form", but slow/sudden onset could apply to any of the types.

Short ticket, but a lot of work! :)

Let me know if we need to jump in a call @udaynwa @tovari

**Comment by anamariaescobar** [comment]
Hello! Since we are going to be working on the exports to include the Type of DREF, let' take this opportunity to re-organize the first page of the exports, please find a Word document attached, mainly the changes are:

- [x] For any export of the Application, the tittle should change from "DREF application" to "DREF operation"
- [x] The IFRC logo needs to change, we are using the square logo for now on
- [x] The GO logo will move to the bottom right
- [x] The design of what information to show on the gray boxes can be found on the Word document for each one of the exports
[Templates headings.docx](https://github.com/IFRCGo/go-frontend/files/11015739/Templates.headings.docx)
- [ ] Let's add some space between the picture and the gray boxes so the page doesn't look too empty on the bottom.
@udaynwa @tovari

**Comment by udaynwa** [comment]
@anamariaescobar , 1 question; 

> The GO logo will move to the bottom right

The GO logo should be on each page at the bottom right or only on the first page of the export?

cc @tovari

**Comment by anamariaescobar** [comment]
Hi @udaynwa , in every page please!!

cc @tovari

**Comment by anamariaescobar** [comment]
Tested in production and working beautifully!!!
