### ISSUE TITLE
STAGING notification emails

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2646]
There's emerging need on using the staging site for training and testing purposes.

Due to the switched-off notification service on staging, registration is not possible without manual activation, the notifications can't be tested. 

Please reset the notifications for staging users and turn on the notification emails for all registered users on staging.

cc: @LukeCaley

**Comment by szabozoltan69** [comment]
To be safe, before deployment I remove all kind of subscriptions from staging, where the addressee is not in TEST_EMAILS.

**Comment by szabozoltan69** [comment]
Also removed TEST_EMAILS from env file.
