### ISSUE TITLE
Highlighted Operations card updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2647]
Please update the highlighted operations card on the main page and region pages.

Information on the card:

- Targeted population
- Funding Ask with coverage bar
- '# Deployed Surge
- crisis categorisation
- '# of NS reporting to emergency 3W 
- 'Follow' button to subscribe to the emergency notifications
- Number logic - summarise thousands to K and millions to M
- Hover over info: crisis categorization 

When clicking on the different boxes on the card, you are taken to that emergency's different tabs:

- Targeted pop takes you to emergency details
- Funding ask to reports / docs
- Surge to surge
- and NS active to 3w page

prototype:
https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=8129%3A139296&node-id=10300%3A162891&viewport=239%2C407%2C0.11&scaling=scale-down-width&starting-point-node-id=8140%3A139297&hide-ui=1

cc: @LukeCaley

**Comment by mariam-yu** [comment]
Hey team, here are the updated designs. Note the hovers for each box for links.
- Prototype: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=8129%3A139296&node-id=10300%3A162891&viewport=239%2C407%2C0.11&scaling=scale-down-width&starting-point-node-id=8140%3A139297&hide-ui=1
- UI elements: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=10300%3A160778&t=nQlPoVdYfI0XyUHL-4

**Comment by tovari** [comment]
Time tracking info:
DFS- Site improvements - PO 22-0190
YU - Site improvements - PO 22-0189

**Comment by udaynwa** [comment]
Hey @mariam-yu , I cannot find the hover information in the Prototype. It was there before. Could you take a look, please? 
![image](https://user-images.githubusercontent.com/72339626/220309262-e6ff694e-46a2-459d-8441-90ad416686ad.png)

**Comment by mariam-yu** [comment]
@udaynwa Please check here and let me know if this helps:
Prototype: https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=8129%3A139296&node-id=10300%3A162891&viewport=239%2C407%2C0.11&scaling=scale-down-width&starting-point-node-id=8140%3A139297&hide-ui=1
Canvas: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=10300%3A162891&t=MWtBDmohmSjEeGvZ-4
Component: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=10340%3A167351&t=MWtBDmohmSjEeGvZ-4

**Comment by udaynwa** [comment]
Got it in one of the links, @mariam-yu . Thank you

**Comment by tovari** [comment]
Please implement the following functionality:

When clicking on the different boxes on the card, you are taken to that emergency's different tabs:
Targeted pop takes you to emergency details
Funding ask to reports / docs

At funding received label, add a whitespace before 'received'

**Comment by mariam-yu** [comment]
@udaynwa @tovari The highlighted operations cards look great on staging. The hovers are good. The only UI things are the received should be 12px light, same for number and text, and can you check overall box sizes per: https://www.figma.com/file/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?node-id=10300%3A160778&t=6VayYQTyZZDQHckL-4

Also, I guess we are removing the second row? TBD @tovari

**Comment by udaynwa** [comment]
> Please implement the following functionality:
> 
> When clicking on the different boxes on the card, you are taken to that emergency's different tabs: Targeted pop takes you to emergency details Funding ask to reports / docs
> 
> At funding received label, add a whitespace before 'received'

@tovari , these have been pushed to Staging. 

cc @mariam-yu @frozenhelium

**Comment by tovari** [comment]
It seems that long emergency titles are organized into multiple rows and potentially truncated. The available space could be utilized better:

![Image](https://user-images.githubusercontent.com/68283148/223676376-aabc42b7-b80c-483e-a8a4-cb0012217905.png)

**Comment by tovari** [comment]
We decided to remove the 3rd row (IFRC Sureg personnel, NS reporting activities) from the card for now as we have not many emergencies with reported activities. 
Please keep it somehow as we will need it sometime in the future.

**Comment by udaynwa** [comment]
@tovari , we have implemented your feedback and pushed them to Staging.

**Comment by tovari** [comment]
Thanks @udaynwa, please update the 'Funding Ask' label to 'Funding Requirements'.

**Comment by udaynwa** [comment]
> Thanks @udaynwa, please update the 'Funding Ask' label to 'Funding Requirements'.

Updated and pushed to Staging, @tovari

**Comment by mariam-yu** [comment]
@udaynwa Looks great. Quick comment, now that we removed the second row, I guess we don't need the individual box hovers, since I guess it would link to the same page, even though it looks good :) So the whole box can be clickable. That's correct, right @tovari ?

**Comment by udaynwa** [comment]
@mariam-yu , you're right about it linking to the same page, but each box **links to a different sub-page**.  

- Targeted Population ->Emergency Details sub-page
![image](https://user-images.githubusercontent.com/72339626/226262129-9f4a76e6-9300-41a8-b9a8-761619b531cc.png)
- Funding requirements -> Reports/Documents sub-page
![image](https://user-images.githubusercontent.com/72339626/226262183-b3a5d618-118b-4bd0-8793-08fc6d246b72.png)
