### ISSUE TITLE
3W project - edit, duplicate, history options visibility

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2648]
Unauthenticated users also have an option to click on 3W project Edit, Duplicate and History buttons:

![image](https://user-images.githubusercontent.com/68283148/219389604-39fd83a1-9762-467e-aa70-0674a87b0e48.png)

Clicking on Edit, opens the 3w project editing form, where the user can change the data. Only when submits the changes, a red-pop-up under the form (!) shows that the user has no permission to do it. The form covers the red pop-up message.

It should me more clear and what the user might do:
- either disable (grey out or hide) these options for not logged in users,
- or lead to the login page when clicking on these buttons (this is the solution at 3W activities)

I'm not sure what would be the desired and the feasible solution @mariam-yu, @batpad, @frozenhelium

**Comment by mariam-yu** [comment]
@tovari Usually, we should show only the actions that the user can do, especially on row-level. I'd say it should be an expected action to edit only after being able to login. The Login red button below is just a shortcut that allows the users to quickly go there (which hopefully then lands then back on the same page).
