### ISSUE TITLE
Update Table Filters

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#265]
- add date selection
- sort by active
- sort by country
- add emergency level

**Comment by dereklieu** [comment]
Just noting that some items here are many-to-many relations in the database, and thus cannot be sorted. For example, emergencies can be linked to many countries, thus are a many-to-many relationship. 

For objects with a single foreign key relationship, such as appeals <-> country (appeals can have only one country) then we can sort on country here.
