### ISSUE TITLE
Javascript comment visible on Field Report page

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#2675]
Thanks to @JonathanGarro for reporting:

I **think** this is coming from https://github.com/IFRCGo/go-frontend/blob/develop/src/root/views/FieldReportForm/ContextFields/index.tsx#L275 - the `// FIXME` there is just in the context of regular text in the component.

@szabozoltan69 do you think you could try removing that line?

I can see this being a slightly hard one to catch with our automated linting since the linter would have not seen this as part of JS code at all. @frozenhelium am not sure if you have any suggestions for best practices here to automatically catch this kind of problem in the future?

cc @tovari

**Comment by szabozoltan69** [comment]
I can remove that line (or make a comment another way), though I could not reproduce the erroneous view neither on staging nor prod.

**Comment by szabozoltan69** [comment]
Hotfixed via https://github.com/IFRCGo/go-frontend/pull/2678 – thanks @frozenhelium
Deployment to Prod is ongoing.

**Comment by szabozoltan69** [comment]
(A duplication of https://github.com/IFRCGo/go-frontend/issues/2677 )
