### ISSUE TITLE
[PROD] Field report form - js error message appears

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2677]
An error message shows up on the new field report form https://go.ifrc.org/reports/new

https://share.cleanshot.com/ZB8TGVLg

Please deploy it as a hot fix.

**Comment by szabozoltan69** [comment]
Hotfixed via https://github.com/IFRCGo/go-frontend/pull/2678 – thanks @frozenhelium 
Deployment to Prod is ongoing.
