### ISSUE TITLE
Surge CoS document update

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2692]
There are 2 new documents to be added to the Catalogue of Surge Services in the SECURITY area. 
https://go.ifrc.org/deployments/catalogue/security

The security officer profile is to be added under Role Profiles and the Security Coordinator profile is to replace the existing version of the document. 

[Rapid Response Profile Security Officer.pdf](https://github.com/IFRCGo/go-frontend/files/11062206/Rapid.Response.Profile.Security.Officer.pdf)

[Rapid Response Profile Security Coordinator1.pdf](https://github.com/IFRCGo/go-frontend/files/11062207/Rapid.Response.Profile.Security.Coordinator1.pdf)

**Comment by szabozoltan69** [comment]
Hotfix deployed to Prod.
Merged back to develop.
Deployed to Staging also.
