### ISSUE TITLE
Surge CoS - Communication

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2701]
There is a slight error in the Communications section of the catalogue of services. 

The Audiovisual Officer-Videographer and Audiovisual Officer- Photographer, are linking to each others profiles instead of their own. 

![image](https://user-images.githubusercontent.com/68283148/228455807-f4f3cf73-542a-4340-85e0-71729d93ed69.png)

**Comment by szabozoltan69** [comment]
Merged to develop.
