### ISSUE TITLE
New DREF Type: Loan

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2704]
@frozenhelium @udaynwa @tovari, as discussed in the meeting this morning, we are introducing a new type of DREF, Loan.

The behavior of the Loan type of DREF will be similar as the Assessment type, a lot of fields will be hidden, a Loan can be requested in an Application or a DREF that started as any other type could be turn into a loan by an Ops Update too. Once a DREF has a Loan type, the option for creating a Final Report should not appear. An export of the form is not needed when a Loan is requested (an allocation export will be needed, not only for this type of DREF but for all, we will tackle this one later on).
We need to keep the functionality to transfer the information from an application (of any type) to the ops update fields, but if the type of DREF is changed to Loan at this stage, only the fields below should be shown.

The fields that need to be displayed when the type of DREF is Loan are:

#### OPERATION OVERVIEW
- [ ] Share the DREF Application with other Users
- [ ] Name of National Society
- [ ] DREF Type
- [ ] Type of Disaster
- [ ] Type of Onset
- [ ] Disaster Category
- [ ] Add Country
- [ ] Region/Province
- [ ] DREF Title
- [ ] Total affected population
- [ ] Number of people targeted
#### EVENT DETAIL
- [ ] Date of the Event / Date when the trigger was met / Approximate date of impact
#### SUBMISSION/CONTACT
- [ ] Date of National Society Application
- [ ] Date of Submission to GVA
- [ ] Date of Approval
- [ ] Operation timeframe
- [ ] Appeal Code
- [ ] IFRC Appeal Manager (Name, tittle, email, phone number)
- [ ] IFRC Project Manager (Name, tittle, email, phone number)

#### OPERATION OVERVIEW
- [ ] Share the DREF Application with other Users
- [ ] Name of National Society
- [ ] DREF Type
- [ ] Type of Disaster
- [ ] Type of Onset
- [ ] Disaster Category
- [ ] Add Country
- [ ] Region/Province
- [ ] DREF Title
- [ ] Total affected population
- [ ] Number of people targeted
- [ ] Additional Allocation Requested
- [ ] Total DREF Allocation
#### EVENT DETAIL
- [ ] Date of the Event / Date when the trigger was met / Approximate date of impact
#### SUBMISSION/CONTACT
- [ ] Date of National Society Application
- [ ] Date of Submission to GVA
- [ ] Date of Approval
- [ ] Operation timeframe
- [ ] Appeal Code
- [ ] IFRC Appeal Manager (Name, tittle, email, phone number)
- [ ] IFRC Project Manager (Name, tittle, email, phone number)

**Comment by frozenhelium** [comment]
@anamariaescobar for the following fields in Ops. Update
- Date of National Society Application
- Date of Submission to GVA
- Date of Approval
- Operation timeframe
We don't have these field in the Ops. Update yet (They only exist in the DREF Application form), should we add those fields in ops update for the loan type?

**Comment by anamariaescobar** [comment]
Hi @frozenhelium, some answers below:

- Date of National Society Application - _This one we do need, is it possible that this field only appears for ops update when type of DREF is loan? and we can name it "National Society Loan request date"_
- Date of Submission to GVA - _We don't need it on the ops update_
- Date of Approval - _This one we do need, is it possible that this field only appears for ops update when type of DREF is loan? and we can name it "Date of approval of Loan"_
- Operation timeframe - _This one we do have in the Ops update, it is the "Total operating timeframe"_

**Comment by frozenhelium** [comment]
@anamariaescobar Thanks! Those should be possible!

**Comment by anamariaescobar** [comment]
I have tested the DREF Loan and only have one comment:

- [ ] Application: Operation Overview: Requested Amount in CHF needs to appear
- [ ] Application and Ops. Update: Submission: Add DREF Regional Focal point to the contacts (with email, phone and tittle - this can be prepopulated with "DREF Regional Focal point", but she be editable - Also, this field should only appear on type Loan so no need to do changes on the export)

Sorry, I completely missed these fields!!! The rest is looking great!!!

@udaynwa @frozenhelium @tovari

**Comment by anamariaescobar** [comment]
Tested and working correctly in staging, thanks!!
