### ISSUE TITLE
Surge CoS - add new role profile

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2723]
Please piblish the attached Public Health Officer role profile on the Health section https://go-stage.ifrc.org/deployments/catalogue/health

[Rapid Response Role Profile - Public Health Officer.pdf](https://github.com/IFRCGo/go-frontend/files/11196978/Rapid.Response.Role.Profile.-.Public.Health.Officer.pdf)

**Comment by szabozoltan69** [comment]
It will look like this:
![kép](https://user-images.githubusercontent.com/6050643/231096197-480dff4b-53b6-4bce-af86-27b4bf02732b.png)

In the PDF there is no IFRC logo in the header. Is it ok?
![kép](https://user-images.githubusercontent.com/6050643/231096335-7f7ede8b-bbac-46c7-a528-d588fbf07d12.png)

(In a similar one, PHiE Coordinator, there is)
![kép](https://user-images.githubusercontent.com/6050643/231096446-8ed1c8d5-1bdb-4ddc-890b-a966e5c559b0.png)
