### ISSUE TITLE
Incorrect url in the Surge Ops Toolbox

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2728]
Please change the url of the highlighted item:
![image](https://user-images.githubusercontent.com/68283148/231733026-72bfac90-cbe1-454b-9ec8-854bf9da4cc6.png)

The correct link:
https://ifrcorg.sharepoint.com/:f:/s/IFRCSharing/ElJyGf5pFExJgA8iwgkQXJIB4QWRL0EoDu4xGWsrOZFMCg?e=sUwrjV

**Comment by szabozoltan69** [comment]
Deployed to prod and staging.
