### ISSUE TITLE
Surge CoS - Livelihood and Basic Needs

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2735]
Please create a new _Role profile_ widget on the _Livelihood and Basic Needs_ page under a new _Rapid Response Personnel_ section and post the attached documents:
https://go.ifrc.org/deployments/catalogue/livelihoods

[Rapid Response Profile Livelihoods and Basic Needs Coordinator.pdf](https://github.com/IFRCGo/go-frontend/files/11292895/Rapid.Response.Profile.Livelihoods.and.Basic.Needs.Coordinator.pdf)
[Rapid Response Profile Livelihoods and Basic Needs Officer.pdf](https://github.com/IFRCGo/go-frontend/files/11292897/Rapid.Response.Profile.Livelihoods.and.Basic.Needs.Officer.pdf)

**Comment by szabozoltan69** [comment]
Deployed to Prod and Staging.
