### ISSUE TITLE
GO Rewrite

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-frontend#2819]
### Pages and sub-pages

- [x] Home
- [ ] Region
  - [x] Operation
  - [ ] 3W
  - [x] Risk Watch
  - [x] Regional Profile
  - [x] Preparedness - PER
  - [x] Additional Data
- [ ] Country
  - [ ] Operation
  - [ ] 3W (In Country Projects)
  - [ ] 3W (NS Projects)
  - [x] Risk Watch
  - [ ] Preparedness
  - [x] Preparedness - PER
  - [x] Country Plan
  - [ ] Additional Data
- [x] Emergencies
- [ ] Emergency
  - [ ] Emergency Details
  - [ ] Reports/Documents
  - [ ] Activities
  - [ ] Surge
  - [ ] Custom Tabs (up-to 2)
- [ ] Surge
  - [x] Surge Overview
  - [x] Operational Toolbox
  - [x] Catalogue of Surge Services
  - [x] Catalogue - Emergency Needs Assistance
  - [x] Catalogue - Basecamp
  - [x] Catalogue - Cash and Vouchers Assistance
  - [x] Catalogue - Community Engagement and Accountability
  - [x] Catalogue - Communications
  - [x] Catalogue - Health
  - [x] Catalogue - Information Management
  - [x] Catalogue - Information Technology and Telecom
  - [ ] Catalogue - Livelihood and Basic Needs
  - [ ] Catalogue - Logistics
  - [ ] Catalogue - Operations Management
  - [ ] Catalogue - Protection, Gender and Inclusion
  - [ ] Catalogue - Planning, Monitoring, Evaluation and Reporting
  - [ ] Catalogue - Relief
  - [ ] Catalogue - Security
  - [ ] Catalogue - Shelter
  - [ ] Catalogue - WASH
  - [ ] Catalogue - Other
  - [ ] Surge Alerts - All
  - [ ] All Deployed Personnel 
  - [ ] All Deployed ERUs
- [x] Preparedness
  - [x] Preparedness - Global Summary
  - [x] Preparedness - Global Performance
  - [x] Preparedness - Catalogue of Resources
  - [x] Preparedness - Operational Learning 
- [x] 3W
- [x] Risk Watch - Imminent
- [ ] Risk Watch - Seasonal
- [x] Resources 
- [ ] Account
  - [x] Account Information
  - [ ] Notification
  - [x] PER Forms
  - [ ] My DREF Applications
  - [x] 3W Forms 
- [x] All Operations
- [x] All Emergencies
- [x] All Field Reports
- [x] All Flash Updates
- [x] All 3W Projects
- [ ] All 3W Activities
- [ ] Field Report Details
- [ ] Flash Update Details
- [ ] Project Details
- [ ] Activity Details
- [x] Search
- [x] Login Form 
- [x] Register Form
- [x] Field Report Form
- [x] 3W Project Form
- [x] 3W Activity Form
- [x] DREF Application Form
- [ ] DREF Operational Update Form
- [ ] DREF Final Report Form
- [ ] Flash Update Form
- [x] PER Overview Form
- [x] PER Assessment Form
- [x] PER Prioritization Form
- [x] PER Workplan Form

### Others

- [ ] DREF Application PDF export
- [ ] DREF Operational Update PDF export
- [ ] DREF Final Report PDF export
- [ ] Improvements to UI components
- [ ] Translation (In / Out)
- [x] Base setup using Vite/Transcript/Rollup/Eslint/PostCSS
- [x] Improve build performance
- [x] Setup translation in library
- [x] Setup generated typings and integrate with request library
- [x] Setup authentication/routing/environment variables/CI
- [x] Update map library to work with mapbox styles
- [ ] Admin 2 Select input
- [ ] Setup endpoint for PDF export
- [ ] Documentation
- [ ] Backend chanagelog, breaking changes, migration guide for API
- [ ] Copy over changes done on go-frontend while the rewrite was in-progress
- [ ] Transform error from server to forms
- [x] Setup error handling for proper error response
- [x] Configure generation of types from OpenAPI specification for GO Backend
- [x] Configure generation of types from OpenAPI specification for Risk Backend

**Comment by frozenhelium** [comment]
Sneak peak available at: https://ifrc-go-nightly.surge.sh/
