### ISSUE TITLE
[PROD] Rich text editor warning/error message appears

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2824]
On the field report form, the rich text editor field shows a Tiny related error message:
![image](https://github.com/IFRCGo/go-frontend/assets/68283148/a9f132a2-8371-4d78-a90a-0ce6d6c47bbf)
Not sure, if it affects anything.

**Comment by szabozoltan69** [comment]
Is it sure that it is on prod?
I think the new staging domain was not registered yet. But I check both.

**Comment by szabozoltan69** [comment]
Now the approved domains are:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/7369c4b7-59fc-4170-b0c5-4621d1c51dae)

Please give a check if the error still occurs.
(If not, please give me an URL also.)

**Comment by szabozoltan69** [comment]
Now all the 4 rich text editor pages are working fine. (backend/frontend, Staging/Prod)
