### ISSUE TITLE
Scrape Key data from EPoAs pdfs and write to GO database.

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#283]
**Not in phase 2**

EPOA data currently exists as PDFs; waiting on numerical data source scraped from PDFs.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Is there currently any emergency data pulled from the EPoAs? I know there's been a plan for a scraper but not sure if it's ready. If there'd no data being pullet from the EPoA at the moment, let's leave this issue for phase 3.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC There is some kind of working PDF scraping now, yes. But to check or improve it, we can leave it for phase 3.

**Comment by szabozoltan69** [comment]
(The word "EPoA" does not occur in the code anyway.)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Good, I'm now labelling this as a Phase 3 issue.

**Comment by szabozoltan69** [comment]
Dear @dereklieu, I would like to ask some help from you concerning to this change request.
How could we integrate into the Django database these appeals and emergencies got by the https://github.com/IFRCGo/data-analysis scripts? I attach the results.

**Comment by szabozoltan69** [comment]
[output_pdf_scrapers.zip](https://github.com/IFRCGo/go-frontend/files/2983362/output_pdf_scrapers.zip)
[output_precrisis_api_scrapers.zip](https://github.com/IFRCGo/go-frontend/files/2983363/output_precrisis_api_scrapers.zip)

**Comment by nanometrenat** [comment]
Munu updating this ticket

**Comment by mmusori** [comment]
Standalone running, no integration to GO. @IM team to decide where data appears on GO.  The data to be written into a google sheet. This will be pulled into tableau for visualisation. Then iframed into GO. After this test then consider direct ingestation into GO. Script developed. Data being compiled into the GO d/b but work required on the post-processing manual clean-up and visualisation on GO.  Estimated effort to completion: 3-4 days

**Comment by nanometrenat** [comment]
@mmusori as the pdf scraping is happening in GO database in Prod can this ticket be closed now?
