### ISSUE TITLE
[PROD] DREF Final Report

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2847]
## Issue
DREF Final Report for Panama Floods (MDRPA017) is not exporting. When hitting Export" the result is blank. Seems that the bug is related to just this Final Report, others are exporting ok

## Steps to reproduce
This is the link to the final report mentioned: [MDRPA017](https://go.ifrc.org/dref-final-report/1/edit/)

@tovari @udaynwa  @frozenhelium

**Comment by szabozoltan69** [comment]
Backend side seems to be ok. On frontend style I see an undefined style issue:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/0f09d4a6-99e7-4d56-9742-d190701edd20)

**Comment by frozenhelium** [comment]
This should be addressed by https://github.com/IFRCGo/go-frontend/pull/2848

**Comment by udaynwa** [comment]
@anamariaescobar , the hotfix has been deployed to Prod. This should be fixed now.
