### ISSUE TITLE
Mapbox issue at admin2 map selection

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2850]
The admin selection on the map doesn't work in every case on
https://go-stage.ifrc.org/three-w/new

In certain cases, the admins cannot be selected by clicking on the map:
![image](https://github.com/IFRCGo/go-frontend/assets/68283148/09313e94-6dfa-4415-bf6c-cc88973683c2)

Analysis from @frozenhelium:
_sometimes, the mapbox tile request fails, and we are not able to select regions from map, the select input still works, but cliking from the map doesn't. This is an issue due to the nature of mapbox, and we couldn't find an easy fix at the moment._

Is there a way to make the service more reliable?

cc: @davidmuchatiza, @batpad

**Comment by szabozoltan69** [comment]
As I remember, there was a re-creation of territories in Afghanistan, and maybe some manual ID-change also happened on backend side (database side) for the overlapping/new entites.
A fresh re-creating of territories in Afghanistan could solve this issue.

**Comment by batpad** [comment]
Can you give me a bit more precise way to reproduce this problem?

@frozenhelium - let's chat about this? Maaaaybe another approach could be to use the geometries in our API instead of trying to get them via the Mapbox tiles? I'm not fully sure how that would work and that might require a fair bit of changes, but maybe that is an option?

cc @geohacker here.

**Comment by szabozoltan69** [comment]
https://go-stage.ifrc.org/three-w/new
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/b2f26bc1-0b75-4064-a0f8-0fd4b31b3479)
click "Select Province/Region"
And then select admin area.
:-) I could not reproduce the issue. All the territories could be selected, BUT I had to click to the name, not to the territory itself.

**Comment by batpad** [comment]
@frozenhelium might it help if we added an API endpoint that accepted a lat-long and returned the admin2 that contained it?

**Comment by geohacker** [comment]
> sometimes, the mapbox tile request fails, and we are not able to select regions from map

Can you paste the request that's failing? Are we using `queryRenderedFeatures`?
