### ISSUE TITLE
DREF Allocation form

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2851]
We need to create a new export that will be called "Allocation Request", this export applies to Application and Ops. Update. The option to export and download this form should appear on the account page on the 3 dots dropdown only once it has been Approved. Ideally the export will be a pdf.

Please find the export that we are trying to replicate here: 
[DREF Allocation Request TEMPLATE 1 (1).pdf](https://github.com/IFRCGo/go-frontend/files/11957726/DREF.Allocation.Request.TEMPLATE.1.1.pdf)

- [x] DREF Allocation is required for: Leave all the options even if we will be using only DREF operation and Emergency Appeal (for consistency, the other 2 options will be managed manually until we integrate Early action protocols into GO). Emergency Appeal will be ticked when the type of DREF is Loan and DREF Operation for the rest of types.
- [x] Appeal Manager: Comes from Submission --> Tracking data and contacts --> IFRC Appeal Manager --> Name
- [x] Project Manager: Comes from Submission --> Tracking data and contacts --> IFRC Project Manager --> Name
- [x] Country of Operation / National Society (Remove "/ National Society") --> Operation Overview --> Essential Information --> Affected Country
- [x] Name of Operation (as published) --> Operation Overview --> Essential Information -->  DREF Tittle
- [x] Disaster/Hazard Type --> Operation Overview --> Essential Information -->  Disaster details --> Type of disaster
- [x] Response type --> Operation Overview --> Essential Information --> if type of DREF is Imminent then "Imminent crisis", for the rest of types, use the Onset ("Slow Onset" or "Sudden Onset").
- [x] IFRC targeted assistance --> Operation Overview --> Essential Information --> Number of people targeted
- [x] The line "For Early Action Protocols" just leave as it is and no information will be populated yet (this will happen when we implement EAP, but we need to keep it for consistency)
- [x] National Society request date --> Operational Timeframes --> Date of National Society Application (always the one coming from the Application, even if the allocation form is for an Ops Update)
- [x] Disaster Start or trigger date --> Event Details --> Description of the event --> Date of the Event/Approximate date of impact (always coming from the Application, even if the allocation form is for an Ops Update)
- [x] Operating  implementation period --> Submission --> Timeframes --> Operation timeframe for Application and Total operating timeframe for Ops Update
- [x] DREF Allocation Request CHF --> Operation Overview --> Essential Information --> Requested Amount in CHF (For Application) and Operation Overview --> Essential Information --> Additional Allocation Requested (For Ops Update)
- [x] Previous Allocation(s) CHF --> 0 for Application, for Ops Update Operation Overview --> Essential Information --> Budget Allocated so far
- [x] Total Allocations CHF --> Operation Overview --> Essential Information --> Requested Amount in CHF (For Application) and Operation Overview --> Essential Information --> Total DREF Allocation (for Ops Update)
- [x] To be allocated from --> Anticipatory Pillar if the type of DREF is Imminent, Response Pillar for the rest.
- [x] DREF Regional Focal Point Name --> We need to include the DREF Regional Focal point contacts (like we have for the Loan) to all the forms, and bring this information here.

@tovari  @udaynwa  @frozenhelium

**Comment by frozenhelium** [comment]
@anamariaescobar Should we allow users to edit the fields in **To be completed by the DREF Focal Point** (from sample PDF) in the export pdf (In the one we will be creating)? Or, only the section **To be completed by DREF Appeal Manager** can be filled by the user?

**Comment by anamariaescobar** [comment]
@frozenhelium 
**To be completed by the DREF Focal Point** should come from the forms as stated on the previous ticket stated.
**To be completed by DREF Appeal Manager** should be left blank, this will be completed through the E-signature proces (outside of GO) once the form is exported to PDF.

Does this makes sense? Let me know if a quick call will help!

**Comment by anamariaescobar** [comment]
Attaching the allocation form in xlxs 
[Allocation Form.xlsx](https://github.com/IFRCGo/go-frontend/files/12103362/Allocation.Form.xlsx)

@udaynwa @frozenhelium @tovari

**Comment by udaynwa** [comment]
@anamariaescobar , this is deployed in the Staging! Please have a look! Our first impression is that overall it looks good, but it overflows to 2 pages when we try to print it. So, if its primary purpose is to be printed, then we might have to do some adjustments to fit it on one page, otherwise, it looks good. Do let us know what you think.

**Comment by anamariaescobar** [comment]
Heyy @udaynwa, indeed it looks good some feedback:

- [ ] Align the tittle "DISASTER RESPONSE EMERGENCY FUND" to the center of the cell, make it all capitals and use Montserrat 24
- [x]  Align the tittle "Fund Income Allocation Request" to the center of the cell and use Montserrat 18
- [x] Center the text "To Be Completed by The DREF Focal Point" and use Montserrat 14
- [x] Format each one of the "name" fields with grey
- [x] Format each one of the fields with information with light blue
- [x] Remove row above "Country of Operation" row
- [x] Under "IFRC Targeted Assistance", where the number will be add the word "people" at the end
- [x] For Early Action Protocols, on the second box name add "Early Action Protocol Reference"
- [x] For Early Action Protocols, on the second box name change it to "Operating Implementation Period"
- [x] For DREF operations and Emergency Appeals, under "Operating Implementation Period", where the number will be add "months" at the end
- [x] For Allocation CHF, add "CHF" before each of the number.
- [ ] DREF Regional Focal Point Name, this field should be added in all the forms (application, ops update and final report, regardless of the type of DREF, at the end where the contacts are) and the name should populate that field on the Allocation request
- [x] Switch date and Signature
- [x] Center "To Be Completed By DREF Appeal Manager"
- [x] Is it possible to make the rest of the cells white so it resembles more the original?
- [x] it wont be used for printing, but we do need to use it in Adobe e-signature, so we do need it to fit in only one page.

Attached one export with the changes requested:

[Afghanistan Biological Emergency 2023 -test allocation form 17-08-23 Allocation Form - APPLICATION.xlsx](https://github.com/IFRCGo/go-frontend/files/12408859/Afghanistan.Biological.Emergency.2023.-test.allocation.form.17-08-23.Allocation.Form.-.APPLICATION.xlsx)

@tovari

**Comment by udaynwa** [comment]
@anamariaescobar thanks for putting up the list. We'll go through them and start their implementation.

**Comment by anamariaescobar** [comment]
Thank you for all the work on this!! a couple of comments on this:

- [x] "Dref Allocation is requested for"  should be renamed to "DREF Allocation is requested for" (DREF should always be in capital letters)
- [x] The export is still showing 2 pages, we need it to fit in just 1
- [x] The tittle "DISASTER RESPONSE EMERGENCY FUND" looks too big, maybe make it a 20 instead of a 24
- [ ] Allocation CHF part is not pulling the data from the forms, also we need to add CHF in each one of the boxes before the numbers
- [ ] DREF Regional Focal Point Name, this field should be added in all the forms (application, ops update and final report, regardless of the type of DREF, at the end where the contacts are) and the name should populate that field on the Allocation request
- [x] The allocation form should be able to be exported even if the form is not approved yet (sorry, this one is a change from the original requirements!)

@udaynwa @frozenhelium @tovari

**Comment by udaynwa** [comment]
@anamariaescobar , the latest batch of feedback has been implemented and pushed to Staging (except for a few minor details which are in progress). The checkboxes have been updated accordingly.

One question on the `DREF Regional Focal Point Name` field. From which field in the DREF forms should we populate this field? 

cc @frozenhelium @tovari

**Comment by anamariaescobar** [comment]
Thanks Uday!!
Changes look great!
For DFREF Regional Focal point, we need to include this field on all forms (we already have it for the Loan type) it should be included at the last page, where all the contacts are (just like in Loan type).

Let me know if a call would help!

@udaynwa @frozenhelium @tovari

**Comment by tnagorra** [comment]
@anamariaescobar Just do double confirm when we say "on all forms", do they include "dref application form", "dref operational options" and "dref final form"?

**Comment by anamariaescobar** [comment]
yesss!! @tnagorra :)
