### ISSUE TITLE
[PROD] Rapid Response Personnel timeline pop-up window

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2864]
We use to have a pop-up window when hovering the mouse on the red bar of the timeline:

![image](https://github.com/IFRCGo/go-frontend/assets/68283148/248a627e-dfc3-4830-8433-2a109aa79834)

The info pop-up is not available anymore.

**Comment by udaynwa** [comment]
### Link to replicate the issue 
- https://go.ifrc.org/emergencies/6479#surge

### Info in the pop-up
- Person 
- Country 
- Date

**Comment by batpad** [comment]
The last change made to this part of the code was https://github.com/IFRCGo/go-frontend/commit/de4bcc89250144fc7fd7c9180ffb9b0bc1eb6a06#diff-887937255ada86e51215a92196a4cce98c39266d7cc830514a338ed7752841deR251

Though it's a bit unclear to me how that could have broken anything.
