### ISSUE TITLE
[PROD] DREF translation in GO

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2867]
## Issue
When we launched the translations in GO, we blocked that the users can change the language when editing a DREF Application, but the user can still start a New Application in a different language. It is also possible to Export a DREF in progress in a different language than the starting one (we actually want to keep this feat.)

## Steps to reproduce
DREF for Cameroon Floods was started in french, link here: [Cameroon Floods](https://go.ifrc.org/dref-application/188/edit/)

*If applicable, add screenshots to help explain your problem.*
![image](https://github.com/IFRCGo/go-frontend/assets/69478743/8ab0f306-43c0-4074-a5dd-96c1fc5785f1)

## Expected behaviour
We should block the users from starting a DREF application in a different Language than English while we revise the correct workflow for this. We still want to maintain the option for users to export in a different language an application that is in progress.

@tovari @udaynwa

**Comment by tovari** [comment]
Thanks @anamariaescobar. We also need to educate the users to enter data in English. We can enforce changing the UI to English when they start an application, but we cannot do much, if they enter text in other than English language. 

cc: @marcovvu1

**Comment by frozenhelium** [comment]
@anamariaescobar We can block the new DREF form as shown below. It should be enough right?
![2023-08-10-165408](https://github.com/IFRCGo/go-frontend/assets/4931541/60c64d77-c3ab-429f-8de8-d40cbfe74801)

**Comment by anamariaescobar** [comment]
That works for us while we figure out the correct behavior flow! The only thing is, can we add "at the moment" at the end of the first line "DREF forms can only be created in English" ?

Thanks @frozenhelium :)

**Comment by frozenhelium** [comment]
@anamariaescobar Sure will do!

**Comment by udaynwa** [comment]
@anamariaescobar this has been implemented and pushed to Staging.

cc @frozenhelium

**Comment by anamariaescobar** [comment]
It looks good!! ready to be pushed to Production from my side!! @udaynwa @frozenhelium
