### ISSUE TITLE
[PROD] DREF Final Report section missing

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#2870]
## Issue
For the DREF Final report we are experiencing 2 issues:

- [x] In the Account page, once the Final Report there is no option on the dropdown menu with the 3 dots to export the report, it is only doable if you go into the form.
- [x] The section OPERATION REPORT --> FINANCIAL REPORT (which includes 2 fields, an attachment and a text field) doesn't appear in the export.

## Steps to reproduce
https://go.ifrc.org/dref-final-report/26/edit/, I added some text and attachments to this 2 fields to test (I deleted them afterwards as this is an actual Final Report being worked in the moment).

## Expected behaviour

- [x] In the Account page, once the Final Report there should be an option on the dropdown menu with the 3 dots to export the report.
- [x] The section OPERATION REPORT --> FINANCIAL REPORT (which includes 2 fields, an attachment and a text field) should appear in the export.

@tovari @udaynwa

**Comment by udaynwa** [comment]
We will look into them. Thanks for the list, @anamariaescobar

**Comment by udaynwa** [comment]
@anamariaescobar , for confirmation, are we adding the `Main Donors` field at the end of the form after `Cover image` field in `OPERATIONAL OVERVIEW` tab of the Final Report? 
![Screenshot 2023-08-09 at 14 29 48](https://github.com/IFRCGo/go-frontend/assets/72339626/8a94ec63-9a9d-40cb-8ada-6ece4ef2fa3c)

**Comment by anamariaescobar** [comment]
@udaynwa, I have checked the changes pushed to staging and they look good! 
And for the Financial Report, yes, let's add a link for now while we work on a longer term solution for this issue!

Thank you so muchhh!!

**Comment by udaynwa** [comment]
@anamariaescobar , we have added a link that will open up the whole Financial Report document. It has been deployed to Staging. 
<img width="479" alt="Screenshot 2023-08-11 at 19 26 54" src="https://github.com/IFRCGo/go-frontend/assets/72339626/053ed752-5d67-4708-b12f-0bcf7ab5b8c9">

cc @frozenhelium

**Comment by anamariaescobar** [comment]
ok, lets go with this one for now, can we add "Click here for the complete financial report"?

@udaynwa @frozenhelium

**Comment by udaynwa** [comment]
@anamariaescobar , it's done and pushed to Staging ✅

**Comment by anamariaescobar** [comment]
looks good!! can we send it as a hotfix? @udaynwa

**Comment by szabozoltan69** [comment]
(Maybe together with this? https://github.com/IFRCGo/go-frontend/pull/2884 )

**Comment by anamariaescobar** [comment]
Thanks @szabozoltan69 , weirdly the new Donors field is not appearing on Production but yes in Staging:

- [ ] For DREF final reports, we will add in the overview section, at the end, a field called, Main Donors, with a long format text box with a limit of 500 characters. In the PDF export, the text will appeal below the overview table in page one, the font will be in open sans italic, with a size of 10. 

Prod: 

![image](https://github.com/IFRCGo/go-frontend/assets/69478743/5b3bc9d5-6fd6-46df-9744-8bfb48f0855c)

Staging:

![image](https://github.com/IFRCGo/go-frontend/assets/69478743/50e99592-c050-46d3-984a-7fa850c09689)

**Comment by szabozoltan69** [comment]
Unfortunately the hotfix (which did not contain all changes of frontend develop branch – certainly, because there are half-done tasks there) did not contain all the changes that are needed to appear the **Main Donors** field on Prod.

What I checked:

- On develop:

Wed Aug 9
commit 59f991f428de6a34207d906a3799c6de1aa698a6
Author: puranban <puranban77@gmail.com>
    Add final report main donors field
This commit is not on master.

- And:

on develop this is in lang.js:
lang.js:  finalReportMainDonor: 'Main Donors'
But finalReportMainDonor is not in master (so not in Prod).

**Comment by szabozoltan69** [comment]
@frozenhelium please give it a check, I think it can be solved with a bit of effort.

**Comment by szabozoltan69** [comment]
The new hotfixes fixed the absence of the "Main Donors" text area.

**Comment by szabozoltan69** [comment]
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/78bf1076-973d-4e1e-89ce-2deeea825a42)
