### ISSUE TITLE
Send content type to translation server (html, txt)

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-frontend#2890]
Awaiting for API endpoint schema

**Comment by szabozoltan69** [comment]
Zoltan Kapocs created the needed change on translation api.
![kép](https://github.com/IFRCGo/go
[swagger.zip](https://github.com/IFRCGo/go-frontend/files/12428069/swagger.zip)
-frontend/assets/6050643/cc9f5be8-6af5-4555-b50a-765f4ff55f37)

**Comment by szabozoltan69** [comment]
[swagger.zip](https://github.com/IFRCGo/go-frontend/files/12428073/swagger.zip)

**Comment by thenav56** [comment]
This is done.
