### ISSUE TITLE
[PROD] FR form - Emergency search field

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#2901]
The emergency search field on the Field Report form doesn't provide all relevant emergencies. 
https://go.ifrc.org/reports/new

Sample emergencies not showing up in the field:
VEN: Anticipatory Action operation
ISR: Civil Unrest - 2023-09 - Eritrean irregular migrants civil unrest in Tel Aviv
ZAF: Fire - 2023-08 - Structured Fires in Johannesburg city
CUB: Cyclone - 2023-08 - Huracan Idalia Cuba

Due to the issue, users cannot attach filed reports to existing emergencies, thus they create new emergencies, which is not ideal.

**Comment by szabozoltan69** [comment]
A full site elasticsearch index update was run.
After that "ISR: Civil Unrest - 2023-09..." appears in searches, but the other 3 not.
Investigating the reason...
It would be good to check if "**CUB: Cyclone - 2023-08 - Huracan Idalia Cuba**"  event (id: 6633) is there in index or not.

**Comment by szabozoltan69** [comment]
My hunch: there is a limitation of the arriving data in one request. We can set higher value via "size", but this method also has a top limit. So some (bigger number) events can not arrive in one search request. (And we do not use more than 1 search request.)

**Comment by batpad** [comment]
cc @thenav56 @samshara - would be great to get your eyes here to see if there's any ideas of what might be happening here.

**Comment by szabozoltan69** [comment]
This should be a permission issue.
After setting the mentioned "CUB:..." event (from Membership) to Public (and indexing), it was found:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/7a5aa4f0-af2f-4017-9e40-eaf8717ca6b3)
but after setting it back to Membership (and indexing):
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/836135cd-3b3a-4c8f-8606-406c40cf2dea)

This last search should also find the Huracan Idalia, due to I was logged in (as a member).

**Comment by szabozoltan69** [comment]
Is it possible that in the search request no user identification (no token) arrives from frontend to backend, so no chance to have other query than public ones? @frozenhelium

**Comment by szabozoltan69** [comment]
In debug of [HayStackSearch](https://github.com/IFRCGo/go-api/blob/develop/api/views.py#L116-L124):
if self.request.user.is_authenticated:

```
p self.request.user
<django.contrib.auth.models.AnonymousUser object at ...>
```

**Comment by tovari** [comment]
In some cases we cannot find even public emergencies. E.g.:
[LBY: إعصار - 2023-09 - Weather Situation ( Floods- Heavy Rains ) in Libya as a result of Hurricane Danielle](https://goadmin.ifrc.org/en/admin/api/event/6647/change/)

**Comment by szabozoltan69** [comment]
The reason for this last one can be an imperfect index update. After a manual update of search indices it can be found:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/ed4d0cd1-c481-4557-a857-84a800f6ac74)
