### ISSUE TITLE
[PROD] Surge table loading issue

### ISSUE THREAD

**Issue by JonathanGarro** [IFRCGo/go-frontend#2911]
The open surge alert table on [this emergency](https://go.ifrc.org/emergencies/6646/surge) is rendering elements on top of each other: 

![Screen Shot 2023-10-31 at 02 27 07 PM](https://github.com/IFRCGo/go-frontend/assets/8890661/8834b3c2-4ad6-4a87-a8ee-cbdfa9fbac81)

**Comment by tovari** [comment]
This is on Mac and Safari, right?

**Comment by batpad** [comment]
Unfortunately, I am able to confirm the issue on Safari on Mac. Safari v16.5.2 .

This seems to be fine for me on both Firefox and Chrome, so the issue seems to be Safari specific.

**Comment by batpad** [comment]
Safari is such a weird browser. If I open Inspect Element, then scroll to the bottom of the page, then scroll back up, the CSS some-how "fixes itself". Am a bit worried this might be a browser bug.

**Comment by JonathanGarro** [comment]
> This is on Mac and Safari, right?

Yes - I actually rarely use Safari but just happened to be when I caught this issue.

**Comment by tovari** [comment]
Is this resolved now, @batpad ? Thanks

**Comment by batpad** [comment]
> Is this resolved now, @batpad ? Thanks

I have a PR up for it that I **think** fixes the issue, but awaiting review and testing from either @samshara or @frozenhelium : https://github.com/IFRCGo/go-web-app/pull/287

**Comment by batpad** [comment]
> I have a PR up for it that I think fixes the issue

To clarify, it definitely seems to fix the issue for me in Safari. And it **seems** fine in both Chrome and Firefox with the change. But I haven't tested all edge cases or know if this might impact something else.

**Comment by batpad** [comment]
(This was auto-closed I think because of my commit message - keeping this open until we've tested and verified the fix.)

@tovari this should be ready to be tested on staging.

**Comment by nanometrenat** [comment]
@JonathanGarro can this be closed?

**Comment by JonathanGarro** [comment]
Yes, this looks normal in safari now.
