### ISSUE TITLE
[PROD] Emergency key figures bug

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#2914]
## Issue
I assume with the new update (which is great btw!) the key figures for emergencies now doesn't accept commas and just extracts the number before the comma.

For example for Libya (which I have now fixed), the backend looked like this:
<img width="1407" alt="Screenshot 2023-11-06 at 09 22 01" src="https://github.com/IFRCGo/go-frontend/assets/6359748/1c4d8b3a-4d49-4c63-b68b-fcf8e7cecb14">

Which was rendered on frontend like this:
<img width="1427" alt="Screenshot 2023-11-06 at 09 21 43" src="https://github.com/IFRCGo/go-frontend/assets/6359748/2de2d4b6-b787-4239-9866-50cde6b15697">

## Examples

- [Libya Storm Daniel](https://go.ifrc.org/emergencies/6647/details) (fixed)
- [Sudan Crisis](https://go.ifrc.org/emergencies/6414/details) (not fixed!)

Easy to fix per emergency by just removing the commas but flagging as bug because there may be numerous emergencies affected that are no longer actively worked on.

## Expected behaviour
Should display the whole number. I wonder if this used to be a text field that is now a number field so others may be badly affected e.g. People affected = 1 million. Will this render? Will it just say one?

## Impact
Questions of data quality for past emergencies and reputational impact.

## Is there a workaround?
Remove commas for the figures of each emergency - fine for those currently being worked on but not for past emergencies.

**Comment by batpad** [comment]
@jhenshall thanks much for the report!

@samshara @udaynwa this does seem like a pretty critical issue - is it possible to look at it soon? Thanks!

**Comment by szabozoltan69** [comment]
Just one notice:
 - from backend the formatted numbers arrive. E.g in this case: https://go.ifrc.org/emergencies/6414/details
 in Inspector: 
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/41c76ab0-40de-40d5-9ca8-219c8d193c7f)
we have pre-formatted numbers:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/cfa810a7-c566-4bc1-ae33-bf8a2ee8a88d)
(Why? Why they are not simply 9000000 or 4295092?)
If it is by intention, then on frontend we should fix these:
![kép](https://github.com/IFRCGo/go-frontend/assets/6050643/7fb43763-8851-4edf-97f6-63ae6fdefc71)

**Comment by samshara** [comment]
@szabozoltan69 we should ideally store these as numeric fields and format / internationalize  them as necessary.

**Comment by batpad** [comment]
@samshara am afraid it might not be so straightforward to do on the backend right now, especially since I think some Key Figures can be text - this would also involve a lot of migrating of past data.

Can we please fix this on the frontend for now and then discuss what the longer term solution should be, as this is a pretty critical bug?

**Comment by samshara** [comment]
> @samshara am afraid it might not be so straightforward to do on the backend right now, especially since I think some Key Figures can be text - this would also involve a lot of migrating of past data.
> 
> Can we please fix this on the frontend for now and then discuss what the longer term solution should be, as this is a pretty critical bug?

@batpad we have fixed on the client. Thanks on the clarification.

**Comment by szabozoltan69** [comment]
Fixed via https://github.com/IFRCGo/go-web-app/commit/4791abe8ff204b2b6001de908092b6478006c41e
