### ISSUE TITLE
Make country pages more accessible

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#306]
@ascalamogna when you have a moment, we should talk about this. Country pages are really hard to find right now.

**Comment by dereklieu** [comment]
In addition to #315, I think we should create a country index page that just lists all of the countries we have in the system. This page would be in the top navigation and would lead to something like this:

http://data.ifrc.org/fdrs/societies

@ascalamogna wdyt?

**Comment by ascalamogna** [comment]
@dereklieu I'd rather not clutter up the navigation with even more lists and pages. This was one reason in phase 1 we added the search feature. We should make sure countries are surfaced better in the tables, for example in the appeals and drefs tables, we can remove name and add a country column.

I also think it's a good idea to highlight the countries on region pages. Currently, it's hard to know what countries are in that region. I think we could highlight on the map and also add a module that lists the countries in that region.

**Comment by dereklieu** [comment]
We now have a module on region pages, showing countries within that region:

![screen shot 2018-07-06 at 4 52 09 pm](https://user-images.githubusercontent.com/1590802/42399748-0acba87e-813d-11e8-8ac3-f4f4bb466954.png)

Tooltips now also link to countries.

**Comment by dereklieu** [comment]
Closed #306
