### ISSUE TITLE
Field reports should help the issuer decide which emergency to attach to

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#316]
A modal or UI should appear if a user has not attached an emergency to a field report. The modal should list the 5 most recent emergencies for a given type, in a given country.

Field report logic is quite complex already so this is not a trivial task to get right.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Shall we merge this with #316?

**Comment by szabozoltan69** [comment]
Now emergency is searchable in Field report form, and selection none of them is allowed also.
