### ISSUE TITLE
Country names and ISO properties should be unique

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#317]
We shouldn't allow duplicate country names and ISO properties.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu I would like to raise a further issue. Where is the current map in the dev environment pulling the country names? Before launching, we must make sure that the country names are in line with the Movement conventions. Additionally, we must style the font differently for disputed territories, most obvious of these being Kosovo, Western Sahara and Taiwan. We may not even need labels for some smaller disputed regions such as the Falkland or Kuril Islands.

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC country names are using the default mapbox labels layer, so they are not pulling from our shapefiles.

Last night I uploaded a new tileset that contains the boundaries we discussed. You can find that at the link below. There are also centroids in that tileset with name data for each admin 0 and 1 feature, which you can use to create labels.

https://www.mapbox.com/studio/tilesets/go-ifrc.go-tiles-v3/

The Go dev site is now using this new tileset and applying a very basic style for disputed and undisputed boundaries. You can see that [here](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/get-new-map.js#L51-L87).

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Thank you for clarifying this, I was actually thinking that the labels are from some default layers. I have been doing some experiments with the labeling.

However, it looks like the country names have been pulled from the NAME (Column 5) of the ICRC datasets. It sounds very formal to talk about "Republic of Albania" or "People's Republic of Algeria". I suppose we use the names in the NAME_ICRC (Column 3) as those are the ones used in all other documentation.

There's also one country whose name needs updating: Swaziland is now officially eSwatini - it would be good to reflect this on our maps.

**Comment by LukeCaley** [comment]
Closing this as captured #415
