### ISSUE TITLE
Situation reports should have a category type that they can be filtered by

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#318]
A situation report should have a category type. You should be able to filter by type in the front-end.

Steps:

1. Create a table for category types that can be user-modified in the admin.
2. On every emergency, fetch the categories table, and use it to generate the set of dropdown options for filtering the reports.
3. Dropdown allows user to filter the situation reports by category.

**Comment by dereklieu** [comment]
@szabozoltan69 

http://dsgocdnapi.azureedge.net/api/v2/situation_report/?limit=100&event=2

Right now this event has almost 100 situation reports. It should be possible to add another filter, to filter reports by type. For example:

http://dsgocdnapi.azureedge.net/api/v2/situation_report/?limit=100&event=2&type=foo

This will involve adding the table to the model in `api`, linking it to the situation reports, updating the serializer to include a `type` field, and updating the viewset so that the type can be filtered on.

**Comment by szabozoltan69** [comment]
Ok, I begin to work on it.

**Comment by szabozoltan69** [comment]
Now I made a first commit, please check it, @dereklieu.
https://github.com/IFRCGo/go-api/compare/sitreptype?expand=1

**Comment by dereklieu** [comment]
@szabozoltan69 Can you also include a test that performs the queries against the API and gets a filtered result back?

**Comment by szabozoltan69** [comment]
Ok, it sounds good.

**Comment by szabozoltan69** [comment]
Done. I don't understand why the circleci test fails; for me it runs fine.

Other: Why can't I see this in /docs of the new "type" field comment?
    """ Document type, to be able to filter Situation Reports """
