### ISSUE TITLE
ERU Types

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#32]
Types of ERU:

Logistics
IT & Telecommunication
Water & Sanitation: Module 15
Water & Sanitation: Module 40
Water & Sanitation: Module Mass Sanitation 20
Basic Health Care
Referral Hospital
Rapid Deployment Hospital
Relief
Base Camp

@dereklieu @danielfdsilva @matthewhanson

**Comment by dereklieu** [comment]
@ascalamogna In the field report form, do they just need the option to select one or more of these? Or do they also need to be able to add a number or text to each of these?

**Comment by ascalamogna** [comment]
@dereklieu for each ERU they need to select a type from a list of options (just one type per ERU) and a number of units for each type of ERU.
