### ISSUE TITLE
Split country profile into two columns

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#322]
One should be country profile, the other should be national society details.

Change wording so that users know it's both country and national society details.

**Comment by LukeCaley** [comment]
Add hyperlink to the sources (e.g. FDRS, World Bank, etc) and move to the bottom.
Three columns with a header for each: country profile, National Society key figures and IFRC operations in that order left to right across the head of the page
@dereklieu can you also double check the correct key figures are being pulled from FDRS, notice that blood collected is still in there for instance

**Comment by mmusori** [comment]
The split has been done. The source is displayed but the source name is not hyperlinked

**Comment by LukeCaley** [comment]
"Targeted people in ongoing operations" should read '"Targeted people in ongoing emergency operations" to avoid confusion with development activities

**Comment by dereklieu** [comment]
@LukeCaley sometimes the most recent year for a particular statistic is prior to the most recent year from another statistic. We use the most recent year available for every statistic.

Ie GDP might be from 2016 while the API only offers infant mortality as recently as 2014.

@mmusori the source we're using is the FDRs API endpoint, which is password-protected. We don't expose the password to end users, even if they're logged in. What should the source name link to?

**Comment by LukeCaley** [comment]
@dereklieu Would there be any way to add reporting date in brackets and light text after each figure then?  

Still need to add a hyperlink to FDRS next to the source.

**Comment by mmusori** [comment]
@dereklieu we can link it to the FDRS webpage.
