### ISSUE TITLE
Go to include a flexible, user-controlled charting library

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#324]
**This is not part of phase 2.**

Context: We currently bundle and use [Recharts](http://recharts.org/#/en-US/), a charting library that provides out-of-the-box functionality for many types of graphics, for the existing Go charts.

A request was made to allow admins to specify which charts to place, and where, essentially building a user-defined charting functionality into Go. 

An admin should be able to define:

1. What type of chart they'd like.
2. What type of data they'd like.

In my opinion, this is exactly the functionality that services like Tableau provide. Tableau and others have built entire businesses around giving non-technical users the ability to generate charts and graphics. I think whatever solution we could build internally would likely fall short of existing tools. 

Here is a rough estimate of the lift. I'll categorize things by easy, medium, or hard. Easy items can be done in an hour or so. Medium items will take about a day. Hard items can take up to 2 days. This is all assuming a high level of familiarity with Go. Time estimates will increase with lower familiarity.

1. In the API, create a chart model: **Medium difficulty**. The model should specify the different combinations of data and charts that can be made available. IE, does the data have a time component? If so, it can be used in a line chart. If not, it can be used in a pie chart, etc. These have to be defined for every combination of charts and data that you'd like this system to support.

1. In the API, attach the chart model as a relation to relevant objects: **Medium difficulty**. IE, should there be user-defined charts on an emergency page? If so, the chart model must have a relation to the emergency table. The emergency object's API response must also include any attached chart objects.

1. In the front-end, create a module to decode each chart object it receives: **Medium - hard difficulty**. IE, if the chart object specifies a chart should use monthly appeals data, this module should know which API endpoint to query for that data. Does it need to be filtered by region or country? If so, those filters should be applied. Does it need to be filtered by DREF/Appeal? If so, those filters should be applied. This task gets harder the more charts and data combinations need to be supported.

1. For each chart and data combination, create a chart module to handle that: **Hard difficulty x # of charts**. For example, something should be able to output a different graphic for monthly appeals vs monthly emergencies. This includes getting the axis right, showing relevant tooltips for the different data pieces. 

1. Create a style module on the Go page that will allow for an arbitrary number of charts, while maintaining visual and readability standards: **Hard difficulty**. To create a system where someone can have 1 or 7 charts on a page will take some design work and thinking. We're seeing this now in the situation reports: the requirements for displaying 5 are different from displaying 100. 

1. Testing the system to make sure it works properly: **Hard difficulty**. Giving users the ability to combine arbitrary data into charts can be error-prone, even if just choosing from a list of pre-defined combinations. Choices need to be made on what to do if data is lacking, for example.

**Comment by nanometrenat** [comment]
Closing this ticket due to elapsed time and not on current priority radar - will reopen or create new issue if prioritised for action.
