### ISSUE TITLE
Improve the default Django admin view

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#328]
I think we can pretty easily change the header. Other changes will add to the lift.

**Comment by LukeCaley** [comment]
A banner should be enough for now - as long as users are aware they are still in GO.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Is there any possibility to add a banner on the Django log-in? If not (yet), let's leave this to phase 3.

**Comment by szabozoltan69** [comment]
It should be possible according to http://books.agiliq.com/projects/django-admin-cookbook/en/latest/logo.html – I make it this week.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Very good.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Done. If you want some colors otherwise, please tell me.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Looks very nice. I'm closing the issue.
