### ISSUE TITLE
Include history of record updates

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#329]
**Not in phase 2**

There are modules that provide functionality to save the previous states of any create, update, and delete operation. This is one example:

https://django-simple-history.readthedocs.io/en/latest/index.html

This would allow you to, for example, revert a delete on a model.

For analysis, I don't think this module out-of-the-box gives you an API endpoint for all the historical revisions of an object. So if you wanted the front-end to query every change to a specific report, you would have to build that separately.

One consideration is that this functions using the Django's `post_save` signal, which executes something immediately after a record is saved. In the past we've had issues using `post_save` on objects, which have led to bugs. Some examples:

1. Elasticsearch timing out and showing an error message (but the model still gets saved).
1. Bulk imports failing or slowing down considerably as each update needs to wait for an accompanying trigger action, which essentially doubles or triples the number of database queries.
1. Many-to-many relations not being set on `post_save`. When an emergency is saved, because of the nature of many-to-many relations, the trigger function does not have access to the emergency's countries. Unless the history module I linked to above has some way around this, this means that history records would lack these many-to-many relations.

**Comment by dereklieu** [comment]
I don't think the issues I laid out above are insurmountable, however they contribute to additional integration and testing requirements for this feature.

**Comment by nanometrenat** [comment]
Closing - latest audit trail conversations being tracked under https://github.com/IFRCGo/go-api/issues/572
