### ISSUE TITLE
In emergency page, specify data source as field report where applicable

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#330]

**Comment by mmusori** [comment]
Specifying  data source for  field reports in emergency page is not working. Lionel created a field report Test 2 Africa but the source is not shown. https://dsgoproxyapp.azurewebsites.net/emergencies/3180

**Comment by LukeCaley** [comment]
Emergency pages should display _something_ (static map as placeholder for now) to the right of the appeal data.

**Comment by LukeCaley** [comment]
Situational overview "show more" link provides the rest of the text.  this is not highlighted so difficult to pick up.  should have light highlighting.
Source should have links and not just say "emergency"

**Comment by dereklieu** [comment]
@mmusori sorry, I'm not understanding you. The field report source is shown below, with a link to the field report itself. Can you show me where this isn't working?

<img width="548" alt="screen shot 2018-07-22 at 10 46 10 pm" src="https://user-images.githubusercontent.com/1590802/43054761-28eae308-8e01-11e8-9443-25470439ec5a.png">

**Comment by dereklieu** [comment]
@LukeCaley when the source says 'emergency' it is coming from the record that is represented by the page you're already on. We don't want to have a link to the page you're currently on. It's just there to distinguish from field report sources, which do make sense to link externally (and do). Maybe changing the text would make more clear?

**Comment by LukeCaley** [comment]
@dereklieu I meant the right side of the banner above the emergency page, when there is no data entered from a field report, e.g.
![emergency-gap](https://user-images.githubusercontent.com/7791954/43078569-8ef11e3c-8e93-11e8-97e9-e5d3565c1fff.PNG)

**Comment by dereklieu** [comment]
@LukeCaley Yes, I was referring to your point about the "emergency" source

>Source should have links and not just say "emergency"

I made a separate ticket documenting your proposal to show a placeholder map in that space. https://github.com/IFRCGo/go-frontend/issues/365 Let's discuss that there so we can keep a single ticket to a single deliverable.
