### ISSUE TITLE
Emergency pages show deployments 

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#335]
If an emergency has deployments regarding it specifically, it should show them.

**Comment by dereklieu** [comment]
Since we've split deployments into four separate tables, it's not easy to query them all or have them appear in a single module. I've suggested we prioritize ERU's, and only show these if they are deployed to a specific emergency. Waiting on reply.

**Comment by LukeCaley** [comment]
I have to admit I'm a bit confused as to why RDRT, HEOPS and FACT were split in the first place. They are all personnel and have mostly the same fields.  I will check with Surge team (who will manage this area of the site) but can you let us know how easy it would be to change this to display as one table for personnel with an additional field called 'Surge level' to which we add Global (for FACT and Heops) and Regional (for RDRT)?

Could it then be possible to have a table for ERUs and Personnel on the emergencies page?

**Comment by dereklieu** [comment]
In hindsight splitting the personnel wasn't the best choice. I don't think we were clear at that point what the different types of personnel where or how they would be used or managed. It would take a bit of time, but not much, to create a new personnel table that has these fields, and switch both the admin and site to reflect this. So we would have one table for personnel on both the deployments and emergency pages.

We would lose any data we currently have in these three tables, but it doesn't look like there's much there at the moment.

**Comment by LukeCaley** [comment]
That would be my preference but will double check with surge and get back to you.

In terms of existing data, could we not export, merge, add the 'surge level' field and then bulk import?  If not, how many records are we looking at?

**Comment by dereklieu** [comment]
Judging by the number of records in the production database, it would be faster to do this by hand.

Bulk imports unfortunately are more involved than taking data from one side and plugging it in the other. We have to create custom scripts for this, akin to our scrapers, because each record is interconnected with emergencies, regions, countries, etc.

**Comment by mmusori** [comment]
From the Surge team : FACT and RDRT/RIT should be merged. Reservation on HEOps.  Request for mocks up of how different options would look for more informed decision making.

**Comment by dereklieu** [comment]
@mmusori each HEOP would have a deployment with a single 'deployed person.' So this would say 'HEOP person' and each record would have only one of them filled out. The empty ones would show but they would leave them blank.

<img width="1391" alt="screen shot 2018-07-22 at 10 43 33 pm" src="https://user-images.githubusercontent.com/1590802/43054688-c0fa436a-8e00-11e8-8d2f-7e455ebc41c8.png">

**Comment by mmusori** [comment]
@dereklieu @LukeCaley . The decision has been taken that we merge all three personnel tables into one table as you had suggested earlier.

**Comment by mmusori** [comment]
From discussions in Nairobi last week on the deployments page
1. The readiness table needs a title.
2. The ERU deployed table has information replicated in the readiness table. We can remove this table and only have the readiness table. Showing both deployed and ready units
3. The list showing the ready units should be a vertical list.

![image](https://user-images.githubusercontent.com/7780809/43083135-148a782a-8e96-11e8-8709-794f8d2415e5.png)

**Comment by dereklieu** [comment]
Deployments tables (ERU and Personnel) show up on emergency pages if any are assigned to that emergency.
