### ISSUE TITLE
Implement ICRC Admin 1 Shapefiles

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#357]
This should be done in a way that would allow IM the ability to modify map styles.

**Comment by LukeCaley** [comment]
Needs to ensure disputed boundaries reflect NS territorial integrity, e.g. Somalia is one single entity because one single NS.

**Comment by ElsaRaunioIFRC** [comment]
What does the "ability to modify map styles" mean? In my vision, we have pre-defined colours for Admin1 areas that are affected (and have response activities). Other than that, no styling options will be given to the end user.

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC Ability to modify map styles means you have that ability, not the general organization.

**Comment by ElsaRaunioIFRC** [comment]
Thank yoyu @dereklieu for clarifying this issue. Sounds good.

**Comment by dereklieu** [comment]
This is now in progress, still need to upload ICRC boundary file that has disputed flag.

**Comment by dereklieu** [comment]
The ICRC boundaries with disputed flags have ben uploaded and are in use.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Excellent staff, looks good on the Emergencies page.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu I have one more comment: should I style the boundaries on MapBox or is the layer coming from another source? I am thinking not to use any stroke for the country polygons as the boundary layer should provide visible strokes for the countries.

In the current Emergencies page, do the country polygons have strokes? I think that those strokes conceal some of the disputed boundaries, for example, the Hala'ib triangle (area between Egypt and Sudan).

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC please continue to create the new map style on Mapbox. We have a hard-coded map style in the Go codebase right now. I would like to swap it with the style you create.
