### ISSUE TITLE
Getting to country pages via the regional map 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#358]
It is very difficult to click on the regional map to get to the country page. For countries without an operation you don't have an option to click on the map to get to the country page.  The list below the map does help and is easier to use to get to the country page. 
If possible we should be able to click on a country and get the tooltip. Instead of associating the tooltip to the dot/bubble that represents a current emergency response.

**Comment by dereklieu** [comment]
Countries without operations will open a tooltip that links to the country.
