### ISSUE TITLE
Country page 3Ws

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#359]
The map is displaying and the list of PNS and PNS activities are also displaying on the front end. 
1. The Tooltip is available but the exported map does not have data from the tooltip and does not display ‘PNS activities’.
2. The two side by side lists  lists i.e.  ‘activities by PNS’  and the ‘Type of activities by PNS’ need to be linked. As it stands people work on the assumption that the 1st country name on the ‘activities by PNS’ list corresponds to the 1st activity on the  ‘Type of Activities by PNS’.  
3. The title ‘Activities By PNS ‘  for a list of countries is rather inaccurate. Should just change to PNS or ‘NS name’. 
![image](https://user-images.githubusercontent.com/7780809/42807291-10254512-89b9-11e8-81c7-08dda204e65f.png)

**Comment by dereklieu** [comment]
1. Unfortunately there's no way to export the tooltip along with the map. The two are generated using very rendering methods, and the native canvas method we use to export the map doesn't apply to the tooltip.

2. I think I need more clarification here, I'm not understanding the issue.

3. Yes we can change the name.

**Comment by mmusori** [comment]
For 2: I now think it is understandable the first PNS name is linked to the first PNS activity. And the dots represent the number of activities by each PNS.  This comment was for the deployment page. 

![image](https://user-images.githubusercontent.com/7780809/43081451-43222876-8e92-11e8-80e1-d42c8bc0e9d3.png)

**Comment by dereklieu** [comment]
Closing since to my understanding there are no next steps. Please correct me if I'm wrong.
