### ISSUE TITLE
Regional page appeal data

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#362]
Not sure why we have a separate table for DREF and appeals.  If combined we can filter or sort by type.

In addition, we need to work out whether we display movement appeal data or not.  At the moment this appears as part of the sum total on the map but not in any table.

**Comment by szabozoltan69** [comment]
Now we have 3 kind of appeal-types: DREF, APPEAL, INTL – the last two are all considered as "appeal". (So we keep in the same [database] table the DREF-s and appeals.) Do you mean frontend surface as "different table"? Please clarify which part of the frontend would you like to see in a different form (if possible, with screenshots).

**Comment by szabozoltan69** [comment]
Please send some example URL-s.

**Comment by szabozoltan69** [comment]
The movements can be seen e.g. here: https://go.ifrc.org/regions/3#appeals – the only requirement is to set the Appeal type to Movement ( = "Intl").

**Comment by ElsaRaunioIFRC** [comment]
As we now have the Intl option, I am closing this issue.
