### ISSUE TITLE
Issues with data entry of field reports

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#363]
a) Change from 'Brief description of situation' to 'Situation report'.  Keep 'Briefly describe the situation' underneath.
b) Change 'Number of Expats/Delegates' to 'Number of RCRC Movement International Personnel involved'
c) Change 'Actions Taken by PNS Red Cross (if any)' to 'Actions taken by any other RCRC Movement actors' 
d) Change 'Select the activities taken by the National Society and briefly describe' to 'Select the activities undertaken by the National Society and briefly describe'
e) Change 'Select the activities taken by the foreign National Society and briefly describe' to 'Select the activities undertaken by any other RCRC Movement actor(s) and briefly describe'
f) Change 'Actions Taken by Federation Red Cross (if any)' to 'Action taken by the IFRC'
g) Change 'Select the activities taken by the Federation (could be the Zone office, DMUS, ...) and briefly describe' to 'Select the activities taken by the IFRC (could be the Regional office, cluster office or country office) and briefly describe
h) move IFRC above any other RCRC movement actors
i) Change 'About information management, indicate if an Information Bulletin was published, is planned or if no Information Bulletin will be issued for this operation/disaster.' to 'Indicate if an Information Bulletin was published, is planned or if no Information Bulletin will be issued for this operation/disaster'
j) Change 'Actions Taken by Others (Governemnts, UN)' to 'Actions taken by others (Governments, UN)'
k) Change 'Indicate the status of the differents international tools: Was DREF requested? How much ? Has it been approved ? How many beneficiaries ? Has the DREF operation been issued?' to 'Indicate status of global and regional tools' 
l) Remove 'Same for the emergency appeal' & 'For RDRT/FACT/ERU, only indicate if used, planned/requested or not used.'
m) Change 'IFRC Staff Relocated' to 'IFRC Staff'
n) Change 'Federation Contact' to 'IFRC contact'
o) Change 'A contact of the Federation (Secretariat/Zone/DMUs) for more information. Select someone who will be available for interview.' to 'A contact of the IFRC (HQ, regional, cluster and country office) for more information. Select someone who will be available for interview'

**Comment by LukeCaley** [comment]
The country dropdown seems to begin at Uganda and then scroll round to Ukraine before scrolling round to Afghanistan.

**Comment by LukeCaley** [comment]
p) Change 'Assisted by Red Cross' to 'Assisted by RCRC Movement'
q) Change 'A contact of the Federation (Secretariat/Zone/DMUs) for more information. Select someone who will be available for interview.' to 'A contact of the IFRC (HQ, regional, cluster and country office) for more information. Select someone who will be available for interview'

**Comment by dereklieu** [comment]
Hey @LukeCaley I'll carve out some time for these tomorrow.
