### ISSUE TITLE
Export CSVs with modified headers and columns

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#364]

**Comment by LukeCaley** [comment]
We need to add sensible fields to the .csv export so this is understandable.  Revised field names in first row of the below: 
[2018-07-appeal.zip](https://github.com/IFRCGo/go-frontend/files/2223867/2018-07-appeal.zip)

**Comment by dereklieu** [comment]
As of #371 CSVs save with a proper extension, and have their query limit removed. 

As it turns out, it's not simple to replace header fields. The payload from the API is already formatted as CSV, which to the browser is just text, and would require some expensive parsing and then re-formatting back to CSV in order to replace headers and fields. This would also negatively impact performance on whole-table queries, which is currently the default behavior.

The place to hook in this feature is probably at the API level, ie you could specify a list of columns and also a column name for each column to include in the resulting response. However, the API currently doesn't support this, and it's out of scope for phase 2.

I've changed the title of this ticket to reflect that. cc @LukeCaley

**Comment by ElsaRaunioIFRC** [comment]
This issue has been partially solved. 

There are still some columns that I would revise, like this:

country society_name > national_society_name
code > appeal_code

Other than this, the column names are clear and understandable.

**Comment by szabozoltan69** [comment]
Done. Tested with .../appeals/all?region=3

**Comment by ElsaRaunioIFRC** [comment]
Let's go for -

**Comment by szabozoltan69** [comment]
Done.
