### ISSUE TITLE
Add placeholder map next to emergency when there is no field report

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#365]
![43078569-8ef11e3c-8e93-11e8-97e9-e5d3565c1fff](https://user-images.githubusercontent.com/1590802/43080381-9e9e8558-8e5d-11e8-9431-a9ff163ce512.png)

Since we don't have a single emergency map, this would require creating a new map component.

**Comment by dereklieu** [comment]
@lukecaley could we instead show some placeholder text that says something like, 'no field report has been filed yet, if you're a member, click here to file one'?

**Comment by nanometrenat** [comment]
UX/UI amendments made mean no need for further action on this
