### ISSUE TITLE
Language and layout - Deployments

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#378]
1) Next to the ambulance icon, change ERU unit to ERUS
2) Change Key - 'ERU Equipment Unit' to 'Emergency Response Units deployed'
3) Prefer map to display deployed personnel as choropleth, not ERUs, if that's feasible
4) Add ERUs to the filter deployments dropdown
5) Deployed personnel table seems to be missing
6) Change table title form 'Deployed ERU' to 'Deployed ERUs'
7) Add export table button

**Comment by dereklieu** [comment]
FYI, deployed personnel table was missing because there is no such data of this kind in the database.
