### ISSUE TITLE
Language and layout - Country

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#380]
1) National society statistics - remove 'people reached' and 'people giving blood'
3) Add hyperlink to FDRS - http://data.ifrc.org/fdrs/
4) Map - the legend often covers the bulk of the country.  Suggest to set zoom further out.
5) A small PNS appears on the legend box - please remove

Not urgent but flagging here:
a) Add link to NS website and their 'priority sectors'
b) Change PNS activities terminology based on data available - suggest something around additional emergency activities @mmusori

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Points 1. and 2. have been solved. 

Point 3. continues to be a problem for some countries.

Point 4. I propose we replace PNS with "Additional Response Activities"

Additionally, replace "infinity" with a discrete maximum figure.

**Comment by szabozoltan69** [comment]
Would be good "100%" instead of "infinity"?

**Comment by ElsaRaunioIFRC** [comment]
The purpose of this chart is to show PNS activities on Admin 1 level. Based on the current estimates, the maximum activities of a PNS within Admin 1 is something like 5. So I suggest setting the maximum figure to 5. 100% does not really help in this context as we are not looking at proportions but rather, the number of PNSs.

**Comment by szabozoltan69** [comment]
Ok, it will be 5 then.

**Comment by szabozoltan69** [comment]
You can check the result e.g. on https://dsgoproxyapp.azurewebsites.net/countries/74 – and soon on production also.
