### ISSUE TITLE
Deployment Page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#383]
## Issue

1. Bar charts should disappear when no ERU data is displayed.
2. ERU Readiness section should disappear when no ERU data is displayed.
3. Replace country name with National Society name in the "ERU Owner" Column in the ERU Table.
4. Replace country name with National Society name in the "from" column in the personnel table.

**Comment by dereklieu** [comment]
Once this is actually in use, how likely a scenario is it that there is no ERU data at all to display?

I'm happy to do the work but I just want to make sure we're not overcompensating to development data.

**Comment by guipizzini** [comment]
@dereklieu we might not have many across the year, but when we would have ERUs deployed those would be our largest and most important emergencies and therefore would make sense to have the data structured correctly. Does that make sense?

@LukeCaley ideas?

**Comment by guipizzini** [comment]
@LukeCaley any ideas on this one?

@dereklieu could you explain the difference between "personnel" and "personnel deployments" in the Django Admin? They seem very similar but do not understand the logic. Thanks

**Comment by dereklieu** [comment]
This is the personnel form:

![screen shot 2018-08-09 at 11 17 14 am](https://user-images.githubusercontent.com/1590802/43908385-dcbb78c6-9bc5-11e8-9aa8-78f634e2f454.png)

A personnel is assigned to a deployment. The deployment specifies which country/region and, optionally, which emergency they are deployed to.

This is the deployment form:

![screen shot 2018-08-09 at 11 16 55 am](https://user-images.githubusercontent.com/1590802/43908449-03867cda-9bc6-11e8-88d5-b7a315e3683d.png)

You can optionally enter personnel members who are a part of that deployment. If you add a personnel member using this form, they will also appear in the personnel table.

Hope that helps.

**Comment by dereklieu** [comment]
It can be useful to think in terms of deployments, as that allows you to see all the people from the range of national societies who have been deployed to an emergency, not just singular personnel or personnel from a single national society.

However, you could also create many deployments, each with a single personnel, to a single country or emergency. The Go front-end would display it the same as a single deployment with multiple personnel.

**Comment by LukeCaley** [comment]
@dereklieu understand the logic for the deployments, although we need to ensure it is clearer to users.  Suggest we have two options: a) providing some form of explanation alongside the django interface (probably not easy to do?); b) educating each user through user guides etc.  As the former is probably difficult to do right now I would suggest we have to do the latter.  

In terms of the original list of issues (pasted below) I would agree that these are nice to haves and the right idea but not as urgent at this moment.

Bar charts should disappear when no ERU data is displayed. - Agree but not high priority
ERU Readiness section should disappear when no ERU data is displayed. - Agree but not high priority
Replace country name with National Society name in the "ERU Owner" Column in the ERU Table.
Replace country name with National Society name in the "from" column in the personnel table.

**Comment by szabozoltan69** [comment]
Recently in the "Owner" and "from" colums there are: Bolivian Red Cross, French Red Cross... Is that OK like this? If not, where can I find the Bolivian National Society name?

**Comment by szabozoltan69** [comment]
![empty_personnel_page](https://user-images.githubusercontent.com/6050643/46542408-a016f280-c8be-11e8-960d-05ab6547e349.png)

**Comment by ElsaRaunioIFRC** [comment]
This issue appears to be solved.
