### ISSUE TITLE
Data tables (export/and no data tables)

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#384]
## Issue

1. Data export is existing in the deployment page, for each data table. However this is missing across other sections of the site. We should have this option available for all data tables in the site.

2. For all sections in the site where there is no data for a specific "section" that should disappear across all the site.

**Comment by dereklieu** [comment]
1. For other tables, click view all to see the table page, which will have an export button.
2. Not sure where you see this happening, can you be more specific? Also please open another ticket for this issue.

**Comment by dereklieu** [comment]
Personnel and ERU tables now have a view all link that take you to the separate page, which includes the export link, making this behavior consistent across the site.
