### ISSUE TITLE
Map on Mobile

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#389]
Hi Derek,

All seems nicely working on Mobile, however the Mapbox structure is overlapping with other sections, just pointing this one out.

Will let @LukeCaley agree on the importance of this one.

Cheers,

G.

**Comment by dereklieu** [comment]
Can you post a screenshot?

**Comment by guipizzini** [comment]
![img-2329](https://user-images.githubusercontent.com/23258092/43644901-5f2874e6-9741-11e8-8666-2d1519156c21.PNG)

![img-2328](https://user-images.githubusercontent.com/23258092/43644908-63083e20-9741-11e8-943a-4a6b9a16eff2.PNG)

![img-2327](https://user-images.githubusercontent.com/23258092/43644921-66ab3dca-9741-11e8-8812-4a27aff8ee34.PNG)

Here you have some screenshots, going beyond the map actually...

**Comment by ElsaRaunioIFRC** [comment]
This issue appears to be solved.
