### ISSUE TITLE
Deleting data on Deployments Page but still appearing

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#395]
## Issue

I've deleted data related to ERUs from the Django Back End. However they still appear on the front end despite hard reload of the browser. I've as well opened different browsers and the data still appears there despite having being deleted in the back end.

This should be fixed as soon as possible, please.

**Comment by dereklieu** [comment]
Looks like it's working, there's no ERU data and no deployment data.

**Comment by guipizzini** [comment]
Derek, it is not working on multiple browsers. I can call you and you can check my steps and actions to see that the data is still there...you tell me!

**Comment by dereklieu** [comment]
Can you send a screenshot of what you're seeing? This is what I'm getting on the deployments page.

<img width="1280" alt="screen shot 2018-08-06 at 8 58 21 am" src="https://user-images.githubusercontent.com/1590802/43717877-ec9b6790-9956-11e8-8442-ed28a277268f.png">

https://go.ifrc.org/deployments

**Comment by guipizzini** [comment]
![screencapture-go-ifrc-org-deployments-2018-08-06-17_01_22](https://user-images.githubusercontent.com/23258092/43718020-65d77912-999a-11e8-93e4-5436d1bfc2b9.png)

Then when you click "see all" it basically renders an empty page.

**Comment by dereklieu** [comment]
This is a caching issue at the [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) level. We use an Azure CDN to improve API performance across regions. On development we don't cache at all at the CDN level. On production I shortened the cache to 30 minutes. This should still improve performance during peak hours but will significantly decrease the time that stale content stays in cache.
