### ISSUE TITLE
Field Reports not pulling in

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#397]
## Issue

The field reports are not coming into the site for some weird reason. Check the screenshot below.
This would require immediate attention, please.

<img width="1216" alt="screen shot 2018-08-06 at 16 14 12" src="https://user-images.githubusercontent.com/23258092/43716111-ee61ede6-9993-11e8-9432-79b9dab93340.png">

**Comment by dereklieu** [comment]
@guipizzini what page is this on?

**Comment by guipizzini** [comment]
https://go.ifrc.org/emergencies

**Comment by dereklieu** [comment]
They're showing for me? Can you try removing cache or using a different browser? Or logging out and logging in again?

<img width="1219" alt="screen shot 2018-08-06 at 8 51 04 am" src="https://user-images.githubusercontent.com/1590802/43717533-e150c07a-9955-11e8-9b85-79978fcd92b0.png">

**Comment by guipizzini** [comment]
Did all of that, tested on different laptops too from other users...

**Comment by dereklieu** [comment]
I think this is the same issue as https://github.com/IFRCGo/go-frontend/issues/395#issuecomment-410802584
