### ISSUE TITLE
Data inaccuracy displayed

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#399]
## Issue

On the Emergency page the labels display the inaccurate number.

We have 55 emergencies in the last 30 days but then the title of the table structure is showing 111 in brackets.

Here below are the screenshots...

![screen shot 2018-08-07 at 09 29 53](https://user-images.githubusercontent.com/23258092/43762090-3e43f898-9a27-11e8-835f-a9094716c83b.png)
![screen shot 2018-08-07 at 09 29 58](https://user-images.githubusercontent.com/23258092/43762091-3e6b56f4-9a27-11e8-90c3-32066df9e455.png)

**Comment by dereklieu** [comment]
The 55 (now 57) number is counting appeals. It is the number of emergencies that IFRC is responding to. 

The larger number in the table shows all emergencies, including ones that don't have a response.

**Comment by guipizzini** [comment]
What is then the difference with the map on the home page? That one is meant to show all ongoing DREFs and Appeals, which means is the same as the Emergency map which should not be the case.

**Comment by dereklieu** [comment]
My mistake, I looked again, the emergencies map does map emergencies and not operations, however the tables were set to show the past 90 days and not 30. There had been some back and forth about how recent to show this data. I'll change the interval to 30.

**Comment by guipizzini** [comment]
Thanks @dereklieu we have now 55 emergencies in the last 30 days on the top banner and 52 emergencies in the last 30 days on the header of the table, which means we still have some slight inaccuracies with the data. Could you look into this one, please?

**Comment by dereklieu** [comment]
@guipizzini ah I see that one is set to start counting from the start of the day, the other is set to count from the end of the day. I've fixed this in https://github.com/IFRCGo/go-frontend/pull/421. They should always show the same number now.
