### ISSUE TITLE
Serbia and Montenegro in the list of countries

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#400]
Serbia and Montenegro ceased to exist in 2006. However, we still have it in the list of countries in the Europe Region page. 

I have tried to unassign Serbia and Montenegro from the Europe Region on Django. However, this does not seem to work as the system keeps prompting for a region. 

While we want to keep Serbia and Montenegro in our database (because of historical operations in the country), we should not display it for the public in our list of countries.

**Comment by dereklieu** [comment]
This could be accomplished by adding a `inactive` field to the country model, and then modifying the front-end to filter those that are set to `inactive`.

**Comment by ElsaRaunioIFRC** [comment]
Thanks for the response @dereklieu. Would this work with the same principle as the active/inactive users?

**Comment by dereklieu** [comment]
Not exactly, active/inactive is a Django feature of the user model. In this case we would have to build our own functionality on the front-end to hide inactive countries.

**Comment by ElsaRaunioIFRC** [comment]
Merged with #415.
