### ISSUE TITLE
Elasticsearch should re-index updated countries and regions

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#401]
We have changed the names of some of the countries to match with our naming standards. However, even after changing the name, the old name appears in the search box.

For example, we have changed Libyan Arab Jamahiriya to Libya (the former was used during Gaddafi's rule, not by the current government). However, in the search box, we can still see Libyan Arab Jamahiriya. A screenshot:

![screenshot 32](https://user-images.githubusercontent.com/31092591/43764791-b742d69a-9a2e-11e8-966e-bbd84475102c.png)

The same issues happens with other countries whose names we have changed or modified.

**Comment by dereklieu** [comment]
Since countries are now indexed to elasticsearch, they have to be re-indexed when they change. I just did this manually, but we upgrade the indexing script to also look for changed countries.
