### ISSUE TITLE
Deployment data details

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#407]
## Issue

1. We should have "IFRC" and "ICRC" as an option when selecting where from someone is deployed from. Often we can deploy IFRC and/or ICRC staff.

2. The name of the National Society (or IFRC or ICRC) should appear and not the country name.

This is quite urgent.

**Comment by dereklieu** [comment]
@guipizzini please see my note [here](https://github.com/IFRCGo/go-frontend/issues/415#issuecomment-415179088).

**Comment by guipizzini** [comment]
Ok - noted, whenever the other ticket is closed we can proceed in closing this one too.
