### ISSUE TITLE
Add ERU HR option to Personnel Deployments

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#409]
Our Surge Team colleagues have been populating the deployment data.

Currently, there appears to be no "ERU HR" option in the deployment type. ERU HR means those who are deployed as individual personnel into an ERU Unit. Many national societies do not have ERU units but personnel that are deployed as part of a ERU Unit belonging to another national society.

Let me know if you require any further clarification on this.

**Comment by dereklieu** [comment]
Hey, I'm glad Surge is adding data. 

I really would like to find a way to de-dupe the `unit` and `equipment unit` fields in an ERU. If we add an HR type, it would make more sense to me to use `unit` and get rid of `equipment unit` entirely. 

Thoughts @ElsaRaunioIFRC @LukeCaley?

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu How about adding the ERU HR option to Personnel Deployments, in addition to FACT, HEOps and RDRT?

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC from a technical perspective, that's not difficult to do. I also think it makes sense to group the personnel entries together. So if you give me the go-ahead, I can add that to the API.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Very good. So, we would need the following personnel types:
-FACT
-HEOps
-RDRT
-Deployed as IFRC Staff
-ERU HR

Let me know if there are any further issues.

**Comment by dereklieu** [comment]
Thanks, I will add these new personnel types.

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC new personnel types are deployed to development. Can you give it a look and give me a thumbs up to deploy to production?

https://dsgocdnapi.azureedge.net/admin/deployments/personnel/add/

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Looks good. Good to go for production.

**Comment by dereklieu** [comment]
Thanks, this is deployed to production.

https://prddsgocdnapi.azureedge.net/admin/deployments/personnel/add/
