### ISSUE TITLE
URGENT: Response documents / situation reports not landing anywhere

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#413]
I have uploaded some documents under the DR Congo Ebola Response page. However, they do not seem to be landing anywhere on the page. Previously, there was the section "Response Documents", this is still present in the production environment. Several colleagues have expressed their concern for the documents not being available for the deployed personnel.

For the smooth operational communication, it is crucial that the response documents and situation reports are easily accessible for the deployed personnel, just like in the production environment page. Hence, this issue requires a very quick fix.

**Comment by dereklieu** [comment]
This should be fixed by https://github.com/IFRCGo/go-frontend/pull/421, waiting to confirm.
