### ISSUE TITLE
Chronology of emergencies and active operations

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#416]
## Issue

Emergencies and active operations appear according to the date they started. 

## Steps to reproduce

*If you can reliably reproduce the issue, please list the steps taken to do so.*

## Expected behavior

I think it will make more sense, as they were sorted according to which one was lately updated or is still ongoing. As for instance now Ebola in DRC is not showing on the front page, as it was linked to previous Appeal from May.

**Comment by ElsaRaunioIFRC** [comment]
I think the "Highlighted Emergencies" tab has provided a solution to this problem, at least in this development phase.
