### ISSUE TITLE
Automated Ingest of Field Reports into Emergency 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#417]
## Issue

At the moment field reports are automatically fed into emergency page, which in case of Ebola in DRC results in showing a really outdated data on the emergency page. 

## Steps to reproduce

*If you can reliably reproduce the issue, please list the steps taken to do so.*

## Expected behavior

Ability to turn off the function of automatic feeding the reports.

**Comment by LukeCaley** [comment]
This also links to issue #365.  If we turn off the field report we need to be able to have an option to ingest a standard map of the country.  

If there has not been a field report submitted for the emergency, we should then be able to encourage NS to post a report through a visible link to add field report section.

**Comment by dereklieu** [comment]
Hey @omniscjencja can you help me understand what you mean by turning off the automatic feeding of field reports? Do you mean we should no longer show them on the emergency page? cc @LukeCaley 

For the DRC Ebola response, I think that would be a good candidate to mark as a featured emergency, which would cause it to show up on the homepage and make it easier to find.

**Comment by omniscjencja** [comment]
@dereklieu sure, basically we want to be able to decide, turn on or off from the admin page, whether we want to show the data from the field reports 

for instance, here, it shows the data from an outdated report, so we rather not have it shown at all, but we cannot control it at the moment from an admin page 

![sans titre](https://user-images.githubusercontent.com/29458013/44449070-624f5a80-a5ed-11e8-8d83-aab6801f6e8d.jpg)

**Comment by dereklieu** [comment]
@omniscjencja I understand. However, this is not the most straightforward to do. The field report data is there because we deemed it crucial to understanding an emergency. In a case like this, where this is so much attention being paid, wouldn't the better solution be to have someone submit an updated report?

**Comment by omniscjencja** [comment]
@dereklieu I can imagine, however the nature of our work sometimes doesn't allow to upload field reports, for instance due to security concerns, hence we would like to have such feature

**Comment by LukeCaley** [comment]
Feedback on use and display of field reports during the Sulawesi EQ response:

_I’ve been actively trying to use the GO platform and have experienced some difficulties in making sure data is relevant and updated. 

In this instance, the emergency overview section pulled from the Field Reports does not seem to be well placed and might end up causing a lot of headaches and extra work for any IM oriented in the operation. 

The following points have been observed:

•	Field Reports overwrite: This means that if the first field report contained contact information, that needs to be copied over to the next field report or you lost that information
•	There is not really a systematic approach for when to add to the field report data. It seems like it is highly encouraged that the information here be from the NS, but if there is no information it just remains blank at the top of the page and is the first thing you see. Whereas the key numbers might be more valuable at this stage. Might be use changing this visual hierarchy? Or giving guidance on when to use Field Reports outside of a field observation, i.e. when it is appropriate to fill with just the emergency response management center (or something like that). 
•	It also prioritizes non-government numbers- so if a field report adds only govt numbers then they’re not displayed on the update._

**Comment by LukeCaley** [comment]
@szabozoltan69 This is becoming a significant issue with current operations in Indonesia.  @szabozoltan69 Can we prioritise finding a solution, i.e hiding this?

**Comment by szabozoltan69** [comment]
Yes, we can prioritize this, but now in a few minutes I go home and continue only in Monday. If more urgent, maybe @dereklieu can suggest a solution.

**Comment by szabozoltan69** [comment]
Sometimes the hiding mechanism is working, e.g. here: https://go.ifrc.org/emergencies/3284
But here it is not: https://go.ifrc.org/emergencies/3288
I should find the criteria where it is decided, and – if needed – change it. (Otherwise, even though there are zero values in Affected, there are some other valuable figures which are displayed, so I can undestand the aim of the programmer.)

**Comment by omniscjencja** [comment]
dear @szabozoltan69, it is not that hiding mechanism is working, but that for Dominica emergency there are no field reports, while for Indonesia, there are some, hence the Emergency Overview appears. We want to be able to manage it from the back-end, have a feature - show emergency overview, Y/N

**Comment by szabozoltan69** [comment]
Dear @omniscjencja, so you would like to have a "Show emergency" checkbox to every appeal in the backend. If it is checked, then the recent behavior will work (so if there are no field reports, no is shown, but if there is, then they are shown), and if it is not checked, then no "Emergency overview" will be shown in any case.

**Comment by omniscjencja** [comment]
Dear @szabozoltan69 yes, that is exactly what we need, to be able to decide when to show the emergency overview and when no

**Comment by szabozoltan69** [comment]
@dereklieu, you could finish much faster this request, than me. I added show_emergency (boolean) field to Appeal class (and table), and I made the migration also. Now I would like to check from the frontend (views/emergency.js, renderFieldReportStats) if the related appeal has a True show_emergency (or not). So something similar to: 
```if (!report) return null;
```

**Comment by dereklieu** [comment]
@szabozoltan69 sorry, I've been moved onto other work and don't have time for feature-building on this project. That said, what's your reasoning for adding this to the appeal class? To me, it seems more direct to just add it to the emergency class. The field report is not generating an appeal, it is generating an emergency. Also, when a field report generates an emergency automatically, that emergency won't necessarily get an appeal.

**Comment by szabozoltan69** [comment]
@dereklieu thank you for the response. | My reason to adding this to the appeal class was the screen itself (above), where left side are "Appeals" statistics and they always (wanted to be) displayed, while the right side should be decided via this checkbox. But I rethink it...

**Comment by szabozoltan69** [comment]
Thanks for the idea, now the show_emergency is in the "event" class and works fine.

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-api/pull/319
https://github.com/IFRCGo/go-frontend/pull/480

**Comment by szabozoltan69** [comment]
A better name was used (thanks Derek). Now it works like this:
![show1](https://user-images.githubusercontent.com/6050643/47000939-afe9ce80-d129-11e8-977b-90d17a7cc1a7.png)
![show2](https://user-images.githubusercontent.com/6050643/47000944-b2e4bf00-d129-11e8-847e-c6ee955590cb.png)
Now let's hide it:
![hide1](https://user-images.githubusercontent.com/6050643/47000954-b9733680-d129-11e8-9a79-99a7fcda3bab.png)
![hide2](https://user-images.githubusercontent.com/6050643/47000961-bd06bd80-d129-11e8-84cc-953fcf9347cb.png)
![hide3](https://user-images.githubusercontent.com/6050643/47000965-c001ae00-d129-11e8-969a-ad20efa5a56e.png)

**Comment by szabozoltan69** [comment]
@omniscjencja @LukeCaley @Munu You can test it e.g. on https://dsgoproxyapp.azurewebsites.net/emergencies/3364

**Comment by nanometrenat** [comment]
Hi @mmusori @LukeCaley  can you please take a look and advise whether this meets your requirements or if further work is required?  Cheers

**Comment by LukeCaley** [comment]
Thanks @nanometrenat this works for current requirements.  We are planning to scope out an improved means to use GO for situational/operational updates (e.g. updating Field Reports and so-called "informal updates") in release 4.2.

**Comment by mmusori** [comment]
The original idea in phase 3 for phase 4 was that the Field Report data would be replaced with a map of the affected area. So now when you turn the data of the whole box disappears and you have the map. So this is done and the ticket should be closed. See example below (Zambia Floods) where I turned off the box since it did not have any data. If we want new features we can create a new ticket. 
![image](https://user-images.githubusercontent.com/7780809/72344556-d3efe300-36d1-11ea-80e8-e96ebf1c074b.png)
