### ISSUE TITLE
Highlighted emergencies banner not deployed to production

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#418]
The highlighted emergency banner, which was apparent in the development environment, has not been deployed to production.  This should appear on the emergencies page and redirect users to key emergencies determined by a user in the django backend.  The function to highlight emergencies is appearing in neither the front nor the back end.

**Comment by dereklieu** [comment]
Hey @LukeCaley you should be able to flip the `Is featured` checkbox on the emergency page admin. It's right below the disaster start date field. 

<img width="694" alt="screen shot 2018-08-22 at 7 42 26 am" src="https://user-images.githubusercontent.com/1590802/44443169-0ed61000-a5df-11e8-87d2-315317720f0c.png">

The featured emergencies will appear on the homepage.
