### ISSUE TITLE
Mispositioned country centroids in the Emergencies page

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#419]
Some countries, particularly those with overseas territories, have their centroids mispositioned. Currently, this is the case with Portugal. Since Portugal has the Azores, the calculated centroid is somewhere in the Mid-Atlantic (as in the current map), see the screenshot below.

![image](https://user-images.githubusercontent.com/31092591/44405987-e1478300-a55a-11e8-85a0-febba7c384dd.png)

However, this would not make much sense from the user point of view. I advise that with Portugal (and other countries with overseas territories), the centroid will be adjusted so that it falls in the middle of the main territory of the country.

As another example, I use the USA; because of Alaska, the calculated centroid of the USA is somewhere in Canada. However, we would like the centroid to go into the center of the main part of the USA. With the hurricane season approaching, we anticipate to get a lot of field reports from the USA.

**Comment by dereklieu** [comment]
Hey @ElsaRaunioIFRC to account for the fact that automatic centroid placement is not ideal for the cases you've outlined and others, we maintain in the Go application a manually curated list of country and district centroids. You can find the country file here:

https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/country-centroids.js

If you send me the correct centroids for Portugal, the US, and any others that are misaligned, I can correct them.

(By the way, this also means that when we wish to add a new country, if we want to show it's centroid we would have to include an entry for it in this list.)

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Excellent. I will proceed with this task today and you should get the correct centroids by tomorrows. I will also provice a list of countries whose centroids I've changed.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu You can find the list of countries and corrected centroids [here](https://docs.google.com/spreadsheets/d/1JwegpznRqlorMQ8Sf9Q8o89BlEQZCu6IPJT1Bx6xwxA/edit?usp=sharing). 

Please note that I only assigned centroids to those countries that the IFRC recognises as independent.

**Comment by dereklieu** [comment]
Hey @ElsaRaunioIFRC I think some of the data points got shifted. For example, Myanmar is showing where Mongolia should be, and Mongolia is in the Pacific.

<img width="845" alt="screen shot 2018-08-23 at 5 11 27 pm" src="https://user-images.githubusercontent.com/1590802/44530683-ad559480-a6f7-11e8-8471-16523ee0b97e.png">
<img width="849" alt="screen shot 2018-08-23 at 5 11 35 pm" src="https://user-images.githubusercontent.com/1590802/44530691-af1f5800-a6f7-11e8-853a-c62e93f149a8.png">

I'm going to make sure Portugal and the US look ok and close this, but please let me know if you spot other countries where this is an issue, and send me a revised coordinate pair.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Looks like there's been  a serious data error from my side, thanks for bringing this up. I have now worked on the data to correct this issue. Is it working? Please report if anything is wrong and I'll try to fix it.

**Comment by dereklieu** [comment]
Looks like that fixed it, I'll deploy these to dev shortly.

**Comment by ElsaRaunioIFRC** [comment]
Very good
