### ISSUE TITLE
Not working link 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#420]
## Issue

When one is on the admin page - IFRC Go administration, and clicks on Visit site, instead gets redirected to https://prddsgocdnapi.azureedge.net/ with info: Not Found, The requested URL / was not found on this server.

## Steps to reproduce

*If you can reliably reproduce the issue, please list the steps taken to do so.*

**Comment by szabozoltan69** [comment]
Do you mean "View site"? (There is no "Visit site").
I suppose you would like to use this View site to go to the frontend. (Because the API administration web instance the "site" itself is the root of the API system, and that is shown via clicking to "View site" – so basically it does the job well.)

**Comment by szabozoltan69** [comment]
@dereklieu hey,
   now I try to achieve a small change in the go API djano system: change the "View site" URL.
I see that (in docker instance) we can find contrib/admin/sites.py, and in this there is a site_url, which is now simple /, and it should be changed.

In production environment to go.ifrc.org, in non-production environment to dsgoproxyapp.azurewebsites.net .

I know that in the env file there is an ENVIRONMENT setting, but could you help me how to use it in this case?

So my aim is:
 - to change (or override) the docker-inside sites.py
 - to "see" from it the ENVIRONMENT parameter and set site_url depending on it.

**Comment by szabozoltan69** [comment]
Now I could put a perl replace depending on ENVIRONMENT, but there should be a nicer solution, than this:
```cp -p sites.py sites.py_orig
perl -pi -w -e "s/(    site_url = '\/')$/\#\$1\n    site_url = 'https:\/\/dsgoproxyapp.azurewebsites.net\/'/" /usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py
  or  
perl -pi -w -e "s/(    site_url = '\/')$/\#\$1\n    site_url = 'https:\/\/go.ifrc.org\/'/" /usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py
```

**Comment by dereklieu** [comment]
@szabozoltan69 there is already a environment parameter called `FRONTEND_URL` that you can probably just use directly. You can see an example of it being pulled here: https://github.com/IFRCGo/go-api/blob/master/main/frontend.py

**Comment by szabozoltan69** [comment]
@dereklieu Thanks. Some difficulty comes from the fact that the
_/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py_
file is not amongst the developed files, but it get installed in docker build time.
I tried to override the site_url variable in our main/settings.py (via os.environ.get('FRONTEND_URL')), but it was not enough, the web page remained the original one.

**Comment by szabozoltan69** [comment]
Ready to test
