### ISSUE TITLE
Key figures on emergency page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#423]
## Issue

The automated formatting is not working and once you have more than 4 attributes the cards will go beyond the section and do not automatically render and format correctly.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Do you know what this issue is about? After going through the current emergencies, everything appears to be in order.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC I think it is about mobile view (or a narrow browser view) of https://go.ifrc.org/emergencies . In a narrow viewbox some part of the field riports get out of the window (and should scrolled). The ordering is OK by my opinion.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 I've taken a look on the mobile too and it looks fine, at least on iOS.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Fine, then you can close it.
