### ISSUE TITLE
Admin page not working for some of the users! 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#428]
## Issue

One of the users reported that since a version 2 was deployed, she is unable to edit the vents. When she clicks on “Edit Event”, she gets this page, which says the emergency does not exist and cannot find another way to edit the page. Please see screenshots attached. She is an admin for the region, and even when we sent her a direct link, she got a 403 Forbidden error. 

She is able to access the emergency via the read API and the page works, so the emergency clearly exists, but somehow she can’t access the change page for any emergency – she checked on the Nepal earthquake one too as a test. Basically, her GO admin page lists 0 emergencies for her to look through or change, but allows her to add new ones. She didn’t have any of these issues until after the version 2 launch. 

## Expected behavior

Fix as soon as possible, as she is an admin for Bangladesh. 

![error](https://user-images.githubusercontent.com/29458013/44706832-2dd31700-aaa3-11e8-9b85-0a82b2ce0462.jpg)

![error 2](https://user-images.githubusercontent.com/29458013/44706847-375c7f00-aaa3-11e8-8caf-6cf98454bd0f.jpg)

![error 3](https://user-images.githubusercontent.com/29458013/44706852-39bed900-aaa3-11e8-9b54-690bb57c4ccb.jpg)

**Comment by guipizzini** [comment]
It was a matter of necessary admin rights which has been fixed and closed.
