### ISSUE TITLE
http redirect to https not happening

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#431]
## Issue

The http site is not redirecting automatically to https which means that the site is not secured - mainly when people registering.

**Comment by dereklieu** [comment]
Redirection is not happening and that is an issue. However, as of https://github.com/IFRCGo/go-api/pull/290/files all registration emails are now sent with explicit https links. The only way someone would find an unsecured link is to change the url themselves.

**Comment by guipizzini** [comment]
Ok - that would make sense - however we have issues on links and urls in general as reported here:

https://github.com/IFRCGo/go-frontend/issues/435

Thank you for looking into this one, please.

**Comment by szabozoltan69** [comment]
Now it works fine due to an Azure "only https" setting.
