### ISSUE TITLE
Chrome Browser not working 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#433]
## Issue

Not possible to view the site in Chrome, not even in Chrome incognito (it loads but without any content). [See this source code paste. 
](https://0bin.net/paste/fioLNTklUzi5VDcK#dhJM5Ep4Vh8k-rMWqmYRbgCPYWfW8eaWQ0Ah9A71BwX)

**Comment by dereklieu** [comment]
@omniscjencja does it load in other browsers? Which other browsers have you tried? Which url are you attempting to load? Does your console show any errors?

Thank you for pasting the source code of the site, however that does not help me debug at all any issue, as the source code is exactly as it appears here in this repo (I already have access to it, in other words). However, your console will inform you of many errors that could help me a great deal.

https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by dereklieu** [comment]
This was caused by an OpenGL bug in an older version of Chrome. No longer relevant.
