### ISSUE TITLE
Uppercase characters not allowed when registering 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#434]
## Issue

Registering with an email that contains uppercase characters isn't possible.

## Expected behavior

I suggest allowing them since they are valid in email and many people (e.g. IFRC email) use capitalization frequently, making copy-pasting difficult.

**Comment by dereklieu** [comment]
Registration should now ignore case. @omniscjencja @szabozoltan69 can this be closed?

**Comment by szabozoltan69** [comment]
This can be closed now.
Otherwise the registering allows both upper- and lowercase, but the login (and password change) process is case insensitive.

**Comment by nanometrenat** [comment]
Related to #471

We are now seeing problems where users can't reset password as typing their email address with a different capitalisation to what it was saved as when registering/being migrated.  From the above comment it sounds like the password change process was meant to be case-insensitive but that doesn't seem to be the case in practice.  I will log a separate ticket.
