### ISSUE TITLE
Confusing order of deployments 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#446]
## Issue

Surge deployments on emergency page are not in logical chronological order, as they are sorted by an end date of deployment, instead of a start date. We already encountered issues with users reporting that deployments are not up to date, as they expect to see a person deployed on the certain date on top of the list, instead of somewhere in the middle. 

## Expected behavior

Sorting deployments by a start date. Or ideally allowing the user to select how they want the list to be sorted.

**Comment by szabozoltan69** [comment]
Ok, let's work with this. Please send me some example URL-s about the not-good and the wished result.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC The task is not clear (or maybe partially solved before). Recently the emergencies are ordered by start date, as the above requirement would like to have, on page https://go.ifrc.org/emergencies

![em1](https://user-images.githubusercontent.com/6050643/49076074-7cc25100-f238-11e8-82c3-053ab687826d.png)

The field reports are ordered by Creation date:

![em2](https://user-images.githubusercontent.com/6050643/49076347-112cb380-f239-11e8-8b6e-8a71b08b57f2.png)

At field reports there is no "deployment date", only these 3 dates are represented:

![em3](https://user-images.githubusercontent.com/6050643/49076365-2275c000-f239-11e8-96b5-0fedfd5d0d27.png)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 This request concerns deployed personnel only (FACT, HEOps, RDRT/RIT). What we would like is to have the deployments sorted by the mission start date rather than end date. Since the lengths of the missions vary from a few weeks to many months, it makes more sense to sort these according to the start date.
![image](https://user-images.githubusercontent.com/31092591/49079506-05dd8600-f241-11e8-866c-243f411cd1fa.png)

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Oh, thank you. Now it's clear. The "_...on emergency page..._" localisation was a bit misleading, because it is on Deployments page (/deployments).

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Please test it. Also fixed the half-working sorting links (^, v). (For the Emergency text itself there is no sorting possibility in API.) If OK, we can close this.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 I don't see any difference either in the dev or product environment. Would you mind adding some more deployments to the development? Currently, all the deployments have the same starting date and thus, cannot be tested for this function. I don't think I have an access to the development admin.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Maybe you tested it too quick, before the actual deployment. :-) Well, if you load it now, you can see that the first (Start Date) column is ordered:
```
2018-10-31
2018-10-12
2018-09-27
2018-09-16
2018-09-14
```
– this was the request. If you click to an other column, e.g. End Date (first), then the End Date is the ordering data:
```
^
2018-12-08
2018-12-09
2018-12-09
2018-12-13
2019-01-03
```
One more click to End Date reverses the order:
```
v
2019-01-03
2018-12-13
2018-12-09
2018-12-09
2018-12-08
```

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Now this is working as requested, with the default sorting in reverse chronological order by start date.
