### ISSUE TITLE
Changed country names and regions being overwritten

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#460]
I have changed the names of some countries several times and every time they seem to be automatically overwritten after a few days.

The same thing happens when trying to change the region of a country (Israel from MENA to Europe). Because of the political sensitivity of this issue (as with the country names), this problem requires a quick fix.

**Comment by szabozoltan69** [comment]
We made a database rollback last week, so all the work of the day 20180919 was deleted (and set to morning 7:00 state).

**Comment by ElsaRaunioIFRC** [comment]
Thanks, Zoli. How should we proceed? If we now change the country names again, can you ensure that they won't change again?

**Comment by szabozoltan69** [comment]
Yes, Elsa, I can ensure that there will be no database rollback in these days.

**Comment by ElsaRaunioIFRC** [comment]
Thanks. Should any rollback happen in the future, it would be good to inform our team about this. Hence, we may ensure that the politically sensitive country names (Taiwan, Palestine, Israel, etc.) will be sorted out before too many users spot them.

**Comment by dereklieu** [comment]
Hey @ElsaRaunioIFRC in order to make sure that, when the DB gets restored, we don't overwrite your changes to countries, I think you should change them to their proper representations in this file as well:

https://github.com/IFRCGo/go-api/blob/master/api/fixtures/Countries.json

These are the "default" countries as we initially received them, and on database restores they are synced to make sure we have working countries. If you create a PR with the proper changes, I can make sure it gets reviewed and merged, and this issue will no longer be a problem.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Thank you, Derek for sharing the database. I will mark updating this database as today's priority task.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC There is a waiting pull request (https://github.com/IFRCGo/go-api/pull/293 ) which will make optional the "region" for any countries. If it goes to production, then you can set to "none" the region of these (or other) countries.

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC hey just to confirm, did you also remove countries from Go? If so, could you also remove those countries from this [fixture](https://github.com/IFRCGo/go-api/blob/master/api/fixtures/Countries.json)? Right now there is an inconsistency between what's deployed and our local development environment, and that's preventing us from fixing a bug with ingesting users from DMIS.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Thanks for bringing this up. I've indeed removed Taiwan and Hong Kong in order to minimise the risk of those appearing for public. I've now also removed them from the fixture. In the future, I'll remember the fixture, should we need to remove any other countries from Go.
