### ISSUE TITLE
a mistake that prevents to update page on the Appeal for MDRCD026

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#464]
## Issue (by Guido) 

The error is not highlighted so I do not know what it refers to and I have the following issues:
 
There is a blank record in the appeal document. If I try to delete it, it will not delete it. If I add a random url it will create that random second url but will keep the blank one which I assume is causing the issue.
 
This means that if I want to manually update the figure of the appeal amount (correct figure is: 3,747,211 CHF) I cannot do this as it will not save by giving me the error.
 
## Expected behavior

Could we work on fixing this, please?

**Comment by dereklieu** [comment]
@guipizzini @omniscjencja I noticed that some appeal documents are saved with a full URL. They are saved simply as: `/docs/appeals/Active/MDRCD026.pdf`

I deduced that this refers to `http://ifrc.org/docs/appeals/Active/MDRCD026.pdf`. However, the API can't make the same assumption. After I visited the page for this appeal, I fixed two instances of this error, and can now make the changes I need to on the appeal.

https://prddsgocdnapi.azureedge.net/admin/api/appeal/3078/change/?_changelist_filters=q%3DMDRCD026

Unfortunately the error message that shows up when this occurs is quite small and hard to catch, but that is what's happening.
