### ISSUE TITLE
Zone removed from the deployment tab & IFRC added as a deploying entity 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#467]
## Issue

In the deployment tab – we should have removed the naming of “Zone” for the Regional Office and we are missing the IFRC as a deploying entity – which unfortunately the name of the NS is linked to the Country and there is no existing IFRC country. This means I cannot add the IFRC as a country name that then enables us to choose those deployed by the IFRC as some core elements are required (correctly) such as ISO 2 Code. This was already discussed and my understanding was that we had agreed on these changes.

**Comment by dereklieu** [comment]
@omniscjencja I opened a ticket for this in https://github.com/IFRCGo/go-frontend/issues/475. Right now there's not a great workaround here. A "zone" country entry, or an IFRC country entry, might be your best bet.

I believe @szabozoltan69 removed the requirement to attach a region to a country, and ISO codes, while required, do not have to correspond to anything (ie it could be `zz`).

**Comment by szabozoltan69** [comment]
Yes, the region is now optionally linked to the country. (Otherwise it can be selected from an option list, so can not be anything, but it can be left empty.)
