### ISSUE TITLE
Automatic reminder of usernames

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#470]
Several users have contacted us requesting a reminder of their username (rather than password). They may not have used the DMIS for a long time and have forgotten their usernames. Would it be possible to automate this process by a username reminder?

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 I think the idea here is to add a "forgotten username" option (in addition to forgotten password). Many users have registered to the DMIS but forgotten their credentials. They then register a new account with the same account, which will block their account. Does Django allow such recovery of a username, based on the user's email address?

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Yes, we can implement this feature: to send the user's username for the given email address, if exists in GO database.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Do you think about a real automatic (e.g. monthly) sent message? Or just a link on the webpage?

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 A link to the webpage should be sufficient, at least for now.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Would this feature (a link on the webpage) become available at Phase 3 or earlier?

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC I think it can be solved before Phase 3 (in a few days).

**Comment by szabozoltan69** [comment]
This kind of link is acceptable for that purpose? (Or better to put in one line both?)

![forgot_username](https://user-images.githubusercontent.com/6050643/49383681-9c1a1c00-f719-11e8-9a66-2ec1db8156cc.png)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 This looks good, feel free to take it to production.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC You can test it (using your email address) on https://dsgoproxyapp.azurewebsites.net/login – on Wednesday it can go to production.

**Comment by szabozoltan69** [comment]
Now it is in production.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 This feature is working just as we wanted.
