### ISSUE TITLE
Better error checking for DMIS ingests

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#474]
Now that some countries have been deleted from the API, the DMIS ingest is breaking, since the original country list came from DMIS.

This means that **some field reports from DMIS will have no place to ingest to** because you've decided that the countries they pertain to no longer exist. cc @LukeCaley @ElsaRaunioIFRC 

In order to get the DMIS ingest working again, I will add error checking to ignore these field reports if a country isn't found.

**Comment by dereklieu** [comment]
Ok update to say that it isn't being thrown by field reports from non-existant countries, it is being thrown by users who have marked their country as ones that no longer exist. I assume these are the "zone" countries. 

I have a fix for this but can't test it without syncing my development environment to production, re https://github.com/IFRCGo/go-frontend/issues/460#issuecomment-428736512. @ElsaRaunioIFRC if you could please remove countries from the api fixtures as you did in the admin, I can verify it's working and make a PR.

**Comment by szabozoltan69** [comment]
I attach the fresh "Countries" table from DMIS database. Is this what you were looking for? 
[MDIS_countries.xlsx](https://github.com/IFRCGo/go-frontend/files/2585315/MDIS_countries.xlsx)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Is there any further work required from our side?

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC No, you can close it, thank you.
