### ISSUE TITLE
Appeals are not linked to countries 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#478]
## Issue

Many Appeals that were imported to GO from other Red Cross systems are not linked to a country. 

## Expected behavior

Each Appeal should be linked to a relevant country, or in case of Regional Appeals to a corresponding country of Regional Office.

**Comment by dereklieu** [comment]
@omniscjencja could you give me an example please?

**Comment by omniscjencja** [comment]
[data from go.xlsx](https://github.com/IFRCGo/go-frontend/files/2473358/data.from.go.xlsx)

**Comment by omniscjencja** [comment]
those are just for Africa, we got the issue reported directly from the field

**Comment by dereklieu** [comment]
I mean, is there a specific appeal code that I can look up in Go, where the country should be attached but isn't?

**Comment by omniscjencja** [comment]
all of the appeals in the attached excel sheet are missing the country

**Comment by omniscjencja** [comment]
MDRCD022
MDRCD020
MDRCD019
MDRGM011
MDRTZ020
MDRSS005
MDRCD018
MDRCD017
MDRTZ019
MDRCD016
MDRTZ018
MDRCI009
MDRCI008
MDRSS004
MDRTZ017
MDRGM010
MDRCI007
MDRTZ016

**Comment by omniscjencja** [comment]
just an example

**Comment by dereklieu** [comment]
Thank you. I believe these were created in the initial export in February, and at the time we had no way of matching countries beyond country name. These were the countries where the names did not match what we use in Go.

We now use iso2 codes and don't have this problem, however it seems this initial batch of imports were not corrected. 

Once this PR is merged and deployed to master, these appeals should be updated and countries added.

https://github.com/IFRCGo/go-api/pull/316

**Comment by LukeCaley** [comment]
Thanks @dereklieu 
@omniscjencja Can you track and double check this once the PR is deployed to master?

**Comment by szabozoltan69** [comment]
This above PR is deployed to master.

The above appeals are OK in http://go-api.ifrc.org/api/appeals :
```
MDRCD022: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRCD020: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRCD019: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRGM011: <GEC_code>GM</GEC_code><OSC_name>Gambia</OSC_name>
MDRTZ020: <GEC_code>TZ</GEC_code><OSC_name>Tanzania</OSC_name>
MDRSS005: <GEC_code>SS</GEC_code><OSC_name>South Sudan</OSC_name>
MDRCD018: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRCD017: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRTZ019: <GEC_code>TZ</GEC_code><OSC_name>Tanzania</OSC_name>
MDRCD016: <GEC_code>CD</GEC_code><OSC_name>Democratic Republic of  Congo</OSC_name>
MDRTZ018: <GEC_code>TZ</GEC_code><OSC_name>Tanzania</OSC_name>
MDRCI009: <GEC_code>CI</GEC_code><OSC_name>Cote d'Ivoire</OSC_name>
MDRCI008: <GEC_code>CI</GEC_code><OSC_name>Cote d'Ivoire</OSC_name>
MDRSS004: <GEC_code>SS</GEC_code><OSC_name>South Sudan</OSC_name>
MDRTZ017: <GEC_code>TZ</GEC_code><OSC_name>Tanzania</OSC_name>
MDRGM010: <GEC_code>GM</GEC_code><OSC_name>Gambia</OSC_name>
MDRCI007: <GEC_code>CI</GEC_code><OSC_name>Cote d'Ivoire</OSC_name>
MDRTZ016: <GEC_code>TZ</GEC_code><OSC_name>Tanzania</OSC_name>
```
