### ISSUE TITLE
% Funded from emergencies not pulling to featured page for  Nigeria floods

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#481]
## Issue
On  https://go.ifrc.org/ under highlighted emergencies Nigeria Floods there is no % funded figure .
When you click on the Nigeria floods  box it takes you to https://go.ifrc.org/emergencies/3136 which actually has the funding figure and the budget figure to calculate the percentage funded. 

*Please describe your issue. If possible, include when you first encountered the issue, who it affects, a link to a relevant page, and any other information that might be helpful in diagnosing it's cause.*

![image](https://user-images.githubusercontent.com/7780809/47139060-34b82200-d2bb-11e8-8c82-3c7f0fc5113c.png)

## Steps to reproduce
1. Open https://go.ifrc.org/
 2. Check the highlighted emergencies 
*If you can reliably reproduce the issue, please list the steps taken to do so.*

## Expected behavior

On https://go.ifrc.org/ under Highlighted Emergencies the box with Nigeria floods should have a figure for % funded.  

*Please describe how this feature should be working.*

**Comment by szabozoltan69** [comment]
On the admin interface we can search in Home › Api › Emergencies the Nigeria floods. There are 7 of them. Maybe the "Featured" checkbox is checked at the wrong one? The 3136 id emergency has this "Featured" checkbox checked, and it has no attached field report at all.

**Comment by szabozoltan69** [comment]
If I check funded/requested amounts, then this can be seen:

![funded_requested](https://user-images.githubusercontent.com/6050643/47153363-b4f07e80-d2df-11e8-91c1-bbaeb777a598.png)

**Comment by szabozoltan69** [comment]
I found the solution, we should change featured-emergencies.js (L27-28) from
```
    const requested = appeals.reduce((acc, curr) => acc + curr.amount_requested, 0);
    const funded = appeals.reduce((acc, curr) => acc + curr.amount_funded, 0);
```
to
```
    const requested = appeals.reduce((acc, curr) => acc + Number(curr.amount_requested), 0);
    const funded = appeals.reduce((acc, curr) => acc + Number(curr.amount_funded), 0);
```

**Comment by szabozoltan69** [comment]
I've put to staging and production.
