### ISSUE TITLE
API not Pulling Movement Appeal funding MDRSS006 & MDRNG022

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#486]
## Issue

The GO API is not pulling in the funding for the 'Movement appeal` type .

*Please describe your issue. If possible, include when you first encountered the issue, who it affects, a link to a relevant page, and any other information that might be helpful in diagnosing it's cause.*

The GO API is not pulling in the funding for the 'Movement appeal` type this affects two operations MDRSS006 & MDRNG022 found at  https://go.ifrc.org/emergencies/5  and https://go.ifrc.org/emergencies/9 respectively.  When you update this manually the API overwrites it every hour with 0.00 funding. 

## Steps to reproduce

*If you can reliably reproduce the issue, please list the steps taken to do so.*

## Expected behavior
![image](https://user-images.githubusercontent.com/7780809/47210591-a5cb0880-d393-11e8-8a61-940ad957f2aa.png)

*Please describe how this feature should be working.*

**Comment by szabozoltan69** [comment]
I think that the API is pull these entities also – maybe the frontend does not display them. On API backend they can be seen (really with intl type):
![mdrss006](https://user-images.githubusercontent.com/6050643/47217118-9eadf580-d3a7-11e8-8dfa-4215c906ecd9.png)
![mdrng022](https://user-images.githubusercontent.com/6050643/47217121-a2417c80-d3a7-11e8-9695-11255d8562d7.png)

**Comment by toffehoff** [comment]
According to Business Objects there is a significant contribution:

![bo](https://user-images.githubusercontent.com/705634/47224846-3cfc8400-d3c5-11e8-9f6b-86091366a945.png)

**Comment by szabozoltan69** [comment]
So the task is at the financial API – why does this not appear in http://go-api.ifrc.org/api/appeals ?

**Comment by toffehoff** [comment]
That, and the manual override does not work. Not sure if that is intended or a "feature". But yes, the incorrect data from the financial API is a more urgent issue ...

**Comment by szabozoltan69** [comment]
It was a new decision to "do not look at modification date, always use all data" from financial API, and due to this, everything is overwritten hourly (in the cases where there is manual and automatic gained data). In the future we can give a higher priority to manual figures, if needed.

**Comment by toffehoff** [comment]
That is a fair decision. Assuming the data from the financial API is always correct. As it should, since that is the "factual truth". 
Back to the bigger problem: why is the API showing a different number as the reports in Business Objects.

**Comment by mmusori** [comment]
Dear All
Is it possible to fix this issue soon. If the API is pulling in the data from the data warehouse then the problem is in pushing it on to GO.

**Comment by dereklieu** [comment]
I'm closing this as it's not an issue with the Go source code, and there are no next actions in this repo.

### Explanation:

Go reads financial data from the API at [http://go-api.ifrc.org/api/appeals](http://go-api.ifrc.org/api/appeals). This API is still showing 0 (aka `nil`) contributions for the appeals in question. Go is successfully reading this number, as it does for other appeals. 

### Resolution:

Once someone on the financial API side can make sure that this contribution figure is correctly configured, Go will automatically read the number and update itself and the website.

@toffehoff @mmusori I would advise you to open a line of communication about this with the team responsible for the financial API. They need to correct the bug that causes these contribution amounts to show up as `nil`.
