### ISSUE TITLE
Opening page is blank in Internet Explorer

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-frontend#488]
## Issue

The opening page of go.ifrc.org is blank in Internet Explorer.

## Steps to reproduce

If we type go.ifrc.org/emergencies (or other subpage) it can be seen fine, and after that we can navigate to the opening page (and it renders fine). But direct calling go.ifrc.org is blank.

## Expected behavior

go.ifrc.org should not be blank even on MSIE.

**Comment by dereklieu** [comment]
There are many versions of MSIE, and most of them aren't officially supported. Which version are you seeing this in?

**Comment by szabozoltan69** [comment]
I tried it in a fresh (Windows 10) Internet Explorer 11.
Otherwise in Edge (which is the preferred browser for Microsoft) it is fine.
But we can put some effort to make MSIE working, it should not be impossible. (If not other way, redirecting to a subpage if the detected browser is MSIE.)

**Comment by szabozoltan69** [comment]
Otherwise MSIE market share is below 3% today...
http://gs.statcounter.com/browser-market-share

**Comment by szabozoltan69** [comment]
The error comes from the bundled vendor-...js script, which gives an error in case of MSIE.

**Comment by szabozoltan69** [comment]
Solved by fixing get-new-map.js
