### ISSUE TITLE
Event search / filter for adding personal deployments 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#492]
## Issue

When adding the personnel deployments on the admin site, it is not possible to search through the events to which a deployment should be added. In addition, events are not in alphabetical order and hence adding new deployments is very tedious. 

## Expected behavior

Since first one has to select a country, it would be nice if the events were narrowed down only to the country previously selected. Also it would be great to be able to search for the particular event.

**Comment by omniscjencja** [comment]
![surge_admin](https://user-images.githubusercontent.com/29458013/47569697-90765100-d934-11e8-8d1d-2e247156482b.jpg)

**Comment by szabozoltan69** [comment]
Ok, I could find the suggested way.
```
class PersonnelDeploymentAdmin(admin.ModelAdmin):
    search_fields = ('country_deployed_to', 'region_deployed_to',)
    **autocomplete_fields = ('event_deployed_to',)**
```

**Comment by szabozoltan69** [comment]
Solved, see:

![search_pers_depl](https://user-images.githubusercontent.com/6050643/47651948-e6413800-db84-11e8-841a-2d4d5a765350.png)
