### ISSUE TITLE
DPR Korea not shown in GO 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#497]
## Issue

When downloading data from GO, all operation concerning DPR Korea have country name missing, which results in them not being shown in the map on the front page. Please see the screenshot attached. 

![5](https://user-images.githubusercontent.com/29458013/47649321-3ae0b500-db7d-11e8-9cfa-d1d05caa840f.jpg)

**Comment by szabozoltan69** [comment]
The missing name in the downloaded table and the missing name of the front page map has a common root; the registry of the country ID-s (like DPR Korea's one) could be inconsistently changed in different systems.

**Comment by szabozoltan69** [comment]
It can be in connection with this deployment error:
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_permission_content_type_id_codename_01ab375a_uniq"
DETAIL:  Key (content_type_id, codename)=(13, country_admin_193) already exists.
```

**Comment by szabozoltan69** [comment]
Maybe it's an upper/lowercase question? In data/Countries.csv:
api.Country,192,"Korea, Rep.",kr,2,The Republic of Korea National Red Cross,http://www.redcross.or.kr/
api.Country,193,"Korea, Dem. Rep.",**KP**,2,Red Cross Society of the Democratic People's Republic of Korea,
api.Country,194,Mongolia,mn,2,Mongolian Red Cross Society,http://www.redcross.mn/
api.Country,195,"Micronesia, Fed. Sts.",fm,2,Micronesia Red Cross,

**Comment by szabozoltan69** [comment]
If we check on the admin interface the North-Korean appeals: MDRKP001 .. 012, all of them has a missing Country field. This way that is no miracle that no country is attached to them. Maybe some incoming-data/Country-iso-code difference causes this? Anyway, data cleaning is not scope of the development:
![no_country](https://user-images.githubusercontent.com/6050643/47659369-1d1f4a00-db95-11e8-903a-621b6c4697c3.png)

**Comment by szabozoltan69** [comment]
It can be solved by data cleansing, and I'll do it.
select * from api_country where id=193;
193 | Democratic People's Republic of Korea ...
```
update api_appeal set country_id=193 where name like 'DPR Korea%';
UPDATE 12
```

**Comment by szabozoltan69** [comment]
Now it's OK.
![korea_is_ok](https://user-images.githubusercontent.com/6050643/47660448-4d67e800-db97-11e8-90d7-04c0a6bec521.png)

**Comment by dereklieu** [comment]
To make sure this doesn't reoccur someone should check that the `gec_code` which comes from the appeals API matches the iso code in Go.

**Comment by szabozoltan69** [comment]
Thank you for to good idea. It seems to be OK:
<GEC_code>**KP**</GEC_code><OSC_name>Democratic People Republic of Korea</OSC_name>
