### ISSUE TITLE
adjust order of snippets on emergency page?

### ISSUE THREAD

**Issue by danbjoseph** [IFRCGo/go-frontend#498]
on https://go.ifrc.org/emergencies/3288

we can't seem to adjust the order of the iframe embeds in the snippets for when they display on the page. it appear that the most recently added appears at the top? regardless of which snippet is pasted into which box when editing the page.

**Comment by dereklieu** [comment]
Very likely using `-created_at` to order it, which would be consistent with what you're seeing. The order in which they're entered in the UI would not affect things. 

Potentially there could be an `order` field where you could put numbers and it would sort in descending or ascending order, however having them mimic the order in which you see them on the page would be difficult, as this isn't a wysiwyg editor. In the meantime you could delete a snippet and then re-attach it (copy, delete, paste, save) if you wanted it to appear up top.

**Comment by danbjoseph** [comment]
so would need to delete all. then add one at a time, saving after each, in reverse order, to get them to appear in a specific order?

**Comment by dereklieu** [comment]
I understand that for an emergency with a lot of snippets, this isn't ideal. We can look a little bit for a better solution, however would a non-reverse created-at order be better? IE, order so that the oldest snippet comes first. This would be a quick change.

**Comment by danbjoseph** [comment]
ah, i can also just put the all the iframe embeds in a single snippet with line breaks between them.

**Comment by dereklieu** [comment]
That works too!

**Comment by ElsaRaunioIFRC** [comment]
We are instructing our IM collegues to use the method suggested by @danbjoseph. This should solve the issue with the snippet order.

**Comment by ElsaRaunioIFRC** [comment]
I have reopened the issue as from the user perspective, it is more intuitive to add the frame snippets separately and still have an option to control the order.

**Comment by ElsaRaunioIFRC** [comment]
New snippets are being added on the [Indonesia page ](https://go.ifrc.org/emergencies/3288) every week. However, due to the current bug (as described in the first message), we cannot order the snippets in any sensible way. 

We currently have three sub-operations under the Indonesia Earthquake & Tsunamis page: Lombok, Central Sulawesi and Sunda Straits. It would make sense to find a way to classify the snippets into different sub-operations.

**Comment by szabozoltan69** [comment]
Now I added a "weight" field to the snippet table (in the API) – the front-end will soon follow this. Order by: weight (default 10), then id (if possible).

**Comment by szabozoltan69** [comment]
Done. Front-end change was not necessary. @ElsaRaunioIFRC Please test it.
