### ISSUE TITLE
"Add report" and "Edit event" button doesn't work for users with limited rights 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#500]
## Issue submitted by Sune 

"add report" and "edit event" button on the emergency page doesn't work for anyone besides super users. Even if a user is given admin rights to add and edit reports, clicking on the button returns and error. It is really user unfriendly, as then a user has to log in to admin page and look for a given emergency etc.

**Comment by szabozoltan69** [comment]
Could you please give a URL example for this?

**Comment by omniscjencja** [comment]
![2](https://user-images.githubusercontent.com/29458013/47908845-738ad200-de8e-11e8-917d-d691c30c5ce7.jpg)

basically when a user is on an emergency page and clicks add a report, he gets a 403 error 

![1](https://user-images.githubusercontent.com/29458013/47908860-83a2b180-de8e-11e8-923a-3f3c14c9ccaa.jpg)

**Comment by omniscjencja** [comment]
![3](https://user-images.githubusercontent.com/29458013/47909051-10e60600-de8f-11e8-920e-bb92ef4d646a.jpg)

but they have access to admin page, when they log directly there

**Comment by szabozoltan69** [comment]
If you give proper rights to the user (e.g. "emergencies", which is a synonyme for "events") then the permissions are OK for edit events.

![event_equals_emergency](https://user-images.githubusercontent.com/6050643/48129948-5dfd1a00-e28b-11e8-9cff-5fcc5e5786da.png)

The solution for manipulating reports is similar. The user has to have "report..." permissions.

**Comment by szabozoltan69** [comment]
This was "Emergencies" should be seen on the user's page:

![emerg](https://user-images.githubusercontent.com/6050643/48131111-34de8880-e28f-11e8-8d7e-f19246c79d15.png)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Should we merge the issues concerning user rights? Our vision is to have a 5-Tier user system, as seen in this organigram: https://drive.google.com/file/d/1cL2QstYMqPKPlj9gr9azTiJt_A7bTvSF/view?usp=sharing

This is the document describing the user profiles and their correspondent rights:
https://docs.google.com/document/d/1q5IixAZSSRKsVcXc6bl3nQVhn6EmmpdrpKHdiyUlX04/edit?usp=sharing

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Yes, we can merge these issues, if it makes life better.

**Comment by nanometrenat** [comment]
Closing as will be part of user permission review.
