### ISSUE TITLE
Disaster type not showing in tables on GO 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#501]
## Issue

In the lists of Active Operations, Emergencies or Field Reports, the disaster type data is missing. Please see the screenshots attached. 

![1](https://user-images.githubusercontent.com/29458013/47905303-12abcb80-de87-11e8-80fc-797213c2e687.jpg)
![2](https://user-images.githubusercontent.com/29458013/47905306-14758f00-de87-11e8-8270-0a4af3770dbf.jpg)
![3](https://user-images.githubusercontent.com/29458013/47905310-16d7e900-de87-11e8-8515-a8216c269e72.jpg)

**Comment by szabozoltan69** [comment]
The fix can be tested on staging website: https://dsgoproxyapp.azurewebsites.net/ – it will be on production soon.
