### ISSUE TITLE
Lack of search function for events when adding a Situation Report. 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#502]
## Issue

Lack of search function for events when adding a Situation Report. 

![1](https://user-images.githubusercontent.com/29458013/47909773-31af5b00-de91-11e8-9394-bef6606127eb.jpg)

## Expected behavior

It should be possible to search through the events to which one wants to add a document, as users with limited rights, have a very limited navigation of the admin site. 

![3](https://user-images.githubusercontent.com/29458013/47910738-0bd78580-de94-11e8-82f7-34eead7e28ce.jpg)

**Comment by szabozoltan69** [comment]
I've found the solution. De default autocomplete field is a bit narrow in Django admin, but it's usable.
![sitrep_add_searchable](https://user-images.githubusercontent.com/6050643/48127352-cb0cb180-e283-11e8-97f0-123ae8f89d97.png)
Will be on stage and production in some minutes.
