### ISSUE TITLE
Change default setting 'Public' when adding Situation Report

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#503]
## Issue

At the moment the default setting when adding a new document is 'Public'. Considering many documents are confidential, it would be better to change it to IFRC or Membership, in case a person adding it, doesn't notice. 

![2](https://user-images.githubusercontent.com/29458013/47911783-acc74000-de96-11e8-976b-042cad061c7b.jpg)

**Comment by szabozoltan69** [comment]
Changed to IFRC default.
