### ISSUE TITLE
User rights not showing on the admin page 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#504]
## Issue

Users do not have access to their given user rights. 

![1](https://user-images.githubusercontent.com/29458013/47914427-e2245b80-de9f-11e8-9fed-db99839f7621.jpg)

for instance this user was assigned a set of rights, including adding and editing ERUs and Situation Reports, but when he logs in to an admin site, he has no access 

![2](https://user-images.githubusercontent.com/29458013/47914462-0c761900-dea0-11e8-9cc4-3d884645aab4.jpg)

![3](https://user-images.githubusercontent.com/29458013/47914469-13049080-dea0-11e8-9315-527e00e0cd07.jpg)

**Comment by szabozoltan69** [comment]
It is not enough to move the privilege-rows to the other side, a "Save" is also to be pushed at the end.

**Comment by szabozoltan69** [comment]
Could not reproduce. If I move some privilege-rows to the right hand side, and push a "Save" after, the changes remained permanently.

![save1](https://user-images.githubusercontent.com/6050643/47996281-52c5b500-e0f8-11e8-9d3e-bf368b3e8ec7.png)

![save2](https://user-images.githubusercontent.com/6050643/47996283-56593c00-e0f8-11e8-9680-43520cfcdb05.png)

There is a message showing whether the changes happened.

**Comment by omniscjencja** [comment]
@szabozoltan69 Dear Zolta, the issue is not that the admin rights do not save on the user profile, but that I as a super user gave sb the admin rights to add, edit or delete ERUs, but when this person logged into their admin site, they could not actually do it. Hence, the screenshots. You can see that this particular user was given more rights than those showing for him, when he logged in.

cc @LukeCaley @guipizzini @mmusori

**Comment by szabozoltan69** [comment]
@omniscjencja Could you please help me by giving the user id? (Maybe better in email to protect  his/her personal data: zoltan.szabo@ifrc.org.). Or an other possibility is to create a user in test environment (https://dsgocdnapi.azureedge.net/admin ) with the same permissions and test things with it.

**Comment by omniscjencja** [comment]
@szabozoltan69 e-mail sent

**Comment by szabozoltan69** [comment]
Thank you.
I created a similar test user in test environment: https://dsgocdnapi.azureedge.net/admin/
username: permissioncheck-testuser (password is in email).
You should give him the concerning regions also. (None of them is given.) Then, if the effect is good, you can perform it on the production user also.

**Comment by szabozoltan69** [comment]
I suggest to select these possibilities:
```

api | region | Admin for Africa
api | region | Admin for Americas
api | region | Admin for Asia Pacific
api | region | Admin for Europe
api | region | Admin for Mena
api | situation report | Can add situation report
api | situation report | Can change situation report
api | situation report | Can delete situation report
deployments | deployed person | Can add deployed person
deployments | deployed person | Can change deployed person
deployments | deployed person | Can delete deployed person
deployments | eru | Can add eru
deployments | eru | Can change eru
deployments | eru | Can delete eru
deployments | ERUs from a National Society | Can add ERUs from a National Society
deployments | ERUs from a National Society | Can change ERUs from a National Society
deployments | ERUs from a National Society | Can delete ERUs from a National Society
deployments | FACT | Can add FACT
deployments | FACT | Can change FACT
deployments | FACT | Can delete FACT
deployments | FACT Person | Can add FACT Person
deployments | FACT Person | Can change FACT Person
deployments | FACT Person | Can delete FACT Person
deployments | HeOp | Can add HeOp
deployments | HeOp | Can change HeOp
deployments | HeOp | Can delete HeOp
deployments | partner society activities | Can add partner society activities
deployments | partner society activities | Can change partner society activities
deployments | partner society activities | Can delete partner society activities
deployments | partner society deployment | Can add partner society deployment
deployments | partner society deployment | Can change partner society deployment
deployments | partner society deployment | Can delete partner society deployment
deployments | personnel | Can add personnel
deployments | personnel | Can change personnel
deployments | personnel | Can delete personnel
deployments | personnel deployment | Can add personnel deployment
deployments | personnel deployment | Can change personnel deployment
deployments | personnel deployment | Can delete personnel deployment
deployments | RDRT/RIT | Can add RDRT/RIT
deployments | RDRT/RIT | Can change RDRT/RIT
deployments | RDRT/RIT | Can delete RDRT/RIT
deployments | RDRT/RIT Person | Can add RDRT/RIT Person
deployments | RDRT/RIT Person | Can change RDRT/RIT Person
deployments | RDRT/RIT Person | Can delete RDRT/RIT Person
notifications | surge alert | Can add surge alert
notifications | surge alert | Can change surge alert
notifications | surge alert | Can delete surge alert
```
