### ISSUE TITLE
improving the process of submitting field reports 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#512]
## Issue

Following feedback was submitted by a user: 

_The platform does not allow one to review the information shared before submission. Its good to have an interface that reminds you that when you click you will be submitting the update. 

Also referencing to the DMIS, it would be good to have a review page where all the information fed into the platform is brought back so the one submitting reviews._

We also had several cases of the same reports being submitted multiple times, because the page was freezing or not responding. And users provided following feedback: 

_Please note that on all the attempts on saving it mentioned the “ERROR: Could Not Submit Field Report”, and the report would not appear even after more than an hour of saving,

Is this a glitch or normal, just to know for future attempts,_

**Comment by szabozoltan69** [comment]
For me it's ok to merge some issues. The "can not submit ..." stuff usually seems to be network problem, and is not our competency.

**Comment by nanometrenat** [comment]
@mmusori advises that this issue can be closed - field reports have had a number of updates since this was logged.
I note that there was one 'could not submit' error recently but this was due to a country mapping issue that has since been solved.
