### ISSUE TITLE
Feature to further restrict the visibility of response documents

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#517]
New (20/11/2018)
Currently, the visibility of the response documents can be restricted to "IFRC" or "Membership". However, it is currently not possible to hide response documents from GO users who are not involved in the specific operation. 

To carry out this, we would require a feature to assign staff members into a specific operation and set the visibility as "Operations Specific".

Original (19/11/2018)
When the "Visibility" setting of the Situation Reports and other Response Documents is set to "IFRC", those outside of the IFRC (e.g. a national society) won't be able to see the document. Setting them

Since many of the operations staff is deployed from outside of the IFRC, they won't be able to see the documents with the visibility setting as "IFRC". In case the setting is "Public", the documents will be shown for all registered GO users. Due to the sensitive nature of some response documents, they must be shown for the operations-specific personnel only.

Is there an option to add an "Operations Membership" for the registered users? Any other workaround would also be helpful.

**Comment by dereklieu** [comment]
Isn't there a third, "membership" option, for users with a login who are not IFRC? This seems to be built to address your issue.

**Comment by ElsaRaunioIFRC** [comment]
Hi @dereklieu, Thanks for the quick response. Does the "Membership" option apply universally on all Go pages or can it be operations-specific?

If, let's say, an American Red Cross member is deployed for Indonesia Earthquake, we want him to see the Indonesia-specific SitReps but not those related to DR Congo Ebola (for example). Does the current membership/admin rights combination allow this kind of operations-specific restrictions?

**Comment by dereklieu** [comment]
Membership means anyone with a login who is currently logged in can view the content. 

On the backend there are more powerful levers to control access and editing rights based on a user's region or country, but as far as displaying things on the front-end, there are only these three for the time being.

**Comment by ElsaRaunioIFRC** [comment]
In this case, we will go for the "Membership" option now. However, we will inform the users that as for now,  response documents cannot be hidden from non-Ops staff.

Should I close this issue and open another one about the Ops-specific user rights? This could be a Phase 2.2, even 3.0 issue.

**Comment by ElsaRaunioIFRC** [comment]
A quick fix for this issue: ask all deployed personnel to use @ifrc.org email address (rather than, for example, the NS email address). We will make sure to increase our outreach on this.

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC I think it's useful to keep this ticket open so that our conversation can provide context for future development. You could just edit the title so it better reflects the feature.

**Comment by nanometrenat** [comment]
Closing due to upcoming permissions review
