### ISSUE TITLE
Changed appeal host country overwritten

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#519]
In very rare occurrences, we may have to change the initial host country of an emergency or appeal. 

Currently, this is the case with MDR65002. The related emergency took place in Crimea and the field report was submitted by the Russian Red Cross. Due to political considerations, the appeal was assigned to the Europe Regional Office located in Hungary. However, since this is not a multi-country appeal (as usual with the regional appeals), it would be very misleading to show this appeal in Hungary. 

From the general IFRC point of view, the location of this appeal and the associated emergency is in Ukraine. Yesterday, I changed the country from Hungary to Ukraine but it was overwritten a few hours later.

In order to avoid putting us in an awkward situation, I suggest we add an opportunity to manually change the location of the appeal.

I am happy to provide further information of this Russia/Ukraine/Hungary case by email.

**Comment by szabozoltan69** [comment]
The appeals arrive hourly from the financial (appeal) api.

A quick solution could be the possibility to give an APP_code list for which the automatic overwriting is omitted (so recently it is MDR65002). So, if it is a recurring need, we can find out a nice data representation of this (e.g. a new status, "active and constant" or so, or just create a table for these appeals), but now it would be the easier to wire in the MDR65002 into the appeals ingesting program (to forget the renewal of this appeal).

**Comment by ElsaRaunioIFRC** [comment]
We anticipate this need to be very rare (I'll provide more information on email). We can go for the easiest option as long as we can make sure that the changes won't be overwritten.

**Comment by szabozoltan69** [comment]
OK, I've patched the program, now the manual changes of MDR65002 will be persistent.
I've put these rows to line 77:
```
#               Temporary filtering, the manual version should be kept:
                if r['APP_code'] in ['MDR65002']:
                    continue
```

**Comment by dereklieu** [comment]
@ElsaRaunioIFRC could the country of the appeal not have been changed in the source financial database? That would have fixed this without the need to introduce a temporary one-liner that someone will have to remember to revert later.

**Comment by ElsaRaunioIFRC** [comment]
@dereklieu Handling the financial database is beyond our reach as the decision is made higher in the organisation. 

I would like to highlight that this kind of problem will be very rare - once a year or even less. 

As the last option, we could also hide controversial appeals as this from GO.
