### ISSUE TITLE
website crashing when uploading multiple documents 

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#535]
## Issue

One of the users / ops, reported that the website was crashing when he was trying to submit more than one document at once and therefore he had to submit all 13 documents separately. 

## Expected behavior
![antoine](https://user-images.githubusercontent.com/29458013/49089018-e6ebed80-f25a-11e8-9f8e-307bfabc53f3.jpg)

**Comment by szabozoltan69** [comment]
The fact that a maximum ~5MB is uploadable at once is known. Derek suggested to build an Amazon test enviroment for debugging (among more) this upload issue, but Luke postponed this proposal to the next year. Until then it can not be solved easily, and ops has to take the time for the uploads.

**Comment by nanometrenat** [comment]
@LukeCaley is this still a regular problem for users?

**Comment by LukeCaley** [comment]
I am not aware of anyone notifying us of this issue but that doesn't mean it does not exist. @sanjay @szabozoltan69 are you aware of the limitations?

**Comment by nanometrenat** [comment]
I'm closing this issue as no action since 2018 - we will raise a new ticket if users identify this problem again.
