### ISSUE TITLE
Spaces in usernames

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#538]
Currently, it is possible to register a username with spaces in it. However, when you try to modify the user, such as assign them more user rights, the system gives the error message below:
![image](https://user-images.githubusercontent.com/31092591/49213341-5f21f280-f3c4-11e8-97f0-522022bc551e.png)

I see this problem being fixed either by
1) Do not allow spaces in names upon registration on Go.
2) Change the settings in Django so that spaces will be allowed.

I think the latter solution would be more sustainable as we currently have plenty of old DMIS usernames with spaces.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC I strongly suggest the 1st version: not allowing spaces at registration time.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 OK, let's choose this option.

**Comment by szabozoltan69** [comment]
I've found the solution. It will be deployed along with the new Django banner, because both of them had to implement in backend side. I write when it is done.

**Comment by szabozoltan69** [comment]
Done.
