### ISSUE TITLE
Field reports not exporting

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#539]
I have tried exporting the field reports over different connections and browsers but all I get is a long wait and an error message "Export failed". 

Since the field reports include an important part of our operational data, it is important to fix this problem.

**Comment by szabozoltan69** [comment]
True, it arrives for me also. Maybe it is due to the huge amount of field report data. I shall check it.
![fr_exp](https://user-images.githubusercontent.com/6050643/49230960-29dfc980-f3f1-11e8-8b6a-9fb25e70169a.png)

**Comment by szabozoltan69** [comment]
For quick solution I suggest to divide the data along regions, then no error occur:
https://go.ifrc.org/reports/all?region=0
https://go.ifrc.org/reports/all?region=1
https://go.ifrc.org/reports/all?region=2
https://go.ifrc.org/reports/all?region=3
https://go.ifrc.org/reports/all?region=4
These exported .csv-s gives all the field reports.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Do we have an option how to implement your suggestion on the front page? For example, when a user wants to export field reports, they are prompted to choose the region first.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Good idea! I think about the implementation...
A quick and easy solution would be to change the link at the bottom of the /emergencies page instead of:
_View all field reports_

To
View all field reports of Africa
View all field reports of Europe
...
Can I implement this?

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Looks good, let's go for this option, in this phase (until we find the way to export all at once).

**Comment by szabozoltan69** [comment]
I found this design the best workaround. Please test it in dev environment @ElsaRaunioIFRC
https://dsgoproxyapp.azurewebsites.net/emergencies/

![more_links](https://user-images.githubusercontent.com/6050643/49365253-99ea9a00-f6e6-11e8-8960-139d57ceda71.png)

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Looks good, please go ahead.

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC Thank you for the green light, now it is in production.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 I have one more suggestion: Could we amend the .csv names with the name of the region, e.g. field-reports-africa, field-reports-asia-pacific, etc? This would make the data management easier for the end user.

**Comment by szabozoltan69** [comment]
Good idea, I continue the work with it...

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC You can test it in dev environment, e.g. https://dsgoproxyapp.azurewebsites.net/reports/all?region=2 | I increased a limit variable also, but I am not sure that it (alone) solves the "Export All" problem.

**Comment by ElsaRaunioIFRC** [comment]
Looks good in production. I'm closing the issue.

**Comment by dereklieu** [comment]
I think this was a good solution @szabozoltan69. On one hand, there's not much we can do about the fact that the entire table export will be thousands of rows, and that this number will only increase from here.

However, at least during development earlier this year, I remember the field report export being consistently successful, albeit somewhat slow. I don't think we've created more field reports during this time to push this over some kind of performance edge. I would look into whether other features we've implemented, ie parsing and re-rendering headers to make them more human-readable, are inadvertently causing performance issues that cause this fix to be necessary in the first place.

**Comment by szabozoltan69** [comment]
Yes, you are right, Derek: the "more human-readable" header is the main reason of the less performance (or the overuse of memory). If someone really wants to have an "all-in-one" .csv export for field reports, then the nice header should be omitted (or fix afterwards manually with an other tool).
