### ISSUE TITLE
Emergencies table not exporting

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#553]
@szabozoltan69 Any attempt to export the emergencies results in a network error - we have tried exporting over several different networks.

![image](https://user-images.githubusercontent.com/31092591/50333080-6ee4b080-0504-11e9-95ca-46a5170608c3.png)

With this being on of the core datasets on Go, it is very important to fix this issue as soon as possible.

**Comment by szabozoltan69** [comment]
Which "emergencies" do you mean?
In the main emergencies page there is a workaround to export some region's emergency list, and it worked fine for me now. Of course "all" the emergencies can not be exported, but it's a known (and wrote on the webpage) issue.

![eme](https://user-images.githubusercontent.com/6050643/50343236-5e453200-0526-11e9-911e-121695618766.png)

For me "as soon as poosible" is in january.

**Comment by szabozoltan69** [comment]
Somebody suggested me to use blob, filereader for this part of the program, as https://github.com/Stuk/jszip/blob/master/dist/jszip.js#L3459 does (and other MDN js programs does). This way we could extend the limits of the export data size. @dereklieu – could you give me some advices about this?

**Comment by dereklieu** [comment]
I don't have much experience with the `FileReader` spec unfortunately and can't say whether it would actually solve our problem or not.

**Comment by nanometrenat** [comment]
Speaking with @LukeCaley we would like to address this so that users can export the full list of emergencies (not just by region).  @batpad can you advise the technical requirements for such a fix?

**Comment by lauripynnonen** [comment]
Just to extend this ticket - the export fails with all surge alerts https://go.ifrc.org/alerts/all (currently 507 alerts), however when limiting the view to just FACT surge alerts (349 alerts, 1,223 KB csv file) the export works just fine. Maybe there is a magical limit somewhere between those numbers. 

Interesting side note: the exported FACT-surge file is named "surge-alerts-africa.csv" even though it does contain all  regions

**Comment by batpad** [comment]
This ticket is a bit old, and we've worked through a lot of these issues. I am closing this, but please feel to re-open tickets specific for CSV exports that may still be failing. There are a few things we did to greatly improve the stability of the Field Report CSV exports, and we can probably apply similar methods to try and improve other exports that still have issues.

Related:

 - https://github.com/IFRCGo/go-api/issues/738
 - https://github.com/IFRCGo/go-api/issues/708
