### ISSUE TITLE
document type dropdown overflow issue

### ISSUE THREAD

**Issue by danbjoseph** [IFRCGo/go-frontend#554]
"Mobilisation Table for Current Operation" is cut off when choosing document type
either expand the width of the option box? or shorten that doc type name?

<img width="394" alt="screen shot 2018-12-27 at 9 51 16 am" src="https://user-images.githubusercontent.com/4806884/50484167-1e19ff80-09bd-11e9-99f8-35123bcef8d0.png">

**Comment by szabozoltan69** [comment]
Please give me an URL to test it.
(This long name can be changed in the "Situation Report Types" section of the backend, e.g. to "Current Ops Mobilisation Table")

**Comment by danbjoseph** [comment]
screenshot is from https://go.ifrc.org/emergencies/3288

**Comment by szabozoltan69** [comment]
Thank you, now I see the place of the hidden menu point...
