### ISSUE TITLE
Some national society email addresses not recognised 

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#556]
Some users from the Norwegian Red Cross (@redcross.no) and Belgian Red Cross (@rodekruis.be) have not been able to register on Go because their email addresses have not been recognised as national society emails. This happens even though these are the official email address endings of the respective national societies.

When the email addresses are not recognised as official national society emails, the user is prompted to provide two references. However, references with @redcross.no or @redcross.be endings give the following error message:

![image](https://user-images.githubusercontent.com/31092591/50890975-8c1de800-13fb-11e9-9f0f-bdcd636d85de.png)

Is there anywhere a database of the recognised national society email endings? It would be good to check if this database is up to date.

**Comment by szabozoltan69** [comment]
Both redcross.no ( https://github.com/IFRCGo/go-api/blob/master/registrations/views.py#L116 ) and redcross.be ( https://github.com/IFRCGo/go-api/blob/master/registrations/views.py#L99 ) is on the "valid domain" list, so the registration should not ask 2 admin emails for them. On the screenshot we can't see which email address did the users use for registration.

**Comment by szabozoltan69** [comment]
rodekruis.be is not on the "valid domain" list. Should it be? And also gmail addresses are not good, even if the user has a redcross email adress also.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Belgian Red Cross is very exceptional because the country has three Red Cross societies. They use the following email endings:

@rodekruis.be (for the Flemish speaking part)
@croix-rouge.be (for the French speaking part)
@roteskreuz.be (for the German speaking part)

Accordingly, all of these should be made valid national society domains.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 The user from the Norwegian Red Cross had the following error message:

![image](https://user-images.githubusercontent.com/31092591/50894395-6563af80-1403-11e9-87aa-c83d6e9a662e.png)

**Comment by szabozoltan69** [comment]
Ok, I add this 3 Belgian domains to the list.

However, concerning the Norwegian user I still don't see the problem. (From this screenshot we can not see the email address (s)he gave [it could be ...@gmail.com], only the two contact addresses, but if I search for them in the "pending registration" table, I can't find them.)

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/342

**Comment by szabozoltan69** [comment]
Yes, it's true. Hopefully it's not a very frequent issue when a new IFRC-domain appears.
A smoother (but less safe) solution could be to keep these domain names in a database table.

**Comment by ElsaRaunioIFRC** [comment]
We will keep monitoring this and will report if this issue continues to persist.

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 We have identified another issue under this topic. The currently recognised email domain of the Portuguese Red Cross is @cruzvermelha.pt. However, the actual email domain should be @cruzvermelha.org.pt. 

Can I submit a pull request on this in the master file (linked above)?

**Comment by szabozoltan69** [comment]
I change  @cruzvermelha.pt to @cruzvermelha.org.pt in my next API merge, you do not have to create a pull request for this. Thanks for notification.

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/359

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69: The Austrian RC has provided us with their district-specific email addresses. Currently, the system recognises @roteskreuz.at as the only official RC email. However, the majority of the staff are using district-specific email addresses (see the list below). Would it be possible to add these in the recognised email domains?

Steiermark (Styria):                                        @st.roteskreuz.at
Salzburg:                                                           @s.roteskreuz.at
Burgenland                                                      @b.roteskreuz.at
Tirol (Tyrol)                                                      @t.roteskreuz.at
Wien (Vienna)                                                 @w.roteskreuz.at
Vorarlberg                                                        @v.roteskreuz.at
Kaernten (Carinthia)                                      @k.roteskreuz.at
Niederoesterreich (lower Austria)             @n.roteskreuz.at
Oberoesterreich (upper Austria)                @o.roteskreuz.at

**Comment by szabozoltan69** [comment]
@ElsaRaunioIFRC I've put these domains to the trusted domain list (on production site).

**Comment by ElsaRaunioIFRC** [comment]
@szabozoltan69 Would it be possible to add @trcs.or.tz into the trusted domains? This is the email domain for the Tanzanian Red Cross Society.

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/391

**Comment by teklal** [comment]
@szabozoltan69 : Could you add the email domain of the Polish Red Cross @pck.pl to the list of trusted domains? Thanks!

**Comment by szabozoltan69** [comment]
@teklal : Ok, it will be in the PROD system in an hour...

**Comment by teklal** [comment]
@szabozoltan69  There's actually another one to add as well: for Israel it's @mda.org.il

**Comment by szabozoltan69** [comment]
@teklal : Ok, I'll do it soon.

**Comment by szabozoltan69** [comment]
Done :-)

**Comment by teklal** [comment]
@szabozoltan69 Could you add @croixrouge-mali.org to the list as well?

**Comment by szabozoltan69** [comment]
Done :-)

(We could think about putting these into database... if such appending occurs weekly)

**Comment by teklal** [comment]
Yes, I agree that if this continues to be a frequent request we could think of another solution. Thanks for doing all the appending thus far @szabozoltan69 !

**Comment by teklal** [comment]
@szabozoltan69  Sorry Zoltan, there seems to be a spike in these requests at the moment. Could you add @redcrossghana.org to the list?

**Comment by szabozoltan69** [comment]
Yes, in the evening...

Tekla Larinkoski <notifications@github.com> ezt írta (időpont: 2019. okt.
15., K 17:42):

**Comment by teklal** [comment]
@szabozoltan69  Another Austrian Red Cross email domain to add to the list :D 
@roteskreuz-innsbruck.at
Sorry and thanks Zoltan!

**Comment by szabozoltan69** [comment]
@teklal Hi, I added it to production site.

(Now I used a "quick and dirty" solution, logging into the production site docker and changing the file on site, then giving a 'python  -m py_compile views.py' command. This way we should not play the whole deployment process for every single added domain name. If you (or anyone) can test it, please do it. The "normal" deployment will happen at the next bigger program change, containing – of course – this change also.)

**Comment by teklal** [comment]
Hi @szabozoltan69 , there's another one to be added: @redcross.org.mk for the Red Cross of the Republic of North Macedonia

**Comment by szabozoltan69** [comment]
Ok, Thanks Tekla, I put it to the system on the quick way... (At 11:20 it can be used.)

**Comment by nanometrenat** [comment]
Hi, a few from the Pacific...
Tonga Red Cross' domain is below (switched to this in 2018 as part of IT upgrade):

- tongaredcross.to

Vanuatu Red Cross uses a number of domains:

- redcrossvanuatu.com (mostly this one for email)
- VRCS also use redcross@vanuatu.com.vu as their main public-facing enquiries email address
- vanuaturedcross.org is the official website

Cook Islands Red Cross advertises their mail domain as being

- redcross.org.ck

More to come... let me know if I can self-serve, thanks

**Comment by szabozoltan69** [comment]
Hi Natalie, @nanometrenat ,
 I'll put them in (except vanuatu.com.vu – we can put only domain names into this list, and the whole vanuatu.com.vu is not RedCross-related). The self service is not so straightforward recently, due to the backend deployment is more sophisticated. There was a plan to put these data into admin tables in the future.

@GregoryHorvath it's a repetitive task, if you'll have time let's discuss it. Quite simple: only to put the new domain names intohttps://github.com/IFRCGo/go-api/blob/master/registrations/views.py – if possible, to it's "logic place", ~ in alpahbetic or similarity order.

**Comment by nanometrenat** [comment]
Further domains to please add to the whitelist:

- Albania - kksh.org.al
- Fiji - redcross.com.fj
- Palau - palauredcross.org
- Papua New Guinea - redcross.org.pg
- Solomon Islands - redcross.org.sb

**Comment by lauripynnonen** [comment]
Further domains for European Red Cross Societies 
kksh.org.al
rcsbh.org
krc.kg
ckrm.org.mk
tgymj.gov.tm

**Comment by lauripynnonen** [comment]
could you also add redcrossnigeria.org

**Comment by mmusori** [comment]
Looks like the following domains are not on the white list:
redcross.org.sz
croixrouge-gabon.org
redcross.org.ls
liberian-redcross.org
crmada.org
redcross.mw
mauritiusredcross.org
redcrossnigeria.org
southsudanredcross.org

**Comment by nanometrenat** [comment]
Closing this ticket now the magical back-end page to administer whitelisted domains is in play.  Thanks all!
https://github.com/IFRCGo/go-api/issues/669
