### ISSUE TITLE
Add Sort/Filter Functionalities to tables

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#58]
**Emergencies**
date - dropdown 
Name - sort alphabetical
Disaster Type - dropdown
total affected - sort 
total beneficiaries  - sort

**Field Reports**
date -dropdown
disaster type- dropdown
region - dropdown 

**Appeals/Drefs**
date -dropdown
name - alphabetical 
disaster type -dropdown
requested funding - sort
funding - sort 

**HeOps**
region -dropdown
name-dropdown
role- dropdown

For date let's do the following ranges unless some has better suggestions:
- last week
- last month
- last year

cc @dereklieu @danielfdsilva

**Comment by danielfdsilva** [comment]
Pretty much done
