### ISSUE TITLE
Same figure pops up for Target People as for Affected people on the live GO.

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#584]
## Issue

*Please describe your issue. If possible, include when you first encountered the issue, who it affects, a link to a relevant page, and any other information that might be helpful in diagnosing it's cause.*

## Steps to reproduce

*If you can reliably reproduce the issue, please list the steps taken to do so.*

## Expected behavior

*Please describe how this feature should be working.*

**Comment by szabozoltan69** [comment]
Please give an example.
On https://go.ifrc.org/emergencies/3465 we can see different figures for targeted (0) and affected (11791) people.

**Comment by szabozoltan69** [comment]
Recently it is in assets/scripts/components/homemap.js, (n(d.num_beneficiaries)} People Affected), but Mano refactored this file (for Go Phase III) so he will fix it.

**Comment by mankamolnar** [comment]
@mmusori Hi! we have a bigger ongoing task on the map. As I would like to avoid merge conflicts, I would be happy if I could add this bug to that change. This means that probably it would be deployed to production (live) around March 18-19.  If it is something 'critical' that we should deploy earlier please contact me, I will try to find a solution.

The ongoing development goes on the 'feature/FR15-overview-map' branch.

Thanks & Regards

**Comment by mmusori** [comment]
@mankamolnar , I had a discussion with Zoltan while I was checking a few more entries. The Problem is not the data. The issue is the label on the tooltip of the map. So the tooltip should have the label  'People targeted '.  In Budapest we can discuss the idea of pulling in data from the python scripting script to populate the tooltip with people affected. For now BO does not have that value.  The urgency of task is in that, whenever someone access GO and uses that map tooltip they are receiving erroneous information. As an example, for the measles outbreak in Philippines the tooltip has 290,000 people affected (which is our target) but 2,4 million people are affected.

**Comment by szabozoltan69** [comment]
The Affected->Targeted label change is done in the mentioned tooltips (even on production).
