### ISSUE TITLE
Include country name in the field report alerts

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#590]
Currently, the Go alerts includes the title (or name) of the field report only, without the name of the country where the emergency has taken place.

Usually, the name of the country is mentioned in the title. However, as we can see from the screenshot below, this is not always the case. 

![image](https://user-images.githubusercontent.com/31092591/54816703-3a17ff00-4c95-11e9-9620-6fd3e6fbb5c2.png)

Would it be possible to add the country name in the alert, so that the alert would look like this:

Malawi: 840,000 affected by floods and heavy rains.

**Comment by szabozoltan69** [comment]
Thanks for the feedback, this will be fixed soon.
