### ISSUE TITLE
ERUs on the deployment page not shoulding on the cards on the homepage case in point Mozambique

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#616]
## Issue

It seems not all ERUs are counted in the emergency cards on the GO front page. For example, Mozambique shows 5, bt when you enter the emergency page, 8 are listed in the bottom under ERUs.  But the issue is that the table in the deployments pages only display 5 emergencies. When you expand the table to show all deployments the cards get up dated. 
homepage : https://go.ifrc.org/
Deployment page: https://go.ifrc.org/deployments/erus/all

## Steps to reproduce
Please watch this video to reproduce. 

https://files.slack.com/files-pri/T3NMR1AFJ-FJGE8S8CR/download/go_deployments.mov

*Please describe how this feature should be working.*

The cards show be based on the deployments in the database not on the display in the deployments page.

**Comment by szabozoltan69** [comment]
Good remark, Munu!

> When you expand the table to show all deployments the cards get up dated.
Yes, but after a second refresh – again the old value (5) appears.

(By which account the slack movie can be seen?)

**Comment by szabozoltan69** [comment]
It can be the root:

**Comment by szabozoltan69** [comment]
Fixed in both environments.
