### ISSUE TITLE
Updated Field Report not updating the emergency page. 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#618]
## Issue

 Bosnia and Herzegovina submitted a field report for the floods. The field report was updated it with some more details and figures but the changes do not appear in the emergency page.

## Steps to reproduce

Field Report: https://go.ifrc.org/reports/11795
Emergency page: https://go.ifrc.org/emergencies/3548

## Expected behavior

The number of missing people in the field report should be reflected in the emergency page. The update situation overview in the emergency page should be reflected in the emergency page.

**Comment by szabozoltan69** [comment]
This behaviour is really strange (and can be some frontend issue) because on the backend it is updated, .../admin/api/event/3548/change/ - num_missing = 1.
![missing1](https://user-images.githubusercontent.com/6050643/57786857-8f700a00-7734-11e9-9b54-c1b8e4ddbfbd.png)

**Comment by szabozoltan69** [comment]
The frontend gets emergency's num_missing data (and others) from the latest field report.
In the latest field report num_missing is empty.
Only gov_num_missing is filled out ( = 1).

**Comment by szabozoltan69** [comment]
@mankamolnar Please correct the emergency.js:
Missingg<span className='content-highlight'>{n(get(report, 'num_missing'))}</span>
To add num_missing + gov_num_missing into this field.

**Comment by mankamolnar** [comment]
fixed & deployed
