### ISSUE TITLE
Convert country names in the GDACS feed to match with the IFRC standards

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#619]
The GDACS feed has a slightly different set of countries than the existing GO dataset. For example, we currently have an emergency in Aruba. However, as our existing dataset does not include a country called "Aruba", this emergency appears in the 0.0 point (0°N 0°E) on the map (see the picture below).

In the IFRC standards, Aruba is considered as part of Netherlands. Thus, for any disaster happening in Aruba (or any other Dutch overseas territory), the dot on the map should appear on the Netherlands main territory. The same applies to the overseas territories of UK, France, USA, etc.

In order to fix this problem, we should convert the GDACS country names to match with the IFRC standards, this way:

Aruba -> Netherlands
Curacao -> Netherlands
British Virgin Islands -> United Kingdom of Great Britain and Northern Ireland
New Caledonia -> France

etc. etc.

@szabozoltan69 and @mankamolnar: I propose we start this process by acquiring the GDACS feed dataset and writing the appropriate conversion code. I am happy to help with this process. Do you have any other ideas on how to solve this problem (with the least time consuming manner)?

**Comment by szabozoltan69** [comment]
Hi Elsa, Mark and me has read your request, and we shall write if we have a proposal.
Due to the short deadline until the June Sprint, it is not sure that we can schedule it before this event.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/936 which may need to be cleaned up

**Comment by jhenshall** [comment]
Another example of this is Laos from GDACS not matching to Lao PDR in the GO database - e.g. for this [GDACS event](https://go.ifrc.org/emergencies/4769#details). A consideration for the wider geo-data changes! cc @geohacker
