### ISSUE TITLE
Response documents not uploading to Mozambique Cyclone Idai page

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#623]
Any attempt to upload situation reports on the Mozambique Cyclone Idai page results in Bad Request (400). 

We have not got results of a similar error happening on other emergency pages.

**Comment by szabozoltan69** [comment]
Did it happen on admin page or via the frontend?

**Comment by ElsaRaunioIFRC** [comment]
The problem is happening when uploading the document on the emergency admin page. 

On the other hand, I was able to upload [the document](http://prddsgofilestorage.blob.core.windows.net/api/sitreps/3469/MobTableReports_23.05.2019_Updates_6_v2_1.pdf) through the[ Situation Reports ](https://prddsgocdnapi.azureedge.net/admin/api/situationreport/) page. The problem is that most GO admin users are unaware of this workaround.

**Comment by szabozoltan69** [comment]
The multiple file upload was intended through this workaround (situation reports afterwards from Situation Reports page). But it's true that the classic upload possibility should work via emergency page. I'll check it.

**Comment by szabozoltan69** [comment]
Oh, I see.
There are "too many" documents there, with the eye of the webserver:
**The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.**
So it should be increased somehow.
That is why this error does not appear in other emergencies, because so much documents are not present elsewhere.

**Comment by szabozoltan69** [comment]
Well, recently it's 1000. Do we really want to increase it?

global_settings.py:DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

Or we could say that it's a reasonable limit – in case of Mozambique Cyclone (or other similar crowded cases) only "experts" should increase the quantity of data, who know the sit.rep workaround?

**Comment by szabozoltan69** [comment]
I increased it to 2000, so the upload is successful.
(Afterwards I removed the surplus document.)
![2000](https://user-images.githubusercontent.com/6050643/58467983-f631f200-813c-11e9-8fc0-b104b0ff0b3f.png)

**Comment by ElsaRaunioIFRC** [comment]
Thank you @szabozoltan69 for the effort.
