### ISSUE TITLE
3w: Form to capture project details

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#640]
We need to implement a form on the frontend for users to enter details of Projects, that will be aggregated on the Who-What-Where frontend on the Country page.

The design for the form is here: https://projects.invisionapp.com/share/P9SA110GT4S#/screens/369905382

Backend tickets to implement [models](https://github.com/IFRCGo/go-api/issues/443) and [API](https://github.com/IFRCGo/go-api/issues/444).

This form will post to the API we create on the backend and save `Projects`.

Question on the design: currently, there is a button next to the map on the country page that says `Edit` that takes you to this form. I'm not sure how that's supposed to work, or if that button should say `Add` ? If it is meant to be `Edit`, which Project should they be editing, since there will be many projects? I will clarify this with the design team.

cc @mankamolnar

**Comment by batpad** [comment]
Capturing some changes to the design based on discussion with @guipizzini : 

 - Add a field called `Type of Operation` (radio?) with options `Long-term operation` and `Emergency operation`
 - Move `Programme Type` field to next to or below `Type of Operation` field
 - Based on selection of `Type of Operation` and `Programme Type` fields:
   - if Type of Operation is `Emergency Operation` and `Programme Type` is `Multilateral`, show `Current Operation` dropdown. Else, do not show. @guipizzini to confirm if `Current Operation` is to show or not for `Emergency Operation` that is of Type `Bilateral`.
 - Split `Sector of Activity` into two fields:
   - `Primary Sector of Activity` which will allow a user to select only a single sector.
   - `Secondary Sectors of Activity` which is a multi-select, currently will have same options as `Primary Sector of Activity`, but user can select multiple. Backend ticket for this: https://github.com/IFRCGo/go-api/issues/514

@frozenhelium @guipizzini - please let me know if I missed capturing anything.

**Comment by frozenhelium** [comment]
More changes after discussing with @guipizzini and @LukeCaley

**Comment by batpad** [comment]
@LukeCaley both @frozenhelium and my strong recommendation here would be to go for option 1 for this - when the user updated the `status` to `complete`, show the 2 numeric fields for `People Targeted` and `People reached` and make these fields required if status is complete.

This will guarantee that we can validate the data and make sure that there cannot be Projects where the status is complete and do not have this data filled out. Overall, this seems to me like it's more intuitive for the user, as well as easier to implement.

@LukeCaley please let know if it's fine to go ahead with Approach 1 - i.e. `Make these new field required if the status field in project form is set to completed.` instead of going the notifications route.

Of course, there could be details of the work-flow that we're missing, so if it makes more sense to go with the notifications or another approach, we should discuss that soon.

**Comment by LukeCaley** [comment]
@batpad Thanks for outlining the options and for the suggested appraoch.  Agreed that this should be the logic.  Once we have the prototype we will explore user journeys with the module to understand potential exceptions but the suggestion looks good for now.
