### ISSUE TITLE
search for user in admin token interface

### ISSUE THREAD

**Issue by danbjoseph** [IFRCGo/go-frontend#645]
on
Home › Auth Token › Tokens
there are 16 pages of entries so there is no easy way to find a particular user to retrieve or delete their token 

i think it would be useful if there was a way to search for a particular username

**Comment by szabozoltan69** [comment]
Good idea. Will be fixed soon.
(Otherwise it's a backed issue, not frontend)

**Comment by szabozoltan69** [comment]
@batpad I have a question for this ticket.
I could solve it in the local development environment via fixing 
/usr/local/lib/python*/site-packages/rest_framework/authtoken/admin.py
 simply by inserting a
`search_fields = ('user__username', 'user__email',)` row.
But it is not nice and can not be "conserved" – we would need a solution which overrides the system site-package files. Any ideas?

**Comment by szabozoltan69** [comment]
Solved via:
```
from rest_framework.authtoken.admin import TokenAdmin
from rest_framework.authtoken.models import Token

class GoTokenAdmin(TokenAdmin):
    search_fields = ('user__username', 'user__email',)

admin.site.unregister(Token)
admin.site.register(Token, GoTokenAdmin)

**Comment by szabozoltan69** [comment]
Solved via https://github.com/IFRCGo/go-api/pull/453

**Comment by danbjoseph** [comment]
thank you!
