### ISSUE TITLE
Translations: Implement UI translation framework

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#649]
We want to make the website multilingual / translated into multiple languages: Spanish, French and Arabic.

Broadly, there are two ways to do this:

1. Send the contents of the entire page to an external translation service, and get back and display the whole page translated. This is roughly how a Google Translate widget in the browser works. The pro of this approach is that it is very easy to setup. The cons are that one has no control over the generated translations, and they can often be of poor quality.

2. Manage all translations in the system ourselves. Use well established tools like [`Transifex`](https://www.transifex.com/) to manage translation strings, and integrate translation strings on both the backend and the frontend.

This ticket assumes approach 2 - i.e. using Transifex to manage translation strings and integrating a translation framework into both the frontend and backend. (I will cover integrating automatic translation services to aid in the translations in a separate ticket).

On the frontend, we want all strings that are part of the UI to be translatable into various languages. And a user should have a way to select a language and then get all pages on the website to show in the language of their choice.

We have used different things in the past, and this is mostly a matter of "marking up" all strings that need to be translated in the React code with a custom component / tag, and then some tooling to export Transifex translation files, and import the translated JSONs back into the system.

The favoured tool in the React community to do this now seems to be https://github.com/formatjs/react-intl - it looks good and very similar to the approach we would have taken if writing this.

So, to make the frontend UI strings translatable, we would need to:

 - Use the `FormattedMessage` component from `react-intl` to mark all strings in the frontend as translatable.
 - Use https://www.npmjs.com/package/react-intl-translations-manager to manage the translations, translate them using Transifex

There will be additional work to handle the case of right-to-left languages like Arabic. I will make a separate ticket for this.

**Comment by nanometrenat** [comment]
Closing as now tracked via https://github.com/IFRCGo/go-frontend/issues/934
