### ISSUE TITLE
Translations: Ensure UI supports right-to-left languages

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#653]
Following on from #649 - we want the user to be able to select Arabic as a language option. We need to ensure that this works with the existing layouts. There will also possibly be cases where we don't have all strings translated and will be displaying a mix of Arabic and English on the page.

I'm not sure what the best CSS approach is to ensure that the layout works when displaying `rtl` languages, or if there's specific rules we should be adding. Perhaps this will not really be much of an issue, but opening this ticket to track any best practices or CSS changes we should implement to support `rtl`.

cc @LanesGood in case you have any tips here.

**Comment by LanesGood** [comment]
@batpad I've not used them before but there are some converters that can do some of the conversion work for us. Adjusting text-alignment and the box model directions for layout is the most obvious fix; margins, padding and positioning. Other areas to note directionality are icons, button placement, forms and media objects. If the converters below don't work in this app, another approach would be to enable an "RTL" class when Arabic is selected, with some reversed styling built into each element.

**Converters:**
https://rtlcss.com/index.html
https://cssjanus.github.io/
https://github.com/cssjanus/grunt-cssjanus

Material design's guidance on the subject: https://material.io/design/usability/bidirectionality.html

**Comment by nanometrenat** [comment]
Closing as now tracked via https://github.com/IFRCGo/go-frontend/issues/934
