### ISSUE TITLE
"Storm Surge" disaster type not showing on GO frontpage

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#654]
In the admin page we have chosen "storm surge" as the disaster type but it shows as "other" on the GO front page.

For the following emergency
https://go.ifrc.org/emergencies/3664

**Comment by szabozoltan69** [comment]
It's true, that there can be a gap between admin and frontend.
Admin page has a (48-element) database-sourced list, while the frontend has a (12-element) wired-in list (maybe with the less frequents are in the "other" category).
This is the admin database content:
```
Biological Emergency
Chemical Emergency
Civil Unrest
Cold Wave
Complex Emergency
Cyclone
Drought
Earthquake
Epidemic
Fire
Flood
Food Insecurity
Heat Wave
Insect Infestation
Landslide
Pluvial/Flash Flood
Population Movement
Radiological Emergency
Storm Surge
Transport Accident
Transport Emergency
Tsunami
Volcanic Eruption
Biological Emergency
Chemical Emergency
Civil Unrest
Cold Wave
Complex Emergency
Cyclone
Drought
Earthquake
Epidemic
Fire
Flood
Food Insecurity
Heat Wave
Insect Infestation
Landslide
Other
Pluvial/Flash Flood
Population Movement
Radiological Emergency
Storm Surge
Transport Accident
Transport Emergency
Tsunami
Volcanic Eruption
(and Other)
```

**Comment by batpad** [comment]
Yes, this list seems to be hard-coded on the frontend here: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/field-report-constants.js#L296

What is a bit strange is that `Storm Surge` is in that list, so it should show up.

I think what we should do here:

Short-term: Export the list of disaster types from the back-end with correct ids and names, check if there are discrepancies with the list on the frontend, and update the frontend list.

Longer-term: Make the frontend fetch this list from the API, and not have it hard-coded.

@szabozoltan69 are you able to output all the disaster types from production along-with their ids? I can try replacing the frontend list then.

**Comment by szabozoltan69** [comment]
@batpad Here is the id-s and disaster types (not 48, only 24):
```
1;Epidemic
2;Earthquake
4;Cyclone
5;Population Movement
6;Complex Emergency
7;Civil Unrest
8;Volcanic Eruption
11;Tsunami
12;Flood
13;Other
14;Cold Wave
15;Fire
19;Heat Wave
20;Drought
21;Food Insecurity
23;Storm Surge
24;Landslide
27;Pluvial/Flash Flood
54;Transport Accident
57;Chemical Emergency
62;Insect Infestation
66;Biological Emergency
67;Radiological Emergency
68;Transport Emergency
```

**Comment by szabozoltan69** [comment]
For the longer-term solution: I think we could give a limit (or 0), if no disaster in that category, than frontend should not show it. Maybe this way the "crowded" frontend can be avoided.

**Comment by batpad** [comment]
@szabozoltan69 I don't have access to the production admin, but can you check something:

So, on the list on the front-page in the list it actually shows Appeals and not Emergencies (Appeals are linked to Emergencies). And the Appeal can have a different Disaster Type to the Emergency. Can you check if the Appeal associated with this Emergency has the correct Disaster Type, i.e. Storm Surge?

As a larger issue, I'm not sure if Appeals and associated Emergencies should be allowed to have different disaster types, but we can open a separate ticket for that if that is an issue.

cc @teklal

**Comment by batpad** [comment]
@teklal The reason for `Other` showing up as the Disaster Type in the frontend is that the Appeal "Gambia - Windstorm  Surge" has the Disaster Type set to Other: https://prddsgocdnapi.azureedge.net/admin/api/appeal/3190/change/ - if you change the Disaster Type there to `Storm Surge`, it should show up correctly.

**Comment by teklal** [comment]
@batpad @szabozoltan69  Thanks for exploring and getting to the root of the issue. It shows up correctly now.
