### ISSUE TITLE
Operations with partially entered data not showing on GO

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#664]
Currently, we have two operations where the data has not been correctly entered on GO:

- MDRTJ028
- MDRUG042

![image](https://user-images.githubusercontent.com/31092591/61048725-f4697880-a3e2-11e9-8fb5-35c6228b48cb.png)

As some of the data is missing, it looks like the operations are completely missing from the GO platform. I have already informed the our Finance colleagues on the issue.

Meanwhile, would it be possible to show the operations even when the data is not fully entered? For missing values, we could use figure 0 (or similar).

**Comment by ElsaRaunioIFRC** [comment]
Update: our finance colleague has just fixed the problem by entering the missing info on Apple. However, we may still want to consider if we would like to pull also those operations with missing info on the GO platform.

**Comment by batpad** [comment]
@szabozoltan69 tagging you here, let me know if this is something you want to discuss.

**Comment by ElsaRaunioIFRC** [comment]
@batpad @szabozoltan69 I talked about this issue with our finance colleagues and we all agreed that it is a very, very rare occurrence that any data is missing from Apple. Hence, we can consider ignoring this problem, at least if it turns out to be very difficult to fix.

**Comment by batpad** [comment]
👍 Closing this issue for now. Please feel to re-open if you think it is important to keep it on the roadmap. Thank you!
