### ISSUE TITLE
Show country stats on Emergency page if Emergency stats are disabled

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#718]
For an Emergency like: https://go.ifrc.org/emergencies/3469

The stats on the right are disabled and this shows an empty box.

In these cases, we should fill it with the Country information for that National Society - i.e. data on the right side of the top box here: https://go.ifrc.org/countries/120

cc @mmusori @LukeCaley @guipizzini

**Comment by nanometrenat** [comment]
Superceded by UX/UI changes
