### ISSUE TITLE
First Name does not update when saving Profile

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#728]
Steps to Reproduce:

 - Account - Edit Profile - Edit First Name and Save.

Expected:

 - First Name gets updated

Actual:

 - First name does not get updated

cc @szabozoltan69

**Comment by szabozoltan69** [comment]
Checking...

**Comment by szabozoltan69** [comment]
Oh, I've found the quilty:

-    this.props._updateProfile(id, this.serializeProfile(profileAttributes.slice(**2**, profileAttributes.length)));
+    this.props._updateProfile(id, this.serializeProfile(profileAttributes.slice(1, profileAttributes.length)));

**Comment by szabozoltan69** [comment]
https://github.com/IFRCGo/go-frontend/pull/730 solved it.
