### ISSUE TITLE
UI: Update map design: Layout, popups, etc.

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#763]
Update the design of the maps to closer match the new designs:

 - Move filters to the top right + match design
 - Popup styling to match the new designs
 - Styling of Expand Map / Fullscreen button

Will create separate tickets for:

 - Fixing the map + page styling on the fullscreen view
 - Implementing the new date-range filter

**Comment by batpad** [comment]
On region page map, remove chart in non-fullscreen view, make consistent with home-page, match Invision.

**Comment by guipizzini** [comment]
This seems not available on the staging environment - hence re-opening this one as we cannot proceed with the UAT.

**Comment by batpad** [comment]
@guipizzini the changes to the map on the region page are not implemented, but the changes on the home page should all be there:

 - Moving search drop-downs to top-right of map and styling
 - Moving FullScreen button to top left of map as per design
 - Styling of popups
 - Combining the map and the all operations table below under a single header

**Comment by guipizzini** [comment]
perfect - all those are working, we are pending the map changes at this point. Will keep this one open

**Comment by LukeCaley** [comment]
All good from a coding point of view so can be closed here.  Links however to the MapBox point changes referred to in https://github.com/IFRCGo/go-frontend/issues/806

**Comment by mmusori** [comment]
In presentation mode:
1.  The key figures should have the icons. 
2. More importantly the key figures are too small, the font size should be the same as the one for 'Active Operations'.  
3. The bar with Active Operations and 'view all operations' should be removed. This then allows for more space to have the icons and larger font for key figures. 
![image](https://user-images.githubusercontent.com/7780809/64686337-d1158500-d488-11e9-95f8-18e430a9369b.png)
