### ISSUE TITLE
Implement date-range filter for map + All Operations

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#764]
Implement filters as per new design on the home-page map as well as the All Operations view.

This requires a few things:

 - Layout changes on the home-page to have the table of Operations directly below the map. Then, the filters above the map should apply to both the items on the map as well as the list of Operations below.
 - Add the same filter to the All Operations page
 - Add the functionality to filter by a date-range to the back-end: @szabozoltan69 do you know if this already exists? If not, I can create a separate backend ticket for this.

This is related to #763

**Comment by batpad** [comment]
+ similar implementation on Region pages.

**Comment by batpad** [comment]
The functionality for this is implemented, but it needs some basic improvements to styling. Re-opening.

**Comment by teklal** [comment]
I can't see the date-range filtering functionality on the staging environment currently - neither for the map nor the 'All Operations' page. Has this been implemented?

![image](https://user-images.githubusercontent.com/52411237/64252214-93f64380-cf1a-11e9-8634-f38c2bdfb432.png)


![image](https://user-images.githubusercontent.com/52411237/64252232-9fe20580-cf1a-11e9-99d6-81452cc1ccc6.png)

**Comment by batpad** [comment]
You click on the little arrow next to Start Date, and you should see the filter (similar to the other table filters). Let me know if this works.

**Comment by guipizzini** [comment]
The filter works on the table - but not on the map, is that normal and expected attitude?

**Comment by batpad** [comment]
That is expected, yes.

We will need a larger refactor / redesign of the filters if we want to think of them as combined with the map.

Alternatively, we can add a separate date range filter to the map, and have that operate separately from the existing filters on the tables. Happy to discuss!

**Comment by batpad** [comment]
Can we treat this issue very specifically for the implementation of the Date Range filter on the Operations table? And consider the merging of the table / map into common filters as a separate issue (which I can create separately).

**Comment by batpad** [comment]
Am closing this issue, since the date filter is working. @teklal @guipizzini could you test, and then we can put our heads together and open a separate issue for the larger idea of "merging" these two filters into a common filter-set for the map and the table.

**Comment by batpad** [comment]
Changed the title of this issue to reflect the fact that what is Done is only the date range filter for the All Operations table.

**Comment by teklal** [comment]
This has been tested and it works. @batpad  have you created a separate ticket for the date-range filter fr the map yet?
