### ISSUE TITLE
Fix styling of elements in full-screen view

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#765]
This may need a little more clarity on exactly what all we want to see in the full-screen views (cc @LukeCaley ) - but also right now, things look a little broken in the full-screen.

To start, make the full-screen match the design in invision and neaten it up: https://projects.invisionapp.com/share/P9SA110GT4S#/screens/359410012

**Comment by LukeCaley** [comment]
Two quick points of feedback

- please check that the presentation mode works on the standard browsers.  Currently the GO homepages and presentation mode renders awkwardly on safari for example (the targeted population furthest to the right drops onto the next line)
- change text from "expand the map" to "presentation mode" or revert to the old icon for this

**Comment by necoline** [comment]
I just tested out the full screen on safari. This is what it looks like on local:
![image](https://user-images.githubusercontent.com/20410256/64351123-c742dc00-cfc7-11e9-984b-6647a690ba97.png)

**Comment by batpad** [comment]
@necoline the only remaining item here is `change text from "expand the map" to "presentation mode" or revert to the old icon for this` - let's just change the text that says "Expand the Map" to "Presentation Mode" and this should be good to close.
