### ISSUE TITLE
Map export browser compatibility

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#767]
The current Map Export functionality works only in Google Chrome.

This seems to be because the `html2canvas` library no longer supports newer versions of Firefox.

This maybe a rabbit hole to fix, but at the very least we should:

 - Make sure our version of html2canvas and other libraries is up-to-date.
 - Create a minimal example that highlights the issue and create an issue on the `html2canvas` issue tracker
 - Investigate other libraries that maybe work that would allow us to stick to the current client-side approach to generating the images.

If we fail at getting the client-side approach to work, we will need to ticket out an alternative approach which maybe a lot more complex. Then, the interim fix maybe to either hide the button for non-Chrome users or display a message informing them of the browser requirement for the Export Map feature.

**Comment by mmusori** [comment]
![image](https://user-images.githubusercontent.com/7780809/64252674-dff5b800-cf1b-11e9-80b7-cd10a9cf7cf0.png)
From Firefox
