### ISSUE TITLE
Change text on Emergency Page Map Export

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#768]
@LukeCaley do we still need to update the text with credits under the map. If yes, can you tell me exactly what it needs to be updated to and then this is a quick fix.

**Comment by LukeCaley** [comment]
For the Field Report / Emergency map export, e.g. [https://go.ifrc.org/emergencies/3732#details](url)
Leave the first disclaimer sentence.  
Change the Map data sources to:

> Data sources: IFRC, OSM contributors, MapBox.

Remove Map design sentence completely.

**Comment by mmusori** [comment]
![image](https://user-images.githubusercontent.com/7780809/64252302-d1f36780-cf1a-11e9-8b59-e1d81234f6b8.png)

The requested changes have been implemented. there is one disclaimer sentence and the sources are as stated above.
