### ISSUE TITLE
Update headers and titles as per wireframes

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#769]
Check all headers / titles and match them to wireframes.

**Comment by batpad** [comment]
@teklal as per conversation, it would be great to get your help here to catch all the specific places where the headers and titles need to be changed and make this issue more specific. Thank you!

**Comment by teklal** [comment]
@mmusori  can you take a look at this

**Comment by LukeCaley** [comment]
@yellowumbrella-design to identify specific changes to be implemented based on wireframe / PROD audit.  Text file broken down by page / component preferred by @batpad

**Comment by batpad** [comment]
This ticket is stale, and I think the important changes to section titles, etc. should be covered in https://github.com/IFRCGo/go-frontend/issues/1012 - closing here, but @LukeCaley, feel free to re-open.
