### ISSUE TITLE
GO browser compatibility

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#772]
At the moment GO does not render at all on Internet Explorer. This needs to be fixed urgently.

We need to make sure that GO functionalities work across different browsers.

Related to issue #767 

@batpad @szabozoltan69

**Comment by szabozoltan69** [comment]
I have no possibility to check the issue recently.
Otherwise even Microsoft suggests Edge instead of Internet Explorer, and Edge works fine.

**Comment by batpad** [comment]
@teklal can you please specify what version of Internet Explorer this is?

**Comment by teklal** [comment]
Internet Explorer 11, Version: 11.239.18362.0

**Comment by LukeCaley** [comment]
In addition to the above noted IE browser issue, we are having issues displaying GO using a Samsung Smart TV Web Browser - 2014 - Version 2.0.4.0220194 (TizenBrowser).  

As we are using Samsung TVs to display ifrc.go.org in the Emergency Operations Centre, this is a must-fix.  @szabozoltan69

**Comment by batpad** [comment]
@LukeCaley fixing this could be really hard - the online browser emulation tools do not support this particular browser, and debugging would be really hard.

I would strongly recommend not using the in-built TV browser to present, in general. Either a ChromeCast or a FireStick should allow you to then cast from your regular browser either from a phone or laptop through the WiFi. Could this be a workable solution?

**Comment by nanometrenat** [comment]
Closing - spoke with Sune just now, and we are not doing any further work on GO side to make it compatible for the Samsung TVs at this stage.
