### ISSUE TITLE
Response Documents organisation through cards

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#773]
In major operations there are often dozens of Response Documents and it can be tricky to find the one you are looking for.  Having 'empty' cards for expected documents might also suggest to users to upload these 'missing' documents.

This was quite a big issue in the Mozambique operation for example: https://go.ifrc.org/emergencies/3469#details (need to scroll down to the bottom of the page).

There are wireframes here: https://projects.invisionapp.com/share/K8R901UBXN4#/screens/361592718 which also suggest a date range filter and search function, both of which would be nice-to-haves but are not absolutely essential at this stage.  It would however be good to be able to directly upload a missing doc type, redirecting the user to the relevant place in the back-end., through a simple upload button on the card itself.

Related to #396 and #413

**Comment by batpad** [comment]
For Response Documents, use Situation Report Types defined in the backend to show the 6 groupings of report types.

**Comment by LukeCaley** [comment]
@batpad as discussed, more info on the Response document types, and text for callouts, for the front end:

1. Situation reports - "IFRC, National Society, and other Emergency Response Unit and technical sitreps"
2. Maps / infographics - "Static maps and graphics created by IFRC and Movement partners"
3. Needs assessment reports - "IFRC, National Society and Movement Partners"
4. Surge documents - "Staff health, security, ToRs, and other surge related docs")
5. Mob table and logistics - "Mob tables, shipping details and other logistics docs"
6. Secondary data links - "Key information sources for situational awareness" (this should be a "link only" card - with no document upload)

@batpad If at all possible, would we be able to implement a 'pin' doc function so that we could identify the key documents within each type and ensure that they are seen first?

**Comment by LukeCaley** [comment]
One to one mapping of revised Response Documents categorisation:

1. Situation reports - contains 'Situation Reports' and 'ERU reports'
2. Maps / infographics - 'Maps'
3. Needs assessment reports - 'Information products' 
4. Surge documents - 'Key Surge Documents'
5. Mob table and logistics - 'Mobilisation Tables'
6. Secondary data links - no current document type in the d/b

Note to self @guipizzini @mmusori @tekla to review the implications on previously categorised 'Information products' which are not necessarily 'Needs assessment reports'.

**Comment by LukeCaley** [comment]
In terms of ordering:

One to one mapping of revised Response Documents categorisation:

First row:
1. Situation reports 
2. Surge documents 
3. Mob table and logistics
Second row
4. Maps / infographics 
5. Needs assessment reports
6. Secondary data links

**Comment by batpad** [comment]
Ideally, we would create some way to re-order the categories in the backend.

For now, we may need a mapping in the frontend to create the ordering.

@necoline - assigning you on this - we will probably need to check the ids of the Response Document categories, and then create a mapping to the correct ordering. Happy to chat about this when you come online.

**Comment by batpad** [comment]
@necoline my understanding of the new order for the current names:

First row:
1. Situation Reports
2. Key Surge documents
3. Mobilisation Tables

Second row:

1. Maps
2. ERU Reports
3. Information Products

**Comment by necoline** [comment]
@batpad I couldn't get any data coming through on the reports on the response docs. I don't know if I am missing something on my end. I will need to sync with you before I can pick this up again since I can't make much progress unless I can access the response documents.

**Comment by batpad** [comment]
Additionally, we need to make sure the documents within each card are ordered descending by date uploaded.

**Comment by batpad** [comment]
@necoline I can check on the date ordering, since that might involve the backend.

**Comment by batpad** [comment]
These should now be organized as per the ordering above. Ready for testing, closing.

**Comment by guipizzini** [comment]
I've added them into the back end on the staging. @LukeCaley for your validation of course.

The functionality and cards creation works and is UAT approved.

<img width="494" alt="Screenshot 2019-09-11 at 09 31 24" src="https://user-images.githubusercontent.com/23258092/64676999-0913cc80-d477-11e9-91d1-b353ef4545c8.png">

**Comment by guipizzini** [comment]
@batpad 

ERU reports ---> Surge Documents

**Comment by LukeCaley** [comment]
@guipizzini agreed.
@batpad slight amendments to info box explanations of the document categories. Those categories with a * are slightly amended as discussed.

*Situation reports - "IFRC and National Society sitreps"
Maps / infographics - "Static maps and graphics created by IFRC and Movement partners"
Needs assessment reports - "IFRC, National Society and Movement Partners"
*Surge documents - "Staff health, security, ToRs, ERU sitreps and other surge related docs")
Mob table and logistics - "Mob tables, shipping details and other logistics docs"
*External docs and links - "Key secondary info for situational awareness"
