### ISSUE TITLE
Country pages - add links

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#776]
At the foot of the redesigned wireframes for country pages there are relevant links with 'mini-cards', specifically:

- country page on IFRC.org
- country page on ReliefWeb
- country page on IFRC evaluations database - omit
- home page for National Society (input url on admin back-end)

At this point, we should excerpt the DEEP Philippines page link.  This will come in 2020 as we build the DEEP-GO connector.

https://projects.invisionapp.com/share/K8R901UBXN4#/screens/356658484

**Comment by batpad** [comment]
@LukeCaley it it possible to give me example country page links for each of the 4 sources you mention above? So that I can understand how to construct these links from each country page on GO.

Let me know if this needs any clarification.

**Comment by LukeCaley** [comment]
Links for an example country (afghanistan):

country page on IFRC.org: https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/afghanistan/
country page on ReliefWeb: https://reliefweb.int/country/afg
home page for country on GO: https://go.ifrc.org/countries/14#operations

Seems there is no country page on IFRC evaluations database and the link is not currently working so let's not add this link at this point.   We are scoping the DEEP country page in phase 4 but is also not worth pointing users to at this point.

**Comment by LukeCaley** [comment]
Note also there are links on the footer of all pages, on the same red banner as the links to source code etc, which are:

RCRC SIMS: http://rcrcsims.org/
IFRC data blog: http://data.ifrc.org/

**Comment by batpad** [comment]
Just a note - the links on ReliefWeb use three digit country codes. In the IFRC database, we have only 2 digit ISO codes.

For now, I will create a mapping from 2-digit to 3-digit codes just on the frontend using this CSV file: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv .

When we are re-looking at the spatial tables and updates, we should consider storing the 3 digit codes directly in the database.

**Comment by batpad** [comment]
> Note also there are links on the footer of all pages, on the same red banner as the links to source code etc, which are:

@LukeCaley can you explain what the actionable task is here? Do we need to add links to RCRC Sims and IFRC Data Blog to the site-wide footer? If yes, could I ask you to create a separate ticket? This should be doable in this phase, would just be nice to have a separate issue since it's quite a distinct task from adding the links on the counry pages.

**Comment by guipizzini** [comment]
@LukeCaley same comment and feedback as for this issue:

https://github.com/IFRCGo/go-frontend/issues/795
