### ISSUE TITLE
Tweaks to notification emails

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#783]
There are still some tweaks to be made to the email notifications to make them more in line with the notification wireframes.

- Include the name of disaster in email subject for new field report / new event / new operation,

ie. ‘(IFRCGO) 1 new field report: Belarus Floods’
‘(IFRCGO) 1 new Operation: Belarus Floods’
etc.

- For new event, new operation, new field report: Move the text ‘_You are receiving this update based on your selected preferences. Update your preferences_’ further down below the title and description.

The wireframes on Zeplin: [https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/dashboard](url)

@batpad @szabozoltan69

**Comment by szabozoltan69** [comment]
The change request makes sense, the description is more important than the "Update your preferences" text.

Please specify, @teklal , which wireframe do you think.
The recent notification layout follows this one:
https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5d29cd1c61a34a722d15663c

One more (unimportant) note: the notification system is managed via the backend, so the (next notfiication) issue should be in https://github.com/IFRCGo/go-api/issues

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/507
(The subject has this meaningful extension only in case when there is only 1 entity)
