### ISSUE TITLE
GO 3.2 - Emergency page redesign

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#796]
Issue relates to implementing a redesign for the regional page following approved wireframes here: https://projects.invisionapp.com/share/K8R901UBXN4#/screens/361592718

- Headline boxes - implement the same style and icons as the home page, People targeted, Funding requested and Funding coverage.  Deployed personnel can be dropped for this release, to be revisited if more structured data in release 4.1.
- Tabs - retain as Emergency Details and Additional Information for this release.  As discussed, move the majority of clean, structured data on to emergency details and the iframes/graphic dashboards on to additional information

Emergency Details
- Key figures - Implement Field Report automatic population here.  There should be an option to hide or 'override' the field report data and manually update here, and/or add new fields that were not captured in the field report.  This is a bigger piece to scope for release 4.1.  For now, ensure that the field report data appears and that we can then hide this is sufficient.
- Movement activities - to be implemented with the 3w feature in release 4.1.  Hide for now.
- Situational overview - include "last update:" as an automated date field.  Make the text appearance three lines before requiring a user to toggle the 'expand' button.
- Surge alerts for this emergency - for release 3.2, we can implement the alerts table as it is on current GO.  Surge data and viz to be scoped further for release 4.1
- IFRC surge deployments - for release 3.2, we do not need to implement this visualisation. Surge data and viz to be scoped further for release 4.1
- **Add back in** ERU table - this was moved to Additional Information and should be the auto population of ERU data that was previously functioning pre GO3.1
- Response documents - refer to https://github.com/IFRCGo/go-frontend/issues/773
- **Add back in** Appeal Documents - this was moved to Additional Information and should be the auto population of DREF and Appeal documents that was previously functioning pre GO3.1
- Contacts - improved styling if time for release 3.2

Additional information
- Graphic title 1 - change to a field defined by user in the back-end.  Hide the graphics when there is no data available.

**Comment by LukeCaley** [comment]
As a standard approach we aim to hide tables or data fields when there is no data to display.  So, for example, if there were no ERUs for a particular emergency, the default would be that the table become invisible.  In addition, if the Emergency page was not linked to an IFRC operation (DREF or appeal) then the auto populated headline figures should disappear.  This would avoid Targeted Population being 0 for instance, which obviously looks odd.

**Comment by batpad** [comment]
Add Key Figures coming in from the Field Report, to replace current Key Figures.

If there is no Field Report key figures, display current Key Figures.

**Comment by batpad** [comment]
Am marking this issue as closed.

We have covered the re-organizing of the data in the two tabs, styling the headline boxes and the contacts. Also, we now hide all data boxes where there is no data available.

We will need to create separate issues for handling the Field Report vs. Key Figures issue, as well as other issues marked for 4.1

But it would be great to be able to test the current changes of re-ordering, hiding boxes, etc. and get feedback on those.
