### ISSUE TITLE
Allow users to either add links or upload documents in Response Document upload

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#799]
- Add help text to suggest a file naming convention for documents -- @LukeCaley can you add details on what we should ask users to follow w/ regard to file-naming?

**Comment by LukeCaley** [comment]
To be defined before implementation.  First proposal is the following:

date_datacategory_source_permission_freetext
e.g. 2019-09-06_Sit_IFRC_pub_Dorian Sitrep 1

The purpose of each clause is as follows:
date - autogenerated and useful for sorting
datacategory - this would be a three character code for the 6 response doc categories
source - describes the original source of the dataset. It can use as many letters as necessary in the clause.
permission - this describes both the permissions for redistributing data. It uses a three letter description in the clause.
freetext - this provides free text to describe in greater detail, if needed, what the data is. It can use as many letters as necessary in the clause.

**Comment by LukeCaley** [comment]
Current naming of this ticket appears to be incorrect "Allow users to either add links or upload documents in Response Document upload".  The content of this ticket refers to a suggested file naming convention 'hint' which does not currently appear to be on staging.  @batpad please confirm the feature to be tested for this ticket and, if this is separate to the suggested file naming feature, to set up a separate ticket for that (not necessarily prioritised for R4.1).

**Comment by batpad** [comment]
@LukeCaley my apologies here - I was under the misunderstanding that this was covered in recent work done by @GregoryHorvath, but I see that is not the case. I'm moving this ticket to the backlog, let's revisit and scope things out in greater detail for future work.
