### ISSUE TITLE
Homestat list over-flow in Safari

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#803]
## The stats on the home page run onto a second line when viewed in Safari

Styling of the homestats components needs to be adjusted to be consistent across browsers including Safari.

## Steps to reproduce

This issue can be seen when the home page is viewed in Safari

## Expected behavior

All of the stats should span the length of one line

**Comment by batpad** [comment]
Fixed in #804 . This also addresses the Safari issue mentioned in #765 .
