### ISSUE TITLE
MapBox styling: redesign points and layerfiles 

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#806]
Task: create MapBox style point icons which reflect different data for DREF, Appeal, Movement Response and multiple types to be used on GO home page.  Preference would be to avoid different colours.

Optimal might be some kind of concentric circles (using the GO style guide) which indicate the use of different funding mechanisms, usually at different stages / levels of an emergency, i.e. first DREF, then Appeal/multiple types, then Movement response at the highest level.

**Comment by jhenshall** [comment]
Think this is covered by #1202 so closing this issue. @LukeCaley do you think it's all covered on other ticket? If not, can reopen or capture there.
