### ISSUE TITLE
Disable fullscreen and map filtering functionalities for Deployments page

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#823]
The fullscreen mode on the current 'Deployments' page on GO doesn't work well at the moment so it would be better to disable this functionality for now. Below a screenshot of what the fullscreen view looks like at the moment.

![image](https://user-images.githubusercontent.com/52411237/64862335-833c8080-d632-11e9-816e-aafceb21c854.png)

The filtering functionality doesn't fully work either, so this should be disabled as well.
There are currently FACT and RDRT deployments and ERUs in The Bahamas, but the map doesn't show the ERUs when that filter is chosen.

![image](https://user-images.githubusercontent.com/52411237/64863135-74ef6400-d634-11e9-9aa0-b789ab4067ac.png)

![image](https://user-images.githubusercontent.com/52411237/64863154-7fa9f900-d634-11e9-8521-952fd37d0a5b.png)

![image](https://user-images.githubusercontent.com/52411237/64863186-905a6f00-d634-11e9-9e59-4fdda4368714.png)

@szabozoltan69

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-frontend/pull/824

**Comment by szabozoltan69** [comment]
The functionalities should be fixed, so I reopen this ticket.

**Comment by teklal** [comment]
Closing as Deployments/Surge is going to undergo database changes in the coming months.
