### ISSUE TITLE
Enable date filter on map (home + region pages)

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#828]
In addition to the `All Appeal Types` and `All Emergency Types` filters above the map, it should include a date filter, similar to the date filter on the table below.

There are two options here for the implementation:

 - Simpler: Add a start date and end date filter to the map filters, similar as the table. They operate only on the map (independently from the table filters) and filter the data on the map to only the data within the filtered date range. This will take a bit of looking into the data structure for the data on the map, and applying this filter to the GeoJSON.

 - Complex: Refactor the filters completely, and make the filters for the data on the map and in the table a common set of filters. In addition to being a considerable UI lift, this does introduce a lot of complexity since the data on the map and the data in the table are not the exact same data, and filtering through each with a common set of parameters could introduce weird edge-cases.

I'd vote for just adding a date filter to the map filters, but it would be good to make sure we're all on the same page with this implementation.

cc @LukeCaley @guipizzini @necoline

**Comment by necoline** [comment]
Maybe we could start by throwing all of the filters into a common utility. If there is any overlap in logic, we can apply that to the maps and tables in the different views, otherwise we can breakout methods to deal with the unique data sets where needed. Would that be inline with what you are thinking @batpad ?

**Comment by batpad** [comment]
>  Would that be inline with what you are thinking @batpad ?

@necoline I'm a bit worried about throwing all the filters into a common utility - it seems like the filtering is just so different between the table and the map, that it maybe more trouble than it's worth to have a common interface. I also think the design and interaction is not so obvious / clear if we want to "merge" the filters to have a common filter interface for the map and the table.

I would definitely vote for, to start with, just implementing the date filter on the map as a separate thing, separate from the filters on the table below. I think the work to re-imagine the filters to be common between the table and the map is probably a bigger piece, and if we have these filters implemented separately, it maybe easier to think about what parts are common and can be abstracted,  and also think about the user experience more carefully if we take the filters out of the table headings and need to represent them along-with the map filters.

Does that make sense?

**Comment by necoline** [comment]
Per our conversation earlier, I reviewed the table and map more closely to see where the data is coming from. 

The data being used to populate the table and the map are the same however, the logic to manipulate the table and the map are very different. Some of this is necessary, other bits can be parsed out and used across both map and table if we want to. 

I think it might be worthwhile to split this all out so we can reuse some of the logic that is duplicated across tables and maps. Maybe we could talk about the merit of this endeavor as part of our refactoring/cleanup that we have scheduled.

For now, I think we can start by breaking out the date filter component `display-table` to reuse in the map. 
I made a WIP PR to show you what I mean.

**Comment by batpad** [comment]
@necoline this looks *really good* to me.

> I made a WIP PR to show you what I mean.

Conceptually, this seems really good. This does seem like we now have a rough framework that we can use toward combining the filters on the map and the table. I think this does open up a lot of UI questions for how we see these filters being used long-term, and what the UI would look like if we were to have a common set of filters for the map and the table on the home and region pages.

@LukeCaley we had so far punted a bit on the question of combining the filters for the map and table - both because we did not have a clear UX design for this, as well as because the technical implementation was a bit involved. With @necoline looking at the data more in detail and the implementation of a re-usable common date filter, it seems like from an implementation point of view, we are one step closer to implementing the filters as a common set. It maybe worthwhile to talk about this at some point and understand how you would ideally like to see these filters implemented across the map and the table. 

This will probably help inform how we implement the date filter on the map in the shorter term, and how we think about the filters in the longer term. Then, we can also create a broader ticket for combining the filters across the map and the table and discuss exactly how that could work across the different pages and contexts.

**Comment by batpad** [comment]
@teklal can I ask you to test this on staging? The filter above the map on the home and region pages should now have a date filter, allowing you to filter the data on the map by date.

**Comment by teklal** [comment]
Thanks @batpad.
A few observations:
- the date filter works on the maps on the home and region pages but does not work in the presentation mode
![image](https://user-images.githubusercontent.com/52411237/67379937-e7cff100-f589-11e9-87bf-ed563c8f5c47.png)
- is the map supposed to allow multiple filters to be applied at the same time? if yes, this functionality does not work, as other filters are reset when another one is applied

**Comment by batpad** [comment]
> the date filter works on the maps on the home and region pages but does not work in the presentation mode

Thank you for the catch, @teklal . I am able to reproduce this. Click on Presentation Mode -> Click on the Date Filter -> It does not drop down the date filters as expected. @necoline will you be able to take a look at this?

> is the map supposed to allow multiple filters to be applied at the same time? if yes, this functionality does not work, as other filters are reset when another one is applied

The behavior of the two drop-downs was always such that only one could be applied at a time, and we continued to follow that. If we want to change that to make the filters cumulative, let's try and outline this in a separate ticket? I do agree it is probably nice to be able to combine filters, but let's outline that as a separate ticket.

**Comment by necoline** [comment]
Thanks for catching this @teklal ! I will get a fix in for this straight away

**Comment by necoline** [comment]
I apologize for not testing this use case on the first submission of this fix.
I did have some time to look into this behavior. 

Unlike the native map dropdown selects, the date filter dropdown contains multiple functionalities (adding 2 separate dates and submitting them as a map filter). In order to perform this, we are accessing an external component (as opposed to a native select component)

The trick here is that fullscreen mode is designed with a display in mind rather than a view with various interactions. This means that features that dynamically add external components and update features can get messy pretty quickly. 

It is possible to make this work, but some of the existing code around our date filter as well as our fullscreen are quite brittle making the implementation of this date filter a nontrivial task. 

I propose 2 solutions:
**Option 1** : Remove the map filters from the fullscreen mode
Any filter applied to the map prior to entering fullscreen mode persists in fullscreen mode, including dates. This means would mean that
- users may still access filtered maps in fullscreen mode granted they set the filters prior to changing modes
- Fullscreen mode would function purely as a display screen which is a general expectation for fullscreen mode
- The fullscreen mode would present a visually cleaner display which could be a win for presentation aesthetics

**Option 2** Changing out the dropdown date filter to access native date selects
I could create a date filter that would work within the current rules of the map filter. This would require 2 date drop downs, one to set the start date, one to set the end date
Drawbacks to this would be:
- Extra visual clutter in fullscreen mode
- Variation in date filters in standard and fullscreen mode (unless we want to apply these changes to the standard map)

I would recommend that we go with option 1 with the rationale that it will be time effective and will not significantly impact user behavior. 

@teklal I welcome your thoughts and input on next steps for this bug

**Comment by batpad** [comment]
@necoline speaking to @LukeCaley and folks, we don't really need the filters to show up in Presentation Mode. Hiding them all will probably improve overall consistency and reduce clutter in Presentation Mode.

**Comment by necoline** [comment]
Great, that will be a quick fix

**Comment by LukeCaley** [comment]
Presentation mode on region page leaves an unnecessary amount of white space as well as does not include the key figure cards.  

The sizing and placement of the title text "IFRC Disaster Response and Preparedness" also appears different on the region page implementation - please replicate the parameters on the home page presentation mode. @necoline

**Comment by necoline** [comment]
Thank for pointing that out @LukeCaley I'll add the key figure cards and fix the title alignment

**Comment by LukeCaley** [comment]
Is this ready for testing? @necoline

**Comment by necoline** [comment]
Yes it is!

**Comment by teklal** [comment]
Thanks for the work and improvements on this!
There are few things that still need attention. We can have a call to discuss these as I'm not sure my written explanations are comprehensive or capture everything.

- when the date filter is applied it would be good to have it show somewhere that that filter has been applied, e.g. by showing the dates on the box similarly as when one of the two other filters is applied, as shown below:

![image](https://user-images.githubusercontent.com/52411237/70237888-64004b80-1768-11ea-97f3-8d084daf9c99.png)

![image](https://user-images.githubusercontent.com/52411237/70237941-809c8380-1768-11ea-8053-dc3c1d3f17c4.png)

- after closing the presentation mode when an 'emergency type' or 'appeal type' filter has been applied, the filter box resets i.e. does not show anymore that a filter has been applied, although the filter in fact is still applied and the map shows filtered information

- when clicking on the 'emergency type' filter, it shows numbers on the drop down list (as in image below) according to how many active operations there are for each emergency type. It would be great if these numbers changed based on the date filter applied reflecting the number of operations of each type during that time frame

![image](https://user-images.githubusercontent.com/52411237/70240040-c6f3e180-176c-11ea-888b-b009a9a1c38d.png)

Let me know if something is unclear and I can elaborate on a call.

**Comment by batpad** [comment]
> when the date filter is applied it would be good to have it show somewhere that that filter has been applied, e.g. by showing the dates on the box similarly as when one of the two other filters is applied, as shown below:

This is now done and on staging. Please test.

> after closing the presentation mode when an 'emergency type' or 'appeal type' filter has been applied, the filter box resets i.e. does not show anymore that a filter has been applied, although the filter in fact is still applied and the map shows filtered information

This is an excellent catch, thank you. We will work on fixing this.

> when clicking on the 'emergency type' filter, it shows numbers on the drop down list (as in image below) according to how many active operations there are for each emergency type. It would be great if these numbers changed based on the date filter applied reflecting the number of operations of each type during that time frame

I think this is a good idea and would be good to do, unfortunately would be out of scope for this release, so can we ticket this separately?

**Comment by teklal** [comment]
I created new separate tickets for the two remaining issues so that we can move this ticket to Done and have what has been fixed so far pushed into production.
