### ISSUE TITLE
Field Report Early Warning option

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#833]
On the Field Report form, allow user to choose `Early Warning` as the field report type.

In this case, various field options and help texts need to change to be consistent with the Early Warning type. These are outlined in the Invision design.

So, we need to add the Early Warning option, and then go through the Invision doc, identify all the things that need to change based on the Field Report type selected by the user, and then implement these changes.

**Comment by batpad** [comment]
@mmusori

**Comment by batpad** [comment]
This is on hold until we get clarification on all changes and final functionality specs from @mmusori .

**Comment by batpad** [comment]
Thank you @mmusori for the detailed email with changes from the wireframes. Pasting your email below (with a little added formatting):

### Context page

 - Status: should read “Early warning message for the risk of an upcoming disaster”
 - Start date: would propose it be worded more clearly as “Predicted Date of Impact”


### Situation page

 - For the sources, change to “Red Cross/Red Crescent”
 - Situational Overview: change to “Risk Analysis” and for the explanation to be changed to “Brief overview of the potential disaster and projected impacts”
 - Optional box where to place a weblink to the source is referred to, in order to be able to verify the figures given (and avoid a random figure is provided).


### Early action page

 - For “Assisted by Government and RCRC Movement”, add  “Number of people …” at the beginning to read “Number of people assisted by Government” and “Number of people assisted by RCRC Movement”
 - For early actions taken by NS, would suggest to:
    - Add “Activation/mobilization of volunteers”
    - Add “Public awareness raising and sensitization”
    - Add “WASH”
    - Add “Food security and livelihoods”
    - Remove “Community engagement activities” – broad, unclear
    - Remove “Community early warning” – 
    
 - For early actions taken by IFRC, would suggest:
    - Add,  “Support NS submission to FbA by the DREF or Imminent DREF” 
    - For early actions taken by RCRC Movement, see comments for NS. Change this to Early Action taken by other RCRC Movement
    - Add “Activation/mobilization of volunteers”
    - Add “Public awareness raising and sensitization”
    - Add “WASH”
    - Add “Food security and livelihoods”
    - Remove “Community engagement activities” – broad, unclear
    - Remove “Community early warning” – 

 - For Early Action taken by others, also ask to specify who the others are.

 
### Response page

 - Change “Trigger-based Early Action” to “FbA by the DREF” .
 - Add another option called “Forecast-based Action
 - Change “DREF Requested” to “DREF”
 - National Society contact: Change the description to “The most senior staff in the NS responsible and knowledgeable about the risk”
 - IFRC Focal Point: Change the description to “IFRC staff who is overall responsible for supporting the NS in its response to the anticipated disaster event” 

cc @necoline 

We will get back to you with questions soon, and we will also spend some time scoping these out in detail, identifying which of these changes require corresponding back-end changes, etc.

**Comment by batpad** [comment]
@mmusori I've consolidated all the changes on the field report for the Early Warning option, based on the Invision designs, with the modifications as per your note above. This should cover every change, and every field on the form. I have highlighted places where I had questions. I think the only thing that needs slightly urgent discussion is allowing users the ability to add text for `Other` sources.

Please do let me know if anything here seems wrong, or missing:

### Step 1 - Context:

 - Status: change Early Warning help text to: `“Early warning message for the risk of an upcoming disaster`
 - Title: No Change
 - Start Date: For Early Warning, change Label to `Predicted Date of Impact`. help text for Early Warning to change to `Date at which significant impacts are predicted to occur`
 - Affected Country and Province / Region: For Early Warning, change Label to `Potentially Affected Country and Province / Region`. Change Help Text to `Anticipated Affected Country and Province / Region`
 - Disaster Type: For Early Warning, Label to be `Hazard Type`
 - Government Requests for International Assistance: No Change.

 ### Step 2 - Situation:

 - Change Source text from `Red Cross` to `Red Cross / Red Crescent`. **Question**: Is this to be done for both Early Warning and Regular Field Reports?
 - Fields for Early Warning are different (will need new fields in the database):
   - Potentially Affected (Number)
   - People at Highest Risk (Number)
   - Largest Population Centers Likely to be Affected (String?)
 - Situational Overview: for Early Warning, change text to `Risk Analysis`, and help text to `Brief overview of the potential disaster and projected impacts`
 - Add ability to add arbitrary text to identify an `Other` source. This would be a new feature and require fairly significant backend changes. **Question**: Would this apply to Event and Early Warning? __Needs Discussion__

 ### Step 3 - Actions:

  - `Action` should be renamed to `Early Action` in the top bar with steps for Early Warning.
  - Top Section: Early Warning has only 2 fields instead of 5 and change labels (**Question**: Should these be separate fields in the db for early action or re-use existing fields?):
    - Number of People Assisted by Government - Early Action
    - Number of People Assisted by RCRC Movement - Early Action

  - Actions Taken by Society section:
    - Change title of Section to `Early Actions Taken by NS`
    - Change help text of Section to `Select the early action activities undertaken by the National Society and give a brief description`
    - Change Checkboxes to be:
      - Activation / mobilization of volunteers
      - Cash & Voucher
      - Evacuation
      - Food Security & Livelihoods
      - Health
      - NFI Distribution
      - Pre-positioning of Stocks
      - Psychosocial Support
      - Public Awareness Raising & Sensitization
      - Rapid Training (including on First Aid)
      - Shelter
      - WASH
      - Other
    - Change `Description` Box to be smaller and placeholder text to `Brief description of the action`

  - Known Actions Taken by IFRC section:
    - Change title of Section to `Early Actions Taken by IFRC`
    - Change help text of section to `Select the early action activities undertaken by the IFRC and give a brief description`
    - Change checkboxes to be:
      - Interagency coordination
      - Monitor situation
      - Movement coordination
      - Review Early Action Protocols
      - Support NS advanced preparedness actions
      - Support NS submission to FbA by the DREF or Imminent DREF (label too long?)
      - Support NS to activate contingency plan
    - Description box stays the same.

 - Known Actions Taken by RCRC Movement Actors:
   - Change title of Section to `Early Action Taken by other RCRC Movement`
   - Change help text of section to `Select the early action activities undertaken by the RCRC Movement and give a brief description.`
   - Change checkboxes to be:
      - Activation / mobilization of volunteers
      - Cash & Voucher
      - Evacuation
      - Food Security & Livelihoods
      - Health
      - NFI Distribution
      - Pre-positioning of Stocks
      - Psychosocial Support
      - Public Awareness Raising & Sensitization
      - Rapid Training (including on First Aid)
      - Shelter
      - WASH
      - Other
    - Description box stays the same

- Actions Taken by Others
    - Change title of Section to `Early Actions Taken by Others`
    - Change help text of section to `List the early action activities undertaken by other actors and give a brief description`. **Question**: We want to ask users to mention who the Others are. Should we add a line saying `Also mention who the other actors are.` to the help text? Or?
    - Description box gets larger as per Invision design. An option here would be to add an example to the place-holder to give an example of mentioning who other actors are.

### Step 4 - Response

 - Planned International Response:
   - Add additional options - they function the same as the options for regular field report, which remain the same as Early Warning:
     - `FbA by the DREF or Imminent DREF`.
     - `Forecast-based Action`
   - Change text for `DREF Requested` to `DREF`

 - Contacts:
   - Stays the same as Contact for regular field report, except for:
     - Under National Society Contact, change help text to `The most senior staff in the NS responsible and knowledgeable about the risk`
     - IFRC Focal Point, change help text to `IFRC staff who is overall responsible for supporting the NS in its response to the anticipated disaster event`

 - Field Report is Visible To:
   - No Changes from Regular Field Report.

cc @necoline

**Comment by batpad** [comment]
@mmusori This is ready to be tested. I have created a separate ticket for adding the two new fields: #880 . And I will create a separate ticket to ensure all the values are displayed on the field report frontend correctly (though would still appreciate you pointing out things missing there).

You should now be able to select Early Warning to have options and labels and help texts change, as per the details in this ticket.

It is entirely possible I missed one or two minor things as I was going along, please let me know - this was quite a big implementation, so I do expect there to be at least a couple of issues to resolve - please feel free to let me know and I will fix things as soon as I can.

**Comment by mmusori** [comment]
Changes requested by the FBA team for the EA/EA Field Report. 
Title: Early Warning/ Early Action instead of just Early Action
change description of the title to  to: First report for this hazard.
Change the word predicted to forecasted.
Move hazard up to below the Title box. 
Screen 2: 
Largest population:  remove the word Estimation. 
Change example to: Hurricane Sirius is expected to hit the Whinging region early Tuesday morning. The system currently has sustained core wind speeds of 140km/h and gusts up to 170 km/h. The local government has started evacuating thousands of people. The Red Cross branch in Whinging has deployed staff and volunteers to communities at risk to support evacuation and to assist the population in protecting themselves and their livelihoods from the impacts of Sirius. 
IFRC Early actions: remove Review Early Action Protocol
Screen 3:
Information bulletin: add /hazard like in the paragraph below.
'Indicate if an Information Bulletin was published, is planned or if no Information Bulletin will be issued for this operation/disaster/hazard.'
Screen 4: Remove imminent DREF from FbA by the DREF

**Comment by batpad** [comment]
@mmusori have implemented all the changes above, with some clarifications required below:

> Title: Early Warning/ Early Action instead of just Early Action

Which title are you referring to here?

> change description of the title to to: First report for this hazard.

Done

> Change the word predicted to forecasted.

Done

> Move hazard up to below the Title box.

Done

> Largest population: remove the word Estimation.

I changed this to say `Names` as it looks strange without any label there. Let me know if this is fine.

> Change example to: Hurricane Sirius is expected to hit the Whinging region early Tuesday morning. The system currently has sustained core wind speeds of 140km/h and gusts up to 170 km/h. The local government has started evacuating thousands of people. The Red Cross branch in Whinging has deployed staff and volunteers to communities at risk to support evacuation and to assist the population in protecting themselves and their livelihoods from the impacts of Sirius.

Done

> IFRC Early actions: remove Review Early Action Protocol

Done (deleted Action from Admin)

> Information bulletin: add /hazard like in the paragraph below.
> 'Indicate if an Information Bulletin was published, is planned or if no Information Bulletin will be issued for this operation/disaster/hazard.'

Done. (Made this change for both Event and Early Warning field reports - let me know if this should apply only to EW)

> Screen 4: Remove imminent DREF from FbA by the DREF

Done.

@mmusori Could you please test the above and let me know if all looks fine on the form? Thank you!

**Comment by mmusori** [comment]
1. The example in the Risk Analysis has not yet been changed.  
2. You completely removed the FBA by the DREF. The request was to remove the words "imminent DREF". So as an option  under Planned International Response can we still have 'FBA by the DREF'
Otherwise all good on the form.

**Comment by mmusori** [comment]
The Front end for the EA/EW Field Report is still identical to that of the Event field Report. but the input fields for the EA/EA are different so we would like it if the front end would show the fields from the EA/EW Filed Report input form.

**Comment by batpad** [comment]
@mmusori sorry - can you please tell me specifically what fields need to be changed on the frontend for the field report ?

**Comment by mmusori** [comment]
Last Feedback: 
Third Section:  Early Action
Under actions taken by NS , add: Activation of Early Action Protocol.
Under IFRC: Support activation of Activation of Early Action Protocol
Fourth Section: Response, Changed 'Planned Response' to Planned Interventions'

**Comment by batpad** [comment]
Munu,

> Under actions taken by NS , add: Activation of Early Action Protocol.
> Under IFRC: Support activation of Activation of Early Action Protocol

These now no longer require code changes. So we can just make these changes
in the admin backend.

> Fourth Section: Response, Changed 'Planned Response' to Planned
Interventions'

Will do.

-Sanjay

**Comment by mmusori** [comment]
> @mmusori sorry - can you please tell me specifically what fields need to be changed on the frontend for the field report ?

Hi , I sent you the below screenshots on Teams. 
But those are the numerical details we expect to see on the frontend. 
Thanks. 
![image](https://user-images.githubusercontent.com/7780809/70615451-b9c37080-1c0c-11ea-93b6-786b2b25a2bb.png)

**Comment by batpad** [comment]
Thank you @mmusori that was a bug, it should now only show the numeric details applicable to the FR type. Please check. Hopefully this addresses everything :) - Let me know. Thank you!

**Comment by mmusori** [comment]
Thanks @batpad the EA Field Report on the front end looks great. It is pulling in the data and has the new numeric fields.  But the emergency page still has the Event numeric fields so no data is pulling into the Emergency page in the Emergency overview box. If we can have the same fields in the emergency overview as in the numeric details of the EW Field Report.  And rename the Emergency overview to "Overview"

**Comment by batpad** [comment]
@mmusori displaying the correct fields as per the field report type (Event or Early Warning) should now be fixed. Please test. Thanks for noticing this.
