### ISSUE TITLE
UI fixes, PER and other small things

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#834]
I've discovered some small things when going through the PER pages on the development pages (live pages don't have data yet so hence these aren't visible on the production side) that require attention to improve the UI.

Below a screenshot of one issue, where data (here email) input by the user goes over the edges of the box/card:

![image](https://user-images.githubusercontent.com/52411237/66118349-775f3100-e5d6-11e9-80c9-9c9e043a0e39.png)

We also need to make sure that we use the same expressions across the different tabs and pages.

If there is no data submitted and to show on a particular page or tab, it should say "No data to display." At the moment, some tabs say that but on some pages it says "There is no data to show." For consistency let's have one thing across all pages.

![image](https://user-images.githubusercontent.com/52411237/66145703-ac39ab00-e60b-11e9-95da-232f6ac747fa.png)

![image](https://user-images.githubusercontent.com/52411237/66145739-bbb8f400-e60b-11e9-8c89-4b2fae4e3197.png)

**Comment by szabozoltan69** [comment]
"There is no data to show" fix is done by @GregoryHorvath via https://github.com/IFRCGo/go-frontend/commit/7d200cd325ebe66433aaee031be386e30b261491

**Comment by teklal** [comment]
A few other small fixes (sorry!):

When creating a field report, the form already correctly uses the new surge terminology (Rapid Response Personnel instead of FACT/RDRT/RIT)

![image](https://user-images.githubusercontent.com/52411237/66326136-c4ba0600-e928-11e9-82dd-fa399b986f84.png)

However after a form has been submitted, it stll says FACT (example below). Can you change this to also say Rapid Response Personnel?

![image](https://user-images.githubusercontent.com/52411237/66326078-a9e79180-e928-11e9-8960-01a4e85ac549.png)

Could you also change on this same page (submitted form), the text "DREF Requested" to simply say "DREF"`?

**Comment by GregoryHorvath** [comment]
@teklal The fix is done by https://github.com/IFRCGo/go-frontend/commit/414e81aa12db8a28a5a2013ad0a6aa8e8df51c7e .

**Comment by teklal** [comment]
Fantastic, thanks @GregoryHorvath

**Comment by GregoryHorvath** [comment]
@teklal Regarding the issue with the e-mail text overflow, if I open a country's page and look at the 'Preparedness' tab I see different stuff than in your screenshot, like "Preparedness Work Plan" instead of "Preparedness for Effective Response Overview" as a title there and nothing is purple or darkened for me.

@szabozoltan69 Could this be different on production than the (probably) staging code I'm looking at? Or maybe I'm looking at the wrong page?

**Comment by szabozoltan69** [comment]
The purple/grey colors appear only on the development page (not on production, neither on local environment).

**Comment by nanometrenat** [comment]
@teklal can you please check if any more work is required under this one?  Cheers!

**Comment by teklal** [comment]
Most of the issues in this ticket have been fixed and addressed - however the problem of the email address going over the edges of the box is still there (first screenshot in this ricket).

**Comment by GregoryHorvath** [comment]
@teklal Sorry this auto-closes if I link the Issue to the Pull Request, if it's still needed as an open ticket feel free to reopen it.
