### ISSUE TITLE
Improve notification emails

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#836]
User emails to contain graphic elements, updated key figures, etc (as per YU designs).

**Comment by GregoryHorvath** [comment]
Comments by Munu:

> Weekly Digest:
> - Should replace ‘latest’ with ‘in the past 7 days’ for clear reporting period.
> - Swap total budget and emergency appeals funded boxes
> - Change ‘budget for DREFs and appeals’ to ‘total funding requirements’
> - Change ‘emergency appeals funded;’ to ‘total appeal coverage’
> - Latest field reports: seems to miss some info, i.e. date, country
> - Move ‘you are receiving this…’ to the bottom for all notifications

> New Operations:
> - Move ‘you are receiving this…’ to the bottom for all notifications
> - Amounts should always say (CHF)
> - Start and end date should not include time codes
> - Remove staff, volunteers, expat delegates (we should avoid expat delegate terminology completely)

> New Field Report:
> - Change “Request Assistance” to “International Assistance Requested”
> - Remove staff, volunteers, expat delegates (we should avoid expat delegate terminology completely)
> - Actions taken the information from the tick boxes is needed as well as from the description field. Actions taken needs to be disc aggregated by Actions taken by Ns, Actions taken by IFRC and Actions Taken by Other RCRC Movement actors.
> - Move ‘you are receiving this…’ to the bottom for all notifications

**Comment by mmusori** [comment]
The new 'Field Report' notification is good to go to production from staging.
The new 'Operations' is fine based on the forwarded emails from Greg but I still need to test in staging
The 'Weekly Digest' looks great from the forwarded email from Greg but I still need to test in staging.

**Comment by mmusori** [comment]
Dear Greg, on the Weekly Digest for the Deployments notification can you make the following changes. 
Change ALERTS/DEPLOYMENTS IN THE PAST 7 DAYS  to DEPLOYMENTS IN THE PAST 7 DAYS
Completely Remove Alerts 
Delete Type  column,  
Delete Deployment column, 
Delete Appeal column,
Change Title to  Emergency,  
Change Deploying person to Name, 
Change Society from to Deployed by, 
Add State date 
Add End date

**Comment by mmusori** [comment]
@GregoryHorvath on the New Operations Notifications,
They layout is fine. It provide more information than e had before. Just one more issue

1.	The “Follow this operation” button does not do anything. Not sure if this should be a big red button, but I like it. 😊

**Comment by mmusori** [comment]
This is now live in the production. We can go ahead and close this. New issues/requirements will be on a new ticket.
