### ISSUE TITLE
Consolidating map and table components and filters on Home and Region page

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#839]
## Issue

There is a fair amount of duplication across the the table and map features on the home and region page. 

## Expected behavior

The tables should share as much logic as possible and should make clear distinctions in data shared between the map and table to set this up for potentially creating a single filter system for both the table and map.

The map/table on region should be updated to include the same features present on the home page.
This means:
- [x] add presentation mode
- [x] remove bar chart
- [x] add legend
- [x] add filters with `in <Region_Name>`
- [x] add legend
- [x] update layout to match home_map
- [x] maintain automatic region filtering

**Comment by batpad** [comment]
@necoline - just a clarification here:

We do want the map + filters + table on the region page to behave **exactly** like they currently are on the home-page - the behaviour and design, including the data displayed on the map, should be exactly the same. Except, of course, on the region page, all the data is filtered by the region one is currently looking at.

Ideally, this would also include the Presentation Mode functionality. So, this would mean, on the region page:

 - Make map on region page consistent with home-page (don't show bar graph on map, show legend on bottom-right)
 - Make layout consistent - i.e. View All Operations on top, then map and table as a single component. We may want `View All Operations` to say `View All Operations in <Region_Name>`, and it links, of course, to all operations, filtered by current region.
 - Implement filters on top of map exactly like home-page (except on the region page there is always an implicit additional region filter).

Essentially, literally everything should be the same on the region page as the home-page, except for the fact that all data is filtered by region on the region page.

Sorry for not clarifying this clearly earlier - let me know if there are any questions.

**Comment by necoline** [comment]
Thanks for the clarification @batpad I'll revise my comment to include this

**Comment by LukeCaley** [comment]
@necoline @batpad map and table filters are not linked on either home or regional page.  Complexity explained in https://github.com/IFRCGo/go-frontend/issues/828.  In order to implment this we would need to either a) resolve these complexities and find a solution which enabled the desired behaviour of the filtering options on the header of the map affecting both the map and table view simultaneously orb) we implement these filters independently and we provide a clear hint to the users that this is the case.  @batpad @necoline to clarify and propose solutions.

Secondary issues:
1) date format should be in sync, i.e. yyyy-mm-dd for both the filter and the table
2) hint for user that a filter has been applied in the filtering tab, i.e. slight change in colour?

**Comment by necoline** [comment]
I think the work of resolving the complexities in order for the map and table filters to be linked will be outside the scope of this current phase. We have made changes that will make this feasible in the future, but require more time to refactor the tables and filtering utilities and direction on the UX before we can outline an appropriate way forward on this particular issue.

I will look into fixing the secondary issues since they are much lighter lifts.

**Comment by necoline** [comment]
The PR above does the following:
- Shows the active dates in the map date dropdown title so users know when the filter is active and for which dates
- Changes active table filter headers to red so users know which filters are applied to the table

The PR does not change the date format to yyyy-mm-dd
We are using native html form inputs for this date feature which does not allow for the reformatting of the display of dates. In order to change the way the day is formatted in the input field, we would have to bring in or build a custom date tool. This may be possible in future enhancements but would exceed the scope of this particular ticket.

**Comment by teklal** [comment]
I created new tickets for the issues that are beyond the scope of this release so that we can move this ticket to 'Done'.
