### ISSUE TITLE
Choose and implement a single select component

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#840]
## Issue

Currently there are number of select options used throughout the site:
**Custom Dropdown:**
![image](https://user-images.githubusercontent.com/20410256/66659299-3dfb7680-ec11-11e9-9599-da5764432b2a.png)
- app/assets/scripts/components/common/dropdown.js

Used in:
app/assets/scripts/components/connected/user-menu.js
app/assets/scripts/components/common/filters/date-filter-header.js
app/assets/scripts/components/display-table.js
app/assets/scripts/components/header-region-button.js

**Native Dropdown:**
![image](https://user-images.githubusercontent.com/20410256/66660680-a6e3ee00-ec13-11e9-8006-ebcaf0abbde7.png)

Used in:
app/assets/scripts/components/map/home-map/appeal-types-dropdown.js
app/assets/scripts/components/map/home-map/emergency-types-dropdown.js
app/assets/scripts/components/map/per-map/per-phase-dropdown.js

**react-select**
![image](https://user-images.githubusercontent.com/20410256/66661052-4ef9b700-ec14-11e9-917d-7e6a24bf6199.png)

Used in:
app/assets/scripts/views/field-report-form/index.js
app/assets/scripts/components/form-elements/input-select.js
app/assets/scripts/components/header.js
app/assets/scripts/components/mobile-header.js
app/assets/scripts/views/account.js
app/assets/scripts/views/register.js

## Proposal
I would like get a consensus between devs on which approach we should choose or introduce if we don't think any of the current options suffice and implement a single select option across the site.

I am partial to the react-select option especially seeing as it is already used throughout the code base
https://react-select.com

React select covers all of our use cases aside from date range selects. 
Currently our custom dropdown component has a date feature, but the dropdown is generally difficult to work with so I would recommend choosing a more customizable date selector as well

To address the date select, I have been looking at : 
https://github.com/airbnb/react-dates
- pros: it is a relatively simple feature
- cons: it uses moment which is a huge library. I generally try to avoid using moment unless there is good reason to

https://reactdatepicker.com
- pros: no moment, versatile, easy to work with
- cons: may be too much for what we need

@frozenhelium @batpad 
Please feel free to jump in here with your thoughts and ideas. I know you both have spent some time thinking about this and working with our selects. I would love to build this conversation around your experiences

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-api/issues/526
