### ISSUE TITLE
PER: map to show PER phase instead of PER forms

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#844]
The map on the PER page (on staging as production site doesn't have PER data yet) currently shows information on the PER forms that have been completed by a National Society. The request from the PER team has been to have the map instead display the PER phase that the NS has last completed. 

![image](https://user-images.githubusercontent.com/52411237/66998588-cd52cf00-f0d4-11e9-9901-184922c578e5.png)

The colors of the dots on the map should correspond to the colors of the respective PER phase as shown in the image on the PER page (snip below):

![image](https://user-images.githubusercontent.com/52411237/66998859-43573600-f0d5-11e9-8c05-9062c6953713.png)

**Comment by LukeCaley** [comment]
@necoline is this possible within the scope of the PER refactoring for GO 4.1?

**Comment by necoline** [comment]
@LukeCaley I don't see this as being a very heavy lift, I think it would be nice to have this included to showcase improvements that are visually apparent to the user. I will carve out a few hours for additional enhancements upon completion of the PER update to add this in.

**Comment by teklal** [comment]
@necoline did you have a chance to work on this yet?

**Comment by necoline** [comment]
The entirety of my time last quarter was spent working on updating the per forms. I spent some time this week on this issue, the ticket above describes in detail what I did

**Comment by teklal** [comment]
Thanks @necoline , I've taken a look at the current state of this on staging and it looks great! The one thing that I know has to be adjusted is the phrasing ("Last submitted phase" likely to be changed to "Current PER phase") on the legend, I am waiting for the confirmation from the PER team for their desired wording and will let you know as soon as I have that.

**Comment by necoline** [comment]
Sounds great, that will be a quick adjustment to make when you are ready

**Comment by teklal** [comment]
So the feedback from the PER team is to use "Current PER phase"

**Comment by batpad** [comment]
Thanks @teklal - I have made this change in https://github.com/IFRCGo/go-frontend/pull/959 and merged to `develop`. This change should be on staging in a few minutes.

**Comment by batpad** [comment]
This text change is done. Please re-open if anything needs to change.

**Comment by teklal** [comment]
Hi @batpad , thanks for making the text changes. 

There is one thing that I've noticed with the map and that needs to be addressed:
The dot over Argentina is currently black (which is not a color in the legend and does not correspond to any of the phases) and I haven't figured out a reasoning for that color. As it doesn't have a phase specified, it should be gray i.e. "incomplete"

![image](https://user-images.githubusercontent.com/52411237/74357344-15061080-4dc0-11ea-8e20-97a009f724d4.png)

**Comment by batpad** [comment]
@teklal - pushed a fix to fix the black dot issue. Ready for testing whenever you're able.

**Comment by teklal** [comment]
Tested and can't see a black dot on the map anymore, cheers!
