### ISSUE TITLE
PER: visibility restrictions

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#845]
There are some adjustments that need to be made to the visibility restrictions of the PER components on GO.

On the National Society specific / country specific Preparedness page this first box with the PER overview (as in image below) can be visible to the public but everything else should be visible only to that NSs PER Admin (for now).
  
![image](https://user-images.githubusercontent.com/52411237/67010921-e4061f80-f0ee-11e9-8b82-e310f29c420e.png)

Just to recap:  if a NS has submitted an Overview form, it shows up as a block like above.

This should be the only block that is visible to the public. All the other PER blocks (components, workplan, phase outcomes) should be completely hidden for everybody else except people with the PER permissions to that country (and higher level permissions of course).

**Comment by szabozoltan69** [comment]
(This task can have go-api related part also)

**Comment by szabozoltan69** [comment]
No problem at all... ☺️

**Comment by nanometrenat** [comment]
@szabozoltan69 can you please confirm whether this work has been done?  Thx

**Comment by szabozoltan69** [comment]
@nanometrenat - Hi Natalie, I have to recheck this, I don't remember clearly. I think yes.
Though as far as I know there is an ongoing full facelift for the PER code, so even if it was done, it has to be tested again, if the refactoring has been finished.

**Comment by necoline** [comment]
The PER refactor does not touch this feature. @szabozoltan69 if you updated the permissions to reflect these requirements then the behavior should remain the same.

**Comment by szabozoltan69** [comment]
Now I checked this feature with a non-admin user (in staging). For them there is only a blank white "first box" can be seen, with a notice of "Please log in".
(Otherwise the "first box" for admins differs from the above screenshot, there are cards in it.)
So it would be good to clarify if the recent behavior is OK or what to change/show for the public.

![preparedness_please_log_in](https://user-images.githubusercontent.com/6050643/73066694-fbe7ff00-3ea6-11ea-854b-6f6a578d2039.png)

**Comment by nanometrenat** [comment]
Hi @teklal can you please check if further work is required for this one, and assign to Sanjay if there is?  Cheers!

**Comment by teklal** [comment]
This fix is not done yet. As stated in the initial ticket/comment the overview box (it exists only if an overview form has been submitted for that country/NS) should be visible to all i.e. even not logged in users. Currently nothing is shown if a user is not logged in.

**Comment by tovari** [comment]
Obsolete
