### ISSUE TITLE
Add Highlighted Operations

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#846]
## Issue

Highlighted Operation should be present on region and country pages.
Only operations relevant to the region or country should be present

Related Issues: #851

## Description
Highlighted operations are referred to as [featured-emergencies](https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/connected/featured-emergencies.js) in the code base

## Related Questions
- Currently, there is no defined limit for the number of operations on display. The mockup is limited to 3 squares. 
   - Should we limit the operations to show only three (if so, how would these be selected)
  - Should we change the design to have rows of three?
  - Should we create a way to paginate through operations showing three at a time?
  - Any other approaches to consider?

## Tasks
- [x] create region and country filter for operations
- [x] update design to match mock
![image](https://user-images.githubusercontent.com/20410256/67027282-46532600-f0d7-11e9-891d-085b87c2336a.png)

**Comment by LukeCaley** [comment]
@necoline 
**Should we limit the operations to show only three (if so, how would these be selected)?** - the approach for the 'global' page has been to allow for more than three but to advise not to add more. This is partly because three is the magic number, partly because adding a fourth or more makes the overspill look awkward.  Suggest we adopt the same approach.

**Comment by necoline** [comment]
Thank you for the clarification @LukeCaley !

**Comment by LukeCaley** [comment]
@necoline 
current behaviour: individual events selected as "is featured" on the back-end appear on both home and regional page.  The user is not able to determine just to highlight on the region page.  This is the desired behaviour as we want to provide the regions the option to select what should be highlighted on their region, independent to what is highlighted on the home page (which is determined by the Geneva / HQ team).

Secondly, we should not limit the number of highlighted operations to 3 visible on the home page.  This could be as many as 6 (max limit) but we would like some elegant solution to centre and present a number of cards over 3.

**Comment by batpad** [comment]
To summarize the changes requested and next steps here:

 - Allow users to mark an Emergency as "Is Featured on Region Page" on the backend, which will allow users to feature emergencies on the region page, without them being featured on the home-page. On the front-end, on the region page, it should display the emergencies marked as `is_featured_region`. **Question** On the region page, should it also show emergencies marked as `is_featured` for the home-page? My suggestion would be to ask users to explicitly select Featured for Home-Page and Featured for Region separately on the backend.

 - Allow there to be a maximum of 6 Highlighted Operations on the home-page. Improve the styling for when there are more than 3 highlighted operations. **Question**: does the same logic apply to the Region page? **Longer-Term**: Our long-term suggestion here is to move to a carousel-like UI, with the highlighted operations occupying a single row, and allowing users to slide left-to-right. This would then allow us to have more highlighted operations without interfering with the styles. This would be out of scope for the immediate phase. **Short-Term**: Improve the styling for 4-6 operations as much as feasible, and take a call on the maximum number of operations we want to show.

cc @necoline @LukeCaley

**Comment by batpad** [comment]
Ideally, have permissions for is-featured-region only to be editable by admins of a region.

**Comment by batpad** [comment]
@LukeCaley I did a bit of digging into restricting the ability to set `is_featured_region` to "region admins". I created a separate ticket here: https://github.com/IFRCGo/go-api/issues/553 - let us continue discussion about granular permissions, but I think the permission restriction is likely beyond the scope of this ticket.

**Comment by batpad** [comment]
Both these are done and ready for testing. There is an option to mark an Emergency as Is Filtered For Region in the Admin backend. And upto 6 operations are now shown in Highlighted Operations.

**Comment by mmusori** [comment]
The requirements have been met. But we will need to discuss the ordering of the highlighted emergencies.  For now proceed to deployment.
