### ISSUE TITLE
Filter countries to show active operations

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#848]
## Issue

The country list on the region page should have the option of filtering for countries with active operations

Related Issues: #851

## Tasks
- [x] add a toggle button that activates a filter for countries with active operations

![image](https://user-images.githubusercontent.com/20410256/67031420-80282a80-f0df-11e9-8416-2134bb7fcf01.png)

**Comment by LukeCaley** [comment]
This works well for the regional country list, with one caveat.  Would it be possible to ensure that the alpha ordering is not truncated with a letter at the bottom of a column, as per example here
![active-ops](https://user-images.githubusercontent.com/7791954/69623845-dfb11880-1043-11ea-8980-a06fb88735d3.PNG)

**Comment by LukeCaley** [comment]
Desired functionality for this filter would extend to the /appeals/all page where users could then filter to only view active operations in the table view.  @necoline is this possible?

**Comment by necoline** [comment]
I didn't realize that this filter was intended to be applied to anything beyond the country list. This logic is closely coupled to the rendering of the country list. I'm sure I could apply a similar filter to the appeals/all page, but to my awareness, that would largely be a standalone ticket. Maybe we can discuss in our upcoming meeting when and how we should add this additional filter.

**Comment by necoline** [comment]
> This works well for the regional country list, with one caveat. Would it be possible to ensure that the alpha ordering is not truncated with a letter at the bottom of a column, as per example here (K appearing at the bottom of first column and Kenya appearing at the head of the next column to the right)
> 


This is not the simplest issue to address, I will take some time to see if I can find a solution to this problem

**Comment by LukeCaley** [comment]
> I didn't realize that this filter was intended to be applied to anything beyond the country list. This logic is closely coupled to the rendering of the country list. I'm sure I could apply a similar filter to the appeals/all page, but to my awareness, that would largely be a standalone ticket. Maybe we can discuss in our upcoming meeting when and how we should add this additional filter.

@necoline thanks for looking into this one and for discussing last week.  Suggest to set up a backlog ticket for this one as it would be a nice feature as discussed.

**Comment by batpad** [comment]
Created a separate ticket for the issue of an alphabet appearing at the bottom of a column: https://github.com/IFRCGo/go-frontend/issues/912

Am going to mark this issue as done and follow up on the styling of the columns separately.
