### ISSUE TITLE
Ability to deploy alternate code branches for testing

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#859]
I'm not sure if this ticket should go in a different repository.

We need a good way to be able to deploy different branches of the frontend code for testing.

Currently, `develop` gets automatically deployed to staging. There are times when we need to stage a different branch and have it available for testing. Currently, there is no straightforward way to do this.

Opening this ticket to discuss options and approaches we could take.

This is definitely more often a need on the frontend. Once we have this setup for the frontend, we can try and do something similar for the backend, but it would be great to have a process to "stage" a branch of the frontend code.

I'm not 100% sure how this should work -- whether this is something configured in CI, or a command a user runs like `yarn run stage-branch`, etc.

@frozenhelium you mentioned you guys generally have a similar setup - will be great to see exactly how you're managing this.

I'm also not sure if we should deploy to Azure for this, or use something more lightweight and easy for frontend apps, like surge.sh or so.

Would be great to hear ideas / thoughts - @szabozoltan69 @frozenhelium @necoline

**Comment by nanometrenat** [comment]
Related to https://github.com/IFRCGo/go-frontend/issues/479

**Comment by nanometrenat** [comment]
@batpad @frozenhelium I think this is sorted with the surge URLs yes?  If so may we close this ticket?  thanks heaps!

**Comment by batpad** [comment]
Yes. @kamicut wanted to look into if we can automate this in CI and whether that makes sense to do, but we can create a separate ticket for that if we think that's a good idea. Closing here.
