### ISSUE TITLE
Add keyword to indicate action creator functions

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-frontend#863]
Eg:
```js
const dispatcher = dispatch => ({
  _getAdmAreaById: (...args) => dispatch(getAdmAreaById(...args)),
  ...
});
```
should be
```js
const dispatcher = dispatch => ({
  getAdmAreaById: (...args) => dispatch(getAdmAreaByIdAction(...args)),
  ...
});
```
We can add some keyword like `action` to indicate that it is an action function and we won't have to prefix the actual props with  `_`

**Comment by batpad** [comment]
The `_` is confusing. I'm not sure if prefixing with `action` is a whole lot better, though. In these cases what I generally prefer to do is import the whole `actions` module or so, so then the code would land up looking roughly like:

```
const dispatcher = dispatch => ({
  getAdmAreaById: (...args) => dispatch(actions.getAdmAreaById(...args)),
  ...
});
```

cc @necoline if you have any thoughts here.

**Comment by necoline** [comment]
I understand the readability of your argument @batpad but in this case, I agree with @frozenhelium. I personally would prefer to avoid passing around the whole actions module. I am in favoring of using  destructured imports whenever possible which benefit from descriptive names to avoid confusion/naming conflicts.

**Comment by nanometrenat** [comment]
@batpad @frozenhelium @tovari was this dealt with via the rewrite or is there still work outstanding under this ticket?  Thanks!
