### ISSUE TITLE
3w: Changes to Sectors and Tagging options.

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#870]
As per feedback, we want some additional choies to appear in the Tagging section, that should not appear in the Primary Sector choices. Also some of the choices need to be renamed:

 - Add `Recovery` as a Tagging choice
 - Add `Internal Displacement` as a Tagging choice
 - `Education` to be added as a Primary Sector choice (@guipizzini clarification: should this be added to the Tagging choices as well?)
 - `Preparedness` to be renamed to `NS Strengthening` in the Sectors. (@guipizzini clarification: Does Preparedness get renamed in both Sectors and Tagging, or is there still a Preparedness option in Tagging and NS Strengthening only under the Sectors?)
 - `Livelihoods and Basic Needs` to be added as a Sector (@guipizzini the spreadsheet was a bit confusing on this one - is this correct? Does it get added to both sectors and tags?)
 
cc @frozenhelium @thenav56

**Comment by frozenhelium** [comment]
@guipizzini Can you confirm this?

**Comment by guipizzini** [comment]
Add Recovery as a Tagging choice
**YES**
Add Internal Displacement as a Tagging choice
**YES**
Education to be added as a Primary Sector choice (@guipizzini clarification: should this be added to the Tagging choices as well?)
**YES and YES**
Preparedness to be renamed to NS Strengthening in the Sectors. (@guipizzini clarification: Does Preparedness get renamed in both Sectors and Tagging, or is there still a Preparedness option in Tagging and NS Strengthening only under the Sectors?)
**NS strengthening replaces Preparedness in the Sectors. Could we keep the list of "tagging" open for us to customise it from the django interface as this will expand**
Livelihoods and Basic Needs to be added as a Sector (@guipizzini the spreadsheet was a bit confusing on this one - is this correct? Does it get added to both sectors and tags?)
**YES**

**Comment by frozenhelium** [comment]
So the options for **Sectors** will be
- WASH
- PGI
- CEA
- Migration
- Health
- DRR
- Shelter
- NS Strengthening
- Education
- Livelihoods
- Basic needs


And for **Tagging**
- WASH
- PGI
- CEA
- Migration
- Health
- DRR
- Shelter
- NS Strengthening
- Education
- Livelihoods
- Basic needs
- Recovery
- Internal displacement

Is this correct @guipizzini

**Comment by teklal** [comment]
Tested and works as desired. 

My OCD side is wondering about the ordering of the sectors and tags, is there a certain logic behind this order or should we have them in e.g. alphabetical order? Thoughts, @guipizzini ?
