### ISSUE TITLE
3w: Allow user to link to existing Emergency for Emergency Operations

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#871]
From feedback sheet:

When selecting "Emergency Operation" the link tab option to select existing operations should appear, which is not the case.

Is this to be an additional field that should appear that allows the user to link to an Emergency? Or should this linking happen in place of the current `Project Name` field?

The way I understand this is:

When the user selects Emergency Operation as the Operation Type, they should get an additional field which allows them to select an existing Emergency to link to. @guipizzini please confirm that that is the desired behaviour.

cc @frozenhelium @thenav56

**Comment by frozenhelium** [comment]
@guipizzini Can you confirm this?

**Comment by guipizzini** [comment]
Yes, i confirm this : When the user selects Emergency Operation as the Operation Type, they should get an additional field which allows them to select an existing Emergency to link to

**Comment by frozenhelium** [comment]
So, as previously discussed the input for current operation appears when we select `Emergency operation` and `Multilateral` (Programme type) option together
![2019-11-26-211039](https://user-images.githubusercontent.com/4931541/69647344-693b0780-1091-11ea-8da5-e72386687f2f.png)

**Comment by guipizzini** [comment]
Current operation should give us the list of emergencies on GO - and this should appear only when selecting emergency operation and multilateral. And the label should change from "Current Operation" to "Current IFRC operation"

**Comment by nanometrenat** [comment]
Test passed - in 3Ws when I select emergency operation and multilateral I get a Current IFRC Operation dropdown labelled 'Current IFRC Operation' that lists all emergencies.
