### ISSUE TITLE
3w: Do not submit form when user presses "Enter"

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#872]
From the feedback sheet:

If you press the  enter buttom in the middle of your data entry this is taken as having clicked submit. You incomplete data is then taken as your final entry and you are redirected to the 3W page. Submission should be only when you click submit. 

I like the idea of allowing form submit when the user presses enter, but I can see how this can cause problems for the user. @frozenhelium @thenav56 does this seem reasonably straightforward to do?

**Comment by frozenhelium** [comment]
It's pretty straightforward

**Comment by guipizzini** [comment]
good stuff :)
