### ISSUE TITLE
3w: Remove Disaster Type selection option

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#873]
Currently, when you select Long-Term Operation as the type, you are required to fill in a Disaster Type.

From the feedback sheet:

When selecting long-term operation, you are forced to choose a disaster or cannot submit the module. However there is no 'development' option that can be chosen. Could it be possible that when long-term is selected, people are not forced to choose a disaster ? 

And the suggested action:

Remove the disaster type selection option.

@guipizzini should the Disaster Type selection be removed entirely, or just made optional? Please confirm either way.

cc @thenav56 @frozenhelium

**Comment by guipizzini** [comment]
Remove entirely the disaster type tab. Since they will select from the "emergency list" that field is already there

**Comment by batpad** [comment]
From @guipizzini in Slack:

So, when we select an operation then ---> emergency field (from GO database) appears. No need for disastery type to appear, as that is already categorised within the emergency itself.

When long term programme is selected, a blank text entry to put the name is available as mandatory field and the disaster type appears too as a non mandatory field

@frozenhelium sorry, that seems a little bit different than what was indicated above in the ticket. Does the above make sense and would you be able to make changes accordingly?

**Comment by frozenhelium** [comment]
So, we'll have to just remove the required condition for the disaster type, right @guipizzini?

**Comment by nanometrenat** [comment]
Tested and it works as per description above - when long term programme is selected, a blank text entry to put the name is available as mandatory field and the disaster type appears too as a non mandatory field.

However the user does not know that disaster type is an optional field as it looks the same as all the mandatory ones...
