### ISSUE TITLE
3w: Visualize "No of people reached" and "No of people targeted"

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#874]
Currently, we take these values in the form from the user, but do not show them anywhere in the visualization.

@guipizzini do we have a clear idea of where and how these should be visualized?

cc @frozenhelium @thenav56

**Comment by frozenhelium** [comment]
For now I'll add it to the table. We can later figure out how we can better represent it. @guipizzini

**Comment by guipizzini** [comment]
perfect
