### ISSUE TITLE
3w: Rename "Long term Operation" to "Programme"

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#875]
From the feedback sheet:

I would just question if long term operation is a commonly used term - suggest that this could be replaced by 'development activities' or 'longer term programming' rather than longer term operation 

Suggested Action:

Revert language from 'long term operations' to 'programmes'

My understanding:

Under the Operation Type drop-down, the option called `Long term operation` should be renamed to `Programme`. @guipizzini is this accurate?

cc @thenav56 @frozenhelium

**Comment by guipizzini** [comment]
correct this : Under the Operation Type drop-down, the option called Long term operation should be renamed to Programme
