### ISSUE TITLE
Create new fields on Field Report

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#880]
We need to create two additional fields on the Field Report Form, both are applicable to both Event and Early Warning Field Reports:

 - Add a Yes / No field for `National Society Requires International Assistance` (`ns_request_assistance` in the backend).

 - Text field for users to add sources for where they have mentioned `Other` as source - `other_sources` in the backend.

Follows up from #833

**Comment by mmusori** [comment]
The requested fields are there.
1. Is it possible to have the requests for international assistance in one box. the Request by Gvt and the request by NS. this is not a deal break if not possible.
2. The Source box. In its current state is not likely to be used. Is it entirely not possible to have it by each condition (Injured, dead,...). But again not a deal breaker.
3. When I submit the field report it created an emergency page (Good) but I cannot see the field report. The link takes me to a blank grey page. http://dsgoproxyapp.azurewebsites.net/reports/9397

**Comment by batpad** [comment]
> When I submit the field report it created an emergency page (Good) but I cannot see the field report. The link takes me to a blank grey page. http://dsgoproxyapp.azurewebsites.net/reports/9397

@mmusori that link works for me -- i.e. http://dsgoproxyapp.azurewebsites.net/reports/9397
 - I see the Field Report and the information.

If there is a particular combination of steps that caused you to get the grey page, please let me know if you are able to reproduce it and let me know.

Does that link work for you if you click on it directly? If it is giving you a grey page, will be great if you can let me know what browser you are using, so I can try and reproduce the problem. Thank you.

**Comment by batpad** [comment]
> Is it possible to have the requests for international assistance in one box. the Request by Gvt and the request by NS. this is not a deal break if not possible.

Will give this a shot, but it maybe a bit more complex and I'd rather then keep this for later than implementing some sort of "ugly hack" solution. Will let you know by tomorrow.

> The Source box. In its current state is not likely to be used. Is it entirely not possible to have it by each condition (Injured, dead,...). But again not a deal breaker.

As discussed, this is unfortunately really not possible in this phase of work. I do feel like we need to ticket out changing how this data is stored on the backend before implementing this, and that's a bit of a larger lift. I do agree this is not a great solution. Let me know if we want to keep the other sources box in, or take it out, and perhaps try and work quickly toward the implementing of the "Other" textbox per row.
