### ISSUE TITLE
Improve signup workflow

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#889]
General improvements to the overall authentication workflow required.  Some considerations

- Consider expiry date for accounts
- Should the auth process request authentication by NS (requiring a new role of GO focal point per NS) and/or IFRC focal point by region?  
- Export functionality (csv) enhancement to include user roles and expiry date
Ref: https://github.com/IFRCGo/go-frontend/issues/5

_The below items were originally logged under this ticket but now split off into separate ticket #1233 as relate solely to the Register page display and not to follow-on processes_
_- Currently new users choose free text to identify their host National Society - this should be a dropdown_
_- IF Organisation type = IFRC THEN change Org Name to Office name_

**Comment by nanometrenat** [comment]
Re user export, xref https://github.com/IFRCGo/go-api/issues/419

**Comment by nanometrenat** [comment]
Note - these changes (e.g. NS dropdown) should be reflected in back end as well, to ensure consistency when IM manually sets up users.

**Comment by LukeCaley** [comment]
@batpad to architect and assign

**Comment by LukeCaley** [comment]
@batpad could you re-assign this as would like to implement this sooner rather than later as there are likely to be a jump in new users when communicating desired changes to use of field reports and the 3w feature.  @mmusori to accompany from an IFRC / business logic perspective.

**Comment by batpad** [comment]
@necoline re-assigning to you here, but this does need more speccing out.

@necoline I think if you can help with the speccing out of what is needed here, it is likely this is more backend focused and could be something that either @geohacker or @GregoryHorvath could take on.

**Comment by nanometrenat** [comment]
For potential consideration - we may also wish to improve process to deal with "stuck" pending users - e.g. 

> Greg was wondering about somehow/somewhere on the Django Admin, we could show a button or something that each admin would be able to press to validate the user (just as the links are constructed in the mails, 1-1 button only for each admin). So even if a mail (to verifiers) fails there would still be an option to validate.

**Comment by nanometrenat** [comment]
Greg's suggestion in 1233 re adding validation to stop users having @ in their new username when registering (to help users know to use their username not their email address to log in):
https://github.com/IFRCGo/go-frontend/issues/1233#issuecomment-656233517

**Comment by nanometrenat** [comment]
> Greg's suggestion in 1233 re adding validation to stop users having @ in their new username when registering (to help users know to use their username not their email address to log in):

Noting that the username is shown on the front end in places - and I can see that several of the recent Field Reports were created by people who have their email address as their username... which means that their email addresses are visible to everyone who looks at the FR.  Of course sometimes their email would be in the FR anyway (input into the 'contacts' section) but in other cases the user who inputs the FR is not one of the listed contacts - so @tovari you'll need to consider whether the user's email address [via their username] should show!

**Comment by nanometrenat** [comment]
@tovari it looks like there have recently been changes to the signup workflow - but I can't instantly spot the ticket so mentioning it here.

Now. if someone inputs a non-RC email, the error message to the user does not match the wording of the box below it:

> It appears you do not have an official Red Cross Red Crescent email, we will need to verify your status. Please provide the names and email addresses of two RCRC members with active GO accounts for us to contact.
i.e. it asks for two names and email addresses - but the box below just says
> Please justify that you are part of RCRC movement

![image](https://user-images.githubusercontent.com/33625192/152461811-0cabc52d-986b-40ee-b044-d8f78589de28.png)

the above may already be known in whcih case feel free to track it via an existing ticket.

And not sure if this specific ticket ("Improve signup workflow") is now obsolete?  Cheers N

**Comment by tovari** [comment]
Thanks @nanometrenat for spotting this. It should have been there already. Strange that this UI update is not on prod.
https://github.com/IFRCGo/go-api/issues/1243

**Comment by szabozoltan69** [comment]
This text mismatch is fixed via https://github.com/IFRCGo/go-frontend/pull/2210

**Comment by szabozoltan69** [comment]
![kép](https://user-images.githubusercontent.com/6050643/152521564-9371da87-5dcc-44f7-a02b-7aaa4346608a.png)
(prod)
