### ISSUE TITLE
Emergency and Field Report numbers differ

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#895]
## Issue

@batpad I guess this is an issue on the frontend but if not, notify me to check on the backend later.
> So the people reported by Others do not appear on the Field Report but they appear on the Emergency page. (Munu)

![Screenshot_1](https://user-images.githubusercontent.com/30079559/70424166-33255c80-1a6f-11ea-89d3-35373a2d8400.png)

##

![Screenshot_2](https://user-images.githubusercontent.com/30079559/70424173-34ef2000-1a6f-11ea-80c9-2de516b157fe.png)

## Steps to reproduce

1. https://dsgoproxyapp.azurewebsites.net/reports/9399
2. https://dsgoproxyapp.azurewebsites.net/reports/9399/edit (Situation step)

**Comment by batpad** [comment]
Thank you for the detailed issue @GregoryHorvath . I will fix this.
