### ISSUE TITLE
'Actions others' field is not shown anywhere on Emergency or Fields Report pages

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#896]
## Issue

@batpad @mmusori

On the backend:
![Screenshot_3](https://user-images.githubusercontent.com/30079559/70425627-d8413480-1a71-11ea-8425-eece4202abc0.png)

**Comment by batpad** [comment]
Thank you for the detailes issue @GregoryHorvath . Fixed with https://github.com/IFRCGo/go-frontend/commit/29af6710455ef9038663a135e3d604b4101d8c27 - will update here when this is merged to develop.
