### ISSUE TITLE
Map centering on regional pages and map "flatness"

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#897]
Hey @batpad and @geohacker , I stumbled upon a funny problem with the maps on a few regional pages. I noticed that currently the default centering of the maps on some of the regional pages is such that not all the countries in that region are shown. So the default view centering would need to be adjusted.

Below the problems I identified:

![image](https://user-images.githubusercontent.com/52411237/70444395-18b4a880-1a9a-11ea-9c72-c45f3ff48996.png)

In the Europe case, e.g. Tajikistan is in the region but does not show on the map at all.

![image](https://user-images.githubusercontent.com/52411237/70444745-b019fb80-1a9a-11ea-8561-7a228347d609.png)

For MENA the label box hides e.g. Yemen which is a country in this region.

![image](https://user-images.githubusercontent.com/52411237/70444867-d93a8c00-1a9a-11ea-91f2-e4162e88417d.png)

With Asia Pacific I discovered the problem to be a bit more complex: Samoa is part of this region, but a simple re-centering would not help in this case as the map is flat and Samoa is on the far "other side" of the map. It would be good to change all the maps from flat to "round" i.e. so that when navigating to the edge of the view, it would continue beyond the 0 degree line (or international date line). 

Sorry again if my explanation of the issue is not very clear. Happy to explain and elaborate more if needed.

I don't know how big of an issue this is or how much time fixing this would take but wanted to flag this as it would be good to fix these sooner or later for sure.

**Comment by teklal** [comment]
The screenshots are from the development GO pages, just fyi.

**Comment by geohacker** [comment]
Quick note -- the recent work to import bbox and centroid to the go database should help address this. It still means once the https://github.com/IFRCGo/go-api/pull/815 is deployed to production, someone has to edit the standard bbox and centroid to what's necessary. Editing can be done on the django admin.

cc @batpad

**Comment by batpad** [comment]
The bounding boxes for regions are now editable in the admin and can be used to define the default map view for each region.

@geohacker can this be considered as part of #938 and closed? @jhenshall can you confirm this can be considered done?

**Comment by jhenshall** [comment]
Regional bounding boxes and much of the examples are sorted. There's still an issue of 'map flatness' that affects the Asia Pacific region but I've split out into it's own ticket. This one can be closed @batpad .

**Comment by jhenshall** [comment]
@mariam-yu - also wanted to flag this ticket to you for the map design. Having the legend overlap the map often means that areas of interest are hidden behind it. Might be worth taking off the map itself or chaning location / size. Thanks!
