### ISSUE TITLE
Visual Design Mockups

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#9]
We’re really excited to share a few mockups to show you the overall look and feel of the Go Platform. We’ve incorporated IFRC’s distinguished red color in a way that will allow us to grow the color palette to meet the demands of multiple visualizations. We’ll continue to refine this palette as we see things with real data. The visual design is a clean, professional look that will represent IFRC’s brand and image inside and outside the organization. We’ll begin building next week building based on these styles. We’re excited to see this all coming together!

The mockups are available as pdfs in the drive:
https://drive.google.com/open?id=1OX23eo2iuPDdkzkE_RPJJD2C-cO3YdU-

@renecnielsen

**Comment by renecnielsen** [comment]
This looks awesome, @ascalamogna! Love it.

FYI, the IFRC Visual Identity doc is in the UX folder as is feedback on wireframes (including commented PDF) and a few of my old Sketch files (so you can see the fonts and colours I had dabbled with).

**Comment by ascalamogna** [comment]
@renecnielsen thanks! glad you like it! Most of the wireframe feedback looks fine. 

Quick question though: Why do you want to group the main navigation more? I'm worried it'll make it more difficult for users to find what they're looking for by adding an extra step.

**Comment by SimonbJohnson** [comment]
@renecnielsen looking at the event page feedback, I think more work might need to be put into how it will be displaced.  At the moment showing point data, when standard practice is admin codes and polygons.  There is no polygon service with pcodes, but looking to prototype in the new year.

@ascalamogna a bit of context setting of how we got to where we are
https://medium.com/@Simon_B_Johnson/who-is-doing-what-where-visualisation-from-concept-to-use-6aa0ae1c3cd5

and I've been thinking of a new way of approaching it, for some more food for thought:
https://simonbjohnson.github.io/report_driven_3w/
