### ISSUE TITLE
Link Emergencies from Alerts table

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#90]

**Comment by danielfdsilva** [comment]
@dereklieu On the alerts table we're getting the value for Emergency from the `operation` property. Is this correct?
Also the `id` returned in the response is not an `emergency` id. What should we use here?

**Comment by dereklieu** [comment]
@ascalamogna @danielfdsilva right now the surge alerts are not connected to a specific emergency. I will add a column in the database so that they *can* be connected. However, since the historic alerts come from a Google sheet, and only have an operation name, there's no way to link them to an emergency programmatically. 

So the historic alerts will not be linked, but new alerts will be (when the operator connects an emergency in the admin).

We should continue to use the `operation` property.

**Comment by guipizzini** [comment]
@dereklieu can this one be closed?

**Comment by dereklieu** [comment]
@guipizzini yes, but it just occurred to me that I don't think we're surfacing the surge alert table anywhere. It used to be on the home page but we removed it in favor of appeals. Should I put it back in the homepage, under appeals?

**Comment by guipizzini** [comment]
@dereklieu not needed, we have the surge tables and data on the deployments page - this is good enough. Thanks, will close this one.

**Comment by guipizzini** [comment]
@dereklieu, yes - we should put it under the appeals (and it requires a login). Can we as well link the alert table to the region page and emergencies, as we do for field reports and filter the display only for those concerned for that region/emergency? and the global view is on the home page, under the operations overview?

**Comment by k-som** [comment]
Additionally, can we have 'Operation' replaced with 'Event'?

![alert](https://user-images.githubusercontent.com/25579864/36031323-a0b38dea-0daa-11e8-9f6b-b6312a5827d9.jpg)

**Comment by dereklieu** [comment]
Phase 2.

**Comment by guipizzini** [comment]
in phase 2 even adding the table of alerts on the home page? Any chance we can do that one in phase 1?

**Comment by guipizzini** [comment]
@dereklieu had to re-open this one just to ask if we can add on the front end table a column called "Alert Type" that would display the value "Category" in Django. Thanks

**Comment by guipizzini** [comment]
@dereklieu as a last request, could the point above be implemented as a final ingest before we go to production?
