### ISSUE TITLE
Filter emergency type numbers on map filter drop down

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#901]
Related to #828 

On the home page and regional page when clicking on the 'emergency type' filter on the map, it shows numbers on the drop down list (as in image below) according to how many active operations there are for each emergency type. It would be great if these numbers changed based on the date filter applied reflecting the number of operations of each type during that time frame

![image](https://user-images.githubusercontent.com/52411237/70529049-eebdbd80-1b4f-11ea-94d7-498d3d2ed2c7.png)

**Comment by nanometrenat** [comment]
@necoline can you please advise on complexity of fixing this issue?  Backup option is to instead completely remove the numbers from the filter.
