### ISSUE TITLE
Surge: Query Surge google sheet

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#906]
## Issue
Due to the widespread familiarity of google sheets among admin users, it is proposed that admin users responsible for deployments be allowed to maintain data input through a google sheet that will be queried by the IFRC DB. An example of the new data can be found [here](https://docs.google.com/spreadsheets/d/1CBvledFYc_uwlvHTvJE0SYS7_mPGU2L-zhrqbB4KNIA/edit?usp=sharing). The current data is not clean, but the proposal is that we populate the sheet with clean data for the current year and add additional rows of previous years as the data is cleaned.
 
## Challenges
- the data in the google sheet should be available alongside older deployment data in the current database
  - In order for this to happen, time will need to be allocated toward identifying the optimum strategy for reconciling the google sheet and the deployments table into one cohesive table with a shared model. 
 
- Identifying the structure and use of the google sheet so that the values match the value types expected in the schema and measures are put into place to prevent people that are updating the sheets from accidentally dirtying the data.

**Comment by nanometrenat** [comment]
This ticket is on hold - Google sheet will not be used.

**Comment by nanometrenat** [comment]
Closing as Surge changes are on hold pending RRM integration design.  New ticket to be logged if required once those details confirmed.
