### ISSUE TITLE
Surge: Alerts and Deployments Tables

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#907]
Definition: Deployments are alerts that have been assigned. 
Deployments will be displayed in a table for deployed personnel. The table should contain information newly available from the google sheets. It should also allow users to see a longer list of past deployments.
In the first iteration, these tables will not vary in style or functionality from the existing design (shown below). The bulk of the time budget will prioritize the backend work. Until the complexity of the data integrations is identified, we will commit to implementing these tables without the filters, export or style changes. 
Original table:
![image](https://user-images.githubusercontent.com/20410256/70563183-c936b100-1b5b-11ea-8809-ba63aedec0a5.png)

Redesigned Table:
![image](https://user-images.githubusercontent.com/20410256/70563231-de134480-1b5b-11ea-9256-23d92e8cec91.png)

Deployment data is accessed in a variety of locations throughout the code base so we should ensure that these changes do not affect any of the following features:
Emergency Page:
ERU table
Personnel table
Featured Emergency
Deployment Page
Deployment Map
ERU Table (to be replaced)
Operations Popover

**Comment by nanometrenat** [comment]
Closing as Surge changes are on hold pending RRM integration design.  New ticket to be logged if required once those details confirmed.
