### ISSUE TITLE
Surge: Replace ERU Readiness

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#908]
ERU Readiness
This functionality present in the deployments page is not used in the current platform. It is proposed to change the cards currently in use to a snippet, possibly an iframe, from Tableau that pulls from the google sheet to display the ERU readiness.
Since these cards have no connection to the rest of the GO platform, this transition should not contain any side effects for other features.

Current design:
![image](https://user-images.githubusercontent.com/20410256/70563483-5548d880-1b5c-11ea-9d94-96b9508bced5.png)

New table to be imported from Tableau:
![image](https://user-images.githubusercontent.com/20410256/70563524-672a7b80-1b5c-11ea-8270-a30f07ec8dcb.png)

**Comment by nanometrenat** [comment]
Closing as think this is superceded by Ana Maria's work
