### ISSUE TITLE
Surge: Add Surge Deployments table

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#909]
## Issue

In a small number of cases, a surge deployment will be created. A table displaying the following information will be created in Tableau and added as a snippet or iframe at the bottom of the deployments page.

![image](https://user-images.githubusercontent.com/20410256/70563696-b375bb80-1b5c-11ea-9baf-ece2289a1c76.png)

**Comment by nanometrenat** [comment]
Closing as Surge changes are on hold pending RRM integration design.  New ticket to be logged if required once those details confirmed.
