### ISSUE TITLE
Separate lines for DREFS and Appeals

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#91]
On the homepage charts, have two lines one for DREFS and one for Appeals.

**Comment by danielfdsilva** [comment]
@ascalamogna The homepage charts rely on aggregate data. The api din't support returning aggregate results by type. @dereklieu Is this still the case?

**Comment by dereklieu** [comment]
Yeah, separating drefs and appeals in the response is a todo.

**Comment by dereklieu** [comment]
@danielfdsilva On the back-end, the only practical way to do this is to split the query into two, one for DREFs, and the other for Appeals. I've added the ability to do this using an arbitrary `filter_{key}={value}` property to the `aggregate` endpoint.

So to get DREFs (atype = 0) you would use:

[`/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year&filter_atype=0`](https://dsgocdnapi.azureedge.net/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year&filter_atype=0)

Appeals (atype = 0) would be:

[`/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year&filter_atype=1`](https://dsgocdnapi.azureedge.net/api/v1/aggregate/?start_date=1990-01-01&model_type=appeal&unit=year&filter_atype=1)

**Comment by guipizzini** [comment]
@dereklieu any progress on this? Could enhance a lot, the analytics on the front end. Thanks

**Comment by dereklieu** [comment]
@guipizzini there's a pull request open and waiting on review. Should be deployed today or tomorrow.
