### ISSUE TITLE
URGENT: GO not working on Edge or Internet Explorer

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#921]
Currently GO does not appear to be rendering at all on Microsoft Edge or Internet Explorer (which is still used within IFRC and is hence important to have working). 
When trying to open GO, all it gives is a blank page.

Don't know if this problem is only at my end.

Microsoft Edge:
![image](https://user-images.githubusercontent.com/52411237/70978096-6f7c3c80-20af-11ea-98bc-f8a700f0581e.png)

Internet Explorer:
![image](https://user-images.githubusercontent.com/52411237/70978040-57a4b880-20af-11ea-8bb4-dc3be582f63d.png)

Edit: the problems with Firefox are probably only on my end as things worked on Firefox on Sune's computer.

**Comment by batpad** [comment]
cc @thenav56 @frozenhelium

**Comment by nanometrenat** [comment]
These are the errors I get in my console when navigating to Go using Edge:
ERRORS:

- SCRIPT1028: SCRIPT1028: Expected identifier, string or number - vendor-51cdb2b243.js (1,2019149)
- SCRIPT5022: SCRIPT5022: Cannot find module 'babel-polyfill' - bundle-6fa35ad00f.js (1,206)

INFO:  CSS3121: The media query -ms-viewport has been deprecated.

**Comment by teklal** [comment]
Microsoft Edge version 44.18362.449.0
Internet Explorer version 11.476.18362.0

**Comment by frozenhelium** [comment]
@teklal It's fixed. Can you verify it through the staging server (https://dsgoproxyapp.azurewebsites.net/)
CC: @batpad

**Comment by nanometrenat** [comment]
Hi @frozenhelium Natalie here - looking better for Edge but not yet for IE for me.

The GO homepage Staging version now loads well on my Edge browser (Microsoft Edge 44.18362.449.0), thank you.

However it still doesn't load in IE for me (my version of IE is 11.535.18362.0)
When loading the Staging envt page I no longer get the babel-polyfill error (that I get in Prod) but I do get the below now, and still a blank screen:
SCRIPT1002: Syntax error - vendor-f78405ea52.js (1,407134)
SCRIPT5022: Cannot find module 'react' - bundle-6d605db9f2.js (1,206)

**Comment by frozenhelium** [comment]
@nanometrenat Hi Natalie, IE has become obsolete, so we agreed not to add fix for it (Since it'll take a lot of effort and time to add support for IE)

**Comment by nanometrenat** [comment]
@frozenhelium  good point, well made.  Works well in Edge.  Cheers!

**Comment by frozenhelium** [comment]
@batpad lets push this to production, should I cherry pick the fix and create PR targeting `master`?

**Comment by batpad** [comment]
The fix has been pushed to production. As discussed, this is fixed for Edge, and we are not attempting to fix IE right now.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/772
