### ISSUE TITLE
Country pages - GO weblinks to IFRC.org don't support multi-word country names

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#922]
## Issue

Weblinks to IFRC.org country pages were added via #776.  On the whole these are great, but country names with two-or-more words (e.g. Solomon Islands, Democratic People's Republic of Korea, Federated States of Micronesia, New Zealand etc.) currently don't link correctly, as the URL on GO has spaces in it.

## Steps to reproduce

Go to GO Country page e.g. Solomon Islands https://go.ifrc.org/countries/156.  The link at the bottom (labelled *Solomon Islands on IFRC.org*) goes to a URL of `https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/solomon%20islands/` (which returns a PageNotFound screen)

Similarly the FSM country page https://go.ifrc.org/countries/195 links to `https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/micronesia,%20federated%20states%20of/`   (which returns a PageNotFound screen)

The DPRK country page https://go.ifrc.org/countries/193#operations currently links to `https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/democratic%20people's%20republic%20of%20korea/`  (which returns a PageNotFound screen)

## Expected behavior
We need to fix these so they go to correct links.  As far as I can tell from my clicks around, the simplest business rules to change the current GO ifrc.org URLs that should fix the vast majority of these broken links are:

- replace spaces with hyphens
- remove commas and apostrophes

e.g. correct links for the first two examples above would be
`https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/solomon-islands/`
`https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/micronesia-federated-states-of`

## The full fix for 100% correct links
NOTE: the above business rule changes would improve things a lot but would not fix ALL of the broken links however, as some of the IFRC web pages use a different word order to what's used on GO - e.g. DPRK on GO is DPRK vs on IFRC.org it's KDPR
Real IFRC.org link is `https://www.ifrc.org/en/news-and-media/news-stories/asia-pacific/korea-democratic-peoples-republic-of/`
and in other cases it's not solely a word order thing e.g. For Iran the GO page links to
`https://www.ifrc.org/en/news-and-media/news-stories/middle-east-and-north-africa/iran,%20islamic%20republic%20of/` whereas the actual link on IFRC.org is
`https://www.ifrc.org/en/news-and-media/news-stories/middle-east-and-north-africa/iran/` (one word country name rather than the full country name)

Presumably a separate mapping table would be needed if we are to explicitly link all countries (or to have a manual override for cases where IFRC.org web page conventions are not the same as GO).  This is similar to the country discussion in #415

@lukecaley can you please confirm how you would like to approach this?  Thx

**Comment by nanometrenat** [comment]
For the avoidance of doubt, this is not an urgent request, just one for the list - but I don't have the power to do labels as yet...

**Comment by batpad** [comment]
Thanks for the detailed issue @nanometrenat . This seems clear, will add it to the project board and this should be an easy fix to prioritize.

**Comment by LukeCaley** [comment]
Thanks @nanometrenat.  We should be able to do this as a one-off process verifying against the IFRC.org site so a simple process to download a master table and amend URLs is required.

**Comment by nanometrenat** [comment]
As per @LukeCaley comment above we need to add an extra field in the countries table for IFRC web URL, and we will then manually populate (rather than constructing the IFRC.org URL programmatically)

**Comment by GregoryHorvath** [comment]
@nanometrenat Right now the **regions** in the path are pretty hardcoded as well, and while looking around the site `/europe-and-central-asia` is a valid part of the path, in some cases it wasn't working with some **countries** for ex.:
* `/europe-and-central-asia/hungary` was **bad**
* `/europe/hungary` was **good**

Do we want the field to allow one to specify the whole URL, or just the region/country part of the path?

**Comment by nanometrenat** [comment]
Thanks - I think if we're specifying any part of the path we may as well specify the whole path... that way we can quickly change things up if/when the IFRC.org website gets restructured... Cheers :)

**Comment by teklal** [comment]
@GregoryHorvath when will the frontend PR be deployed to staging (or a separate url) for testing? I see the url field has been added in the backend but won't be able to fully test this until frontend is deployed too.

**Comment by GregoryHorvath** [comment]
> @GregoryHorvath when will the frontend PR be deployed to staging (or a separate url) for testing? I see the url field has been added in the backend but won't be able to fully test this until frontend is deployed too.

@teklal Oh right sorry for that, I forgot I assigned that review to Sanjay but he's busier these days than ever so I just pulled that into `develop` so it should be on staging in ~5 mins I believe (or maybe it already is while I finish this comment).

**Comment by teklal** [comment]
@GregoryHorvath So the thing here to test at the moment is that in the backend a user can specify the IFRC URL for a country and that this URL shows up correctly on the frontend? 

If a URL has not been specified this "button" 
![image](https://user-images.githubusercontent.com/52411237/78349650-36a39d00-75a4-11ea-8a6c-fa4b7afadace.png)
will not show on that country's GO page.

Anything else to test?

If that's it, then this is tested and works.

**Comment by GregoryHorvath** [comment]
@teklal As far as I understood Natalie's comments right, I believe this is it. Thanks!

**Comment by nanometrenat** [comment]
Closing this ticket as it is now complete and in Production.  It's the first ticket I ever logged in GO Github!

IM manual work required to paste in the IFRC URLs country by country, that is on my list for coming days.

In the meanwhile I have already done New Zealand :) as that is how I first noticed this.  Woop!

**Comment by nanometrenat** [comment]
Note to self - see also "Verbose URLS" ticket https://github.com/IFRCGo/go-api/issues/357
