### ISSUE TITLE
Document encryption via token

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#926]
## Issue

Currently documents are retrieved via a URL link without a token requirement.

## Steps to reproduce

1. Click on http://dsgofilestorage.blob.core.windows.net/api/sitreps/3804/Member_Visibility_Test.pdf and document will open
(This is a Surge Document from this emergency on test site: 
 https://dsgoproxyapp.azurewebsites.net/emergencies/3804#details and this particular doc is set to visibility = Member)

## Expected behavior

The above document should not open unless the user is logged in with a user account that has permission to view the document (i.e. the document should be secured via Token and should also be https)

(if this should instead be API feel free to move it!)

**Comment by nanometrenat** [comment]
Now tracking this issue outside Github, via SRV-15418.  Will reopen if work at this end is required.

**Comment by szabozoltan69** [comment]
Another example is (thx Natalie) https://go.ifrc.org/emergencies/3751#details - ERU reports.

**Comment by LukeCaley** [comment]
'Correct' solution might be to implement some kind of federated login.  IFRC ITD looking into this as of 19 March

**Comment by nanometrenat** [comment]
Thanks @LukeCaley - note that right now for COVID operation we are heavily making use of the unrestricted permissions for the docs in the snippet.  So it would cause us problems if we suddenly switched this - would need a migration process for current already-existing docs to ensure continuity.
