### ISSUE TITLE
Practical navigation and knowing where you are incl identifiers

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#928]
## Issue

At the moment when on certain GO screens there are sometimes no links or breadcrumbs to show where you are and allow you to navigate - e.g. on the Albania earthquake page https://go.ifrc.org/emergencies/3887 you can see the country name in the text and on the map but there are no links to click back to the country or region.

Also, while one can see the GLIDE number for this emergency (EQ-2019-000157-ALB) on the screen that lists emergencies (https://go.ifrc.org/emergencies/all?region=3) it is not shown anywhere on the page of the emergency itself. 

Similarly, the Appeal Code for this is MDRAL008 but it's not visible on the page - I have to open the Appeal documents to see it.

I am aware there have been previous discussions re breadcrumbs (and wireframes show some) but further discussion is needed to confirm requirements specifications before proceeding to development.

Related issues #770 https://github.com/IFRCGo/go-frontend/issues/769

**Comment by batpad** [comment]
Just looking at this ticket again, it seems there are two related but distinct issues:

 - Implementing "breadcrumbs" for navigation as per the design, which I will outline in further detail at https://github.com/IFRCGo/go-frontend/issues/770 .
 - Displaying some additional data on some pages that is currently not being shown -- example of GLIDE number on emergency page and Appeal Code above.

For additional data that we should display on various page, @nanometrenat would it be possible to compile a comprehensive list, and along with each, point to existing design indicating where this data point should go / how it should be displayed, or just describing / indicating where that information should go.

**Comment by necoline** [comment]
@nanometrenat I think now would be a good time to embed practical navigation into the breadcrumb feature. I'm not sure who the best person is to identify what crumbs we want to implement as a fulfillment of this goal. Below is a list of views with the breadcrumbs currently in place in #1026 

It would be great if we could update this list with the desired breadcrumb information that we can implement in the current PR

_The check marks note what is currently in place. Emergency is an example of what an updated breadcrumb might look like to include more navigation details_

- About
  - [x] home > about
- Account
  - [x] home > account
- Country
  - [x] home > region > country
- Deployment
  - [x] home > deployments
- Emergencies
  - [x] home > emergencies
- Emergency
  -  [ ] home > emergencies > region > country > emergency
- Field Report
  - [x] home > reports(account/notifications) > field report
- PER Forms
  - [x] home > account > PER form
- Preparedness
  - [x] home > preparedness
- Region
  - [x] home > region
- Tables(view all ...)
  - [x] home > name of table

**Comment by LukeCaley** [comment]
@teklal and @yellowumbrella-design could you please sync with @necoline to determine what IFRC /  UI input is required for this ticket?

**Comment by nanometrenat** [comment]
Closing, breadcrumbs being dealt with under https://github.com/IFRCGo/go-frontend/issues/770

Emergency page still doesn't show Appeal Code (e.g. for Global COVID emergency it's MDRCOVID19 but I only know that when I go into Appeal Docs and open one to see it) however this should be covered under the Emergency Page redesign if it's deemed useful.  Thanks! @mariam-yu
