### ISSUE TITLE
Update GO to have new IFRC logo

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#929]
The IFRC has a new logo that was recently launched. Once we have guidelines from IFRC communications on how to use the new IFRC logo with the GO logo, this should be updated on GO.

**Comment by nanometrenat** [comment]
The logo will need to be updated in the following places that I can think of, dev to please look through code and ensure all places are found!

- homepage of both front end
- homepage of back end
- notification emails (all types of notification email)

**Comment by teklal** [comment]
Some more places where the logo needs to be updated:
- presentation mode on the front page map
- map exports

**Comment by batpad** [comment]
@GregoryHorvath the logo insertion for the map export / presentation mode might be slightly strange - let me know if I can help,

**Comment by LukeCaley** [comment]
@teklal to reference colour shade issues across the site with new IFRC logo @batpad

**Comment by GregoryHorvath** [comment]
@batpad With a quick check, I found we use the primary red color only in 8 different files. But for ex.: the selected page number in a paged table uses a different color code for red, so there could be multiple instances of this.

**Comment by teklal** [comment]
Other changes to make linked to this:

- [ ] update "red" across website to be IFRC red
- [ ] change icons (DREF, appeals etc) on cards to new IFRC icons

**Comment by LukeCaley** [comment]
Among the various options presented we will go with **adopting new IFRC logo and colour scheme but not icons** at this stage.  This will require some work on reducing the impact of the striking red, cc @yellowumbrella-design .

As noted, in the medium term, we will need to create and maintain a library of comms / GO / inter-agency icons.  The first required change will be create updated (but simplified) Appeals and DREF icons in line with inter-agency (OCHA noun project icons) standards.  After this we would also seek to adapt but reduce the impact of the offset red in icons which could be adopted, e.g. affected population icon to be used for targeted population. Suggest to implement the above colour and logo change and create a ticket from this second, longer task to be prioritised at a later date.

**Comment by nanometrenat** [comment]
OCHA icons:  https://thenounproject.com/ochavisual/collection/ocha-humanitarian-icons-v02/

There's a powerpoint and an AI file in the dropbox linked from here:  https://www.unocha.org/story/iconography-part-un%E2%80%99s-humanitarian-efforts-ocha-releases-new-humanitarian-icons

The IFRC Github repo is https://github.com/IFRCGo/red-OCHA-Icons-2018

@yellowumbrella-design FYI

**Comment by yellowumbrella-design** [comment]
UI color updates: https://invis.io/Q2WPW94R5SW#/412200855_1-0-0_-_Home_-_RED_V2
The icons are OCHA, a bit updated based on the above links (e.g. targeted population).

**Comment by yellowumbrella-design** [comment]
And with the COVID banner: https://invis.io/YGWPWLI5EFU#/412204959_1-0-0_-_Home_-_RED_COVID

**Comment by LukeCaley** [comment]
Looking good @yellowumbrella-design.  Looking good but left some comments on the wireframes and requests for slight adjustments.  Thanks!

**Comment by yellowumbrella-design** [comment]
> Looking good @yellowumbrella-design. Looking good but left some comments on the wireframes and requests for slight adjustments. Thanks!

@LukeCaley the comments were updated and the links above work. Let us know your thoughts. The last icon is from OCHA - affected population.

**Comment by GregoryHorvath** [comment]
Deployed the latest changes based on the the design of @yellowumbrella-design on Zeplin, to: https://ifrc-go-minor-new-logo.surge.sh/ and soon making a pull request.

cc @LukeCaley @teklal @batpad

**Comment by teklal** [comment]
A few comments, don't know if any of these would be blocking issues for deploying to prod today (at least most of them I'd think not):

- the logo does not look great in presentation mode of frontpage map
![image](https://user-images.githubusercontent.com/52411237/79324930-9ee16f80-7f10-11ea-9ffc-52ca2ee2abf9.png)
- same for the front page map export (logo is stretched)
![image](https://user-images.githubusercontent.com/52411237/79325269-31820e80-7f11-11ea-8be0-79a5baf17266.png)
- the color of the title in the above map export needs to be adjusted to the new red
- logo does not seem to be working in notification emails
- logo still needs to be added to the admin backend
- the highlighted operations cards are not fully centered/balanced on the page (this may be a bit much to comment on but the highlighted parts pop out for me at least)
![image](https://user-images.githubusercontent.com/52411237/79327302-8410fa00-7f14-11ea-9637-a5311de484a8.png)

As a shout-out: the logo does work and looks great on the field report map exports (although there could be a little more padding at the top of the logo), thanks!

There are still some differences between the wireframes and what we have now on staging. don't know if there will be a more extensive UI audit (@yellowumbrella-design ?) so if I should spare the effort of going through these things more extensively but here a few notes:
- the figure cards and the highlighted operations are switched around in order i.e. figures up
- on zeplin in the bottom right in the bottom panel: update to IFRC 2020 (now IFRC 2019)
![image](https://user-images.githubusercontent.com/52411237/79327481-d18d6700-7f14-11ea-8af9-27f972e6690f.png)
- on zeplin in the bottom left there are some links to webpages (ifrc.org rcrcsims.org data.ifrc.org) - the revamping of the About page is pending (#1094) and some of these links will be hosted there as well, so not sure what the need/plan for having them in the bottom panel will be after that

If needed/helpful, let me know and I can move some of these into separate tickets - especially if some changes relating to this will already be pushed to production.

**Comment by GregoryHorvath** [comment]
@teklal What is weirdest to me that I have none of those issues on the frontend if I run the code locally but if I open up staging they appear for me too. @batpad could it be we have a different thing on staging somehow? I just pulled down `develop` and ran that, and they show up differently...

On the backend/notification email logo part, I think I can fix those before today's planned release but we'll see.

**Comment by GregoryHorvath** [comment]
@teklal Okay so the backend + notifications logo should be covered one side, the other side the export and the presentation dash logo + header should be fixed as well. Keep in mind the backend changes didn't make it into staging yet but will be shortly before they hit production, but we just tested them.

**Comment by batpad** [comment]
This is Done.
