### ISSUE TITLE
Informal updates - scoping

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#930]
Systematic   means for capturing operational informal updates from IFRC Offices (IFRC   secretariat only). The informal update should be linked to an existing   emergency.

Emergency pages with notification emails.

Details of fields required will be provided by the 21st of January.

Requires scoping, design wireframes, user consultation, text editor #931

**Comment by szabozoltan69** [comment]
These fields are needed, connected to emergencies, as a form (thx Munu):
 Situation/Summary
  ·       Narrative
  ·       Graphic/map
 Government Actions
 National Society  Actions
 IFRC Actions &/or Coordination
 Focal Points

**Comment by LukeCaley** [comment]
@mmusori and @yellowumbrella-design & @GregoryHorvath to update details around wireframing / scoping process - estimate required from completion

**Comment by GregoryHorvath** [comment]
@LukeCaley Based on the current wireframes I started to work on the backend side of it. Basically the main models/database tables and parts of the Django Admin are done, though it could need refining if I'll finish the frontend part and get feedback via testing.

The remaining work I currently see on it (@mmusori feel free to add in if I miss something):
* Email notification
* Frontend pages

I'd say the requirements are pretty straightforward to me from the wireframes of the Create Informal Update form and the "List view". For the estimations I believe I updated the delivery dates in the sheet.

**Comment by yellowumbrella-design** [comment]
https://projects.invisionapp.com/share/HGWKUFPKNP3#/screens/407044170 (PW: IFRC) - updated and finalized

**Comment by batpad** [comment]
@mmusori @LukeCaley - can you please move this over to the 4.3 board if this is work still happening?

**Comment by GregoryHorvath** [comment]
> @mmusori @LukeCaley - can you please move this over to the 4.3 board if this is work still happening?

This might need full rework after all the changes happened to the Field Reports in the COVID sprint, but have to check if this is resumed.

**Comment by tovari** [comment]
@GregoryHorvath, @batpad would you mind to comment, how the implementation of this feature stands? Would be nice to see, how much work would it still require. Thanks!

**Comment by GregoryHorvath** [comment]
@tovari I honestly believe that the scope/approach behind this have changed a lot since, and I also suspect that the work done on this is lost in some branch and we'd be better off starting over from scratch with this (it wasn't too much done anyway).

I'd say this needs planning (and probably design) again, based on what have changed since the original request of this.
