### ISSUE TITLE
Formatting of text input fields - 

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#931]
The current field report Description and summary section  does not currently allow formatting. 

Desired behaviour is to have text editors for when people input information into the system - e.g. field reports - a style bar with options for paragraph, font, bold/underline, quote and bullet point. Paragraphs should be included.

This then needs to feed into formatting and layout onscreen, and notifications.

In the field report example, the summary could then be turned into a title with set structure. i.e Country -disaster type.( html text)

Action with Sanjay and Navin to look into potential solutions and come back with scoping/recommendations.

**Comment by batpad** [comment]
We would want a generalized solution for users to be able to apply formatting to fields both in the Django Admin as well as the frontend.

@teklal @mmusori - can you please point to exactly where we currently have fields where we allow users to add formatting? We can then evaluate whether we should take the same approach or a different one.

@thenav56 @frozenhelium do you have a favoured way to handle this? My preference recently has been to use simple markdown editors, but I am not completely opposed to something like ckEditor or other editors that output HTML if this is something that you folks have experience with and feel comfortable about maintainabiliy of and quality of output HTML.

**Comment by teklal** [comment]
Sorry @batpad for taking so long to get back to you on this. One area in which it would be great to have formatting enabled, is the surge alerts
 https://prddsgocdnapi.azureedge.net/notifications/surgealert/
https://go.ifrc.org/alerts/all

(Keeping in mind though that these will be in the future pulled automatically through an api)

**Comment by nanometrenat** [comment]
Currently on the Back End there is a formatted text editor for editing the 'summary' field for Emergencies:  https://dsgocdnapi.azureedge.net/api/event/3833/change/

HOWEVER not all of the formatting input there is rendered when the page is displayed - e.g. can't have multiple levels of bullet points:  e.g. see https://dsgoproxyapp.azurewebsites.net/emergencies/3833#details

So, we need to make sure that whatever editing options are available are also supported on the display side :)

**Comment by batpad** [comment]
@nanometrenat @teklal - would it be possible to get a consolidated list of all fields where we would like rich text editing? Then we can split those up into separate tickets for implementation in the Django Admin backend, and in the frontend forms. This can include the field report fields, snippets, other text fields..

Ideally, displaying all of these rich text fields correctly, including the existing ones, on the frontend will be handled in https://github.com/IFRCGo/go-frontend/issues/1011

**Comment by nanometrenat** [comment]
The single most important place that we need Rich Text Editing ability is in the snippets on Emergency pages (still need the ability to copy and paste a URL e.g. iframe or add a file of course - just have RTE as an option, together with a full audit trail).  I think someone said RTE snippets would be separated into a separate ticket but I can't tell which ticket it is... so have logged new issue https://github.com/IFRCGo/go-api/issues/670

**Comment by nanometrenat** [comment]
Xref comment on https://github.com/IFRCGo/go-frontend/issues/1011#issuecomment-690020781

**Comment by nanometrenat** [comment]
Closing as I believe this is superceded - I can see there is rich text editing in Emergencies and Field Reports.
I've not tested how they show on front end, but we can log another ticket if there's any other work required.

**Comment by nanometrenat** [comment]
Closing on the assumption that there has been a full rewrite of GO - if further work is required on rich text editing - or display of rich text on the front end - then new tickets will be logged with specifics.
