### ISSUE TITLE
URGENT - cannot submit field report

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#936]
## Issue

A user in Production has tried to submit a field report and at the end of the input process they have received an onscreen error message "Error:  Could not submit field report", with no information about exactly what the error is.

This is for a new emergency.  Screenshots have been provided of the 4 input screens, and I have tried to replicate in the staging environment but cannot replicate - my field report was saved successfully.

Can you please investigate?  Sending screenshots by email.  Many thanks.

**Comment by szabozoltan69** [comment]
After inserting "Puerto Rico" (with id 257) into prod database the field report could be created:
https://go.ifrc.org/reports/12080
Please check if the data are correct, I copied it from the attached screenshots.

**Comment by nanometrenat** [comment]
https://github.com/IFRCGo/go-api/issues/437

**Comment by nanometrenat** [comment]
Happened again today with New Caledonia (country 252) - selecting New Caledonia in the field report Country dropdown causes an immediate white screen due to a 400 error being returned for country=252&limit=200 (because no districts present for that country).

New Caledonia should not be available to select in the Countries dropdown.  Will update the master ticket #938 re Spatial data.
