### ISSUE TITLE
Add Number of Beneficiaries to HP Charts

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#94]
In the pop-up show the number of beneficiaries and amounts per month and per year for DREF and Appeals

**Comment by dereklieu** [comment]
@ascalamogna @danielfdsilva the API now supports arbitrary SUM properties in the format `?sum_{custom_field_name}={api_field}`. For example, to include the sum of the `num_beneficiaries` field for every appeal or dref for each year, you would use:

`?sum_benefit_peeps=num_beneficiaries`

Here's the full query:

[`api/v1/aggregate/?model_type=appeal&unit=year&sum_benefit_peeps=num_beneficiaries`](https://dsgocdnapi.azureedge.net/api/v1/aggregate/?model_type=appeal&unit=year&sum_benefit_peeps=num_beneficiaries)

Output:

<img width="378" alt="screen shot 2018-01-14 at 9 19 11 pm" src="https://user-images.githubusercontent.com/1590802/34916280-96b5c414-f970-11e7-909e-dfe452087eef.png">

Note that you can specify multiple properties to sum, aka `?sum_benefit_peeps=num_beneficiaries&sum_funded=amount_funded`. You can also use this in conjunction with [filter properties](https://github.com/IFRCGo/go-frontend/issues/91).
