### ISSUE TITLE
Don't render button next to Contacts on Emergency page if email / phone is empty

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#942]
## Issue

Currently, if a contact `email` is blank, the UI renders a strange looking empty button next to the Contacts on the emergency page. For eg. scroll to bottom of https://dsgoproxyapp.azurewebsites.net/emergencies/3827#details

## Steps to reproduce

Enter Contacts in a Field Report with Email left as blank. Then navigate to the associated Emergency page. See the buttons for contacting show up without any text in them.

## Expected behavior

If there is no email or phone provided, the button should not appear.

@nanometrenat noticed this bug, not sure how we should prioritize?

**Comment by batpad** [comment]
Offending code is roughly here: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/views/emergency.js#L582

**Comment by nanometrenat** [comment]
@batpad re priorities, this is a cosmetic issue so not high priority at all.  Good to fix in a spare moment!
