### ISSUE TITLE
[Staging] PER Blocker: PER Forms Area 3 and Area 5 do not render in Staging site

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#946]
## Issue
Similar to #943 there is a different screen that does not render (goes grey when you navigate it to it).

## Steps to reproduce

1. Go to Account / PER Forms https://dsgoproxyapp.azurewebsites.net/account#per-forms
2. Click on "Area 3: Operational Capacity 2" (https://dsgoproxyapp.azurewebsites.net/per-forms/operational-capacity-2/0) - that gives you a grey screen

Edit:  same problem with Area 5 (https://dsgoproxyapp.azurewebsites.net/per-forms/operations-support/0)

In the console I get these errors:

- Uncaught TypeError: Cannot read property 'nsAnswers' of undefined

- vendor-a68e2871b9.js:1 The above error occurred in the <E> component:
    in E (created by t)
    in t (created by Connect(t))
    ...
    Consider adding an error boundary to your tree to customize error handling behavior.

* note - the first time I went to this page I also saw an error around countries in the console - so I edited the form with country = none to assign it country = New Zealand - however the page still does not render.  So presumably this can't be exactly the same issue as #943

## Expected behaviour
Should have the form display ready for the user to access it.

## Related feature
PER #865

## Criticality/Urgency
Blocker - user cannot access the page.

**Comment by teklal** [comment]
Thanks for logging this @nanometrenat

**Comment by necoline** [comment]
Thanks for catching this!! I'll get on it this afternoon

**Comment by nanometrenat** [comment]
Maybe it might be to do with 'Exist Could Be Strengthened' vs 'Exist, could be strengthened' (i.e. the comma), though that is a total guess!!

**Comment by batpad** [comment]
@nanometrenat @teklal thank you so much for the catch. This should now be fixed on staging.

**Comment by teklal** [comment]
Checked and tested on staging, and it works!

**Comment by batpad** [comment]
Confirmed Fixed. Closing.
