### ISSUE TITLE
[Staging] PER: changes to wording on 3 PER benchmarks

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#947]
## Issue
Request from PER team to change the wording of 3 benchmarks in the PER forms. 

Benchmark 12.9
Currently on GO: "12.9 NS can manage the transition from relief phase and use of short-term resources and volunteers, to medium-term recovery interventions."
This is a mistake, that text corresponds to another benchmark (12.11)
The correct text is: 
"12. 9 The plan considers how to support self-recovery of affected population with their active participation beyond providing relief."
 
Benchmark 37.12 (note from Tekla: I was not able to check this on staging as Area 5 form did not render, this is based on PER team's comments of the production site)
Currently on GO: "37.12 NS has a donation tracking system, and works with the IFRC on joint operational shared services platforms (Mob table, etc.).NS has a donation tracking system, and works with the IFRC on joint operational shared services platforms (Mob table, etc.)."
The text is repeated. Should be:
  "37.12 NS has a donation tracking system, and works with the IFRC on joint operational shared services platforms (Mob table, etc.)."  

Benchmark 14.53
Currently on GO: “14.53 NS volunteers are trained in the use of the prepositioned shelter materials to construct basic shelters (e.g. shelter kit training).”
This is a mistake, that text corresponds to another benchmark (14.44)
The correct text is: 
“14.53 NS has considered how to integrate sector interventions to have the maximum impact on affected communities.”

## Related feature
#865 

## Criticality/Urgency
Is not a blocking feature for uploading but has been flagged by the PER team and hence important to fix in order to sign off the PER module on GO.

**Comment by batpad** [comment]
@teklal this should be fixed in #949 - I just want @necoline to have a look before it's merged - should be on staging by this evening.

**Comment by batpad** [comment]
This is merged to staging and ready to test, @teklal .

**Comment by teklal** [comment]
Tested and works. Thanks!
