### ISSUE TITLE
Hook Up Deployments Page

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-frontend#95]
The Map, table and overall stats need to be hooked-up for the deployments page. Attached is a mockup of what should go on the map. 
![screen shot 2018-01-08 at 4 31 56 pm](https://user-images.githubusercontent.com/6752098/34694576-9475cf12-f495-11e7-93e7-86118fab01dd.png)

**Comment by guipizzini** [comment]
comments on the deployments page, will be sent to you today.

**Comment by guipizzini** [comment]
@ascalamogna I've closed this one. Thanks
