### ISSUE TITLE
[Staging] PER - Question order and URLs

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#953]
Spun off from https://github.com/IFRCGo/go-frontend/issues/950

So I've found another small "bug" that needs to be fixed and that may be causing this problem.

Currently in staging the forms "Area 3: Operational capacity" (components 15 to 23) and "Area 3: Operational capacity 2" (component 14) are component-numerical-order-wise the wrong way round. 

Confusingly their urls are the "wrong way round" in the live environment (screenshots below)

Form: "Area 3: Operational capacity"
![image](https://user-images.githubusercontent.com/52411237/73366671-9fbe1a00-42ae-11ea-800b-dedef86473c4.png)

Form: "Area 3: Operational capacity 2"
![image](https://user-images.githubusercontent.com/52411237/73366636-903ed100-42ae-11ea-81a7-316a56fe0e6f.png)

 In the staging environment the forms are in the right order according to url (but not component wise).

I don't know if I was able to explain the problem clearly, let me know if you have questions. Basically the Area 3 forms should be the other way around in staging and in their current order they are in a different order from the live environment (right order but urls inconsistent with form numbering).

_Originally posted by @teklal in https://github.com/IFRCGo/go-frontend/issues/950#issuecomment-579790223_

## Related feature
PER #865

**Comment by necoline** [comment]
@tekla

I'm not sure I fully understood the problem.

Are you saying that the form 3 should contain component 14 and 3-2 should contain components 15-23 like so:

![image](https://user-images.githubusercontent.com/20410256/73370300-fd883d00-4281-11ea-9f30-591e576df7a3.png)
![image](https://user-images.githubusercontent.com/20410256/73370328-0d078600-4282-11ea-9f5c-0345522a5d2b.png)

_you can view the code changes in the PR above_

**Comment by teklal** [comment]
@necoline yes, exactly!

**Comment by nanometrenat** [comment]
Hi @necoline to be clear there are two different things here which may be related.  One is which URL maps to which labelled button in the top section
![image](https://user-images.githubusercontent.com/33625192/73380486-6b555880-42c4-11ea-9284-59fd585cfa79.png)
 i.e. if you hover over the two Area 3 buttons in STAGING the **URLs** are the correct way round:
- Area 3: Operational Capacity links to /per-forms/operational-capacity/0
- Area 3: Operational Capacity 2 links to /per-forms/operational-capacity-2/0
but when you click into them the **CONTENTS** have the wrong questions
i.e. operational-capacity page has Component 15: Mapping of NS capacities as first question and
operational-capacity-2 has Component 14: NS-specific areas of intervention as first question


This is the opposite to Production, where the contents are correct once you click into a page, but the URLs are the wrong way round.

Shall we have a call to discuss if further clarification is required?

**Comment by necoline** [comment]
Thank you all of the clarification.
#952 is ready for testing

**Comment by batpad** [comment]
@teklal @nanometrenat could you confirm this works as expected? thank you.

**Comment by teklal** [comment]
Yes, works as expected.
