### ISSUE TITLE
[PROD] Front End does not show last login date for users

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#956]
## Issue
Spin off of https://github.com/IFRCGo/go-api/issues/522 whereby the last login date shown in Django admin site only reflects last login to back end (logins to the front end site are not tracked in db).

## Steps to reproduce
Create a new user, log in to GO front end, check that user on Django back end and you will see the last login date is still empty.

## Expected behaviour
Should show date when user last logged in to front end or backend.
ALTERNATIVELY (in fact ideally) we would have a separate field to record last login to front end (retaining as-is the current field that tracks last login to back end).

If a new field then it should also be added to the user export report (requested via Action dropdown on https://dsgocdnapi.azureedge.net/api/profile/)

@batpad I would appreciate advice on whether we should implement something more sophisticated (that tracks last successful login, last failed login, number of failed login attempts etc.) as I'm sure something must already exist for this - or whether we should specifically build each bit individually.

## Related feature
https://github.com/IFRCGo/go-api/issues/572
(potentially see also old PR https://github.com/IFRCGo/go-frontend/pull/8)

## Impact
All users

## Severity
No impact to end users but makes troubleshooting difficult for admins.

## Is there a workaround?
No.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-frontend/issues/889 re Improve Signup Workflow

**Comment by GregoryHorvath** [comment]
Deployed to staging.

**Comment by teklal** [comment]
Thanks @GregoryHorvath, it's fantastic to be able to see the last login date to the frontend! I only wonder whether it would be better to have this field show on the "User" page (instead of "User profile" - or both?) as that is where the backend login and join dates show - to have the "important dates" in one place?

**Comment by GregoryHorvath** [comment]
@teklal I couldn't (maybe yet) find a way to add fields to the actual `User` model since it's the standard Django model if I'm right. I believe thus why it was necessary to implement the `User Profile` model so the `User` model could be extended this way.
On the other side if we want to show it somewhere on the frontend that should be no problem.

cc @batpad @thenav56 could you validate if I'm wrong-or-not please?

**Comment by thenav56** [comment]
@GregoryHorvath Yeah creating `User Profile` is a better/easier approach then custom `User` model.

If the requirement is to show the user profile in the user edit page in the Django admin panel then it can be done using inline.
Eg: https://github.com/the-deep/server/blob/develop/apps/user/admin.py#L15-L46
NOTE: Don't pass profile inline if the instance is been created. https://github.com/the-deep/server/blob/develop/apps/user/admin.py#L43-L46

**Comment by GregoryHorvath** [comment]
@teklal Above PRs name describes it well I guess, thanks for the tip @thenav56 I don't know why I haven't done this earlier:
![Screenshot from 2020-07-16 17-59-13](https://user-images.githubusercontent.com/30079559/87694200-2cda2a00-c78e-11ea-9a74-fa969bffd8cb.png)

**Comment by GregoryHorvath** [comment]
@teklal deployed to staging.

**Comment by nanometrenat** [comment]
Pleased to report that for a brand new user (Daniel) the Last frontend login date gets correctly populated (from null) on first login.
Still to test:  that subsequent logins update it correctly.  Cheers!

**Comment by nanometrenat** [comment]
@GregoryHorvath can you please also add this new field to the user export csv (available from https://dsgocdnapi.azureedge.net/api/profile/ in the dropdown)?  Thanks loads

**Comment by GregoryHorvath** [comment]
@nanometrenat It's there for me?
![image](https://user-images.githubusercontent.com/30079559/87946548-72ef0080-caa2-11ea-9abe-294b03b6c29c.png)

**Comment by nanometrenat** [comment]
> @nanometrenat It's there for me?

SORRY!  I looked again and you are so right.  @tovari and I were both looking and didn't spot it - oops!  Apols! Thanks for your patience with my muppetdom :)

**Comment by nanometrenat** [comment]
@batpad advises that @karitotp has tested this and is happy.

**Comment by nanometrenat** [comment]
Moving to Done as it's great to see the User Profile on the Users screen

**Comment by nanometrenat** [comment]
Released this morning I am told

**Comment by nanometrenat** [comment]
Checked in Production and the User Profile section is now there in Prod, and Front End logging correctly reflecting when user actually types in their login details and logs in.

Noting that as mentioned above if a user's login/session/cookie is stored (i.e they don't go via the login screen) then the last login field isn't updated.  However it is super exciting to have this field at all :)

**Comment by nanometrenat** [comment]
Unintended consequence of moving User Profile to also show on User page - now if editing an existing user that doesn't have a country (e.g. if user had been set up directly via back end or via migration, without going via the front end Register page) then you can't save any edits without selecting a country.  This isn't a bad thing - just making a note cc @teklal

**Comment by teklal** [comment]
This feature has brought me a lot of joy this week so thanks all for implementing it! :)
