### ISSUE TITLE
[PROD] URLs - BASE URL points to staging, notification emails - also user-friendly URLs please

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#958]
## Issue
There are several places in LIVE where a staging URL is shown.  We need to fix this so the appropriate URL for the environment is shown.  Ideally the URL would be the user-friendly URLs (go.ifrc.org and goadmin.ifrc.org rather than the azureedge URLs)

1. When a user registers for GO in Production they receive a confirmation email directing them to https://prddsgocdnapi.azureedge.net/verify_email/?token=...

This page has the following contents:

```
> It is a great day! <a href="https://go.ifrc.org/"><img   border="0" align="right" src="https://dsgoproxyapp.azurewebsites.net/assets/graphics/layout/logo300.png">
> You’ve validated your   email address and your IFRC Go account is now approved.
> If you do experience   any problems, please contact <a href="mailto:im@ifrc.org">im@ifrc.org</a>.
> You can start your   IFRC Go experience <a href="https://dsgoproxyapp.azurewebsites.net/login">here</a>.
> Thank you,
> IFRC Go
```

The URL on this screen should be go.ifrc.org/login rather than dsproxyapp... 
 Think the code is here:  https://github.com/IFRCGo/go-api/blob/master/notifications/templates/registration/success.html

2. password resets from GO contain the IFRC logo - as does the above page.  This is currently served from staging as per
`You are receiving this email because you requested a reset to your IFRC =
GO password. If you did not request a reset, ignore this email.
<a href=3D"https://go.ifrc.org/"><img border=3D"0" align=3D"right" sr=
c=3D"https://dsgoproxyapp.azurewebsites.net/assets/graphics/layout/logo300.=
png"></a>`
The image should instead come from a Production URL

Suggest a find and replace of the code to hunt out all examples of dsgoproxyapp hardcoding and substitute with environment-specific variables.

3. URLs used in emails are the long azure emails rather than the short go.ifrc.org or goadmin.ifrc.org versions.  Ideally the base urls would be the user-friendly versions.

## Steps to reproduce
1. Register as a new user, and click on the verification email.  Ensure the "You can start your   IFRC Go experience here" link goes to go.ifrc.org/login
2. Request a password reset via forgot password link.  Check image.
3. Look at email notifications and ensure they are correct.

## Expected behaviour
Production should never refer a user to the staging site (and vice versa) - whether by hyperlinks in emails or by hyperlinks in code.

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
Affects any users registering as new users or receiving emails from GO.

## Is there a workaround?
Users can navigate to correct URL but only if they know what that is.

**Comment by nanometrenat** [comment]
NOTE:  I will need your advice re how to test this in Staging, as currently emails from Staging don't come through.  We may need to use peer review approach rather than full testing (for the email aspects anyway)

**Comment by GregoryHorvath** [comment]
> 2. ...IFRC logo...The image should instead come from a Production URL...

@szabozoltan69 explained to me once why he explicitly used the staging URL for the logo instead of the production one, to be totally honest I can't remember the reason sadly, but I believe this could be changed with no problem.
It should be easy to change these into using some ENV variables instead anyway, as you said.

> I will need your advice re how to test this in Staging, as currently emails from Staging don't come through. We may need to use peer review approach rather than full testing (for the email aspects anyway)

If I don't find any other way I'll try to manually send some e-mails using local code and using ENV variables from the staging after the above changes are done.

**Comment by szabozoltan69** [comment]
>  why he explicitly used the staging URL for the logo
The reason was just for performance.
I wanted to minimize the requests for the production site. (The staging site is "underused" normally, it can tolerate some more requests.) But if you think this can be deceptive (and the PROD site can bear more usage) then let's set it to PROD.

The BASE URL nicing is a good aim. Please check whether the recent one (dsgoproxyapp or dsgocdnapi) is not checked/hardcoded literally somewhere. The URL nicing (and not using it as a string (hardcoded), but taking it from ENV variables) was aimed on other 2 github tickets: https://github.com/IFRCGo/go-api/issues/379 and its brother on frontend: https://github.com/IFRCGo/go-frontend/issues/940

**Comment by szabozoltan69** [comment]
On backend side these files contains "dsgo":
```
api/templates/admin/base_site.html
main/context_processors.py
main/frontend.py
main/runserver.sh
notifications/templates/design/head1.html
notifications/templates/includes/logo.html
notifications/templates/registration/success.html
```
Two important checks are these, they should be changed:
main/context_processors.py:
 'IS_STAGING': True if settings.PRODUCTION_URL == 'dsgocdnapi.azureedge.net' else False,

main/runserver.sh:
 if [ "$API_FQDN"x = prddsgocdnapi.azureedge.netx ]; then

**Comment by nanometrenat** [comment]
> > why he explicitly used the staging URL for the logo
> 
> The reason was just for performance.
> Normally the src of the logo image is not explored from the email html source (except some curious eyes :-) ). I wanted to minimize the requests for the production site, because this logo is on each notification. (The staging site is "underused" normally, it can tolerate some more requests.) But if you think this can be deceptive (and the PROD site can bear more usage) then let's set it to PROD.

OK understood, the imageURL was the least important part (you are right, my eyes were too curious!)  And mostly the logo image doesn't change - but I know we have a logo upgrade coming up so we will have to be careful with that :)

So, given the above info, the most important thing to fix is part 1 re user registrations as that is confusing people.

Then part 3 re email links because again this will streamline the user experience (and also there is some thought that might be contributing to Google thinking some links are suspicious).

I'm OK either way re Part 2 - it's fine if you think it's best the images stay where they are.

THANKS!

**Comment by szabozoltan69** [comment]
Not at all! :-) 
Now in the code there is no hardcoded "dsgo" in email templates (except the logo).
I deploy it and make a test (in 15 mins)...

**Comment by szabozoltan69** [comment]
Now the password recovery email links to nice URL (on PROD).
Also changed to the nice URL the "start your IFRC GO experience" link in registration emails. :-)
(Logo remained the one from staging).

(There are some users, who are is_active, after the latest registration_pending record, so it shows that – except some usertons - the registration was not impossible even in the last days.)

If you want to change the logo URL to prod, no obstacle. On both places there are the logos:
https://dsgoproxyapp.azurewebsites.net/assets/graphics/layout/logo300.png
https://prddsgoproxyapp.azurewebsites.net/assets/graphics/layout/logo300.png :-)

**Comment by szabozoltan69** [comment]
So, by now, we can close this issue, if you agree (and tested).

**Comment by nanometrenat** [comment]
OMG and on your last day too!  Hugest of thanks to you for all this.  Best wishes from us

**Comment by nanometrenat** [comment]
@GregoryHorvath @szabozoltan69 unfortunately the fix for 1 was unsuccessful in Production.
The email I received when registering as a new user sent me to https://prddsgocdnapi.azureedge.net/verify_email/

BUT then on that page the 'You can start your IFRC GO experience here' linked only to
**`https://login/`**
(i.e. is now missing the domain completely, so user has no host to resolve)

To be honest in this particular instance it's still probably no worse than sending people to the wrong site - however we should fix it asap so that users who confirm registration can go directly to GO rather than being linked to nowhere.

Thanks a lot!

**Comment by szabozoltan69** [comment]
Ok, I'll check it. Somehow that needed variable (frontend_url) is not visible in that template... Sorry for the "early happyness".

**Comment by nanometrenat** [comment]
FYI I only just saw the Teams question - apols - for clarification, point # 1 relates to a PAGE on GO, not to an email.  It's the https://prddsgocdnapi.azureedge.net/verify_email/ page that was pointing to Dev before, and now has no domain.  Thanks all!

**Comment by szabozoltan69** [comment]
Dear @nanometrenat – plese give one more test to the registration process on PROD. (Last time I've forgotten to change both kind of "*success.html" templates. (https://github.com/IFRCGo/go-api/commit/adaa8d44204859db22ca5903ca58f36d6c6ff08f – later I fixed the typo "frontent")

(Now I used a better tracking method for the fixing – via the "shell" possibility of the django framework.)

**Comment by nanometrenat** [comment]
Sorry to report @szabozoltan69 but now I'm getting `Page not found The requested page does not exist or may have been removed.` for https://go.ifrc.org/verify_email/?token=cgjIMnKLw6oCdgui0qmKnfhiz4U17swP&user=natalieifrcrego
(this was a new user with an IFRC email address).  User therefore remains inactive even after I clicked on the link in the verification email.

**Comment by szabozoltan69** [comment]
Oh, yes, thanks @nanometrenat – I went too far with forcing the "nice frontend". It is a link to BACKEND. If I wrote in the "admin" word after go, it was correct, and took me to the (backend) web page:

It is a great day!
You’ve validated your email address and your IFRC GO account is now approved.
If you do experience any problems, please contact im@ifrc.org.
You can start your IFRC GO experience [here](https://go.ifrc.org/login).
Thank you,
IFRC Go

(This is a once usable link, so you will not be able to try it again with that token.)
Now I fix it and point to backend... Sorry for this bad (Sunday) job...

**Comment by szabozoltan69** [comment]
Hopefully now it's ready...

**Comment by nanometrenat** [comment]
Thanks @szabozoltan69 I have tested two scenarios and am pleased to confirm both pass in Production - thank you.

1. with a National Society user that requires two verification emails:
* First email to user has correct URL to verify address:  https://goadmin.ifrc.org/verify_email/?token=xxx&user=yyy
* Email to verifiers has correct URL for them to verify the user:  https://goadmin.ifrc.org/validate_user/?token=xxx&user=yyy
* Email to user to confirm they have been validated (with wording you can start your IFRC GO experience here) has correct URL:  https://go.ifrc.org/login

2. with an IFRC user:
* the email to user has correct URL https://goadmin.ifrc.org/verify_email/?token=xxx&user=yyy
* the page shown at the above URL (with the wording you can start your IFRC GO Experience here) correctly links to https://go.ifrc.org/login

THANK YOU!!!
