### ISSUE TITLE
[PROD] Display change RR to Rapid Response in Deployments section and include in calculation

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#965]
Logged on behalf of Sune

## Issue
Recently a new category of deployment was added - 'Rapid Response'.  Think it was via this change (not via a ticket):  https://github.com/IFRCGo/go-api/pull/590/commits/f5d16f41586f808b9a175ca2a9e8199950c15274#diff-cee64f30dcc9faf89588eda83273ec9a

1. On the front end this shows in the 'type' column as 'RR'.  This should show 'Rapid Response' NOT RR (It's fine for Rapid Response to be split across two lines).
2. In the Totals for deployed personnel, Rapid Response deployments are not included but should be.
3. 'Deployed FACTS' Label to be changed to 'Deployed Rapid Response' on Deployments page

## Steps to reproduce
1. Go to https://go.ifrc.org/deployments and look in Type column.
NB This data is also shown in other places e.g. https://go.ifrc.org/deployments/personnel/all and in the Emergencies page https://go.ifrc.org/emergencies/3972#details - the display should be updated in all pages where a deployments table is shown.
This is a display issue only, but it is important to use the correct terminology.
2. Where deployed personnel are totalled, these totals should include Rapid Response deployments in all the places where FACT is currently included.  e.g. the box for Coronavirus in Highlighted Operations on homepage and regional page currently shows 0 deployed surge personnel, even though Rapid Response personnel are currently deployed.
3. Go to https://go.ifrc.org/deployments - the top square box should include total of FACT+Rapid Response (not just fact and not just Rapid Response - as Rapid Response is the replacement terminology for FACT).  And label change needed as noted above.

**Comment by nanometrenat** [comment]
Thanks, checked in Staging and Rapid Response is now shown in places 1 & 3 above, and the calculated totals include Rapid Response as well as FACT.   Good to go to Production :)

**Comment by teklal** [comment]
Double-checked this, and as @nanometrenat said, Raid Response works in places 1&3 now as should.

One thing I noticed, where this is not yet included is the filtering by type in the Surge Alerts section. In the backend there is the option of choosing Rapid Response for the Alert Type but on the frontend it does not show as one of the options in the dropdown. 

![image](https://user-images.githubusercontent.com/52411237/76871186-0ac9ad00-686b-11ea-9fab-78cb1c18f4e9.png)

![image](https://user-images.githubusercontent.com/52411237/76871221-174e0580-686b-11ea-9497-397ba9e3aa86.png)

Not sure how much this filtering is used as this has not been noticed before so I wouldn't let this particular issue keep from pushing to production. 

Currently the Type does not show at all on the frontend on the alerts and I'll have to check if the filtering even works for the other types so this is worth logging on a separate ticket - I'll do that.

**Comment by GregoryHorvath** [comment]
@teklal Nice catch, it's really missing from the Types list! On it, should be a quick fix.

**Comment by teklal** [comment]
Thanks for getting on it so fast @GregoryHorvath  !

Another thing I noticed but forgot to type while I was typing the other things (too much typing haha) is that re Nat's original ticket, for the third point, i.e. the deployments page and all additions, Rapid Response does not replace only FACT but also RDRT, so all of these should be summed and there should be only one "Deployed Rapid Respinse" box on the deployments page (combining the two boxes highlighted in the screenshot) 

![image](https://user-images.githubusercontent.com/52411237/76875016-4450e700-6870-11ea-8892-9e2b58f6a850.png)

Happy to explain better if needed!

**Comment by GregoryHorvath** [comment]
@teklal Made a PR for this also. Set @batpad as the approver for both.

**Comment by teklal** [comment]
Thanks @GregoryHorvath !

While testing this I just discovered a new location where Rapid Response needs to be added to (sorry!)

On an Emergency page that has deployments associated with it, there is a section as below (this one is from https://dsgoproxyapp.azurewebsites.net/emergencies/3786#details):
![image](https://user-images.githubusercontent.com/52411237/76947207-91cb6380-6905-11ea-98d2-6c0f13789cdb.png)

There the Type (filter) is still lacking Rapid Response, similarly as for the alerts.

**Comment by teklal** [comment]
@batpad @GregoryHorvath Just checking about my most recent comment above: should I put that in a new open ticket or re-open this one as it doesn't seem to be on staging yet? Sorry for the late catch on those additional sections where Rapid Response needs to be added.

Also to clarify it's the type drop-down/filter where it needs to be added to.

**Comment by batpad** [comment]
@teklal apologies - issue was closed by accident due to the auto-closing feature of Github. Re-opening.

@GregoryHorvath would you be able to take care of this?

**Comment by teklal** [comment]
Hey @batpad @GregoryHorvath , in production now on the Deployments page the Deployed Rapid Response shows dashes instead of the number of deployed personnel. I went back to staging to test this and there it works.
![image](https://user-images.githubusercontent.com/52411237/77050591-4a5adb00-69ca-11ea-9af8-e26a50cd455d.png)

Should I log a separate ticket for this?

**Comment by GregoryHorvath** [comment]
> Hey @batpad @GregoryHorvath , in production now on the Deployments page the Deployed Rapid Response shows dashes instead of the number of deployed personnel. I went back to staging to test this and there it works.
> ![image](https://user-images.githubusercontent.com/52411237/77050591-4a5adb00-69ca-11ea-9af8-e26a50cd455d.png)
> 
> Should I log a separate ticket for this?

@teklal I'm on it. Basically what seems to be happening, since that number now includes FACT, RR, and RDRT if any of those are null it handles like if all were null.
