### ISSUE TITLE
[Maint] Remove Admin link from surge email notification

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#966]
## Request
Please remove the `| GO Admin` link from surge *alert* and surge *deployment* notification emails.

Currently, for surge alert notifications, after the description there is a 'Read more' link to the emergency page (which we need to keep), then a link to the edit surge alert page on GO Admin (which is the link we need to remove - both the text and the hyperlink should be deleted).

## Background as to reason
Some users are reporting that Google is treating their Surge email notifications as having 'suspicious links'.  This may be due to differences in Certificate setup between go.ifrc.org and goadmin.ifrc.org, or to do with the info mentioned in SRV-16556.  It was initially thought to perhaps be to do with #958 but that has now been ruled out.

As only a handful of people have permission to edit surge alerts (and they don't need to receive the link by email) the best thing to do is to just delete the link altogether.

Suggest doing this at same time as changing email logos via #929

**Comment by GregoryHorvath** [comment]
Fixed in: https://github.com/IFRCGo/go-api/pull/612, https://github.com/IFRCGo/go-api/pull/612/commits/fed79d54115d57e733b940c78792e662c289e2a0

**Comment by nanometrenat** [comment]
This change was deployed on 27 Feb, admin link no longer appears in surge notifications - therefore closing issue, thanks a lot
