### ISSUE TITLE
[PROD] Appeals documents ingest not picking up all documents

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#968]
## Issue
It seems that the Appeals Documents scraper is not ingesting all appeal documents.  e.g. the recent Operations Update for MDR00005 that appears on https://www.ifrc.org/en/publications-and-reports/appeals/?ac=MDR00005&at=0&c=&co=&dt=1&f=&re=&t=&ti=&zo= was not pulled through, but the Cronjob is not reporting errors.  I have manually uploaded this particular document for now.

## Expected behaviour
From Greg: the Appeal docs ingestion does:
1. Collects the Appeals saved in the database for the last 3 months.
2. Gets the Appeal documents list from here: https://www.ifrc.org/en/publications-and-reports/appeals/?ac=MDRMV003&at=0&c=&co=&dt=1&f=&re=&t=&ti=&zo= where the bold part is the changing parameter (appeal code). If there was a --fullscan flag set when running the script is gets all Appeals, but it's never used at the moment.
3. Creates an AppealDocument record (created at, name, document url, appeal [code])

If there is no further filtering I would've expected the OU to have been pulled through.

Workaround is to monitor and manually upload.

**Comment by GregoryHorvath** [comment]
Some updates for this:
1. Collects the Appeals which have an **'End date'** set in the database for **the last 3 months** and **if the Appeals don't have any documents yet**.
2. Zoltan confirmed this was only used when an environment needed a full ingestion, like an initial one for example.

So I'm pretty sure it's not pulling that document through because of the second part of the 1. Should I change it that it will only have the last 3 months check, @nanometrenat?

**Comment by nanometrenat** [comment]
Thank you, it makes sense to me that it adds documents if the documents don't already exist on GO.  BUT I think we really need to test this somehow (even if locally) to make sure that it doesn't do unexpected things (e.g. create duplicates of documents that already exist on an appeal etc.)  @GregoryHorvath @batpad are you able to confirm that everything will be OK in that respect?  Thanks a lot!

**Comment by batpad** [comment]
The code here should prevent duplicate appeal docs from being ingested: https://github.com/IFRCGo/go-api/blob/8ccfdb63db2d55a704dd18349285f6e4fabbd463/api/management/commands/ingest_appeal_docs.py#L107 - @GregoryHorvath it would be great to give this a try locally though just to be double sure nothing unexpected happens.

**Comment by GregoryHorvath** [comment]
> The code here should prevent duplicate appeal docs from being ingested: https://github.com/IFRCGo/go-api/blob/8ccfdb63db2d55a704dd18349285f6e4fabbd463/api/management/commands/ingest_appeal_docs.py#L107 - @GregoryHorvath it would be great to give this a try locally though just to be double sure nothing unexpected happens.

Sure I've tested it locally but we could test this on staging too.

**Comment by nanometrenat** [comment]
There were 3 appeal docs added to IFRC website last night for MDR00005 and 1 this morning for MDRAF005.
None of them pulled through to Prod (both these appeals already existed in Prod, and had previous documents linked)
However all 4 of them successfully pulled through to Staging (thank you):
ingest_appeal_docs at Feb. 18, 2020, 4:18 p.m. shows "Done ingesting appeals_docs on url https://www.ifrc.org/en/publications-and-reports/appeals/, 3 appeal document(s) were created, 376 already exist, 0 not found" and similarly at Feb. 19, 2020, 9:18 a.m. it shows Done ingesting appeals_docs on url https://www.ifrc.org/en/publications-and-reports/appeals/, 1 appeal document(s) were created, 379 already exist, 0 not found
Documents showing correctly against the above appeals in Staging.

Still to test:  what happens if a Appeal doc has already been added manually

**Comment by nanometrenat** [comment]
Verified that the matching is based on appeal doc URL.  Manually manipulated 4 docs as follows, when the job next ran it picked up 3 docs as being new and needing to be added.

- MDRAF005 - Operations Update 4 - changed name to add "Test"  => result: no change, no new doc added _- PASS_
- MDR00005 - Appel d'urgence révisé #1 - changed Adore URL to add "4" on the end => result: doc added again with same name and correct URL (i.e. looks like a duplicate but is correct, the original doc with incorrect URL needs to be manually deleted) _- PASS_
- MDR00005 - Emergency appeal revision #1 Russian - deleted the Adore URL and uploaded a doc instead (so new URL is http://dsgofilestorage.blob.core.windows.net/api/appeals/MDR00005/MDR00005REA_Rus.pdf) => result: doc added again with same name and correct URL (i.e. looks like a duplicate but is correct, the original doc with file URL rather than Adore URL needs to be manually deleted) _- PASS_
- MDRLA006 - DREF Operation Update - deleted it completely => doc added again _- PASS_

Still need to check why one of the items on the list of recently-added appeal docs Greg sent through has a blank URL.

**Comment by nanometrenat** [comment]
Suspect the blank one was manually-added as it has a specific time of day (as opposed to others from the scraper, which have midnight as the time.  Therefore ignoring this one, thanks.
5951 | 2020-01-08 09:17:54+00 | Emergency Appeal                                     |          |                                                   |      3283

**Comment by GregoryHorvath** [comment]
> Suspect the blank one was manually-added as it has a specific time of day (as opposed to others from the scraper, which have midnight as the time. Therefore ignoring this one, thanks.
> 5951 | 2020-01-08 09:17:54+00 | Emergency Appeal | | | 3283

Based on this how **should** it work? If there was an Appeal Document with the same name, delete the existing one and pull the "new" one through, or should we keep both (as it is now based on how it looks on staging)?

**Comment by nanometrenat** [comment]
Hi @GregoryHorvath I think the current way of working is good.  Old documents should not be deleted by the scraper - fine to keep both.  If it's easy to We can manually address any historic issues where docs were manually added because scraper wasn't picking them up.  This should be a one-off process though, as once the new code is in Production there shouldn't be new duplicates created going forward.

**Comment by nanometrenat** [comment]
Change released to Prod just now :)

**Comment by nanometrenat** [comment]
Working well apart from Donor Response docs, thanks a lot.  I have logged #986 to track the Donor Response doc work, so will close this ticket now.
