### ISSUE TITLE
Export file enhancement - dates in format that can be opened by Excel

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#969]
Noted by Sune
xref #553 re Exporting tables

At the moment when GO tables are exported (e.g. emergencies, surge alerts etc.) the date fields are in T Z format (i.e. include time and timezone information) as per ISO_8601 e.g. 2020-02-06T12:45:13.486476Z

The problem is that when the file is opened in Excel, Excel does not recognise these fields as dates, so users have to do manual formulae e.g. =DATEVALUE(LEFT(A1,10)) to convert it into a date Excel recognises.

This ticket is to figure out a plan for ensuring Export files can easily be opened in Excel (without subsequent manipulation, and while not causing any time zone conversion issues)

https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

**Comment by batpad** [comment]
Thanks for the ticket @nanometrenat, this makes a lot of sense and should be relatively straightforward.
