### ISSUE TITLE
PER Refactor Retrospective

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#971]
## PER Refactor Retrospective

In November 2019, the DevSeed team noticed a nontrivial amount of tickets being filed to fix features relating PER. As part of an effort to contribute to a solution that would drive at the root of these bugs, we published a paper reviewing the code practices that should be changed to facilitate a more resilient product. 

[PER Review.pdf](https://github.com/IFRCGo/go-frontend/files/4194986/PER.Review.pdf)

In response to this document, we were asked to spend some time addressing some of the solutions listed in the review. The time we had budgeted for this refactor was not enough to offer comprehensive solutions. It did result in a [PR](https://github.com/IFRCGo/go-frontend/pull/919/files) that removed 2,600 lines of code, in addition to some [updates](https://github.com/IFRCGo/go-frontend/pull/941) to the PER map that were not in the original scope of our contract, but added perk of our refactor.

The refactor [PR](https://github.com/IFRCGo/go-frontend/pull/919/files) had two bugs:
- [language mix-up](https://github.com/IFRCGo/go-frontend/pull/952)
- [misplaced conditional](https://github.com/IFRCGo/go-frontend/pull/948)

These were caught and fixed immediately upon added into staging.

In addition to these fixes, we addressed preexisting bugs rooted in unrefactored code that surfaced during testing. These included:
- [text updates](https://github.com/IFRCGo/go-frontend/pull/949)
- [country list filter](https://github.com/IFRCGo/go-frontend/pull/945)
- [error handler for unrelated portion of PER](https://github.com/IFRCGo/go-frontend/pull/944)
- [hotfixes for per issues in production](https://github.com/IFRCGo/go-frontend/pull/960)
- [additional fallbacks](https://github.com/IFRCGo/go-frontend/pull/962)

**Comment by nanometrenat** [comment]
Closing as discussed with @batpad - thanks a lot for this documentation.
