### ISSUE TITLE
[Staging] PER Forms being submitted with country_id as null

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#973]
## Issue

It seems like it is possible to submit a PER form such that the country id gets submitted as `null`. The steps to reproduce seem pretty reliable / am able to reproduce consistently.

## Steps to reproduce

 - Go to Account Page -> PER Forms.
 - Select a National Society from the dropdown
 - Select a Form to to create, eg. Area 1: Policy and Standards
 - Fill in form and submit

**Expected**: Form to be submitted with the correct country_id for the National Society chosen by the user.

**Actual**: The Form gets submitted to the backend with country_id as null, and the db does not validate presence of the country_id and saves the form, not associated to any country_id

Example JSON sent by the frontend when submitting a form:

```
{
	"code": "a1",
	"name": "Policy strategy form",
	"language": 1,
	"started_at": "2020-02-20 13:9:57.26+00",
	"submitted_at": "2020-02-20 13:9:57.26+00",
	"user_id": 3761,
	"ns": " - ",
	"data": [{
		"id": "a1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c0q0",
		"op": 0,
		"nt": ""
	}, {
		"id": "c0q1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c0q2",
		"op": 0,
		"nt": ""
	}, {
		"id": "c0q3",
		"op": 0,
		"nt": ""
	}, {
		"id": "c0q4",
		"op": 3,
		"nt": ""
	}, {
		"id": "c1q0",
		"op": 0,
		"nt": ""
	}, {
		"id": "c1q1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c1q2",
		"op": 0,
		"nt": ""
	}, {
		"id": "c1q3",
		"op": 3,
		"nt": ""
	}, {
		"id": "c2q0",
		"op": 0,
		"nt": ""
	}, {
		"id": "c2q1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c2q2",
		"op": 0,
		"nt": ""
	}, {
		"id": "c2q3",
		"op": 0,
		"nt": ""
	}, {
		"id": "c2q4",
		"op": 3,
		"nt": ""
	}, {
		"id": "c3q0",
		"op": 0,
		"nt": ""
	}, {
		"id": "c3q1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c3q2",
		"op": 0,
		"nt": ""
	}, {
		"id": "c3q3",
		"op": 0,
		"nt": ""
	}, {
		"id": "c3q4",
		"op": 0,
		"nt": ""
	}, {
		"id": "c3q5",
		"op": 3,
		"nt": ""
	}, {
		"id": "c4q0",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q1",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q2",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q3",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q4",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q5",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q6",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q7",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q8",
		"op": 0,
		"nt": ""
	}, {
		"id": "c4q9",
		"op": 4,
		"nt": ""
	}]
}
```

Relevant code in the backend that sets country_id to null if it is not sent: https://github.com/IFRCGo/go-api/blob/master/per/views.py#L91

And then one can see rows saved in the database with country_id set to `null`:

```
 id | code |         name         | language | user_id |            created_at            |            updated_at            | finalized | ip_address | ns  | comment |             ended_at             |            started_at            |           submitted_at           |              unique_id               | validated | country_id 
----+------+----------------------+----------+---------+----------------------------------+----------------------------------+-----------+------------+-----+---------+----------------------------------+----------------------------------+----------------------------------+--------------------------------------+-----------+------------
  1 | A1   | Nemo                 |        1 |         | 2019-06-29 15:25:16.824798+05:30 | 2019-06-29 15:25:16.890638+05:30 | f         | 127.0.0.1  |     |         | 2019-06-29 15:25:16.816839+05:30 | 2019-04-11 17:12:22.278796+05:30 | 2019-04-11 15:12:52.278796+05:30 | db825391-0ed6-4fcf-a0bd-bd888504b10d | f         |           
  2 | a1   | Policy strategy form |        1 |    3761 | 2020-02-20 12:27:31.795573+05:30 | 2020-02-20 12:27:31.862298+05:30 | f         | 127.0.0.1  |  -  |         | 2020-02-20 12:27:31.790986+05:30 | 2020-02-20 17:57:31.767+05:30    | 2020-02-20 17:57:31.767+05:30    | 8b02e16d-849b-4b1b-8eac-bb7a2ea16d09 | f         |           
  3 | a1   | Policy strategy form |        1 |    3761 | 2020-02-20 12:33:18.347644+05:30 | 2020-02-20 12:33:18.413967+05:30 | f         | 127.0.0.1  |  -  |         | 2020-02-20 12:33:18.344768+05:30 | 2020-02-20 18:03:18.31+05:30     | 2020-02-20 18:03:18.31+05:30     | 686f980c-7624-4202-bda4-95c1c5a40fa3 | f         |           
  4 | a1   | Policy strategy form |        1 |    3761 | 2020-02-20 12:39:51.979437+05:30 | 2020-02-20 12:39:51.985899+05:30 | f         | 127.0.0.1  |  -  |         | 2020-02-20 12:39:51.975309+05:30 | 2020-02-20 18:09:51.95+05:30     | 2020-02-20 18:09:51.95+05:30     | ac6f7455-6eaf-4b9b-b2c2-4b6c7aab436a | f         |
```

Two things here:

 - I'm not sure why the frontend isn't sending the country_id correctly. Am going to dig into that more.
 - Secondly, is there ever a case where we'd want to allow submission of a PER form without a valid country_id? If not, we should also enforce this validation on the backend to not end up with inconsistent data.

@necoline do you have any clues /' sense as to why the forms are not sending the country_id? I'll do some digging as well.

cc @nanometrenat @teklal 

## Expected behaviour
The PER Form should submit the country_id as expected based on the country / national society selected from the drop-down.

## Criticality/Urgency
This seems pretty critical / related to the PER bugs we are seeing, I will be looking at this as a matter of priority.

**Comment by batpad** [comment]
Quick note: Logged out the value of `this.props.nationalSociety` here and it seems fine: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/per-forms/per-form.js#L40

**Comment by batpad** [comment]
Seems like the problem is this line:

https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/per-forms/per-form.js#L182

It is:

```
request.country_id = this.country_id === undefined ? this.props.ns : request.country_id;
```

I believe this should be:

```
request.country_id = this.country_id === undefined ? this.unifiedNs : request.country_id;
```

Will test a bit and confirm that this associates the country_id correctly on new forms.

**Comment by nanometrenat** [comment]
Thanks @batpad you are right that there should ALWAYS be a country associated with a PER form.  Thanks for investigating this.

**Comment by batpad** [comment]
I have deployed a fix for this on staging.

It should now always correctly associate a country id with the form submission.

cc @teklal @nanometrenat

**Comment by batpad** [comment]
@teklal if you can confirm this is fixed, this should be good to close.

**Comment by batpad** [comment]
This was fixed a while ago before we had the current process and we forgot to close. Closing now.
