### ISSUE TITLE
[Staging] PER: stop benchmarks from being mandatory

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#974]
## Issue / Expected behaviour
As per request from the PER team, the _benchmarks_ in a PER form should not be mandatory **but** the _components_ should be.

So within a form that is filled by a user (Account -> PER forms -> Choose National Society from dropdown -> click on one of the "Area" forms), the benchmarks should not be mandatory fields (in the screenshot below 2.X) but the final box within a component ("Component Y performance") should remain mandatory.

![image](https://user-images.githubusercontent.com/52411237/74917911-95cc9a00-53c8-11ea-9779-2a20bdcf8861.png)

## Steps to reproduce
This concerns the forms highlighted below as each of them contains components and benchmarks.

![image](https://user-images.githubusercontent.com/52411237/74843481-42a50980-532c-11ea-836e-5037bf63e994.png)

## Criticality/Urgency
As some historical PER data, that is to be migrated to GO, does not have all the benchmarks, this is a blocker for the upload of prior PER data.

**Comment by batpad** [comment]
On the frontend, we need to:

 - Modify the `checkFormFilled` method to allow the `Benchmark Status` fields to be optional - https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/per-forms/per-form.js#L231. There's probably a few ways to do this - ideally would be to add another property in the form data to specify `required` as either `True` or `False`. An alternative would be to always allow Yes / No questions to be optional. @necoline would be great to quickly get your thoughts on best approach here.

On the backend:
 - Around here: https://github.com/IFRCGo/go-api/blob/master/per/views.py#L112 - ideally we would just not be sending values for things that are not filled in for the frontend, so instances of FormData for questions not filled in would just not exist.

We just need to test thoroughly that if the backend does not contain data for some questions for a form, all aspects of the frontend work fine - this is a bit hard to tell for certain without some more digging and testing, but I will start working on making the Benchmark Status questions optional on the frontend, not save those answers to the db, and then do a thorough check of what might break as a consequence.

**Comment by nanometrenat** [comment]
@batpad advises that this will take a significant chunk more time to build.

So for now, this ticket is going ON HOLD, and I'm assigning @LukeCaley to confirm whether to proceed or whether to close ticket and leave all as mandatory

**Comment by nanometrenat** [comment]
This change request is CANCELLED - @LukeCaley has agreed with PER team that existing rules will stay as-is (i.e. all components and benchmarks are mandatory).

thanks for investigating and working on this @batpad but no code check in required.  Closing ticket.
