### ISSUE TITLE
End-to-end Testing with Cypress

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#975]
# End-to-End Testing

End-to-end testing is an approach to QA that checks to ensure that an application is behaving as expect from start to finish. Unlike unit testing or integration testing, end-to-end focuses on functionality from the perspective of a user. Similar to our current manual testing process, a testing library like Cypress with goes through an application and simulate user actions like clicking buttons and navigating through pages and logs any errors that are created by those interactions. 

![cypress](https://user-images.githubusercontent.com/20410256/75042976-4ac88a80-548d-11ea-9a52-2368290c7e2f.gif)

IFRC Go stands to benefit from implementing end-to-end testing in a number of ways:
- Save time for the QA team by automating many of the testing tasks they complete on a regular basis
- Improve confidence that code works as expected before it leaves the development environment
- Increases logging and documentation around failures so we have a better understanding of where and why something went wrong
- Reduces time spent debugging issues because problems are caught closer to the time of their creation

## Implementation

Initial set up and writing of these test will be nontrivial. If we want to have complete test coverage, it will require time to write a test for every possible user interaction. When considering different approaches to implementation a few things to consider include:

- Many of our bugs arise from old code that is too expensive to refactor but too buggy to leave alone. 
- Manual testing occurs on interactions that we think to test often leaving out use cases that escape our awareness or fall outside our expectations for user workflows, leaving room for a mechanism to employ comprehensive testing.
- There is likely a number of bugs in existing code that we are unaware of because our attention in on new features. We could benefit from a testing suit that covers all the features that users depend on.

Some testing approaches include

**Testing the whole app** : This would require a significant chunk of time to set up the tests and write tests for the whole app. It is a feasible goal that would serve developers and users immediately upon implementation and into the foreseeable future.  

**Testing Critical Features** : We might prioritize the testing of features or workflows that have had a lot of recent changes or have historically produced a number of bugs.

**Testing of new features** : We might do the initial setup of Cypress and then write tests as we create new features. The plus side of this is that the initial overhead is minimal, the scope is well defined and easy to budget time for. The drawback is that it does not set aside time to test existing features meaning that regression testing would not be available

**Links to documentation**
https://www.cypress.io/

**Comment by nanometrenat** [comment]
Deployment process ticket is #859

**Comment by nanometrenat** [comment]
Closing this ticket as agreed on GO call.

It is great to have this documentation for future reference, however further QA process conversations are required on the business side before we look at implementing any specific tool.
