### ISSUE TITLE
[PROD] Cyprus appeal won't link to a country

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#976]
## Issue
https://go.ifrc.org/appeals/all - the DREF for MDRCY001 | Cyprus - Population Movement does not have a country linked.  It doesn't have an emergency page so correctly doesn't have the emergency link - however it should be possible for it to be linked to a country anyway!

I have manually linked this DREF to Cyprus in the Admin UI, and it shows as linked on the front end - but then when I check again later it is no longer linked, so it looks like a regular job overwrites it.

I have noticed that the iso code for Cyprus is capitalised in the database (CY) whereas almost all other countries have lower case iso codes, so not sure if that could be part of the problem?  I think that iso codes are case sensitive (based on https://github.com/IFRCGo/go-api/blob/master/api/management/commands/ingest_appeals.py#L143).

I just updated Cyprus' iso code to lower case via admin UI to see if this helps.

(NB in order to save this change I also had to input an ISO3 code, which other countries don't yet have).  Will monitor.

## Related feature
https://github.com/IFRCGo/go-frontend/issues/938

## Impact
One DREF operation.  Henk chasing.

## Is there a workaround?
No workaround as updated

**Comment by nanometrenat** [comment]
NOTE the ISO code is also capitalised in the Front End code (my change above is ONLY for the db)
https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/utils/field-report-constants.js#L232

**Comment by nanometrenat** [comment]
Just checked again and this DREF operation is still linked to country = Cyprus, so think the immediate issue is resolved.

Leaving ticket open though so we can check data/config for other countries (db and code)

**Comment by nanometrenat** [comment]
NB just spotted that San Marino doesn't have a region in the db (should be Europe, and NS name is Red Cross of the Republic of San Marino).  So it doesn't appear on the regional page (but is on IFRC NS contact lists)

**Comment by geohacker** [comment]
Update - with https://github.com/IFRCGo/go-frontend/pull/1514 this should no longer be an issue. Once the API and the front-end changes are deployed, they will use the iso codes from a single source.

**Comment by batpad** [comment]
@jhenshall can you confirm that the issues of Appeals linking with Countries seem to now all be fixed?

**Comment by jhenshall** [comment]
Initial checks for the country linking of appeals is all good, however, this Cyprus one does seem a bit weird. It is [linked to country](https://go.ifrc.org/appeals/all?record=3229) but but doesn't appear on [Cyprus page](https://go.ifrc.org/emergencies/all?country=228). Having looked at API, is this because it `needs_confrimation`=`TRUE`?

**Comment by nanometrenat** [comment]
(logged into github for the first time in a while and saw this notification!)

The "Needs Confirmation" check of appeals data is meant to be one of the daily data checks that Tekla used to do that I think was to be taken on by @tovari .  There was a specific page in the Teams wiki for regular checks - but the daily checks may perhaps only be picking up recent items rather than looking back historically as well?

Also I think there were a handful of exceptions Tekla knew about that were kept hidden for a reason (hopefully documented also??)  Cheeeeeers!

**Comment by jhenshall** [comment]
This specific issue is definitely fixed. We've also made the broader geo API changes and converted all ISO codes to uppercase - checks do not reveal any issues, so closing this ticket.
