### ISSUE TITLE
[Staging] PER: remove total number of components and "component" from 

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#981]
## Issue
Not an issue per se but an improvement/change request resulting from discussion with PER team.
To avoid confusion around the number of components/sub-components the *PER components and sub-component results" box on a country's Preparedness tab (snapshot below), the highlighted part should be removed i.e. only show the big red number and also remove the text “component”.

![image](https://user-images.githubusercontent.com/52411237/75716295-91ad5000-5cd7-11ea-8294-46e7f28b4605.png)

This box will appear on a country's/National Society's Preparedness tab if there have been form(s) filled and submitted for that NS.

## Expected behaviour
Box should only show the number of components/sub-components that have been assessed as high-performing/exists/needs improvement/... not the total number of components or word "components"

## Criticality/Urgency
Part of PER improvements and requested by PER team. It is known that PER consists of 37 components, so differing numbers in the box may cause unnecessary confusion.

**Comment by nanometrenat** [comment]
Closing ticket as advised by Stephanie - this old PER is either not relevant any more, or solved because of the new forms/NS preparedness section.  There are other Github tickets related to the new development.
