### ISSUE TITLE
[Staging] PER: Add option to set PER phase in the PER overview form

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#982]
## Issue (functionality enhancement request)
Currently the PER phase is set by logging into the backend. This however does not make much sense as the rest of PER information is filled through forms in the frontend. This is also one of the more important pieces of information as it is the phase that is displayed on the map on the global Preparedness page.

Each NS is able to submit an overview form even if they would not be in the process at a phase of filling the rest of the forms. Hence it is requested to move the selection of phase to the Overview form.

Currently the Overview form looks like the following, and the proposed addition would be placed where the red line is:
![image](https://user-images.githubusercontent.com/52411237/75719303-31b9a800-5cdd-11ea-9cb8-3bfa135564e6.png)

To be added a dropdown "Current PER phase" with the options for the phase (almost) as currently on backend:
![image](https://user-images.githubusercontent.com/52411237/75719053-b8ba5080-5cdc-11ea-92c7-5e823610d4bf.png)

"Baseline" should be removed from the dropdown and the options should be the same as the wording for the phases on the map:
![image](https://user-images.githubusercontent.com/52411237/75719791-0c796980-5cde-11ea-9b50-bb333cf00586.png)

## Steps to reproduce
The Overview form is accessed by logging in and navigating to the Account page, PER forms tab and clicking on the "Overview" button after having selected a NS from the dropdown.

## Related feature
Related to PER refactor and usability fixes

## Criticality/Urgency
This will be a big improvement in the usability as most of the PER functionality users will not be otherwise familiar with the backend of GO and hence being able to set the phase on the frontend will be much easier and less intimidating.

**Comment by batpad** [comment]
TODO:

 - [ ] Add Select dropdown to select Phase in Overview Form
 - [ ] Get API to save Phase data based on form input: https://github.com/IFRCGo/go-api/blob/master/per/models.py#L26
 - [ ] Add phase data to API called when loading Overview Form
 - [ ] Handle populating of Phase correctly on frontend when loading Overview Form
 - [ ] Remove 'Baseline' from list of options for Phases, rename options as per above.

"Removing" the `Baseline` option seems slightly tricky if we were to remove it from the backend and possibly need to change existing data.

**Comment by tovari** [comment]
@marcovvu1 is preparing requirements for a new overview page, which will include this functionality.
