### ISSUE TITLE
[PROD] Additional IFRC countries - Bhutan and Marshall Islands

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#983]
## Issue
The Bhutan Red Cross Society and the Marshall Islands Red Cross Society were admitted on 5 December 2019 as 191st and 192nd full members of the IFRC. This was decided unanimously at the 22nd Session of the IFRC General Assembly that is currently underway in Geneva.

We therefore need to make sure that Bhutan RCS and Marshall Islands RCS are correctly represented on GO.  Iso codes are BT and MH

I know that I can make them appear in certain places by going into these Countries on the back end, and selecting region = Asia Pacific.  However, I know that this won't make them show in all the places they need to be, due to the fact that some country lists are hard-coded on front end rather than pulling through from db, as documented under #938, #940 and other related issues.

## Action required
Add these two National Societies in to all places that they need to be in order for them to function as fully as the other countries that have had NSs already for a long time.  This will require both back end updates in https://goadmin.ifrc.org/api/country/234/change/ etc. and also code changes, unless 

## Testing

- all dropdowns (front end, back end) including Field Reports and Emergency pages, PER, user setup etc.
- country pages are listed in Asia Pacific region and display correctly
- all maps show these two countries correctly (from looking at tickets it seems that their centroids are already present, not sure about Admin1)
- API
- user registration process (for whitelisted URLs as per #556)
etc.

## Data
*Marshall Islands*
Society name:  Marshall Islands Red Cross Society
Iso2: mh
Iso3: mhl (you need this before you can save a country in back end - not sure whether it should be upper case or lower case?)
Society URL:  (none yet)
Email domain for whitelisting:  rmiredcross.org

*Bhutan*
Society name: Bhutan Red Cross Society
Iso2: bt
Iso3: btn
Society URL:  (none yet)
Email domain for whitelisting:  brcs.bt

(For both countries we will also need to add IFRC web URL but there is nowhere in db to put this until #922 is done to add an extra field.)

**Comment by nanometrenat** [comment]
Assigning to @GregoryHorvath as this is a Support+maintenance issue, however @batpad you may need to feed in given the other work around countries vs db!  Thanks

**Comment by GregoryHorvath** [comment]
@nanometrenat Could you please go into details where it doesn't work? I added them to some places (not deployed yet) but even without them by just changing their Region to Asia Pacific it was enough for me to work on:

- Create Field Report page (**dropdown**)
- **Map** and **Countries list** on Region - Asia Pacific page

The whitelisting of domains is done via: https://github.com/IFRCGo/go-api/commit/8134ac93fe811c57be0abb9869314f6d1bf1c960. If this needs to be pushed to production asap just notify me.

PS: I agree wholeheartedly that this needs some refactoring (among all the other hardcoded stuff). I believe the domain whitelist could be handled elsewhere too, for ex. in a table in the DB and then Admins on the Backend would be able to add them as well @batpad ?

**Comment by GregoryHorvath** [comment]
@nanometrenat The whitelisting of domains were deployed to production.

**Comment by nanometrenat** [comment]
Thanks for whitelisting.  Reopening this for the other work (some of which is database config that can be done by IM)

**Comment by LukeCaley** [comment]
@nanometrenat could you describe the database config task for @teklal to implement here?

**Comment by nanometrenat** [comment]
Simply going into the back end and editing the countries to set them up with a region and the other details above.  

> I know that I can make them appear in certain places by going into these Countries on the back end, and selecting region = Asia Pacific. 

Easy!  Over to you @teklal

**Comment by teklal** [comment]
I've done the backend edits to the countries and have checked that the two NS/countries show up as they should in the following places:

Dropdowns (frontend and backend):
- field reports
- PER
- user registration and setup
- deployments
- appeals
- emergency pages

Also checked:
- countries show up correctly under Asia Pacific region
- urls are whitelisted
- countries show on maps (there are some issues with maps not specific to just Marshall Islands, some of which have already been raised in other tickets, e.g. flatness -> not all countries showing up in the default view, and some that I'll ticket later)
