### ISSUE TITLE
[Staging] PER grey screen - Area 5 Operations Support

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#994]
## Issue
In PER Forms (accessed from Account Menu), whenever I click on "Area 5 Operations Support" for a country that hasn't yet filled out that form (e.g. Bahrain, Sweden) I get a grey screen
Uncaught TypeError: Cannot read property 'nsConsiderationHeader' of undefined

## Steps to reproduce

- Go to PER forms:  https://dsgoproxyapp.azurewebsites.net/account#per-forms
- Select country (e.g. Bahrain)
- Click Area 5 Operations Support
- Click "yes" (or no) on the first question re Epi
--> it takes you to https://dsgoproxyapp.azurewebsites.net/per-forms/operations-support/26 , where you get a grey screen
NB - if it's a country that you have NEVER been into then you have to click the radio button before you get a grey screen.  If it's a country that you HAVE been to that form for before then you get the grey screen as soon as you go into the form (this applies whether or not you .

Error message in console:  Uncaught TypeError: Cannot read property 'nsConsiderationHeader' of undefined

## Expected behaviour
Form 5 should be able to be filled out and save completely.

## Related feature
Other grey screen issues include #946 and others

## Criticality/Urgency
Critical for PER

**Comment by batpad** [comment]
@nanometrenat thank you for the catch.

The reason almost definitely seems to be some of the components on this form not having `epiComponent` data - https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/per-forms/form-data/a5/english-data.js#L510 of course, the code should not grey screen here. Digging further.

cc @necoline for visibility

**Comment by batpad** [comment]
Fixed in https://github.com/IFRCGo/go-frontend/pull/995

@nanometrenat please confirm fix on staging whenever you are able to test. Thanks again for the catch.

**Comment by nanometrenat** [comment]
Thanks @batpad confirming no more grey screen on Form 5, thanks for quick turnaround
