### ISSUE TITLE
[Staging] PER: Phase will not show on map if no Area forms have been submitted for that NS

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#996]
## Issue
At the moment the PER phase won't appear on the global Preparedness page's map if there have been no forms for Area 1 to 5 submitted for that country - even if the phase has been set on the backend and an Overview form has been submitted. 

## Steps to reproduce
Set NS PER phase on the backend for a National Society that doesn't yet have PER forms filled and submitted and then go to Preparedness tab to see the map - a dot will not appear.

I tested this for Uganda. I first set the phase on the backend - no dot on map. Then I filled and submitted an Overview form - still no dot.

## Expected behaviour
The phase should show on the map if the phase has been determined/set, irrespective of whether or not other forms have been submitted.

## Related feature
Related to general PER fix/facelift
especially:
#844 
#982 

## Criticality/Urgency
As setting the PER phase and the global map are the main information available to the public of the PER functionality, this is important to fix.

**Comment by nanometrenat** [comment]
Closing ticket as advised by Stephanie - this old PER is either not relevant any more, or solved because of the new forms/NS preparedness section.  There are other Github tickets related to the new development.
