### ISSUE TITLE
[Staging] PER: Browser tab does not say Preparedness for PER related pages

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#997]
## Issue
The text on the browser tab (at least on Google Chrome) for PER related pages, i.e.
- global preparedness tab https://dsgoproxyapp.azurewebsites.net/preparedness
- when opening a PER form from the Account page 

## Steps to reproduce
Navigate to the aforementioned pages/sections of GO and observe.

Current behaviour:
for the global preparedness tab it says IFRC GO - Home (as below)
![image](https://user-images.githubusercontent.com/52411237/76472284-6c19f800-63f5-11ea-91bb-d4e60c500b11.png)

for the PER forms it says IFRC GO - Emergencies (as below)
![image](https://user-images.githubusercontent.com/52411237/76470802-573b6580-63f1-11ea-9fa0-a81602444619.png)
![image](https://user-images.githubusercontent.com/52411237/76472427-ce72f880-63f5-11ea-8346-222ab704066c.png)

## Expected behaviour
The tab should say IFRC GO - Preparedness

## Related feature
PER facelift

## Criticality/Urgency
Not the most urgent issue.

**Comment by batpad** [comment]
This is encapsulated in #1125 . Closing here to avoid duplication.
