### ISSUE TITLE
[PROD] Link styling on COVID-19 emergency page

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#999]
## Issue

On this page: https://go.ifrc.org/emergencies/3972#additional-info - the styling of links is broken - shows with a blue underline.

This is likely due to custom global styles included in the snippet.

## Steps to reproduce

Go to https://go.ifrc.org/emergencies/3972#additional-info - see blue underline under some links, which should not be there.

## Expected behavior

Links should retain styling as rest of site.

We need to fix the CSS styles in the snippet to not globally apply styles to `a` elements on the page, rather only ones within the div that it is in or so.

Longer-term, this would be solved by having proper visual editors to add styling that won't require hacks and break the rest of the page - for now, we need to edit the CSS of the snippet to correctly namespace the custom styling for `a` elements on the page.

**Comment by nanometrenat** [comment]
The html in that particular snippet was fixed a while back - the actual fix we need to make is to have a visual editor to allow users to use GO to create the snippet content rather than having to copy and paste html in from elsewhere.
